### ISSUE TITLE
win8.1 ::1并配置了一个IPV6 DNS不返回查询结果

### ISSUE THREAD

**Issue by shuangzhijinghua** [chengr28/Pcap_DNSProxy#10]
nslookup - ::1,config里面添加了[2001:4860:4860::8888]:53,查询全部超时,如果要查询的域名在hosts.ini里面的话就会返回,如果不在hosts里面则不会返回任何结果,都是查询超时.
nslookup - 127.0.0.1,配置同上,返回正常.

以上重启服务均没有错误报告.

**Comment by chengr28** [comment]
已经发送了邮件

**Comment by shuangzhijinghua** [comment]
用了几天似乎问题又变严重了点
nslookup能够显示出dns软件的服务器信息.但是只能根据hosts里面设定好的来回答.而且必须要有缓存一次才能在::1下访问.
dns使用[2001:470:20::2]:53\8.8.4.4:53\208.67.222.222:53

**Comment by shuangzhijinghua** [comment]
不过发现一个细节,用wireshark抓包的时候没有列出openvpn使用的TAP v9虚拟网卡,会不会是这个问题呢...我也看一下.

**Comment by shuangzhijinghua** [comment]
切换到win7,wireshark可以抓到openvpn的TAP v9虚拟网卡的数据,可以看到程序的DNS请求,但是无论是::1还是127.0.0.1都不返回除了hosts.ini以外的内容,甚至都没有返回任何数据.

**Comment by chengr28** [comment]
可能是程序识别 IPv6 隧道的算法有问题……我先研究下系统的机制看看
或者到时候直接放个选项算了……

这类软件改了系统的连接结构……搞起来其实挺麻烦的 =_/=
