### ISSUE TITLE
你好想请教下PROXY配置问题

### ISSUE THREAD

**Issue by tudi1909** [chengr28/Pcap_DNSProxy#101]
[Proxy]
SOCKS Proxy = 1
SOCKS Version = 5
SOCKS Protocol = IPv4 + UDP + TCP
SOCKS Reliable Socket Timeout = 6000
SOCKS Unreliable Socket Timeout = 3000
SOCKS UDP No Handshake = 1
SOCKS Proxy Only = 0
SOCKS IPv4 Address = 192.168.203.202:2008
SOCKS IPv6 Address = [::1]:1080
SOCKS Target Server = 119.29.29.29:53
SOCKS Username = 
SOCKS Password = 
已经配置好了，并且也重新启动服务了，为何没有效果呢？感谢

**Comment by rampageX** [comment]
你用境外的SOCKS服务器连境内的DNS服务器？明显不行，请用默认的四个8

tudi1909 <notifications@github.com>于2015年11月12日 周四17:50写道：

**Comment by chengr28** [comment]
启用 UDP 的话需要本地和远程的 SOCKS 服务器支持 UDP Relay 一般可以先用 TCP 试试
而且不太清楚你说的『没有效果』指的是什么

**Comment by tudi1909** [comment]
@rampageX 我本地环境4个8，8.8.4.*不能ping同所以才用的此dns
@chengr28 抱歉没有说太清楚，我是使用的工具在局域网中架设的socks5,http,可能需要抓包看下具体情况了 多谢

**Comment by kang000feng** [comment]
@chengr28 你好， 请问 [Local Hosts/境内DNS解析域名列表] 与 [Hosts/主要Hosts列表] 哪个优先级高？ 文档中两处有矛盾，如 Hosts 文件格式说明：

Hosts 配置文件分为多个提供不同功能的区域
* 区域通过标签识别，修改时切勿将其删除
* 优先级：Local Hosts/境内DNS解析域名列表 > Hosts/主要Hosts列表，

**Comment by chengr28** [comment]
@kang000feng 那部分的确写下有段时间没更新了……正确的流程是后者

**Comment by jorismq** [comment]
你好，你最终成功了吗？我一直不成功。设置后还是登不上google。而我的server也确认是工作的。
win10 pro x64

我有一个代理服务器，1.1.1.1:1080。其他软件开启socks5代理，输入上面地址后，这个软件可以顺利连网使用
我想使Pcap_DNSProxy也用这个代理
Direct Request = IPv4 + IPv6
SOCKS Proxy = 1
SOCKS Version = 5
SOCKS Protocol = IPv6 + IPv4 + TCP + UDP
SOCKS UDP No Handshake = 0
SOCKS Proxy Only = 0
SOCKS IPv4 Address = 127.0.0.1:1080
SOCKS IPv6 Address = [::1]:1080
SOCKS Target Server = 1.1.1.1:1080
SOCKS Username =
SOCKS Password =

但是nslookup www.google.com
就会出现DNS time out
什么也解析不了。
