### ISSUE TITLE
你好想请教为什么有些程序域名解析请求只走 Local Hosts/境内 DNS 解析域名？

### ISSUE THREAD

**Issue by kang000feng** [chengr28/Pcap_DNSProxy#102]
你好，我设置的优先级是：系统 Hosts > Pcap_DNSProxy 的 Hosts 条目 > Hosts/主要 Hosts 列表） > DNS 缓存 > Local Hosts//境内 DNS 解析域名；
但是Goagent[PHP] fetchserver= XXX.COM中域名解析请求只走 Local Hosts/境内 DNS 解析域名，没有走系统 Hosts ，理论上所有DNS解析都应先经过系统Hosts，请问是我设置有问题吗？

**Comment by chengr28** [comment]
如果这边你开了 Issue 那么随便改也是没问题的，但是 close 了这边却又去开一个新的 Issue 并不好……就像 https://github.com/chengr28/Pcap_DNSProxy/issues/103

**Comment by kang000feng** [comment]
抱歉，我一定改
