### ISSUE TITLE
你好想请教为什么有一程序域名解析请求只走 Local Hosts/境内 DNS 解析域名？

### ISSUE THREAD

**Issue by kang000feng** [chengr28/Pcap_DNSProxy#103]
你好，我设置的优先级是：系统 Hosts > Pcap_DNSProxy 的 Hosts 条目 > Hosts/主要 Hosts 列表） > DNS 缓存 > Local Hosts//境内 DNS 解析域名；
但是Goagent[PHP] fetchserver= XXX.COM中域名解析请求只走 Local Hosts/境内 DNS 解析域名，没有走系统 Hosts ，理论上所有DNS解析都应先经过系统Hosts，请问是我设置有问题还是Goagent的问题？

**Comment by kang000feng** [comment]
测试了好几个goagnet版本都是一样的结果，[PHP] fetchserver解析只走Local Hosts/境内 DNS

**Comment by chengr28** [comment]
GoAgent 是自己进行 DNS 域名解析，并不使用系统的 DNS 接口
