### ISSUE TITLE
Linux 下编译出现4条警告信息，是什么原因，有影响麽？

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#104]
/root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Service.cpp: In function ‘void FlushAllDNSCache()’:
/root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Service.cpp:389:45: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system("service nscd restart 2>/dev/null"); //Name Service Cache Daemon service
                                             ^
/root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Service.cpp:390:48: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system("service dnsmasq restart 2>/dev/null"); //Dnsmasq service
                                                ^
/root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Service.cpp:391:37: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system("rndc restart 2>/dev/null"); //Name server control utility of BIND(9.1.3 and
                                     ^
/root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Service.cpp:392:35: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system("rndc flush 2>/dev/null"); //Name server control utility of BIND(9.2.0 and n
                                   ^

Ubuntu 15.10, 依赖已经全部安装。
麻烦看看，是什么原因，有影响麽?

**Comment by chengr28** [comment]
这4个信息意思是编译器提醒忽略了 system 函数的返回值，调用这个函数用于清除系统的 DNS 缓存
不过事实上这个无论清除成功与否都与程序的运行没有关系，所以是不需要理会的
