### ISSUE TITLE
请问，能否实现根据不同的请求来源，返回不同的解析结果？

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#105]
例如：
192.168.1.0/24，这个网段的用户发出的对  www.x.com 域名的解析请求，返回解析结果IPv4为 1.1.1.1；
除了上面这个网段的其他用户发出的对  www.x.com 域名的解析请求，返回解析结果IPv4为 2.2.2.2；

有这个需求，想问下，能不能实现这个需求？
如果 pcap 不能实现，是否有其他软件和方案，辅助实现呢？

**Comment by chengr28** [comment]
这个功能应该不会添加了……实际上本项目本身是针对作为客户端运行的情况，虽然作为服务器端也可以正常工作，但如果要追求更加高级的功能，应该使用类似 BIND 的软件进行

**Comment by jzp820927** [comment]
好吧，谢谢作者解答，如果实现不了就算了，感谢!

**Comment by chengr28** [comment]
刚才更新的版本添加了 Source Hosts 的功能，可以试试

**Comment by jzp820927** [comment]
额，非常感谢，我先看看 doc 怎么配置先
