### ISSUE TITLE
小白请教在vps上到底如果编译安装

### ISSUE THREAD

**Issue by gaoyan1234** [chengr28/Pcap_DNSProxy#107]
最近腾讯云有一块钱一个月的学生特惠租用云服务器的优惠 准备在上面安装一个centos 系统，运行 Pcap_DNSProxy  就可以墙内避免dns污染了。到底如何在vps上安装呢，看了说明根本看不懂。 有没有像ss 或者openvpn服务器那样通俗易懂的教程啊 甚至是一键安装教程  谢谢

**Comment by wongsyrone** [comment]
使用 https://github.com/chengr28/Pcap_DNSProxy/tree/master/Source/Scripts 内的脚本或者参照Linux的Readme文档。脚本也算是一键安装吧。

**Comment by chengr28** [comment]
Linux 的[说明文档](https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe_Linux(zh_Hans).txt)其实已经算是详细的安装部署步骤了吧，因为 Linux 平台本身发行版不同架构也可能不一样，依赖和启动方式之类的，只能依靠用户自己动手完成……

**Comment by chengr28** [comment]
补充一下吧……其实就是：
* 按照说明把依赖解决好
* 运行 Linux_Build.sh 编译程序
* 选择程序服务的类型，就是 Linux_Install.xxx.sh
* 修改系统的 DNS 配置
