### ISSUE TITLE
在64位的Debian8上编译失败

### ISSUE THREAD

**Issue by llorch-zh** [chengr28/Pcap_DNSProxy#108]
2015/12/13，clone源码后编译失败，报错情况：
<pre>
[ 11%] Building CXX object Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Initialization.cpp.o
In file included from /home/builder/Pcap_DNSProxy/Source/Pcap_DNSProxy/Initialization.cpp:20:0:
/home/builder/Pcap_DNSProxy/Source/Pcap_DNSProxy/Initialization.h:47:10: error: variable or field ‘DNSCurveConfigurationTableSetting’ declared void
  _Inout_ DNSCurveConfigurationTable *DNSCurveConfigurationParameter);
          ^
/home/builder/Pcap_DNSProxy/Source/Pcap_DNSProxy/Initialization.h:47:10: error: ‘DNSCurveConfigurationTable’ was not declared in this scope
/home/builder/Pcap_DNSProxy/Source/Pcap_DNSProxy/Initialization.h:47:38: error: ‘DNSCurveConfigurationParameter’ was not declared in this scope
  _Inout_ DNSCurveConfigurationTable *DNSCurveConfigurationParameter);
                                      ^
Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/build.make:146: recipe for target 'Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Initialization.cpp.o' failed
make[2]: *** [Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Initialization.cpp.o] Error 1
CMakeFiles/Makefile2:125: recipe for target 'Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
</pre>
系统配置：
```Linux localhost 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux```
GCC版本：
```gcc (Debian 4.9.2-10) 4.9.2```
CMake版本：
```cmake version 3.0.2```

**Comment by chengr28** [comment]
呃这里好像漏写了两行……编译没开 LibSodium 支持的话的确会有问题

解决方法是在 Initialization.h 的第45和46行之间插入一句 `#if defined(ENABLE_LIBSODIUM)`
以及在整个文件最后一行加上 `#endif` 保存并重新编译应该就没问题了
下个版本会修复这个问题

**Comment by llorch-zh** [comment]
感谢大神指引！通过编译了！谢谢！这个repo很精彩，持续关注中。。。

**Comment by llorch-zh** [comment]
大神，我在Debian8上安装了`libpcap0.8-dev`之后再编译就没有报错了。最开始报错是直接粗暴地`cmake ..&&make`过去的。

**Comment by llorch-zh** [comment]
这个问题好像是CMakeLists.txt引起的，执行`Source/Script/Linux_Build.sh`脚本又正确地在`Source/Release`下面生成了二进制。

**Comment by chengr28** [comment]
源代码漏写了那两行，导致在不包含 LibSodium 编译时会出问题，不是 `CMakeLists.txt` 的问题：
* `Script/Linux_Build.sh` 里默认包含 LibSodium（除非指定参数不包含）所以不会触发这个问题
* 直接 `cmake . && make` 默认不包含 LibSodium 所以会触发这个问题
* 关于详细的编译方法和注意事项，可参见[说明文档](https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe_Linux(zh_Hans).txt)的介绍

**Comment by chengr28** [comment]
刚才更新了 0.4.4.6 应该没有这个问题了
不过其实正确的做法是运行 `Linux_Build.sh` 的，其它方法没试过也不好说……

**Comment by llorch-zh** [comment]
O了，谢谢！
