### ISSUE TITLE
  hosts的正规则如何写？

### ISSUE THREAD

**Issue by oe77** [chengr28/Pcap_DNSProxy#109]
折腾了很旧，还未弄明白hosts的正规则写到Hosts.ini文件，还是写到系统中的 hosts文件，可以指点一下吗？网上又无小白教程，hosts正规则能否写一个例子！

**Comment by chengr28** [comment]
个人觉得先去了解一下[正则表达式](https://zh.wikipedia.org/wiki/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F)比较好……毕竟也算是一个领域
系统 Hosts 并不支持正则表达式，而且优先级最高同时不受程序的控制，所以修改系统的 Hosts 是没用的

举个例子就是：
`28.28.28.28 .*\.google\.com` 就是符合 *.google.com 规则 Hosts
`2828::2828 lh[1-6]\.googleusercontent\.com` 就是符合 lh(从1到6) 这样
