### ISSUE TITLE
使用中遇到的2个问题，希望作者解答下。

### ISSUE THREAD

**Issue by liangxyz** [chengr28/Pcap_DNSProxy#11]
第一个问题是有关Operation Mode的，在Server中，我发现提供DNS服务的地址是本机的局域网地址，但同时好像127.0.0.1:53端口也是被占用的。请问作者能不能向dnsforwarder一样，在设置成服务器模式的时候释放127.0.0.1：53端口，因为我要用dnsspeeder做dns管理。我原来的DNS是先通过127.0.0.1：53端口向dnsspeeder发送请求，然后dnsspeeder向本机局域网地址（192.168.1.6）53端口发送dns请求，由dnsforwarder解析并返回结果。现在我想用Pcap_DNSProxy替代dnsforwarder，但是dnsspeeder会提示127.0.0.1:53端口被占用，而这只能是Pcap_DNSProxy的原因。

第二个，我使用的国外DNS为106.186.17.181：2053，Provider Name = 2.dnscrypt-cert.ns2.jp.dns.opennic.glue，Public Key = 8768:C3DB:F70A:FBC6:3B64:8630:8167:2FD4:EE6F:E175:ECFD:46C9:22FC:7674:A1AC:2E2A，可是在加密使用的时候一直出现错误：UDP get signature data request error ，看了FAQ表示不知道如何得到服务器的魔数和指纹。请问作者可以提供下帮助吗？谢谢！
另外感谢作者提供了如此优秀的软件，谢谢！！！

**Comment by chengr28** [comment]
* 监听那个端口的问题其实和系统本身的策略有关，本程序 Server 模式使用的是未指定地址进行绑定，你可以理解为监听所有发往本机 53 端口的请求，这样你后来再绑定 127.0.0.1 自然就绑不了了……如果你确实想两个一起用，那么谨记『先开小再开大』在本例中就是先开 127.0.0.1 的监听再开未指定地址的监听，这样就不会有冲突的问题了
* 或者这样吧，我在下次更新的时候添加一个自定义本地监听地址的功能，这样应该就能彻底解决这种监听冲突的情况
* 关于这个 OpenNIC 的 DNSCrypt 服务器，我这边测试得到 `Destination Unreachable(Port Unreachable)` 的错误，似乎是服务器的端口关闭，或者你可以理解为服务器停止 DNSCrypt 的服务了，就是服务器失效了的意思。建议是更换一个服务器，或者干脆就用本程序自带的 OpenDNS 也可以

**Comment by liangxyz** [comment]
谢谢，十分期待您的更新。对于那个服务器，我这里发现使用系统自带DNS可以使用，在看网站说明，貌似也可以用5353端口
另外win7 x64系统，安装WinPcap时候没有选择开机启动驱动，然后会遇到下面的问题，重复时间不定，请问是什么情况？
2015-02-10 09:30:47 -> WinPcap Error: An error occurred in \Device\NPF_{625C1BC7-A743-4CF5-998F-1E910E4817A3}.
2015-02-10 15:34:03 -> WinPcap Error: Insufficient permissions or no any available network devices.

**Comment by chengr28** [comment]
* WinPcap 安装那里有没选择开启启动是没有关系的，因为程序是直接使用 API 调用，就算开机没启动也是可以照样使用的
* `An error occurred in xxx.` 是 WinPcap 检测到网络适配器发生错误，一般是因为改网络适配器（就是本地连接和无线连接之类的硬件设备）连接中断或者被禁用导致的。下面那句话意思就是没有检测到可用的网络适配器，程序会继续自动检测，只要再有网络适配器可用就会进行监听，这方面是不用人为干预的

**Comment by liangxyz** [comment]
谢谢，我明白了，可能还是我手动修改DNS服务器导致的

**Comment by chengr28** [comment]
希望能提供一个邮件地址，我把新的测试版本发过去给你试试
就是添加了上面所说功能的版本w

**Comment by liangxyz** [comment]
作者您好，我的邮件地址是liangxyz@live.com，麻烦您了，谢谢

**Comment by liangxyz** [comment]
感谢作者，完美解决我的问题！！！

**Comment by muink** [comment]
**Pcapdnsproxy没有缓存管理的确不方便啊XD**

按lz思路也完成了对解析结果的管理

Dnsspeeder曾经用过,因不喜其自动对所有网卡配置dns已抛入冷宫
所以目前我用的是AnalogX的FastCache做的管理
- 我的配置过程
 1. 通过FC监听本地端口,将请求发往接口地址为110.110.110.110的VBOX Host-Only网卡(发往本机ip会发生重定向循环)
 2. 然后Pcapdnsproxy监听110.110.110.110这张网卡,处理收到的请求
 3. FC缓存所有Pcapdnsproxy返还的解析结果,并以图形界面呈现

**Comment by chengr28** [comment]
@muink https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe(zh_Hans).txt#L203 程序是有缓存机制的

**Comment by wongsyrone** [comment]
@muink 
另外，传 `--flush-dns` 参数可以清除程序内部缓存和系统缓存。

**Comment by muink** [comment]
@chengr28 @wongsyrone 
谢谢啦,明白啦
