### ISSUE TITLE
速度上的问题....

### ISSUE THREAD

**Issue by oe77** [chengr28/Pcap_DNSProxy#110]
首先谢谢作者解答了我刚才的问题，使用Pcap_DNSProxy确实达到了防DNS污染效果！但我比较注重速度上的问题，请问使用Pcap_DNSProxy对国外网站响应的速度会不会比直接修改系统中的hosts文件快？还是两者效果都是一样...

**Comment by chengr28** [comment]
你似乎混淆了域名解析和实际数据的传输两个过程……程序只负责将正确的解析结果呈递给系统，就是类似给不认识路的指路，但实际上去走的并不是负责解析域名的程序。实际请求是系统或者其它程序去请求的，所以如果你说与远程服务器传输，速度并不是程序能控制的……
如果你纯粹只是说解析域名的快慢，之前的 Issue 也说过了系统里优先级最高就是那个 Hosts 文件，自然就是写到那个 Hosts 文件里是最快的
