### ISSUE TITLE
是否可以添加`回返报文域名恢复小写`选项

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#111]
如题

事情是这样的:  
> 由于本人有用dnsspeeder做pacpdns的后置缓存服务器
并且pacpdns有开`域名随机大小写`功能
虽然这个功能可以过滤很多的假报文
但同时收到的报文也是随机大小写的域名结果
然而作为后置的dnsspeeder却大小写敏感, 导致同一域名会逐渐积累起重复的三条记录
在域名频繁更换ip的情况下, 这会导致dnsspeeder只会更新完全相同的域名, 其余两条记录不会改变,这就导致实际使用中冲突, 之前都是使用手动排错, 现在越来越冗长的列表实在无力维护, 希望作者能够添加这个开关选项

**Comment by chengr28** [comment]
呃……这个本来就是附加的功能而已，这个功能的工作原理就是利用了域名大小写不敏感作为前提工作的，如果不用可以直接关掉也没事……起码现在没发现有大问题
不过域名系统大小写不敏感是标准要求实现的，而 dnsspeeder 不按照标准工作……应该去给他们项目组反馈才对

**Comment by muink** [comment]
dnsspeeder已经有好几年没更新了,反馈似乎没什么用
除了关闭`域名随机大小写`没别的办法了么

**Comment by chengr28** [comment]
似乎并没有……

**Comment by kkkst** [comment]
原来是这样，还以为中毒或者dns又被投毒了呢
Ping WWW.gOOglE.CoM。。。
