### ISSUE TITLE
DNS服务器解析问题

### ISSUE THREAD

**Issue by houzi-** [chengr28/Pcap_DNSProxy#113]
在tomato平台上
Local Main = 1
Local Routing = 1

开启这两个选项会导致facebook加载不了图片，导致裂图！关闭就正常！

**Comment by chengr28** [comment]
如果用的是 Chrome 可以按 F12 打开控制台的 Console 看看
应该能看到出错的域名是什么

**Comment by houzi-** [comment]
@chengr28 
![vbnz](https://cloud.githubusercontent.com/assets/9395995/12046764/3807bcf0-aefa-11e5-890c-61a10aaf698e.PNG)

**Comment by rampageX** [comment]
我这没问题。

**Comment by chengr28** [comment]
如果是 DNS 解析有问题 Console 里应该会显示 `net::ERR_NAME_NOT_RESOLVED` 刚才发的图上的错误消息 `net::ERR_CONNECTION_TIMED_OUT` 是连接超时的意思，就是说浏览器已经拿到了域名的解析结果，但是连接服务器超时，并非程序的问题

**Comment by houzi-** [comment]
@rampageX @chengr28 Local Host = 方案解决！真是奇怪了！如果用
Local Main = 1
Local Routing = 1
就会导致time out！真是无解了！

**Comment by chengr28** [comment]
`Local Hosts` 是白名单域名……Local Main + Local Routing 不行可能是本地 DNS 服务器的问题

**Comment by houzi-** [comment]
@chengr28 嗯！thanks! 我觉得也是，继续观察看看吧！
