### ISSUE TITLE
服务无法启动

### ISSUE THREAD

**Issue by meltyblood2010** [chengr28/Pcap_DNSProxy#116]
WIN7 64BIT系统 WinPcap_4.1.3已安装
管理员启动ServiceControl.bat选择"1:Install service"之后
--------------------------分隔线---------------------------
[SC] OpenService 失败 1060:

指定的服务未安装。

[SC] OpenService 失败 1060:

指定的服务未安装。

[SC] CreateService 成功
操作成功完成。
操作成功完成。
--------------------------分隔线---------------------------
一直显示上面这个。进程列表多出3个Pcap_DNSProxy.exe进程，强行关闭命令行窗口后无法用结束这3个进程。多出一个停止状态的Pcap_DNSProxy服务，强行开启显示1053错误。DNS无法工作。浏览网页显示DNS解析失败
重启后这3个进程消失，Pcap_DNSProxy服务消失。再次前面的步骤情况依旧

**Comment by wongsyrone** [comment]
尝试选择2: Uninstall service之后再次1: Install service

**Comment by chengr28** [comment]
遇到这种问题其实可以先不管服务是否运行，而是在确保没有其它 Pcap_DNSProxy 在后台后直接运行程序，这样应该就能看到出错的原因，或者留意有没有 Error.log 生成

**Comment by meltyblood2010** [comment]
1L的方法试过并没有用。
2L：管理员批处理文件选1之后直接3个Pcap_DNSProxy进程(我不知道这算不算后台)+1个停止状态的Pcap_DNSProxy服务，进程无法关闭。DNS服务也不可用，浏览网页会报DNS错误。
最新情况：关机过程中Pcap_DNSProxy.exe进程弹窗报0xc0000142内存错误。不管它重启完毕就能使用了。没有 Error.log 生成。目前使用正常
PS:进程关不掉服务无法开启只能重启。重启完了运行批处理文件又是同样地问题。有时候不知道怎么了就能使用了，明明没有任何变动。

**Comment by chengr28** [comment]
或许是遇到什么问题卡住了，机器的环境不一样也不好说……0xc0000142 就是那个多开程序会崩溃的问题，可能就是因为之前的程序卡死了无法结束，之后再运行的程序就会出现这个问题
应该还是程序内部延迟退出的机制设计得不是很好的缘故……会找个时间看看能不能解决

**Comment by meltyblood2010** [comment]
感谢解答
