### ISSUE TITLE
一个生成 WhiteList.txt 的脚本

### ISSUE THREAD

**Issue by dgeibi** [chengr28/Pcap_DNSProxy#118]
https://gist.github.com/dgeibi/f77456a679e307e9e90d

代码拙劣，见谅

**Comment by dgeibi** [comment]
更新了

**Comment by chengr28** [comment]
看着好像还不错……稍微需要点时间测试，顺便看看能不能移植到 Windows 上

**Comment by wongsyrone** [comment]
Release/Windows/Tools/Routing_Update/bin里面已经有了curl和sed

**Comment by dgeibi** [comment]
测试了，那里的 curl 不支持 HTTPS

**Comment by wongsyrone** [comment]
http://curl.haxx.se/download.html#Win32 这里有支持SSL的，替换一下现有的应该就行了

**Comment by dgeibi** [comment]
http://www.paehl.com/open_source/?CURL_7.46.0

winssl 的版本好用

**Comment by dgeibi** [comment]
batch 版弄好了

**Comment by chengr28** [comment]
要装 Visual C++ Redistributable 其实不太好，不过既然只是辅助用的工具也就没什么所谓……项目主程序那边都是编译链接的时候配置好不需要额外的运行库的w

**Comment by dgeibi** [comment]
http://curl.haxx.se/download.html#Win32 Darren Owen 的最新版本，Win10下不需要额外导入证书或安装Visual C++ Redistributable 就能正常运行

**Comment by chengr28** [comment]
Linux 的脚本似乎在部分发行版里不能正常运作……提示 `sed：-e 表达式 #1，字符 18：未终止的“s”命令`
系统环境 Debian 8.2.0 + `sed (GNU sed) 4.2.2`(自带)
然而最奇葩的是 Windows 下用隔壁 Update_Routing 的 sed.exe 却没有出现任何问题……

**Comment by dgeibi** [comment]
分隔符问题，已经把`@`改成`|`了

**Comment by dgeibi** [comment]
![default](https://cloud.githubusercontent.com/assets/2224764/12867488/1a30faa4-cd2a-11e5-910b-6f04a1e9b208.PNG)
Linux/MINGW64 的 sed 都像上图这样，好奇怪 (

**Comment by chengr28** [comment]
已更新……新版本已经附带了更新白名单的批处理和脚本w

**Comment by chengr28** [comment]
顺便不怎么懂 `sed` 貌似印象中极少使用……另一边更新路由表的脚本是直接 `printf` 的

**Comment by dgeibi** [comment]
😂 所以刚刚更新`Update_WhiteList.sh`还需要加一个`\`

**Comment by chengr28** [comment]
@dgeibi 好吧下次更新的时候再加进去了……Windows 这边测试有没有 `\` 貌似输出的数据文件都是一样的

**Comment by dgeibi** [comment]
是呀
