### ISSUE TITLE
更新记录0.4.5.1  sha-256校验错误

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#119]
![00](https://cloud.githubusercontent.com/assets/7929014/12578082/92f2bc90-c459-11e5-89f2-2204a308f9f0.PNG)
看样子是更新记录写错了?

**Comment by chengr28** [comment]
更新记录里的那个是 **SHA-3(256)** 也就是 SHA-3 的 256 位
并不是 SHA256 哦，这个是 SHA-2 的 256 位

**Comment by muink** [comment]
好吧,试了一下的确是这样
另这工具蛮好的,支持算法挺多

**Comment by muink** [comment]
@chengr28 似乎还是有问题
我用Toolkit里的FileHash算出的0.4.8.4的64位主程序sha3-256是
`B28B1D013FE4690F809D3D1FFCA0FFAF152C9F2A3201E2596D398F90E78B2657`
用HashTab和RapidCRC算出的都是
`96CBAD593610A49B0930E85548E5C8D1F2544C25B303D27D27FC94CEA193B499`
不知道是什么情况

**Comment by chengr28** [comment]
@muink 因为这些工具用的是 Keccak 赢得 NIST 下一代 SHA 算法竞赛时的旧算法，Toolkit 里用的是 NIST 正式发布 SHA-3 (FIPS 202) 时的新算法。测试的方法是 Hash 一个空文件：
* Toolkit 里算出来的是：
`a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a`
* 而那些工具是旧版 Keccak 算法，算出来是：
`c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`
