### ISSUE TITLE
老大,是否可将edns开关单独分离本地dns和主要dns

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#120]
### 配置参数
- 本地协议为`ipv4 + udp`
- 已开启`Local Hosts`
- 本地解析服务器为路由器`192.168.1.1:53`(路由器使用`DNSPod公共dns`和`中科大dns`解析)
- 主要解析服务器为`OpenDNS`和其他一些国外服务器
- `EDNS Label = 1`且`DNSSEC Request = 1`且`DNSSEC Validation = 1`
- `Host.ini`中`[Local Hosts]`下包含`.*\balicdn\.com.*`
- 程序监听在网卡`192.168.110.110`上

### 问题描述
- 开启`EDNS Label`本地解析无效化
![0-0](https://cloud.githubusercontent.com/assets/7929014/12645608/24888934-c606-11e5-8a7e-7def5eec73da.PNG)
![0-1](https://cloud.githubusercontent.com/assets/7929014/12645949/3e982cec-c608-11e5-8cfa-e1268e24e097.PNG)
![1-0](https://cloud.githubusercontent.com/assets/7929014/12645609/24944170-c606-11e5-9468-9f2dfed8f6a0.PNG)
- 直接使用路由器解析
![2-0](https://cloud.githubusercontent.com/assets/7929014/12645874/e01668a0-c607-11e5-87f5-b46f9a2f090a.PNG)
- 关闭`EDNS Label`后解析, 本地解析又有效了
![2-1](https://cloud.githubusercontent.com/assets/7929014/12645992/8ce4293c-c608-11e5-92bb-32910bb38954.PNG)

### 问题引发猜测
1. 未知原因的local edns解析失败
   - 已测试路由器可以解析edns+dnssec
![3-0](https://cloud.githubusercontent.com/assets/7929014/12645993/8ce73258-c608-11e5-807b-d7476bd36824.PNG)
2. 按照程序流程,本地请求失败后转而请求主要dns

**Comment by wongsyrone** [comment]
参数不是已经分离出来了么，https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe(zh_Hans).txt#L512

**Comment by muink** [comment]
Oh!!  抱歉,是我忘记更新我本地的ReadMe了
已改配置,没问题了

**Comment by chengr28** [comment]
个人觉得比较像是 `DNSSEC Validation` 参数的问题，毕竟有个验证的功能……或者可以先试试把 `DNSSEC Request` 关掉然后重启看看，因为就现象来看似乎是因为来自 Local DNS(这里是路由器) 无法通过程序的检查造成的。实在不放心的话可以抓个包发到我的邮箱里，可以帮忙看看是怎么回事w

**Comment by muink** [comment]
@chengr28 可能不是,我把`DNSSEC Request`和`DNSSEC Validation`都关了
本地解析还是失效的

**Comment by chengr28** [comment]
@muink 这样可能真的要抓个包看看了……`EDNS Label` 本身也是有检查的

**Comment by muink** [comment]
@chengr28 抓包试了一下,路由器没有返回包
把本地dns服务器改为`DNSPod公共dns`地址后,还是本地解析失败
但它有回应 `server failure`

话说抓包保存的是`pcapng`文件么

**Comment by chengr28** [comment]
可以的，直接发到邮箱就行

**Comment by chengr28** [comment]
把 `IPv4 EDNS Client Subnet Address` 和 `IPv6 EDNS Client Subnet Address` 后面的地址全部清空，然后把 `EDNS Client Subnet Relay` 关掉重启服务

**Comment by muink** [comment]
噢,可以正常解析了
但是为什么呢
`EDNS Client Subnet Address`不是用来提升地区准确度的么
它和本地解析不兼容?

**Comment by chengr28** [comment]
是这样……EDNS Client Subnet 这个功能主要是给 DNS 转发器用的。举个例子 A 是某个客户，B 是服务器，双方处于完全不同的网络内，A 向 B 请求解析某个域名，B 则向权威 DNS 服务器转发带有 A 地址的请求，因为如果不带 A 地址权威服务器就只会知道 B 的地址而可能返回一个不合适的结果（就是 CDN 地区准确度的问题）带上 A 的地址后才会获得 A 所在地区准确的结果，这个功能就是 EDNS Client Subnet

这个功能最开始是 Google 提出来的，就是 [Client Subnet in DNS Queries](https://tools.ietf.org/html/draft-vandergaast-edns-client-subnet) 现在还只是草案不是 RFC 的正式文档，也就是说现在的软硬件还暂时没有支持或者兼容的义务。归根到底的问题就是你的路由器和 DNSPod 的公共服务器不支持 EDNS Client Subnet 这个功能，自然就无法返回结果了

**Comment by muink** [comment]
恩,刚刚用dig 测试了,路由器的确不支持`EDNS Client Subnet `
DNSPod DNS那边,我把`DNSSEC Validation`关了就能正常解析了,应该是没通过程序验证的关系

**Comment by muink** [comment]
顺便问一下`IPv4 Data Filter`是干嘛用的?

**Comment by chengr28** [comment]
然而收到的抓包看到 DNSPod 直接回复 Server Failed……这个和程序的过滤就没有关系了

**Comment by chengr28** [comment]
`IPv4 Data Filter` 是 0.4 正式版之前内置的针对 IPv4 数据包的过滤，不过后来发现不太可靠而且有过滤正常结果的可能性，所以做了个选项然后默认关掉了

**Comment by muink** [comment]
刚刚试了一下,`DNSPod DNS`解析又没问题了`DNSSEC Validation`也开着,抓包也显示正常
仔细看了一下DNSPod DNS的官网,介绍里面写了是支持`EDNS Client Subnet`的
我现在索性不用路由器解析了,DNSPod DNS的准确度不比ispdns差又比alidns准

**Comment by chengr28** [comment]
DNSPod 自己这样写而已，是不是真的支持实际测试才会知道
