### ISSUE TITLE
可否考虑兼容Win10Pcap？

### ISSUE THREAD

**Issue by smounives** [chengr28/Pcap_DNSProxy#121]
Win10Pcap官网：
http://www.win10pcap.org/
看官网介绍是说兼容以前的WinPcap并且使用的是新的 NDIS 6.x 驱动模型，WinPcap用的是 NDIS 5.x 驱动模型，Wireshark可以直接兼容，但是Pcap_DNSProxy会报错

**Comment by chengr28** [comment]
虽然 Win10Pcap 官方是介绍二进制完全兼容 WinPcap 不过实际使用程序会报 `Unable to disable the capture of loopback packets` 原因他们项目的 https://github.com/SoftEtherVPN/Win10Pcap/issues/7 有提到是因为不支持某个 WinPcap 支持的特性造成的
这边下次更新会把这个参数去掉，这样直接用 Win10Pcap 应该就没问题了w

**Comment by smounives** [comment]
谢谢_(:3」∠)_

**Comment by hsluoyz** [comment]
推荐使用Npcap: https://github.com/nmap/npcap，在release页面有安装包下载。Win10Pcap的作者基本已经停止维护了，并且其代码并没有包括WinPcap的全部功能。Npcap在包含WinPcap 4.1.3全部功能的基础上，增加了一些新的功能。

**Comment by chengr28** [comment]
已更新……实测过不论是 Win10Pcap 还是 Npcap 都是没问题的
感谢反馈w
