### ISSUE TITLE
电信网络，网站IP给解析到联通上了

### ISSUE THREAD

**Issue by muziling** [chengr28/Pcap_DNSProxy#122]
[root@PandoraBox_3CCC:/etc/init.d]#nslookup www.right.com.cn 127.0.0.1:1053
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      www.right.com.cn
Address 1: 113.207.76.102
Address 2: 113.207.76.73
[root@PandoraBox_3CCC:/etc/init.d]#nslookup www.right.com.cn 114.114.114.114
Server:    114.114.114.114
Address 1: 114.114.114.114 public1.114dns.com

Name:      www.right.com.cn
Address 1: 220.167.107.114 114.107.167.220.dial.dy.sc.dynamic.163data.com.cn
Address 2: 220.167.107.112 112.107.167.220.dial.dy.sc.dynamic.163data.com.cn

113.207.76.102 和 220.167.107.114 都在Routing.txt列表里，难道真要维护一个全中国网站的域名列表？

我看chinadns的原理是，如果国内DNS和国外可靠DNS都解析到国内地址，以国内的DNS为准？但我用chinadns来解析，也是解析到联通的IP 220.167.107.114 上。

**Comment by chengr28** [comment]
建议先检查一下程序的配置文件，默认用的是 114.114.115.115 这个地址的
