### ISSUE TITLE
Routing_Update始终提示网络未连接

### ISSUE THREAD

**Issue by w48325832** [chengr28/Pcap_DNSProxy#124]
是这样的，我这边的网络似乎把icmp协议的数据包都拦截了，ping什么都是未响应。导致工具Routing_Update这边的批处理始终检测是网络未连接，有什么好办法么

**Comment by wongsyrone** [comment]
https://github.com/chengr28/Pcap_DNSProxy/blob/Release/Windows/Tools/Routing_Update/Update_GB2312.bat#L84 这行注释掉或者删掉

**Comment by w48325832** [comment]
多谢上面的朋友

**Comment by chengr28** [comment]
已更新，应该没问题了w
