### ISSUE TITLE
远端数据未更新,从本地重建一次路由表后Routing.txt不包含路由表信息

### ISSUE THREAD

**Issue by AnyoeDove** [chengr28/Pcap_DNSProxy#125]
只有这部分内容
> [Local Routing]
> ## China mainland routing blocks
> ## Source: https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest
> ## Last update: 2016-02-11

#Routingipv4# #Routingipv6#内容完整 delegated-apnic-latest也没问题

**Comment by chengr28** [comment]
GB2312 版本的批处理似乎有点问题……可以先用着英文版
下次更新的时候会修复

**Comment by wongsyrone** [comment]
Update_GB2312.bat的`:[WriteIPHead]`缺少`)>"%temp%\IPv%1ListHead"`，括号没闭合，然后临时文件就有问题了。

https://github.com/chengr28/Pcap_DNSProxy/blob/Release/Windows/Tools/Update_Routing/Update.bat#L216
https://github.com/chengr28/Pcap_DNSProxy/blob/Release/Windows/Tools/Update_Routing/Update_GB2312.bat#L216

**Comment by AnyoeDove** [comment]
默默的问一个问题 为什么需要把curl复制到%temp%下执行呢？

**Comment by wongsyrone** [comment]
curl默认下载位置是当前目录，如果有指定位置的参数实际上就不用复制了，wget有一个`-P`

**Comment by chengr28** [comment]
之前原本的批处理都是在 %temp% 里处理的，只是之前 curl 与批处理文件都在相同的目录内，现在因为两个 Update 的工具都要用所以移出去了。改的时候是为了避免有目录和路径的问题，还有就是 WinSSL 版的 curl 处理 Windows 的环境变量/反斜杠路径有问题，才把整个 curl 程序复制过去的，都在相同的目录内操作的话才没事……

**Comment by chengr28** [comment]
已更新
