### ISSUE TITLE
[Hosts]中白名单语句失效？

### ISSUE THREAD

**Issue by lonsx** [chengr28/Pcap_DNSProxy#126]
[Hosts]中白名单语句失效？
【是遵照的严格的先后顺序】
[Hosts]
NULL imap\.gmail\.com
NULL .*\.c\.youtube\.com
203.211.8.59 .*\.?gmail\.com
203.211.8.59 .*\.?youtube\.com
输出结果：
nslookup imap.gmail.com
服务器:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

非权威应答:
名称:    gmail-imap.l.google.cOm
Addresses:  2404:6800:4008:c05::6d
          203.211.8.59
Aliases:  ImAp.gMaIl.cOm
。。。。。。。。。。。。。。。。。。。。。。。
nslookup r11---sn-25g7sm7d.c.youtube.com
服务器:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

非权威应答:
名称:    r11---sn-25g7sm7d.c.youtube.com
Address:  203.211.8.59

**Comment by chengr28** [comment]
这个的确是程序的问题……下次更新的时候会修复这个问题

**Comment by chengr28** [comment]
不好意思拖了一段时间才更新，最近比较忙……刚才更新的版本已经修复这个问题了，可以试试w

**Comment by jxcn** [comment]
好的 马不停蹄滚去更新 菊苣辛苦

2016年3月14日星期一，chengr28 <notifications@github.com> 写道：
