### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by yuan78** [chengr28/Pcap_DNSProxy#128]
bash-4.3# cd Scripts
bash-4.3# ls
Linux_Build.sh		  Linux_Uninstall.Systemd.sh  Mac_Uninstall.sh
Linux_Install.Systemd.sh  Linux_Uninstall.SysV.sh     Update_Routing.sh
Linux_Install.SysV.sh	  Mac_Install.sh	      Update_WhiteList.sh
bash-4.3# chmod 755 Linux_Build.sh
bash-4.3# ./Linux_Build.sh
mkdir: 无法创建目录"Release": 文件已存在
./Linux_Build.sh:行35: cmake: 未找到命令
make: *** 没有指明目标并且找不到 makefile。 停止。
mv: 无法获取"Object/FileHash" 的文件状态(stat): 没有那个文件或目录
./Linux_Build.sh:行49: cmake: 未找到命令
make: *** 没有指明目标并且找不到 makefile。 停止。
mv: 无法获取"Object/KeyPairGenerator" 的文件状态(stat): 没有那个文件或目录
./Linux_Build.sh:行69: cmake: 未找到命令
make: *** 没有指明目标并且找不到 makefile。 停止。
mv: 无法获取"Object/Pcap_DNSProxy" 的文件状态(stat): 没有那个文件或目录
chmod: 无法访问"Release/FileHash": 没有那个文件或目录
chmod: 无法访问"Release/KeyPairGenerator": 没有那个文件或目录
chmod: 无法访问"Release/Pcap_DNSProxy": 没有那个文件或目录

**Comment by chengr28** [comment]
没有装 CMake 的缘故，程序编译时具体所需安装的依赖，参见 https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe_Linux(zh_Hans).txt 的介绍
