### ISSUE TITLE
CMake安装了，编译还是报错啊

### ISSUE THREAD

**Issue by yuan78** [chengr28/Pcap_DNSProxy#129]
bash-4.3# ./Linux_Build.sh
mkdir: 无法创建目录"Release": 文件已存在
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gary/Pcap_DNSProxy-master/Source/Object
Scanning dependencies of target SHA3
[  6%] Building CXX object SHA3/CMakeFiles/SHA3.dir/KeccakF-1600-compact64.cpp.o
[ 12%] Building CXX object SHA3/CMakeFiles/SHA3.dir/KeccakHash.cpp.o
[ 18%] Building CXX object SHA3/CMakeFiles/SHA3.dir/KeccakSponge.cpp.o
[ 25%] Building CXX object SHA3/CMakeFiles/SHA3.dir/SnP-FBWL-default.cpp.o
[ 31%] Linking CXX static library libSHA3.a
[ 31%] Built target SHA3
Scanning dependencies of target FileHash
[ 37%] Building CXX object CMakeFiles/FileHash.dir/Base.cpp.o
[ 43%] Building CXX object CMakeFiles/FileHash.dir/FileHash.cpp.o
[ 50%] Building CXX object CMakeFiles/FileHash.dir/Checksum.cpp.o
[ 56%] Building CXX object CMakeFiles/FileHash.dir/CRC.cpp.o
[ 62%] Building CXX object CMakeFiles/FileHash.dir/MD2.cpp.o
[ 68%] Building CXX object CMakeFiles/FileHash.dir/MD4.cpp.o
[ 75%] Building CXX object CMakeFiles/FileHash.dir/MD5.cpp.o
[ 81%] Building CXX object CMakeFiles/FileHash.dir/SHA-1.cpp.o
[ 87%] Building CXX object CMakeFiles/FileHash.dir/SHA-2.cpp.o
[ 93%] Building CXX object CMakeFiles/FileHash.dir/SHA-3.cpp.o
[100%] Linking CXX executable FileHash
[100%] Built target FileHash
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gary/Pcap_DNSProxy-master/Source/Object
Scanning dependencies of target KeyPairGenerator
[ 50%] Building CXX object CMakeFiles/KeyPairGenerator.dir/KeyPairGenerator.cpp.o
[100%] Linking CXX executable KeyPairGenerator
[100%] Built target KeyPairGenerator
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gary/Pcap_DNSProxy-master/Source/Object
Scanning dependencies of target Pcap_DNSProxy
[  5%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
In file included from /home/gary/Pcap_DNSProxy-master/Source/Pcap_DNSProxy/Structures.h:20:0,
                 from /home/gary/Pcap_DNSProxy-master/Source/Pcap_DNSProxy/Base.h:20,
                 from /home/gary/Pcap_DNSProxy-master/Source/Pcap_DNSProxy/Base.cpp:20:
/home/gary/Pcap_DNSProxy-master/Source/Pcap_DNSProxy/Platform.h:298:26: fatal error: pcap/pcap.h: 没有那个文件或目录
    #include <pcap/pcap.h>
                          ^
compilation terminated.
CMakeFiles/Pcap_DNSProxy.dir/build.make:62: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o' failed
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
mv: 无法获取"Object/Pcap_DNSProxy" 的文件状态(stat): 没有那个文件或目录
chmod: 无法访问"Release/Pcap_DNSProxy": 没有那个文件或目录

**Comment by chengr28** [comment]
**请严格按照[说明文档](https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe_Linux(zh_Hans).txt)进行操作**
说明文档中就有提到 `LibPcap 可访问 http://www.tcpdump.org/#latest-release 获取`
出错的原因是没有安装 LibPcap

顺便有相同一类的问题请在同一个 Issue 里说明，不要开多个 Issue
就算 Issue 是关闭状态也是可以回复的

**Comment by wongsyrone** [comment]
需要安装 libpcap 的头文件，不同发行版的包名不同，另外确定CFLAGS设置正确

**Comment by yuan78** [comment]
好的，多谢

2016年2月16日星期二，chengr28 <notifications@github.com> 写道：
