### ISSUE TITLE
编译完成以后还是无法使用，依赖都已经安装，请帮忙看看是什么原因？

### ISSUE THREAD

**Issue by yuan78** [chengr28/Pcap_DNSProxy#130]
编译完成以后还是无法使用，依赖都已经安装，请帮忙看看是什么原因？
gary-# ./Linux_Build.sh
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gary/Pcap_DNSProxy-master/Source/Object
Scanning dependencies of target SHA3
[  6%] Building CXX object SHA3/CMakeFiles/SHA3.dir/KeccakF-1600-compact64.cpp.o
[ 12%] Building CXX object SHA3/CMakeFiles/SHA3.dir/KeccakHash.cpp.o
[ 18%] Building CXX object SHA3/CMakeFiles/SHA3.dir/KeccakSponge.cpp.o
[ 25%] Building CXX object SHA3/CMakeFiles/SHA3.dir/SnP-FBWL-default.cpp.o
[ 31%] Linking CXX static library libSHA3.a
[ 31%] Built target SHA3
Scanning dependencies of target FileHash
[ 37%] Building CXX object CMakeFiles/FileHash.dir/Base.cpp.o
[ 43%] Building CXX object CMakeFiles/FileHash.dir/FileHash.cpp.o
[ 50%] Building CXX object CMakeFiles/FileHash.dir/Checksum.cpp.o
[ 56%] Building CXX object CMakeFiles/FileHash.dir/CRC.cpp.o
[ 62%] Building CXX object CMakeFiles/FileHash.dir/MD2.cpp.o
[ 68%] Building CXX object CMakeFiles/FileHash.dir/MD4.cpp.o
[ 75%] Building CXX object CMakeFiles/FileHash.dir/MD5.cpp.o
[ 81%] Building CXX object CMakeFiles/FileHash.dir/SHA-1.cpp.o
[ 87%] Building CXX object CMakeFiles/FileHash.dir/SHA-2.cpp.o
[ 93%] Building CXX object CMakeFiles/FileHash.dir/SHA-3.cpp.o
[100%] Linking CXX executable FileHash
[100%] Built target FileHash
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gary/Pcap_DNSProxy-master/Source/Object
Scanning dependencies of target KeyPairGenerator
[ 50%] Building CXX object CMakeFiles/KeyPairGenerator.dir/KeyPairGenerator.cpp.o
[100%] Linking CXX executable KeyPairGenerator
[100%] Built target KeyPairGenerator
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gary/Pcap_DNSProxy-master/Source/Object
Scanning dependencies of target Pcap_DNSProxy
[  5%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
[ 11%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o
[ 16%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o
[ 22%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurve.cpp.o
[ 27%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Initialization.cpp.o
[ 33%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Main.cpp.o
[ 38%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Monitor.cpp.o
[ 44%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Network.cpp.o
[ 50%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PacketData.cpp.o
[ 55%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PrintLog.cpp.o
[ 61%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Process.cpp.o
[ 66%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Protocol.cpp.o
[ 72%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Proxy.cpp.o
[ 77%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadHosts.cpp.o
[ 83%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadIPFilter.cpp.o
[ 88%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o
[ 94%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Service.cpp.o
[100%] Linking CXX executable Pcap_DNSProxy
[100%] Built target Pcap_DNSProxy

Gary <kingtopest9000@gmail.com>
8:55 (6分钟前)

发送至 我 
gary-Source # cd Release
gary- Release # ls
Config.conf  IPFilter.conf     Pcap_DNSProxy.service  WhiteList.txt
FileHash     KeyPairGenerator  PcapDNSProxyService
Hosts.conf   Pcap_DNSProxy     Routing.txt
gary-ThinkPad-X240 Release # ./Pcap_DNSProxy
./Pcap_DNSProxy: error while loading shared libraries: libpcap.so.1: cannot open shared object file: No such file or directory

**Comment by chengr28** [comment]
`部分 Linux 发行版可能还需要运行 ldconfig 刷新系统的库缓存`

**Comment by yuan78** [comment]
但是采用静态编译就好了

2016-02-22 12:03 GMT+08:00, chengr28 <notifications@github.com>:

**Comment by chengr28** [comment]
也行……最后这步无法运行是因为找不到 LibPcap 的动态链接库，因为默认编译的配置是动态链接的，装好了 LibPcap 但是程序却找不到动态链接库，有事可能是系统那边的问题，静态链接的话把整个 LibPcap 都链接进去了也就没有问题，不过如果遇到和系统里的版本对不上的情况，运行就可能出问题

**Comment by yuan78** [comment]
好的，谢谢

在 2016/2/22，chengr28<notifications@github.com> 写道：
