### ISSUE TITLE
请教一下 ：KeyPairGenerator是起什么作用的，我不搭建DNS服务器，想问下Pcap_DNSProxy客户端典型用法是怎样的

### ISSUE THREAD

**Issue by yuan78** [chengr28/Pcap_DNSProxy#131]
请教一下 ：KeyPairGenerator具体是起什么作用的？
我不搭建DNS服务器，想请问下Pcap_DNSProxy客户端典型用法是怎样的？

配置文件太长了，还没有完全看完，可能很多功能都没有用到。

如果我的需求是DNS over TCP和DNS加密，请问典型的Pcap_DNSProxy客户端用法是怎样的？谢谢！

**Comment by chengr28** [comment]
希望你如果有差不多的问题（例如使用上的疑问）能在一个 Issue 里提出来，有问题就再在同一个 Issue 里提出来，不要一个问题就开一个 Issue 这样很容易整个屏幕都是你自己的问题

**Comment by chengr28** [comment]
* 典型用法就是默认配置直接用
* 想用 TCP 的话把 `Protocol = IPv4 + UDP` 改成 `Protocol = IPv4 + UDP + TCP` 即可
* 想用 DNSCrypt 的话直接把 `DNSCurve = 0` 改成 `DNSCurve = 1` 保存并重启服务即可
