### ISSUE TITLE
Local DNS似乎无效？

### ISSUE THREAD

**Issue by AnyoeDove** [chengr28/Pcap_DNSProxy#132]
因为用了微林中转了DNS 然后发现中转阿里DNS并未走流量
用systemexplorer查看Pcap_DNSProxy的连接 发现打开国内网站（百毒微薄等）时 并没有出现链接向境内中转DNS 而是直接使用了境外DNS查询 已开启Local Main = 1 Local Routing = 1
不太会用抓包 如有需要可以抓一下试试

**Comment by chengr28** [comment]
直接装一个 Wireshark 就行，选中正在使用的网络适配器，抓一下发送域名解析请求时的数据包即可，保存了可以发送到我的邮箱里

**Comment by AnyoeDove** [comment]
应该不用抓包了 我试了Local Hosts = 1也是这样 DNS配置
IPv4 DNS Address = 208.67.220.220:443
IPv4 Alternate DNS Address = 208.67.222.222:5353|208.67.220.123:443
IPv4 Local DNS Address = 223.5.5.5:53
IPv4 Local Alternate DNS Address = 112.124.47.27:53
打开国内网站连接历史只有境外DNS的记录
![pcap_dnsproxy](https://cloud.githubusercontent.com/assets/10519576/13378820/c23a534c-de4d-11e5-96ff-374b2c180022.png)

**Comment by chengr28** [comment]
不好意思最近比较忙现在才来处理这边的事情……

抓包的结果看过，绝大部分的请求看到发现都是在反查 IP 地址的反向域名解析，这类记录两种情况都会请求境外服务器的，所以整个屏幕都被这类请求信息淹没了……建议检查一下是什么程序在疯狂请求
至于境内服务器解析看起来是正常在工作的，因为在抓包记录中看到 img.baidu.com 和 tb2.bdstatic.com 是正确请求了 223.5.5.5 没有错

**Comment by chengr28** [comment]
建议是这样……抓包的时候打开 cmd 然后直接 `nslookup 境内的域名` 这样主动触发域名解析请求，再看看抓包结果里（可以发过来）程序对于这三种情况（全不开/开 Local Hosts/开 Local Main + Local Routing）请求的处理流程……

**Comment by AnyoeDove** [comment]
= =我自己抓包分析了 localdns应该是正常的 抱歉了

**Comment by AnyoeDove** [comment]
= =我自己抓包分析了 localdns应该是正常的 抱歉了
