### ISSUE TITLE
错误：1060

### ISSUE THREAD

**Issue by jiangtao0222** [chengr28/Pcap_DNSProxy#133]
[SC] OpenService 失败 1060:

指定的服务未安装。
这是什么情况

**Comment by wongsyrone** [comment]
由于执行安装的时候会自动卸载之前的服务，如果是第一次安装由于不存在对应的服务就会出现这个提示

**Comment by chengr28** [comment]
每次安装服务的时候都会先清除以前可能残留的服务（第一次用可以直接忽略）只要按照说明文档中的测试方法测试通过，使用就没有问题

**Comment by jiangtao0222** [comment]
关键是按照文档测试不能通过，一步一步照着来的，win10 64环境，不知道哪里出的问题

**Comment by chengr28** [comment]
@jiangtao0222 或者这样吧……可以试试直接双击运行程序，看看有没有遇到程序崩溃或者生成了 Error.log 之类的日志
