### ISSUE TITLE
配置文件存在，依然出现“Parameter Error: Cannot open any configuration files.”

### ISSUE THREAD

**Issue by Yashir0** [chengr28/Pcap_DNSProxy#135]
root@localhost:~/Pcap_DNSProxy/Source/Release# ./Pcap_DNSProxy -v
Pcap_DNSProxy 0.4.5.3
root@localhost:~/Pcap_DNSProxy/Source/Release# ./Pcap_DNSProxy --lib-version
LibSodium version 1.0.9
libpcap version 1.7.4
root@localhost:~/Pcap_DNSProxy/Source/Release# ./Pcap_DNSProxy -c ./Config.conf --disable-daemon
2016-03-13 21:35:07 -> Log opened at this moment.
2016-03-13 21:35:07 -> Parameter Error: Cannot open any configuration files.
root@localhost:~/Pcap_DNSProxy/Source/Release# ls -l
total 1100
-rw-r--r-- 1 root root   4642 Mar 13 10:37 Config.conf
-rwxr-xr-x 1 root root 158253 Mar 13 03:22 FileHash
-rw-r--r-- 1 root root    341 Mar 13 03:27 Hosts.conf
-rw-r--r-- 1 root root   1497 Mar 13 03:27 IPFilter.conf
-rwxr-xr-x 1 root root  15413 Mar 13 03:22 KeyPairGenerator
-rwxr-xr-x 1 root root   1895 Mar 13 09:06 PcapDNSProxyService
-rwxr-xr-x 1 root root 554339 Mar 13 03:27 Pcap_DNSProxy
-rw-r--r-- 1 root root   1071 Mar 13 03:27 Pcap_DNSProxy.service
-rw-r--r-- 1 root root 115513 Mar 13 03:27 Routing.txt
-rw-r--r-- 1 root root 232915 Mar 13 03:27 WhiteList.txt

按照文档逐步进行，其他问题都算有因可循，到了这一步实在找不出问题出在哪，求指点。

**Comment by chengr28** [comment]
`启动时指定配置文件所在的以及程序的工作目录` —— ReadMe 里关于 `-c` 参数的介绍

意思就是这个参数指定的是程序的工作目录，不是指具体的某个配置文件
如果配置文件位于程序所在目录内，则不需要使用此参数进行指定

**Comment by Yashir0** [comment]
感谢回复，在去掉-c参数后会报Bus error，可能和环境有关吧，是运行在arm上，还是放弃好了。

**Comment by wongsyrone** [comment]
用的什么toolchain

**Comment by chengr28** [comment]
ARM 的 Bus Error 可能是底层的问题，查了下似乎是内存分配和使用的问题，内存方面是 GCC 编译时通过使用 C/C++ 库控制的，这边比较难处理……x86 平台上似乎没有此类问题
不过奇怪的是之前有人跟我说过在 ARM 上按 Linux 平台的标准编译和安装方法使用很正常，并没有遇到这个问题……或许应该是和架构还有系统等环境因素有关吧

**Comment by Yashir0** [comment]
@wongsyrone 直接执行Linux_Build.sh编译的，ReadMe里提到的工具/库除gcc5.3.0和cmake3.2.2从源安装其它都是编译安装。然而它们运行在一部旧手机上。

@chengr28 环境确实不太标准，下次换个正常的设备做这件事。谢谢你创造了这么有帮助的工具。

**Comment by wongsyrone** [comment]
你是在手机上做的编译？

**Comment by Yashir0** [comment]
是的。

**Comment by wongsyrone** [comment]
可以考虑试试buildroot编译好的交叉工具链

**Comment by wongsyrone** [comment]
Android可以参考 https://developer.android.com/ndk/guides/cpp-support.html 和 https://developer.android.com/ndk/guides/stable_apis.html

**Comment by Yashir0** [comment]
感觉是正好需要的东西，十分感谢。
