### ISSUE TITLE
关于错误日志的小建议

### ISSUE THREAD

**Issue by smounives** [chengr28/Pcap_DNSProxy#136]
Print Error可否提供可选错误等级的输出
类似“Network Error: Not any available gateways to public network.”这种错误，很多时候是本来就没网的时候会出现，但是本身不是什么大问题，能否提供一个较低等级的错误输出，不显示这些无关紧要的错误？

**Comment by chengr28** [comment]
你好，首先感谢你的建议……刚才更新的版本已经加入 `Print Log Level` 功能，可手动指定日志输出的级别，级别越高输出越详细。类似 `Network Error: Not any available gateways to public network.` 被归类到 Level 3 了，所以设置成 2 并重启服务程序就不会再输出此类错误（默认是 3）可以试试

**Comment by smounives** [comment]
正在使用中，未发现错误，感谢你_(:3」∠)_

**Comment by Justsoos** [comment]
v0.45 win10 实测，`Print Log Level`改成4，或者5 都会出错：

`[2018-10-29 xx:xx:23] -> [Parameter Error] Data format error in x:\xxx\Pcap_DNSProxy\Config.ini(Line 10).`

**Comment by Justsoos** [comment]
…… 还以为 4，5能记录被污染dns细节呢。
这2 楼28 小盆友的说法，看起来 3 不过是个中值啊。竟然是终值……

**Comment by chengr28** [comment]
```
  * Print Log Level - 指定日志输出级别：留空为 3
    * 0 为关闭日志输出功能
    * 1 为输出重大错误
    * 2 为输出一般错误
    * 3 为输出所有错误
```
并没有其它的选项……
