### ISSUE TITLE
请问下，Pcap_DNSProxy 支持类似 dnsmasq 中的 指定域名走指定 DNS 解析功能麽？

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#137]
类似于 dnsmasq 中的下面这个配置的功能：
server=/abc.xyz/1.2.3.4

实现 abc.xyz 通过 1.2.3.4 DNS 服务器解析，不知道 Pcap_DNSProxy 有没有类型功能？在文档中好像没看到有相关的配置

**Comment by chengr28** [comment]
之前就有人建议过这个功能，但是考虑到程序请求的架构不太可能实现
而且与其这样指定某个域名的 DNS 服务器，还不如直接写个 Hosts 更好

**Comment by chengr28** [comment]
和 https://github.com/chengr28/Pcap_DNSProxy/issues/146 合并处理

**Comment by Incubator85653** [comment]
从最新情报来看，"Config.ini" 中的：

[Addresses]
IPv4 Local DNS Address = 
IPv4 Local Alternate DNS Address = 

可作为某"些"域名的专用服务器，把这些域名放到"Hosts.ini"后，
修改 "Config.ini" 中的：

[Local DNS]
Local Force Request = 1
Local Hosts = 1

就可以达到几乎一致的效果。
如果单一服务器位置无法满足需求，可垫一个 unbound 再进一步指定域名交给哪些服务器处理。

**Comment by Incubator85653** [comment]
@chengr28 "之前说的架构问题，主要是程序设计的时候是一主一从固定的服务器"
对于这一点的看法，我认为再垫一个 unbound 可使从服务器变为数个服务器组合。
可能架构就不必大改了吧。

**Comment by jzp820927** [comment]
组合要组合其他 DNS SERVER 软件的话，就可以实现很多种可能性了，之前是想的，能不能把功能集成一个软件中。

**Comment by Incubator85653** [comment]
@jzp820927 我写软件的思路是一个可执行文件只处理一件事情，复杂功能就是许多可执行文件搭配，用launcher组合起来的形式。这点也适用于将各种散落的二进制组合起来实现功能，比如在这里 pcap dns proxy 的分流功能起作用，多服务器功能由 unbound 提供。
而 pcap dns proxy 根据之前的说法难以改动，那么在一段时间内专注于增加多个服务器支持这种复杂改动，就无法专注于它的核心功能。

另外在程序设计角度来看，我不是很认同“一个软件把所有事情都做了”，因为人的精力有限，最后往往什么都做不好。一个典型的例子是 UNIX 系中的 tar 和 gz 之间的关系，其中 tar 专注于文件打包，而 gz 专注于压缩数据，同时，tar 和 gz 也分别单独被许多其他软件依赖：有时只需打包不需压缩，有时文件只有1个。实现一次完整的打包和压缩时，其实是首先用 tar 打包文件，然后放进 gz 压缩。tar 的开发者不需要考虑如何压缩文件，gz的开发者也不需要考虑如何将复数个文件打包在一起。

在非商业开源开发中，这样更能节省每个开发者的时间，去优化他们的核心功能。

**Comment by jzp820927** [comment]
其实我目前的DNS 服务器，也是通过 3，4 个软件实现我要的功能的，一个软件确实很难满足所有要求。而且我觉得 pcap 对高并发，高查询量的环境下，稳定性，没有 dnsmasq 好。

**Comment by chengr28** [comment]
拖得有点久了，不过刚才推送的更新已经添加这个功能了，参见 ReadMe 文档中 `Dnsmasq Server - Dnsmasq 兼容格式` 一节的内容。不过需要注意的是启用本功能后，指定 DNS 服务器后只有有限的过滤 DNS 投毒污染的能力，只建议需要 `Local Hosts` 功能的请求使用

**Comment by jzp820927** [comment]
@chengr28 谢谢，马上更新测试。对了支持像下面这种非标准格式的端口吧？masq 是支持的。这也兼容了麽？
server=/abc.xyz/1.2.3.4#5353

**Comment by chengr28** [comment]
@jzp820927 肯定是支持的……这个功能照着 Dnsmasq 的格式做，功能基本都有

**Comment by jzp820927** [comment]
恩，刚刚看 readme 看到了，挺不错的，谢谢！
