### ISSUE TITLE
关于 Hosts.conf 配置文件的一个建议。

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#138]
当前的 Hosts 配置是全部保存在一个 Hosts.conf 文件里面的，我想能不能想 dnsmasq 一样，通过下面这个配置指定一个配置目录，然后可以把 Hosts 的配置数据分离到目录下面的多个配置文件：
conf-dir=/etc/dnsmasq.d

我提这个建议，主要是有一个需求，我的 pcap_DNSProxy 运行在 LInux 下面，有某几个 域名，我需要通过脚本(脚本是自己写的) 在 Hosts.conf 配置文件里面，很频繁的动态更新 IP地址，按照目前的设计模式，一个  Hosts.conf 配置文件的话，我就需要通过脚本文件去文件里面去定位需要更新域名的位置，比较麻烦，而且一旦脚本定位出错，可能导致整个 Hosts.conf 配置文件出错。

如果能像 dnsmasq 一样，分离成多个配置文件，我就可以把需要通过脚本更新的域名，单独写在另一个 Hosts 文件里面，然后脚本只更新这个文件，就不会影响其他 hosts 配置数据。而且也不用去定位，脚本实现起来就很方便了。

不知道我这个想法能不能实现？或者 chengr28 兄，有什么更好的建议嘛？谢谢！

**Comment by chengr28** [comment]
参见 ReadMe 文档中对 `Additional Path` 和 `Hosts File Name` 参数的介绍

**Comment by jzp820927** [comment]
Additional Path 不支持相对路径麽？比如和 Config.conf 在同一目录下面的 配置文件，Additional Path 不能用 . 或者留空表示麽？

**Comment by chengr28** [comment]
`Additional Path` 是附加读取路径的意思……程序读取到的配置文件所在目录的其它文件是无论如何都会被读取到的，不受这个参数的影响，这个参数留空等于没有附加读取路径。至于你说的相对路径，这个功能本来就是设计给可以读取放在别处的文件，只支持相对路径岂不是把这个功能废掉了……
当然你说如果输入相对路径能不能工作，因为程序只负责传递参数，真正打开文件用的是系统的 API 所以你可以试试看有没有效果，这个要看系统是怎样处理的了

**Comment by jzp820927** [comment]
你好，前几天有点事在忙，一直没测试，今天试了下，配置 Additional Path 和 Hosts File Name，好像配置文件没有生效，具体过程如下：
首先我在 Release 目录下新建了一个 conf 目录，作为存放 Hosts 文件的目录，然后再 conf 下面新建 test.conf 文件，里面写入域名的 hosts 配置，然后编辑 Config.conf 文件，修改 Additional Path = conf目录路径 (相对路径和绝对路径我都试过了)，添加 test.conf 配置文件到 Hosts File Name 选项，然后测试 test.conf 文件里面的域名解析结果，和我配置的不一样，也就是说配置没有生效。

然后，我又把 test.conf 文件从 conf 目录下移动到 Release 目录下，把 Additional Path 留空，然后测试配置生效了，也就是说 Additional Path 选项默认留空，当前目录的配置文件没有问题，添加路径后，则不能生效，还请检查下，是 BUG？还是我的操作错误？
