### ISSUE TITLE
hosts.ini中local host部分不生效

### ISSUE THREAD

**Issue by shuangzhijinghua** [chengr28/Pcap_DNSProxy#14]
.*\.taobao\.com
解析www.taobao.com得到的结果是

服务器:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

非权威应答:
名称:    www.gslb.taobao.com.danuoyi.tbcache.com
Addresses:  66.102.255.41
          66.102.255.51
Aliases:  www.taobao.com

海外的服务器.

用本地DNS查询:
> www.taobao.com
服务器:  cache.nn.gx.cn
Address:  202.103.224.68

非权威应答:
名称:    www.gslb.taobao.com.danuoyi.tbcache.com
Addresses:  116.253.191.251
          171.107.80.41
          116.253.191.241
          171.107.80.51
Aliases:  www.taobao.com

延迟仅9ms.是哪里出错了吗?

config.ini

IPv4 Listen Address = 
IPv4 DNS Address = 208.67.222.222:443|208.67.220.220:443|8.8.8.8:53|8.8.4.4:53
IPv4 Alternate DNS Address = 74.82.42.42:53
IPv4 Local DNS Address = 202.103.224.68:53
IPv4 Local Alternate DNS Address = 202.103.225.68:53

**Comment by chengr28** [comment]
最近的 Beta 开始使用 Local Hosts 功能要在配置文件里打开，参见 https://github.com/chengr28/Pcap_DNSProxy/wiki/ReadMe(Chinese_Simplified)#local-hosts---%E5%A2%83%E5%86%85-dns-%E8%A7%A3%E6%9E%90%E5%9F%9F%E5%90%8D%E5%88%97%E8%A1%A8 的内容
`要使用本功能，必须将配置文件内的 Local Hosts 选项打开！`

而且就准确性来说……那个正则表达式应该是 `.*\.taobao.com` 才对
句点在正则表达式里是另外的意思

**Comment by chengr28** [comment]
哦对了其实你不需要一个问题就开一个 Issue 的，特别是之前还开过一个
或者直接用邮箱联系我，得到的答复可能会比这里开 Issue 快

**Comment by yfdyh000** [comment]
@chengr28 独立问题开独立的issue是好习惯吧，便于管理和其他人搜索和阅读。
28不是watch了项目吗，新issue会有邮件通知吧。

**Comment by chengr28** [comment]
@yfdyh000 也是ww

**Comment by shuangzhijinghua** [comment]
其实之前就想在原来的issue里面继续写，不过总感觉有点不太合适，毕竟两个不一样的问题。

**Comment by shuangzhijinghua** [comment]
另外有个性能方面的问题，我设置的opendns走的是443端口，实测用netsh int portproxy add v4tov4 listenaddress=127.0.0.1 listenport=53 connectaddress=208.67.222.222 connectport=443这样的端口转发方式查询速度快很多，而且没有污染。

**Comment by chengr28** [comment]
邮件收到了吗？

**Comment by shuangzhijinghua** [comment]
呃，刚看到。
