### ISSUE TITLE
关于 Additional Path 的问题？

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#140]
@chengr28 你好，前几天我在 https://github.com/chengr28/Pcap_DNSProxy/issues/138 中提出的问题，按着你的指导配置了一下，但是出现了一些问题，，配置的 Additional Path 和 Hosts File Name，好像配置文件没有生效，具体情况如下：

首先我在 Release 目录下新建了一个 conf 目录，作为存放 Hosts 文件的目录，然后再 conf 下面新建 test.conf 文件，里面写入域名的 hosts 配置，然后编辑 Config.conf 文件，修改 Additional Path = conf目录路径 (相对路径和绝对路径我都试过了)，添加 test.conf 配置文件到 Hosts File Name 选项，然后测试 test.conf 文件里面的域名解析结果，和我配置的不一样，也就是说配置没有生效。

然后，我又把 test.conf 文件从 conf 目录下移动到 Release 目录下，把 Additional Path 留空，然后测试配置生效了，也就是说 Additional Path 选项默认留空，当前目录的配置文件没有问题，添加路径后，则不能生效，还请检查下，是 BUG？还是我的操作错误？

我头天已经在 https://github.com/chengr28/Pcap_DNSProxy/issues/138 回复过以上内容了，但是没看到你的回复，怕你没有看到。所以对这个问题，新开一个 issues，还麻烦你看看是什么问题。

**Comment by chengr28** [comment]
你好，首先感谢你的反馈……Additional Path + Hosts File Name + IPFilter File Name 这3个参数之前的版本的确是有 bug 导致不能正常生效，刚才更新的版本已经修复，可以试试w

**Comment by jzp820927** [comment]
你好，刚刚用最新的源码编译测试了，但是好像还是没有生效，不知道你有没有测试过？谢谢。

**Comment by chengr28** [comment]
呃……看来还是得多抽点时间在平通平台看看的

**Comment by jzp820927** [comment]
哦，那我说下我的平台信息吧：
我的操作系统是：Ubuntu Server 15.10

**Comment by chengr28** [comment]
是这样……之前的修复是把 Windows 平台下的 `Additional Path` 修复好了，不过实测发现 Linux/Mac 两个受支持的平台（严格来说应该是 Unix 文件系统）的路径处理有问题，所以这里其实是有2个 Bug 混在一起了……感谢反馈，刚才更新的版本已经修复

**Comment by jzp820927** [comment]
再问一下，Additional Path = 的路径配置，是只针对 Hosts File Name 有效？还是同时对 Hosts File Name 和 IPFilter File Name 都生效？比如，我在 Additional Path 设置了独立的配置文件目录，然后我把 Hosts File Name 下面的配置文件，都移动到这个目录，Hosts 配置就会生效。但是 IPFilter File Name 配置中的 IPFilter.conf 和 Routing.txt 配置文件，我是也要同时移到到 Additional Path 配置的目录下？还是直接放在默认位置，也会自动读取？

**Comment by chengr28** [comment]
出现在 `Additional Path` 里的路径里所有为 `Hosts File Name` 和 `IPFilter File Name` 文件名的配置文件都会读取

**Comment by jzp820927** [comment]
那也就是说，我还要把 IPFilter.conf 和 Routing.txt 也移动到 Additional Path 目录里，不然就读取不到了。

**Comment by chengr28** [comment]
明明就是都能读取到的意思……

**Comment by jzp820927** [comment]
好吧，那就是我理解錯了，不好意思。
