### ISSUE TITLE
CNAME Hosts 多 ip 问题 

### ISSUE THREAD

**Issue by debugzxcv** [chengr28/Pcap_DNSProxy#142]
在 Hosts.conf 文件 [CNAME Hosts] 节加入：
``23.235.33.133|103.245.222.133 ^github\.map\.fastly\.net$``

然后在浏览器里访问 [https://assets-cdn.github.com/images/icons/emoji/unicode/1f389.png](https://assets-cdn.github.com/images/icons/emoji/unicode/1f389.png)
会出现域名无法解析错误。不过只要改成 ``23.235.33.133 ^github\.map\.fastly\.net$`` 就可以解析了。

**Comment by jzp820927** [comment]
这个应该是 hosts 规则吧，你直接配置 hosts 规则就行了

**Comment by debugzxcv** [comment]
> 这个应该是 hosts 规则吧，你直接配置 hosts 规则就行了

这是 **CNAME Hosts**

**Comment by jzp820927** [comment]
确实是  CNAME Hosts，但是刚刚我测试了 CNAME Hosts 在 多个 IP 的情况下没啥问题。

**Comment by debugzxcv** [comment]
额外信息：
默认配置文件

设置多 IP 下 dig 的输出，期望是返回多个 A 记录
```
bind>dig assets-cdn.github.com
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.10.3 <<>> assets-cdn.github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18866
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: Message has 9 extra bytes at end

;; QUESTION SECTION:
;assets-cdn.github.com.         IN      A

;; ANSWER SECTION:
assets-cdn.github.com.  24      IN      CNAME   github.map.fastly.net.
github.map.fastly.net.  900     IN      A       23.235.33.133

;; Query time: 369 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Apr 05 20:49:21 中国标准时间 2016
;; MSG SIZE  rcvd: 101
```

**Comment by jzp820927** [comment]
我这儿 dig 可以返回我配置的多个IP

dig assets-cdn.github.com -p 5353 @127.0.0.1
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 28381
;; Flags: qr rd ra; QUERY: 1; ANSWER: 7; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; assets-cdn.github.com.       0       IN      A

;; ANSWER SECTION:
assets-cdn.github.com.  900     IN      A       103.245.222.133
assets-cdn.github.com.  900     IN      A       23.235.33.133

;; Received 151 B
;; Time 2016-04-06 00:05:49 CST
;; From 192.168.12.108#5353(UDP) in 0.8 ms

**Comment by debugzxcv** [comment]
你设置文件 Local Hosts 和 Local Main 是什么值？
我发现必须要设置 Local Hosts = 1 才能获取期望结果

**Comment by jzp820927** [comment]
@debugzxcv 
[Local DNS]
Local Hosts = 1
Local Main = 0
Local Routing = 0

这是我的配置。

**Comment by debugzxcv** [comment]
你把 Local Hosts = 0 再 dig 看看

**Comment by jzp820927** [comment]
你的意思 3个全部 0？还是 Local Hosts = 0 后面2个是 1？

**Comment by debugzxcv** [comment]
不用试了，感觉是和网络有关

**Comment by jzp820927** [comment]
和网络有关？莫非你的 pcap 不是运行在本机上的？

**Comment by debugzxcv** [comment]
我现在的情况是：
Local Hosts = 0
Local Main = 1

这样设置才能在大部分时候获取期望的结果，偶尔会有 https://github.com/chengr28/Pcap_DNSProxy/issues/142#issuecomment-205791281 这样的错误

**Comment by jzp820927** [comment]
那确实不知道了，我这儿没这问题，那你找找你说的网络问题吧

**Comment by debugzxcv** [comment]
好吧，终于找到了一个暂时解决 CNAME Hosts 多 ip 问题的办法：
设置文件里启用**直连模式**
```
[DNS]
Direct Request = IPv4 + IPv6
```

只能用**直连模式**才能使 CNAME Hosts 获取期望的结果

**Comment by debugzxcv** [comment]
分别在**直连模式**和**非直连模式**下抓的包
[dumpfile.zip](https://github.com/chengr28/Pcap_DNSProxy/files/207601/dumpfile.zip)

**Comment by jzp820927** [comment]
直连模式，不是交给系统来处理 DNS 的吗，那不和没用 pcap 一样了

**Comment by chengr28** [comment]
`Warning: Message parser reports malformed message packet.`
看到了这句，可能是程序处理数据包有问题，这边有时间会看看

**Comment by chengr28** [comment]
最近比较忙现在才回复真是抱歉……关于这个 Issue 的问题，经过分析需要满足『抓包模式』和『同时指定2个及以上地址的 CNAME Hosts』才会触发，是程序本身设计的问题。刚才更新的版本已经修复，可以去试试w
