### ISSUE TITLE
DNSCurve 的服务器设置段能否考虑支持 dnscrypt-resolvers.csv

### ISSUE THREAD

**Issue by rampageX** [chengr28/Pcap_DNSProxy#144]
也就是  [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy) 项目带的那个服务器数据文件，这样可以简化配置 DNSCurve 的步骤。

**Comment by jzp820927** [comment]
这个想法不错，不知道能不能实现，支持一下吧

**Comment by chengr28** [comment]
关于这个，我的想法是通过配置文件控制具体所需的两个服务器。因为程序的设计模型是一主一从，就算把整个 csv 读取进去也没有用……所以直接让用户选一下可能比较好

**Comment by yfdyh000** [comment]
可以弄一个helper的程序快速设置吧，自动获取，输入序号选择，乃至自动测试。

**Comment by rampageX** [comment]
@chengr28 我的意思是加入需要切换服务器只需要填一个短的名称，例如 cisco，cloudns-syd 等等，其他对应信息直接从 csv 读进去了，不需要自己去复制一堆 IP 地址，指纹什么的。

**Comment by chengr28** [comment]
@rampageX 嗯我知道，刚才说的『通过配置文件控制具体所需的两个服务器』就是通过填入行号（刚才的想法）或者短名称读取，只是短名称的话可能会有重名的问题..

**Comment by jzp820927** [comment]
通过 csv 文件里面的行号，选择服务器，其他信息通过行号从 csv 文件读取，这个方案不错。

**Comment by angle1895** [comment]
大家都能用？只有电信不能用dnscrypt-resolvers.csv？只有opendns有效，其他都出错

**Comment by chengr28** [comment]
@angle1895 其实大部分都可以，只是服务器本身位置太偏，或者天朝出口不好，造成解析延迟和丢包的情况很严重而已……

**Comment by jzp820927** [comment]
只要没有封锁IP，基本上都可以用，没啥问题

**Comment by chengr28** [comment]
呃好像这个功能拖得有点久了……这次更新已经加上。主要还是觉得读取 `dnscrypt-resolvers.csv` 和直接写到配置文件里是一步之差，不过既然觉得能方便用户加上也不错。关于这个功能的介绍可以阅读 ReadMe 说明文档中关于 `DNSCurve Database` 一节的介绍。有几点需要注意的是：
- 暂时还没自带这个 csv 文件，想用的话直接放到配置文件的目录重启服务即可。
- csv 的优先级比配置文件里的要高，对 csv 的选择会覆盖配置文件里的配置。
- 有限度的自动文件内容刷新，就是说说明文档里有列到支持自动刷新的参数（例如 Public Key）就能自动刷新，不支持自动刷新的参数（例如服务器地址之类）就算使用 csv 也不会自动刷新，需要重新启动服务。

**Comment by chengr28** [comment]
@yfdyh000 感觉这个不太像是本项目需要提供的功能……其实如果不能用了程序也会报错，用户应该就会去调查和更换，或者另外再下一个官方的工具做测试也是可以的，现在的环境也不太计较延迟，能用已经万事大吉了 =_/=

**Comment by jzp820927** [comment]
哈哈，终于支持 dnscrypt-resolvers.csv 了，看来必须升级了，都跳过好几个版本没升级了，太懒了。

**Comment by chengr28** [comment]
@jzp820927 关于自动刷新你的理解可能有问题……csv 的自动刷新和配置文件的自动刷新机制是一样，是在文件有变动的时候（例如修改了部分参数，上面有说）才会自动刷新，如果服务器失效则只会报错提醒用户进行检查。所以实际上直接改配置文件也是能做到自动刷新的，只是说通过 csv 用户需要改的地方（只需要填入 DNSCrypt Name 字段）比修改配置文件（需要填入地址服务供应商域名和公钥）少了很多步骤而已……
关于任何从服务器自动更新的问题，程序本身是不会集成的，主要是考虑到不想依赖任何需要长久提供服务的网页，这方面或许以后可以写个脚本之类的简化更新的步骤，而且暂时还没有计划自带这个 csv 文件。

**Comment by jzp820927** [comment]
好吧，我就无意中想到的，这个不影响使用，没有计划就算了。感谢回复。
