### ISSUE TITLE
默认Config.ini下报Data length error in line 9

### ISSUE THREAD

**Issue by AnyoeDove** [chengr28/Pcap_DNSProxy#145]
使用旧版配置报错 直接使用默认配置文件也报错
2016-04-06 11:33:24 -> Parameter Error: Data length error in line 9 of F:\Users\Administrator\Desktop\Proxy\Pcap_DNSProxy\Config.ini.

**Comment by jzp820927** [comment]
看提示，好像是 数据长度错误，在第 9行，你是不是第9行内容太长了，按作者说的，一行内容不能超过 4K

**Comment by AnyoeDove** [comment]
@jzp820927 看清楚好嘛 我直接用了默认配置也报了这个错误

**Comment by wongsyrone** [comment]
这个正在处理

**Comment by chengr28** [comment]
这个应该是程序的问题……0.4.5.5 修改了一下内部的处理过程，大概不同情况下有出错的机会，这边会尽快修复……

**Comment by chengr28** [comment]
刚才发了新的版本，应该是修复好了……和 https://github.com/chengr28/Pcap_DNSProxy/issues/143 那边是同一个问题
