### ISSUE TITLE
功能请求，增加一个域名列表规则，其中的域名由一个特定的 DNS 服务器解析。

### ISSUE THREAD

**Issue by Incubator113704** [chengr28/Pcap_DNSProxy#146]
例如目前已在 whitelist 中的数个 google 相关域名，以及 office365 、 windowsupdate 等。
这些域名或许不应从 whitelist 中移除，但如果有一个自定义的列表来自行决定哪些域名从特定 DNS 解析会更易于使用。

此外，有时想要使用某个网络服务的国际版时，便不应通过 whitelist 的国内 DNS 解析它们。

一个典型的例子：非全局代理情况下 google 通过 Los Angels 的运营商访问时，Pcap_DNSProxy 认为域名在白名单中而将这个域名交给本地【无污染】的 DNS 解析，从而返回了香港的【有效】 IP 而不是 Los Angles 的 CDN；与此同时该 IP 地址通过本地运营商无法访问。(这个计划外的行为使加速变为了阻挡)

目前的临时 workaround 是从 WhiteList.txt 中逐条移除每个域名和子域名，但每次更新后重新编辑成本巨大，因此这个用户认为我们有方法可以容易的取得一个网络服务使用的所有子域名，那么将这些域名全部由远程解析是一个更好的办法；然后增加一个单独列表使它们更易于维护。

**Comment by jzp820927** [comment]
https://github.com/chengr28/Pcap_DNSProxy/issues/137

我以前就提出过这个功能(上面链接)，老大说，目前的架构不太可能实现这个功能，你就死心吧。不过赶脚这个功能的需求量还是挺大的。

**Comment by Incubator113704** [comment]
看起来自己定义 Whitelist.txt 而不跟随主版本更新是更好的选择，这已经差不多解决了问题，总之谢谢提醒未来更新没有这部分。

**Comment by wongsyrone** [comment]
本身程序配置就是高度灵活的，给出的配置文件只是示例，目前是用附带的工具生成的，自己定制的部分自己保留就行了

**Comment by jzp820927** [comment]
@Incubator113704 如果你用 linux 的话，这个就很简单的，自己写个 bash 脚本，很容易搞定的！

**Comment by chengr28** [comment]
后来认真考虑了一下其实也是可以的……只是工作量的确比较大
之前说的架构问题，主要是程序设计的时候是一主一从固定的服务器，防投毒污染的策略很多也是针对固定数量的服务器，所以加入此功能也可以，只是用的时候会和直连模式一样不能防止投毒污染的问题。不过既然有需求也是可以试试的，而且似乎对这个功能需求的都是针对 CDN 类的解析请求而不是需要防止投毒污染的解析请求

**Comment by jzp820927** [comment]
防污染一般都可以考固定 hosts 手动解决，但是CDN确实是个大问题，不容易能够手动解决。
既然老大都说了有希望能实现，还是比较期待的，请问这个功能其实还说挺有用的，比如谷歌有部分在中国的服务域名，用 正则指定 hosts 后，就不好控制了。如果能够实现这个功能，就可以把这部分域名单独指定国内 DNS 解析。
我觉得这实现上，只要增加一个请求转发功能就可以了吧，对特定的域名把 DNS 请求，转发给上游 DNS 服务器，类似于 DNS 代理。

**Comment by rampageX** [comment]
说实话我没明白这个需求的意思，开启 Local Hosts = 1 后，难道 Whitelist.txt 里面的域名不是通过

    IPv4 Local DNS Address = 

    IPv4 Local Alternate DNS Address = 

这两个指定服务器解析的？而这两个指定服务器肯定就是填国内质量较好的服务器或者是当地 ISP 服务器，CDN 完全没问题啊。

难道不是？

**Comment by jzp820927** [comment]
* 请求域名解析优先级
  * 直接使用网络适配器设置进行域名解析（小部分）：Pcap_DNSProxy 的 Hosts 配置文件（Whitelist/白名单条目 > Hosts/主要 Hosts 列表） > DNS 缓存 > Local Hosts/境内 DNS 解析域名列表 > 远程 DNS 服务器

Local Hosts 的优先级太低了，很多情况匹配不到。

**Comment by Incubator113704** [comment]
baidu.com 由1.2.4.8:53解析
taobao.com 由1.2.4.8:53解析
zhihu.com 由1.2.4.8:53解析

google.com 由127.0.0.1:19053解析
bing.com

**Comment by jzp820927** [comment]
@Incubator113704 没看懂，你这是要表达神马意思，是设计方案么？

**Comment by Incubator113704** [comment]
@jzp820927 这是这个 issue 想要 pcap dns proxy 做的事情， 其中127.0.0.1:19053是另外一个自建 DNS，对特定域名会返回优化后的 IP。
所以 pcap dns proxy 目前需要的改进是， 收到一个 DNS 请求， 匹配一下特定列表，在列表中，则交给 127.0.0.1:19053 这种自建DNS， 如果不在列表中 交给首选 DNS 比如1.2.4.8正常解析。

如果在程序方面难以改进，另一个临时解决方案就是从 whitelist.txt 中逐条移除特定的那些域名。也可以达到一样的效果。

**Comment by jzp820927** [comment]
哦，那和我上面的想法基本上一样，看老大怎么实现吧

**Comment by rampageX** [comment]
Pcap_DNSProxy 在反污染的逻辑上做的太复杂，而且这个 `Pcap` 的优势没看出来。

其实这类软件有一个很简单的逻辑，就是在保证网站 CDN 正确优化的情况下，还能解析被污染的网站域名。在 fakeip 列表失效的情况下，要判别网站域名是否被污染，目前能使用的技术就是靠国内域名列表，国内路由表或者 gfwlist 列表，当然还有抓包，这个是 Pcap 特有的功能。那么意味着我们必须而且最少要有两组 DNS 服务器，一组是本地 ISP 服务器，也可以是 114，223 这些比较可靠的国内服务器，还一组就是境外用来处理被污染域名的服务器，目前比较靠谱的就是非标端口的境外服务器例如 OpenDNS:5353，或者是通过 ss-tunnel，dns2socks 连接远程 shadowsocks 创建的本地服务器。

如何正确的`分流`到这两组服务器？

我们对比目前能用在反污染上的几个同类软件： DNSMASQ，Unbound，Pdnsd，dnsforwarder，ChinaDNS，SANs 和 Pcap_DNSProxy：

1. 在 fakeip 列表无效后，dnsmasq，Unbound，Pdnsd，dnsforwarder 基本就是靠 dnsmasq-china-list 或者 gfwlist 这种黑白名单来分流，可以只用一个列表，也可以混合使用。这个方法其实用起来简单粗暴，可以自己定一个例外名单，脚本更新时通过 sed 加载移除例外名单中的域名；

2. ChinaDNS 则用了指针+延时配合国内路由表来实现，这里有个不确定的因素就是延时的设置，根据网络状况不一样。

3. SANs 其实很巧妙，作者发现向境外 DNS 服务器查询被污染域名的 SOA 时，也会返回 A ，于是利用这个特征来分流。缺陷是在一些局域网里面，特别是局域网内有其他共享上网服务器时，会修改/修正这种结果，导致判断失败；

4. 我们来看看 Pcap_DNSProxy。原本第一次看到 Pcap_DNSProxy 有抓包功能时，我觉得这才是终极方案，所以即使内存占用比其他各款都高很多（相对路由器这种设备来说），我还是很积极的去测试。

然后发现配置文件中各种费脑的字段。。。各种优先级。。。各种组合，特别看到还有 `直接使用网络适配器设置进行域名解析（小部分）`，我就疯了，意味着调试 Pcap_DNSProxy 我要关掉其他所有同类软件，因为在 dnsmasq （local:53）中我设置的是并发向这几个软件一起查询。

关键的关键，我没看到大头 Pcap 作用在哪？如果有抓包，应该是不需要任何列表的？

也许我只是理解不了作者的思路:（

**Comment by chengr28** [comment]
@rampageX 那是因为你没看到过出版的 Pcap_DNSProxy……当年设计的时候是很简单的方案，就是通过抓包在网络层根据一批特征过滤数据包，抓取正确的结果以避免投毒污染。但是正如你所说的一大段话一样，当发出来后不断有人请求添加功能『各种优先级...各种组合』所以后来就改变策略成了大而全的功能合集：
* SOCKS 协议支持：这个功能程序加进去了
* 靠 dnsmasq-china-list 或者 gfwlist 这种黑白名单来分流：这个功能程序加进去了
* 指针+延时配合国内路由表：这个功能程序加进去了
* 作者发现向境外 DNS 服务器查询被污染域名的 SOA 时，也会返回 A：这个策略程序也有

**Comment by Incubator113704** [comment]
@rampageX @chengr28 还是认为 DNS 解析这个事情，抓包啊，规则啊，其实是把简单的事情做复杂了。比如目前，我的做法是采用双 DNS 暴力代理，国内域名通过 pcap dns proxy 发送到1.2.4.8进行查询和返回，国外域名一律通过 pcap dns proxy 发送到127.0.0.1:19053，19053是一台基于 unbound 的 DNS 远程解析服务器，它会返回 Los Angles 本地运营商一致的美国当地 DNS 查询结果。当然是无污染和 CDN 正确的（这个远程 DNS 解析具体如何实现不在这个问题的讨论范围内）。
这种做法同时保证了无污染和 CDN 加速，而遇到的问题就是 pcap 还不能很好的支持自定义 CDN 域名列表。比如本应交给 Los Angles 查询的 google.com 、 amazonaws等被发给了1.2.4.8。

pcap dns proxy 是为了实现这个目的的几乎最优选择，当然还差一点点。
这个做法它被提出来的原因是，HTTP 代理不支持 DNS 远程解析而 SOCKS5 支持（为什么采用了 HTTP 方案也不在这个问题的讨论范围内），在使用 HTTP 非全局代理的情况下，访问淘宝等国内网站通过国内指定 DNS 加速，而国外 IP 和域名通过 HTTP 访问，这时由于 HTTP 不支持远程 DNS 解析，请求会发给系统（国内） DNS 从而返回国内结果导致缓慢甚至阻断。
pcap dns proxy 内置了一个列表，其中包含了许多国内网站，它们的 DNS 请求会被发给国内 DNS 进行解析，而国外不在这个列表中的域名就会发给自建的 19053 DNS 解析，兼顾 CDN。
当然这个列表目前来看还是包括了一些国外域名的，我并不是说这个列表有问题，只是表达一种情况就是这个列表中的某些域名不适合一些特殊情况，对于这个特殊情况需要特殊的处理一下，增加第二个列表或从列表中自动移除都是可供选择的方案。

**Comment by chengr28** [comment]
@rampageX 所以到后来的设计思路变成了『尽量满足各种自定义工具的需求，在此基础上制作一份普遍适用的默认配置』就是说有能力的可以去研究，没有能力的直接拿来用也不会有问题，所以我才写了一遍大而全的说明文档。因为不写，总会有人来问；写全了，又会有人来说复杂看不懂。但没有办法啊，既然功能都在不写是没有道理的，所以就有了现在这种方案

具体到你的问题：
* 『意味着调试 Pcap_DNSProxy 我要关掉其他所有同类软件』这个完全是误解……所有程序要提供服务必须占用一个套接字（地址+端口）这部分是完全可以通过配置文件修改的（监听地址+监听端口）不存在占了其它同类软件就用不了的情况（除非是大家都要占 53 端口这样，那么就是先到先得）
* 『直接使用网络适配器设置进行域名解析（小部分）』这个里面想表达的意思是：系统里大部分程序通过系统 API 进行域名解析，也有部分程序可能会直接读取网络适配器的 DNS 地址请求，如果直接通过 DNS 地址请求就会绕过系统 Hosts 直接发到程序上而已，没有任何其它的意思，下次更新或许可以修改一下这边的措辞
* 『有抓包，应该是不需要任何列表的』这个的确是没有错……但有个非常现实的问题，就是抓包并不能解决 CDN 的问题？抓包只能确保拿到的结果是真实有效的，但并不能保证 CDN 是 100% 正确的，这个和使用的 DNS 服务器有关，所以才会有不同分流境内外域名解析的方案

**Comment by wongsyrone** [comment]
分流的部分应该交给其他应用来完成，做好DNS污染这部分应该是Pcap_DNSProxy的主业，KISS

**Comment by Incubator113704** [comment]
@wongsyrone 严格来说， pcap dns proxy 是我找到的唯一一个【易于配置的】具备分流能力的自建 DNS 服务器工具。当然 unbound 也可以写几千行 forward-zone。难以维护。
此外 pcap dns proxy 更直接具有国内 DNS 白名单，它可用于国内加速，被它过滤掉的国外域名还可以通过特定的备用 DNS 进行国外加速，Awesome!

**Comment by chengr28** [comment]
@Incubator113704 以前 Pcap_DNSProxy 内置的表是这边专人负责更新的，后来经过讨论发现如果需要专人维护并不好（项目本身不是应该做这个，其次也有其它项目有更好更完善的维护）所以才写了个（在 `Tools\Update_WhiteList` 目录里）自动从 dnsmasq-china-list 下载并转换成可识别格式的批处理/脚本自动处理这个问题，所以白名单匹配存在的问题，很大程度也是 dnsmasq-china-list 的问题

**Comment by Incubator113704** [comment]
@chengr28 这就是问题所在了。最后一个确认的事情是 pcap dns proxy 的未来更新中，是否会包括一个列表或工具来过滤或去掉那个 dnsmasq-china-list 中的国外服务域名？
如果不会做这部分的话我可以现在就开始制作相关工具，有的话继续等待更新就好。

pcap dns proxy 和其他工具之间互相配合的能力很不错:)
例如我没有用 TCP/DNSSEC/DNSCRYPT 等方案取得防污染 IP，而是用了自建远程解析。在这里 pcap dns proxy 主要起到了分流的作用。

**Comment by chengr28** [comment]
@Incubator113704 并没有类似的计划……现在 `Update_WhiteList` 的批处理/脚本其实也是别人写了发 PR 合并进来的，就是实现了从 dnsmasq-china-list 项目下载并转换成程序可识别格式这个功能
虽然不太清楚『自建远程解析』的工作过程，不过如果只是开在非标准端口上之类也可以直接通过设置『直连模式』交给程序处理，当然如果是加密信道等程序不支持的协议那就无能为力了……

**Comment by wongsyrone** [comment]
那个白名单是根据dnsmasq-china-list上游生成的，每次更新附带进去作为参考配置文件，你有两个选择：1、汇报白名单域名问题到上游，上游移除相关条目之后这边就会跟进
2、维护自己常用的白名单列表，其实那么多域名你不可能全部用到，只是时间积累的问题

**Comment by rampageX** [comment]
@chengr28 
『有抓包，应该是不需要任何列表的』这个的确是没有错……但有个非常现实的问题，就是抓包并不能解决 CDN 的问题？抓包只能确保拿到的结果是真实有效的，但并不能保证 CDN 是 100% 正确的，这个和使用的 DNS 服务器有关，所以才会有不同分流境内外域名解析的方案。

我是这么理解的，你看对不对：

首先，国内网站 CDN 是没有问题的，因为这些域名不会被抓包分流，肯定是由客户设置的国内 ISP 服务器解析的；
好，我们说被污染的境外域名，这里又分两种情况，先说简单的一种：
就是这类被污染的域名总是通过代理访问，这应该是绝大部分，那这里没有问题，只要你设置的境外解析服务器就在你的 VPS 上，或者是通过 shadowsocks 连接到 VPS 上创建的本地服务器，总是可以获得相对 VPS 来说的最优解析结果；
我想你们讨论的是第二种情况，就是类似 google 有一些域名，其实是有国内 IP 的，只要解析出这些 IP 其实是可以直连的，不需要代理。我个人觉得这种情况目前没有什么特别好的解决方式，首先这些域名无法通过程序来实现列举，人工收集也很难。目前我个人的办法就是用香港的 VPS （或者其他有海底光纤直连的服务商），代理和解析都在这个 VPS 上，广东电信看起来影响不大。

**Comment by Incubator113704** [comment]
@chengr28 @wongsyrone 好的，我会做一个给自己用的域名列表，说不会也会把工具丢回来分享一下。

然后是 @chengr28 提到的远程解析，其实就是

[Addresses]
IPv4 Listen Address = 127.0.0.1:53
IPv4 EDNS Client Subnet Address = 
IPv4 DNS Address = 127.0.0.1:19053
IPv4 Alternate DNS Address = 
IPv4 Local DNS Address = 112.124.47.27:53
IPv4 Local Alternate DNS Address = 114.215.126.16:53

whitelist.txt 中的域名理论上来说交给112.124.47.27:53、114.215.126.16:53，其他全都丢给19053。
19053是一个 unbound，它负责返回 Los Angles 当地的 DNS 查询结果（8.8.8.8/8.8.4.4）。
同时，这些发到19053的域名 DNS 查询请求回来的 IP，当然也通过 Los Angles 的 HTTP 代理来访问。
差不多相当于给 HTTP 代理 增加了类似 SOCKS5 代理那样的 DNS 远程解析功能吧。

**Comment by chengr28** [comment]
@Incubator113704 看来是个隧道……的确不错的方案

**Comment by chengr28** [comment]
@rampageX 『抓包』的意思是抓取流经网络适配器的数据包，具体到程序的行为就是通过一组规则过滤数据包以『确保只有真包可以被接受』；『分流』顾名思义就是『判断域名使用境内或境外的 DNS 服务器进行解析』。现在的问题是，『抓包』行为和『分流』行为是完全不一样的两个过程，所以所产生的作用和效果也完全不一样……不能理解你所说的事情

**Comment by rampageX** [comment]
@chengr28 嗯，我理解错了

**Comment by Incubator113704** [comment]
@rampageX @chengr28 有点鸡同鸭讲，现在重新整理一下：

我提出的是单纯的分流问题，pcap dns proxy 是我能找到的完成度最高的分流工具（即使分流不是它的主要设计目的）。
@rampageX 误解了这个 issue 的主题，其实这个 issue 就是请求 pcap dns proxy 再优化一下白名单，没有任何的这个被封域名解析出来后直连的意思。开发上出了偏差要负责的。
如果 pcap dns proxy 没有这个优化白名单计划就自己把前面的临时 workaround 完善一下，写个工具什么的。目前结论是得自己做。

**Comment by chengr28** [comment]
@Incubator113704 +1s 闷声发大财

**Comment by rampageX** [comment]
@Incubator113704 白名单优化很简单啊...在他那个 Update 的脚本加几句就能按照自己定义的名单来删除了...

        while read domain; do
            sed -i "/${domain}/d" $dnsmasq-china-list
        done < $domain_exclusion_list

>_<
