### ISSUE TITLE
Host.ini Local Hosts 优先级不够，仍然有其中的域名被转发到国外 DNS 服务器的情况。

### ISSUE THREAD

**Issue by Incubator113704** [chengr28/Pcap_DNSProxy#147]
Host.ini:

...
[Local Hosts]

```
.*\.baidu.com
.*\.taobao.com
.*\.taobao-img.com
```

[Address Hosts]
...

Config.ini:

...
[Listen]
Pcap Capture = 0
...
[DNS]
Protocol = IPv4 + UDP
Direct Request = IPv4
...
[Local DNS]
Local Protocol = IPv4 + UDP
Local Hosts = 1
Local Main = 0
Local Routing = 0
...
[Addresses]
IPv4 Listen Address = 127.0.0.1:53
IPv4 EDNS Client Subnet Address = 
IPv4 DNS Address = 127.0.0.1:19053
IPv4 Alternate DNS Address = 
IPv4 Local DNS Address = 114.215.126.16:53
IPv4 Local Alternate DNS Address = 112.124.47.27:53
...

64位 Windows 10 专业版 1511 (10.0.10586)，E3 1231 V3 ，16GB RAM。
pcap dns proxy 运行在 Service Mode。
尝试过清空 whitelist.txt，仍然发现存在 Local Host 域名被转发到国外 DNS 服务器的情况。

5月2日更新

看起来国内服务器慢了一拍比如timout就会向国外查询，有可能让这些域名必须从国内解析吗？也就是从国内解析失败时，增加选项 让它再试一次而不是向国外请求。

**Comment by Incubator113704** [comment]
Error logs

2016-04-12 11:17:41 -> Hosts Error: Regular expression pattern error in line 25993 of PcapDNSProxy\Hosts.ini, error code is 2.
2016-04-12 11:17:41 -> Hosts Error: Regular expression pattern error in line 25994 of PcapDNSProxy\Hosts.ini, error code is 2.
2016-04-12 11:17:41 -> Hosts Error: Regular expression pattern error in line 25995 of PcapDNSProxy\Hosts.ini, error code is 2.
2016-04-12 11:17:41 -> Hosts Error: Regular expression pattern error in line 25996 of PcapDNSProxy\Hosts.ini, error code is 2.

**Comment by Incubator113704** [comment]
nslookup www.taobao.com 112.124.47.27
服务器:  UnKnown
Address:  112.124.47.27

非权威应答:
名称:    www.taobao.com.danuoyi.tbcache.com
Addresses:  183.136.138.188
          122.227.164.190
          122.225.67.253
          122.228.74.168
Aliases:  www.taobao.com


nslookup www.taobao.com 127.0.0.1
服务器:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

非权威应答:
名称:    www.taobao.com.danuoyi.tbcache.cOm
Address:  66.102.255.57
Aliases:  WwW.TaObAo.cOm

**Comment by jzp820927** [comment]
问题解决了吗？

**Comment by Incubator113704** [comment]
@jzp820927 …事实上，没有，它… 处于一种… 很不好形容的状态，返回国内或国外结果简直像是随机的。
还需要更多信息再来。

**Comment by dgeibi** [comment]
正则表达式写错了吧

**Comment by jzp820927** [comment]
@dgeibi .*\.taobao.com 正则没问题，第3，4 字符，\. 是转义 .用的
@Incubator113704 既然问题没解决，你怎么把 issuse 关了？其实我想说，我也遇到这个问题。看到你发来，我就不准备发了，但你又把他关了，我还以为你解决了，想问问你呢

**Comment by dgeibi** [comment]
我错了 （ 但 `.*\.taobao.com`  不能匹配 `taobao.com`，所以 `.*\btaobao\.com` 更合理点

**Comment by jzp820927** [comment]
@dgeibi \b 我只知道能匹配空格，但是不知道能不能匹配 .

**Comment by Incubator113704** [comment]
我没有足够的信心证明是我的使用方式问题还是程序本身的问题，在进一步调查之前还是暂时这个状态吧。

**Comment by chengr28** [comment]
关于这个问题，经测试发现此功能是正常工作中的，可以试试抓包看看
可能的原因是就算把结果写入 Local Hosts 里，实际上也只是指令程序『优先使用境内服务器进行解析』而不是『强制使用境内服务器进行解析』如果境内服务器应答了一个程序不能接受的结果（黑名单之类）或者在超时前不能回应，程序是会继续使用余下其它设定好的解析方式获取结果，这可能就是导致测试结果不确定的缘故

**Comment by Incubator113704** [comment]
@chengr28 『强制使用境内服务器进行解析』 那么有可能实现这一点吗？比如加个选项之类的？

**Comment by chengr28** [comment]
@Incubator113704 那就是如果境内服务器解析不出来，那么干脆就不要解析域名的意思吗？

**Comment by Incubator113704** [comment]
@chengr28 是的， 境内不可能解析不出来，只能是因为网络问题慢了一拍，所以这时候就让它自己重试一下。实际测试中发现本地确实 OneDNS 的返回时常 timeout，下一步计划换成阿里的 DNS，然后这边还是需要一个选项防止那些国内的域名 CDN 请求被发到国外去这种情况。

**Comment by Incubator113704** [comment]
因为加到 Local Host 中的域名一定是有十足把握国内正常访问嘛， 比如那个淘宝那个京东百度什么的。

**Comment by jzp820927** [comment]
我觉得可以增加个强制国内 DNS 解析的选项，不如会出现 CND 错误。国外网络问题严重，不能按照常规的方法来解决问题。

**Comment by chengr28** [comment]
刚才更新的版本添加了 `Local Force Request` 参数，可以实现强制境内服务器解析的功能，当然万一境内服务器解析失败……就没有然后了

**Comment by jzp820927** [comment]
不过设计成一个开关还是比较方便的，如果确实境内DNS解析不了，可以把域名从白名单去掉，或者把开关关掉，这个还说是比较灵活的，能不能解析成功就靠自己测试了。

**Comment by Incubator113704** [comment]
@jzp820927 当然这些就得手动啦~
