### ISSUE TITLE
centos 编译时出现错误

### ISSUE THREAD

**Issue by gaoyan1234** [chengr28/Pcap_DNSProxy#149]
Scanning dependencies of target Pcap_DNSProxy
[  5%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
In file included from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Structures.h:20:0,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Base.h:20,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Base.cpp:20:
_**/root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Platform.h:301:26: fatal error: pcap/pcap.h: No such file or directory**_
    #include <pcap/pcap.h>
                          ^
compilation terminated.
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o] Error 1
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
make: *** [all] Error 2
mv: cannot stat `Object/Pcap_DNSProxy': No such file or directory
chmod: cannot access `Release/Pcap_DNSProxy': No such file or directory
这是错误代码 请问大神这是什么问题

**Comment by rampageX** [comment]
装 libpcap-devel
