### ISSUE TITLE
请问centos 6.5 如何启动install脚本

### ISSUE THREAD

**Issue by gaoyan1234** [chengr28/Pcap_DNSProxy#150]
[root@VM_199_161_centos Scripts]# ./Linux_Install.SysV.sh
./Linux_Install.SysV.sh: line 27: insserv: command not found
Start Pcap_DNSProxy service
/etc/init.d/PcapDNSProxyService: line 43: /sbin/start-stop-daemon: No such file or directory

  PID TTY          TIME CMD
\nPcap_DNSProxy is not running when PID is empty.
[root@VM_199_161_centos Scripts]# sh PcapDNSProxyService  start
sh: PcapDNSProxyService: No such file or directory
 文件里面只有debian 脚本 请问 centos6.5 编译好后如何安装

**Comment by jzp820927** [comment]
/etc/init.d/PcapDNSProxyService: line 43: /sbin/start-stop-daemon: No such file or directory

提示没找到文件，你改脚本里面的路径了没

**Comment by gaoyan1234** [comment]
对于一个根本不懂linux的小白，请问怎么改

**Comment by jzp820927** [comment]
不懂，你还用 Linux ？

**Comment by gaoyan1234** [comment]
正因为不懂 才学习嘛

**Comment by jzp820927** [comment]
你不懂，就很难给你说得清楚了，建议新手用 ubuntu ，centos 老手用都很麻烦

**Comment by gaoyan1234** [comment]
我都到最后一步了 也难得再换系统了 再说我也不是专门搞IT的 只是买了个国内vps 搭个dns服务器而已 求指导怎么改路径

**Comment by jzp820927** [comment]
* 使用 System V Init 时：
    * 进入 Release 目录并编辑 PcapDNSProxyService 文件，编辑完成后保存：
      * NAME 项为程序的名称
      * PATH 项为程序的绝对路径

看看 PcapDNSProxyService 文件的 PATH 是否修改为正确的 程序执行文件路径

**Comment by wongsyrone** [comment]
It's not a bug of Pcap_DNSProxy, please use search engines to find answers.
