### ISSUE TITLE
静态编译失败

### ISSUE THREAD

**Issue by yuan78** [chengr28/Pcap_DNSProxy#151]
[ 83%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadIPFilter.cpp.o
[ 88%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o
[ 94%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Service.cpp.o
[100%] Linking CXX executable Pcap_DNSProxy
/usr/local/lib/libpcap.a(nametoaddr.o)：在函数‘pcap_nametoaddrinfo’中：
/home/yuan/libpcap-1.7.4/./nametoaddr.c:128: 警告： Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/lib/libpcap.a(nametoaddr.o)：在函数‘pcap_nametoaddr’中：
/home/yuan/libpcap-1.7.4/./nametoaddr.c:102: 警告： Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/lib/libpcap.a(nametoaddr.o)：在函数‘pcap_nametonetaddr’中：
/home/yuan/libpcap-1.7.4/./nametoaddr.c:146: 警告： Using 'getnetbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/lib/libpcap.a(nametoaddr.o)：在函数‘pcap_nametoproto’中：
/home/yuan/libpcap-1.7.4/./nametoaddr.c:263: 警告： Using 'getprotobyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/lib/libpcap.a(nametoaddr.o)：在函数‘pcap_nametoport’中：
/home/yuan/libpcap-1.7.4/./nametoaddr.c:176: 警告： Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/lib/libpcap.a(pcap-dbus.o)：在函数‘dbus_write’中：
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:114：对‘dbus_message_demarshal’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:120：对‘dbus_connection_send’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:121：对‘dbus_connection_flush’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:123：对‘dbus_message_unref’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:116：对‘dbus_error_free’未定义的引用
/usr/local/lib/libpcap.a(pcap-dbus.o)：在函数‘dbus_read’中：
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:66：对‘dbus_connection_pop_message’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:80：对‘dbus_connection_pop_message’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:70：对‘dbus_connection_read_write’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:83：对‘dbus_message_is_signal’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:88：对‘dbus_message_marshal’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:100：对‘dbus_free’未定义的引用
/usr/local/lib/libpcap.a(pcap-dbus.o)：在函数‘dbus_activate’中：
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:185：对‘dbus_connection_open’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:191：对‘dbus_bus_register’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:230：对‘dbus_bus_add_match’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:231：对‘dbus_error_is_set’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:232：对‘dbus_error_free’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:235：对‘dbus_bus_add_match’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:236：对‘dbus_error_is_set’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:238：对‘dbus_error_free’未定义的引用
/usr/local/lib/libpcap.a(pcap-dbus.o)：在函数‘dbus_cleanup’中：
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:143：对‘dbus_connection_unref’未定义的引用
/usr/local/lib/libpcap.a(pcap-dbus.o)：在函数‘dbus_activate’中：
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:169：对‘dbus_bus_get’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:178：对‘dbus_error_free’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:227：对‘dbus_connection_set_max_received_size’未定义的引用
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:176：对‘dbus_bus_get’未定义的引用
/usr/local/lib/libpcap.a(pcap-dbus.o)：在函数‘dbus_cleanup’中：
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:143：对‘dbus_connection_unref’未定义的引用
/usr/local/lib/libpcap.a(pcap-dbus.o)：在函数‘dbus_activate’中：
/home/yuan/libpcap-1.7.4/./pcap-dbus.c:193：对‘dbus_error_free’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/Pcap_DNSProxy.dir/build.make:510: recipe for target 'Pcap_DNSProxy' failed
make[2]: *** [Pcap_DNSProxy] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
mv: 无法获取"Object/Pcap_DNSProxy" 的文件状态(stat): 没有那个文件或目录
chmod: 无法访问"Release/Pcap_DNSProxy": 没有那个文件或目录
root@yuan-GA-MA770T-UD3P:/home/yuan/pcap_DNS/Source/Scripts# ./Linux_Build.sh

静态编译失败，但是非静态编译OK

**Comment by rampageX** [comment]
这个和系统带的 glibc 在编译时的参数有关，我在 debian for arm 上也有类似问题，但是用 tomatoware 就没有问题，你可以参考：

http://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo

> 
glibc uses libnss to support a number of different providers for address resolution services. Unfortunately, you cannot statically link libnss, as exactly what providers it loads depends on the local system's configuration.

除了自己编译 glibc 或者换一个编译系统没有什么简单的办法。
