### ISSUE TITLE
Hosts.ini 里屏蔽某域名的AAAA记录无效

### ISSUE THREAD

**Issue by smounives** [chengr28/Pcap_DNSProxy#152]
### 程序运行环境及版本号
Windows 7 SP1 64-Bit
Pcap_DNSProxy 0.4.5.6

### 问题重现步骤

1.Hosts.ini 里添加一条 [Hosts] 规则“NULL:AAAA	dl.google.com”
2.重启 Pcap_DNSProxy
3.屏蔽 AAAA 记录未生效

### 期望的程序行为
nslookup dl.google.com
返回结果无 AAAA 记录

### 实际的程序行为

仍然有 AAAA 记录
nslookup dl.google.com
服务器:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

非权威应答:
名称:    dl.l.gOoGlE.CoM
Addresses:  2404:6800:4008:c07::5d

### 与默认配置文件不同的部分
Config.ini
[DNS]
Protocol = IPv4 + TCP + UDP
Direct Request = IPv6 + IPv4

[Local DNS]
Local Main = 1
Local Routing = 1

[Switches]
EDNS Label = 1

### 程序错误日志
无

**Comment by jzp820927** [comment]
好像有人遇到过这个问题，不过 老大，最近好像很忙，之前很多 BUG 一直还没修复

**Comment by chengr28** [comment]
Hosts.ini 里屏蔽的关键词是 `BANNED` 而不是 `NULL` 后者是用于绕过 Hosts 的，详细的说明请务必认真查看说明文档中的介绍
