### ISSUE TITLE
[提问]如何停止解释出ipv6地址（不是ipv6网络，ipv6地址不能连通）

### ISSUE THREAD

**Issue by matthew728960** [chengr28/Pcap_DNSProxy#153]
### 程序运行环境及版本号
    Windows 10
    Version = 0.4

### 期望的程序行为
停止解释出ipv6地址（不是ipv6网络，ipv6地址不能连通）

### 实际的程序行为
    nslookup www.haproxy.org 127.0.0.1
    非权威应答:
    名称:    WwW.HaPrOxY.OrG
    Addresses:  2001:7a8:363c:2::2
                195.154.117.161

### 与默认配置文件不同的部分
    [Listen]
    Listen Protocol = IPv4 + TCP + UDP
    [Local DNS]
    Local Protocol = IPv4 + UDP

**Comment by chengr28** [comment]
如果纯粹只是想屏蔽所有域名的 IPv6 记录，可以在 Hosts.ini 文件 [Hosts] 一节里添加 `BANNED:AAAA .*`
不过不建议这样做，首先 Windows 本身不少高级功能都是依靠 IPv6 才能完成一刀切不好；其次就是虽然能解析出 IPv6 地址，但是因为不存在默认的 IPv6 网关，程序如果尝试使用 IPv6 时会因为地址不能路由而请求失败，同时会通过 IPv4 重新尝试（除非请求的程序强制只能使用 IPv6）所以一般其实不用担心这个问题
