### ISSUE TITLE
更改配置会影响下载速度吗

### ISSUE THREAD

**Issue by sishentibu** [chengr28/Pcap_DNSProxy#154]
我知道浏览网页的速度会有影响
但是对于迅雷下载之类的，会有影响吗？

配置基本是默认配置，就是开启了
Local Main = 1
Local Routing = 1

试过暂时卸载再下载，貌似是没啥影响。

我想要了解下

**Comment by jzp820927** [comment]
没看懂，你想表达什么意思

**Comment by sishentibu** [comment]
其实我只是想问问，pcap的版本更新，以及对其中配置的更改，会不会影响下载工具的下载速度

**Comment by chengr28** [comment]
影响下载工具速度的因素太多，需要你自己实际测试才能体会

**Comment by jzp820927** [comment]
@sishentibu pcap 只是解析域名用的，按理说，下载软件一般只会在下载最开始的时候解析域名，一旦下载开始了，就是连接IP传输数据的过程，应该不会用到域名解析的。所以应该没有影响

**Comment by sishentibu** [comment]
@jzp820927 issue关闭后还可以回复的吗？还真的没注意过
因为近几天，下载速度从1M变到2M多了。那估计就是外部网速变化了，而不是我电脑本身的原因

**Comment by jzp820927** [comment]
@sishentibu 你别跟我说，你今天才知道 issue关闭后还可以回复？好吧，这次我是真的醉了。

**Comment by sishentibu** [comment]
@jzp820927 还真的是才知道。。。从没试过在关闭的issue中回复过。。

**Comment by jzp820927** [comment]
只要是你能打开的帖子都可以回复，除非是LZ把帖子锁了。

**Comment by sishentibu** [comment]
在输入框下方就一个close跟comment，还有别的选项的？

**Comment by jzp820927** [comment]
你还想要什么选项？

**Comment by sishentibu** [comment]
close不是关闭吗？
你说的锁帖是在哪里的？

**Comment by jzp820927** [comment]
锁贴要项目主才有权限。

**Comment by sishentibu** [comment]
哦，了解
