### ISSUE TITLE
请求支持HTTP DNS查询

### ISSUE THREAD

**Issue by doraeden** [chengr28/Pcap_DNSProxy#155]
移动宽带劫持了任何UDP协议的DNS，包括移动自己的DNS服务器，UDP模式不能查询到结果，TCP模式也不能很好的解决，国内主流的公共DNS服务商只有114支持TCP查询，而且查询结果精确度很差，希望能够加入DNSPOD的HTTP DNS的支持，A记录使用HTTP来查询结果，其他记录使用TCP这样。

**Comment by chengr28** [comment]
HTTP DNS 在我看来是一个笨拙的解决方案……就像骑自行车，现在变成了人背着自行车走

ISP 如果对于 DNS 协议的干扰是如此的严重，建议还是挂个代理之类的比较好
顺便几乎所有的 DNS 服务器都有 TCP 的支持，因为这是 DNS 标准要求实现的功能

**Comment by jzp820927** [comment]
现在 TCP 53 已经死了，非标准端口 UDP 也死了，反正我这边是这样的，不知道其他地区是什么情况。

**Comment by doraeden** [comment]
找不到能代理查询移动递归DNS的VPS，移动的DNS服务器不支持网外查询

**Comment by doraeden** [comment]
好吧，终于找到合适的解决方法了，用VPS转发阿里DNS就可以得到准确的解析结果了，阿里DNS测试支持EDNS，移动也真是恶心，直接把223.5.5.5和223.6.6.6路由做空了，直接连解析不出来

**Comment by chengr28** [comment]
统一到 https://github.com/chengr28/Pcap_DNSProxy/issues/172 讨论
