### ISSUE TITLE
关于EDNS标签格式

### ISSUE THREAD

**Issue by doraeden** [chengr28/Pcap_DNSProxy#156]
之前以为DNSPOD不支持EDNS，后来用dig测试发现是格式的问题，它支持的格式不标准，1.1.1.1/24这样的带CIDR前缀的格式不支持，只支持1.1.1.1这样的IP地址，希望加上对这种IP格式的支持，DNSPOD使用EDNS的DNS解析结果准确率实测高于ALIDNS

**正确的结果：**
; <<>> DiG 9.9.3 <<>> @119.29.29.29 www.taobao.com +client=120.198.230.1
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8191
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; CLIENT-SUBNET: 120.198.230.1/32/24
;; QUESTION SECTION:
;www.taobao.com.                        IN      A

;; ANSWER SECTION:
www.taobao.com.         534     IN      CNAME   www.taobao.com.danuoyi.tbcache.com.
www.taobao.com.danuoyi.tbcache.com. 10 IN A     183.232.48.253
www.taobao.com.danuoyi.tbcache.com. 10 IN A     183.232.31.125
www.taobao.com.danuoyi.tbcache.com. 10 IN A     183.232.151.165
www.taobao.com.danuoyi.tbcache.com. 10 IN A     183.232.60.123

;; Query time: 8 msec
;; SERVER: 119.29.29.29#53(119.29.29.29)
;; WHEN: Sun Apr 24 10:11:16 CST 2016
;; MSG SIZE  rcvd: 164

**错误的结果：**
; <<>> DiG 9.9.3 <<>> @119.29.29.29 www.taobao.com +client=120.198.230.1/24
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63027
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.taobao.com.                        IN      A

;; ANSWER SECTION:
www.taobao.com.         32      IN      CNAME   www.taobao.com.danuoyi.tbcache.com.
www.taobao.com.danuoyi.tbcache.com. 60 IN A     112.90.32.223
www.taobao.com.danuoyi.tbcache.com. 60 IN A     163.177.63.95

;; Query time: 32 msec
;; SERVER: 119.29.29.29#53(119.29.29.29)
;; WHEN: Sun Apr 24 10:12:05 CST 2016
;; MSG SIZE  rcvd: 120

**Comment by chengr28** [comment]
你好，首先感谢你的反馈。是这样，希望能提供一下执行这两个命令时的抓包记录，以便这边对 DNS 数据包的结构进行分析。因为 IETF 那边对于 EDNS Client Subnet 尚未正式发布，所以格式的问题不好说

**Comment by doraeden** [comment]
已经将抓包数据发送到你的邮箱，麻烦您了

**Comment by chengr28** [comment]
已经收到……看了下，两个请求 EDNS 标签的格式完全一样，不同的只是 CIDR 的掩码长度：
* 『正确』的掩码长度是 24 位，DNSPod 看来是支持的
* 『错误』的掩码长度是 32 位，DNSPod 看来是不支持的

所以比较好的解决方法是修改程序的配置文件时指定 /24 的前缀长度

**Comment by doraeden** [comment]
加上/32以后确实可以正常解析了，谢谢
