### ISSUE TITLE
Pcap_DNSProxy 能否支持 Google DNS-over-HTTPS API

### ISSUE THREAD

**Issue by debugzxcv** [chengr28/Pcap_DNSProxy#158]
介绍: https://developers.google.com/speed/public-dns/docs/dns-over-https
API 示例:
`https://dns.google.com/resolve?name=example.com`

**Comment by wongsyrone** [comment]
Similar to #155

**Comment by jzp820927** [comment]
作者之前说过，这种做法很幼稚，应该不会加吧

**Comment by wongsyrone** [comment]
如果想用这个，需要解决先有蛋还是先有鸡的问题。域名DNS污染和解析出来的IP封锁，这两个是无解的，我先标为wontfix了

**Comment by jzp820927** [comment]
这种情况只是解决仅污染，非封锁的域名，对于直接封锁IP的域名，靠 DNS 肯定是无解的。
不过仅污染，非封锁的情况，还是蛮多的，大部分的 https 都是这种情况。封锁IP毕竟成本过高，网络负担过大，对正常国际业务影响太大。大部分情况都是 只污染，不封锁的。

**Comment by chengr28** [comment]
统一到 https://github.com/chengr28/Pcap_DNSProxy/issues/172 讨论
