### ISSUE TITLE
DNS Address detection

### ISSUE THREAD

**Issue by angle1895** [chengr28/Pcap_DNSProxy#159]
5.2日版本win7系统。网站https://ipleak.net
使用pcap无法检测dns只开启了Local Hosts = 1其他都是默认，用Acrylic可以检测dns。。。。无法上传图片。。至能文字表达

**Comment by jzp820927** [comment]
没看懂啥意思

**Comment by Incubator113704** [comment]
尝试阅读了一下，你可能是指的，
系统 DNS 设为 pcap dns proxy 时， https://ipleak.net/ 检测不到你在用什么 DNS 或者出来一堆乱七八糟的不是你的 DNS 的地址？它说了一句 "If you are now connected to a VPN and between the detected DNS you see your ISP DNS, then your system is leaking DNS requests"。也就是说，这里的作用是这个网站试着抓出你当前使用的 DNS 地址。但是你用 pcap dns proxy 时，它抓不到你的地址。

按理来说这应该是好事，然后，Acrylic 是一个 DNS proxy 客户端，你的意思可能是你用 Acrylic 作为你的系统 DNS 时，https://ipleak.net/ 能够抓出你当前使用的 Acrylic DNS 地址。

但是，让 https://ipleak.net/ 抓到你当前使用的 pcap dns proxy 地址，有什么意义吗？
这个 issue 的目的是什么？如果你发 issue 的目的不是打听一下怎么让 https://ipleak.net/ 能够抓到 pcap dns proxy 的地址，那么是什么？

如果是的话，这有什么意义？

**Comment by jzp820927** [comment]
就算是LS所说的意思，然而并不影响使用，然而这个 issues 并没意义。
