### ISSUE TITLE
[Values] Domain Test 设置无效

### ISSUE THREAD

**Issue by debugzxcv** [chengr28/Pcap_DNSProxy#160]
win7 sp1 x64
pcap_dnsproxy 0.4.6.1

> ReadMe :
> * Domain Test - DNS 服务器解析域名测试间隔时间：单位为秒，最短间隔时间为5秒

不管怎么设置间隔都为 5 秒左右:
[Values]
Domain Test = 45000

**Comment by jzp820927** [comment]
设置这个有什么用麽

**Comment by debugzxcv** [comment]
只要开启了 pcap 模式就按照一定的时间间隔发送 `[data] Domain Test Data` 的数据到 dns 服务器

**Comment by jzp820927** [comment]
这个定期发送数据，是测试 DNS 服务器？还是取数据回来缓存用？

**Comment by debugzxcv** [comment]
细节不太了解 应该只是测试服务器可用性什么的

**Comment by chengr28** [comment]
根据程序的逻辑，这个功能是用于测试和验证非境内 DNS 服务器的真伪，至于那个参数设置的是在**成功**获取真实服务器所需验证信息的情况下才会适用，也就是说如果获取**失败**的话会自动重试，那个间隔正是最小的间隔时间……建议检查一下列表中的 DNS 服务器
