### ISSUE TITLE
请教 Pcap 在 Linux 下的一个问题。

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#161]
### 运行环境及程序版本号
Ubuntu 15.10
Pcap_DNSProxy 0.4.5.5

### 问题重现步骤
通过 netstat -anp|grep Pcap_DNSProxy 查看，Pcap 在运行后，在不到1分钟时间的内，就会迅速达到下面这个状态。
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp   212736      0 0.0.0.0:5353            0.0.0.0:*                           12559/Pcap_DNSProxy
raw   213056      0 0.0.0.0:1               0.0.0.0:*               7           12559/Pcap_DNSProxy
raw   213056      0 0.0.0.0:1               0.0.0.0:*               7           12559/Pcap_DNSProxy
raw   213056      0 0.0.0.0:1               0.0.0.0:*               7           12559/Pcap_DNSProxy
raw   213056      0 0.0.0.0:1               0.0.0.0:*               7           12559/Pcap_DNSProxy
raw   213056      0 0.0.0.0:1               0.0.0.0:*               7           12559/Pcap_DNSProxy
raw   213056      0 0.0.0.0:1               0.0.0.0:*               7           12559/Pcap_DNSProxy

这个时候 DNS 就不能再解析了。
dig github.com -p 5353 @127.0.0.1
; <<>> DiG 9.9.5-11ubuntu1.1-Ubuntu <<>> github.com -p 5353 @127.0.0.1
;; global options: +cmd
;; connection timed out; no servers could be reached

补充一下，我发现用 TCP 协议的话，可以正常解析。以下是对比：
UDP 解析：
dig www.qq.com -p 5353 @192.168.12.108
; Warning: response timeout for 192.168.12.108#5353(UDP)

; Warning: response timeout for 192.168.12.108#5353(UDP)

; Warning: response timeout for 192.168.12.108#5353(UDP)
; Warning: failed to query server 192.168.12.108#5353(UDP)

TCP 解析：
dig www.qq.com +tcp -p 5353 @192.168.12.108
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 17146
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; www.qq.com.          0       IN      A

;; ANSWER SECTION:
www.qq.com.             222     IN      A       182.140.167.44

;; Received 44 B
;; Time 2016-05-07 15:43:40 CST
;; From 192.168.12.108#5353(TCP) in 3500.0 ms

如果重启一下，又可以正常解析，但是不到1分钟时间，就会达到上面的状态。不能解析。
感觉有点像溢出的状态，请问，大概是什么原因导致的？

### 程序错误日志

此处粘贴错误日志，如果错误日志行数过多，可使用外链
（提交时删除本提示）

**Comment by wongsyrone** [comment]
最新版是0.4.6.2，试试还有类似问题吗

**Comment by jzp820927** [comment]
行吧，不知道请求量过大，会不会造成这个问题，我限制了一些访问源，好像又好了。

**Comment by chengr28** [comment]
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      2015/Pcap_DNSProxy
    tcp6       0      0 :::53                   :::*                    LISTEN      2015/Pcap_DNSProxy
    udp        0      0 0.0.0.0:53              0.0.0.0:*                           2015/Pcap_DNSProxy
    udp6       0      0 :::53                   :::*                                2015/Pcap_DNSProxy
    raw     3072      0 0.0.0.0:1               0.0.0.0:*               7           2015/Pcap_DNSProxy
    raw     3072      0 0.0.0.0:1               0.0.0.0:*               7           2015/Pcap_DNSProxy
    raw     3072      0 0.0.0.0:1               0.0.0.0:*               7           2015/Pcap_DNSProxy
    raw     3072      0 0.0.0.0:1               0.0.0.0:*               7           2015/Pcap_DNSProxy

在默认配置下这边运行的结果是这样的，符合预期。建议先填一下 Issue 中 `程序错误日志`（如果有）和 `与默认配置文件不同的部分` 的部分或者干脆把整个配置文件粘贴上来，信息不完整也不好判断
仔细想了下……有两种情况可能会限制最大的同一时间可处理请求数：一个是 `Buffer Queue Limits` 和 `Queue Limits Reset Time` 参数的设置，一个是系统的 Socket 的最大数量限制，建议查阅相关的文档看看。这边并没有严格测试过在请求量非常大的情况下本程序的实际表现，不过据反馈回来的信息来看 Linux 平台上使用本程序搭建应用范围不大的 DNS 服务器，问题应该是不大的

**Comment by jzp820927** [comment]
程序能正常运行，应该没有错误日志吧，config 只改了Additional Path，Hosts File Name，Operation Mode = Server，Accept Type = Deny:AAAA，Protocol = IPv4 + UDP + TCP，Local Hosts = 1，还有把上游 DNS 服务器换了2个，其他都没改动了。

**Comment by chengr28** [comment]
错误日志 Error.log 就在程序目录内……至于性能瓶颈，主要在两个地方：
* `Protocol = ..TCP` 请求用 TCP 协议，如果每个请求远程 DNS 服务器的连接均需要 TCP 的3次握手会导致这边处理一个请求的时间大幅延长，尤其是出现丢包之类的情况下，请求量大了卡住甚至还会占用大量 Socket 还是有可能的，建议如果出现问题可以去掉试试
* `Local Hosts = 1` 这个对性能的拖累是最为凶猛的，因为需要进行正则表达式的匹配。如果以默认配置所附带的几万条的规则，在 PC 上实际测试一个查询起码需要延迟几十 ms 进行独占匹配，在请求量比较大的情况下……不可想象。所以其实是不太建议开启的。建议是使用 `Local Main` + `Local Routing` 的组合，可以再试试

**Comment by jzp820927** [comment]
我说说我的想法吧，你说的这2点，我觉得是在国内必不可少的功能。

第一条，TCP协议查询上游，不知道你有没有发现，现在 查询境外 404 域名的时候，udp 协议的 标准，非标端口，TCP 协议的 标准端口，全部受到干扰，只有 TCP 协议，非标端口可以正常使用。不知道你那边是什么情况，反正我这边是这样的，我是经过长时间，很多次的测试，得出的结果。所有者不开身 TCP 的情况下，很难保证查询的稳定性，经常会出现 timeout 超时(我印象中，去年 udp 非标都可以正常使用，今年开始就不行了。)

第二条，作用是保证 国内和 国外 CDN 的智能路由。Local Main + Local Routing 确实没做过大查询量的测试。据我理解，Local Hosts 是基于域名 的正则匹配，Local Main + Local Routing 是基于国内 IP 路由表的普通匹配？这2种模式在实现功能上有什么区别麽？如果 Local Main + Local Routing 模式能实现 Local Hosts 模式一样的功能，那是不是这两种模式就产生了功能上的重复了？

**Comment by chengr28** [comment]
* 可能各地的情况不一样，但是这边的测试结果来看现在普遍与境外的通讯都受到影响，TCP 比起 UDP 需要更多的握手步骤，受影响应该是更严重的，所以实际使用反而是 UDP 比较顺畅。当然也不是说用 TCP 不行，只是要做好心理准备，提防大量的多线程 TCP 请求可能会耗尽系统的资源而已，尤其是当网络环境恶劣的时候，会导致大量线程阻塞等待握手响应，有阻碍后来连接的可能

* 区分国内外 CDN 目的就是把国内有 CDN 的流量和国外的区别开来而已，Local Hosts 和 Local Main + Local Routing 是实现这一目的的两种不同的方法而已。当然实际的实现肯定是有很大区别的，域名白名单属于轮询正则匹配，肯定会比查路由表的动作所需的时间多几个数量级，可以先试试运行一段时间看看。关于是不是程序设计上有性能的瓶颈，这边也都会看看

**Comment by jzp820927** [comment]
好吧，我再多测试一段时间，多谢作者答复，这个问题可以慢慢测试。
反正我现在把 pcap 放后端了，所以基本上不会出问题了。而且像我这种需求的可能也很少，大部分应该都是 监听 127，自己一台机子使用，顶多也就放路由器上，给一个网段用。所以查询量非常小。

**Comment by jzp820927** [comment]
今天早上把问题重现了：
$ netstat -anp|grep Pcap
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      47971/Pcap_DNSProxy
udp      768      0 192.168.1.1:43933    208.67.222.222:443      ESTABLISHED 47971/Pcap_DNSProxy
udp      768      0 192.168.1.1:52251    208.67.222.222:443      ESTABLISHED 47971/Pcap_DNSProxy
udp      768      0 192.168.1.1:44311    208.67.222.222:5353     ESTABLISHED 47971/Pcap_DNSProxy
udp      768      0 192.168.1.1:46443    8.8.4.4:53              ESTABLISHED 47971/Pcap_DNSProxy
udp   211200      0 0.0.0.0:53              0.0.0.0:*                           47971/Pcap_DNSProxy
udp      768      0 192.168.1.1:59455    8.8.8.8:53              ESTABLISHED 47971/Pcap_DNSProxy
udp      768      0 192.168.1.1:34934    8.8.4.4:53              ESTABLISHED 47971/Pcap_DNSProxy
udp      768      0 192.168.1.1:37013    208.67.220.220:443      ESTABLISHED 47971/Pcap_DNSProxy
udp      768      0 192.168.1.1:33368    8.8.8.8:53              ESTABLISHED 47971/Pcap_DNSProxy
udp      768      0 192.168.1.1:53857    208.67.220.220:443      ESTABLISHED 47971/Pcap_DNSProxy
udp      768      0 192.168.1.1:51883    208.67.222.222:5353     ESTABLISHED 47971/Pcap_DNSProxy

Error.log 文件大小是 0，没有内容，看吧：
$ ll
total 1484
drwxr-xr-x  3 root root   4096 Jun 10 14:07 ./
drwxr-xr-x 12 root root   4096 Jun  9 21:20 ../
-rw-r--r--  1 root root   4781 May 28 12:57 Config.conf
-rw-r--r--  1 root root      0 Jun 10 14:07 Error.log
-rw-r--r--  1 root root    493 May 27 21:49 Hosts.conf
-rw-r--r--  1 root root   1532 May  8 13:21 IPFilter.conf
-rwxr-xr-x  1 root root 750304 May  8 13:21 Pcap_DNSProxy*
-rw-r--r--  1 root root 120131 May  8 13:21 Routing.txt
-rw-r--r--  1 root root 604436 May  8 13:21 WhiteList.txt

**Comment by jzp820927** [comment]
你好，今天运行在后台的时候，也出现这个问题了，赶脚好像和请求量没太大关系。我是通过下面模式运行的：

 ./Pcap_DNSProxy --disable-daemon
Segmentation fault (core dumped)
./Pcap_DNSProxy --disable-daemon
Segmentation fault (core dumped)
./Pcap_DNSProxy --disable-daemon
Segmentation fault (core dumped)

运行了几次，一直这样，快的时候，几秒钟就这样了，慢的时候，也就，20，30秒时间。

**Comment by chengr28** [comment]
程序崩溃的问题在另一边 https://github.com/chengr28/Pcap_DNSProxy/issues/170 讨论就行……至于大请求量下卡死的问题，这边还需要时间测试和确认问题

**Comment by jzp820927** [comment]
好吧，我不确定这2个问题有没有关联，所以顺便发了一下。既然和请求量没关系，这边就不讨论这个问题了。大请求量的问题，可以先放放，不是太影响使用，还请优先解决下崩溃问题，因为无法使用了。谢谢！

**Comment by aloasut** [comment]
我也遇到这个问题。好像有些情况下就停止工作了，errorlog也没有。
下面254是我局域网另外一个server

root@raspberrypi:~/Pcap_DNSProxy/Source/Release# nslookup www.itsmac.net 127.0.0.1
;; connection timed out; no servers could be reached

root@raspberrypi:~/Pcap_DNSProxy/Source/Release# nslookup www.itsmac.net 192.168.10.254
Server:		192.168.10.254
Address:	192.168.10.254#53

Non-authoritative answer:
Name:	www.itsmac.net
Address: 104.28.1.78
Name:	www.itsmac.net
Address: 104.28.0.78

**Comment by jzp820927** [comment]
LS，你是不是报下面错？
Segmentation fault (core dumped)

**Comment by chengr28** [comment]
刚才推了一下新的版本，修改了几个可疑的地方……重新编译并部署一次试试？

**Comment by jzp820927** [comment]
那我试试，反正我是最先遇到这个问题的人

**Comment by jzp820927** [comment]
问一下，下面这个报错是什么原因造成的？
Network Error: Socket initialization error, error code is 97.

Error.log 里面全部都是这个报错。但是 pcap 又是正常运行的，而且解析域名也是正常的。

**Comment by wongsyrone** [comment]
97貌似是Address family not supported by protocol

**Comment by chengr28** [comment]
Errno 97 是 EAFNOSUPPORT/Address family not supported by protocol 协议不受支持，这个错误是调用系统 API 产生的，也就是说如果报的是 97 那么应该是系统那边的问题，建议检查系统的配置
正常运行程序需要如下的协议（族）的支持：
* IPv4
* IPv6
* RAW/ICMP
* RAW/ICMPv6

**Comment by jzp820927** [comment]
好吧，可能是我调整系统配置的原因吧，我检查下。

**Comment by houzi-** [comment]
开始运行就会出现，尝试多次都不能成功启动
```
root@R6300V2:/tmp# ./Pcap_DNSProxy -c /opt/etc/pcap-dnsproxy --disable-daemon
Segmentation fault
```
有可能是内存泄漏

**Comment by wongsyrone** [comment]
如果是静态链接，可能是C库的问题

**Comment by houzi-** [comment]
动态编译（musl）

**Comment by wongsyrone** [comment]
我在gcc 6.2 + musl下稳定运行，也没闪退
有兴趣可以试试https://github.com/wongsyrone/lede-1
另外gcc 6.2的补丁已经被nbd合并了，不久上游就有更新。

**Comment by bazingaterry** [comment]
Mac 下遇到类似的问题，使用 brew 安装的 4.7 版本，表现和上面的相同，Log 中错误 Complete UDP socket initialisation error。

**Comment by wongsyrone** [comment]
@bazingaterry 你这个好像不是同一个问题，重要的错误代码你没贴出来
ref： https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/FAQ(zh_Hans).txt#L195

**Comment by chengr28** [comment]
@bazingaterry 0.4.7.0-0.4.7.1 这两个版本有一个会耗尽系统套接字资源的问题，如果出现 `socket initialisation error` 可能与其有关，Homebrew 那边还是正式的版本，这边也还有些工作还没完成所以没法更新，建议是先用 GitHub 上的最新版本版本

**Comment by chengr28** [comment]
@houzi- @jzp820927 @aloasut @bazingaterry
关于 0.4.7.0-0.4.7.2 这几个版本崩溃的问题应该已经在刚才的 0.4.7.3 修复好了，有时间可以先自己试试，待测试稳定后再部署下去。如果还是有崩溃的问题，建议是另开新的 Issue 因为看起来这个 Issue 混合了各种各样的问题……

**Comment by chengr28** [comment]
回到最初的问题，就是大量请求下程序的表现：这边使用了 BIND 自带的 `queryperf` 工具进行各种并发的测试，使用刚才最新的 0.4.7.3 版本（之前的版本并没有测试过不清楚，所以把本 Issue 当成 `enhancement` 处理）在三个受支持平台进行测试。
计算单位是 Queries Per Second 一共2套自行生成的域名测试数据库：前者 1000/1k 条随机不重复数据，后者 100 万条/1000k 重复 25 万次的 4 条不重复数据，如非特殊说明均使用默认配置：
* Windows/Linux/Mac 三个平台性能差别不大
* 使用前者连续几次测试模拟一般情况：
  * 不论 Local Routing 还是自带的 WhiteList 进行一次完整匹配造成的延迟小于 0.0001s
  * 开启 Local 情况下 30 QPS 左右，关闭 Local 情况下 60 QPS 左右
  * 超时响应率开启 Local 情况下 1% 左右，关闭 Local 情况下 0.5% 左右，原因应该如下
  * 这部分结果基本和网络状况以及所使用的 DNS 服务器有关，之前还查到其他人只有 15 QPS 的
* 使用后者连续几次测试性能表现：
  * 使用 Intel i5-3210M 的 CPU 进行测试
  * Dnsmasq 在 50k QPS 左右，程序也在 50k QPS 附近，均没有任何超时的情况
  * 通过交换机在同一个内网内进行查询，两者均在 10k QPS 左右
* 所有测试完成后程序功能一切如常，所占用的资源也没有明显上升

**Comment by chengr28** [comment]
这边有几个可以优化大量请求下程序表现的建议：
* `Pcap Reading Timeout` 适当调低这个参数能使抓包模块以更高的频率抓取数据包，降低延迟
* `Cache Parameter` 尽量调高这个参数能增加缓存的生存时间或者队列长度，提高缓存命中率
* `Thread Pool Maximum Number` 适当调高这个参数能可以增大缓冲区最大可容纳请求的数量
* `Queue Limits Reset Time` 不要开启，限制请求数量的参数
* `Multiple Request Times` 非极其恶劣情况慎用，消耗大量系统资源且会些微提高延迟

**Comment by jzp820927** [comment]
感谢这么详细的分析与测试，因为我的大请求量的情况，是因为 53 端口绑定在 公网 IP 上的，所以也不排除，有带攻击性的恶意大量请求 (类似于 DDOS)，直接把服务 down 掉。现在就想问下，在这方便，程序自身有没有什么检测防御措施。比如，检查到超高量的不正常请求，可否有自动把请求源加入黑名单，类似的措施。

**Comment by wongsyrone** [comment]
上面那几条建议可以写在文档里面了

**Comment by wongsyrone** [comment]
@jzp820927 我记得有iptables命令可以限制请求频率的

**Comment by jzp820927** [comment]
@wongsyrone 对 iptables 没有太高级的研究，只会基本规则，可否给个配置示例？

**Comment by wongsyrone** [comment]
限制全局如下，具体内容查看manpage，另外可参考 https://github.com/smurfmonitor/dns-iptables-rules 干掉恶意访问

```
iptables -A INPUT -p tcp -m tcp --dport 53 -m limit --limit 300/m --limit-burst 300 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 53 -j DROP
```

**Comment by jzp820927** [comment]
好的，谢谢，那我研究下。

**Comment by chengr28** [comment]
程序倒是自带有 IPFilter 的功能，上面提到的 `Queue Limits Reset Time` 也能限制一段时间内的请求数量。不过比起这种用户态程序内的自行实现，肯定是用系统的 `iptables` 更好，在底层拦截下来直接能节省不少转换所需的资源

**Comment by wongsyrone** [comment]
你可以把 -p tcp -m tcp 改成 -p udp -m udp，毕竟支持TCP和UDP查询

**Comment by jzp820927** [comment]
行吧，那我就研究下 iptables，争取在 iptables 上实现。

**Comment by chengr28** [comment]
说起来在公网上开这种危险的服务而且还是标准端口压力不会很大么……记得这边之前有台机器也是标准端口开服务而且没有限制，一个多小时就被扫出来当肉鸡乱打人了，尤其现在 DNS 放大攻击很是流行……

**Comment by jzp820927** [comment]
目前没发现什么问题，用的 dnsmasq 前端，以后准备限制请求源，只运行我这个地域的IP访问，其他IP全部禁止。
