### ISSUE TITLE
Local Hosts配置说明有错误

### ISSUE THREAD

**Issue by BBA365** [chengr28/Pcap_DNSProxy#162]
* Local Hosts - 白名单境内服务器请求功能：开启为 1 /关闭为 0
    * 开启后才能使用自带或自定义的 Local Hosts 白名单，且不能与 Local Hosts 和 Local Routing 同时启用

应该是：

* Local Hosts - 白名单境内服务器请求功能：开启为 1 /关闭为 0
    * 开启后才能使用自带或自定义的 Local Hosts 白名单，且不能与 Local Main 和 Local Routing 同时启用

PS:同时问一下，dns缓存是否开启，在哪里可以看到？按照说明配置后，不能清楚的知道缓存是否开启。

**Comment by chengr28** [comment]
说明文档的确是写错了，下次更新的时候会改回去

关于程序内部的 DNS 缓存，是通过 `Cache Type` 参数控制的
至于怎么验证……并没有确定的方法，不过可以通过诸如响应的时间看出
如果请求一个没有 Hosts 的域名能瞬间无延迟返回，那么侧面说明是有缓存的

**Comment by BBA365** [comment]
如果缓存能生成一个文件，再有能够查看修改缓存文件，就非常的方便了。( *￣▽￣)

**Comment by chengr28** [comment]
缓存就是为了让下一次相同的请求能快速命中而存在的，保存到磁盘上不就本末倒置了……

**Comment by yfdyh000** [comment]
可以弄一个转储参数，运行后输出内部结果（再>file）/转储为文件。
不知道实现有无难度，弄一个API/固定地址读取/其他方法。

**Comment by jzp820927** [comment]
赶脚就像是 dns 转换成 hosts

**Comment by Incubator113704** [comment]
@chengr28 保存到磁盘上再读取回去我认为不符合一般 DNS 服务器的思路，但如果只是想简单验证缓存有没有起作用，debug版里加一大堆 console.writeline 就行了。

**Comment by chengr28** [comment]
@Incubator113704 主要是觉得这个完全是画蛇添足的功能，要验证缓存是否有起作用 2L 就有方法，为什么非得要程序输出呢？

**Comment by yfdyh000** [comment]
@chengr28 瞬间返回全凭感觉吧，如果本地服务器也很快（虽然大概没有，查询也耗时）。感觉输出内部信息对于未来调试会有作用，包括各种生效的标志位，但开发和维护也挺费事的，所以仅做参考。
另外，如果是固定地址或API的读写，可能要注意漏洞问题，或许会留隐患。

**Comment by chengr28** [comment]
@yfdyh000 dig 记得是有个请求延迟的计时功能，顺便说道标志位还真不太可能简单就做到 dig 的程度，输出数据非常丰富（前提是有 DNS 数据包结构的基础）……

**Comment by yfdyh000** [comment]
@chengr28 主要指各参数的生效情况，因为配置文件或许因为某些原因没成功之类的（应该会有吧）。

**Comment by chengr28** [comment]
说明文档在刚才的更新中已经改好了w
