### ISSUE TITLE
能否更新下 brew 上的版本？

### ISSUE THREAD

**Issue by gythialy** [chengr28/Pcap_DNSProxy#163]
@blackgear 有时间否？

**Comment by jzp820927** [comment]
还是自己编译源码靠谱

**Comment by blackgear** [comment]
最近因为毕业论文等事情比较忙，有几天没关注这边了，brew上的版本更新已经提交brew-core，请稍等半天左右即可。

**Comment by gythialy** [comment]
非常感谢 😀

Send from my Nexus 6P.
