### ISSUE TITLE
同时开启Direct Request 和 DNSCurve 时，DNSCurve未正常启用

### ISSUE THREAD

**Issue by smounives** [chengr28/Pcap_DNSProxy#164]
### 运行环境及程序版本号

Windows 7 SP1 64bit, WinPcap 4.1.3, Pcap_DNSProxy 0.4.6.2

### 问题重现步骤

1.正常安装Pcap_DNSProxy
2.修改 Config.ini 里第 25 行 `Direct Request = IPv4 + IPv6`, 第 125 行 `DNSCurve = 1`
3.重启程序，CMD nslookup www.facebook.com 127.0.0.1

### 期望的程序行为

通过 DNSCurve 协议，解析到未受到污染的结果

### 实际的程序行为

实际程序并没有使用 DNSCurve ，而是用了 [Addresses] 里的 IPv4 DNS Address 和 IPv4 Local DNS Address
以下是 Wireshark 抓包结果
![image](https://cloud.githubusercontent.com/assets/9267814/15536796/8c5cb124-22a5-11e6-910a-5895be3a6d08.png)

以下是 nslookup 结果
![image](https://cloud.githubusercontent.com/assets/9267814/15537077/174d5c4c-22a7-11e6-8864-bca0f612d0ab.png)

### 与默认配置文件不同的部分

Config.ini 里
第 25 行 `Direct Request = IPv4 + IPv6`
第 125 行 `DNSCurve = 1`

### 程序错误日志
 无

**Comment by smounives** [comment]
好吧，从ReadMe里找到这样一段话
"请求远程 DNS 服务器的优先级：Direct Request 模式 > TCP 模式的 DNSCurve 加密/非加密模式（如有） > UDP 模式的 DNSCurve 加密/非加密模式（如有） > TCP 模式普通请求（如有） > UDP 模式普通请求"
假如我又想让特殊线路使用Pcap_DNSProxy，又想要用DNSCurve该怎么办呢_(:3」∠)_

**Comment by chengr28** [comment]
我觉得首先要搞清楚 `Direct Request` 这个参数到底是什么用途：
**直连模式，启用后将使用系统的 API 直接请求远程服务器而启用只使用本工具的 Hosts 功能**

**Comment by jzp820927** [comment]
应该直接开启 DNSCurve = 1 就可以了，Direct Request 不用动，Direct Request 是用在 VPN 模式下的，相当于，直接DNS 查询，不做任何处理，
