### ISSUE TITLE
经常出现“找不到服务器”

### ISSUE THREAD

**Issue by jrkkei** [chengr28/Pcap_DNSProxy#165]
### 运行环境及程序版本号
win10 x64
Version = 0.4

### 问题重现步骤

1.不定时出现，以国内网站居多，偶尔国外网站也会出现
2.
3.

### 期望的程序行为
国内外网站分别使用国内外DNS，国内CDN，国外防DNS污染

### 实际的程序行为
有时打开网页就直接显示找不到服务器，没有任何延迟，稍等片刻刷新可以打开
PS C:\Users\fkms> nslookup ithome.com
サーバー:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

権限のない回答:
DNS request timed out.
    timeout was 2 seconds.
名前:    ItHoMe.cOm
Address:  123.56.190.53

PS C:\Users\fkms> nslookup microsoft.com
サーバー:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

権限のない回答:
名前:    mIcRoSoFt.cOm
Addresses:  104.43.195.251
          23.100.122.175
          23.96.52.53
          191.239.213.197
          104.40.211.35

PS C:\Users\fkms> nslookup baidu.com
サーバー:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

権限のない回答:
DNS request timed out.
    timeout was 2 seconds.
名前:    BaIdU.CoM
Addresses:  123.125.114.144
          180.149.132.47
          111.13.101.208
          220.181.57.217

PS C:\Users\fkms> nslookup google.com
サーバー:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

権限のない回答:
名前:    GoOgLe.cOm
Addresses:  2404:6800:4005:804::200e
          216.58.199.110

### 与默认配置文件不同的部分

Local Force Request = 1
Local Hosts = 1

### 程序错误日志

无日志

**Comment by Incubator85653** [comment]
在技术支持进入战场前...一点小建议。
直接检查你设置的国内 DNS 响应速度如何，有时确实存在国内 DNS 响应响应缓慢的情况。
如果响应速度没问题，再将 pcap dns proxy 的进程设置为高优先级试试。

**Comment by jrkkei** [comment]
默认的114真的会丢包，这个也算有名了，真没想到。但是换了不丢包的DNS问题仍然存在。
208.67.222.222:443在路由器上单独用就能返回正确结果，也没有解析失败的情况出现，223.5.5.5不丢包，这两个DNS在其他同类软件中也可以正常工作，只有本软件出现异常
@Incubator85653 不会调优先级，任务管理器没有相关选项

**Comment by Incubator85653** [comment]
@jrkkei 右键服务名，选转到进程，再右键设置优先级。
这是为了看看是不是没获得足够的 CPU 时间。

**Comment by jrkkei** [comment]
好像找到原因了，系统自带的DNS client服务没开，打开就没再出现找不到服务器了，以前用的软件都是自带缓存的，一时间也没往这方面想，要是给个提示就更好了。。。
不过nslookup所有国内网站都会有
DNS request timed out.
    timeout was 2 seconds.
实际使用是正常的，解析速度很快。国外网站没有这个提示
@Incubator85653 原来在这里设置，细心点应该就能找到了，丢人了

**Comment by jzp820927** [comment]
DNS request timed out.
timeout was 2 seconds.

这个，我也有，每个解析都要超时2秒。

**Comment by chengr28** [comment]
境内 DNS 服务器 AAAA/IPv6 记录的解析在开启 `Local Force Request` 功能同时没有实际地址结果时的确是不能获取成功的，因为 nslookup 默认是请求了3次其中有次就是 IPv6 地址。应该是程序流程上有问题，下个版本会修正

**Comment by chengr28** [comment]
刚才发布的新版本应该已经解决这个问题了，可以试试w
