### ISSUE TITLE
为什么我的测试是IPV6的？我不是校园网。

### ISSUE THREAD

**Issue by streamgo** [chengr28/Pcap_DNSProxy#166]
### 运行环境及程序版本号

最新版。

### 问题重现步骤

1.CMD中  nslookup www.google.com
2.出现IPV6的DNS。
3.

### 程序错误日志

此处粘贴错误日志，如果错误日志行数过多，可使用外链
（提交时删除本提示）

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>nslookup www.google.com
服务器:  pcap-dnsproxy.localhost.server
Address:  ::1

非权威应答:
名称:    WwW.GoOgLe.cOm
Addresses:  2404:6800:4005:804::2004
          216.58.199.100

C:\Users\Administrator>

**Comment by Incubator85653** [comment]
在 cmd 中运行
ipconfig /all>123.txt

这将产生一个含有你网络配置信息的 txt，将那个 txt 的内容全部复制发上来能进一步分析这个问题。

**Comment by streamgo** [comment]
Windows IP 配置

   主机名  . . . . . . . . . . . . . : PC201408242246
   主 DNS 后缀 . . . . . . . . . . . : 
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 本地连接:

   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Realtek PCIe FE Family Controller
   物理地址. . . . . . . . . . . . . : B8-2A-72-9C-94-34
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::d950:226f:a64f:4352%11(首选) 
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.33(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2016年5月30日 星期一 上午 10:25:15
   租约过期的时间  . . . . . . . . . : 2016年6月4日 星期六 上午 11:17:28
   默认网关. . . . . . . . . . . . . : 192.168.1.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : 280504946
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-1B-8B-B5-B1-B8-2A-72-9C-94-34
   DNS 服务器  . . . . . . . . . . . : ::1
                                       127.0.0.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

无线局域网适配器 无线网络连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Dell Wireless 1705 802.11b/g/n (2.4GHZ)
   物理地址. . . . . . . . . . . . . : 64-5A-04-44-F7-F5
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

隧道适配器 isatap.{9693ECA3-9396-4CF8-82CE-841C9A08D515}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft ISATAP Adapter
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

隧道适配器 isatap.{D1E1CEA4-DD39-48B8-8C2E-5348B9506310}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft ISATAP Adapter #2
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

**Comment by streamgo** [comment]
我家里和公司，同样的系统WIN7 64位，同样的配置环境，都是同样的这个问题。

**Comment by chengr28** [comment]
首先要区分『通过 IPv6 协议查询域名』和『查询到域名的结果是 IPv6 地址』的区别，现在看来这种情况似乎是后者，因为 nslookup 默认是会查询 AAAA/IPv6 记录的，实际上 IPv4 的 DNS 也可以查到 IPv6 的地址，IPv6 的 DNS 也可以查到 IPv4 的地址

**Comment by Incubator85653** [comment]
备份你的 "Config.ini"，按如下检查和修改：

[DNS]
Protocol = IPv4 + UDP
Direct Request = IPv4
...
[Local DNS]
Local Protocol = IPv4 + UDP
...
[Addresses]
IPv6 Listen Address = 
IPv6 Alternate DNS Address = 
IPv6 Local DNS Address = 
IPv6 Local Alternate DNS Address = 

试着改成相同的设置以后用 "ServiceControl.bat" 重启 pcap dns proxy。
然后再测试解析情况。

**Comment by streamgo** [comment]
@Incubator85653 @chengr28 按照楼上修改配置文件后，重启服务，得到的结果和此前的是一样的。而教程上正常情况下，应该是如下显示：

**Comment by streamgo** [comment]
3.运行结果应类似：

   >nslookup www.google.com
    服务器:  pcap-dnsproxy.localhost.server（视配置文件设置的值而定，参见下文 配置文件详细参数说明 一节）
    Address:  127.0.0.1（视所在网络环境而定，本地监听协议为 IPv6 时为 ::1）

    非权威应答:
    名称:    www.google.com
    Addresses: ……（IP地址或地址列表）

而我这里显示的非127.0.0.1，而是直接::1

**Comment by streamgo** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>nslookup www.google.com
服务器:  pcap-dnsproxy.localhost.server
Address:  ::1

非权威应答:
名称:    wWw.gOoGlE.CoM
Addresses:  2404:6800:4005:803::2004
          216.58.199.100


C:\Users\Administrator>

**Comment by Incubator85653** [comment]
zip打包你的整个 pcap dns proxy 安装目录，包括配置文件，用附件发送到 ms10717015@outlook.com，
今天刚好有时间来详细检查一下。

**Comment by streamgo** [comment]
@Incubator85653 太感谢了！我马上发送给您。万分感谢！

**Comment by streamgo** [comment]
@Incubator85653 邮件贴到了吗？

**Comment by Incubator85653** [comment]
首先恢复你之前的备份，然后按以下检查和修改：

[DNS]
Protocol = IPv4 + UDP
Direct Request = 0
...
[Addresses]
IPv4 Listen Address = 127.0.0.1:53

你的配置文件中这一项空着，保险起见填写一个127.0.0.1:53或者0.0.0.0:53。
只有一台电脑要用的情况下这两个效果是一样的。
Direct Request 仍然是按照你的实际情况来设置。不一定要是0。

然后在 网络和共享中心 - 更改适配器设置 - 右键当前用于联网的适配器，属性
在新的设置窗口中取消勾选 "Internet 协议版本 6 (TCP/IPv6)"，按确定保存。
选中 "Internet 协议版本 4 (TCP/IPv4)"， 点击下方三个按钮最右侧的"属性(R)"
新窗口的下半部分选择 "使用下面的 DNS 服务器地址(E):"
"首选 DNS 服务器(P)" 填写127.0.0.1。备用不填写，空着。
两次确定保存，之后重启电脑确保新的设置起作用，和测试 pcap dns proxy。

**Comment by streamgo** [comment]
@Incubator85653 这次可以了。禁用IPV6协议并按照如上调整设置后。重启了服务，没有重启电脑。如下内容：

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>nslookup www.google.com
服务器:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

非权威应答:
名称:    wWw.gOoGlE.CoM
Addresses:  2404:6800:4005:803::2004
          216.58.197.100


C:\Users\Administrator>

**Comment by Incubator85653** [comment]
```
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>nslookup www.google.com
服务器: pcap-dnsproxy.localhost.server
Address: ::1

非权威应答:
名称: wWw.gOoGlE.CoM
Addresses: 2404:6800:4005:803::2004
216.58.199.100

C:\Users\Administrator>
```

这里可能的情况是即使你没有拥有一个 IPv6 的互联网连接，但是你的局域网可监听地址被分配了一个可用的 IPv6 地址，而你的 "Config.ini" 中没有明确指定要监听到哪个 IP 上，于是被挂到了那个 IPv6 的本机 IP 上。从原理上来讲，这是不影响你正常使用的。

IPv6 的 "::1"，相当于 IPv4 的 "127.0.0.1"，它不往互联网发送信息，所以你通过这个本地地址查询到的 DNS 结果依然包含正常的 IPv4 结果，你也就能正常地上网。

**Comment by streamgo** [comment]
@Incubator85653 明白了，确实不影响我的正常上网使用。只是困惑在不懂为什么会出现这样的情况。现在了解了。

再次感谢您的指点和教导！

**Comment by Incubator85653** [comment]
@chengr28 @streamgo 他这个情况是 pcap dns proxy 的监听地址被挂到本地 IPv6 版 127.0.0.1 上了
（我不确定怎么称呼 "::1"）
整个解析过程相当于浏览器往 IPv6 "::1"发了一个请求，然后 pcap dns proxy 通过 IPv4 UDP 向上级 DNS 发送查询请求，再将结果通过 IPv6，从 "::1" 返回给浏览器。
解析过程是正常的，不过这个用户主要好奇的是
为什么他 nslookup 以后底下出现的"::1"和教程中写的"127.0.0.1"不一样。

……就这个破事hhhhhhh

**Comment by streamgo** [comment]
@Incubator85653 是的。我一开始理解的是，为什么我没有IPV6网络，解析时却是使用了IPV6的DNS去解析。

**Comment by Incubator85653** [comment]
@streamgo 新的 Windows 系统自动为每个适配器分配 IPv4 和 IPv6 的局域网 IP 段，
你知道 127.0.0.1 这个 IP 地址是每台电脑都只能访问自己的那个 127.0.0.1。
::1 也是这种 IP 地址，是自动分配的保留 IP，互联网不使用这个 IP。

即使你的互联网不支持 IPv6，甚至根本就没有互联网，局域网里依然可以使用 IPv6 协议互相通信。

**Comment by streamgo** [comment]
@Incubator85653 明白了。以前因为没有遇到过这样的问题，所以来请教。现在理解了。多谢！

**Comment by chengr28** [comment]
@Incubator85653 `::1` 是回环地址，和 `127.0.0.1` 是一模一样的

**Comment by streamgo** [comment]
@chengr28 是的，明白。谢谢了！
