### ISSUE TITLE
平行地址一次返回多个记录一般使用第1个，如果第一个挂了以后会访问其他的可用IP吗？。

### ISSUE THREAD

**Issue by kang000feng** [chengr28/Pcap_DNSProxy#167]
* Hosts/CNAME Hosts/Source Hosts - 
  * 例如有一个 [Hosts] 下有效数据区域：
    127.0.0.1|127.0.0.2|127.0.0.3  localhost
    * 请求解析 localhost 的 A 记录（IPv4）会返回 127.0.0.1、127.0.0.2 和 127.0.0.3
 ，一般使用第1个 127.0.0.1，

这果有两个疑问请教大神：1)如果一开始尝试连接发现第一个挂了(TIME OUT/RESET)，浏览器会访问其他的IP 127.0.0.2 or 127.0.0.3吗？
2）如果连接了一段时间后第一个IP挂了，这时候 浏览器会访问其他的IP 127.0.0.2  or 127.0.0.3吗？
谢谢！不知道TCP/IP api的对于这种情况如何处理

另外请问如果windows下system32\drivers\etc的hosts 设置 
127.0.0.1 localhost
127.0.0.2 localhost
127.0.0.3  localhost
是不是浏览器请求解析 localhost 的 A 记录也会返回3 个A记录？ 除了system32\drivers\etc的hosts 域名不支持正则外，最后达到的效果有区别吗？

**Comment by chengr28** [comment]
* 程序：平行地址 Hosts 实际上是一次性给请求者返回多个地址，至于具体是这些地址里面哪个排第一个是程序随机选择的，也就是说有可能每次请求出来的顺序都不一样
* 操作系统/应用程序：接收到结果后绝大部分都会选择结果列表中的第一个作为目标地址，如果第一个目标地址出现问题，处理的策略则是操作系统/应用程序自己控制的，也就是说每个系统/每个应用程序的处理方法（是直接提示无法访问还是尝试其它地址）可能都不一样，不能一概而论
* 系统的 Hosts：并没有平行地址的功能，写成这样的话效果就是只有第一个条目也就是 `127.0.0.1 localhost` 生效。至于程序这边的 Hosts 比系统的 Hosts 多了哪些功能，建议参阅说明文档的介绍

**Comment by jzp820927** [comment]
据我实际测试得出的结果，目前不管是操作系统，还是应用程序，如果在第一个IP失效的情况会，不都会去尝试其他的IP，使用说多IP的平行地址，实际上，目前没什么实用性。
