### ISSUE TITLE
在网络不稳定的时候(如频繁掉线的时候)，CPU占用率可能会很高

### ISSUE THREAD

**Issue by 02015678** [chengr28/Pcap_DNSProxy#168]
﻿### 版本号及运行环境
**0.4.6.1**
 Windows

### 问题重现步骤
连接一个不稳定的无线网络，他经常掉线

### 期望的程序行为
在无法连接主DNS服务器和任何备用服务器的时候，暂停fetch工作，仅依赖本地Cache工作。

### 实际的程序行为
可能是在不停的尝试?这导致了CPU占用率容易过高

**Comment by chengr28** [comment]
关于断网……有两种类型，识别的情况完全不相同：
* 一种情况是所有网络适配器处于非激活状态（例如网线或者 WLAN 断了）这种程序是可以识别并将问题输出到错误记录中的
* 一种情况是网络适配器处于激活状态但网络实际上是不通的，这种情况并没有什么比较好的通用的解决方法，微软是依靠 NCSI 做监控，但这个仅仅只是个起参考作用的指示器不具有实际的控制用途。实际上这个指示器似乎经常会误判，更不用说本项目向境外服务器请求时的丢包和 DNS 服务器本身不稳定之类的因素了
* 关于 CPU 占用的问题，多个不同平台对以上两种情况的实际测试似乎没观察到占用率极高的情况。至于重试机制是否会导致额外占用率的问题，参见下文
* 当网络离线时程序的表现可以分为：
  * 所有网络适配器处于非激活状态时，所有网络程序（包括本程序）均不能发送或接收任何网络数据包（包括本机内部的数据包）这个是系统 TCP/IP 栈策略决定的
  * 网络适配器处于激活状态但网络实际上是不通时：这种情况程序可以使用回复请求，但是由于上文所说对于『网络实际是否通畅』无法进行准确判断，所以无法阻止程序向远程服务器发起请求。程序 **并没有重试的机制** 本身只是类似数据包传递者这样的角色，所以重试实际上是请求者（系统或者需要域名解析的其它程序）进行的，程序无法对其进行控制
