### ISSUE TITLE
2015-03-14 中的 DNSCurve 似乎有问题

### ISSUE THREAD

**Issue by yfdyh000** [chengr28/Pcap_DNSProxy#17]
Win8.1 x32，默认配置，启用 EDNS0 Label = 1 和 DNSCurve = 1
启动服务，始终返回：
> 无法启动服务
> 无法完成该操作。
> 服务没有及时响应启动或控制请求。

Error.log 无日志输出。

另外，2015-03-14更新了什么，没有变更日志。

**Comment by chengr28** [comment]
嗯昨天发的 Beta 13（没有改版本号）那个似乎是有问题的……
刚才更新了 Beta 14 应该已经把问题修复好了，试试ww

**Comment by yfdyh000** [comment]
好像好了，谢谢。

不过，Local Main / Local Hosts / Local Routing 现在只能选择一个了吗，或者说就应该只选择一个吗。
记得以前可以全=1的，现在两个及以上=1就会报 Parameter Error 并退出。

**Comment by chengr28** [comment]
之前的版本没有进行限制，后来仔细想了下，这三个选项有逻辑上的冲突：
Local Main - 所有请求发往 Local 服务器，除非遇到黑名单或者 Local Routing 开启时检测失败的
Local Hosts - 根据 Local Hosts 名单决定是否发往 Local 服务器
Local Routing - Local 路由表识别功能国内地址

因为黑名单已经失效了现在一般开第一个和第三个，第二个既然是根据名单判断了就不能开其它的，最后一个在其它两个没开的情况下是没有意义的

**Comment by yfdyh000** [comment]
感谢解答，但看着有点云里雾里的，Documents 中目前也没描述需求和优先级。

“因为黑名单已经失效了现在一般开第一个和第三个”，意思是只开第一个效果不好？
“最后一个在其它两个没开的情况下是没有意义的”，意思是第三个需要前两个？但不是“第二个既然是根据名单判断了就不能开其它的”吗。

**Comment by chengr28** [comment]
刚才表达有点问题……应该是：
* 不开 Local Main 就不会通过 Local 服务器进行解析，开了 Local Hosts 的话 Local Routing 就没有意义了，所有 Local Main 开了后才能开 Local Routing
* Local Hosts 是根据域名白名单来匹配，既然已经有白名单也就不需要做过滤了，所以 Local Routing 过滤是没有意义的，不能同时开
* 既然开了 Local Main 所有解析先通过 Local 服务器进行解析，那么再用 Local Hosts 域名白名单就是没有意义的，所以不能同时开

**Comment by yfdyh000** [comment]
我的理解：
第一条，Local Routing 在 Local Main 开启时有效。
第二条，Local Routing 不能作为白名单的补充、二次检查吗？如果白名单有未知的遗漏。
第三条，Local Hosts 在关闭 Local Main 时才有效？

还是有点乱，最好在文档中写一下……

**Comment by chengr28** [comment]
文档中也差不多的……只有一句话 =_/=
* 对的
* 似乎是对白名单的理解有偏差……白名单是说，这列表里的域名使用 Local 请求解析时无条件信任的，如果做了二次检查那还能被称为『白名单』吗？
*  Local Main 就是所有请求先发往 Local 服务器进行解析，注意是『所有请求』那么既然是所有的请求都发 Local 服务器那此时还要白名单有什么意义？

**Comment by yfdyh000** [comment]
* OK
* 我之前对Local Hosts的理解是优先发往境内，然后再检查黑名单和Routing。原来是无条件信任……

**Comment by chengr28** [comment]
『优先发往境内，然后再检查黑名单和 Routing』那个就是 Local Main 的功能了ww

**Comment by yfdyh000** [comment]
嗯，我的想法是Local Main和Local Hosts能否都=1，效果是首先都首先发往境内，然后检查白名单（Local Hosts=1）、黑名单和路由，如果匹配白名单就跳过路由检查，也就是允许白名单内的境内域名返回境外地址。不确定理解是否正确。

**Comment by yfdyh000** [comment]
如果用Local Main = 0、Local Hosts = 1、Local Routing = 0，我理解的效果是，仅白名单的域名发往境内，其他域名都发往境外，怀疑这样是否延迟稍高。

**Comment by chengr28** [comment]
是这样，Local Main 启用时所有请求都发往 Local 服务器，收到解析后再进行过滤（如果有 Local Routing 的话）再决定是否信任。而 Local Hosts 则是先检查域名是否在白名单中，如果在就发往 Local 服务器并无条件信任收到的结果，其它没有命中的就直接跳过只会发往境外服务器的
所以我一直说同时启用是没有意义的……

**Comment by yfdyh000** [comment]
好像是我的思路错了，Local Hosts 似乎是我想要的。
嗯，只是有时觉得解析延迟稍高（数秒），我再调试看看吧。
谢谢耐心解答。感谢创造此项目。
