### ISSUE TITLE
最近频繁出现 Segmentation fault (core dumped) 错误，然后程序自动退出。

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#170]
﻿### 版本号及运行环境
Pcap_DNSProxy 0.4.6.2
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"

### 问题重现步骤
运行没有多久(有时几秒，有时几分钟)，就出现下面的错误。然后程序自动退出。
./Pcap_DNSProxy --disable-daemon
Segmentation fault (core dumped)

### 与默认配置不同的部分
为了调试全部用默认配置，没改，就添加了一些 google 域名的 hosts 记录

### 程序错误日志
错误日志一直是空。

**Comment by chengr28** [comment]
这个是程序崩溃了，性质和之前那个卡死又不一样了……大概是什么版本开始出现这个情况的？

**Comment by jzp820927** [comment]
应该就是 我上面贴的那个版本吧，因为不出问题，我一般都不升级的，所以这个版本之前的版本是很老的版本了。这次也是升级 ubuntu 系统，顺带一起重新编译了源码。

**Comment by wongsyrone** [comment]
据我所知，ubuntu会将coredump转给apport，如果想要更好的定位问题，编译传入`-g -O0`，当再次出现问题时，可以将coredump文件发上来。其他详情请Google

**Comment by jzp820927** [comment]
我去，空了，我试试。

**Comment by chengr28** [comment]
刚才推送了新的版本，发之前专门留了一段时间测试了一下在 Linux（这边是 Debian）平台的运行情况，暂时没发现有 `Segmentation fault` 的情况，可以更新到最新版本试试。如果还是不行，建议如 @wongsyrone 所说尝试定位问题，因为段错误这边也不好找具体是哪里的问题……

**Comment by jzp820927** [comment]
好的谢谢，这段时间我这边也没重现这个问题，不知道具体是什么原因导致的，估计可能是某些特殊情况造成的，如果问题重现了，我再来反馈，谢谢！

**Comment by chengr28** [comment]
如果还出问题的话直接 Reopen 一下就行了……直接说也行
这边第一时间都有邮件通知的
