### ISSUE TITLE
Feature Request: Address Hosts 按掩码映射

### ISSUE THREAD

**Issue by LGA1150** [chengr28/Pcap_DNSProxy#171]
目前 Address Hosts 只能实现对单个地址的映射，所以能否实现一个按掩码映射的功能？
如:
`6.7.8.0    1.2.3.0 24` 会把 1.2.3.56 1.2.3.67 分别映射到 6.7.8.56 6.7.8.67 ， 
`2001:db8:1::   2001:db8::  96` 会把 2001:db8::abcd 映射到 2001:db8:1::abcd

**Comment by chengr28** [comment]
这功能看起来并没有什么意义……

**Comment by jzp820927** [comment]
我也有这种赶脚，可能唯一的功能就是少写几条配置。

**Comment by LGA1150** [comment]
很多大型网站/CDN的 IP 都是有规则的，比如 Google, Akamai, 甚至一些国内CDN商（如百度开放云、百度运加速等），规则就在于后面几位都是固定的
这个功能方便批量批量映射（达到加速或者绕过某墙的目的），避免了一个网段下有多少 IP 就要写多少行规则的麻烦
dnsmasq 也有类似功能，叫做 alias

**Comment by chengr28** [comment]
有时间看看……

**Comment by chengr28** [comment]
刚才的新版本添加了这个功能，不过格式上和建议的有点区别，这边处理也不会弄得太复杂。本质上 `Address Hosts` 类型的条目是按照地址范围指定的，所以识别地址的时候并没有应用网络前缀长度的规则，而是只把规则部署到替换地址时才会生效，例如：

    192.168.1.1/16 172.16.0.0-172.31.255.255

是把地址范围 `172.16.0.0/12`（= `172.16.0.0-172.31.255.255`）内地址的前 16 位数据换成 `192.168.0.0` （由于只指定了前 16 位，后面 16 位写什么都没有所谓，但是不能不写）的前 16 位。举个例子

    127.28.38.48

这个地址属于 `172.16.0.0/12` 会被上面的规则替换为 `192.168.38.48`
这样处理好处是识别的范围和替换的行为不挂钩，可分成两个不同的部分进行处理
更多对此格式的要求，可参见说明文档相关章节的介绍
