### ISSUE TITLE
解析 localhost.ptlogin2.qq.com 到 127.0.0.1

### ISSUE THREAD

**Issue by hyxxsfwy** [chengr28/Pcap_DNSProxy#173]
```localhost.ptlogin2.qq.com```、```localhost.ptlogin2.qcloud.com``` 等域名是QQ快速登录获取本地 clientkey 使用的域名，DNS的解析地址为 127.0.0.1。
在使用 Pcap_DNSProxy 后若不手动添加 Hosts ```127.0.0.1 localhost.ptlogin2.*.com```，则QQ的快速登录功能失效。
其实这是个如何正确处理有些域名会解析到本地地址的问题，[Public Wildcard Domain Name To Resolve To 127.0.0.1](https://stackoverflow.com/questions/1562954/public-wildcard-domain-name-to-resolve-to-127-0-0-1 "https://stackoverflow.com/questions/1562954/public-wildcard-domain-name-to-resolve-to-127-0-0-1")，请C大加以修正。

**Comment by chengr28** [comment]
刚才推送的更新已经解决这个问题了……
回环地址这个问题的确不好解决，原本这个是内置在程序内部最高级别黑名单里的地址，这次应该算是误伤了，不过这边有收到过报告说会使用这个地址进行 DNS 投毒污染，所以这个情况不好处理
