### ISSUE TITLE
开启ipv6后无法解析

### ISSUE THREAD

**Issue by jrkkei** [chengr28/Pcap_DNSProxy#174]
﻿### 版本号及运行环境

最新版本。
6in4隧道，win10 x64

### 期望和实际的程序行为

国外网站全无反应
v6 dns能ping通

### 与默认配置不同的部分

Protocol = IPv6 + IPv4 + TCP或IPv6 + TCP，状况完全一样

IPv6 DNS Address = [2620:0:CCC::2]:5353|[2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = [2001:4860:4860::8888]:53|[2620:0:CCD::2]:443

### 程序错误日志

Network Error: Socket Hop Limits setting error, error code is 10022

**Comment by chengr28** [comment]
请参阅说明文档的 `安装方法` 中 `6.特别注意` 的内容：

`如需让程序的流量通过系统路由级别的代理（例如 VPN 等）进行域名解析，请选择其中一种方案，配置完成后重启服务..`
`* Direct Request = IPv4`
`* Direct Request = IPv6`
`* Direct Request = IPv4 + IPv6`

**Comment by gaoyan1234** [comment]
我是校园网ipv6网络 不开启direct request 也是10022错误 为啥

**Comment by jzp820927** [comment]
LS 都说了，是需要配置 Direct Request，你现在是不开启 direct request ，肯定不行撒。

**Comment by chengr28** [comment]
@jzp820927 不不，这个 `Direct Request` 选项的意思是『直连模式』也就是说使用类似楼主的『隧道』或者『VPN』才需要打开，原生 IPv6 网络是不需要开启的（就像原生 IPv4 网络一样），不能用是其它的问题
