### ISSUE TITLE
中科大dns似乎通不过dns头检测

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#177]
﻿### 版本号及运行环境
windows7x64
pcap_dnsproxy 0.4.6.6

### 问题重现步骤
- 修改默认配置只留两个中科大dns, 开启dns头检测
```
IPv4 DNS Address = 202.141.162.123:53|202.141.176.93:53
IPv4 Alternate DNS Address = 
IPv4 Local DNS Address = 
IPv4 Local Alternate DNS Address = 
DNS Data Filter = 1
```

### 期望和实际的程序行为
+ 期望 正常解析
+ 实际 解析超时

### 程序错误日志
> 2016-07-31 09:54:14 -> Log opened at this moment.
2016-07-31 09:54:14 -> Network Error: UDP Monitor socket initialization error, error code is 10038.

### 备注
另请求和回返报文抓包已发送至你邮箱

**Comment by chengr28** [comment]
你好，首先感谢你的反馈。看了抓包的结果，中科大的 DNS 似乎会强制在每个解析结果的最后附带提供所有 NS 权威服务器的列表，程序在处理这部分数据的时候，应该是规则过于严格导致数据包无法通过伪造数据包模块的检测，下个版本会修复这个问题

**Comment by chengr28** [comment]
刚才推上来的更新应该已经解决这个问题了……如果还是不行可以直接邮件联系，或者 Reopen 这个 Issue

**Comment by muink** [comment]
挺好奇dns检测是如何识别污染包的
我只知道通常情况下
请求中含有认证域名会触发污染
返回两个100ms以下几乎同时到达的包
而且都只带一个a记录

**Comment by jzp820927** [comment]
最简单的办法就是通过污染 IP 数据库来识别

**Comment by chengr28** [comment]
具体的原理源代码有，基本上是搜集了伪造数据包的特征和其它诸如包头信息之类的，是个组合判断方案，不是依靠单一的算法过滤的

@jzp820927 地址黑名单以前有用，但去年开始有随机地址投毒污染的，基本上只靠这个方法是已经失效了，程序里也有，现阶段只能作为辅助手段用来提高解析的可靠性

**Comment by jzp820927** [comment]
恩，是有段时间污染 IP 随机化，但是现在好像又比较固定了，我观察了很长一段时间，基本上就只有常见的几个IP了，可能是我观察到网址比较少，不知道其他人是什么情况
