### ISSUE TITLE
Pcap_DNSProxy是否存在内存泄漏及CPU异常占用问题？

### ISSUE THREAD

**Issue by AnyoeDove** [chengr28/Pcap_DNSProxy#178]
﻿### 版本号及运行环境
npcap: 0.08r2
Pcap_DNSProxy: 0.4.6.6
Windows: Windows 10 Enterprise 2015 LTSB (x64) (内部版本：10240)
CPU: i5-4200M
内存: 12G

### 问题重现步骤
Pcap_DNSProxy运行一段时间后，出现波动的CPU占用以及不断增高的内存占用。该问题出现时电脑无特殊操作，均为正常浏览网页或者什么都没做.....
启动后几秒：
![1 start](https://cloud.githubusercontent.com/assets/10519576/17317500/e8d35020-58b0-11e6-8044-d8d8f8a9cdf6.png)
启动后十分钟：
![2 somehow](https://cloud.githubusercontent.com/assets/10519576/17317512/12cc5066-58b1-11e6-8e9c-2002cd9ee335.png)
CPU占用异常：
![3](https://cloud.githubusercontent.com/assets/10519576/17317522/29ff6548-58b1-11e6-9a74-7b0fef66e140.png)

### 与默认配置不同的部分
[Base]
File Refresh Time = 6
[Log]
Log Maximum Size = 6MB
[DNS]
Protocol = IPv6 + IPv4 + TCP + UDP
[Addresses]
//DNS均采用非53的私有DNS，端口号在18000-30000之间。

### 程序错误日志
无

恢复File Refresh Time = 15后内存占用上升减缓，但仍存在CPU波动情况：
![4](https://cloud.githubusercontent.com/assets/10519576/17317527/3ffdcd3a-58b1-11e6-81b0-cf6a8494018a.png)

**Comment by chengr28** [comment]
内存泄漏的问题其实在 0.4 正式版后借助智能指针已彻底解决了……

现在内存占用很高大概是开启了 `Local Hosts` 境内域名白名单的缘故，因为白名单的机制是正则表达式，海量的正则表达式和匹配动作有耗用大量 CPU 和内存资源的可能性。按照默认配置在 Windows 下内存正常是 4MB - 7MB 之间的，如果条件许可可以试试把 `Local Hosts` 关掉，然后启用 `Local Main` + `Local Routing` 路由表匹配模式，重启服务再看看资源占用的情况

**Comment by AnyoeDove** [comment]
我原来就是Local Hosts = 0 Local Main = 1 Local Routing = 1，不过我会更新whitelist.txt，是会自动加载whitelist即使Local Hosts = 0吗？
删除目录下的whitelist.txt后重新启用pcap_dnsproxy之后内存维持在5-6M间，CPU波动维持在1%-3%之间，我再观察一下。

**Comment by chengr28** [comment]
没开 `Local Hosts` 而只是修改 WhiteList.txt 也会造成资源占用飙升？

**Comment by AnyoeDove** [comment]
.....我不知道....把whitelist放回去后重启服务内存占用并没有上去....
不知道要怎么复现= =只有这几天才注意到奇怪的内存占用跟CPU占用...

**Comment by chengr28** [comment]
我的意思是在不重启服务的情况下修改 WhiteList.txt 文件，保存然后监察一段时间这样看看程序会不会出现资源占用飙升的问题……因为程序隔 `File Refresh Time` 秒刷新一次非配置文件是否有修改然后重新载入的，有可能这部分设计有问题导致资源占用飙升

**Comment by chengr28** [comment]
刚才测试了一下，并已经成功重现 Issue 提到的问题，和这边的设想是一样的：
* 在 `Local Hosts` 未启用的情况下无论怎么修改白名单都不会出现问题
* 在 `Local Hosts` 启用但不修改白名单，匹配时 CPU 占用偏高，内存占用稳定在 30MB
* 在 `Local Hosts` 启用后多次修改白名单，内存飙升并稳定在 60MB 附近
* 造成这种情况的原因就像上面所说，海量的正则表达式和匹配动作耗用大量 CPU 时间和内存资源……这边有时间考虑一下解决方案，建议先用 `Local Main` + `Local Routing` 顶着……

**Comment by jzp820927** [comment]
想不到 正则 这么消耗资源，还好我是部署在独立服务器上的，资源不是问题。

**Comment by AnyoeDove** [comment]
突然想到一个问题 会不会跟IPv4 Alternate DNS Address所填写的DNS数量有关？
我之前填了9个....

**Comment by chengr28** [comment]
也有可能，不过对内存的消耗最主要应该还是上面提到正则表达式的问题
DNS 服务器数量填得多，对网络和系统的 I/O 消耗比较大，尤其是启用 TCP 连接的时候，不过这部分的资源消耗应该不会算到程序的专有资源占用里，Windows 上的话大概会是 System 之类的

**Comment by chengr28** [comment]
刚才推送的更新已经添加这个功能了，参见 ReadMe 文档中 Dnsmasq Address - Dnsmasq 兼容格式 一节的内容，把原来的 `正则表达式` 更换成 `Server=/域名后缀/` 格式保存并重启服务即可。

或者可以跟随程序的版本更新，把自带的 `WhiteList.txt` 更新到最新版本即可。实测 PC 上内存占用将稳定在 15MB/30MB 左右比原来减少 50% 以上，把正则表达式切换成域名后缀匹配所需的时间也将大幅下降
