### ISSUE TITLE
ControlService 失败 1062:  服务尚未启动。

### ISSUE THREAD

**Issue by viewtheard** [chengr28/Pcap_DNSProxy#18]
ControlService 失败 1062:

服务尚未启动。

0.4版没法启动服务怎么回事

**Comment by xinhugo** [comment]
@viewtheard 反馈问题时，提交详细信息，有助于快速定位问题。

例如：
操作系统版本：Windows 7
操作系统类型：X64
Pcap_DNSProxy 版本：v0.4 Beta 14(Windows)
Pcap_DNSProxy 配置是否为默认设置：是
Pcap_DNSProxy 目录下，是否出现：Error.log；如有，粘贴内容。
WinPcap 版本：4.1.3

**Comment by xinhugo** [comment]
经测试，Windows XP X86、Windows 7 X64，Pcap_DNSProxy v0.4 Beta 14 正常运行。

**Comment by viewtheard** [comment]
搞定了,下成master版了
