### ISSUE TITLE
当前版本是否支持 HTTP2 代理？

### ISSUE THREAD

**Issue by agentmario** [chengr28/Pcap_DNSProxy#181]
### 版本号及运行环境

0.4.6.7, Windows 10 x64
### 疑问

在 Proxy 配置中发现可以指定 HTTP 协议版本，请问是否支持 HTTP2 代理

**Comment by chengr28** [comment]
并不能……HTTP/2 需要强制 TLS 加密连接的支持，程序并没有 TLS 协议的任何支持。程序的 SOCKS/HTTP Proxy 本身定位是作为本地或内部网络其它 SOCKS/HTTP 代理服务器（例如 SS 之类）之间联系的桥梁使用的，并不是作为一个远程请求的模块进行设计的

**Comment by chengr28** [comment]
不过设计之时 HTTP/2 并没有标准化……根据后来的资料，普遍使用的 h2 虽然强制要求使用 TLS 加密，但是也有不强制要求的版本 h2c 但是基本没有支持，这边可能会考虑支持 h2c 但是短期内应该不会提供

**Comment by chengr28** [comment]
刚才更新的版本已经为 HTTP CONNECT 隧道添加了对 HTTP/2 协议的支持，两个版本 h2 和 h2c 的协议，以及 HPACK 头部压缩算法除了动态索引表外（静态索引表，Huffman 编码，纯字符串）都有实现，有兴趣可以试试。
