### ISSUE TITLE
ICMP Test 和Domain Test 参数无效

### ISSUE THREAD

**Issue by xieqiyou** [chengr28/Pcap_DNSProxy#182]
最新版本在win10下
不论Domain Test 设置多少秒。每7秒就会向IPv4 DNS Address的dns服务器发生测试包。
可不可以设置关掉这个测试包的

**Comment by chengr28** [comment]
关掉 `Domain Test` 在 GitHub 最新的版本上有了，不过 Windows 的版本还有些问题要处理，所以 Release  那边还没有更新。新版本出来后把这个值设成 0 就能关掉
* 不过其实个人不建议关掉，因为程序是根据这些包对来自真实的数据包进行检测和记录，关掉会对伪造数据包识别率有很大的影响
* 至于你说每 N 秒（其实不是 7 秒而是 5 秒）就会发一次，而且 *不间断* 有个可能就是指定的 DNS 列表里的某个地址失效或者一直记录不到真实的数据包，建议是检查一下所有的 DNS 服务器状况

**Comment by chengr28** [comment]
新版本可以设置成 0 关掉这两个功能了
