### ISSUE TITLE
为什么我总是显示 请以管理员身份运行啊

### ISSUE THREAD

**Issue by hexianfu** [chengr28/Pcap_DNSProxy#183]
ServiceControl.bat 这个点出来之后就出现这个问题 我是用右键管理员运行的，我笔记本上前几天刚装上的，现在台式上就这个问题！

**Comment by jzp820927** [comment]
你的意思是用右键管理员运行，会提示 “请以管理员身份运行”，那么不用右键管理员运行，直接运行试试呢？

**Comment by hexianfu** [comment]
@jzp820927  都一样！还是要提示

**Comment by jzp820927** [comment]
这个有点不科学啊，没遇到过类似问题，等老大来给你看看吧

**Comment by hexianfu** [comment]
不是！但有管理员权限，我笔记本也没用administrator  登录的啊

**Comment by chengr28** [comment]
`net session` 批处理依靠的是这个判断是否为管理员权限运行
如果怀疑有问题，可以在普通用户和以管理员权限分别在 cmd 里运行看看结果

**Comment by chengr28** [comment]
之前专门在从 Windows XP 到最新 Windows 10 都测试过，因为这个程序系统都有自带，所以并没有发现出问题的情况，如果有新情况可以直接在这里回复
