### ISSUE TITLE
Missing ntohs on DNS_Record_Standard->Length

### ISSUE THREAD

**Issue by pzread** [chengr28/Pcap_DNSProxy#186]
Shouldn't the `DNS_Record_Standard->Length` need to be converted by `ntohs` first before being compared with the `DOMAIN_MINSIZE` ?

https://github.com/chengr28/Pcap_DNSProxy/blob/master/Source/Pcap_DNSProxy/Protocol.cpp#L1291

I haven't verify it yet. Just found it when doing a light review.

**Comment by chengr28** [comment]
It's a bug, has been fixed in 0.4.7.2.
Thanks for your report w
