### ISSUE TITLE
Windows 版 0.4.7.2 无法重启服务，0.4.7.1 及以前版本正常

### ISSUE THREAD

**Issue by smounives** [chengr28/Pcap_DNSProxy#187]
﻿### 版本号及运行环境
Pcap_DNSProxy 0.4.7.2
Windows 10 64-bit RS1 Build 14393.105

### 问题重现步骤
卸载旧版本并安装最新版，默认设置，选择 `5: Restart service`

### 期望和实际的程序行为
![image](https://cloud.githubusercontent.com/assets/9267814/18251795/e2da4e94-73bd-11e6-977d-801de13ace6c.png)

### 与默认配置不同的部分
无

### 程序错误日志
无

**Comment by wongsyrone** [comment]
我刚才测了一下，并没有问题，请确保ServiceControl.bat右键属性中没有“解除锁定”的复选框。

**Comment by smounives** [comment]
这个，我一直都有下载完文件以后解除文件锁定的习惯，确认没有

**Comment by wongsyrone** [comment]
从上面的截图可以看到显示了pid，可能是检测是否成功运行部分有问题，不过我这里无法复现。

**Comment by smounives** [comment]
![image](https://i.imgur.com/jbvOYzs.gif)

**Comment by smounives** [comment]
比较了一下两个版本的 ServiceControl.bat ，完全一样，尝试重装 WinPcap 无效

**Comment by chengr28** [comment]
不一定需要使用服务器脚本启动程序的，如果觉得程序有问题，直接双击 exe 也能启动程序

**Comment by wongsyrone** [comment]
也可能是之前卸载的有问题？

**Comment by smounives** [comment]
在旧版的ServiceControl里选择uninstall服务，删掉旧版文件，将新版文件复制过来，ServiceControl里选install，这样操作是否有误？

**Comment by wongsyrone** [comment]
应该是没错。毕竟批处理没改过。

**Comment by smounives** [comment]
算了…就这样用吧…

**Comment by jzp820927** [comment]
要是服务不能正常使用，就放到“启动”里面，效果是一样的吗

**Comment by chengr28** [comment]
看起来批处理的确是有命令系统启动服务，不过看起来服务没有启动成功
所以刚才说『如果觉得程序有问题，直接双击 exe 也能启动程序』

**Comment by smounives** [comment]
![image](https://cloud.githubusercontent.com/assets/9267814/18265924/a2e81cde-744a-11e6-9c49-f69eedebf57d.png)
Stop service 之后直接双击 Pcap_DNSProxy.exe 的结果，也许我该重装一波系统压压惊？

**Comment by smounives** [comment]
补充：直接运行 0.4.7.1 版后的结果
![image](https://cloud.githubusercontent.com/assets/9267814/18266111/9a7f0976-744b-11e6-9b9a-45c094578a08.png)

**Comment by smounives** [comment]
换了一台相同环境的台式机问题依旧，100% 重现，系统一样是 Windows 10 64-bit RS1 Build 14393.105

**Comment by chengr28** [comment]
刚才推送了新的版本，应该不会再有停止工作的问题了w

**Comment by smounives** [comment]
Fixed. Thanks!
