### ISSUE TITLE
老大,能不能搞一个携带版?

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#188]
可随时从可移动磁盘上启动

无需注册服务

不修改注册表的

**Comment by wongsyrone** [comment]
这个直接运行就可以吧

**Comment by jzp820927** [comment]
可以直接运行，服务只是附加功能，不影响程序运行。所以放U盘，完全没问题。

**Comment by muink** [comment]
@wongsyrone @jzp820927 可以运行
不过要怎么隐藏到后台
还有不太懂这个报错`console mode`是啥
![default](https://cloud.githubusercontent.com/assets/7929014/18337063/dc4257d0-75bf-11e6-8937-d49dd3e83bcb.PNG)

**Comment by jzp820927** [comment]
这个提示表示运行成功了，如果你不想看到这个 cmd 窗口，可以最小化，如果想最小化到托盘，可以用 goagent 的 taskbar ，修改下启动成功就可以了。如果想完全隐藏，可以用 nirsoft 的cmd

**Comment by chengr28** [comment]
程序本身是独立设计不依赖系统服务，没有系统服务也可以运行。不过如果想隐藏窗口，只能在这边编译的时候传送一个固定的隐藏窗口的命令，不能依靠启动后参数才设定，所以程序窗口在直接运行下是无法隐藏的，或者也可以试试前面说到的第三方工具

**Comment by muink** [comment]
应该可以的我试试单独搞个launcher
