### ISSUE TITLE
请问osx下如何刷新Pcap_DNSProxy的dns缓存?

### ISSUE THREAD

**Issue by kiliwalk** [chengr28/Pcap_DNSProxy#189]
﻿### 版本号及运行环境
stable 0.4.6.0, osx 10.11.6

我看windows下有刷新选项, 但没法找到osx下的. 
刷新了osx的系统缓存, 不管用. 
然后我移除dns设置中的127.0.0.1, dns确实已经更新. 但重新设置为127.0.0.1后, 还是原来的ip.

**Comment by chengr28** [comment]
这功能属于程序的外挂参数，需要使用终端进入程序所在目录，然后输入 `./Pcap_DNSProxy --flush-dns` 回车这样，Windows 下实际上也是这样，只是写成了批处理方便调用而已……
ReadMe 文档其实是有介绍的，节选一段：
```
程序运行参数说明：
由于部分功能无法通过使用配置文件指定使用，故而使用程序外挂参数进行支持
...
* --flush-dns
  立即清空所有程序内以及系统内的 DNS 缓存
```

**Comment by kiliwalk** [comment]
刷新缓存报错: `FIFO write messages error, error code is 6.`
使用sudo也是一样的错误.
重启service也是.

```
prw--w--w-  1 root  wheel  0 Sep  8 17:44 /tmp/pcap_dnsproxy_fifo
```

**Comment by chengr28** [comment]
呃 Mac 上的清空 DNS 缓存功能工作的确有问题，也不知道是不是系统升级机制改了还是这边设计的问题……下个版本应该可以修复这个问题

**Comment by chengr28** [comment]
刚才的更新应该已经修复这个问题了

**Comment by kiliwalk** [comment]
谢谢, 等brew有更新我再试试
