### ISSUE TITLE
IPv4 Alternate DNS Address 疑似bug

### ISSUE THREAD

**Issue by yfdyh000** [chengr28/Pcap_DNSProxy#19]
问题版本：v0.4 Beta 14(Windows) 2015.03.15；正常：v0.4 Beta 13(Windows) 2015.02.18。
目前默认配置中的 `IPv4 Alternate DNS Address = 8.8.8.8:53|208.67.220.220:53|208.67.222.222:53`
如果手动去掉后面两个OpenDNS的IP地址，只保留`IPv4 Alternate DNS Address = 8.8.8.8:53`，软件启动正常（无错误日志），但似乎所有请求都会超时，错误日志输出 Winsock Error: UDP request error, error code is 10049.。

另外，两项IPv4 Local好像不能像IPv4 DNS和IPv4 Alternate DNS那样用 | 指定多个地址，会报`Parameter Error: Item length error in line`错误。

**Comment by chengr28** [comment]
关于那个 Winsock 10049 错误，看了下的确是程序的问题，有个参数写错了
刚才已经上传了新的 Beta 14(2015-03-16) 版本，更新一下试试，应该是没有问题的

关于多线程请求，因为最近大半年来境外服务器丢包极其严重，工作日晚上甚至到了90%的丢包率……所以这个功能是设计提高 DNS 解析可靠性的。Local 服务器没有丢包的问题，而且不论 114DNS 这种还是 ISP 自己搭的挂了都是大事件……所以并没有为其设计多线程请求功能
其实只有 IPv4/IPv6 (Alternate DNS) 这4个参数是支持多线程的……

**Comment by yfdyh000** [comment]
看上去没问题了。发现这个问题是我不太喜欢OpenDNS，因为商业化和错误页插广告的行为。只是提一下，我清楚本项目自带了Blacklist过滤。

多线程是因为想能否实现并行化和白名单先到先得。既然是无条件信任，那么对于cn域名的解析，想着能否实现<50ms的解析速度，提高一点体验。没具体测试，不清楚具体的当前和软件内部黑白名单处理时延。

**Comment by chengr28** [comment]
说实话如果解析是成功的那么耗费在程序转发中的时间不过是网络 I/O 的零头……与其为了这可能不够一两 ms 的节省还不如去换个更快的网络和更好的网卡路由器之类……
关于并行化这些不同的请求功能其实是不好的，说白了就是用资源换时间。并行化的话，占用了多一倍（理论上应该是不止的）的资源去节省这一点点时间，是不值得的。之前也说过了，本程序的首要任务不是提高用户体验，想快的话应该是直接用系统的 DNS 功能，最重要的域名解析的可靠性

**Comment by yfdyh000** [comment]
程序耗时我指的是那个域名白名单的匹配，不知道有没有用到哈希表之类的技术，匹配效率如何，因为眼见一片正则，近5000行。还有中国路由，近6000行。黑名单应该是零头吧。
资源的话，感觉并发几个UDP并不耗资源吧，但如果加上监控就很费资源，那么还是程序本身耗时的问题。只是想能否保证可靠性的前提下改善速度，因为并不太清楚耗时在哪方面，就想是不是非并行的问题。

**Comment by chengr28** [comment]
之前测试过，最耗时的是网络 I/O 无误……至于程序里看过，Local Hosts 那个正则匹配默认那个列表完全做一次平均 20ms-40ms 的样子，正则匹配基本都很耗时 STL 的实现应该算是很好的了。至于那个路由表……完全做一次大概 0.12ms 左右。这些貌似都和 CPU 有关，不过应该差不多
至于并行……之前就说过其实只是用资源换时间而已，例如要多准备几个缓冲区接收数据进行对比之类，足足是原来是几倍，虽说现在 CPU 和内存之类越来越快越来越大，但着实没这个必要。事实上连检查 Hosts 这种事情都是可以并行化，但问题是如果这边命中了，那边并行请求的结果也拿到了，这个时候后面的动作不是很没有必要？

**Comment by yfdyh000** [comment]
20~40ms的确不算大。那个白名单好像都是普通匹配，其实用不上正则吧，感觉可以优化成哈希表的匹配，像是Addons Plus的算法，如果有兴趣实现的话。路由表那么低就没问题了。
嗯，几倍不清楚是多大，如果不是几MB感觉还是可以接受的。如果可以，并行做成个可选项也不错。

~~本地抓包测了一下，我的环境如果解析一个不存在的域名，最初发出和最终返回大概花费1.6秒（大概3个DNS请求；第二次测差不多），比我想象的低了不少，看来是我太苛刻了，但的确能够体感到。
其中第一个到114的请求花费0.4秒，不知道具体花在了哪里，匹配和检查吗。直接请求114（ping约23ms），花费时间0.0824秒，基本无法体感到。~~

更正：我的测试有误，的确花在了网络IO上，1.6秒分别在四个请求（各0.4s左右），A与AAAA及nslookup的一次重试。那次0.08s大概是我没换随机域名结果114有缓存了。
看来的确没什么优化余地了。就这样吧，感谢耐心的回复和解释……

**Comment by chengr28** [comment]
正则是直接做成了接口的……因为当初刚开始项目的时候就说要支持正则表达式这样，也算是 Feature 了，再换回字符串匹配之类的又丧失掉了原本的优势 =_/=
至于内存占用和请求的数量有关，UDP 的话一个包应该是和局域网 MTU 一样是 1500 字节的，本地一发一收多功能多线程一发一收，这样一个请求可能就是几个十多KB了……

**Comment by yfdyh000** [comment]
接口也有道理，那就这样吧。只是如果未来会支持路由器等设备上运行，正则也许会太慢而不得不改掉。
其实几十KB内存占用和相应CPU资源可以忽略不计吧。但如果增加复杂度或很费时间就算了，目前的确不是强需求。

**Comment by chengr28** [comment]
之前就有人好像帮我测试过在 OpenWRT 上运行，说是要占用1MB的空间……晕，所以最近都很注重资源的占用，毕竟还是 C/C++ 的程序，写出来和 Python 之类的差不多就没有意义了，不过想想还是本身做过滤考虑的太多，就是可靠性……最近流行的 ChinaDNS 就是设计得很简单，但是说实话个人觉得那个可靠性不是很好，之前 2015 年头那次随机污染域名了他们那个就中枪了 =_/=

本项目应该没有移植的打算了……之前有想过 OpenWRT 和 Android 之类，都是因为资源占用和系统 API 之类的撞上了……
