### ISSUE TITLE
homebrew安装中配置文件所在目录的问题

### ISSUE THREAD

**Issue by pzgz** [chengr28/Pcap_DNSProxy#190]
在使用homebrew安装的时候(HEAD版本），从formular中可以看出来，配置文件是安装在`/usr/local/etc/pcap_DNSproxy`下，但是在plist文件和其它的一些命令中，配置文件对应的应该是`/usr/local/etc/pcap_dnsproxy`。

如果系统文件是大小写不敏感，那没问题，但是如果文件系统是大小写敏感的话，就会出现服务无法启动的情况。

建议更改homebrew的公式，把配置文件的目录更改为`/usr/local/etc/pcap_dnsproxy`

**Comment by wongsyrone** [comment]
Mac部分好像是由 @blackgear 维护的

**Comment by blackgear** [comment]
New formular has been submitted to homebrew core.
