### ISSUE TITLE
无法解析本机或局域网内主机名的IP

### ISSUE THREAD

**Issue by smounives** [chengr28/Pcap_DNSProxy#191]
### 版本号及运行环境

Pcap_DNSProxy 0.4.7.4
Windows 10 64-bit Build 1607
### 问题重现步骤

nslookup 本机名或局域网内某个主机名，无法解析，虽然可以手动添加hosts，但是如果网络环境变化了，就得重写hosts，很麻烦
### 期望和实际的程序行为

能正常解析出来
### 与默认配置不同的部分

无
### 程序错误日志

无

**Comment by chengr28** [comment]
这个并不是本程序的问题，程序只负责对外的 DNS 解析服务，不负责本地链路的名称解析：
* 实际上本地链路的名称解析服务由 NBNS/NetBIOS Name Service 和 LLMNR/Link-Local Multicast Name Resolution 协议共同负责的，这两个协议内置在系统的协议栈内且使用时优先级高于远程 DNS 服务，仅当它们无法解析名称时才会将请求转发至远程 DNS 服务器
* 如果此功能工作不正常，请确认机器都在同一个本地链路内，路由器会转发多播包，同时本机协议栈需要启用 `启用网络发现` 以及 `启用网络连接设备的自动设置`

**Comment by smounives** [comment]
感谢答疑

**Comment by smounives** [comment]
不好意思重新打开一次，之前一直没试你说的 `启用网络发现` 以及 `启用网络连接设备的自动设置` ，现在我设置好了，依然无法解析到内网的机器
![image](https://cloud.githubusercontent.com/assets/9267814/20141055/92e53b62-a6c9-11e6-8cb5-06e6fc9409d3.png)

![image](https://cloud.githubusercontent.com/assets/9267814/20141076/a0793f6c-a6c9-11e6-8ea2-fa81cdb181b5.png)

与默认配置不同的地方：
```
IPv4 Local DNS Address = 172.19.0.2:53
IPv4 Local Alternate DNS Address = 172.16.0.2:53
DNSCurve = 1
```
Client OS:Windows 10 64-bit
DNS 服务器，DHCP服务器都是这台DC01域控服务器，都在同一网段。

**Comment by wongsyrone** [comment]
这个也不是一个合法的域名啊

**Comment by smounives** [comment]
机器名，带DNS后缀的，我也不是很懂，用内网这个DNS就能解析出
![image](https://cloud.githubusercontent.com/assets/9267814/20141344/e5d0ef46-a6ca-11e6-9d52-4909ed46a2dd.png)
![image](https://cloud.githubusercontent.com/assets/9267814/20141355/f5682460-a6ca-11e6-860b-9be183ad5529.png)

**Comment by chengr28** [comment]
好吧第一次提出这个问题的时候提供的信息不足，还以为是内网的 NBNS/LLMNR 工作不正常，但是如果本身有一台 WINS 服务器的话，这就相当于把这台 WINS 服务器当成上游 DNS 服务器了，和是不是内网已经没关系了……
因为这个服务器是填入 Local DNS 里的，如果没有修改配置文件其它地方，那么默认应该是使用境内路由表匹配模式，显然 `172.16.0.0/20` 没有在其中所以导致程序不接受 WINS 服务器的结果，把这句加到 `[Local Routing]` 并重启服务应该能解决问题

**Comment by smounives** [comment]
依然不行，奇怪了……解析结果和上图一样

**Comment by chengr28** [comment]
呃写错了……`172.16.0.0 - 172.31.255.255` 这段地址是 `172.16.0.0/12` 才对

**Comment by smounives** [comment]
生效了！多谢w
