### ISSUE TITLE
无法在arm下编译

### ISSUE THREAD

**Issue by wwng2333** [chengr28/Pcap_DNSProxy#192]
﻿### 版本号及运行环境
Linux orangepi 3.4.39 #41 SMP PREEMPT Sun Jun 21 13:09:26 HKT 2015 armv7l armv7l armv7l GNU/Linux
Ubuntu 16.04.1 LTS \n \l
### 问题重现步骤
无法编译，一切依赖均已安装

### 期望和实际的程序行为
希望能在ARM平台下使用

### 程序错误日志
-- Build files have been written to: /root/Pcap_DNSProxy-master/Source/Object
Scanning dependencies of target Pcap_DNSProxy
[  5%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o
[ 11%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
[ 22%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o
[ 22%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurve.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/Pcap_DNSProxy.dir/build.make:134: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/DNSCurve.cpp.o' failed
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/DNSCurve.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wongsyrone** [comment]
Not enough ram, make sure to run the command "free -m" and check your ram

**Comment by wwng2333** [comment]
free ram = 700m,not enough?

**Comment by wwng2333** [comment]
重启之后可以编译了，谢谢。

**Comment by wwng2333** [comment]
使用单线程并增加swap后成功编译
