### ISSUE TITLE
情况越来越严重了。

### ISSUE THREAD

**Issue by zasl** [chengr28/Pcap_DNSProxy#193]
﻿### 版本号及运行环境
WNDER4300路由器刷trunk openwrt
pcap为最新编译版本4.74

### 问题重现步骤
启动程序正常情况下啊可以放污染，但是日志里就是这样的error

Sat Sep 24 23:39:30 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:30 -> Network Error: Socket connecting error, error code is 13.
Sat Sep 24 23:39:30 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:30 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Sat Sep 24 23:39:31 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:31 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Sat Sep 24 23:39:32 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:32 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Sat Sep 24 23:39:35 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:35 -> DNSCurve Error: IPv4 Alternate Server TCP get signature data error.
Sat Sep 24 23:39:35 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:35 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Sat Sep 24 23:39:35 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:35 -> Network Error: Socket connecting error, error code is 13.
Sat Sep 24 23:39:35 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:35 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Sat Sep 24 23:39:35 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:35 -> Network Error: Socket connecting error, error code is 13.
Sat Sep 24 23:39:35 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:35 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Sat Sep 24 23:39:36 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:36 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Sat Sep 24 23:39:38 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:38 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Sat Sep 24 23:39:40 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:40 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Sat Sep 24 23:39:40 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:40 -> Network Error: Socket connecting error, error code is 13.
Sat Sep 24 23:39:40 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:40 -> Network Error: Socket connecting error, error code is 13.
Sat Sep 24 23:39:40 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:40 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Sat Sep 24 23:39:40 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:40 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Sat Sep 24 23:39:40 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:40 -> DNSCurve Error: IPv4 Alternate Server TCP get signature data error.
Sat Sep 24 23:39:41 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:41 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Sat Sep 24 23:39:43 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:43 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Sat Sep 24 23:39:45 2016 user.info mwan3track: Lost 8 ping(s) on interface wan (pppoe-wan)
Sat Sep 24 23:39:45 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:45 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Sat Sep 24 23:39:45 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:45 -> Network Error: Socket connecting error, error code is 13.
Sat Sep 24 23:39:45 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:45 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Sat Sep 24 23:39:45 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:45 -> Network Error: Socket connecting error, error code is 13.
Sat Sep 24 23:39:45 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:45 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Sat Sep 24 23:39:46 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:46 -> DNSCurve Error: IPv4 Alternate Server TCP get signature data error.
Sat Sep 24 23:39:46 2016 daemon.err Pcap_DNSProxy[7354]: 2016-09-24 23:39:46 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.

以下是崩溃日志，不定时崩溃，没有大流量操作，只是简单的流量网页就会崩溃，然后是崩溃后的日志。
有脚本监控pcap，没1分钟监控一次。现在情况是脚本自动重启pcap后大概3分钟内，pcap在top监控里面可以看到运行，但是无法解析任何域名，就和断网一样

Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:11 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:12 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:12 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:12 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:12 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:12 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:12 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:12 2016 daemon.err Pcap_DNSProxy[5277]: 2016-09-24 23:37:12 -> DNSCurve Error: IPv4 Main Server UDP get signature data error.
Sat Sep 24 23:37:12 2016 daemon.err Pcap_DNSProxy[5277]: 2016-09-24 23:37:12 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Sat Sep 24 23:37:13 2016 daemon.err Pcap_DNSProxy[5277]: 2016-09-24 23:37:13 -> Network Error: Socket connecting error, error code is 13.
Sat Sep 24 23:37:13 2016 daemon.err Pcap_DNSProxy[5277]: 2016-09-24 23:37:13 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Sat Sep 24 23:37:13 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:13 2016 kern.err /usr/bin/ss-tunnel[13222]: [udp] server_recv_sendto: Network unreachable
Sat Sep 24 23:37:13 2016 daemon.err Pcap_DNSProxy[5277]: 2016-09-24 23:37:13 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Sat Sep 24 23:37:13 2016 daemon.err Pcap_DNSProxy[5277]: 2016-09-24 23:37:13 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Sat Sep 24 23:37:13 2016 daemon.err Pcap_DNSProxy[5277]: 2016-09-24 23:37:13 -> Network Error: Socket connecting error, error code is 13.
Sat Sep 24 23:37:13 2016 daemon.err Pcap_DNSProxy[5277]: 2016-09-24 23:37:13 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.

### 与默认配置不同的部分
完整的配置内容
其他文件都是默认的

[Base]
Version = 0.4
File Refresh Time = 15
Additional Path = 
Hosts File Name = Hosts.ini|Hosts.conf|Hosts|Hosts.txt|Hosts.csv|WhiteList.txt|White_List.txt
IPFilter File Name = IPFilter.ini|IPFilter.conf|IPFilter.dat|IPFilter.csv|IPFilter|Guarding.p2p|Guarding|Routing.txt|chnrouting.txt|chnroute.txt

[Log]
Print Log Level = 3
Log Maximum Size = 50KB

[Listen]
Pcap Capture = 1
Pcap Devices Blacklist = AnyConnect|Host|Hyper|ISATAP|IKE|L2TP|Only|Oracle|PPTP|Pseudo|Teredo|Tunnel|Virtual|VMNet|VMware|VPN|any|lo
Pcap Reading Timeout = 250
Listen Protocol = IPv4 + IPv6 + TCP + UDP
Listen Port = 1053
Operation Mode = Server
IPFilter Type = Deny
IPFilter Level < 0
Accept Type = 

[DNS]
Protocol = IPv4 + IPV6 + TCP
Direct Request = IPv4 + IPv6
Cache Type = Queue
Cache Parameter = 128
Default TTL = 900

[Local DNS]
Local Protocol = IPv4 + UDP
Local Force Request = 0
Local Hosts = 0
Local Main = 1
Local Routing = 1

[Addresses]
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 
IPv4 DNS Address = 127.0.0.1:5300|208.67.222.222:5353|208.67.220.220:443
IPv4 Alternate DNS Address = 8.8.4.4:53|8.8.8.8:53
IPv4 Local DNS Address = 202.100.96.68:53
IPv4 Local Alternate DNS Address = 114.114.115.115:53
IPv6 Listen Address = 
IPv6 EDNS Client Subnet Address = 
IPv6 DNS Address = [2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = [2001:4860:4860::8888]:53|[2620:0:CCD::2]:443|[2620:0:CCC::2]:5353
IPv6 Local DNS Address = 
IPv6 Local Alternate DNS Address = 

[Values]
Thread Pool Base Number = 0
Thread Pool Maximum Number = 128
Thread Pool Reset Time = 60
Queue Limits Reset Time = 0
EDNS Payload Size = 1220
IPv4 Packet TTL = 32 - 255
IPv6 Packet Hop Limits = 32 - 255
IPv4 DNS TTL = 0
IPv4 Alternate DNS TTL = 0|0|0
IPv6 DNS Hop Limits = 0
IPv6 Alternate DNS Hop Limits = 0|0|0
Hop Limits Fluctuation = 2
Reliable Socket Timeout = 3000
Unreliable Socket Timeout = 2000
Receive Waiting = 0
ICMP Test = 900
Domain Test = 900
Alternate Times = 10
Alternate Time Range = 60
Alternate Reset Time = 300
Multiple Request Times = 2

[Switches]
TCP Fast Open = 1
Domain Case Conversion = 1
Compression Pointer Mutation = 0
EDNS Label = 1
EDNS Client Subnet Relay = 0
DNSSEC Request = 0
DNSSEC Validation = 0
DNSSEC Force Validation = 0
Alternate Multiple Request = 1
IPv4 Do Not Fragment = 0
IPv4 Data Filter = 0
TCP Data Filter = 1
DNS Data Filter = 1
Blacklist Filter = 1

[Data]
ICMP ID = 
ICMP Sequence = 
ICMP PaddingData = 
Domain Test ID = 
Domain Test Data = 
Localhost Server Name = 

[Proxy]
SOCKS Proxy = 0
SOCKS Version = 5
SOCKS Protocol = IPv4 + TCP
SOCKS Reliable Socket Timeout = 6000
SOCKS Unreliable Socket Timeout = 3000
SOCKS UDP No Handshake = 1
SOCKS Proxy Only = 0
SOCKS IPv4 Address = 127.0.0.1:1080
SOCKS IPv6 Address = [::1]:1080
SOCKS Target Server = 8.8.4.4:53
SOCKS Username = 
SOCKS Password = 
HTTP Proxy = 0
HTTP Protocol = IPv4
HTTP Socket Timeout = 3000
HTTP Proxy Only = 0
HTTP IPv4 Address = 127.0.0.1:1080
HTTP IPv6 Address = [::1]:1080
HTTP Target Server = 8.8.4.4:53
HTTP Version = 1.1
HTTP Header Field = Content-Length: 0
HTTP Header Field = User-Agent: Pcap_DNSProxy/0.4
HTTP Header Field = Accept: */*
HTTP Header Field = Cache-Control: no-cache
HTTP Header Field = Pragma: no-cache
HTTP Proxy Authorization = 

[DNSCurve]
DNSCurve = 1
DNSCurve Protocol = IPv4 + IPV6 + TCP
DNSCurve Payload Size = 512
DNSCurve Reliable Socket Timeout = 3000
DNSCurve Unreliable Socket Timeout = 2000
Encryption = 1
Encryption Only = 0
Client Ephemeral Key = 0
Key Recheck Time = 1800

[DNSCurve Addresses]
DNSCurve IPv4 DNS Address = 208.67.220.220:443
DNSCurve IPv4 Alternate DNS Address = 113.20.8.17:443
DNSCurve IPv6 DNS Address = [2620:0:CCC::2]:443
DNSCurve IPv6 Alternate DNS Address = [2A00:D880:3:1::A6C1:2E89]:443
DNSCurve IPv4 Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv4 Alternate Provider Name = 2.dnscrypt-cert-2.cloudns.com.au
DNSCurve IPv6 Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv6 Alternate Provider Name = 2.dnscrypt-cert.resolver1.dnscrypt.eu

[DNSCurve Keys]
Client Public Key = 
Client Secret Key = 
IPv4 DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
IPv4 Alternate DNS Public Key = 67A4:323E:581F:79B9:BC54:825F:54FE:1025:8B4F:37EB:0D07:0BCE:4010:6195:D94F:E330
IPv6 DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
IPv6 Alternate DNS Public Key = 67C0:0F2C:21C5:5481:45DD:7CB4:6A27:1AF2:EB96:9931:40A3:09B6:2B8D:1653:1185:9C66
IPv4 DNS Fingerprint = 
IPv4 Alternate DNS Fingerprint = 
IPv6 DNS Fingerprint = 
IPv6 Alternate DNS Fingerprint = 

[DNSCurve Magic Number]
IPv4 Receive Magic Number = 
IPv4 Alternate Receive Magic Number = 
IPv6 Receive Magic Number = 
IPv6 Alternate Receive Magic Number = 
IPv4 DNS Magic Number = 
IPv4 Alternate DNS Magic Number = 
IPv6 DNS Magic Number = 
IPv6 Alternate DNS Magic Number =

**Comment by wongsyrone** [comment]
Dnscurve应该是受干扰了

**Comment by jzp820927** [comment]
意思 Dnscurve 被协议识别了/

**Comment by wongsyrone** [comment]
我这里打开dnscurve也有类似的log，那几个服务器全公开的信息，被关照也不奇怪。

**Comment by jzp820927** [comment]
如果只是公开的服务器被关照，倒还感觉没什么。如果是协议层的识别，那就是通杀了。

**Comment by zasl** [comment]
有什么办法找点好的服务器呢？

**Comment by chengr28** [comment]
@jzp820927 DNSCurve 协议本身不是设计用于匿踪或者混淆用途，所以实际上真要屏蔽的话也就是写个规则就能搞掂的事情

**Comment by chengr28** [comment]
DNSCurve 协议应该是没有遭到屏蔽的，不过不能排除部分地区会屏蔽服务器，以这个错误报告的情况来看所有 DNSCurve 协议通讯都不通，建议直接关闭这个功能

**Comment by zasl** [comment]
那请问有什么好的规则设置推荐吗？

**Comment by chengr28** [comment]
默认配置（OpenWrt/LEDE 平台配合那边项目主页修改某些参数）就是官方的推荐配置

**Comment by jzp820927** [comment]
目前感觉最稳定的就是 非标准端口 的 TCP 协议。

**Comment by chengr28** [comment]
@jzp820927 非标准端口无论 TCP 还是 UDP 都很稳定……UDP 并没有 RESET 的设定，不过容易受到 QoS 的影响而已

**Comment by jzp820927** [comment]
可能你那边 UDP 没问题，不过我这边却是受到影响，只能用 非标准端口无论 TCP ，下次遇到了，你截图给你看看就知道了，我是 电信。可能是 ISP 不一样吧。
