### ISSUE TITLE
大量异常的IO读

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [chengr28/Pcap_DNSProxy#195]
﻿### 版本号及运行环境
0.4.7.4 0.4.7.3都有
win 10x64 一周年 专业版  在两台机器上都重现了

wincap使用的是
Win10Pcap-v10.2-5002

环境中有cfosspeed  kis2016  迅雷最新版的极速版

### 问题重现步骤
只要启动即重现
会随着网络流量同步增减
最大时出现过1000+GB/s 当时网络大约100MB/s

### 期望和实际的程序行为
如图

![2016-09-27 14_18_34-process explorer - sysinternals_ www sysinternals com jeremie-win7_administrato](https://cloud.githubusercontent.com/assets/6566869/18862537/55059fac-84bf-11e6-9328-87cca9beafc3.png)

### 与默认配置不同的部分

[Listen]
Operation Mode = Server

[DNS]
Protocol = IPv4 + TCP

[Local DNS]
Local Hosts = 1
Local Main = 0
Local Routing = 0

[Addresses]
IPv4 DNS Address = 203.239.131.1:53
IPv4 Alternate DNS Address = 203.253.31.1:53|208.67.220.220:443|208.67.222.222:5353
IPv4 Local DNS Address = 10.10.240.3:53
IPv4 Local Alternate DNS Address = 10.10.240.2:53

[Proxy]
SOCKS IPv4 Address = 127.0.0.1:25961
SOCKS IPv6 Address = [::1]:25961

[DNSCurve]
DNSCurve = 1

### 程序错误日志
没有

**Comment by chengr28** [comment]
关于 I/O 的问题几个月之前这边进行性能测试的时候已经留意到，不过并不是『异常』的情况。程序的 I/O 来自于几个方面：
* 网络 I/O：占极少数，和网络流量以及并发连接数有关
* 磁盘和基本输出输入 I/O：占极少数，屏幕信息和错误日志的输出
* 抓包模块所产生的 I/O：占绝大部分
  * 由于抓包模块需要从 NIC 抓取数据包，也就是说整体网络流量越多产生的 I/O 字节越多，除非将抓包模块关闭（就是 `Pcap Capture` 参数）否则无法避免
  * 适当增大 `Pcap Reading Timeout` 参数可减少 I/O 的次数，但是总体数据量是不变的
  * 填入更多 `Pcap Devices Blacklist` 参数可更精确过滤不需要抓包的 NIC 降低两种 I/O

**Comment by Lyoko-Jeremie** [comment]
之前也是有IO的，但是比较少所以没有注意到
现在的和网络流量同步，但是大概有20000倍的数量差距，这一点上我感觉是不是一种异常情况了
现在我这里网络流量大概10KB/s上下 dnsp的io则有200MB/s上下
怎样的算法大概都不会在抓包上产生被抓流量2万倍的数据，所以我觉得这是一种异常了

另外，貌似在某些时刻会导致其他程序的IO被延迟，比如我使用foobar2000+asio做音频输出
和以前相比现在要把asio4all的缓冲区调到以前的4倍才不会出现音频跳断的问题
不知是不是win10的锅

**Comment by Lyoko-Jeremie** [comment]
![2016-09-27 15_25_46-jeremie-ic -](https://cloud.githubusercontent.com/assets/6566869/18864009/beb64d32-84c6-11e6-8334-050983dd1bad.png)
这张图环境和上面一样
下面产生网络流的是迅雷的后台服务
上面产生io流的是dnsp

这是哪里产生的放大效应么

**Comment by Lyoko-Jeremie** [comment]
关掉抓包模块之后确实没有了

restart服务后log如下
```
[2016-09-27 15:31:28] -> [Notice] Pcap_DNSProxy started.
[2016-09-27 15:31:28] -> [Notice] TCP Data Filter require Pcap Cpature.
```

**Comment by wongsyrone** [comment]
不过关掉了抓包模块感觉自损八百。

**Comment by Lyoko-Jeremie** [comment]
@wongsyrone 是啊。所以现在这个问题很困扰

**Comment by chengr28** [comment]
`TCP Data Filter` 这个是过滤模块用的参数，不过既然抓包功能已经关掉了那么这个功能也就没用了，这里是在提醒想启用 `TCP Data Filter` 必须先启用 `Pcap Cpature`

**Comment by chengr28** [comment]
看了下……这边产生的 I/O 字节只是 NIC 记录的流量总和的 1/10
建议换成 WinPcap 试试会不会有下降

**Comment by Lyoko-Jeremie** [comment]
@chengr28 
WinPcap 有对win10兼容性好的版本么

**Comment by chengr28** [comment]
@Lyoko-Jeremie 这边也是 Win10 最新正式版本，WinPcap 一路过来都没发现有什么问题
Win10Pcap/Npcap 和 WinPcap 的区别就是前者用了 NDIS 6.x 的驱动模型，比后者的 5.x 更先进，用起来区别不大
