### ISSUE TITLE
希望支持google https dns作为上游并加入edns client开关

### ISSUE THREAD

**Issue by Smallthing** [chengr28/Pcap_DNSProxy#197]
﻿### 版本号及运行环境

**Comment by chengr28** [comment]
EDNS Subnet Client 功能一直都有，至于 Google HTTPS DNS 的问题之前在三四个 Issue 都有解释过暂时不添加的原因 https://github.com/chengr28/Pcap_DNSProxy/issues/172 建议发之前先翻翻 Issue 列表

**Comment by jzp820927** [comment]
挺奇怪，为什么这么多人都想添加 dns-over-https，看来大家对 google 的 DNS 都挺钟情的，我想了哈，如果用 dns-over-https 配合缓存的话，效率应该也不会太差。

**Comment by chengr28** [comment]
其实这货用途官方就有说……第一点是说传统 DNS 没有加密，但其实他们只是不想支持 OpenDNS 的 DNSCrypt 协议而已，成熟的实现一直都有；第二点是说一些基于 Web 的程序（大概指的是 HTML5）可能对 DNS 有更高级的应用，个人是觉得 Google DNS over HTTPS 的推出更像是给后者做支持的

**Comment by jzp820927** [comment]
应该是吧，不过目前非标准端口能稳定使用，感觉也够了，真到了非标准端口也 over 的时候，再考虑 https 也不迟。

**Comment by Smallthing** [comment]
可能我的描述不是很清楚。
是这样的：
1.如果某个地方对境外dns的封锁很严，墙外机器都是必须的，和https还是dnscrypt或是53dns协议都没关系。对吧。
2.我在厦门杭州的实测，OPENDNS常常不能良好的靠edns解出正确的本地区IP。而GOOGLE这个我做了不少测试是可以的。
我想要的其实是支持google的https协议，不是只支持google的域名，我可以通过反向代理/一些daemon程序（比如go写的,python写的,nodejs写的）从境外VPS解出被劫持域名的相对比较准确的本地的dns结果。
自己添加这段代码好了：）

**Comment by Smallthing** [comment]
@jzp820927 其实只是因为他的edns在我这边看来相对比较精确而已。

**Comment by jzp820927** [comment]
@Smallthing 你的意思，你已经添加了 google https dns 相关功能的代码？求分享。。。

**Comment by chengr28** [comment]
统一到 https://github.com/chengr28/Pcap_DNSProxy/issues/172 讨论
