### ISSUE TITLE
Release 分支不见了

### ISSUE THREAD

**Issue by yfdyh000** [chengr28/Pcap_DNSProxy#199]
只发布在 https://github.com/chengr28/Pcap_DNSProxy/releases 了吗。

**Comment by chengr28** [comment]
对的，因为本身在 git 里放编译好的二进制可执行文件其实不好，GitHub 这边的标准做法就是把它们发到 releases 里才是正确的做法，这次更新之后 releases 那边也会加快同步更新

**Comment by yfdyh000** [comment]
嗯，确实不好。不知道 Git LFS 怎么样。

**Comment by wongsyrone** [comment]
Git LFS 上传的话我这里比较慢，不如直接用release，放到S3上面
