### ISSUE TITLE
在使用中碰到个问题想问一下

### ISSUE THREAD

**Issue by sunlei213** [chengr28/Pcap_DNSProxy#20]
在使用中发现个问题，就是用了时间久了，程序的udp连接数会升的很高，我家里的电脑一天没有关机，第二天早晨看到程序的udp连接到了15000多。昨天下了最新的使用，晚上开始一两个小时连接数还不高，大概100-200左右，晚上开着下东西，早晨起来看已经升到1700多了。为什么会有那么多连接没释放

**Comment by xinhugo** [comment]
我也有同样的疑问。

**Comment by chengr28** [comment]
你好，请问你们是使用什么软件看到程序的 UDP 连接很多的？

**Comment by xinhugo** [comment]
NetLimiter 3。

**Comment by sunlei213** [comment]
我开始是看360的网络监控，后来怕误报用windows自带的netstat看的也一样

**Comment by xinhugo** [comment]
@sunlei213 把结果粘贴来看看，我这里 netstat 没能重现你说的。

**Comment by sunlei213** [comment]
我用netstat -a -b -p UDP看的,记录太多，有几千行。没法贴上来

**Comment by chengr28** [comment]
这样吧……先试试我刚才上传的版本，修改了几个比较可疑的地方再测试看看。因为我这边用 TCP View 和 netstat 都没出现这种情况，所以还需要看看

其实也不用全部发上来的……节选一些或者重点区域截个图就行ww

**Comment by sunlei213** [comment]
其实netstat显示出来也没什么具体内容，就是这样一组显示，表示这个连接是下面那个程序占用，但这样的数据有上千组，只是端口不一样
 UDP    0.0.0.0:49258          *:*                    
 [Pcap_DNSProxy.exe]

**Comment by chengr28** [comment]
![Netstat UDP](https://lh6.googleusercontent.com/-y4XbcAAbPW0/VQlCrRsR4II/AAAAAAACNzw/jGYVPxxHF4o/w0/2015-03-18-Listen-Pcap.png)

最新版本也是这样？那还真是奇怪啊，这几天一直开着没关，看着都只有 `0.0.0.0:53` 的
而且最重要的是类似这种 `0.0.0.0:端口` 是本地监听用的接口，实际上如果没有在配置文件指定多个监听地址或者多个监听端口一般的机器都只会开4个的。所以也不太清楚是什么回事……

**Comment by chengr28** [comment]
至于 NetLimiter 显示很多连接，实际测过……似乎是 NetLimiter 本身的问题
程序的话会在超时时间（几秒）后自动关闭网络请求的套接字，从 TCP View 里也能看出来，只是 NetLimiter 对于 UDP 的显示似乎是定时清除的，也就是说过一个固定长度的时间才会从列表上清除（实测大约几分钟）这样就导致了很多套接字实际上已经关闭但却还在列表中显示的问题 =_/=

**Comment by sunlei213** [comment]
用了最新的程序正常了，谢谢
