### ISSUE TITLE
How do I make PcapDNSProxy use Timer and Queue for cache at the same time?

### ISSUE THREAD

**Issue by Incubator85653** [chengr28/Pcap_DNSProxy#200]
0.4.6.3
Windows 10 14393 x86

```
[DNS]
Cache Type = Timer
```

If Timer and Queue at the same time,

What exactly the correct string should I write in?

My config:
Cache Type = **Timer + Queue**
Cache Parameter = **0**

And after the service running, any domains cannot be resolved.

**Comment by wongsyrone** [comment]
Try latest version: 0.4.7.6

**Comment by chengr28** [comment]
About cache types in ReadMe:

    混合类型：超过指定时间时、超过队列长度时以及超过域名本身 TTL 时，都会删除最旧的 DNS 缓存

`Cache Type = Timer + Queue` is correct(After version 0.4.7.6). In this case, timeout is depend on `Default TTL` parameter and queue length is depend on `Cache Parameter` parameter. So `Cache Parameter = 0` means "queue length is zero" or shutdown whole cache system.

**Comment by Incubator85653** [comment]
@chengr28 Solved, thanks.
