### ISSUE TITLE
Parameter Error: Data format error in line 60 

### ISSUE THREAD

**Issue by dNEryno** [chengr28/Pcap_DNSProxy#202]
﻿### 版本号及运行环境
0.4.77 openwrt
### 问题重现步骤
Parameter Error: Data format error in line 60 of /etc/pcap-dnsproxy/Config.conf.

这行是IPv4 DNS TTL = 0
### 程序错误日志

2016-10-24 19:00:29 -> Parameter Error: Data format error in line 60 of /etc/pcap-dnsproxy/Config.conf.

**Comment by chengr28** [comment]
请务必填写 `与默认配置不同的部分` 的内容，因为这个错误推测是修改了 DNS 服务器地址的缘故，因为 TTL/Hop Limits 那里的数量是需要和 DNS 服务器地址数量相对应的。也就是说，如果 Main + Alternate 的 Address 不等于Main + Alternate 的 TTL/Hop Limits 会报错，例子可参考默认的配置文件

**Comment by dNEryno** [comment]
哦...确实更改了DNS..国外的..那我先改回国内的试试.

**Comment by chengr28** [comment]
并不是……这个参数是要求填境外 DNS 服务器的，报错的原因大概是 TTL 的数量和填入 DNS 服务器的数量不一致，建议可以清空两个 TTL 参数，这样并不会影响功能的实现

**Comment by dNEryno** [comment]
说错,我意思我改回默认数量.我改了国外的DNS,然后还多加了一个..

另外
ipconfig /flushdns
nslookup download.bullguard.com

我做了个bat,用它来测是否可以过滤污染.
通常第一次都是超时失败,得第二次测试才能出来正确结果是为啥呢.

**Comment by dNEryno** [comment]
Default TTL = 900
IPv4 Packet TTL = 32 - 255
IPv4 DNS TTL = 0
IPv4 Alternate DNS TTL = 0|0|0

就这四个带TTL的,删掉哪几个呢.

**Comment by dNEryno** [comment]
另外忘了说我是openwrt上运行的...为的是所有设备的DNS都不会被污染.

**Comment by chengr28** [comment]
`nslookup` 只有2秒的等待响应时间，程序本身走的流程比较长，获得正确解析结果的时间也比较长，所以经常会有超时的现象，第二次查询是因为有缓存了所以可以正常解析。系统的协议栈请求解析的超时时间比较长，不会出现这种情况

**Comment by chengr28** [comment]
`DNS TTL/Hop Limits` 和 `Alternate DNS TTL/Hop Limits` 的都可以删掉，反正指定是 0 相当于自动获取，不填也是自动获取的意思

**Comment by dNEryno** [comment]
那么有什么办法缩短点儿获取结果的时间吗?

**Comment by wongsyrone** [comment]
dnsmasq-> pdnsd-> pcap-dnsproxy
第一次会慢一点，以后就快了，加个永久缓存

**Comment by dNEryno** [comment]
我就是按楼上发的教程弄的...
no-resolv
no-poll
domain-needed
no-negcache
server=127.0.0.1#1053
all-servers
cache-size=10000
conf-dir=/etc/dnsmasq.d

这样子搞的..配合SS,然后chroute列表FQ...速度经常惨不忍睹..偶尔也会快一些..不晓得是不是中间解析慢了,U2B没加载完全?

**Comment by wongsyrone** [comment]
那样只是用了dnsmasq的缓存，那个缓存时间短，条数少。

**Comment by dNEryno** [comment]
嗯好的.安装了pdnsd.正在琢磨配置下...

**Comment by jzp820927** [comment]
pcap-dnsproxy 自带缓存配置，用不着装这么多软件了吧
