### ISSUE TITLE
Cant build under arm

### ISSUE THREAD

**Issue by wwng2333** [chengr28/Pcap_DNSProxy#205]
﻿### 版本号及运行环境
Linux OrangePI 3.4.39 #1 SMP PREEMPT Mon Oct 12 12:02:29 CEST 2015 armv7l armv7l armv7l GNU/Linux
gcc version 4.9.2 (Ubuntu/Linaro 4.9.2-10ubuntu13) 
### 问题重现步骤
./CMake_Build.sh --enable-static
### 程序错误日志
Linking CXX executable Pcap_DNSProxy
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x8): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: cannot find -lz
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libpcap.a(nametoaddr.o): In function `pcap_nametoaddrinfo':
(.text+0x4c): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libpcap.a(nametoaddr.o): In function `pcap_nametoaddr':
(.text+0x2): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libpcap.a(nametoaddr.o): In function `pcap_nametonetaddr':
(.text+0x6a): warning: Using 'getnetbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libpcap.a(nametoaddr.o): In function `pcap_nametoproto':
(.text+0x1be): warning: Using 'getprotobyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libpcap.a(nametoaddr.o): In function `pcap_nametoport':
(.text+0x84): warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
CMakeFiles/Pcap_DNSProxy.dir/build.make:560: recipe for target 'Pcap_DNSProxy' failed
make[2]: *** [Pcap_DNSProxy] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
mv: cannot stat ‘Object/Pcap_DNSProxy’: No such file or directory
root@OrangePI:~/Pcap_DNSProxy/Source/Scripts#

**Comment by jzp820927** [comment]
橙子派。

**Comment by chengr28** [comment]
`/usr/bin/ld: cannot find -lz`
请检查 zlib 库是否正确安装和部署

**Comment by wwng2333** [comment]
after apt install zlib1g-dev , it works.
(bu shi wo yao zhuang bi , shi mei shu ru fa.)

**Comment by wwng2333** [comment]
root@OrangePI:~/Pcap_DNSProxy/Source/Release# dig @127.0.0.1 google.com

; <<>> DiG 9.9.5-9ubuntu0.5-Ubuntu <<>> @127.0.0.1 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31672
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;gOoGlE.CoM.			IN	A

;; ANSWER SECTION:
gOoGlE.CoM.		300	IN	A	216.58.197.14

;; Query time: 528 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Nov 12 22:15:36 CST 2016
;; MSG SIZE  rcvd: 55
