### ISSUE TITLE
openwrt ar71xx（路由是wndr4300）运行pcap问题

### ISSUE THREAD

**Issue by Chandler-Lu** [chengr28/Pcap_DNSProxy#208]
﻿### 版本号及运行环境
OpenWrt Chaos Calmer 15.05.1 / LuCI (git-16.018.33482-3201903)
pcap-dnsproxy_0.4.7.8-2_ar71xx.ipk

### 问题重现步骤
root@CRouter:~# /etc/init.d/pcap-dnsproxy start
Removing previous Error.log
Hooray! Error.log not found
Pcap_DNSProxy failed to start

### 期望和实际的程序行为
应当正常启动，已经检查端口占用等问题，应该是正常的。

### 与默认配置不同的部分
/etc/config/pcap-dnsproxy文件：

config pcap-dnsproxy
	option enabled '1'

### 程序错误日志
root@CRouter:~# /etc/init.d/pcap-dnsproxy start
Removing previous Error.log
Hooray! Error.log not found
Pcap_DNSProxy failed to start

**Comment by wongsyrone** [comment]
/etc/init.d/pcap-dnsproxy libver输出什么？

另外可尝试https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/issues/27

**Comment by wongsyrone** [comment]
另外看/etc/pcap-dnsproxy目录下是否有Error.log文件存在，如果有贴出内容

**Comment by cpexplorer** [comment]
这位同学是我推荐到这边来反馈的，用的是我编译给他的libpcap1.8.1和pcap-dnsproxy 0.4.7.8-2，openwrt ar71xx版本

**Comment by Chandler-Lu** [comment]
root@CRouter:~# /etc/init.d/pcap-dnsproxy libver
/usr/sbin/Pcap_DNSProxy: can't load library 'libsodium.so.18'
然后libsodium的版本是1.0.2-1

**Comment by wongsyrone** [comment]
这版本太低了，需要安装编译时候链接的那个版本

**Comment by wongsyrone** [comment]
@cpexplorer 如果你给他编译的话，需要把软件包和对应依赖的包都给他才行，先保证 libver 的检查能顺利通过。

**Comment by cpexplorer** [comment]
看来有可能是libsodium跟我编译的不匹配的问题，晓得了，晚上发给他试试

**Comment by wongsyrone** [comment]
另外直接 `dig @127.0.0.1 -p 1053 www.google.com` 有回应吗

**Comment by Chandler-Lu** [comment]
问题已经解决啦，换了cpexplorer编译给我的libsodium就搞定了~感谢楼上两位~

**Comment by wongsyrone** [comment]
好，那就先关掉了。

**Comment by roc1010kmt** [comment]
怎麼編譯沒看太明白，請問能否編譯一個ar71xx路由器用的？
