### ISSUE TITLE
将socks ipv4 address指向ss-local会不会对抗污染有加成？

### ISSUE THREAD

**Issue by cpexplorer** [chengr28/Pcap_DNSProxy#209]
﻿### 版本号及运行环境

version :0.4.8.0
firmware :lede pandorabox and openwrt

### 问题重现步骤

[Proxy]
SOCKS Proxy = 0
SOCKS Version = 5
SOCKS Protocol = IPv4 + TCP
SOCKS UDP No Handshake = 1
SOCKS Proxy Only = 0
SOCKS IPv4 Address = 127.0.0.1:1080

请问如果把此处socks proxy打开并将socks ipv4 address指向ss-local会不会对抗污染效果有加成作用？不考虑因此导致的资源占用

**Comment by chengr28** [comment]
这个功能的意思是，将 DNS 的流量使用 SOCKS 协议包装后发往指定的服务器
优先级高于普通请求，也就是说在普通请求进行之前先给 DNS 请求挂了个代理
那肯定是可以 100% 免除投毒污染的，而且还可以加密流量

**Comment by chengr28** [comment]
补充一点，将 `SOCKS Proxy Only` 开启还强制指定只使用 SOCKS 代理进行传输
顺便你看 `SOCKS IPv4 Address` 默认配置填那个地址就知道这个功能实际上就是为 SS 设计的

**Comment by cpexplorer** [comment]
好的，谢谢解答，我也是这么猜的～～～

**Comment by cpexplorer** [comment]
哦，顺便问下，开启socks proxy 并指向ss-local后，output protocol那边应该设置什么值？

**Comment by chengr28** [comment]
`Output Protocol` 控制的是普通请求的协议，SOCKS 协议的请求由 SOCKS 的参数指定，所以不用管就行

**Comment by cpexplorer** [comment]
多谢大神耐心解答，豁然开朗~

**Comment by jzp820927** [comment]
前置代理，类似于全局代理，会对 CDN 造成影响。

**Comment by chengr28** [comment]
肯定的，如果不想有影响可能需要双方都启用 EDNS Client Subnet 功能

**Comment by jzp820927** [comment]
我觉得还是 pcap 目前默认的模式比较好，既能防止污染，又可以适应 CDN

**Comment by cpexplorer** [comment]
配合的是gfwlist模式使用的，只有匹配gfwlist的才会向pcap-dnsproxy查询，所以应该没影响到cdn吧？

**Comment by jzp820927** [comment]
只要不是全局性的代理查询，都没影响。

**Comment by cpexplorer** [comment]
我再问一下，开启socks proxy only和不开启的区别在哪？是不是指不开启的话是优先使用socks协议，如果失败再使用其他协议；而开启了的话就只使用socks协议。这个功能是不是考虑到一些socks服务器不稳定的情况，而对于使用本地ss-local的话，就没必要开启socks proxy only了？

**Comment by jzp820927** [comment]
我觉得差不多是这个意思吧，从字面意思看，就是 仅使用代理查询，不开的话，应该就是同时兼容普通查询模式

**Comment by chengr28** [comment]
差不多是这个意思，这个功能一般是为了避免可能因尝试其它解析方式造成的混乱，因为只要符合规则的解析结果都会被接受而不管是用什么方法获取到的，有些情况下可能需要强制使用 SOCKS Proxy 这样
你看很多请求方式都有 Only 选项的，都是这个意思，默认这个都是不启用的

**Comment by jorismq** [comment]
你好，你最终成功了吗？我一直不成功。设置后还是登不上google。而我的server也确认是工作的。
win10 pro x64

我有一个代理服务器，1.1.1.1:1080。其他软件开启socks5代理，输入上面地址后，这个软件可以顺利连网使用
我想使Pcap_DNSProxy也用这个代理
Direct Request = IPv4 + IPv6
SOCKS Proxy = 1
SOCKS Version = 5
SOCKS Protocol = IPv6 + IPv4 + TCP + UDP
SOCKS UDP No Handshake = 0
SOCKS Proxy Only = 0
SOCKS IPv4 Address = 127.0.0.1:1080
SOCKS IPv6 Address = [::1]:1080
SOCKS Target Server = 1.1.1.1:1080
SOCKS Username =
SOCKS Password =

但是nslookup www.google.com
就会出现DNS time out
什么也解析不了。
