### ISSUE TITLE
对域名不存在（Non-existent domain）的处理策略

### ISSUE THREAD

**Issue by yfdyh000** [chengr28/Pcap_DNSProxy#21]
* 在Hosts模式开启时，解析不存在的cn域名（例如www123.g.cn）
  * 软件得到境内返回不存在错误后还会再请求主境外服务器（而且并不使用DNSCurve服务器），两者都不存在才会返回不存在，会造成手动测试时体感上的一点时延，如果能优化掉更好。
* 在解析境外的不存在域名时，软件同样会在得到不存在错误后请求境外，但这次加上了DNSCurve，等于本地+4*8+DNSCurve。
* 而且似乎非并行，所以似乎总延迟更高。

只是有点疑惑这是否是预期行为，如否应考虑能否优化最终性能。
可靠性固然重要，但解析一次可能花几秒感觉也不那么舒服嗯……

**Comment by chengr28** [comment]
流程：收到解析请求→Hosts 检查→Local 请求→DNSCurve→TCP 请求（如果有）→普通 UDP 请求

* 关于 NX 错误：
    * 如果 Local 服务器返回 NX 错误程序是当请求失败来处理的，因为以前的确是完全信任的，直到有次遇到有些域名大概是碰到投毒污染了（没错就是 CN 域名）而 Local 服务器出错直接返回了 NX 错误但此时境外服务器却又都是正常解析的（这个也是神奇）所以出于可靠性的考虑，所有的机制设计都是一旦上面的流程某一步失败就会继续使用下一步进行域名解析，直到最后还是 NX 错误程序才会确信无误返回给用户，用户（系统）方面虽然获得解析结果的时间延长了，但是得到了真实的结果
    * nslookup/ping 等程序默认解析超时时间好像是2秒，但事实上类似 Chrome 之类的浏览器和系统本身在第一次请求域名解析失败时会进行多次重试，程序本身有 DNS 缓存功能，在再次重试的时候就会拿到结果，而且还会留存一段时间。不过说实话这个过程到底还是和 DNS 服务器的响应速度有关。例如现在这边配置 Google Public DNS 和 OpenDNS 一共4个服务器，或者直接用 DNSCurve/DNSCrypt 协议进行解析，在 Local 服务器返回 NX 错误后再去重试都是可以在 nslookup/ping 等程序默认解析超时时间内返回结果的
    * 关于 Local 服务器请求收到 NX 错误后不会请求 DNSCurve……刚才实测发现这边似乎是没问题的，只要开启了 DNSCurve 的选项（当然还要程序成功获取到 DNSCurve 服务器的信息才能成功开始接受解析）都是按照上面的流程来做的
   * 关于手动测试手感的问题，建议不要太纠结 =_/=
* 解析境外不存在域名时也是上面的流程，只是由于没有命中白名单所以跳过了 Local 请求一步，其它都是一样的
* 关于并行的问题，以上流程是不是应该并行进行，在 Issue 20 提过类似的观点，就是资源占用。不论是对网络带宽资源，还是对于服务器的资源，都是这样。至于解析一次域名用的时间是否值得……对于本程序来说拿到正确的解析结果才是重中之重，个人认为如果为此付出几秒问题不大。而且实际上是不是会花费这样多的时间也不一定，起码我在5个不同的 ISP 不同的时间段测过，普遍都是一次超时时间内（指的是上面说的2秒）就能走完整个流程拿到结果

**Comment by yfdyh000** [comment]
* 看到长篇的回复有点吓尿了，现在才敢来仔细读。其实也没那么长，就是Github默认的中文字体好像有点大……提问的主要原因其实就是我用nslookup测试时的手感问题，但才发现其实总是会有点延迟的，哪怕本地的DNS，看来是我太纠结了……
* 并行建议同 #20 的回复，目前我也认为好像没必要了，而且的确浪费了资源和泄露了更多隐私。

关于cn解析没有DNSCurve参与的问题，我的测试仍然是并没有看到请求DNSCurve服务器。

测试配置的参数大致如下：
* Local Hosts = 1
* EDNS0 Label = 1
* DNSCurve = 1
* DNSCurve IPv4 DNS Address = 151.236.20.236:53
* ……

测试时像是 nslookup qrjalfjsfkl.g.cn（不重用），Wireshark监控数据包，可见对IPv4 Local DNS Address和IPv4 DNS Address的各一次A查询，都得到NX，它们会随即再来一遍AAAA，然后nslookup就返回了Non-existent domain错误，未见与DNSCurve服务器通讯。不过，最开始的确与有一次对DNSCurve的TXT记录查询，不清楚是什么，验证吗，Error.log和Running.log中未见有相关错误。
其实也不重要了，境内用本地和IPv4 DNS Address解析也基本足够了。也没准是我的配置问题吧。

**Comment by chengr28** [comment]
DNSCurve/DNSCrypt 这样配置的确是不行……这服务器用加密的参数是这样的：
`DNSCurve IPv4 DNS Address = 151.236.20.236:443`
`DNSCurve IPv4 Provider Name = 2.fvz-rec-hk-nt-01.dnscrypt-cert.meo.ws`
`IPv4 DNS Public Key = AEE3:61A5:D48D:C08A:A333:34F4:9D66:6521:5983:0BA2:6BB1:A818:3558:BAC5:3510:6999`
参见 https://scr.meo.ws/paste/2015-03-08-12-36-15-AZJJzfnW.txt

不过这服务器也不知道是怎么回事，实测不论什么域名都返回 NX 错误的
包括使用加密的，大概是要登录了才能用？不清楚……

**Comment by yfdyh000** [comment]
我有配置，只是嫌太长省略了，但果然弄误会了……我的配置取自[这里](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv)，是：
```DNSCurve IPv4 DNS Address = 151.236.20.236:53```
```DNSCurve IPv4 Provider Name =  	2.fvz-rec-hk-nt-01.dnscrypt-cert.meo.ws```
```IPv4 DNS Public Key = AEE3:61A5:D48D:C08A:A333:34F4:9D66:6521:5983:0BA2:6BB1:A818:3558:BAC5:3510:6999```

突然意识到，难道端口不是53。我记得当时好像是看到上面有几个是53就猜成53了，而且53也是DNS标准端口，再加上用上后也没见过任何报错。现在再仔细看，也有不少是443……
这些为什么会省略呢；本项目能自动补全或提醒这种省略形式吗；能显示工作状态/报错吗……

**Comment by chengr28** [comment]
显示获取错误的话的确是可以显示的，下次更新的时候会加进去……这样如果写错之类获取失败就会报错了。至于地址格式的问题……这个当初是为了支持自定义端口而做的，也是统一的接口，没写端口的话是直接报错的，但是写了总不能说不是默认端口所以报错吧……看来还是给 DNSCurve 那边写个报错比较好

至于这个服务器，昨天也提到实际表现很奇怪，53端口的确是有回应的但全都是 NX 错误，包括要求获取服务器加密指纹的请求，所以实际上53端口不能用加密……

**Comment by yfdyh000** [comment]
嗯，奇怪的是我将它改成443端口后，Wireshark监听看到的是QUIC协议，这里用了QUIC吗……
而且改之后再将主境内和主境外IP改错，nslookup的结果是超时，有与DNSCurve通信，但大概是没成功（看不出）。另外，好像没看到与备用境内和境外服务器通信呢。

**Comment by chengr28** [comment]
把 DNSCurve 识别成 QUIC 是 Wireshark 的问题……或许本来 UDP 的通讯就比较难识别呢，QUIC 本身也没有很明显的特征，和 DNSCurve 的混在一起也不奇怪……

刚才给你发了邮件，附件里的版本：
* 加了错误报告，就是如果获取加密握手信息失败的话会有提醒……之前没有的
* 至于主备用服务器的切换……实测了 DNSCurve 的确是切换不了的，大概是当初写的时候逻辑有问题，这个和上面错误报告获取加密握手信息是同一个模块，这次更新的时候也修复好了

**Comment by yfdyh000** [comment]
的确有错误报告了，设置`151.236.20.236:53`或`151.236.20.236:443`会有一片`DNSCurve Error: IPv4 Main Server UDP get signature data error.`，几秒一条。大概是因为自动测试，有点太频繁了。只在初始化测试时报一次就可以吧，或者自动检测与上条重复。

设置`128.199.248.105:54`没有报签名错误，并且会看到UDP一收一发，但仍然不正常。
将主DNS设为8.8.0.8:53，备用为8.8.4.4:53，启用DNSCurve。只见请求了错误的8.8.0.8，一收一发DNSCurve，但结果是超时。与备用的8.8.4.4未见有效通讯，对它只有一个ping和一个莫名其妙的`Name: 63qlifkgmf0qykcqhxqkny8bdwc.ywh`解析（及上一条是向8.8.0.8解析这个）。

然后是解析不存在的.cn域名，114返回NX，DNSCurve内容加密看不到，.0.8无结果，未调用备用境/内境外服务器解析，返回结果是超时。

**Comment by chengr28** [comment]
邮件已发……关于这些：
* 错误报告连续报告个人觉得才好……因为发现除非不能运行了否则一般人都不会留意有没有 Error.log 特别是现在错误报告还不会自动删除，越多越显眼 =_/=
* 关于这个服务器的确是可用的，程序判断请求失败是因为这货似乎不支持 EDNS0 因为程序的 DNSCurve 是参照了 OpenDNS 的 DNSCrypt 实现必须要求支持 EDNS0 的，刚才发给你的版本解除了这个限制……现在应该没有问题了
* 至于主备用服务器切换，昨晚的版本调整了抓包列表工作机制后没把超时探测加回去……现在应该也是可以的了

**Comment by yfdyh000** [comment]
* 如果用户未注意或者机器无人，撑出几十上百MB也有可能吧，真的感觉没什么必要，而且浪费IO。
* 还是不知道是53或443还是别的什么。用53好像就会有不断报错`DNSCurve Error: IPv4 Main Server UDP get signature data error.`，但抓包看到的确有正确回应`151.236.20.236	***	DNS	192	0	Standard query response 0x0850 No such name`。用443还是识别成QUIC。不知道怎么测试。
* 感觉还是不行，你试试改成 `IPv4 DNS Address = 8.8.0.8:53`，对于不存在的境内外域名，最终只会返回超时而不会报错NX。好像只Ping了备用但没有用来解析。
* 一点疑问，如果解析境外域名时主/备境外IP都挂掉，DNSCurve能正常验证和使用吗，能自我验证吗（无加密解析或自证签名），或者调用境内服务器获取签名来验证。

**Comment by chengr28** [comment]
* 参见 Log Maximum Size 参数的介绍
* 大概是因为那个服务器的 53 端口不支持 DNSCurve 加密模式造成的……不支持也没法，直接就拿不到加密连接的握手信息，自然就是用不了。至于 443 因为传输数据是加密的，所以我也不会知道最终传输的是什么……
* 关于这个我实测过是可以的，参见 Alternate Times/Alternate Time Range/Alternate Reset Time 这3个参数的介绍。毕竟这个功能只是设计给服务器挂掉时的备用方案，为了避免主要和备用服务器切换得太容易和频繁，程序内部只会每隔10秒检查一次计数状态，设计上是不能进行快速切换响应的。如果填的地址完全没有响应，等一段时间的确是可以切换到备用服务器的，你可以等几分钟再看看
* 按照 DNSCrypt 标准的作业方式，程序先会请求目标 DNSCurve 服务器的加密连接握手信息，请求失败才会尝试使用所有可用的服务器（注意这步是本程序为增加可靠性而加，并非 DNSCrypt 标准作业方式）请求，还是失败就是失败了。一开始我也以为加密连接握手信息是可以从公共 DNS 上拿到，但后来发现只有 OpenDNS 可以这样做，其它乱七八糟的域名都只能请求目标 DNSCurve 服务器的目标端口才能拿到……

**Comment by yfdyh000** [comment]
* 看到了，之前以为留空是无限制，刚翻文档看到了是8MB。
* 嗯……
* 哦，原来如此，大概我测试的间隔太近了。
* 嗯，只是疑问假设所有非DNSCurve服务器都挂掉时，DNSCurve能否正常使用。虽然基本不会遇到。

**Comment by chengr28** [comment]
主要是 DNSCrypt 的加密连接握手信息是储存在那个 TXT 记录里的（之前抓包应该也有看到吧）而那个 TXT 记录公共 DNS 不一定会有，也就是说 DNSCurve 服务器提供商不一定会去注册公共域名。如果他们不去注册域名，只能由他们自己的 DNSCurve 服务器（还有可能只能由 DNSCurve 加密传输使用的端口）进行解析，那么其它 DNS 服务器怎么查都是 NX 错误的……

**Comment by yfdyh000** [comment]
抓的包没仔细看，原来那个不是有效的公共域名吗……也就是说只能用自己的非加密隧道来获得自身TXT进行握手吗。如果加密隧道不能自举，该怎么初始握手。有点糊涂；只是好奇……

**Comment by chengr28** [comment]
流程：启动→向 DNSCurve 端口发送非加密请求（请求获取加密握手信息，此为非加密请求）→计算并记录所需的加密握手信息→加密握手传输

这个和 TLS 其实差不多，TLS 握手阶段（证书密钥交换之类）也是非加密的

**Comment by yfdyh000** [comment]
哦，也就是说DNSCurve也会接受非加密的DNS TXT查询请求了。

**Comment by chengr28** [comment]
DNSCurve 本身就有加密和非加密两种模式的……两种模式可以随便选随便用
只是加密模式使用前要获取加密用的握手信息而已……
参见 Encryption 参数的介绍
