### ISSUE TITLE
Pcap_DNSProxy 0.4.8.0 无法使用

### ISSUE THREAD

**Issue by wang20150419** [chengr28/Pcap_DNSProxy#210]
﻿### 版本号及运行环境

Pcap_DNSProxy 0.4.8.0 更新日志(2016-11-23)

Windows server 2012, 2008, 64bit

### 问题重现步骤

缺省配置，仅仅 修改 Operation Mode = Server

C:\Users\Administrator>nslookup www.google.com 127.0.0.1
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时

### 与默认配置不同的部分

仅仅 修改 Operation Mode = Server

### 程序错误日志

服务正常启动，防火墙也开放了。无出错日志。
恢复为上一版本工作正常。

**Comment by jzp820927** [comment]
用 TCP 模式试试

**Comment by wang20150419** [comment]
问题是，它要为普通计算机提供DNS服务，必须 UDP 53

**Comment by jzp820927** [comment]
我不是说本地监听，我是说，连接上级 DNS 服务器用 TCP 模式，现在 udp 也有干扰。

**Comment by wang20150419** [comment]
现在的问题是，不工作。连 t.cn 都解析不了。开启DNSCurve，可以抗干扰。

**Comment by jzp820927** [comment]
行吧，老大出面了，等老大解决吧

**Comment by chengr28** [comment]
刚才推上去的新版本应该已经解决这个问题了……这个 bug 是在修复另一个 Custom 模式工作不正常 bug 时引入的，真是失手 v_v

**Comment by cpexplorer** [comment]
@wongsyrone

**Comment by wongsyrone** [comment]
Done.
