### ISSUE TITLE
请问是否支持指定ptr记录

### ISSUE THREAD

**Issue by dzxx36gyy** [chengr28/Pcap_DNSProxy#211]
请问是否支持指定ptr记录呢? 想给一些内网地址加些ptr, 如果可以的话就不用再套个dnsmasq了

**Comment by dzxx36gyy** [comment]
另外在0.4.8.0上碰到过即使并没有打开ipv6监听，但是实际运行的时候还会不断尝试初始化ipv6监听的情况，不知道现在修好了没。

**Comment by jzp820927** [comment]
好像不行吧，docs 没有看到相关说明。

**Comment by chengr28** [comment]
并不支持，而且感觉只是给地址做个 PTR 并没有什么实际用途……

**Comment by chengr28** [comment]
不清楚是什么平台，不过建议是先升级到最新的版本再看看。理论上监听什么类型的地址是由 `Operation Mode` + `Listen Protocol` + `Listen Port` 这几个参数决定的，先修改设置一下看看

**Comment by dzxx36gyy** [comment]
@chengr28 主要是看到能定义pac_dnsproxy的servername，所以就好奇能否给其它地址做ptr记录。

**Comment by dzxx36gyy** [comment]
至于那个bug的话是在centos6.8 x64上碰到的(阿里云ECS)，系统镜像默认关闭了IPv6协议栈的支持。看了下文档说是指定了具体的Listen Address后上面的Listen Protocol之类会无效，所以理论上配置文件里应该已经彻底关闭了IPv6监听了（在碰到问题后也把Listen Protocol里的IPv6去掉了），Error.log内容全是"Network Error: Socket initialization error, error code is 97"，在把系统的IPv6支持恢复后才没有该报错。

**Comment by chengr28** [comment]
指定本地的 server name 纯粹是给 Windows 上 `nslookup` 看着方便的，如果直接转发的话会看到 `UnKnown` 不太好，实际上这个功能没有实际用途的

**Comment by dzxx36gyy** [comment]
了解了，那我再套个dnsmasq好了_(:з」∠)_。

**Comment by chengr28** [comment]
或者这样吧……把配置文件里所有的 IPv6 地址都去掉试试？

**Comment by dzxx36gyy** [comment]
@chengr28 事实上我已经这么做过了，但是依旧还是有问题……所以就比较懵逼，现在的话是把系统的ipv6支持打开了，使用正常，编译环境被我玩坏了，所以也不能马上测试新版本是否还有这问题_(:з」∠)_

**Comment by chengr28** [comment]
好吧，有时间检查一下看看……因为想要在完全不支持 IPv6 的系统上测试比较麻烦，需要的时间可能比较多

**Comment by jzp820927** [comment]
确实这个问题我之前也发现了，如果关系系统的 IPV6，就会不停的报这种错误。

**Comment by chengr28** [comment]
@dzxx36gyy @jzp820927 完全禁用 IPv6 协议栈后程序报错的问题大概已经解决……不过没有实际环境测试不太清楚，刚才的版本应该已经解决这个问题，有时间可以试试。

**Comment by jzp820927** [comment]
好的，空了我试试，因为有报错，上次就把 IPV6 又打开了，现在不方便重启，等我要重启的时候，再测试。有问题再来报告。

**Comment by chengr28** [comment]
测试的时候要把所有 IPv6 地址和数据清空

**Comment by jzp820927** [comment]
IPV6 禁用了，地址就自动没有了吧？ 不知道你说的地址，和数据，具体是指的？

**Comment by chengr28** [comment]
实际上程序不会主动检测系统是否支持 IPv6 而只能通过实际使用时系统 API 报告的错误，所以如果要让程序在完全不支持 IPv6 的情况下正常使用，需要把配置文件中所有和 IPv6 有关的数据删掉，这样。

**Comment by jzp820927** [comment]
哦，我懂了，你指的是配置文件里面的 IPV6 的地址。行。下次测试的时候，先清理配置文件。
