### ISSUE TITLE
咨询个源码编译的问题？

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#212]
看到最新源码 Source/Dependency/ 路径下，已经包含 LibSodium，OpenSSL，WinPcap 源码，是不是 Linux 下编译现在就不需要再单独安装这几个 依赖工具/库 了？但是怎么只有 WinPcap，没有 LibPcap 呢？

**Comment by wongsyrone** [comment]
这几个理论上只是给特定平台用的，比如Win，Mac，详情可以看头文件。分离出来是方便管理。

**Comment by jzp820927** [comment]
哦，原来是这样，不好意思，理解错误，我还以为直接把依赖的源码也集成了。

**Comment by chengr28** [comment]
Source/Dependency 目录那个是用于 Windows(Visual Studio) 和 macOS(Xcode) 静态链接用的源文件，是编译成二进制可执行文件时用的，而 Linux 一般是用户自行解决依赖和编译，所以实际上不需要这个目录

**Comment by jzp820927** [comment]
原来是这样，在 docs 里面没看到这个目录的说明，不好意思。
