### ISSUE TITLE
请问菊苣用什么 IDE 开发的？

### ISSUE THREAD

**Issue by pexcn** [chengr28/Pcap_DNSProxy#213]
或者说是用 vim 吗？

**Comment by jzp820927** [comment]
应该是 VS 吧？

**Comment by pexcn** [comment]
我用 CLion 也可以导入

**Comment by chengr28** [comment]
能用 CLion 是因为 Linux/macOS 版本是用 CMake 做自动化构建系统

**Comment by pexcn** [comment]
@chengr28 您用的是 vim?

**Comment by wongsyrone** [comment]
应该是VS吧

**Comment by wongsyrone** [comment]
如果考虑开发，版本号可以用 https://github.com/chengr28/Pcap_DNSProxy/blob/master/Source/Pcap_DNSProxy.sln#L4

**Comment by chengr28** [comment]
现在是 Visual Studio 2015 一般是新版出来一段时间测试一段时间才会更新这样

**Comment by pexcn** [comment]
@chengr28 @wongsyrone 谢谢两位菊苣 :kissing_heart:

**Comment by chengr28** [comment]
嘛多说两句吧……源代码本质上就是个文本文件而已，实际上用什么编辑工具都一个样，最重要还是自己必须要能懂自己在写什么干的是什么，实际上本人用得最多的是 Notepad++

**Comment by jzp820927** [comment]
我也用 notepad++，找到知己了。

**Comment by wongsyrone** [comment]
实际上我看代码主要是github网页，diff还有notepad++

**Comment by jzp820927** [comment]
很多聚聚都是用 st，想不到也有用 np++ 的聚聚，难得啊。
