### ISSUE TITLE
[DNSCurve Error] IPv4 Alternate Server UDP get signature data error.

### ISSUE THREAD

**Issue by yfdyh000** [chengr28/Pcap_DNSProxy#214]
﻿### 程序版本号及运行环境
0.4.8.3 (2016-12-24)

### 问题重现步骤
`DNSCurve = 1`

### 期望和实际的程序行为
`DNSCurve IPv4 Alternate Provider Name = 2.dnscrypt-cert-2.cloudns.com.au` 已失效？https://cloudns.com.au/ 网站的证书过期挺久了。

### 与默认配置不同的部分
仅Hosts.ini有修改。

### 程序错误日志
`[DNSCurve Error] IPv4 Alternate Server UDP get signature data error.` 不断输出到Error.log。

**Comment by jzp820927** [comment]
确实过期了，可以用 opendns 的嘛

**Comment by chengr28** [comment]
这里不用 OpenDNS 的考虑是它已经是 Main 的服务器了，如果 Alternate 的服务器还是 OpenDNS 那么一旦 OpenDNS 出问题就起不到备用的作用了，只是这边也没想到 DNSCrypt 了非 OpenDNS 服务器会这么不靠谱，之前 ISI 有一台也是写在 Alternate 上也是过期失效……

**Comment by wongsyrone** [comment]
我猜可能是运行成本的问题吧，改之前可以先试试哪个还可以

**Comment by jzp820927** [comment]
最靠谱的还是自己 VPS 上搭建一个 DNSCurve 服务器。

**Comment by chengr28** [comment]
@wongsyrone 其实基本上那个 csv 里的都可以，延迟比较高而已，但是不是长期有效这个真是硬伤……当年选 ClouDNS 一个很重要的原因是看上去比较稳定和靠谱，想不到还是这个样……

**Comment by wongsyrone** [comment]
之前看过哪里写的，好像csv里面的都重点关照了

**Comment by jzp820927** [comment]
https://cloudns.com.au/ 现在直接网站都打不开了，我去

**Comment by chengr28** [comment]
其实是换域名了，现在是 https://asia.cloudns.net

**Comment by jzp820927** [comment]
好吧，这都被你找到了，厉害！

**Comment by SeaHOH** [comment]
请问是这样设置吗？
```ini
[DNSCurve Addresses]
DNSCurve IPv4 Alternate DNS Address = 85.159.233.18:443
DNSCurve IPv4 Alternate Provider Name = 2.dnscrypt-cert-2.cloudns.net
[DNSCurve Keys]
DNSCurve IPv4 Alternate DNS Public Key =
```
 Public Key 有变化吗，留空可以不？

**Comment by jzp820927** [comment]
@SeaHOH 你在哪儿找到的这个 DNS ？我怎么没看到？

**Comment by SeaHOH** [comment]
解析 2.dnscrypt-cert-2.cloudns.net

**Comment by jzp820927** [comment]
好吧，这都能被你发现，太牛了。看来 cloudns 的 DNS 不是挂了，是被隐藏了。

**Comment by chengr28** [comment]
决定先观察一段时间再决定，刚才的更新就直接把 2 个协议的 DNSCrypt 备用服务器都留空了。非 CSV 里列出的暂不作考虑，感觉官方 CSV 里除了 OpenDNS 都不太靠谱的样子，不能直接放到配置文件里……

**Comment by jzp820927** [comment]
俄罗斯最大搜索引擎的那个DNS应该比较靠谱吧。
