### ISSUE TITLE
记录缓存过期功能无效

### ISSUE THREAD

**Issue by kraml** [chengr28/Pcap_DNSProxy#216]
### 程序版本号及运行环境

0.4.8.3
Windows 10 1607 x64

### 问题重现步骤

1. 查询一个域名A记录，记录正确，TTL正确。
2. 在DNS服务器端更新该域名A记录。
3. 待DNS服务器端设置的域名TTL时间过后重新查询，记录未更新，还是旧的结果。
4. 重启pcap_dnsproxy服务，重新查询，结果正确。

### 期望和实际的程序行为

查询结果TTL时间过后，pcap_dnsproxy应丢弃缓存的结果，重新从服务器获取记录。

### 与默认配置不同的部分

无，使用默认配置文件。

**Comment by kraml** [comment]
所以说这不是bug而是之前压根没实现这个功能是吗？

**Comment by chengr28** [comment]
并不是……这里的缓存算法对于缓存时间的部分没有在 ReadMe 里写清楚，其实是这样的：
* 缓存类型为 `TIMER` 时：取解析记录中的 TTL 值，如果值小于等于 `Cache Parameter` 所指定的值则使用 `Cache Parameter` 的缓存时间值，如果大于指定的缓存时间值则使用解析记录中的 TTL 值
* 缓存类型为 `QUEUE` 时：此类型忽略解析记录中的 TTL 值
* 缓存类型为 `BOTH` 时：取解析记录中的 TTL 值，如果值小于 `Default TTL` 所指定的值则使用 `Default TTL` 缓存时间值与解析记录中的 TTL 值的差值作为缓存时间，如果大于等于指定的缓存时间值则使用解析记录中的 TTL 值

**Comment by chengr28** [comment]
至于这样设定的原因是，有不少域名的 TTL 值设得很小（例如几秒）当时设计缓存系统的目的是为了解决由于程序获取解析结果的流程和所需的时间比较长导致解析连续失败的情况，所以划一了使用参数指定一个 **最短缓存时间** 以避免这种情况。所以实际上就是比原来直接使用系统协议栈进行解析，多了一层的缓存做保障这样，缓存的时间也相对地拉长了

如果 LZ 这种情况，需要严格遵守解析记录中的 TTL 值的话，这边在下次更新会加上完全按照解析记录中的 TTL 值进行缓存的功能。至于当年不按照这个标准流程缓存，是因为考虑到程序和系统的协议栈时间线是完全一样的，如果都按照解析记录中的 TTL 值进行缓存，那么两者的缓存会在相同的瞬间过期，这样程序的缓存功能就完全没有用还不如关掉了

**Comment by kraml** [comment]
可是我刚才测试了一下，配置文件中按这样：
Cache Type = Timer
Cache Parameter = 300
Default TTL = 300

我的域名服务器端配置一个A记录TTL 600s。

按描述，pcap_dnsproxy应该在600s之后过期掉该记录的缓存，客户端重新查询的话应重新从DNS服务器获取新的记录。但实际上现象如开始描述，必须要重启pcap_dnsproxy服务后才会获取到更新后的记录，不重启的话一直都是缓存的记录。

**Comment by chengr28** [comment]
呃刚才认真看了下，缓存的部分的确在部分情况下会出问题……理论的工作规则上面说了，不过如果在请求此域名之前有其它解析记录中的 TTL 值更长的情况，可能堵塞掉程序清空缓存列表，这的确是个问题，下次更新应该会解决

**Comment by kraml** [comment]
Thanks。我认为上面那个规则对于实际使用是没问题的，无论是用记录的TTL，还是自己的TTL，其实都可以，只要在预期的时间后清掉就行。期待下次更新解决。

**Comment by chengr28** [comment]
认真想了一下上面的策略有点问题……稍微修改了一下，有建议可以直接发在这里：

---

  * Cache Type - DNS 缓存的类型：分 Timer/计时型、Queue/队列型以及它们的混合类型，填入 0 为关闭此功能
    * Timer/计时型：超过指定时间的 DNS 缓存将会被丢弃
    * Queue/队列型：超过队列长度时，将删除最旧的 DNS 缓存
    * 混合类型：超过指定时间时、超过队列长度时以及超过域名本身 TTL 时，都会删除最旧的 DNS 缓存
  * Cache Parameter - DNS 缓存的参数：分 Timer/计时型、Queue/队列型以及它们的混合类型，填入 0 为关闭此功能
    * Timer/计时型
      * 缓存时间，单位为秒
      * 如果解析结果的平均 TTL 值大于此值，则使用 [TTL + 此值] 为最终的缓存时间
      * 如果解析结果的平均 TTL 值小于等于此值，则使用 [此值] 为最终的缓存时间
      * 如果填 0 则最终的缓存时间为 TTL 值
    * Queue/队列型：队列长度
    * 混合类型
      * 队列长度
      * 此模式下最终的缓存时间由 Default TTL 参数决定
  * Default TTL - 已缓存 DNS 记录默认生存时间：单位为秒，留空则为 900秒/15分钟
    * DNS 缓存的类型为混合类型时，本参数将同时决定最终的缓存时间
      * 如果解析结果的平均 TTL 值大于此值，则使用 [TTL + 此值] 为最终的缓存时间
      * 如果解析结果的平均 TTL 值小于等于此值，则使用 [此值] 为最终的缓存时间
      * 如果填 0 则最终的缓存时间为 TTL 值

**Comment by chengr28** [comment]
刚才推送的更新已经包含这个特性，感谢反馈。
