### ISSUE TITLE
win10 系统下无法正常安装，请问可能是什么情况

### ISSUE THREAD

**Issue by 4630g** [chengr28/Pcap_DNSProxy#217]
﻿### 程序版本号及运行环境

win10 64位系统运行

### 问题重现步骤

servicecontrol.bat 右键以管理员权限运行，选择安装，提示controlservice失败， 1062：服务尚未启动。

**Comment by jzp820927** [comment]
直接运行 Windows/Pcap_DNSProxy.exe 呢

**Comment by chengr28** [comment]
请提供完整的错误画面截图或者文字复制，或者如果有 Error.log 生成也请提供，谢谢
