### ISSUE TITLE
驱动之家的图片服务器解析失败

### ISSUE THREAD

**Issue by jrkkei** [chengr28/Pcap_DNSProxy#218]
﻿### 程序版本号及运行环境

最新版，win10 64

### 问题重现步骤

这个现象偶尔出现，有时会自己恢复正常，今天又碰到，就尝试升级到最新版本，结果一直无法解析，直接用dns没有问题

### 期望和实际的程序行为
 nslookup img1.mydrivers.com
サーバー:  pcap-dnsproxy.server
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** pcap-dnsproxy.server への要求がタイムアウトしました
PS C:\Users\FKMS> nslookup img1.mydrivers.com 114.114.115.115
サーバー:  public2.114dns.com
Address:  114.114.115.115

権限のない回答:
名前:    u955.v.qingcdn.com
Addresses:  120.52.72.37
          220.194.75.241
          218.29.145.38
          120.52.72.39
          220.194.75.239
          218.29.145.40
          218.29.145.37
          220.194.75.240
          218.29.145.39
          120.52.72.40
Aliases:  img1.mydrivers.com
          img1.mydrivers.com.qingcdn.com

### 与默认配置不同的部分
Local Force Request = 1
Local Hosts = 1
Local Main = 0
Local Routing = 0

### 程序错误日志

无。

**Comment by jzp820927** [comment]
就只有这1个域名解析失败？其他都正常？

**Comment by wongsyrone** [comment]
尝试一下默认配置呢？

**Comment by jrkkei** [comment]
@jzp820927 是的
@wongsyrone 默认配置正常。但是我一直是这么用的，也一直正常，不知道为什么近期老是抽

**Comment by wongsyrone** [comment]
我昨晚在路由上测了一下，相对于默认配置我只改了Edns label和tcp fast open，没有问题，有可能是一个bug，也可能是各地区的网络问题，不太好说。

**Comment by jzp820927** [comment]
我这边试了下，也没啥问题，看来是个例？

**Comment by chengr28** [comment]
无法解析是因为 `120.52.72.x` 这几个解析结果在 `IPFilter.ini` 的黑名单里……
如果确实需要解析，可以把过滤规则删掉保存并重启服务：

`## China Unicom`
`120.52.72.0-120.52.73.255 ALL`

**Comment by jrkkei** [comment]
晕，这算是躺枪吗。。。
用白名单模式，不存在的域名都是归境外dns管吧？这个ip黑名单可以禁用吧？

**Comment by jzp820927** [comment]
把那个文件里面的IP，全部删掉，就算是禁用了吧

**Comment by chengr28** [comment]
这个 IPFilter 其实是一种规则，ReadMe 里有提到：

    当 Blacklist Filter 为开启时，将检查本列表域名与解析结果
    如果解析结果里含有与域名对应的黑名单地址，则会直接丢弃此解析结果

这个是对所有请求过程（包括境内服务器）启用的，不存在管不管的问题。
如果只是这个域名出问题，建议是把 `120.52.72.0-120.52.73.255 ALL` 这行删掉就行。
如果不想用，那么直接把这个文件删掉即可，当然这是不建议的。

**Comment by jzp820927** [comment]
对了 “直接丢弃此解析结果” ，理解上有一些歧义，比如这种情况：
IPFilter.ini 里面有
## China Unicom
120.52.72.0-120.52.73.255 ALL

而域名的解析结果是：
120.52.72.37
220.194.75.241

解析结果有2个IP，那么此时的 “直接丢弃此解析结果” 是把这2个IP全部丢掉？还是丢掉 120.52.72.37，220.194.75.241 正常返回，因为这个 IP 不在黑名单。

按我的理解应该是丢掉第一个，返回第二个，如果是这种情况的话，img1.mydrivers.com 应该还是有解析 IP 返回，而不是解析失败。而根据楼主反应的情况，我感觉好像是把所有结果全部丢掉了，感觉这样不太科学。

**Comment by chengr28** [comment]
@jzp820927 你的理解有问题。虽然 nslookup 显示出来是一堆地址，但实际上这是『一个数据包里带有这一批地址』才对，因为命中了黑名单的地址，所以程序就会认为『这一整个数据包』都不能被接受，就丢弃掉了

**Comment by jzp820927** [comment]
好吧，我懂了，谢谢解惑。
