### ISSUE TITLE
WinPcap Error: Insufficient permissions or no any available network devices.

### ISSUE THREAD

**Issue by standritsu** [chengr28/Pcap_DNSProxy#22]
如题，系统是Win 10 X64，看Error.log这个提示每十秒出现一次，以前的版本没这个问题，更新最新版后才出现。

**Comment by chengr28** [comment]
你好，关于 Windows 10 x64 实测了一下，程序的运行是没有问题的，也没有出现错误。这个错误意思是 WinPcap 检测不到有可用的网络适配器，可能是权限问题造成的，也可能是没有任何可用的网络适配器，可能需要检查一下系统的网络适配器是否可用，或者网卡驱动程序是否正确安装

因为现在 Windows 10 现在还在技术预览阶段，有 Bug 其实也不奇怪 =_/=

**Comment by standritsu** [comment]
10041以后的版本网络控制器配置接口改了有BUG，这个在微软官方论坛上有人反映，我不知道是不是这个问题的成因，除了一直提示这个以外，DNS工作似乎并没有问题，WinPcap的安装目录下倒是留下这样的安装日志，不知道是不是安装成功了：
WinPcap 4.1.0.2980 Installation LOG
-----------------------------------------------------
Debug Information


Operating system detected on registry: 8 - AMD64
True operating system (kernel.dll):    8 - AMD64
npptools.dll present on the system:    false
netnm.inf present on the system:       false
nmnt.sys present on the system:        false

End of log
-----------------------------------------------------

**Comment by chengr28** [comment]
能不能正常工作主要是看是否有其它获取解析的方法……WinPcap 这边是主要的，所以如果启动失败的话其实对域名解析很有影响的
如果不想使用 WinPcap 抓包模块，修改 Config.ini 的 Pcap Capture 参数为 0 保存并重启服务即可

**Comment by chengr28** [comment]
Windows 10 正式版本发布了，不知道现在最新版本还会不会出现类似的问题？

**Comment by standritsu** [comment]
现在正常了
