### ISSUE TITLE
讨论，对过滤原理有些疑问

### ISSUE THREAD

**Issue by ccaapton** [chengr28/Pcap_DNSProxy#221]
chengr28你好，目前我使用的设置是Pcap Capture = 0, DNSCurve = 1, DNSCurve Encryption = 0, port 443 基本上就是利用非标准端口上目前没有污染的特点，效果不错。

想问下包过滤功能是否只有依赖libpcap这一种方式？我的理解是，如果需要做透明无感知的过滤，则必须依赖内核iptables/netfilter或者pcap这类工具。但Pcap_DNSProxy是一个显式服务， 要求客户端修改dns地址的， 同时Pcap_DNSProxy通过正常监听端口就可以获取所有服务器（或者不明物体）返回的所有dns记录。虽然劫持包会更早到达，但是Pcap_DNSProxy依然可以选择忽略这个包，继续等待正确结果。那么pcap的依赖是否有必要呢？

**Comment by chengr28** [comment]
这个配置是把抓包模块关掉了，只用非标准端口进行解析。其实抓包模块这个的确不是必须的，Linux/macOS 平台下编译就可以通过 `ENABLE_PCAP` 这个参数进行控制，只是如果启用这个模块，万一其它途径获取结果失败时还有机会能继续正常使用，可以提高域名解析的可靠性。
