### ISSUE TITLE
是不是主服务器出问题了?

### ISSUE THREAD

**Issue by snakwu** [chengr28/Pcap_DNSProxy#222]
Last login: Fri Mar 24 12:26:24 2017 from 192.168.88.5
snakwu@uBuntu-DNS:~$ nslookup www.google.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   wWW.gOOGLe.coM
Address: 216.58.200.36

snakwu@uBuntu-DNS:~$
用的是IPv4 + TCP 模式,正常来说应该是解出地址列表的,现在只有一个地址,还有,如果用手机或者其它设备连上wifi,在局域网下,用他做dns,会断流,常常要刷新好多次出才网页....

**Comment by DonetskRiver** [comment]
我这边也是欸，用的IPv4 + TCP 模式，最近两天，只解析出一个地址。

C:\WINDOWS\system32>nslookup www.google.com
服务器:  pcap-dnsproxy.server
Address:  127.0.0.1

非权威应答:
名称:    wWw.gOOgLe.cOM
Addresses:  2404:6800:4008:803::2004
          216.58.200.36

**Comment by jzp820927** [comment]
既然能解析出来就说明 DNS 工作正常，解析 IP 数的多少，可能和上游 DNS 有关吧。

**Comment by DonetskRiver** [comment]
抱歉，刚想起来我这里开启了Alternate Multiple Request参数.....，感觉应该是它的问题，不知道 @snakwu是否情况与我相同？

**Comment by chengr28** [comment]
看起来这个 Issue 有两个问题：
* 解析结果和上游各个最快返回的 DNS 服务器的解析有关，不清楚『正常来说应该是解出地址列表』这个前提是怎么得来的，如果觉得有有可疑，可自行使用 `dig` 直接请求这些上游的 DNS 服务器检查解析结果
* 关于要刷几次才能刷出来这个不好说，各地网络状况不一样获取解析的时长也不一样，如果确实不放心可以抓个包看看具体的工作情况
* 还有一点就是提 Issue 的时候不要自说自的……这里 New 应该是有模板的，使用的版本和运行环境一个都不说，这边只能靠猜很难进行处理……谢谢。

**Comment by snakwu** [comment]
我并没有开启Alternate Multiple Request,用的是默认值...@DonetskRiver

**Comment by snakwu** [comment]
@chengr28 
使用的版本:0.4.8.5
运行环境:ubuntu 16.04

Error.log
[2017-03-24 20:06:47] -> [Notice] Pcap_DNSProxy started.
[2017-03-24 20:06:47] -> [DNSCurve Error] IPv4 Main Server UDP get signature data error.

**Comment by snakwu** [comment]
配置我也贴上来吧...
[Base]
Version = 0.45
File Refresh Time = 15
Large Buffer Size = 4096
Additional Path = 
Hosts File Name = Hosts.ini|Hosts.conf|Hosts|Hosts.txt|WhiteList.txt|White_List.txt
IPFilter File Name = IPFilter.ini|IPFilter.conf|IPFilter.dat|Routing.txt|chnrouting.txt|chnroute.txt

[Log]
Print Log Level = 3
Log Maximum Size = 8MB

[Listen]
Pcap Capture = 1
Pcap Devices Blacklist = AnyConnect|Host|Hyper|ISATAP|IKE|L2TP|Only|Oracle|PPTP|Pseudo|Teredo|Tunnel|Virtual|VMNet|VMware|VPN|any|gif|lo|stf|utun
Pcap Reading Timeout = 25
Listen Protocol = IPv6 + IPv4 + TCP + UDP
Listen Port = 53
Operation Mode = Server
IPFilter Type = Deny
IPFilter Level < 0
Accept Type = 

[DNS]
Outgoing Protocol = IPv4 + TCP
Direct Request = 0
Cache Type = Timer + Queue
Cache Parameter = 1280
Default TTL = 9000

[Local DNS]
Local Protocol = IPv4 + TCP
Local Force Request = 0
Local Hosts = 0
Local Main = 1
Local Routing = 1

[Addresses]
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 
IPv4 Main DNS Address = 8.8.4.4:53
IPv4 Alternate DNS Address = 8.8.8.8:53|208.67.220.220:443|208.67.222.222:5353
IPv4 Local Main DNS Address = 114.114.115.115:53
IPv4 Local Alternate DNS Address = 223.6.6.6:53
IPv6 Listen Address = 
IPv6 EDNS Client Subnet Address = 
IPv6 Main DNS Address = [2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = [2001:4860:4860::8888]:53|[2620:0:CCD::2]:443|[2620:0:CCC::2]:5353
IPv6 Local Main DNS Address = 
IPv6 Local Alternate DNS Address = 

[Values]
Thread Pool Base Number = 0
Thread Pool Maximum Number = 1280
Thread Pool Reset Time = 120
Queue Limits Reset Time = 0
EDNS Payload Size = 1220
IPv4 Packet TTL = 32 - 255
IPv4 Main DNS TTL = 0
IPv4 Alternate DNS TTL = 0
IPv6 Packet Hop Limits = 32 - 255
IPv6 Main DNS Hop Limits = 0
IPv6 Alternate DNS Hop Limits = 0
Hop Limits Fluctuation = 2
Reliable Once Socket Timeout = 3000
Reliable Serial Socket Timeout = 1500
Unreliable Once Socket Timeout = 2000
Unreliable Serial Socket Timeout = 1000
TCP Fast Open = 0
Receive Waiting = 0
ICMP Test = 900
Domain Test = 900
Alternate Times = 10
Alternate Time Range = 60
Alternate Reset Time = 300
Multiple Request Times = 0

[Switches]
Domain Case Conversion = 1
Compression Pointer Mutation = 0
EDNS Label = 1
EDNS Client Subnet Relay = 0
DNSSEC Request = 0
DNSSEC Validation = 0
DNSSEC Force Validation = 0
Alternate Multiple Request = 0
IPv4 Do Not Fragment = 0
IPv4 Data Filter = 0
TCP Data Filter = 1
DNS Data Filter = 1
Blacklist Filter = 1
Strict Resource Record TTL Filter = 0

[Data]
ICMP ID = 
ICMP Sequence = 
ICMP PaddingData = 
Domain Test ID = 
Domain Test Data = 
Local Machine Server Name = Pcap_DNSProxy

[Proxy]
SOCKS Proxy = 0
SOCKS Version = 5
SOCKS Protocol = IPv4 + TCP
SOCKS UDP No Handshake = 1
SOCKS Proxy Only = 0
SOCKS IPv4 Address = 127.0.0.1:1080
SOCKS IPv6 Address = [::1]:1080
SOCKS Target Server = 8.8.4.4:53
SOCKS Username = 
SOCKS Password = 
HTTP CONNECT Proxy = 0
HTTP CONNECT Protocol = IPv4
HTTP CONNECT Proxy Only = 0
HTTP CONNECT IPv4 Address = 127.0.0.1:1080
HTTP CONNECT IPv6 Address = [::1]:1080
HTTP CONNECT Target Server = 8.8.4.4:53
HTTP CONNECT TLS Handshake = 0
HTTP CONNECT TLS Version = 0
HTTP CONNECT TLS Validation = 1
HTTP CONNECT TLS Server Name Indication = 
HTTP CONNECT Version = 1.1
HTTP CONNECT Header Field = Content-Length: 0
HTTP CONNECT Header Field = User-Agent: Pcap_DNSProxy/0.4.5.0
HTTP CONNECT Header Field = Accept: */*
HTTP CONNECT Header Field = Cache-Control: no-cache
HTTP CONNECT Header Field = Pragma: no-cache
HTTP CONNECT Proxy Authorization = 

[DNSCurve]
DNSCurve = 1
DNSCurve Protocol = IPv4 + TCP
DNSCurve Payload Size = 512
DNSCurve Reliable Socket Timeout = 3000
DNSCurve Unreliable Socket Timeout = 2000
DNSCurve Encryption = 1
DNSCurve Encryption Only = 0
DNSCurve Client Ephemeral Key = 0
DNSCurve Key Recheck Time = 1800

[DNSCurve Addresses]
DNSCurve IPv4 Main DNS Address = 208.67.220.220:443
DNSCurve IPv4 Alternate DNS Address = 
DNSCurve IPv6 Main DNS Address = [2620:0:CCC::2]:443
DNSCurve IPv6 Alternate DNS Address = 
DNSCurve IPv4 Main Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv4 Alternate Provider Name = 
DNSCurve IPv6 Main Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv6 Alternate Provider Name = 

[DNSCurve Keys]
DNSCurve Client Public Key = 
DNSCurve Client Secret Key = 
DNSCurve IPv4 Main DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
DNSCurve IPv4 Alternate DNS Public Key = 
DNSCurve IPv6 Main DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
DNSCurve IPv6 Alternate DNS Public Key = 
DNSCurve IPv4 Main DNS Fingerprint = 
DNSCurve IPv4 Alternate DNS Fingerprint = 
DNSCurve IPv6 Main DNS Fingerprint = 
DNSCurve IPv6 Alternate DNS Fingerprint = 

[DNSCurve Magic Number]
DNSCurve IPv4 Main Receive Magic Number = 
DNSCurve IPv4 Alternate Receive Magic Number = 
DNSCurve IPv6 Main Receive Magic Number = 
DNSCurve IPv6 Alternate Receive Magic Number = 
DNSCurve IPv4 Main DNS Magic Number = 
DNSCurve IPv4 Alternate DNS Magic Number = 
DNSCurve IPv6 Main DNS Magic Number = 
DNSCurve IPv6 Alternate DNS Magic Number =

**Comment by wongsyrone** [comment]
208.67.220.220:443 这个不是opendns的吗，有DNSCurve？

**Comment by snakwu** [comment]
Last login: Fri Mar 24 16:09:04 2017 from 192.168.88.5
snakwu@uBuntu-DNS:~$ dig www.google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30191
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 16384
;; QUESTION SECTION:
;www.google.cOm.                        IN      A

;; ANSWER SECTION:
www.google.cOm.         300     IN      A       216.58.200.36

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Mar 24 22:16:30 CST 2017
;; MSG SIZE  rcvd: 59

snakwu@uBuntu-DNS:~$

**Comment by snakwu** [comment]
@wongsyrone 
我打开了DNSCurve搞干扰

**Comment by wongsyrone** [comment]
从这里试试其他DNSCurve服务器地址，没准被干扰了也说不准：https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

**Comment by snakwu** [comment]
@wongsyrone dnscrypt的服务器,通用?

**Comment by wongsyrone** [comment]
只要写了正确的参数应该就是对的。

另外 @chengr28  这里有个[v2的协议](https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt)，你看看和现在的有没有变化，没准人家更新了协议，然后旧的不能用。

**Comment by snakwu** [comment]
我上面贴出了配置,应该没有问题的吧?

**Comment by wongsyrone** [comment]
在我看来没啥问题。可能是DNSCurve服务器和你这边通讯受到干扰什么的。

**Comment by snakwu** [comment]
嗯,就是这两天,之前一直正常的...

**Comment by chengr28** [comment]
@snakwu `[2017-03-24 20:06:47] -> [DNSCurve Error] IPv4 Main Server UDP get signature data error.` 这个是 DNSCrypt 的连接信息获取失败产生的错误，一般来说应该是等待响应超时导致的，估计是你那边的 ISP 屏蔽（或者例如 CMCC 这种直接架了个假服务器的）了 OpenDNS 也会导致这个问题，这边测试过是没有问题的

**Comment by chengr28** [comment]
@wongsyrone DNSCrypt v2 这个应该是新增了一个算法 `XChaCha20-Poly1305` 有时间会添加支持，这个新算法和旧算法是兼容的可以自行（不知道是客户端还是服务器端）选择。不过好像是前个月才出的估计还没有普及，大概是等待一段时间看看。

**Comment by chengr28** [comment]
@snakwu 还是那两个问题：
* 如果没有写 Hosts 的话，程序的结果都是上游 DNS 服务器提供的，可以尝试使用 `dig -p 端口号 @服务器 查询用的域名` 这样直接查询列表上的 DNS 服务器看看结果。各地区不同 DNS 服务器都有可能影响实际的结果，不能以此为标准就断定 `www.google.com` 的解析结果一定是一个地址列表。
* 关于响应有可能延迟的问题之前也解释过可能是网络原因，尤其是看配置文件 TCP 协议都开启了也可能会大幅延长解析所需要的时间。有一个建议是如果不确定原因，可以在运行了程序的机器上进行抓包，将抓包的结果放上来（或者发到我的邮箱）这样可以进行更详细的检查，这个方法同样适用于上一个问题。

**Comment by snakwu** [comment]
@chengr28 好的,你有没有什么联系方式?

**Comment by snakwu** [comment]
@chengr28 已发你邮箱,请查收!

**Comment by chengr28** [comment]
如果还有问题的话直接在这里回复或者邮件联系就行，这边都能看到。
