### ISSUE TITLE
建议 WhiteList 添加 apple.china.conf

### ISSUE THREAD

**Issue by smounives** [chengr28/Pcap_DNSProxy#223]
如题，felixonmars 的 dnsmasq-china-list 项目添加了一个 [Apple 中国](https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf)的地址，建议在 WhiteList 中或者 Update_WhiteList 中加上，谢谢！

**Comment by chengr28** [comment]
源代码中的所有相关脚本都已经更新了，可执行二进制里附带的相关文件也会在下次更新时更新，感谢反馈。

**Comment by smounives** [comment]
感谢及时更新！
