### ISSUE TITLE
您好，我有一个关于非标准端口的问题想请问。

### ISSUE THREAD

**Issue by chinaniupai** [chengr28/Pcap_DNSProxy#225]
﻿### Version/使用的版本/使用的版本
最新版本

### Running Environment/运行环境/運行環境
win7

### Actual/实际情况/實際情況
我在Listen Port把53端口改成5353之后就无法使用了。

**Comment by chinaniupai** [comment]
请问为什么改成5353之后就无法使用了？
这是Error.log里的内容
[2017-04-03 17:09:32] -> [Notice] Pcap_DNSProxy started.
[2017-04-03 17:09:32] -> [Network Error] Bind UDP Monitor socket error: Only one usage of each socket address (protocol/network address/port) is normally permitted[10048].
[2017-04-03 17:09:32] -> [Network Error] Bind UDP Monitor socket error: Only one usage of each socket address (protocol/network address/port) is normally permitted[10048].

**Comment by chengr28** [comment]
`Error Code = 10048: Address already in use.`
此端口被其它程序占用，无法使用。

**Comment by chinaniupai** [comment]
@chengr28 请问我该如何解决这个问题呢？

**Comment by chengr28** [comment]
Windows 下可以使用以下方法查看端口占用情况：
- 以管理员权限运行 `cmd` 然后输入 `netstat -ano`
- 查找对应的监听端口并记下进程的 PID，例如本例中是 UDP 协议的 5353 端口，那就可以查找类似 `[::]:5353` 或者 `0.0.0.0:5353` 的条目
- 打开任务管理器，通过 PID 找到进程的名称

**Comment by chinaniupai** [comment]
@chengr28 我已经看了，是chrome占用了。我该如何解决？

**Comment by chengr28** [comment]
那这个得找 Google 解决了……或者还有个更简单的方法，就是把所有 Chrome 都关掉，然后运行本程序抢先把端口占了，这样 Chrome 启动后就占不了了……

**Comment by chinaniupai** [comment]
@chengr28 感谢，我还有一个问题，怎么让github自动提醒我有人回复？

**Comment by chinaniupai** [comment]
@chengr28 非常感谢您。谢谢！祝您身体健康，万事如意。

**Comment by chengr28** [comment]
@chinaniupai GitHub 如果有人 @ 的话是会自动提醒的，之前一直都没有 @ 这种回复想要自动提醒，好像得 watch 这个项目才能做到

**Comment by chinaniupai** [comment]
@chengr28 如果我想改成非标准端口，5353，只需要修改Listen Port这一个就可以是吧？
我已经修改了 
[DNS]Outgoing Protocol = IPv4 + TCP

[Local DNS]Local Protocol = IPv4 + TCP

[Switches]EDNS Label = 1

[DNSCurve]DNSCurve = 1  DNSCurve 
Protocol = IPv4 + TCP   
DNSCurve Encryption = 1

如果我修改成了5353端口，上面这些是不是就可以恢复默认了？

**Comment by chengr28** [comment]
`Listen Port` 参数就是指定监听端口用的，其它参数是其它的事情。
更多详细的配置信息，参见 ReadMe 文档。

**Comment by chinaniupai** [comment]
@chengr28 我刚刚关掉所有5353的占用程序之后，错误代码变成了这个

[2017-04-03 18:46:55] -> [Notice] Pcap_DNSProxy started.
[2017-04-03 18:46:55] -> [System Error] Process already exists error: Cannot create a file when that file already exists[183].

**Comment by chengr28** [comment]
这个错误是因为同时多次启动了本程序，请确保同一时间只运行一个本程序

**Comment by chinaniupai** [comment]
好吧

**Comment by chinaniupai** [comment]
可是我目前已经把所有端口占用都弄掉了，还是无法使用5353端口，

**Comment by chinaniupai** [comment]
@chengr28 似乎根本不是端口占用的问题，改成其他端口就无法正常解析。

**Comment by chinaniupai** [comment]
@chengr28 我该如何解决呢= =，您是否有时间可以远程我帮我排查排查问题？万分感谢。

**Comment by chinaniupai** [comment]
@jzp820927

**Comment by SeaHOH** [comment]
windows 连接 DNS 设置？这个没法改吧。

**Comment by jzp820927** [comment]
@chinaniupai 系统默认只支持 53 端口的 UDP 协议。你为什么非要用非 53 端口呢？用 53 端口不行麽？

**Comment by chinaniupai** [comment]
@jzp820927 你们不是说非标准端口可以没污染吗？

**Comment by chinaniupai** [comment]
@jzp820927 @chengr28 那你们是怎么用非标准端口的啊？

**Comment by jzp820927** [comment]
我想你的理解有问题，非标准端口是指的 Pcap_DNSProxy 和境外 DNS 之间的通信，标准端口是用于你的电脑和 Pcap_DNSProxy 直接的通信。

**Comment by chinaniupai** [comment]
@jzp820927 原来是这样啊，那我该如何让Pcap_DNSProxy用非标准端口和境外DNS之间通讯呢？

Listen Port的端口是用于我的电脑和 Pcap_DNSProxy 之间的通信对吧？

**Comment by jzp820927** [comment]
你应该仔细看看文档，文档说的很清楚了，
* Listen - 监听参数区域
* Listen Port - 监听端口，本地监听请求的端口：格式为 "端口A(|端口B)"（不含引号，括号内为可选项目）
此处设置的是你的电脑和 Pcap_DNSProxy 之间的通信端口 。

* Addresses - 普通模式地址区域
* IPv4 Main DNS Address - IPv4 主要 DNS 服务器地址：需要输入一个带端口格式的地址，留空为不启用
此处设置的是 Pcap_DNSProxy 和境外 DNS 之间的通信端口。
默认配置如下：
IPv4 Main DNS Address = 8.8.4.4:53
IPv4 Alternate DNS Address = 8.8.8.8:53|208.67.220.220:443|208.67.222.222:5353
已经是配置好非标准端口了，不用修改直接都能用的。
建议你仔细看看说明文档

**Comment by chinaniupai** [comment]
@jzp820927 我终于看明白了，原来说的是连接人家DNS服务器的端口啊，而且好像谷歌DNS不支持非标准端口。我刚刚ping了一下谷歌dns发现了一件事，联通居然伪造了一个谷歌dns服务器。
![image](https://cloud.githubusercontent.com/assets/26068235/24651569/e961b790-1960-11e7-9df7-ab33a3309e9f.png)

**Comment by SeaHOH** [comment]
不就干这事的吗，它不伪造我们干嘛这么折腾。

**Comment by yfdyh000** [comment]
@chinaniupai 也可能是任播，Google DNS有。我这里联通目前是高丢包率。

**Comment by chinaniupai** [comment]
@SeaHOH @yfdyh000 也就是说，软件里的海外主DNS事实上查询的是伪造的DNS？并不能查询到真的DNS？那我就要考虑把IPv4 Main DNS Address的 8.8.4.4:53换成台湾中华电信的DNS了，168.95.192.1

**Comment by SeaHOH** [comment]
@yfdyh000 
3ms 不可能是真的吧，即使任播。

@chinaniupai 
如果你不是很清楚 DNS 流程，不建议修改，其实默认设置还是够用的。

**Comment by chinaniupai** [comment]
@SeaHOH 我现在把Config.ini文件里所有谷歌的dns都改成了中华电信的dns了。

**Comment by chinaniupai** [comment]
我目前已经修改了这些
[DNS]Outgoing Protocol = IPv4 + TCP

[Local DNS]Local Protocol = IPv4 + TCP

[Switches]EDNS Label = 1

[DNSCurve]DNSCurve = 1 DNSCurve
Protocol = IPv4 + TCP
DNSCurve Encryption = 1

[Addresses]IPv4 Main DNS Address = 168.95.192.1:53
IPv4 Alternate DNS Address = 168.95.1.1:53|208.67.220.220:443|208.67.222.222:5353

[Proxy]SOCKS Target Server = 168.95.192.1:53
HTTP CONNECT Target Server = 168.95.192.1:53

**Comment by chinaniupai** [comment]
@yfdyh000 @jzp820927 我这么改没问题吧？

**Comment by SeaHOH** [comment]
开了 DNSCurve，建议把 Local Main 和 Local Routing 关掉，不然慢得很。
然后既然 Local Main 和 Local Routing 关掉了，就把 Local Hosts 打开，白名单很好用的。
还有，代理没有打开，你确定要用代理？

**Comment by chengr28** [comment]
@chinaniupai 个人建议你先仔细阅读一下 ReadMe 说明文档，尤其是看到你的配置里还修改了 `[Proxy]` 的部分，改之前请确认自己在干什么。

**Comment by chinaniupai** [comment]
@SeaHOH 请问为什么开了DNSCurve之后最好把 Local Main 和 Local Routing 关掉？我记得一个是优先国内解析，一个是检查？
你说的代理指的是什么？

**Comment by chinaniupai** [comment]
@chengr28 我已经阅读了ReadMe 说明文档，但是看得我云里雾里了，好多东西都不明白什么意思。

**Comment by chengr28** [comment]
@chengr28 看不懂那你更应该去借助搜索引擎帮助你进行理解。就举 `[Proxy]` 这个字段来说，连 SOCKS 和 HTTP CONNECT 都不知道是什么，就想着去开，这不太对吧？

**Comment by chinaniupai** [comment]
@chengr28 您说的对....我不应该因为8.8.8.8被伪造就把所有8.8.8.8都改成了168.95.192.1:53

**Comment by chengr28** [comment]
其实……这边的设计思想是，自带的默认配置就能比较好地在大部分的环境下获取正确的 DNS 解析结果，一般只在工作不正常的情况下采取修改，如果有空或者有兴趣也可以尝试去理解和修改配置文件，这样的，并不是说一定要修改才能用，毕竟最终的目的是 **获取正确的 DNS 解析结果** 达到目标才是最重要的。

**Comment by chengr28** [comment]
顺便 `8.8.8.8` 这个应该是伪造的服务器无误，天朝的 Google 服务器没有 DNS 的功能，距离最近的 HK 节点最低延迟就这边的反馈来看顶多也要 8ms

**Comment by chinaniupai** [comment]
@chengr28 那么请问您看我这种情况应该修改哪些选项？您是否能给个建议？我准备把这个文件恢复默认，然后根据我得情况去修改。

**Comment by chengr28** [comment]
@chengr28 这边有几个针对默认配置文件的建议，可以酌情修改：
- 如果你那边 `8.8.8.8` 有问题的话就不要用了，把 `IPv4 Main/Alternate DNS Address` 换成其它 DNS 服务器是正确的修改
- `IPv4 Main/Alternate Local DNS Address` 这个默认是 114DNS 如果工作正常就没事，但是不少人应该会换成自己 ISP 的 DNS 服务器，理论上这样的确也是正确的做法
- 重点是获取正确的解析结果，请务必先进行实际的测试，觉得有问题才分析原因修改配置文件

**Comment by chinaniupai** [comment]
@chengr28 我这里ping谷歌的IP是正确的。

**Comment by chengr28** [comment]
@chinaniupai 想要启用 DNSCrypt 加密 DNS 协议，直接修改 `DNSCurve = 1` 即可

**Comment by jzp820927** [comment]
看来你的 8.8.8.8 应该是有问题，改下 IPv4 Main/Alternate DNS Address 就行了，其他我觉得可以不用改，先测试下，能用就行了，不能用再贴出来分析，再改。

**Comment by chinaniupai** [comment]
@chengr28 我现在已经把DNSCurve = 1改了。

[Local DNS]Local Hosts是否有必要开？
[Switches]EDNS Label是否有必要开？

**Comment by chinaniupai** [comment]
@jzp820927 好的，我目前把你说的那2个改了，还开了一个DNSCrypt。然后把TCP改成了UDP。
@SeaHOH 推荐把Local Main 和 Local Routing关掉，打开Local Hosts。所以我也照做了。

**Comment by chinaniupai** [comment]
@chengr28 我修改DNSCurve = 1之后，是不是所有DNS请求都走DNSCurve IPv4 Main DNS Address = 208.67.220.220:443？

**Comment by chinaniupai** [comment]
@SeaHOH 我又仔细的看了一下发现DNSCurve是需要配置的，最后我把这个功能关了。最后只修改了
Outgoing Protocol = IPv4 + TCP
IPv4 Main /Alternate DNS Address

**Comment by jzp820927** [comment]
可以了，非标准端口 + TCP 已经很稳定了。

**Comment by chinaniupai** [comment]
@jzp820927 我感觉不加密不保险啊。唉。

**Comment by jzp820927** [comment]
DNS 就只是传输域名的解析结果，说简单点，就是几个数字而已。又不是浏览网页，有文字，有敏感词之类的。不知道你说的不保险，具体指的什么

**Comment by chinaniupai** [comment]
@jzp820927 几个数字就会让上面看到我访问了什么IP吧？如果用加密DNS的话他们应该就看不到了吧？

**Comment by chinaniupai** [comment]
@SeaHOH 嗯嗯。

**Comment by chinaniupai** [comment]
@SeaHOH @jzp820927 @chengr28 我现在用的是中华电信的DNS，你们觉得附近哪个DNS好啊？就是中国附近国家的DNS，这个中华电信我这里延迟60多，不知道你们是多少？有电信宽带的吗？ping一下呗，168.95.192.1

**Comment by jzp820927** [comment]
按照你的需求，我推荐你用 tor 吧。

**Comment by chinaniupai** [comment]
@jzp820927 我知道中华电信的DNS是普通的DNS，事实上我在寻找方法能把电脑跟DNS之间加密起来，让别人看不到我访问了哪些网站

**Comment by jzp820927** [comment]
按照你的说法，你不想别人知道你访问了什么网站，以我的理解，这就是匿名。

**Comment by chinaniupai** [comment]
@jzp820927 事实上我觉得加密可以让一些明文可能会被污染的网站没有被污染。就像网页的http和https的区别，一个可以被拦截内容，一个不会被拦截。

**Comment by SeaHOH** [comment]
@chinaniupai 
都可以拦截，只是代价不同。真的建议你不要折腾了，先用一段时间再说。

**Comment by chinaniupai** [comment]
@SeaHOH 嗯嗯。

**Comment by jzp820927** [comment]
@chinaniupai 我觉得你想的太简单了，就算 DNS 加密了，也不可能加密你要访问的服务器的目标 IP，因为数据在网络中传输，经过路由器的时候，路由器必须要知道你的数据要到达的目的地是什么，如果连 IP 都加密了，路由器根本不知道怎么传输数据。所以就算解析域名的 DNS 的数据加密了，连接服务器的时候，IP也是不可能加密的。

**Comment by chinaniupai** [comment]
@jzp820927 好吧，唉，罢了，只要能无污染就行。
