### ISSUE TITLE
请问是否可以设置指定网站用指定DNS访问？

### ISSUE THREAD

**Issue by chinaniupai** [chengr28/Pcap_DNSProxy#226]
https://acg18.us
这个网站我用Pcap_DNSProxy之后访问就进不去，但是我用223.5.5.5就能进去。
所以我想询问是否可以把这个网站指定使用223.5.5.5访问？如果可以，应该从哪个文件设置？我之前在WhiteList这个txt文件里面添加了网站但是还是进不去。

**Comment by SeaHOH** [comment]
在说明文件中查找 Dnsmasq，你会看到设置方法。

**Comment by chinaniupai** [comment]
@SeaHOH OK，好的。

**Comment by chinaniupai** [comment]
@SeaHOH 好的，谢谢

**Comment by jzp820927** [comment]
* Dnsmasq Server - Dnsmasq 兼容服务器格式
  * 要使用本功能，必须将配置文件内的 Local Hosts 选项打开！

然后在 Hosts.conf 文件里面，[Local Hosts] 下面添加
Server=/acg18.us/223.5.5.5

**Comment by SeaHOH** [comment]
这个我也没法，只能不用 Local Main 和 Local Routing，把缓存时间设置长一点减少请求次数。

**Comment by chinaniupai** [comment]
算了，就这样把，等用acg18.us的时候我再手动把dns改成223.5.5.5好了

**Comment by chengr28** [comment]
为什么想得这么复杂……直接给这个域名写个 Hosts 就好了吧

**Comment by jzp820927** [comment]
还是 C 大聪明。

**Comment by chinaniupai** [comment]
@chengr28 直接去系统的hosts里改？域名IP绑定？

**Comment by jzp820927** [comment]
Pcap_DNSProxy 的 Hosts.conf 文件，改系统 hosts 也是可以的，条条大路通罗马，自己觉得那个方法方便，就用哪个吧。
