### ISSUE TITLE
EDNS 子网地址设置疑问

### ISSUE THREAD

**Issue by SeaHOH** [chengr28/Pcap_DNSProxy#227]
@chengr28 请问：
`IPv4/6 EDNS Client Subnet Address` 选项留空时，发不发送本机地址作为 EDNS 标签？
说明里面“留空为不启用”感觉写得不明确，是只要启用了“EDNS Label”就一定会发送吗？

**Comment by chengr28** [comment]
觉得 ReadMe 说明文档写得不明确其实是因为不清楚这两者的关系……EDNS Label 是一个对 DNS 功能扩展的基础框架，用于支持更高级的 DNS 应用，而 EDNS Client Subnet 是 EDNS Label 的一个应用。这样就可以解释了：
- 这两个是不一样的东西
- 启用 `EDNS Client Subnet` 必须启用 `EDNS Label` 因为前者基于后者才能实现
- 启用 `EDNS Label` 而留空（不启用） `EDNS Client Subnet` 则不会发送任何地址到 DNS 服务器

**Comment by SeaHOH** [comment]
我发现我获取的 IP 地址并不总是在同一子网。
那么能不能添加一个自动获取本机子网地址作为 `EDNS Client Subnet` 地址发送出去的功能，这样做有没有意义？

**Comment by chengr28** [comment]
其实不太懂为什么要启用 EDNS Client Subnet……这个功能原意是设计给递归 DNS 服务器使用的，因为递归 DNS 服务器在递归请求的时候会丢失真正需要此解析的用户的地址信息，所以才需要从功能传递用户的地址。如果是自己直接去请求 DNS 服务器，那么服务器直接就能看到请求的地址，没有必要使用此功能。

**Comment by SeaHOH** [comment]
意思是递归 DNS 服务器收到含 EDNS Client Subnet 的请求会原样转发，没有则自动加上？
最终用户完全不用担心这个问题？

**Comment by chengr28** [comment]
或者换个说法吧，到底什么地方需要 EDNS Client Subnet 是个逻辑上的问题……举个例子，A 是用户，B 是中间的递归 DNS 服务器，C 是权威 DNS 服务器：
- 所有结果都需要从 C 获取，B 就是个中转站。A 向 B 发出请求（这时 B 得知 A 的地址，不需要使用 EDNS Client Subnet）；当 B 代 A 请求 C（不启用 EDNS Client Subnet 情况下）时 C 却只能得知 B 的地址而无法得知真正的请求者 A 的地址，导致这个请求得不到最好的解析结果，所以 B 到 C 这步是需要启用这个功能的，由 B 通知 C 真正的地址。由此可见 A 和 B 之间不需要做任何的处理，所以之前才会说『真正需要这个功能的是 DNS 服务器而不是用户』。
- 至于你说强行在 A 和 B 之间启用 EDNS Client Subnet 的情况下 B 会不会帮忙做转发，现在的情况应该是不会，有些甚至还需要申请（Google Public DNS）才能用……

**Comment by SeaHOH** [comment]
那么 ISP 的递归 DNS 服务器不一定可靠了，还不如使用用户较多的公共 DNS？

**Comment by chengr28** [comment]
并不，ISP 的递归 DNS 服务器和用户都在同一个 ISP 内，就是说 A 和 B 刚好在（近似）同一个网络内，实际上有没有 EDNS Client Subnet 都可以实现正确的域名解析。而公共递归 DNS 服务器不一定能在同一个 ISP 内，所以才需要此功能的帮助。

**Comment by SeaHOH** [comment]
很多公共 DNS 用的是任播而且号称智能，与一般单纯的递归服务器应该不同的吧？

**Comment by SeaHOH** [comment]
很多公共 DNS 用的是任播而且号称智能，与一般单纯的递归服务器应该不同的吧？

**Comment by chengr28** [comment]
『而公共递归 DNS 服务器 **不一定** 能在同一个 ISP 内』

**Comment by SeaHOH** [comment]
哦，看到了的。
我是说阿里之类的，不说智能吗，应该就是自己添加了 EDNS Client Subnet 吧？

**Comment by chengr28** [comment]
谁知道呢……他们自己和权威 DNS 服务器之间有没有 EDNS Client Subnet 只有他们自己知道。天朝的话好像只有 DNSPod 明确吹过自己有，其它不清楚，不过国别域名的权威 DNS 服务器好像大部分都支持了。

**Comment by SeaHOH** [comment]
我试过配置 ISP 的 DNS，但是有时候解析结果延迟很大，估计是我访问的网站太小众了（对国内来说）。
