### ISSUE TITLE
Pcap_DNSProxy Mac 版如何重启？

### ISSUE THREAD

**Issue by LisonFan** [chengr28/Pcap_DNSProxy#228]

**Comment by jzp820927** [comment]
readme 文档有说明啊。安装服务了吗？

**Comment by LisonFan** [comment]
@jzp820927 我看文档里面没说重启的方法

**Comment by LisonFan** [comment]
@jzp820927 我现在是重启 Mac 来重启 Pcap_DNSProxy

**Comment by jzp820927** [comment]
应该可以通过 systemd 控制，我在 Linux 下面是这么控制的，没有 mac 环境，你可以试试。

**Comment by LisonFan** [comment]
@jzp820927 貌似没有，刚刚查了一下

**Comment by jzp820927** [comment]
没用过 mac 系统， mac 有没有 systemd 系统吗？

**Comment by LisonFan** [comment]
刚刚试了一下，没有

**Comment by jzp820927** [comment]
那就自己写脚本控制吧

**Comment by LisonFan** [comment]
写好了
[pcap_dnsproxy.sh.zip](https://github.com/chengr28/Pcap_DNSProxy/files/907167/pcap_dnsproxy.sh.zip)

**Comment by chengr28** [comment]
刚才的更新已经给 ReadMe 说明文档加上相关的介绍了。实际上 macOS 里的 `launchctl` 是可以对服务的运行进行控制，只不过不是 `start` 和 `stop` （这两个似乎只是控制服务是否开机启动）而是 `load` 和 `unload` 这两个是可以立即启动和停止服务而无需重启的，当然脚本里用 `killall` 也是没问题的，程序本身的设计有考虑到中途被强行终止的问题，不会造成很大的影响。
