### ISSUE TITLE
编译最新源码有点问题，大概是什么原因？

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#229]
﻿### Version/使用的版本/使用的版本
最新源码

### Running Environment/运行环境/運行環境
ubuntu 16.04

### Actual/实际情况/實際情況
编译最新源码，一直弹下面的信息，大概是什么原因造成的？
[ 95%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/TransportSecurity.cpp.o
In file included from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Structure.h:23:0,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Definition.h:23,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Template.h:23,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Base.h:23,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/TransportSecurity.h:23,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/TransportSecurity.cpp:20:
/root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Platform.h:597:0: warning: "INVALID_SOCKET" redefined
  #define INVALID_SOCKET           (-1)
 ^
In file included from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Platform.h:514:0,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Structure.h:23,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Definition.h:23,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Template.h:23,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/Base.h:23,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/TransportSecurity.h:23,
                 from /root/Pcap_DNSProxy/Source/Pcap_DNSProxy/TransportSecurity.cpp:20:
/usr/local/include/pcap/pcap.h:912:0: note: this is the location of the previous definition
   #define INVALID_SOCKET -1
 ^
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)

**Comment by wongsyrone** [comment]
把第二个位置的也改成 (-1) 就行了，只是重定义

**Comment by jzp820927** [comment]
就是提示那6个源文件，全部要修改？

**Comment by chengr28** [comment]
编译每一个 `Building CXX object CMakeFiles/Pcap_DNSProxy.dir/...` 的时候都会弹，还是说只有这个 `95%` 的会弹？

**Comment by jzp820927** [comment]
每一步都有，循环弹，我把完整的编译日志发上来吧

**Comment by chengr28** [comment]
成功编译的话的确问题不大，这里是因为源代码重定义了所以编译器有提醒，不影响功能，下次更新的时候会采取一些措施。临时修复的方法是编辑 `Platform.h` 文件，直接把第 579 行删掉保存再重新编译就行。

**Comment by jzp820927** [comment]
好吧，只不过看到编译的时候，大片大片的弹出警告信息，有点蛋疼，既然不影响就算了，希望下次更新能处理下。

**Comment by wongsyrone** [comment]
我在LEDE试了一下，libpcap-1.8.1没有上面的重定义问题，估计是旧header的问题。

**Comment by chengr28** [comment]
这个应该和带的头文件有关，不同平台不同实现有可能有不同，只能通过这样的反馈来做特殊处理……例如 Windows 上是有这个的定义的

**Comment by wongsyrone** [comment]
我怀疑他的libpcap版本是旧的，先包含/usr/local/include/pcap/pcap.h，再包含Source/Pcap_DNSProxy/Platform.h，这个重定义是因为两边定义的不一致，我这边就没事，说明两边是一致的，就算是再定义一次也不会弹警告。

**Comment by wongsyrone** [comment]
你可以用
ifndef
define
endif
这个块来检查啊，不用特殊处理吧

**Comment by jzp820927** [comment]
旧header ？是指的内核头文件？还说什么，我已经都更新到最新了。

**Comment by chengr28** [comment]
@wongsyrone 然而这个就说我说的『特殊处理』哈哈……

**Comment by jzp820927** [comment]
好吧，那就坐等你特殊处理吧

**Comment by chengr28** [comment]
刚才更新的源代码应该已经修复这个问题了，感谢反馈。

**Comment by jzp820927** [comment]
好的，我空了，重新编译试试，有问题再反馈，谢谢！

**Comment by jzp820927** [comment]
非常感谢，更新源码，重新编译已经没有警告了。
另外想问一下，关于 
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
这个提示信息，是什么原因造成的？看提示是说，libcurl 没有可用的版本信息？在 /usr/local/lib 下的，应该是我自己编译的 curl。

**Comment by chengr28** [comment]
@jzp820927 这个应该是 CMake 的问题，可能是安装的时候配置有问题，可以去搜索引擎查找相关的资料。

**Comment by jzp820927** [comment]
好吧，谢谢，影响不大，我自己去查吧
