### ISSUE TITLE
请教几个正则的问题

### ISSUE THREAD

**Issue by shuangzhijinghua** [chengr28/Pcap_DNSProxy#23]
使用hosts功能。
匹配`.*\.google.com`但是除了`(r[0-9]?{2}---sn-.*)\.c\.pack\.google\.com`，怎么实现？

**Comment by chengr28** [comment]
先写 `(r[0-9]?{2}---sn-.*)\.c\.pack\.google\.com` 的 Hosts 再写 `.*\.google.com` 的 Hosts
如果直接就不想 Hosts 那个域名，参见 ReadMe 的 `Whitelist - 白名单条目` 的介绍：
`NULL (r[0-9]?{2}---sn-.*)\.c\.pack\.google\.com`

**Comment by xinhugo** [comment]
@shuangzhijinghua 

> [^x]	匹配除了x以外的任意字符

正则示例：

    .*[^c\.pack]\.google\.com

[推荐：正则表达式在线测试][1]


  [1]: http://tool.chinaz.com/regex/

**Comment by xinhugo** [comment]
@shuangzhijinghua 

匹配「www.google.com」，不匹配「google.com」：

    .*\.google\.com

同时匹配「www.google.com」、「google.com」：

    .*\bgoogle\.com

**Comment by shuangzhijinghua** [comment]
已经这样写了
`NULL r[0-9]{2}---sn-.*\.c\.pack\.google\.com`
`64.233.189.196 .*google\..*`
但是查询的时候还是返回第二条的结果。

**Comment by chengr28** [comment]
![NULL_Test](https://lh5.googleusercontent.com/-h84kZP9_NCk/VRK2zkRc97I/AAAAAAACN4s/10cbkAcjESA/w0/2015-03-25-NULL-Parameter-Domain.png)

这边测试似乎没有问题……是不是测试的域名写错了？

**Comment by shuangzhijinghua** [comment]
`NULL r[0-9]{1,2}---sn-.*\.c\.pack\.google\.com`
修改了一下，可以匹配到`r1---sn`以及`r11---sn`.
如果直接`.*\.google\.com`的话会导致这个c.pack.google.com也包括进去了，导致chrome更新失败，或者下载某些谷歌软件包的时候。

**Comment by shuangzhijinghua** [comment]
貌似就没啥问题了，这个正则的东西。
