### ISSUE TITLE
设置了Cache Paramter后DDNS解析问题

### ISSUE THREAD

**Issue by karymay** [chengr28/Pcap_DNSProxy#231]
﻿### Version/使用的版本/使用的版本

最新

### Running Environment/运行环境/運行環境

winserver 2012

### Expectation/期望情况/期望情況

是否可以设置缓存黑名单，黑名单内的采用默认TTL?

### Actual/实际情况/實際情況
设置了Default TTL为较大值（如1天），DDNS的解析就会有问题。

**Comment by chengr28** [comment]
建议参照 ReadMe 说明文档中对 `Cache Type` 和 `Cache Parameter` 和 `Default TTL` 参数的介绍，调整解析结果的缓存时间，不建议设置过长的缓存时间。

**Comment by karymay** [comment]
谢谢回复。
设置长一点,网速就显得很快。
另外还有个问题想问一下。
能够把缓存的dns(包括被访问的次数)导出来吗?因为能导出的话,就可以写点脚本搞个定时刷新DNS。
访问会很快。
谢谢!

**Comment by chengr28** [comment]
缓存时间如果设置得太长，域名改变解析结果的时候有可能会出现无法访问的问题。其实再请求一次，基本上也不差两三秒，没什么必要设置得很长，默认应该是 15 分钟的。

**Comment by SeaHOH** [comment]
我设的 4 个小时。
