### ISSUE TITLE
是否可以搭建在远程服务器上？

### ISSUE THREAD

**Issue by chinaniupai** [chengr28/Pcap_DNSProxy#232]
我想询问这个是否可以搭建在远程服务器上来让安卓和win都可以通过远程VPS来访问？

**Comment by jzp820927** [comment]
只能放在国内服务器上。

**Comment by chinaniupai** [comment]
@jzp820927 这里有人放吗？

**Comment by jzp820927** [comment]
有人放什么？

**Comment by chinaniupai** [comment]
@jzp820927 就是有没有人把这个放到了国内VPS上来给手机用

**Comment by jzp820927** [comment]
就算有人搭建了，也不会公布出来。
其实你只要在 PC 上运行起来，只要手机和PC在一个网段，照样可以用

**Comment by chinaniupai** [comment]
@jzp820927 没在一个网段，因为路由器是百兆网口，限制了我的宽带速度，所以我从光猫弄了2个网线，光猫的lan1弄网线插电脑上，lan2弄网线插在了路由器上。所以明显不在一个网段= =

**Comment by jzp820927** [comment]
不好意思，我说错了，不在一个网段也可以用，只要能互相 ping 通，就行了。

**Comment by chinaniupai** [comment]
@jzp820927 假如ping同了，那手机该怎么设置？DNS设置127.0.0.1？

**Comment by jzp820927** [comment]
你别给我说，你拉的是 千兆 宽带？百兆口还不够你用？

**Comment by chinaniupai** [comment]
@jzp820927 100兆联通下载速度15MB，插上路由器只有12MB。3MB我说不要就不要了？

**Comment by jzp820927** [comment]
好吧，你那儿的宽带，还有超额，太牛B了，我也算联通算了，这么大福利。

**Comment by chinaniupai** [comment]
@jzp820927 ping不通，呜呜呜

**Comment by jzp820927** [comment]
我不知道你的网络上怎么接的，你的 PC 和 手机 是分别接在猫上的 2个 网口上的麽？

**Comment by chinaniupai** [comment]
@jzp820927 PC是直接接在猫的，路由器也是直接接在毛的，但问题是路由器有自己的DHCP的IP池，2个独立IP的

**Comment by chinaniupai** [comment]
@jzp820927 不过我准备把光猫改回桥接，然后把网线接在路由器上了

**Comment by chinaniupai** [comment]
@jzp820927 我想知道如果能ping通，那我手机的DNS该写什么？127.0.0.1？还是电脑的内网IP？

**Comment by jzp820927** [comment]
就是你运行 DNS 程序的那台电脑的 IP

**Comment by chengr28** [comment]
本程序（默认配置）实际上就是在本地实现一个类似 DNS 服务器的功能，如果问能不能搭在公网上，那是肯定可以的，只是有几点需要注意：
- 在公网上的公认端口开服务是非常危险的行为
- 如果需要给其它不在内网网段的设备提供解析服务，参见 `Operation Mode` 参数的说明
- 在内网网段内只要两个设备可以直接连接，那么提供域名解析也是没问题的
- DNS 地址填提供 DNS 服务的设备的 IP 地址
- 网络架构的问题不在本项目的讨论范围，请自行进行研究

**Comment by chinaniupai** [comment]
@jzp820927 我刚刚用电脑ping了一下手机的IP发现100多延迟甚至还有丢包这个正常么？我是TP-LINK WR886N的路由器。

**Comment by chinaniupai** [comment]
@chengr28 请问为何在公网上的公认端口开服务是非常危险的行为？会被黑客入侵吗？
我把我的电脑从路由器上设置绑定了DMZ主机是不是很危险？

**Comment by jzp820927** [comment]
100多延迟？是无线连接嘛？是不是信号不好？
公认端口会被大量扫描机扫描。

**Comment by chinaniupai** [comment]
@jzp820927 路由器，电脑跟手机都在附近啊，电脑是线连，手机是无线，ping手机100多延迟，甚至有丢包。

**Comment by chinaniupai** [comment]
![image](https://cloud.githubusercontent.com/assets/26068235/25527253/8aff64de-2c4a-11e7-832c-aebdedd0721a.png)

**Comment by chinaniupai** [comment]
@jzp820927 因为我有比特彗星，utorrent，btsync这种软件。所以绑定端口要一大堆，我就直接弄DMZ了。
请问您说的会被大量扫描机扫描，这种扫描是谁进行的？

**Comment by jzp820927** [comment]
肯定是黑客来扫描你了，不过上面也说了，是公认端口，utorrent，btsync，这些用的不是公认端口，所以影响不大，不过你要运行 DNS 的话，那就是公认端口了。

**Comment by chinaniupai** [comment]
@jzp820927 那我是否应该取消DMZ主机然后去开放虚拟端口？

**Comment by chengr28** [comment]
这些 P2P 不都有 UPnP 之类可以自动进行端口映射的配置嘛……正如 @jzp820927 所说，就像在公共网络打开 53 端口并且提供 DNS 服务，那么一旦被那些肉鸡扫描机扫到，黑客入侵事小，被成百上千的机器疯狂请求导致连接数爆炸网络瘫痪才是大问题……

**Comment by jzp820927** [comment]
能关闭 DMZ 就尽量关闭吧。
延时和 DMZ 没什么关系，应该是你网络的问题，你可以试试，把 PC 和手机接在路由器下面一个网段内，再ping 一下看看延时
至于 家用的普通宽带也会有黑客来扫描？这个说不准，如果你不是很在意网络安全性的话，其实也可以不用太在意，比较普通人的机子，对黑客来说，意义不大，被攻击的可能性较小。只要你接外网的设备没有什么太明显的漏洞就行了。

**Comment by chengr28** [comment]
@jzp820927 扫描机器一扫都是整个 IPv4 地址空间地扫，不可能扫不到的……这个和 IP 地址是谁在用没什么关系

**Comment by chinaniupai** [comment]
@chengr28 但我如果不端口映射或者不DMZ，就会提示我端口阻塞，我这个路由器可能没有UPnP功能？TP-LINK WR886N。

**Comment by chinaniupai** [comment]
@jzp820927 192.168.1.100跟192.168.1.101是一个网段吧？

**Comment by SeaHOH** [comment]
全扫又不麻烦，顺便咯，有洞就搞。

**Comment by jzp820927** [comment]
是一个网段，自己怎么用方便就怎么用吧，反正这么多大神都给你意见了，自己考虑吧。

**Comment by chinaniupai** [comment]
😂
