### ISSUE TITLE
请问为何使用本软件可以无污染？

### ISSUE THREAD

**Issue by chinaniupai** [chengr28/Pcap_DNSProxy#234]
﻿默认文件是UDP模式，为何也可以无污染？

**Comment by chinaniupai** [comment]
@jzp820927 @SeaHOH

**Comment by jzp820927** [comment]
因为用了 非标准端口

**Comment by SeaHOH** [comment]
因为默认使用抓包模块，而不是从正常顺序获取返回结果。

**Comment by chinaniupai** [comment]
@jzp820927 非标准端口是给opendns用的把，谷歌dns没有非标准端口吧？而且我那个是改成了台湾中华电信的DNS。

**Comment by chinaniupai** [comment]
@SeaHOH 抓包模块和正常顺序获得返回结果有什么区别？国外的【标准53端口】DNS只要经过墙不就直接污染吗？我对这个抓包模块不是很了解

**Comment by jzp820927** [comment]
Pcap_DNSProxy 有很多种组合配置，都能防污染，如果你没用非标准端口，那就是抓包起作用了。通过转包，把污染包丢掉就行了。

**Comment by chinaniupai** [comment]
@jzp820927 也就是说正常境外DNS会给你发送正确的IP，但是墙也会给你发个假的IP来让你正确的IP失效？这个抓包工具就可以过滤掉墙发来的假数据包，让真正的数据包生效？

**Comment by jzp820927** [comment]
是的，GFW 会赶在正确 DNS 包之前，发送一个污染包，客户端接收 DNS 包的默认规则是，哪个包先到就接受哪个，后面的就不管了。所以你就会收到污染包了。

**Comment by chengr28** [comment]
就像楼上各位所说，普通的协议栈没有鉴别 DNS 解析结果真假的能力，本身 DNS 也是一个没有加密和几乎没有验证的协议，被 GFW 强插其实也是正常现象。至于为什么本程序可以避免这些问题……方法有很多，可以根据一些规则对数据包过滤，也可以使用没有被投毒污染的途径获取解析结果等等……

**Comment by chinaniupai** [comment]
@chengr28 感谢各位制作了这个项目来造福广大网友。
