### ISSUE TITLE
请问大家是否知道DNS污染的网站？

### ISSUE THREAD

**Issue by chinaniupai** [chengr28/Pcap_DNSProxy#235]
﻿今天跟朋友推荐这个，可是他觉得没啥用，所以我想请问：谁知道被DNS污染但是没有被封IP的网站。跟他证明一下这个的作用。

**Comment by chinaniupai** [comment]
@chengr28 @jzp820927 @SeaHOH

**Comment by chengr28** [comment]
https://zh.wikipedia.org

**Comment by chinaniupai** [comment]
@chengr28 感谢，请问还有其他的吗？

**Comment by jzp820927** [comment]
只要支持 https 的，一大半都可以，不可能一个一个给你列出来，你自己浏览器测试一下就知道了。

**Comment by chinaniupai** [comment]
@jzp820927 能不能给我列出来2个？2个就够了，

**Comment by jzp820927** [comment]
https://instagram.com
https://www.tumblr.com
https://zh.wikipedia.org

**Comment by chinaniupai** [comment]
@jzp820927 谢谢啦，
