### ISSUE TITLE
请问如何访问特定网页下强制ipv4？

### ISSUE THREAD

**Issue by LiuZHolmes** [chengr28/Pcap_DNSProxy#236]
﻿### Version/使用的版本/使用的版本
0.4.8.4

### Running Environment/运行环境/運行環境
Win10 64位
Chrome

### Expectation/期望情况/期望情況
访问某些网页如火猫，sublimetext的下载网页时应该正常访问

### Actual/实际情况/實際情況
实际上由于ipv6地址优先解析，会去访问它的ipv6地址，而有一些ipv6的地址应该是有问题的，比如上面的两个例子（能解析，但ping超时）。但是ipv4确实没有问题的，由于解析没有问题所以好像无法自动换ipv4，就算换也要等挺久。不知道要怎么改config？

**Comment by jzp820927** [comment]
难道你是教育网？

**Comment by LiuZHolmes** [comment]
是的

**Comment by jzp820927** [comment]
有个简单的办法，就是对这个少部分域名，直接指定 IPV4 的 hosts。

**Comment by LiuZHolmes** [comment]
可以问下具体是在哪里操作吗（xd

**Comment by chengr28** [comment]
关于屏蔽域名的部分类型解析结果的方法，其实 ReadMe 文档里有说明。
本问题的情况可以把 IPv6（AAAA）屏蔽掉以实现此效果，节选一段：
```
* Banned Extended - 黑名单条目扩展功能
  * 有效参数格式为 "BANNED:DNS类型(|DNS类型) 正则表达式"（不含引号，括号内为可选项目）
  * 只允许特定类型域名请求，有效参数格式为 "BANNED(Permit):DNS类型(|DNS类型) 正则表达式"（不含引号，括号内为可选项目）

    BANNED:A|AAAA .*\.test\.test
    BANNED(Permit):NS|SOA .*\.test

  * 第一条即屏蔽匹配规则的 A 记录和 AAAA 记录的域名请求，其它类型的请求则被放行
  * 而第二条则只放行匹配规则的 NS 记录和 SOA 记录的域名请求，其它类型的请求则被屏蔽
```

**Comment by chengr28** [comment]
@jzp820927 这个情况编译 IPv4 的 Hosts 应该不能解决问题，因为如果系统是 IPv6 优先而且存在可用的 IPv6 的网关，那么系统照样会去请求和使用 IPv6 协议，IPv4 会被完全跳过。

**Comment by jzp820927** [comment]
好吧，我以为 hosts 的优先级应该比 DNS 高。是我搞错了。
（对了，说明一下，我 4 楼说的 hosts 是指的 Pcap_DNSProxy 的 hosts 功能，不是 windows 的 C:\Windows\System32\drivers\etc\hosts ）

**Comment by chengr28** [comment]
@jzp820927 这个和 DNS 没有关系，Windows 系统默认 IPv6 优先级比较高，所以会第一时间尝试使用。但是现阶段一般 IPv6 都没有网关，或者 IPv6 解析不出这个域名，这样就没法用了，才会尝试使用 IPv4，才会去尝试 IPv4 解析，所以写 IPv4 的 Hosts 是没有用的。

**Comment by SeaHOH** [comment]
有没有类似 bogus-nxdomain 的功能？直接放弃这个 v6 IP 的解析。

**Comment by chengr28** [comment]
@SeaHOH `IPFilter.ini` 里有 `[Blacklist]` 标签，可以屏蔽所有含有某个 IP 地址的解析结果

**Comment by SeaHOH** [comment]
管用，这样就可以解决楼主的难题了。

**Comment by LiuZHolmes** [comment]
谢谢大神，就是用BANNED: AAAA 的方法解决的。

**Comment by SeaHOH** [comment]
哦，刚才没仔细看 c 大的解答，还以为在讲解自定义 hosts。 :trollface:

**Comment by SugarPP** [comment]
可以在前缀策略中优先使用 IPv4 over IPv6，这样访问网站时会优先访问网站的ipv4网址，这样就可以解决问题了。具体看微软官方的说明[https://support.microsoft.com/zh-cn/help/929852/guidance-for-configuring-ipv6-in-windows-for-advanced-users](url)

**Comment by AnyWAT** [comment]
😱有鬼怪，左键或右键点击楼上链接，都跑到 https://github.com/chengr28/Pcap_DNSProxy/issues/url
