### ISSUE TITLE
Indonesia's local routing with enabled dns curve failed isp's dns interception

### ISSUE THREAD

**Issue by trippleflux** [chengr28/Pcap_DNSProxy#237]
﻿### Version/使用的版本/使用的版本
c42865d1d2f397c5279ae923e343952debb818cb
Compiled with Visual Studio 2017

### Running Environment/运行环境/運行環境
Windows 10 Enterprise Creator Update
Updated Routing.txt for indonesia list with edited Update.bat : 
type ".\latest\%DALmd5%.md5"|findstr ipv%1|findstr ID>"%temp%\#listipv%1#"

### Expectation/期望情况/期望情況
Local Routing with Routing.txt filled with Indonesia's IP subnet routing working without ISP's(Indonesia telecom) interception of DNS with dns curve

### Actual/实际情况/實際情況
Pcap_DNSProxy with local routing failed to prevent my isp dns interception even tough dns curve (cisco) is ON
My config : 
```
[Base]
Version = 0.45
File Refresh Time = 15
Large Buffer Size = 4096
Additional Path = 
Hosts File Name = Hosts.ini|Hosts.conf|Hosts|Hosts.txt|WhiteList.txt|White_List.txt
IPFilter File Name = IPFilter.ini|IPFilter.conf|IPFilter.dat|Routing.txt|chnrouting.txt|chnroute.txt

[Log]
Print Log Level = 3
Log Maximum Size = 8MB

[Listen]
Pcap Capture = 1
Pcap Devices Blacklist = AnyConnect|Host|Hyper|ISATAP|IKE|L2TP|Only|Oracle|PPTP|Pseudo|Teredo|Tunnel|Virtual|VMNet|VMware|VPN|any|gif|lo|stf|utun
Pcap Reading Timeout = 250
Listen Protocol = IPv6 + IPv4 + TCP + UDP
Listen Port = 53
Operation Mode = Private
IPFilter Type = Deny
IPFilter Level < 0
Accept Type = 

[DNS]
Outgoing Protocol = IPv4 + UDP
Direct Request = 0
Cache Type = Timer + Queue
Cache Parameter = 128
Default TTL = 900

[Local DNS]
Local Protocol = IPv4 + UDP
Local Force Request = 0
Local Hosts = 0
Local Main = 1
Local Routing = 1

[Addresses]
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 
IPv4 Main DNS Address = 8.8.4.4:53
IPv4 Alternate DNS Address = 8.8.8.8:53|208.67.220.220:443|208.67.222.222:5353
IPv4 Local Main DNS Address = 114.114.115.115:53
IPv4 Local Alternate DNS Address = 223.6.6.6:53
IPv6 Listen Address = 
IPv6 EDNS Client Subnet Address = 
IPv6 Main DNS Address = [2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = [2001:4860:4860::8888]:53|[2620:0:CCD::2]:443|[2620:0:CCC::2]:5353
IPv6 Local Main DNS Address = 
IPv6 Local Alternate DNS Address = 

[Values]
Thread Pool Base Number = 0
Thread Pool Maximum Number = 128
Thread Pool Reset Time = 120
Queue Limits Reset Time = 0
EDNS Payload Size = 1220
IPv4 Packet TTL = 32 - 255
IPv4 Main DNS TTL = 0
IPv4 Alternate DNS TTL = 0
IPv6 Packet Hop Limits = 32 - 255
IPv6 Main DNS Hop Limits = 0
IPv6 Alternate DNS Hop Limits = 0
Hop Limits Fluctuation = 2
Reliable Once Socket Timeout = 3000
Reliable Serial Socket Timeout = 1500
Unreliable Once Socket Timeout = 2000
Unreliable Serial Socket Timeout = 1000
TCP Fast Open = 0
Receive Waiting = 0
ICMP Test = 900
Domain Test = 900
Alternate Times = 10
Alternate Time Range = 60
Alternate Reset Time = 300
Multiple Request Times = 0

[Switches]
Domain Case Conversion = 1
Compression Pointer Mutation = 0
EDNS Label = 0
EDNS Client Subnet Relay = 0
DNSSEC Request = 0
DNSSEC Validation = 0
DNSSEC Force Validation = 0
Alternate Multiple Request = 0
IPv4 Do Not Fragment = 0
IPv4 Data Filter = 0
TCP Data Filter = 1
DNS Data Filter = 1
Blacklist Filter = 1
Strict Resource Record TTL Filter = 0

[Data]
ICMP ID = 
ICMP Sequence = 
ICMP PaddingData = 
Domain Test ID = 
Domain Test Data = 
Local Machine Server Name = 

[Proxy]
SOCKS Proxy = 0
SOCKS Version = 5
SOCKS Protocol = IPv4 + TCP
SOCKS UDP No Handshake = 1
SOCKS Proxy Only = 0
SOCKS IPv4 Address = 127.0.0.1:1080
SOCKS IPv6 Address = [::1]:1080
SOCKS Target Server = 8.8.4.4:53
SOCKS Username = 
SOCKS Password = 
HTTP CONNECT Proxy = 0
HTTP CONNECT Protocol = IPv4
HTTP CONNECT Proxy Only = 0
HTTP CONNECT IPv4 Address = 127.0.0.1:1080
HTTP CONNECT IPv6 Address = [::1]:1080
HTTP CONNECT Target Server = 8.8.4.4:53
HTTP CONNECT TLS Handshake = 0
HTTP CONNECT TLS Version = 0
HTTP CONNECT TLS Validation = 1
HTTP CONNECT TLS Server Name Indication = 
HTTP CONNECT TLS ALPN = 0
HTTP CONNECT Version = 1.1
HTTP CONNECT Header Field = User-Agent: Pcap_DNSProxy/0.4.5.0
HTTP CONNECT Header Field = Accept: */*
HTTP CONNECT Header Field = Cache-Control: no-cache
HTTP CONNECT Header Field = Pragma: no-cache
HTTP CONNECT Proxy Authorization = 

[DNSCurve]
DNSCurve = 1
DNSCurve Protocol = IPv4 + UDP
DNSCurve Payload Size = 512
DNSCurve Reliable Socket Timeout = 3000
DNSCurve Unreliable Socket Timeout = 2000
DNSCurve Encryption = 1
DNSCurve Encryption Only = 0
DNSCurve Client Ephemeral Key = 0
DNSCurve Key Recheck Time = 1800

[DNSCurve Database]
DNSCurve Database Name = dnscrypt-resolvers.csv
DNSCurve Database IPv4 Main DNS = cisco
DNSCurve Database IPv4 Alternate DNS = 
DNSCurve Database IPv6 Main DNS = cisco-ipv6
DNSCurve Database IPv6 Alternate DNS = 

[DNSCurve Addresses]
DNSCurve IPv4 Main DNS Address = 208.67.220.220:443
DNSCurve IPv4 Alternate DNS Address = 
DNSCurve IPv6 Main DNS Address = [2620:0:CCC::2]:443
DNSCurve IPv6 Alternate DNS Address = 
DNSCurve IPv4 Main Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv4 Alternate Provider Name = 
DNSCurve IPv6 Main Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv6 Alternate Provider Name = 

[DNSCurve Keys]
DNSCurve Client Public Key = 
DNSCurve Client Secret Key = 
DNSCurve IPv4 Main DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
DNSCurve IPv4 Alternate DNS Public Key = 
DNSCurve IPv6 Main DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
DNSCurve IPv6 Alternate DNS Public Key = 
DNSCurve IPv4 Main DNS Fingerprint = 
DNSCurve IPv4 Alternate DNS Fingerprint = 
DNSCurve IPv6 Main DNS Fingerprint = 
DNSCurve IPv6 Alternate DNS Fingerprint = 

[DNSCurve Magic Number]
DNSCurve IPv4 Main Receive Magic Number = 
DNSCurve IPv4 Alternate Receive Magic Number = 
DNSCurve IPv6 Main Receive Magic Number = 
DNSCurve IPv6 Alternate Receive Magic Number = 
DNSCurve IPv4 Main DNS Magic Number = 
DNSCurve IPv4 Alternate DNS Magic Number = 
DNSCurve IPv6 Main DNS Magic Number = 
DNSCurve IPv6 Alternate DNS Magic Number = 

```

**Comment by jzp820927** [comment]
try
DNSCurve Protocol = IPv4 + TCP

**Comment by chinaniupai** [comment]
@jzp820927 楼主是老外？

**Comment by jzp820927** [comment]
不知道，也不确定。

**Comment by chinaniupai** [comment]
@jzp820927 好吧

**Comment by trippleflux** [comment]
@jzp820927 Thanks for the reply, the same thing happened with IPv4 + TCP :(

@chinaniupai Yup, i am indonesian, couldnot speak mandarin or hokian :/, but i have some chinese friends in here, they are cool and great.

**Comment by jzp820927** [comment]
i am sorry,i couldnot speak english too,i think you can use Google Translate
https://translate.google.com/

**Comment by trippleflux** [comment]
@jzp820927 It is quite hard to do technical translation using automated service such as google translate :(.

**Comment by jzp820927** [comment]
have error log?

**Comment by trippleflux** [comment]
It's nothing on the error log hmm.
![dns](https://cloud.githubusercontent.com/assets/1216215/25797147/42097d64-3406-11e7-82bf-ccd534073592.png)

**Comment by chinaniupai** [comment]
@trippleflux Local Routing=Their own computer，IPv4 + UDP=OK。No need to control it

**Comment by chinaniupai** [comment]
@chengr28

**Comment by chengr28** [comment]
I'm not very clearly to understand your problem. Do you mean that Local Routing is not working, or DNSCurve protocol has been blocked in Indonesia? The process of `Local Main + Local Routing` is:

- All DNS query will first send to local DNS which specifies in config file.
- Local DNS replies the result.
- Pcap_DNSProxy will scan the result and accept it when it's matched with routing list.
- Or Pcap_DNSProxy will drop this result and continue to the next step(DNSCurve or others..)

So you can try to change `IPv4 Local Main DNS Address` and `IPv4 Local Alternate DNS Address` to your Indonesia ISP DNS servers (114 and 223 DNS are popular local DNS servers in China mainland, may be they cannot working well in overseas) and restart the program, thanks.

**Comment by chengr28** [comment]
@trippleflux There is another point that you should change your system DNS settings from DHCP to `::1` or `127.0.0.1` to let Pcap_DNSProxy receive all DNS request.

**Comment by trippleflux** [comment]
@chengr28 
In indonesia, indonesia telecom specifically interfering/intercepting all DNS request to port 53, whether it's google DNS, cisco, etc. What i have meant it, local DNS request to remote DNS server is mangled/intercepted with their own dns's block list, without dns curve in place it will be useless to access those 'forbidden' sites.

What i have found with Pcap_DNSProxy are : 
* Local routing with indonesia's subnet filled in is preventing dns curve to working properly, i meant, remote dns request always get intercepted :(.
* Empty or foreign (not indonesia's subnet) Routing.txt makes dns curve working properly.

What i understand from Local Routing is to fastening the dns request to local sites? in my case indonesia's sites.

If that's the case (Local Routing is made to fastening the local site's request) how to make Pcap_DNSProxy only make request to through dnscurve without excluding Indonesia's Local Routing

**Comment by chengr28** [comment]
@trippleflux It's very easy to do this: Modify config file, change `Local Main` and `Local Routing` from `1` to `0` and restart the program to shutdown this module. After shutting down, all request will send to DNSCurve server.

`Local Routing` is designed to match website provider CDN. In some case, we will get foreign addresses(These addresses usually slow) when requesting foreign DNS and we will get local addresses(These addresses usually very fast) when requesting ISP DNS.
