### ISSUE TITLE
请问能否做个"解析记录"的功能

### ISSUE THREAD

**Issue by sjhgithub** [chengr28/Pcap_DNSProxy#239]
﻿### Version/使用的版本/使用的版本
新版

### Running Environment/运行环境/運行環境
windows 7

### Expectation/期望情况/期望情況
做个选项,能够记录解析过的每个域名以及对应的ip地址,可以设置条件
1.每次都记录
2.只记录解析结果为不同ip或不同域名

### Actual/实际情况/實際情況
没发现该功能

**Comment by jzp820927** [comment]
这个不就是日志功能麽？看了下稳定，目前好像只能输出错误任何，解析记录好像还没有进入日志。

**Comment by wongsyrone** [comment]
这个像是dnsmasq的记录dns请求的功能，不过个人感觉没什么用

**Comment by jzp820927** [comment]
可能 debug 的时候，有点用，平时确实没啥用。

**Comment by chengr28** [comment]
很久以前有人提到过类似的功能，然而并没有什么有力的理据说明这个功能有实际的用途……

**Comment by chinaniupai** [comment]
@chengr28 其实我也支持做个这个功能，要是说用途的话，也就是用来看网站的IP地址吧。

**Comment by jzp820927** [comment]
cmd 下面 nslookup 域名，回车，就可以看到 IP地址了

**Comment by chinaniupai** [comment]
@jzp820927 cmd 下面 nslookup 域名这样无法看到调用的DNS地址吧？

**Comment by chinaniupai** [comment]
我该如何知道他是用的谷歌DNS呢，还是用的opendns呢？

**Comment by jzp820927** [comment]
这个是 Pcap_DNSProxy 根据规则，在程序内部处理的，只有 Pcap_DNSProxy 自动

**Comment by chinaniupai** [comment]
@jzp820927 我没提问，我只是说支持做一个这样的工具，并且把这个工具的功能详细的说了出来。你上面不是说日志功能吗？然后我说做一个类似于SS这样的小程序，打开这个程序就可以弹出窗口显示各种解析结果。网站域名+网站IP+调用的DNS地址，不过这个程序应该肯定是跟Pcap_DNSProxy配套的，毕竟DNS解析是在程序内部处理的。

**Comment by chengr28** [comment]
@chinaniupai 实际上想观察程序的网络行为，可以使用 Wireshark 之类的工具对流量进行分析，所以这个功能，更像是为了满足好奇心而要加的。

**Comment by SeaHOH** [comment]
记得 DnsForwarder 会输出解析结果到控制台，不过感觉没啥用。
这是开发者才关心的问题吧，看结果是否符合设计预期。

**Comment by chinaniupai** [comment]
@chengr28 嘿嘿.....

**Comment by sjhgithub** [comment]
没事,我自己改代码实现了.
