### ISSUE TITLE
OpenService 失败 1060

### ISSUE THREAD

**Issue by lxingh** [chengr28/Pcap_DNSProxy#24]
[SC] OpenService 失败 1060:

指定的服务未安装。

[SC] OpenService 失败 1060:

指定的服务未安装。

[SC] CreateService 成功
操作成功完成。
操作成功完成。
[SC] ChangeServiceConfig2 成功
[SC] ChangeServiceConfig2 成功

SERVICE_NAME: PcapDNSProxyService
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 6308
        FLAGS              :

Windows IP 配置

已成功刷新 DNS 解析缓存。

请按任意键继续. . .
============================================================
系统win7 x64, 以管理员身份运行 ServiceControl.bat  选择1: Install service,出现上面的错误,
OpenService 是什么服务?

 以管理员身份运行 ServiceControl.bat ,选择3: Start service,出现下面的错误:
=============================================================
[SC] StartService 失败 1056:

服务的实例已在运行中。

Windows IP 配置

已成功刷新 DNS 解析缓存。

请按任意键继续. . .

**Comment by chengr28** [comment]
上面这个不是错误……这些：
`[SC] CreateService 成功`
`操作成功完成。`
`[SC] ChangeServiceConfig2 成功`
`服务的实例已在运行中。`
都说明其实服务已经成功运行了，测试的方法是在 cmd 里 nslookup www.google.com 127.0.0.1（Google 那个域名随便换都行）有回应可以成功解析就是部署成功的意思。更多详细情况参见 ReadMe 文档内 `正常工作查看方法` 一节的说明
