### ISSUE TITLE
Pcap_DNSProxy 自动停止

### ISSUE THREAD

**Issue by ZeroClover** [chengr28/Pcap_DNSProxy#241]
运行于 CentOS 6.9 x64

阿里云 ECS VPC 机型

已经移除了 `/etc/modprobe.d` 中对 IPv6 的禁用

Pcap_DNSProxy  版本为 0.4.8.7（配置文件仍然写的是 0.4.5）

错误描述：

运行 Pcap_DNSProxy 后数秒内就会自动停止，Error.log 中无错误输出

使用 dmesg 查看得到以下错误日志

```
Pcap_DNSProxy[4831]: segfault at 9 ip 000000000045b001 sp 00007f0923f7e9f0 error 4 in Pcap_DNSProxy[400000+ae000]
Pcap_DNSProxy[5583]: segfault at 47 ip 000000000045b001 sp 00007f87993809f0 error 4 in Pcap_DNSProxy[400000+ae000]
```

使用 addr2line 对以上日志中的错误区域进行分析未得到结果

```
[root@DNS Pcap_DNSProxy]# addr2line -e Pcap_DNSProxy 00007f0923f7e9f0
??:0
[root@DNS Pcap_DNSProxy]# addr2line -e Pcap_DNSProxy 00007f0923f7e9f0
??:0
[root@DNS Pcap_DNSProxy]# addr2line -e Pcap_DNSProxy 00007f87993809f0
??:0
[root@DNS Pcap_DNSProxy]# addr2line -e Pcap_DNSProxy 000000000045b001
??:0
```

配置文件使用默认也存在此问题

**Comment by wongsyrone** [comment]
为啥用老版本，试试0.4.8.7

**Comment by wongsyrone** [comment]
因为编译的时候没加调试符号，所以读不到行数，另外由于有编译器优化，就算是有行数，也不一定是精确的。

**Comment by wongsyrone** [comment]
有条件试一下历史版本，看看是否有可以正常用的，另外贴出配置文件

**Comment by ZeroClover** [comment]
@wongsyrone 是最新版本，因为配置文件写的 0.4.5 所以没注意。实际上是 0.4.8.7 的

默认配置文件也会这样

**Comment by wongsyrone** [comment]
配置文件版本和程序版本不是一回事

**Comment by chengr28** [comment]
看样子像是内存越界的问题，不过这类问题一般定位比较困难……或者可以：
- 先试试最新版本，编译的时候 `./CMake_Build.sh --disable-libsodium --disable-tls --disable-libpcap` 排除第三方库的影响，然后设置 `Direct Request = 1` 看看。
- 或者如 LS 所说可以挑一些历史版本试试看哪个版本开始出问题，之前的都没有问题……这样。

**Comment by chengr28** [comment]
如果还有问题，可以直接再回复，这边都会一直有对 Issue 的跟踪，谢谢。
