### ISSUE TITLE
任务管理器可以看到进程，但还是提示错误，没找到进程

### ISSUE THREAD

**Issue by theratlesnake** [chengr28/Pcap_DNSProxy#242]
软件版本最新的0.4.8.8，运行在win7 64位上，我重启电脑，可以看到进程“Pcap_DNSProxy.exe”随机启动并在任务管理器里，但是刷新服务的时候，会提示一行错误：没有找到进程“Pcap_DNSProxy.exe”，第一次选择安装服务的时候，也提示过这错误。

用nslookup 命令检测www.google.com 可以显示正常的状态，不过检查facebook要运行几次这个命令才行，偶尔会提示timeout，，不知道那个报错会不会有什么影响呢？

**Comment by theratlesnake** [comment]
![2345 20170516010552](https://cloud.githubusercontent.com/assets/24611087/26069566/e6be1d06-39d3-11e7-8066-eda47f975b0f.jpg)
那个google的字变形了，还有timeout

**Comment by LisonFan** [comment]
关于字体大小写随机的问题你需要看一下文档

**Comment by LisonFan** [comment]
找到 `Domain Case Conversion` 并将参数修改成 `0` 即可

**Comment by theratlesnake** [comment]
再请问下，我如果用VPN的话，direct request设置成ipv4，如果不用VPN 了，要不要把direct request改回0？

**Comment by LisonFan** [comment]
@theratlesnake 
这个不清楚

**Comment by jzp820927** [comment]
不用 VPN 的时候，改之前是什么值，还原成之前的值就可以了。

**Comment by chengr28** [comment]
- 使用服务控制脚本出现诸如『没有找到进程』是因为进行安装或卸载之类的动作，会使用系统的任务管理工具进行确认，确保进程不在运行中，只要后续能解析域名就表示没有问题。
- 偶尔会提示 timeout 是因为工具获取域名解析的流程比较长，在没有缓存的情况下需要的时间比较多，而系统自带 `nslookup` 默认超时时间为 2 秒，所以有时会有类似的提示。实际上系统协议栈的 DNS 超时时间是这个时间长度的几倍，基本不用担心这个问题。
- 域名大小写混合是本程序的一个功能，默认开启，由 `Domain Case Conversion` 参数控制。
- 关于使用系统路由级别代理相关的问题，说明文档有相关的介绍。当然大部分 VPN 的网络适配器都自带有 DNS 配置，程序的配置一般不适用于 VPN，所以实际上直接不管让程序一直在后台运行是比较好的处理方法。

**Comment by 19910703** [comment]
@chengr28  Domain Case Conversion在哪里

**Comment by chengr28** [comment]
@19910703 配置文件里的参数
