### ISSUE TITLE
请问是否可以支持HOSTS和SNI服务器？

### ISSUE THREAD

**Issue by chinaniupai** [chengr28/Pcap_DNSProxy#244]
在github上看到了另外一个DNS工具，是一个可以上google的，他的DNS工具支持SNI服务器和hosts文件，把hosts文件的链接引导了racaljk的hosts文件上。SNI服务器的IP是219开头的。如果咱们的工具开发了这2个功能的话，是不是也可以上google了？

**Comment by jzp820927** [comment]
这个只是软件，那个是服务，不是同一个概念。

**Comment by chinaniupai** [comment]
@jzp820927 好吧。不过我在电脑的hosts文件里把那个SNI服务器跟www.google.com绑定到一起，发现可以上谷歌了

**Comment by chengr28** [comment]
完全不清楚说的是什么，实际上这是把几个概念混淆在一起了……那个项目实际是提供了一个 Hosts 文件，使用这个 Hosts 文件能访问一些不能直接访问的网站而已，这个 Issue 就像在问本项目支不支持 Hosts 功能一样……
至于 TLS SNI 是什么，请先去了解一下 https://zh.wikipedia.org/zh-hans/%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%90%8D%E7%A7%B0%E6%8C%87%E7%A4%BA 这个功能和 DNS 一点关系都没有，只是为了解决单地址多证书问题的一个方案而已。那个项目说支持的意思是，他们提供的 Hosts 文件中某些域名所指向的地址支持这个功能，所以可以把各种各样同一间公司的域名都解析到同一个地址的意思而已。

**Comment by chinaniupai** [comment]
@chengr28 感谢解答，好多翻墙DNS都说什么SNI代理，请问咱们这个项目以后是否会支持连接谷歌呢？

**Comment by SeaHOH** [comment]
>Pcap_DNSProxy 是一个基于 WinPcap/LibPcap 用于过滤 DNS 投毒污染的工具，提供便捷和强大的包含正则表达式的修改 Hosts 的方法，以及对 DNSCurve/DNSCrypt 协议、并行和 TCP 协议请求的支持。多服务器并行请求功能，更可提高在恶劣网络环境下域名解析的可靠性

来自项目首页

**Comment by chengr28** [comment]
@chinaniupai 不会添加任何此类功能，这不是本项目所涉及的范围。

**Comment by jzp820927** [comment]
@chinaniupai 你想的太多了，你的想法，就好像在 4S 店里面买车，然后你问卖车的，你们能不能再提供代驾服务一样。

**Comment by chinaniupai** [comment]
@chengr28 好的，明白了。我还有一个疑问，是否拥有SS之后Pcap_DNSProxy这个工具就没用了？

**Comment by SeaHOH** [comment]
工具就是工具，本身的用途也有介绍说明，有没有用不是听别人说，而是你自己怎么用，自己决定的。

**Comment by chinaniupai** [comment]
嗯，感谢各位哈。
