### ISSUE TITLE
请问linux下编译完成之后，目标程序是哪个

### ISSUE THREAD

**Issue by huaxianyan** [chengr28/Pcap_DNSProxy#245]
我知道这个问题非常蠢……

但是我还是要问一问

版本0.4.8.8，ubuntu 17.04，成功编译出来，在上systemd的时候面临一个问题是，我不知道要运行的程序是哪个，FAQ和ReadMe都看了，可能这个问题比较蠢吧没有提及

目前是在Source目录下有
Auxiliary
Dependency
Pcap_DNSProxy
Pcap_DNSProxy.xcodeproj
Release
文件有
Pcap_DNSProxy.sln

请告诉我目标的程序是那个吧_(:з」∠)_

**Comment by jzp820927** [comment]
在 Release 里面，有个 Pcap_DNSProxy，就是他，是二进制可执行文件，如果没有执行权限，就加个执行权限，就行了。

**Comment by huaxianyan** [comment]
@jzp820927 
我发现里面竟然没有这个文件……编译时候出了问题吗

**Comment by huaxianyan** [comment]
@jzp820927 

> -- Configuring incomplete, errors occurred!
> See also "/home/huaxianyan/bin/Pcap_DNSProxy/Source/Object/CMakeFiles/CMakeOutput.log".
> See also "/home/huaxianyan/bin/Pcap_DNSProxy/Source/Object/CMakeFiles/CMakeError.log".
> make: *** 没有指明目标并且找不到 makefile。 停止。
> mv: 无法获取'Object/Pcap_DNSProxy' 的文件状态(stat): 没有那个文件或目录

再编译一次才发现有报错，之前没注意

**Comment by jzp820927** [comment]
你这个编译报错了。不知道你是怎么编译的，你可以把编译步骤贴出来，分析一下。

**Comment by huaxianyan** [comment]
@jzp820927 
1.首先是准备编译环境
CGG自带，6.7就没升级，看了下最新的是7.1
CMake直接通过apt安装，版本3.7.2-1，看了下最新的是3.8.1
LibPcap下载之后编译，发现缺依赖，于是apt安装了flex和bison，安装完成
Libsodium下载之后编译，也发现缺依赖，apt安装libtool和autoconf，安装完成
openSSL自带，版本1.0.2g，看了下最新的好像是f
其中LibPcap和Libsodium是自己编译安装的

2.开始编译Pcap_DNSProxy
按照Readme中操作，进目录给权限，然后执行脚本编译
没有使用root，而是用sudo来给脚本权限执行

之后就是编译完成，报错

**Comment by jzp820927** [comment]
是执行 Source/Auxiliary/Scripts/ 下面的 CMake_Build.sh 脚本？任何报错？

**Comment by huaxianyan** [comment]
`-- Configuring incomplete, errors occurred!
See also "/home/huaxianyan/bin/Pcap_DNSProxy/Source/Object/CMakeFiles/CMakeOutput.log".
See also "/home/huaxianyan/bin/Pcap_DNSProxy/Source/Object/CMakeFiles/CMakeError.log".
make: *** 没有指明目标并且找不到 makefile。 停止。
mv: 无法获取'Object/Pcap_DNSProxy' 的文件状态(stat): 没有那个文件或目录
huaxianyan@7inaBranford:~/bin/Pcap_DNSProxy/Source/Auxiliary/Scripts$ cd ..
huaxianyan@7inaBranford:~/bin/Pcap_DNSProxy/Source/Auxiliary$ cd ..
huaxianyan@7inaBranford:~/bin/Pcap_DNSProxy/Source$ ls
Auxiliary   Pcap_DNSProxy      Pcap_DNSProxy.xcodeproj
Dependency  Pcap_DNSProxy.sln  Release
`
这两个文件实际上找不到，这个目录也不存在

**Comment by jzp820927** [comment]
我去，是不是没权限？

**Comment by huaxianyan** [comment]
给了755权限啊，然后目录下sudo ./CMake_Build.sh运行的

要不我试试登陆root看看

**Comment by huaxianyan** [comment]
貌似解决了，再仔细去读了一下ReadMe，安装了libssl-dev

现在貌似成功编译出来了，我去试试启动

**Comment by huaxianyan** [comment]
正常运行了，拿到的解析都是正确的，感谢帮助，这条可以close了

**Comment by chengr28** [comment]
这些给出的错误信息都是 CMake 编译失败后产生的，编译失败的根源部分的 log 似乎并没有贴出来……所以如果不是后来再仔细看看，其实这边也不好处理的。

**Comment by huaxianyan** [comment]
主要是log文件产生不了，不知道是因为权限原因还是怎么回事

理论上只是缺了个库不应该生成不了log文件，我用图形界面打开那个目录见到文件的产生然后迅速的消失

**Comment by jzp820927** [comment]
我也赶脚  不明觉厉。
