### ISSUE TITLE
能否增加让国外dns查询走sock5代理

### ISSUE THREAD

**Issue by wxy-sky** [chengr28/Pcap_DNSProxy#246]
发现无论谷歌的dns还是其他国外dns 都有被劫持的迹象  本身一直再用小飞机 不知道怎么可以让这下查询走sock5代理

**Comment by jzp820927** [comment]
配置文件里面支持设置代理啊。

**Comment by wxy-sky** [comment]
@jzp820927 我就是不明白那个代理是怎么用的？不全部走代理是什么意思？实在是搞不懂

**Comment by chengr28** [comment]
其实说明文档有对 SOCKS 协议的介绍，如果是 SS 之类的本地代理工具改一下 `SOCKS Proxy = 1` 再重启服务就能用。摘录一段：
- `SOCKS Proxy` 总开关
- `SOCKS Version` 一般不用管
- `SOCKS Protocol` 代理时隧道中使用的协议
- `SOCKS UDP No Handshake` 本地代理一般不用管
- `SOCKS Proxy Only` 强制只使用 SOCKS 协议解析域名
- `SOCKS IPv4 Address` 服务器 IPv4 地址（如果有）
- `SOCKS IPv6 Address` 服务器 IPv6 地址（如果有）
- `SOCKS Target Server` 被代理的 DNS 服务器地址
- `SOCKS Username` 本地代理一般不用管，SOCKS 的用户名和密码验证
- `SOCKS Password` 本地代理一般不用管，SOCKS 的用户名和密码验证

**Comment by wxy-sky** [comment]
@chengr28 多谢大佬！我再好好研究下 谢谢你的时间！

**Comment by chengr28** [comment]
@wxy-sky 如果按照默认配置，默认情况下所有域名解析会首先通过 Local DNS 进行解析，这样可以保证不受 CDN 问题的困扰。然后根据规则不能通过 Local DNS 解析的请求，才会尝试使用 SOCKS 协议进行远程解析，所以才会有『不全部走代理』这种情况。顺便还有问题也可以直接继续在这里说，谢谢。
