### ISSUE TITLE
说明文档有个地方似乎不对

### ISSUE THREAD

**Issue by cok3307788** [chengr28/Pcap_DNSProxy#247]
﻿### Version/使用的版本/使用的版本

0.4.9.0
Pcap_DNSProxy/Documents/ReadMe.zh-Hans.txt 第549行
Unreliable Serial Socket Timeout - 串行可靠协议端口超时时间：单位为毫秒，最小为 500 可留空，留空时为 1000
貌似漏了个’’不‘‘字在‘’可靠‘’之前

**Comment by chengr28** [comment]
呃这都被发现了，佩服……好吧下次更新的时候会改回去，感谢反馈。

**Comment by jzp820927** [comment]
看来是，重度强迫症患者啊

**Comment by chengr28** [comment]
修改好的文档已经更新了，感谢反馈。
