### ISSUE TITLE
0.4.9.0 EDNS 无法使用

### ISSUE THREAD

**Issue by LisonFan** [chengr28/Pcap_DNSProxy#248]
启用之后无法向 Local DNS 发送请求

**Comment by LisonFan** [comment]
不是到是哪里的问题，我弄了一下又好了。

`添加对 EDNS Client Subnet Relay 启用时前缀长度跟随固定地址的功能 `这项改进是不是在`IPv4 EDNS Client Subnet Address`添加`0.0.0.0/32`

**Comment by chengr28** [comment]
这个功能的意思是 `EDNS Client Subnet Relay` 启用的时候，发出请求时所用的前缀长度由 `IPv4 EDNS Client Subnet Address` 或 `IPv6 EDNS Client Subnet Address` 里所指定的前缀长度一致。就是说如果想这样写，那么 `EDNS Client Subnet Relay` 的时候的前缀长度就是 32 位。

**Comment by LisonFan** [comment]
@chengr28
是不是填`0.0.0.0`就是拿请求者的 IP，如果填其它的，比如`28.28.28.28`，EDNS 带的就是`28.28.28.28`？

**Comment by chengr28** [comment]
这个之前那个 Issue 应该有提到啊……`EDNS Client Subnet Relay` 的优先级比 `IPv* EDNS Client Subnet Address` 的高，所以如果填的是 `28.28.28.28/32` 那么效果就是：
- 非私网（内网）地址的请求会带上请求者 32 位前缀长度的 IP 地址
- 私网（内网）地址的请求会带上 `28.28.28.28/32`

**Comment by LisonFan** [comment]
@chengr28
还有个问题，Surge for iOS 的网络诊断有一项是`测试 DNS`，在`Windows`服务器上搭的`Pcap_DNSProxy`进行这一项检测的时候提示超时，不知道什么原因

**Comment by LisonFan** [comment]
@chengr28
是的，之前的 issues 提到过这个优先级的问题。
那填`0.0.0.0`的话带的是本机 IP？

**Comment by chengr28** [comment]
@LisonFan
- 其它软件用什么方法检测这个不好说，如不确定可抓包或联系对方获得更多帮助
- 填什么就带什么，填 `0.0.0.0` 就带 `0.0.0.0`

**Comment by LisonFan** [comment]
@chengr28 
刚刚抓了一下包，发现 Surge 进行诊断的时候会发这个请求
![image](https://cloud.githubusercontent.com/assets/9424775/26754655/3f6cf92c-48b1-11e7-9793-a5a332090482.png)
然后 Pcap_DNSProxy 没有 response

**Comment by LisonFan** [comment]
![image](https://cloud.githubusercontent.com/assets/9424775/26754678/84637db2-48b1-11e7-8b7f-163c95418f57.png)
这张图是我另一台 DNS 服务器，程序用的是 dnsmasq

**Comment by chengr28** [comment]
这个看起来是因为特殊的 Transaction ID 值被过滤掉了，后来查了一下资料，标准里的确没有限制说不能用这个值……所以刚才的更新应该已经修复这个问题了，先试试，如果还是不行可以直接在这里回复，感谢反馈。
