### ISSUE TITLE
不知道怎么回事，改TCP模式，CPU直接100%

### ISSUE THREAD

**Issue by charli2014** [chengr28/Pcap_DNSProxy#25]
不知道怎么回事，改TCP模式，CPU直接跳到100%，基本无法操作。重启后还是一样，最后在安全模式中改为UDP后才正常使用

**Comment by chengr28** [comment]
希望能提供 Config.ini 文件的内容……

**Comment by charli2014** [comment]
[Base]
Version = 0.4
File Refresh Time = 10
File Hash = 1
Additional Path = 
Hosts File Name = Hosts.ini|Hosts.conf|Hosts|Hosts.txt|Hosts.csv|WhiteList.txt|White_List.txt
IPFilter File Name = IPFilter.ini|IPFilter.conf|IPFilter.dat|IPFilter.csv|IPFilter|Guarding.p2p|Guarding|Routing.txt|Route.txt|chnrouting.txt|chnroute.txt

[Log]
Print Error = 1
Print Running Log = 0
Log Maximum Size = 

[DNS]
Protocol = TCP
Hosts Only = 0
Local Main = 1
Local Routing = 1
Cache Type = Queue
Cache Parameter = 10240
Default TTL = 

[Listen]
Pcap Capture = 1
Operation Mode = Private
Listen Protocol = IPv4 + IPv6
Listen Port = 53
IPFilter Type = Deny
IPFilter Level = 0
Accept Type = 

[Addresses]
IPv4 DNS Address = 8.8.8.8:53
IPv4 Alternate DNS Address = 208.67.220.220:5353|198.153.192.1:53|202.12.27.33:53|8.8.4.4:53|208.67.222.222:53
IPv4 Local DNS Address = 223.6.6.6:53
IPv4 Local Alternate DNS Address = 114.114.114.114:53
IPv6 DNS Address = 
## Format -> IPv6 DNS Address = [2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = 
## Format -> IPv6 Alternate DNS Address = [2001:4860:4860::8888]:53
IPv6 Local DNS Address = 
IPv6 Local Alternate DNS Address = 

[Values]
EDNS0 Payload Size = 
IPv4 TTL = 0
IPv6 Hop Limits = 0
IPv4 Alternate TTL = 0
IPv6 Alternate Hop Limits = 0
Hop Limits Fluctuation = 2
Reliable Socket Timeout = 5000
Unreliable Socket Timeout = 3000
ICMP Test = 900
Domain Test = 900
Alternate Times = 5
Alternate Time Range = 60
Alternate Reset Time = 300
Multi Request Times = 0

[Switches]
Domain Case Conversion = 1
Compression Pointer Mutation = 0
EDNS0 Label = 0
DNSSEC Request = 0
Alternate Multi Request = 0
IPv4 Data Filter = 0
TCP Data Filter = 1
DNS Data Filter = 1
Blacklist Filter = 1

[Data]
ICMP ID = 
ICMP Sequence = 
ICMP PaddingData = 
Domain Test ID = 
Domain Test Data = 
Localhost Server Name = localhost.dns-server

[DNSCurve]
DNSCurve = 0
DNSCurve Protocol = TCP
DNSCurve Payload Size = 
Encryption = 1
Encryption Only = 1
Key Recheck Time = 3600

[DNSCurve Addresses]
DNSCurve IPv4 DNS Address = 208.67.220.220:443
DNSCurve IPv4 Alternate DNS Address = 208.67.222.222:443
DNSCurve IPv6 DNS Address = 
## DNSCurve IPv6 DNS Address = [2620:0:CCC::2]:443
DNSCurve IPv6 Alternate DNS Address = 
## DNSCurve Alternate IPv6 DNS Address = [2620:0:CCD::2]:443
DNSCurve IPv4 Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv4 Alternate Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv6 Provider Name = 
## DNSCurve IPv6 Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv6 Alternate Provider Name = 
## DNSCurve IPv6 Alternate Provider Name = 2.dnscrypt-cert.opendns.com

[DNSCurve Keys]
Client Public Key = 
Client Secret Key = 
IPv4 DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
IPv4 Alternate DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
IPv6 DNS Public Key = 
## IPv6 DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
IPv6 Alternate DNS Public Key = 
## IPv6 Alternate DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
IPv4 DNS Fingerprint = 
## IPv4 DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007
IPv4 Alternate DNS Fingerprint = 
## IPv4 Alternate DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007
IPv6 DNS Fingerprint = 
##IPv6 DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007
IPv6 Alternate DNS Fingerprint = 
##IPv6 Alternate DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007

[DNSCurve Magic Number]
IPv4 Receive Magic Number = 
IPv4 Alternate Receive Magic Number = 
IPv6 Receive Magic Number = 
IPv6 Alternate Receive Magic Number = 
IPv4 DNS Magic Number = 
## IPv4 DNS Magic Number = qe47QHHw
IPv4 Alternate DNS Magic Number = 
## IPv4 Alternate DNS Magic Number = qe47QHHw
IPv6 DNS Magic Number = 
## IPv6 DNS Magic Number = qe47QHHw
IPv6 Alternate DNS Magic Number = 
## IPv6 Alternate DNS Magic Number = qe47QHHw

**Comment by charli2014** [comment]
醉了，居然默认用markdown了

**Comment by chengr28** [comment]
希望能提供一个联系用的邮箱，我发一个测试版过去试试……修改了几个比较可疑的地方
不过奇怪的是同样的配置参数，这边 XP/Win7/Win 8.1/Win10 都没发现有类似的情况……

**Comment by charli2014** [comment]
最近在外面，回去后我在试下可以还原不

**Comment by charli2014** [comment]
对不起啊，最近一段时间都在外面。我先关闭问题，到时候能还原再问。

**Comment by chengr28** [comment]
没事没事……如果有问题直接 Reopen 就行ww
