### ISSUE TITLE
偶发的 nginx.org 无法解析的情况

### ISSUE THREAD

**Issue by paperbag** [chengr28/Pcap_DNSProxy#250]
﻿### Version/使用的版本
0.4.8.5

### Running Environment/运行环境
Windows 7 x64

### Expectation/期望情况
nginx.org 能够正常解析。

### Actual/实际情况
nginx.org 出现了无法解析的状况。
```
C:\Users\>nslookup nginx.org
服务器:  localhost
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 localhost 超时
```
问题发生时，我去打开了 Wireshark 进行抓包，似乎响应的结果都被丢弃了。我将抓包的内容用过滤器过滤 DNS 协议后导出（本来想上传到 https://www.cloudshark.org/ 结果发现是要掏钱的）上传至此处。

Attachment: [nginx.pcapng.zip](https://github.com/chengr28/Pcap_DNSProxy/files/1065916/nginx.pcapng.zip)

似乎这个问题是偶发的，后来莫名其妙地就能够解析了。（抓包的内容不包括突然能够解析的时候）
```
C:\Users\>nslookup nginx.org
服务器:  localhost
Address:  127.0.0.1

非权威应答:
名称:    nginx.org
Addresses:  2001:1af8:4060:a004:21::e3
          2606:7100:1:69::3f
          206.251.255.63
          95.211.80.227
```

重启 Pcap_DNSProxy.exe 后问题仍然能够复现（应该是重启后缓存就不在了），但也有正常的情况。

### 与默认配置不同的部分

Config.ini
```
[DNS]
Cache Type = Timer
Cache Parameter = 172800
Default TTL = 86400
[Addresses]
IPv4 Main DNS Address = 8.8.8.8:53
IPv4 Alternate DNS Address = 8.8.4.4:53|208.67.220.220:443|208.67.222.222:5353
IPv4 Local Main DNS Address = 218.108.248.228:53 #这两个都是运营商的 DNS 服务器
IPv4 Local Alternate DNS Address = 218.108.248.200:53
[Values]
ICMP Test = 0
Domain Test = 0
[Switches]
Domain Case Conversion = 0
[Data]
Local Machine Server Name = localhost
```
IPFilter.ini
```
[Blacklist]
## Huashu
30.250.11.135 ALL#加了运营商在域名不存在时所投放的广告地址。
30.250.15.174 ALL
113.215.6.148 ALL 
```

发生此问题的**时间段**没有错误日志，因为并不是每次都能复现，实在有些困惑，当权算是做个记录。

**Comment by chengr28** [comment]
这个问题的根源应该是这两句配置造成的：
- `ICMP Test = 0`
- `Domain Test = 0`
默认配置下抓包模块是启用状态的，但是抓包模块开始工作时需要真正的 DNS 服务器的解析，来记录相关的特征以便对伪造数据包进行过滤。关闭这两个配置会等于关闭了程序的主动式探测模块，那么抓包模块只能通过被动地对解析数据包进行检查以确定相关 DNS 服务器的特征。需要注意的是在 **记录到相关 DNS 服务器特征前，程序不会接受任何远程服务器的解析结果** 重启服务是没有效果的。

**Comment by paperbag** [comment]
蟹蟹小盆友，修改后我又试了几次，现象消失了。
