### ISSUE TITLE
不知道什么原因，用了一段时间之后就不响应 host 外的链接了

### ISSUE THREAD

**Issue by LisonFan** [chengr28/Pcap_DNSProxy#251]
﻿### Version/使用的版本/使用的版本
0.4.9.0

**Comment by jzp820927** [comment]
检查下，进程是不是挂掉了
你是什么操作系统 ？

**Comment by LisonFan** [comment]
@jzp820927 进程没挂，Win10

**Comment by jzp820927** [comment]
不科学，重启一下 pcap 呢？

**Comment by LisonFan** [comment]
@jzp820927 电脑都重启了，没用

**Comment by chengr28** [comment]
机器重启也没有用，那么多半是网络问题……因为这边有收到反馈说不时会出现连续几分钟所有境外 DNS 流量都被阻断的情况。如果需要确认问题，建议出问题的时候抓个包，谢谢。

**Comment by LisonFan** [comment]
@chengr28
不是 0.4.9.0 版本，记错了，我刚刚升到 0.4.9.0 现在没问题了，等出问题了再去抓
