### ISSUE TITLE
为何Local Host不能与Local Main同时开启呢

### ISSUE THREAD

**Issue by cjjdaq** [chengr28/Pcap_DNSProxy#252]
重新整理下，这两天在使用中遇到的问题。

### Running Environment/运行环境/運行環境
lede x64
### Expectation/期望情况/期望情況
基本需求：能控制一个域名强制走境内dns还是强制走境外dns。
### Actual/实际情况/實際情況
监听端口：1053|7913
开的是Local Force Request+Local Hosts （不理解为何一个强制走境内需要两个参数） 
IPv4 Main DNS Address = 境外vps_ip:7549
IPv4 Alternate DNS Address = 境外vps_ip:8549

1： killall后短时间内启动pcap_dnsproxy会出现：Bind TCP Monitor socket error: Address in use[98]，一般都是0.0.0.0：1053绑定失败，其它成功监听。
2：无法解析www.google.com，这个比较纳闷，测试其它非污染和有污染域名都解析正常
dig @vps_ip -p7549（-p8549） www.google.com都正常解析。直接dig www.google.com失败。
3：在不考虑污染的情况下，没法完全控制一条域名强制走境内dns还是走境外dns。
4:设置参数太多，Outgoing Protocol和Local Protocol也不知道什么关系。
5： dig @127.0.0.1 -p1053 www.baidu.com +tcp解析超慢，3秒以上。udp正常
6：dig +trace只能看到第一次根域名，后续信息没有。

**Comment by jzp820927** [comment]
作用一样，同时开启，功能重复了吧

**Comment by cjjdaq** [comment]
那对于域名dns服务器不是境内的，而且使用又是非国内的亚洲ip时，如果处理呢。
开Local Main和Local Routing，解析速度肯定慢。因为ip不在Local Routing中，开Local Force Request也不行，因为域名使用的dns也不是境内的。
国内很多网站主使用的是亚洲主机哎。

**Comment by jzp820927** [comment]
能不能具体说明一下你的需求？

**Comment by cjjdaq** [comment]
比如域名 www.abc1234.com使用的是国外的dns域名解析服务。（如香港的，韩国的，日本的）
www.abc1234.com对应的ip是也是香港的或者韩国的ip
这时候，pcap_dnsproxy解析就会变慢。

**Comment by jzp820927** [comment]
你的意思，类似 www.abc1234.com 这种域名，需要用特别的 DNS 来解析？

**Comment by cjjdaq** [comment]
简单一句话，能够同时开启，功能上并不重复。

**Comment by SeaHOH** [comment]
@cjjdaq 
你理解错了，**Local Hosts** 是白名单功能（需要请求服务器），不是 **Hosts** 功能（本地自定义）。
**Hosts** 的优先级一直在 **Local Hosts** 前面，你期望的功能只需要开启 **Local Main** 和 **Local Routing** 。

**Comment by cjjdaq** [comment]
我没有说hosts功能呀，我说的就是Local Hosts 是白名单功能开启与Local Main 和 Local Routing并没有冲突，只要优先级比Local Main高就可以了呀

**Comment by SeaHOH** [comment]
看错了，已删。

**Comment by cjjdaq** [comment]
比如说，我开启Local Main与Local Routing后，我想强制一个域名走境内dns，可这时候Local Hosts并不能开启。

**Comment by SeaHOH** [comment]
是的，所以我是看错了。 :pray:

**Comment by jzp820927** [comment]
我认为你的想法，应该可以通过 Dnsmasq Server 功能来实现 （https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe.zh-Hans.txt#L939），通过为特定域名指定特定 DNS 解析。或者用 hosts 直接为域名指定 IP。
如果确实需要功能上的改进，只能等 repo 主回复了。

**Comment by cjjdaq** [comment]
我是在讨论Local Hosts Local Force Request Local Main 三者同时开启的问题。

**Comment by chengr28** [comment]
个人觉得你对这几个选项的理解有偏差，他们之间的关系并非不同的请求过程还分权重，而是对同一个请求过程不同的选择策略，不知道为何你会觉得可以同时启用。这几个参数：
- `Local Hosts`：将收到的请求分成两种，命中规则和没有命中规则的，前者发往 Local DNS 并获得解析结果（注意这里有可能不接受），后者直接跳过此部分
- `Local Main`：所有请求都发往 Local DNS 并获得解析结果
- `Local Routing`：必须与 `Local Main` 配合使用（只有后者启用时才能启用），启用则按照路由表匹配，不启用则等于直接使用 Local DNS 解析
- `Local Force Request`：必须与 `Local Hosts` 配合使用（只有后者启用时才能启用 = 只对命中了规则的域名生效 = 已经确定使用境内服务器的域名），强制指定命中了规则的域名只能使用指定的或 Local DNS 解析，不能跳过 Local DNS 这个请求过程

**Comment by chengr28** [comment]
关于 Actual 里的 3 个问题：
- 关于 `dig +trace` 的意思是自行进行分级查询，就是说自行从 root 域名服务器开始一级一级往下查询域名，也就是说除了第一个查询 root 域名服务器列表的请求外，其它所有请求都与非查询域名的 NS DNS 无关。而经过实测，程序可以正常对第一个查询进行回应，不清楚你说的『无法使用』是什么意思
- 关于 `ipset` 的功能，不清楚你想要程序的什么部分实现什么效果
- 关于『如何确定了域名使用境内服务器』这个上面有说，就是『开启 `Local Hosts` 功能后根据规则命中了的域名查询』

**Comment by chengr28** [comment]
关于『那对于域名 DNS 服务器不是境内的，而且使用又是非国内的亚洲 IP 时，如果处理呢』这个问题：当成境外的地址处理不是最好的解决方法？需要明确的前提是，使用 Local DNS 功能查询域名的目的是什么？是境外 DNS 服务器对于境内的 CDN 状况很不友好，导致不同线路解析到不同的 ISP 上拖慢速度。但是你自己一开始也说了『域名使用的 DNS 不是境内的』，在『使用亚洲主机』的情况，难道位于境内的 Local DNS 的解析结果就会比使用境外的 DNS 的解析结果要好？为什么对 Local DNS 有种很奇怪的执着，这点我是真的不懂。

**Comment by SeaHOH** [comment]
我理解楼主是想这样：
白名单命中就发到 `Local DNS`，然后就没有然后了。
白名单没命中仍然发到 `Local DNS`，然后继续匹配路由表，路由表没命中再发到 `DNS`。

**Comment by cjjdaq** [comment]
@chengr28 对呀，就像楼上说的，白名单命中就强制Local DNS 解析，没有命中的还是候发给Local DNS 解析，然后进行路由匹配，匹配直接返回，没有匹配交给境外dns

**Comment by cjjdaq** [comment]
dig +trace如下
root@LEDE-X64:~# dig -p 1053 www.biadu.com

; <<>> DiG 9.10.5 <<>> -p 1053 www.biadu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50019
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.biadu.com.			IN	A

;; ANSWER SECTION:
www.biadu.com.		81756	IN	A	103.51.144.81

;; Query time: 0 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Wed Jun 14 22:59:05 CST 2017
;; MSG SIZE  rcvd: 58

root@LEDE-X64:~# dig -p 1053 www.biadu.com +trace

; <<>> DiG 9.10.5 <<>> -p 1053 www.biadu.com +trace
;; global options: +cmd
;; connection timed out; no servers could be reached
root@LEDE-X64:~#

**Comment by cjjdaq** [comment]
1053端口是pcap_dnsproxy的。
; <<>> DiG 9.10.5 <<>> @127.0.0.1 -p 1053 www.baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50782
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.baidu.com.			IN	A

;; ANSWER SECTION:
www.baidu.com.		80	IN	CNAME	www.a.shifen.com.
www.a.shifen.com.	80	IN	A	180.97.33.107
www.a.shifen.com.	80	IN	A	180.97.33.108

;; Query time: 13 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Wed Jun 14 23:12:44 CST 2017
;; MSG SIZE  rcvd: 90

root@LEDE-X64:~# dig @127.0.0.1 -p 1053 www.baidu.com +trace

; <<>> DiG 9.10.5 <<>> @127.0.0.1 -p 1053 www.baidu.com +trace
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by cjjdaq** [comment]
可能说的啰嗦了。就是开启Local Routing和Local Main的情况下。对于使用港澳台主机这类ip不在路由表中的如何友好的解析。

**Comment by cjjdaq** [comment]
我的逻辑是这样的，一个名单列表强制境内dns，一个名单列表强制境外dns。不在这两个名单列表里的。就按照Local Routing和Local Main的逻辑来。

**Comment by jzp820927** [comment]
我觉得你的需求，用 dnsmasq 很容易实现， Pcap_DNSProxy 估计不太方便。
不过其实 Pcap_DNSProxy 也已经完全支持 dnsmasq 的规则和功能了。

**Comment by cjjdaq** [comment]
dnsmasq不是没有Local Routing和Local Main功能么，而且也不支持tcp，pcap_dnsproxy不是没有ipset支持么。

**Comment by jzp820927** [comment]
你的需要太过复杂，好吧，我也只能坐等砖家来解答了。

**Comment by cjjdaq** [comment]
不知怎么回事，我配置的两个上游境外dns都能解析出www.google.com，可用pcap却解析不出来。
; <<>> DiG 9.10.5 <<>> @192.168.2.1 -p 1053 www.google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by jzp820927** [comment]
pcap 到 上游，是用的 非标准端口麽？

**Comment by cjjdaq** [comment]
的确，两个上游都是非标准端口。但其他有污染和没有污染的都可以解析，唯独这个www.google.com
root@LEDE-X64:~# dig @127.0.0.1 -p 1053 zh.wikipedia.org

; <<>> DiG 9.10.5 <<>> @127.0.0.1 -p 1053 zh.wikipedia.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46320
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;zh.wiKipedia.oRG.		IN	A

;; ANSWER SECTION:
zh.wiKipedia.oRG.	599	IN	A	198.35.26.96

;; Query time: 384 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Thu Jun 15 08:58:46 CST 2017
;; MSG SIZE  rcvd: 61

root@LEDE-X64:~#

**Comment by jzp820927** [comment]
这个有点不科学，我这儿测试没啥问题。其他 google 域名呢？比如 www.google.com.hk ，www.google.co.jp 之类的？

**Comment by cjjdaq** [comment]
看了会让你吐血
root@LEDE-X64:~# dig @127.0.0.1 -p 1053 www.google.com.hk

; <<>> DiG 9.10.5 <<>> @127.0.0.1 -p 1053 www.google.com.hk
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22084
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.GOoGle.com.Hk.		IN	A

;; ANSWER SECTION:
www.GOoGle.com.Hk.	231	IN	A	172.217.6.35

;; Query time: 261 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Thu Jun 15 09:40:33 CST 2017
;; MSG SIZE  rcvd: 62

root@LEDE-X64:~# dig @127.0.0.1 -p 1053 www.google.com.tw

; <<>> DiG 9.10.5 <<>> @127.0.0.1 -p 1053 www.google.com.tw
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61595
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;Www.google.com.Tw.		IN	A

;; ANSWER SECTION:
Www.google.com.Tw.	120	IN	A	172.217.6.35

;; Query time: 315 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Thu Jun 15 09:40:36 CST 2017
;; MSG SIZE  rcvd: 62

root@LEDE-X64:~# dig @127.0.0.1 -p 1053 www.google.com.jp

; <<>> DiG 9.10.5 <<>> @127.0.0.1 -p 1053 www.google.com.jp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 55847
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.gooGle.coM.Jp.		IN	A

;; AUTHORITY SECTION:
Jp.			392	IN	SOA	z.dns.Jp. root.dns.Jp. 1497490204 3600 900 1814400 900

;; Query time: 384 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Thu Jun 15 09:40:41 CST 2017
;; MSG SIZE  rcvd: 93

root@LEDE-X64:~# dig @127.0.0.1 -p 1053 www.google.co.jp

; <<>> DiG 9.10.5 <<>> @127.0.0.1 -p 1053 www.google.co.jp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59682
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;wWw.GoOGlE.Co.Jp.		IN	A

;; ANSWER SECTION:
wWw.GoOGlE.Co.Jp.	58	IN	A	172.217.6.35

;; Query time: 389 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Thu Jun 15 09:41:05 CST 2017
;; MSG SIZE  rcvd: 61

root@LEDE-X64:~# dig @127.0.0.1 -p 1053 dns.google.com

; <<>> DiG 9.10.5 <<>> @127.0.0.1 -p 1053 dns.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8382
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dns.google.com.			IN	A

;; ANSWER SECTION:
dns.google.com.		300	IN	A	172.217.27.142

;; Query time: 82 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Thu Jun 15 09:41:19 CST 2017
;; MSG SIZE  rcvd: 48

root@LEDE-X64:~# dig @127.0.0.1 -p 1053 www.google.com

; <<>> DiG 9.10.5 <<>> @127.0.0.1 -p 1053 www.google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by cjjdaq** [comment]
@chengr28 能为pcap_dnsproxy弄个电报群吗？

**Comment by jzp820927** [comment]
估计作者应该没什么时间去群。

**Comment by cjjdaq** [comment]
tcp解析速度奇慢。udp正常。

; <<>> DiG 9.10.5 <<>> @192.168.2.1 -p1053 www.qq.com +tcp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4480
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.qq.com.			IN	A

;; ANSWER SECTION:
www.qq.com.		30	IN	A	180.96.86.192

;; Query time: 3017 msec
;; SERVER: 192.168.2.1#1053(192.168.2.1)
;; WHEN: Thu Jun 15 14:27:03 CST 2017
;; MSG SIZE  rcvd: 44

root@LEDE-X64:~# dig @192.168.2.1 -p1053 www.qq.com +notcp

; <<>> DiG 9.10.5 <<>> @192.168.2.1 -p1053 www.qq.com +notcp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40575
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.qq.com.			IN	A

;; ANSWER SECTION:
www.qq.com.		276	IN	A	180.96.86.192

;; Query time: 14 msec
;; SERVER: 192.168.2.1#1053(192.168.2.1)
;; WHEN: Thu Jun 15 14:27:13 CST 2017
;; MSG SIZE  rcvd: 44

**Comment by cjjdaq** [comment]
已经killall了Pcap_DNSProxy,再启动总是提示绑定失败。
[2017-06-15 14:31:22] -> [Notice] Pcap_DNSProxy started.
[2017-06-15 14:31:23] -> [Network Error] Bind TCP Monitor socket error: Address in use[98].

**Comment by cjjdaq** [comment]
不折腾了，还是乖乖使用dnsmasq+pdnsd

**Comment by jzp820927** [comment]
怀疑是不是你网络的问题，你的这些问题，在我这边都没有。

**Comment by cjjdaq** [comment]
我是放再lede x64软路由里使用的，并不是单机使用。

**Comment by chengr28** [comment]
关于那几个问题：
1. 这个错误信息意思是，在尝试多开程序或者系统尚未回收监听端口就尝试启动另外一个实例造成，简单来说就是端口被占了。记得 LEDE 上用的是 init script 直接 `killall` 是万不得已才用的方法，不过不太清楚脚本能不能像发行版 Linux 那样控制服务的启动停止，这个问题要咨询一下 @wongsyrone 
2. 单单无法解析 `www.google.com` 的问题应该是写了 IPFilter.ini 将解析的地址列入了黑名单，程序没有接受远程服务器返回的解析结果，或者有一些特别的网络问题导致拒绝接受解析结果。如果需要查清楚，可以在运行程序的机器上查询此域名时抓个包看看。
3.  - 关于这个问题，如果意思和 @SeaHOH 说的是一样的，那么就是因为你一开始有和本功能设计时不一样的前提。因为 Local DNS 这个功能在设计时目的就是 **辅助境外 DNS 服务器解析** 只是你主观地认为这个功能是程序的一个主要的部分（虽然是有这个趋势）。
    - 至于具体的实现，强制域名列表只能使用 Local DNS 那么可以设置 `Local Hosts` + `Local Forece Request` 如果强制域名列表在启用 `Local Hosts` 时不能使用 Local DNS 那么直接不要列在 `[Local Hosts]` 字段中即可，这是一个完整的选择策略，由此可见这套方案下是不需要黑名单的。然而你的前提和这边设计时的不同是要启用 `Local Main` 和 `Local Hosts` 这就造成了整套流程和设计需要更换，实现需要的时间不会短就是了。
    - 关于那个亚洲主机的问题，虽然不清楚为何执着于境外 DNS 解析时间长（实际上也差不多多少）的问题，不过有个临时的解决方法。项目实际上是有附带一套 Tools 用于更新路由表的，批处理/脚本默认过滤 CN 的地址，你把 HK/JP/SG 的也加进去然后更新一次不就好了……
4.  - 参数数量这个见仁见智，有人需要一个功能，实现这个功能需要添加参数……日积月累，多了不是很正常。无关的参数，按照默认配置不就好了？
    - `Outgoing Protocol` 指的是程序 **在请求境外 DNS 服务器时** 所使用的协议集合，而 `Local Protocol` 指的是程序 **在请求 Local DNS 服务器时** 所使用的协议集合。
5. 使用 TCP 协议进行解析会比 UDP 慢这个不是常识？使用 TCP 协议请求时程序会在所有请求过程中强制使用 TCP 协议进行解析。虽然不清楚配置文件的情况，但是由于每个请求远程 DNS 服务器都使用 TCP 而且 TCP 的 3 次握手 + 4 次分手，所占用的时间会比 UDP 多几倍到几十倍，这还没有把服务器协议栈的准备工作算上……
6. 不太清楚你运行 `dig +trace` 想要看到什么效果，这边虽然花费的时间有点长（5 - 6 秒）但是实际上是可以完成所有对 root 域名服务器的查询的。第一个可以看到但是第二个看不到，那么看不到的应该是启用了 DNSSEC 的那个查询，如果不确定是哪里的问题，和第 2 点一样，抓个包看看就知道了。

补充：
- 『为何一个强制走境内需要两个参数』这个和第 4 点一样，有人需要一个功能，实现这个功能需要添加参数，这不是很正常？如果启用 `Local Hosts` 但不启用 `Local Force Request` 你可以理解为『优先使用 Local DNS 进行解析』，吼啊，在 2 个参数都启用的情况下就是『强制走境内的解析』那么我问你一个问题：万一 Local DNS 解析不出这个域名，那么是不是就大家都不要用了？
- IPSET 这个功能可以考虑添加，不过看了基本都是要动筋骨的修改，和第 3 点提到的问题一样。

**Comment by jzp820927** [comment]
老大发飙了，一口气打这么多字

**Comment by SeaHOH** [comment]
DNS 果然是一个看似简单，实质复杂的系统，方方面面都要考虑周到，一个小特性的增加或改变就可能导致某些情况下无法返回结果。
以前用过其它类似工具，后来换用 Pcap_DNSProxy 后，发现光 readme 就有好几十 KB，才知道这类玩意儿包含了作者太多的心血。尤其是 C 大把处理过程中更多的步骤化为方便我们自定义使用的选项，这又是个更加辛苦的工作，万分感谢！
实际上如果要图快，直接用 `Local Hosts` 就是，结果并不会差很多，我就是这样用的。

**Comment by cjjdaq** [comment]
咱们能电报群聊么，这里交流太蛋疼。https://t.me/Pcap_DNSProxy

**Comment by cjjdaq** [comment]
就因为Local DNS不是程序主要功能，所以大神们在做路由固件把pcap_dnsproxy整合进路由的时候只是用来单单的解析gfwlist列表的域名，而且浪费了pcap现有的很多功能。

**Comment by wongsyrone** [comment]
LEDE的新procd脚本已经换成了官方的退出方式，先尝试SIGTERM大概5次，之后进行SIGKILL，所以如果没有改init脚本为旧版的话，应该是不涉及这边的

**Comment by cjjdaq** [comment]
@wongsyrone 我就单单使用了一个主程序，没有使用脚本，没有注意init中是如何退出的，所以我直接killall了

**Comment by cjjdaq** [comment]
@wongsyrone 使用procd脚本，依然会提示绑定失败。/etc/init.d/pcap-dnsproxy restart,绑定失败的端口都是0.0.0.0:1053

**Comment by cjjdaq** [comment]
Fri Jun 16 04:01:39 2017 daemon.err Pcap_DNSProxy[21594]: [2017-06-16 04:01:39] -> [Notice] Pcap_DNSProxy started.
Fri Jun 16 04:01:39 2017 daemon.err Pcap_DNSProxy[21594]: [2017-06-16 04:01:39] -> [Pcap Error] Error reading /sys/class/net: Bad file descriptor
Fri Jun 16 04:01:58 2017 daemon.err Pcap_DNSProxy[21594]: [2017-06-16 04:01:58] -> [Pcap Error] SIOCGIFFLAGS: tunl0: Bad file descriptor

**Comment by chengr28** [comment]
感觉这个 Issue 已经变成一堆混杂在一起的问题了：

3. 注意……在 `[Local Hosts]` 里是没有 `NULL` 这个功能的，之前就有提到过按照现在的这套方案，不命中规则等于不使用 Local DNS 所以没有这个功能，写 `NULL 规则` 会被当成整个正则处理。
4. 这个下次更新的时候会补上。
5. 一样的道理……如果对程序的功能有怀疑，可以在运行程序的机器上抓个包，个人是觉得在请求远程 DNS
 服务器之前，可能是跑去请求了一下 Local DNS 这个只能抓包才能知悉。
8. geoip 这个没什么必要……程序本身不应该集成这种给辅助数据库分类的功能。顺便觉得 ipset 这个功能也是没什么广泛的应用场景，而且最重要是只能在特定的平台上使用，大修大改支持这种功能……只能说会继续考虑，适时回复。
9. `[Pcap Error]` 是从抓包模块报上来的问题，本程序无法解决。至于后面那个 `segfault` 的问题……这个真不好说，最近好像都比较少见了，这类问题都没什么头绪……

**Comment by cjjdaq** [comment]
3. 已经改为Local Main+Local Routing，加入了HK.TW等亚洲等地的ip列表。使用NULL规则可强制境外dns解析。只是假如hk.tw会不会对防污染有影响。
5.发现tcp解析时间和Reliable Once Socket Timeout参数有关，我设置为800，tcp解析大概缩短到1s左右。
6.dig +trace我这没法使用，具体信息
root@LEDE-X64:~# dig -p1053 www.google.com +trace
; <<>> DiG 9.10.5 <<>> -p1053 www.google.com +trace
;; global options: +cmd
;; connection timed out; no servers could be reached

geoip和ipset只是这么一说。

**Comment by cjjdaq** [comment]
关于dig +trace的问题发现个有趣的现象。
重启pcap后，无法直接使用dig +trace www.baidu.com会timeout，这个时候直接运行一次dig或者dig .或者dig +trac后，dig +trace www.baidu.com（或其它任何域名）就能正常使用了。这是什么情况？

**Comment by chengr28** [comment]
关于这几个问题：

- Local DNS 整个请求策略的问题，有时间会考虑一下。
1. 关于程序短时间内重启导致监听地址没法很快被系统协议栈回收再用的问题，感觉 Linux 的情况比较多，不清楚是不是系统协议栈有什么其它的限制，这个可能需要时间研究一下。
3. 加入非 CN 的地址对于会不会对过滤效果有影响，理论上是会的，不过现阶段 DNS 投毒污染回归大部分固定地址（实测发现还是有一小部分重点清除的域名有随机投毒污染地址的现象）应该是没太大的问题。
5. 这个其实不应该……如果远程服务器的解析成功，那么理论上来说不会再等到超时时间才返回的，这方面可能还需要调查下，或者可能提供一下抓包的情况（不方便公开可以发到我的邮箱）有可能是 VPS 的传输策略和程序这边的对不上造成的。
6. 关于这个 `dig +trace` 的问题，看起来是程序不接受刚开始的结果，在获取到远程服务器真实数据包的特征后就切换状态变成接受了。或者你可以试试一开始就用 `dig +vc +trace` 使用 TCP 协议进行解析，应该就不会有问题，这边也会继续优化一下这个探测特征的过程。
7. 所有 `.. TTL/HopLimit` 参数都是一一和 `.. Address` 对应，前者可以少但不能多，不填报错估计是因为前者比后者数量多对不上的缘故。其实如果都是 0 自动获取的话，前面的参数直接不填是没问题的。
8. 其实没什么必要呢……DNS 缓存是一个整体，本身就是对解析结果的最佳适配，就算切分成两部分还是几个部分，都没什么区别。
9. 运行流水的问题在 https://github.com/chengr28/Pcap_DNSProxy/issues/255 有提到。

**Comment by cjjdaq** [comment]
1.我有试过连续重启ss，pdnsd，dnsmasq都不会出现此情况，不管这些软件好像都是在启动过程的最后才监听端口。

2.加入非cn的，如果发现个别污染的，还有用NULL的后路，这没事。

3.等我抓包给你发邮件。不知道邮箱地址，囧。

4.dig +trace +tcp www.baidu.com 没有问题的，不过貌似根服务器的tcp给reset了。我加入了走ss可以完成整个流程，但默认udp不行根列表都不给我，得单独dig一次后才能带域名进行trace

5.就是IPv4 Alternate DNS Address留空，IPv4 Alternate DNS TTL为0会提示错误。


6.为什么会提出这个要求呢，因为国内网络多变，很多网站使用cdn，而且那些cdn节点还不固定，经常变，比如www.baidu.com在江苏对应223.222.223.224这个节点，可能很快就变成223.222.223.225这个节点了，而你要host 223.222.223.224这个节点直接打不开了。这是国内cdn服务商经常干的事情（为了防止被攻击）。我不知道你没有注意过这种情况。所以境内网址或者是route命中的的缓存时间最好要短一点，而且境外网站就没那么复杂了。在加上使用境外dns解析比较慢，如果使用chrome会经常看到正在解析这样的状态，对于强迫症的人来说，境外的缓存时间可以长一点。

**Comment by jzp820927** [comment]
看来 DNS 的情况，也是很复杂的

**Comment by chengr28** [comment]
3. 邮件地址 Profile 就有。
5. 之前就说参数是一一对应的，前者不填后者也不能填，因为填 `0` 等于要求前者要有一个或以上数量。
6. 这个是因为你对这个解析速度和缓存机制太过看重了。前者先不说，程序的缓存只是辅助用途的。系统本身的协议栈会根据解析结果中的缓存时间值对结果进行缓存，程序这边的缓存设计的最大用途就是防止境外解析时间过长的问题，具体的算法 ReadMe 文档对 `Cache Type` 和 `Cache Parameter` 参数的介绍很清楚，基本就是延长系统协议栈的缓存时间和为缓存时间划定最低的缓存时间。所以比较好的解决方法是在两者之间取得一个平衡，而不是东墙倒了拆西墙这样打补丁。

**Comment by chengr28** [comment]
境内服务器解析的部分已经修改完成了，详细的介绍参见 ReadMe 说明文档，节选一部分：
```
* 注意：关于 Local Force Request 和 Local Hosts 和 Local Routing 的组合说明
  * 所有参数均为关闭时：直接跳过使用境内服务器进行域名解析的过程
  * 默认情况下在境内服务器解析失败会进行下一步的操作
  * 只开启 Local Hosts 时：将按照（黑）白名单（无）命中规则的域名，才（不）使用境内服务器进行解析
    * 开启 Local Force Request 参数时，则强制已命中规则的域名只能使用境内服务器进行解析
  * 只开启 Local Routing 时：所有请求都会先发送至境内服务器进行域名解析，然后根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者
  * 同时开启 Local Hosts 和 Local Routing 时：所有（除了黑名单所指定的）请求都会先发送至境内服务器进行域名解析，然后根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者
    * 开启 Local Force Request 参数时，则强制已命中规则的域名只能使用境内服务器进行解析
```
