### ISSUE TITLE
Pcap_DNSProxy-0.4.9.0无法使用

### ISSUE THREAD

**Issue by 19910703** [chengr28/Pcap_DNSProxy#253]
﻿### Version/使用的版本/使用的版本
Pcap_DNSProxy-0.4.9.0

### Running Environment/运行环境/運行環境
windows7旗航版   
管理员运行Pcap_DNSProxy-0.4.9.0里面windows的ServiceControl.bat选择1就提示错误: 没有找到进程  "Pcap_DNSProxy.exe"。 
 
![1](https://user-images.githubusercontent.com/20448046/27210101-98b3efd8-5282-11e7-9d5c-d03a9f070f08.png)

**Comment by chengr28** [comment]
查看程序是否工作正常不是在这里看的，而是在任务管理器（之类的）里看进程是否在后台运行，并按照 ReadMe 说明文档中的测试方法进行测试的。这里会提示这个错误，原因是要避免有其它实例运行或者以前未卸载干净可能会造成的问题。
