### ISSUE TITLE
建议增加加密和绑定多个指定的IP和端口

### ISSUE THREAD

**Issue by liuxyon** [chengr28/Pcap_DNSProxy#254]
﻿### Version/使用的版本/使用的版本

Pcap_DNSProxy 0.4.9.0

### Running Environment/运行环境/運行環境

windows 2016 server winpcap usecap  ipv6 and ipv4  以及ipv6反向代理

### Expectation/期望情况/期望情況

希望对国外普通DNS提供加密功能,因为目前无论IPV6或IPV4 当从上游DNS获取数据时候一旦包含敏感域名或字的时候会被阻断,暂时使用的是压缩2+3 起作用,1基本不起作用.
EDNS 也不起作用.

突然现在压缩也不起作用用于突破. 封锁域名不能解析 只有普通域名可以解析

### Actual/实际情况/實際情況

因为我同一个服务器装有多个DNS服务,如何绑定多个指定的IP和端口?

**Comment by liuxyon** [comment]
[Network Error] Socket connecting error: An operation was attempted on something that is not a socket[10038].
Socket connecting error: An invalid argument was supplied[10022].

**Comment by jzp820927** [comment]
参数无效？你的机子有几块网卡么？

**Comment by liuxyon** [comment]
有2块.

**Comment by jzp820927** [comment]
如果你2块网卡要同时绑定，可以设置绑定 IP 为 0.0.0.0，如果你只想绑定一块网卡，就设置绑定地址为那个网卡的 IP 地址。端口也是可以自定义的，在配置文件指定自己想要绑定的端口就可以了。

**Comment by liuxyon** [comment]
在哪个参数下写?
[Listen]
Pcap Capture = 1
Pcap Devices Blacklist = AnyConnect|Host|Hyper|ISATAP|IKE|L2TP|Only|Oracle|PPTP|Pseudo|Teredo|Tunnel|Virtual|VMNet|VMware|VPN|any|gif|lo|stf|utun
Pcap Reading Timeout = 250
Listen Protocol = IPv6 + IPv4 + TCP + UDP
Listen Port = 5358
Operation Mode = Server
IPFilter Type = Deny
IPFilter Level < 0
Accept Type =

**Comment by liuxyon** [comment]
目前关键是如何解决关键字阻断的问题. 上游是53端口.  我们有没有办法?

**Comment by jzp820927** [comment]
一般都是用程序内置默认的非标准端口 DNS Server，你一定要用你自己的上游 DNS 吗？

**Comment by liuxyon** [comment]
是的，用来解决网站IP被封。 网站IP被封的话就算解析正确也没有用。 所以通过上游代理。

**Comment by jzp820927** [comment]
不知道你想用的上游 DNS Server 是不是你自己的服务器，如果是你自己的服务器，你可以把 DNS Server 监听在非标准端口，这样就可以解决问题。

而且目前 gfw 对 DNS 的手段是污染，并不是 阻断，阻断只是针对 https 的 tcp 连接。

**Comment by liuxyon** [comment]
上游不是我的. 目前DNS已经增加阻断了,测试了. 换成普通域名就可以从上游同一个IP解析,换成被封域名就直接连接不上.

**Comment by jzp820927** [comment]
那就没办法了，加密要服务端和客户端同时支持才行，你没有上游 DNS 服务器的控制权肯定是不行的。

**Comment by chinaniupai** [comment]
@liuxyon 要不你买个国内的云服务器，搭建这个DNS服务，然后把所有电脑什么的都走那个云服务器？

**Comment by liuxyon** [comment]
那抓包起什么作用？ 
买也不会买国内的。买国内有什么用

**Comment by jzp820927** [comment]
你是问 pcap 的抓包功能有什么用？

**Comment by chengr28** [comment]
好像是有几个问题：

- 关于加密的问题，DNS 协议本身是没有加密能力的，要想加密只能依靠其它算法。例如本程序现阶段已经支持的 DNSCurve/DNSCrypt 协议就是加密的，当然 DNS over TLS 之类的也有在计划之中。
- 压缩指针本质只是一个避免被检测的偏方，能不能被识别取决于检测设备。
- 阻断连接的问题只针对 TCP 协议，EDNS 当然是没有用的，因为访问的域名已经被识别出来了，没有加密是没法避免这种情况的。不过这里有个问题就是为什么非得要用 TCP 协议……UDP 协议不能使用？
- 抓包模块是用来辅助工作在 UDP 协议模式时过滤伪造数据包用的。
- 绑定指定地址+端口，参见 ReadMe 文档对 `IPv4 Listen Address` 和 `IPv6 Listen Address` 参数的介绍。当然还有种方法是 `Operation Mode = Server`（绑定通用地址，可接受所有查询）然后设置 `Listen Port` 指定需要监听的（可指定多个）端口。
- 关于那 2 个网络错误，有可能是重置连接的后遗症。

**Comment by chengr28** [comment]
@jzp820927 只要绑定的是通用地址（`0.0.0.0`/`::`）那么无论是多少张网卡发过来的请求都是可以一次性出来的，不需要分别绑定。

**Comment by chengr28** [comment]
关于这张 Issue 让我想到了一种多开程序的需求，这边需要有所改进，就先打上 Tag 了……

**Comment by jzp820927** [comment]
什么情况下需要多开程序？我觉得监听多端口，就类似于多开了。

**Comment by liuxyon** [comment]
我要说明下我测试结果
1.首先阻断目前UDP 和TCP都发生,同时IPV6和IPV4同时发生. IPv6大约从去年开始干扰,先是IPv6污染,现在是全部阻断. 我目前就使用的是UDP, 错误提示还是无法连接被阻断.
2. 在我用你这个程序刚刚开始的时候,使用2+3压缩,UDP可以连接,但是仅仅维持了十几分钟就不行了.
3.目前我使用PFSENSE V2.4路由器,看看是否有什么利用上的.
4. 你说的绑定地址和端口,参考文档还是不明确具体在哪设置, 
5. 有没有办法干扰他们检测关键字. 哪个大小写随机是起什么作用? 我目前上游DNS地址只有IPV6的.

**Comment by liuxyon** [comment]
对了, 目前如果链接上游非53标准端口, 竟然没有阻断, 看起来他们仅仅目前检测53端口

**Comment by liuxyon** [comment]
我认为GWF 可能具有自学习能力,压缩指针刚使用时候起作用,过会就被检测出阻断.
另外多个端口是用什么分割? 空格 逗号 还是分号?
能否有个配置例子? 多地址 多端口. 不同地址配不同端口等等

**Comment by jzp820927** [comment]
我这边电信网，DNS 只有污染，没有其他策略
我目前的情况，我觉得可能要用 DNSCurve/DNSCrypt 加密 DNS 协议，比较适合。按你所说，明文的数据，可能都会被拦截。
关于多接口多端口的监听地址的配置，配置文档有说明，举例如下：
配置文件：根目录 Config.conf
[Addresses]
监听IPV4所有接口：IPv4 Listen Address = 0.0.0.0:端口
监听IPV4指定接口：IPv4 Listen Address = IP1:端口1|IP2:端口2|IP3:端口3
监听IPV6所有接口：IPv6 Listen Address = ::
监听IPV6指定接口：IPv6 Listen Address = IP1:端口1|IP2:端口2|IP3:端口3

**Comment by chengr28** [comment]
1+2+5. 不清楚『阻断』是什么意思，如果是丢黑洞路由没有响应，那这个真不好说。至于想避免被检查设备识别，除了使用加密协议（非标准端口实际上不能避免这个问题，只是现在他们没有在做）外是无解的。

4.关于多重监听的问题：
  - `Operation Mode = Server` 就是等于绑定 `0.0.0.0/::` 不需要再填 `..Listen Address`
  - `Listen Port = 53|5353|..` 配合上一条配置，监听所有 TCP + UDP 的 53 + 5353 + .. 端口
  - 如果需要指定使用某个特定的地址，则请忽略上面的 2 个参数直接填写 `..Listen Address`
  - `IPv4 Listen Address = 192.168.1.28:53|192.168.1.228:5353` 类似这样

**Comment by chengr28** [comment]
@jzp820927 有可能需要同时打开不同实例的程序，同时监听不同方向的请求。主要是因为如果全都在同一个实例里完成，所有的过程基本都共享同一个资源有弊端，而且也考虑到有可能同一台服务器为不同方向提供解析服务时有可能要使用不同的配置。

**Comment by SeaHOH** [comment]
>有可能需要同时打开不同实例的程序，同时监听不同方向的请求。

串联？感觉可以 DIY。

**Comment by jzp820927** [comment]
@chengr28 策略路由？哦不对，应该叫 策略 DNS？

**Comment by liuxyon** [comment]
阻断就是直接让你无法连接到对方. 
日志显示是
 [Network Error] Socket connecting error: An operation was attempted on something that is not a socket[10038].

**Comment by chinaniupai** [comment]
@liuxyon 那抓包起什么作用？【抓包是过滤被污染的DNS】
买也不会买国内的。买国内有什么用【买国外的云服务器，那你还要Pcap_DNSProxy有啥用？国外的服务器经过GFW是会被污染的，买国内的服务器直接获取被过滤后的结果】

**Comment by liuxyon** [comment]
看看这是什么原因

[Network Error] Socket connecting error: A non-blocking socket operation could not be completed immediately[10035].
[2017-06-21 21:27:38] -> [Network Error] Socket connecting error: An operation was attempted on something that is not a socket[10038].
[2017-06-21 21:27:39] -> [Network Error] Socket connecting error: An invalid argument was supplied[10022].

**Comment by liuxyon** [comment]
@chinaniupai  自己有服务器

**Comment by chengr28** [comment]
UDP 被阻断的效果是超时没响应，程序是不会有日志的，如果不确定可以尝试在请求解析域名时抓包调查一下网络的情况。至于这些日志是不是有问题，这边也会进行检查，建议下次更新后可以再试试。

**Comment by liuxyon** [comment]
使用什么工具抓取好?

**Comment by jzp820927** [comment]
Wireshark

**Comment by liuxyon** [comment]
发现UDP不工作, 如果我只设置IPV6+UDP,那么就任何都不能解析.

**Comment by chengr28** [comment]
你确定运行程序的机器支持 IPv6？

**Comment by liuxyon** [comment]
当然支持IPV6了, 上游我只使用的IPv6 DNS. TCP 普通域名可以解析.

**Comment by chengr28** [comment]
TCP 正常那多半是因为不是原生的 IPv6 抓包模块只支持 PPPoEv6 和原生的 IPv6 使用隧道之类的，要启用直接请求模式，参见 ReadMe 文档 **特别注意** 一节中对 `Direct Request` 参数的介绍。

**Comment by liuxyon** [comment]
[Network Error] Socket connecting error: An operation was attempted on something that is not a socket[10038].
[2017-06-23 22:44:42] -> [Network Error] Socket connecting error: An invalid argument was supplied[10022].

**Comment by liuxyon** [comment]
这样吧QQ远程你看看?

**Comment by liuxyon** [comment]
Direct Request = IPv6  这样有改善,UDP可以用了.

[DNS]
Outgoing Protocol = IPv6 + UDP
Direct Request = IPv6
Cache Type = Timer + Queue
Cache Parameter = 512
Cache Single IPv4 Address Prefix = 0
Cache Single IPv6 Address Prefix = 0
Default TTL = 3600

[Local DNS]
Local Protocol = IPv6 + UDP+ TCP
Local Force Request = 0
Local Hosts = 0
Local Main = 1
Local Routing = 1

**Comment by liuxyon** [comment]
有改善但日志还出现错误. UDP 现在能解析封锁域名. 只是不是很稳定. 查询在3000ms左右


[Network Error] Socket connecting error: An operation was attempted on something that is not a socket[10038].
[2017-06-24 00:17:39] -> [Network Error] Socket connecting error: An invalid argument was supplied[10022].

**Comment by chengr28** [comment]
刚才已经更新了版本，可以用新的版本试试，报错的问题应该会有所缓解。之前看了一下提到的错误记录，有不少看起来是程序内部处理的问题，可能是网络状况比较差的时候才会触发，平时就算是超时响应理论上应该也是没有日志的。

**Comment by chengr28** [comment]
如果实在不清楚网络的情况，可以尝试在程序运行时在运行程序的机器上使用 Wireshark 之类的软件抓包，这边可以分析一下具体的情况，不方便公开的话可以发到我的邮箱，还有问题可以直接在这里继续回复，谢谢。

**Comment by liuxyon** [comment]
还是有错误,不知道什么原因?
Socket connecting error: An invalid argument was supplied[10022].
[Network Error] Socket connecting error: An operation was attempted on something that is not a socket[10038]

**Comment by chengr28** [comment]
如果不影响使用那就先用着，这个问题可能有时间需要详细调查一下。主要是因为没有 IPv6 的环境，出了问题也不好做测试。

**Comment by jzp820927** [comment]
这个 IPV6 的报错，确实不影响使用，我以前把我 Linux 服务器的 IPV6 关了，也会一直报这个错，但是可以正常使用。后来把 IPV6 开启了，就没有这个报错了。
