### ISSUE TITLE
Local Force Request开启导致google无法解析

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#255]
﻿### Version/使用的版本/使用的版本
0.4.9.0

### Running Environment/运行环境/運行環境
win7 X64

### Actual/实际情况/實際情況
原版`config.ini`修改内容
```
Local Force Request = 1
Local Hosts = 1
Local Main = 0
Local Routing = 0
```
导致解析`www.google.com`无回复
删除或清空`WhiteList.txt`后解决了问题, 但并没在里面找到对应的匹配规则

**Comment by jzp820927** [comment]
不应该啊，google 的域名怎么会匹配到 local 上呢？

**Comment by cjjdaq** [comment]
这个问题我之前就提了呀。Local Hosts模式下无法解析www.google.com

**Comment by muink** [comment]
那我这里还是有点区别的`Local Force Request = 0`的话, 我这就能解析

**Comment by jzp820927** [comment]
看来要抓包才能解决了。

**Comment by muink** [comment]
抓包应该没什么用
问题要么是程序内部处理白名上有问题, 要么是白名单有问题
步骤都处于向服务器请求dns之前
应该大致就是`www.google.com`不知怎么匹配走了本地解析, 而且还开了本地域名强制本地解析
然后得到的都是污染的结果, 被过滤了之后就啥都不剩了

**Comment by jzp820927** [comment]
好吧，等 C 大来发布权威解释。

**Comment by cjjdaq** [comment]
pcap没有详细的日志，所以出现这种问题我们也不知道啥原因。

**Comment by jzp820927** [comment]
配置文件里面好像可以设置日志级别。不过我很少看日志，你们可以试试

**Comment by chengr28** [comment]
@cjjdaq @jzp820927 那个 `Error.log` 的系统设计上是遇到比较重大的提示或者错误才会报告的，个人是觉得运行流水（我对『详细的日志』的理解是这样，就是类似用什么服务器解析了什么域名，某个解析结果是从哪个具体的服务器得来之类的）平时正常工作时用处不大，而且消耗磁盘 I/O 当然最关键的是写这个功能基本也是大修大改的节奏……

**Comment by chengr28** [comment]
关于这个 Issue 提到的问题，这个的确可以是一个 bug 产生的过程和程序处理的流程有关：
- 读取配置文件，倒序（`www.google.com` → `moc.elgoog.www`）储存
- 查询白名单时倒序对比查询（`moc.elgoog.www` = `moc.elgoog.www`？）
- 这里为了实现 dnsmasq 的匹配效果，只会对比两者较短者的长度，并以查询的域名为准

但是实现时没有考虑到子域名的问题，导致：

- 自带白名单的 `Local Hosts` 里有一个域名 `le.com`
- 倒序储存 `moc.el` 后与 `moc.elgoog.www`
- 由于没有考虑这个问题 `moc.el` → `moc.el` 返回匹配成功的结果

下次更新应该会修复这个问题。

**Comment by jzp820927** [comment]
想不到过程这么复杂。涨姿势了。

**Comment by cjjdaq** [comment]
@就是增加个参数 比如--debug时候才会有流水日志，这样方便排查问题。正常使用下不产生日志

**Comment by jzp820927** [comment]
这个建议倒是不错，不说 C 大的意思，要加详细日志，得大修大补，估计就算要做，也不是短期能做好的吧。

**Comment by chengr28** [comment]
@cjjdaq 看这要求达到的效果，基本就是每做一个判断每做一个动作就得产生一个日志……其实，把时间留去做更有意义的事情不是更好？

**Comment by SeaHOH** [comment]
C 大真神人，只用抓包加脑补就把 Pcap_DNSProxy 做得如此之好，太厉害了！ :pray:

**Comment by muink** [comment]
xD那等下版更新了

**Comment by cjjdaq** [comment]
@chengr28 只要就这个日志就好了
 * 使用系统 API函数进行域名解析（大部分）：系统 Hosts > Pcap_DNSProxy 的 Hosts 条目（Whitelist/白名单条目 > Hosts/主要 Hosts 列表） > DNS 缓存 > Local Hosts/境内 DNS 解析域名列表 > 远程 DNS 服务器
  * 直接从网络适配器设置内读取 DNS 服务器地址进行域名解析（小部分）：Pcap_DNSProxy 的 Hosts 配置文件（Whitelist/白名单条目 > Hosts/主要 Hosts 列表） > DNS 缓存 > Local Hosts/境内 DNS 解析域名列表 > 远程 DNS 服务器
  * 请求远程 DNS 服务器的优先级：Direct Request 模式 > TCP 模式的 DNSCurve 加密/非加密模式（如有） > UDP 模式的 DNSCurve 加密/非加密模式（如有） > TCP 模式普通请求（如有） > UDP 模式普通请求

**Comment by chengr28** [comment]
刚才的更新应该已经解决这个问题了，可以试试。如果还是不行直接在这里回复就行，感谢反馈。
