### ISSUE TITLE
网络显示无法连接到internet

### ISSUE THREAD

**Issue by hnsylzg** [chengr28/Pcap_DNSProxy#257]
﻿### Version/使用的版本/使用的版本

0.4.9.0

### Running Environment/运行环境/運行環境

Windows10 1703 +kcptun + meow（使用shaodowsock代理）翻墙

### Expectation/期望情况/期望情況

windows10 1607版一切正常

### Actual/实际情况/實際情況

事实上网络可以正常使用，也可正常翻墙，但是网络会显示无法连接到internet，并显示叹号。

**Comment by jzp820927** [comment]
这个是 DNS 软件，不是翻墙软件。

**Comment by chengr28** [comment]
暂时先标上 bug 的 Tag 了……Windows 那个网络感应指示器（NSCI）的相关文章在 https://technet.microsoft.com/en-us/library/cc766017(v=ws.10).aspx 有，里面有几个域名应该与此有关。这边检查是发现程序内置的黑名单拦截了其中一个的 IPv6 地址（这个地址实际上是类似私有网络的地址）有可能导致这个问题。但是后来实测发现 1703 后 NSCI 的规则似乎复杂了很多，并不单纯依靠刚才那篇文章介绍的步骤工作，出来的效果就是很长一段时间感叹号才会消失，这个具体可能要调查一下。

**Comment by hnsylzg** [comment]
一般的程序能正常联通，好像有些系统的程序比如说反馈，好像只要叹号出现就不能连通，我使用的是静态地址，用系统的疑难解答，会提示我要重置网络，或者用以太网点右键的诊断会提示要我使用dhcp来获取ip，点确定自动改成dhcp后，叹号会会消失，但是重启后又会出来。这是我的一些尝试

**Comment by chengr28** [comment]
根据这边抓包的结果，看起来 1703 里这个 NSCI 还和 Windows 的遥感服务有关系……总之就是一连串很复杂的检测操作，也不能排除和网络状况（Microsoft 有可能解析到境外）有关。这边的建议是等待一段时间，应该都会自动消失。

**Comment by hnsylzg** [comment]
我这边情况是始终不消失

**Comment by chengr28** [comment]
下次更新会把错误屏蔽 NSCI IPv6 地址的问题修复，到时候再试试看……比较好。

**Comment by hnsylzg** [comment]
到时再试吧

**Comment by chengr28** [comment]
刚才的更新已经解决这个问题了，可以试试，有问题再在这里回复就行，感谢反馈。

**Comment by hnsylzg** [comment]
很久没关注这个，因为虽然显示叹号，但是网络是通的，今天更新最新版还是有叹号。把dns改成任一都能消除叹号.

**Comment by hnsylzg** [comment]
还是没有解决。显示叹号。

**Comment by chengr28** [comment]
你可以试试把网络适配器中 DNS 服务器（IPv4 和 IPv6）地址换成非回环地址看看，这边经过测试发现更换后叹号消失的时间有很大几率会比原来回环（`127.0.0.1` 和 `::1`）快，可能和系统内部的工作流程有关 。当然仔细想想，也可能会和系统域相关的设置有关，也可以尝试调整。

**Comment by hnsylzg** [comment]
偶尔也会不显示叹号，换了换成非回环地址叹号就马上消失，不过能用就不管这么多了。

**Comment by chengr28** [comment]
看来的确是回环地址的问题……

**Comment by chengr28** [comment]
Server/Proxy 模式是绑定在通用地址上的，往任意网卡的同一端口发请求都能收到。

**Comment by muink** [comment]
。。。
突然想起来当初为什么这么设置而不是直接0.0.0.0了
个人的情况是在本程序前加了个前置的dns缓存程序，然后那玩意儿只能绑127.0.0.1
防止冲突就把程序绑到虚拟网卡上了

**Comment by zhangyz1997** [comment]
将[这篇文档](https://support.microsoft.com/en-us/help/4494446/an-internet-explorer-or-edge-window-opens-when-your-computer-connects)中的域名手动解析加入系统的hosts似乎就没问题了，也许对这几个域名需要特殊处理一下?

**Comment by chengr28** [comment]
但是经过测试，这个域名是可以正常解析的，并没有发现有问题。程序里会拦截主要还是那个 `IPFilter.ini` 里可能会有一些保留地址的限制，之前出问题的是 `dns.msftncsi.com`。

**Comment by zhangyz1997** [comment]
> 但是经过测试，这个域名是可以正常解析的，并没有发现有问题。程序里会拦截主要还是那个 `IPFilter.ini` 里可能会有一些保留地址的限制，之前出问题的是 `dns.msftncsi.com`。

有没有可能是解析得延迟太久造成的系统的误判（没啥证据，瞎猜的

**Comment by chengr28** [comment]
这个还真不好说，不过理论上应该不会，巨硬似乎也没有这方面（重试次数，重试时间？）具体的数据。之前有专门为此问过不少用家，基本都是说虽然比原来直接填 DNS 地址要慢，但是最终这个无法连接的提示还是会消失的，小则几秒多则两三分钟。
