### ISSUE TITLE
路由表不全

### ISSUE THREAD

**Issue by LisonFan** [chengr28/Pcap_DNSProxy#258]
我有个国内的 VPS IP 是 119.29.160.xx 都不在路由表里

**Comment by SeaHOH** [comment]
更新

**Comment by chengr28** [comment]
路由表可以通过自带的 Tools/Update_Routing 批处理/脚本自动生成，这边每次更新的时候也会顺便更新自带的版本，使用的是 APNIC 的版本。不清楚这个版本的情况，不过应该是比较正式的，如果有遗漏的可以自己编辑配置文件，加进去就行。

**Comment by LisonFan** [comment]
@chengr28 我有一个建议，能不能把 APNIC 和 [IPIP]
(https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt "IPIP") 这个库综合一下？

**Comment by SeaHOH** [comment]
@LisonFan 
你可以提交一个 Update_Routing 的 pr，不能什么工作都让 C 大一人来做。

**Comment by chengr28** [comment]
@LisonFan 既然是重点针对天朝的，那还不如直接用 IPIP 的……
