### ISSUE TITLE
OpenService 失败 1060该怎么解决

### ISSUE THREAD

**Issue by Mortalit** [chengr28/Pcap_DNSProxy#259]
[SC] OpenService 失败 1060:

指定的服务未安装。

[SC] OpenService 失败 1060:

指定的服务未安装。

错误: 没有找到进程 "Pcap_DNSProxy.exe"。
[SC] CreateService 成功
操作成功完成。
操作成功完成。
[Notice] Windows Firewall test is successful.
[SC] ChangeServiceConfig2 成功
[SC] ChangeServiceConfig2 成功

SERVICE_NAME: PcapDNSProxyService
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x2
        WAIT_HINT          : 0x3e8
        PID                : 7520
        FLAGS              :

Windows IP 配置

已成功刷新 DNS 解析缓存。

请按任意键继续. . .

**Comment by Mortalit** [comment]
nslookup www.google.com 127.0.0.1
服务器:  pcap-dnsproxy.server
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 pcap-dnsproxy.server 超时

nslookup -vc www.google.com
服务器:  pcap-dnsproxy.server
Address:  127.0.0.1

名称:    WWW.gooGle.cOM
Address:  2404:6800:4008:803::2004

这算是成功了吗,没有错误文件产生

**Comment by chinaniupai** [comment]
[Windows.txt](https://github.com/chengr28/Pcap_DNSProxy/files/1114180/Windows.txt)

**Comment by chinaniupai** [comment]
下载这个，然后把TXT改成zip

**Comment by chinaniupai** [comment]
然后把你原来那个打开bat，输入2回车，然后打开我这个输入1

**Comment by chengr28** [comment]
其实……bat 运行提示这个是正常的，上次有人提类似问题的时候就在当次更新时修改了一下说明文档，最重要是看程序能不能成功提供域名解析，而不是看 bat 显示的是什么……
