### ISSUE TITLE
Mac版pcap_datalink 返回值不是DLT_EN10MB，导致出错

### ISSUE THREAD

**Issue by SteveGuo** [chengr28/Pcap_DNSProxy#26]
如题， 我电脑上返回值是138
查了一下是
#define DLT_APPLE_IP_OVER_IEEE1394 138

**Comment by chengr28** [comment]
138 是 IEEE 1394 接口呢……用的转换器连接网络？

**Comment by SteveGuo** [comment]
没有用转换器，同一台电脑，Windows那边就是正常的，Mac这里就有这个问题

**Comment by chengr28** [comment]
那么程序是否能正常解析域名呢？因为抓包模块默认是尝试打开所有可用适配器的，如果只是其中一个次要的适配器类型不匹配，而不是主要的 Ethernet 网络适配器，那么有可能纯粹只是一个错误提示而已，不会对正常使用有影响……

**Comment by SteveGuo** [comment]
//Check device type(Linux/Mac)
	mbstowcs(DrviceName, pDrive->name, strlen(pDrive->name));
	if (pcap_datalink(pAdHandle) != DLT_EN10MB) //Ethernet
	{
		if (pcap_datalink(pAdHandle) != DLT_NULL) //BSD loopback encapsulation
		{
			static const wchar_t *PcapDatalinkError = L" is not a Ethernet device";
			wcsncpy(ErrBuffer, DrviceName, wcslen(DrviceName));
			wcsncpy(ErrBuffer + wcslen(DrviceName), PcapDatalinkError, wcslen(PcapDatalinkError));
			PrintError(LibPcap_Error, ErrBuffer, NULL, NULL);
		}

		delete[] ErrBuffer;
		delete[] Addr;
		delete[] Buffer;
		delete[] DrviceName;
		pcap_close(pAdHandle);
		return EXIT_FAILURE;
	}

这里如果返回值不等于DLT_EN10MB就直接结束退出了

**Comment by chengr28** [comment]
哦看来是太久没更新的缘故，都忘 Mac 的工作机制了……Windows 里是互不干扰的，Mac 是旧的机制所以看 RP 就是如果那个设备在 Ethernet 后面就没事……
其实这里是加了一层保险，如果确定没事可以直接把 `if (pcap_datalink(pAdHandle) != DLT_EN10MB) //Ethernet` 到 `return EXIT_FAILURE;\n}` 整段注释掉也行

**Comment by SteveGuo** [comment]
这里有点介绍哦
http://taosecurity.blogspot.com/2006/01/freebsd-networking-over-firewire-you.html

**Comment by chengr28** [comment]
你好，昨晚的更新里已经支持 Apple IEEE 1394/FireWire 了，不过因为暂时只有 Windows 版的在更新……最近已经在准备 Linux 版的事情，OS X 会在 Linux 版搞掂之后就更新w

**Comment by SteveGuo** [comment]
非常感谢！
