### ISSUE TITLE
你好，我想使用其他的公共的DNS，可Config里必须要输入ip地址+端口。我查不到对方的端口

### ISSUE THREAD

**Issue by jorismq** [chengr28/Pcap_DNSProxy#260]
为什么要这样设置？如何查询其他公共DNS的端口？
谢谢

**Comment by SeaHOH** [comment]
公共 DNS 全都支持标准端口，不然就不叫公共。自己搜索一下什么是 DNS 就知道了。

**Comment by jorismq** [comment]
那为什么同一个国外DNS地址，我在电脑-网络连接里面改了就可以用，而手输到Config文件里面，保留53端口，然后输nslookup命令总是提示timeout？？？？

**Comment by SeaHOH** [comment]
请问你重启 Pcap_DNSProxy 没有？系统 DNS 设置是什么？nslookup 命令都输入了些什么参数？
不要总是搞些什么都没有的问题。

**Comment by jorismq** [comment]
重启了。我win10、系统DNS是127.0.0.1
用默认的Config就行。nslookup www.youtube.com 127.0.0.1。可以返回ip地址
而把默认的改成其他的DNS，如208.76.50.50（可以ping通）。保留53端口
重启proxy，再输nslookup www.youtube.com 127.0.0.1，就timeout了
换回默认的Config又可以了。
不是端口的问题？那是什么原因？怎么处理？

**Comment by SeaHOH** [comment]
这个服务器可以 Ping 通，但是 UDP 根本就不通， 至少我这里是这样。
而且也不要用 `www.youtube.com` 来测试，换个微软啥的多好。

**Comment by jorismq** [comment]
换微软的？应该没被污染吧。。。。那用Pcap_DNSProxy干啥？
如果是这样，那我手动改了网络连接里面两个DNS地址又有啥不同呢？
合适的DNS服务器太难找了。。。。。

**Comment by SeaHOH** [comment]
测试测试测试，三遍完，不跟你罗嗦了。

**Comment by jzp820927** [comment]
@jorismq 你上面用的那个 DNS 应该不是 DNS ，或者是已经失效了。一般找专门的 DNS 服务商的 DNS，会稳定一些，比如 google，opendns 之类的，不知道你有什么需求，要用到第三方的 DNS 服务器，我认为默认配置的 DNS 服务器就可以很好的解决问题了。

**Comment by chengr28** [comment]
- DNS 协议使用 `53` 端口提供域名解析，这个是标准规定的，所有标准的公共 DNS 服务器都应该支持。
- 可以 Ping 通和能不能进行域名解析是两回事，Ping 所用的和 DNS 是完全不一样的协议。
- `nslookup www.bing.com 208.76.50.50` 是使用 `208.76.50.50` 对 `www.bing.com` 进行解析，刚好测试用的域名是属于微软的而已，这个和使用的 DNS 服务器有什么关系？我还可以换成 `nslookup github.com 208.76.50.50` 还有 `nslookup www.gov.cn 208.76.50.50` 呢……
- 一个建议是……先搞清楚 DNS 是什么，以及本工具有什么用途再来发问比较好。
