### ISSUE TITLE
EDNS 如何正确开启

### ISSUE THREAD

**Issue by luolufang** [chengr28/Pcap_DNSProxy#262]
﻿### Version/使用的版本/使用的版本

4.9.0

### Running Environment/运行环境/運行環境

win server 2012

### Expectation/期望情况/期望情況

客户端A 请求DNSPOD，DNSPOD把来源A的IP作为原地址 加入edns  然后请求114.114.114.114
并把114.114.114.114 返回的结果 回传给A。

场景就是各个全国用一台dns翻墙，但是解析的国内cdn地址各有差异。

### Actual/实际情况/實際情況

应该开启那些开关 ，查阅了之前的issue 和文档 感觉不是很明白

**Comment by jzp820927** [comment]
你的标题是不是打错了？“如果”应该是“如何”吧？
另外文档写的很详细，不知道你看文档了没有？

**Comment by luolufang** [comment]
@jzp820927 文档有读过只是以下这种配置感觉不起作用
```

[Addresses]
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 219.137.148.58/32
IPv4 Main DNS Address = 8.8.4.4:53
IPv4 Alternate DNS Address = 8.8.8.8:53|208.67.220.220:443|208.67.222.222:5353
IPv4 Local Main DNS Address = 114.114.115.115:53
IPv4 Local Alternate DNS Address = 223.6.6.6:53



[Switches]
Domain Case Conversion = 1
Compression Pointer Mutation = 0
EDNS Label = 1
EDNS Client Subnet Relay = 1
DNSSEC Request = 0
DNSSEC Validation = 0
DNSSEC Force Validation = 0
Alternate Multiple Request = 0
IPv4 Do Not Fragment = 0
IPv4 Data Filter = 0
TCP Data Filter = 1
DNS Data Filter = 1
Blacklist Filter = 1
Strict Resource Record TTL Filter = 0

```

**Comment by jzp820927** [comment]
你是怎么确定，没有起作用的呢？
另外，你的 pcap 是运行在本机的？还是运行在单独服务端的?

**Comment by chengr28** [comment]
如果是 EDNS 功能相关的花，原理在 https://github.com/chengr28/Pcap_DNSProxy/issues/240 和 https://github.com/chengr28/Pcap_DNSProxy/issues/248 都有提到。

**Comment by muink** [comment]
运行在本地端, EDNS Client Subnet设置是没有意义的...
