### ISSUE TITLE
 DNS request timed out—Timeout was 2 seconds.

### ISSUE THREAD

**Issue by smusicsanshu** [chengr28/Pcap_DNSProxy#264]
﻿### Version/使用的版本/使用的版本

0.4.9.2

### Running Environment/运行环境/運行環境

win10 64位

**更新之后测试工作状态出现一下内容：**

> C:\Users\smusic>nslookup www.google.com
> 服务器:  pcap-dnsproxy.server
> Address:  127.0.0.1
> 
> DNS request timed out.
>     timeout was 2 seconds.
> DNS request timed out.
>     timeout was 2 seconds.
> 非权威应答:
> DNS request timed out.
>     timeout was 2 seconds.
> 名称:    wwW.GooGLE.COm
> Address:  172.*.*.132

**请问：**
> DNS request timed out.
>     timeout was 2 seconds.

> **这个状态是不是出错了？**

**Comment by chengr28** [comment]
这个之前有人也提过 Issue 其实是因为程序请求域名解析的步骤比较多，耗费的时间比较长造成的，因为 Windows 系统自带的 `nslookup` 默认超时是 2 秒，所以看起来经常超时，而从提供的信息来看解析其实是没有问题的。当系统协议栈真正进行解析时，超时时间远远比 2 秒要长，所以其实没有实质的影响，只是访问网站时的观感不太好，这个就要依靠 DNS 缓存之类的辅助功能解决了，这个 ReadMe 说明文档有介绍。

**Comment by smusicsanshu** [comment]
OK，明白啦，收到您这么详细的回答很感谢。

**Comment by chinaniupai** [comment]
@chengr28 请问本软件带DNS缓存吗？

**Comment by chengr28** [comment]
@chinaniupai 有，参见 ReadMe 说明文档的介绍。
