### ISSUE TITLE
Domain Test Protocol 

### ISSUE THREAD

**Issue by liuxyon** [chengr28/Pcap_DNSProxy#265]
﻿### Version/使用的版本/使用的版本

0.4.9.2

### Running Environment/运行环境/運行環境

win 2016

### Actual/实际情况/實際情況
当增加TCP时候，就不断自动停止服务. 什么原因？
Domain Test Protocol = UDP + TCP

**Comment by chengr28** [comment]
直接以管理员权限运行 exe 有收到什么提示，或者程序目录有生成什么 Error.log 之类的吗？

**Comment by liuxyon** [comment]
没有什么特殊日志
日志里只发现有
[2017-07-24 15:17:01] -> [Notice] Pcap_DNSProxy started.
[2017-07-24 15:17:01] -> [Parameter Error] IPv4 address format error in E:\Pcap_DNSProxy\Windows\Config.ini(Line 41).

查询后该41行参数我并没有设置

IPv4 EDNS Client Subnet Address =

**Comment by liuxyon** [comment]
目前是这样配置的
[Data]
ICMP ID = 
ICMP Sequence = 
ICMP PaddingData = 
Domain Test Protocol = UDP 
Domain Test ID = 
Domain Test Data = 189.cn 
Local Machine Server Name =

**Comment by chengr28** [comment]
方便提供完整的配置文件吗？如果发到这里不太好可以发到我的邮箱，这边可以看看。因为从报错的信息来看，不能启动服务是因为读取参数遇到错误导致的……

**Comment by chengr28** [comment]
看起来没有回应？这个其实看起来比较像是特定的配置文件导致程序触发了读取上的问题，但是苦于没有样本，无法验证这个猜测……任何时候都可以在这里提供一份会出问题的样本，这边都会进行测试，谢谢。

**Comment by liuxyon** [comment]
邮箱给我，最近忙没时间上来。

**Comment by chengr28** [comment]
我的 Profile 里有
