### ISSUE TITLE
googleads.g.doubleclick.net 就算强制经国外VPS代理解析，返回结果依然是国内IP

### ISSUE THREAD

**Issue by kalerice** [chengr28/Pcap_DNSProxy#266]
﻿### Version/使用的版本/使用的版本
Pcap_DNSProxy-0.4.9.2

### Running Environment/运行环境/運行環境
CentOS Linux release 7.3.1611
3.10.0-514.26.2.el7.x86_64

### Expectation/期望情况/期望情況
googleads.g.doubleclick.net 解析到国外的IP

### Actual/实际情况/實際情況
解析到了中国的IP。

cmd:
nslookup googleads.g.doubleclick.net

服务器:  pcap-dnsproxy.server
Address:  192.168.*******

非权威应答:
名称:    pagead46.l.doUbLeClick.nEt
Addresses:  2401:3800:4002:802::101a
          203.208.40.58
          203.208.40.57
          203.208.40.45
Aliases:  googLeads.g.doUbLeClick.nEt

就算经代理至VPS向8.8.4.4查询，一样是这个结果。抓包确认的确是从VPS发出查询。
而在VPS上直接解析这个域名，就是国外的。
这是什么原因呢？为什么就算VPS代理发出查询依然会解析到国内IP？阿里云和vultr都是一样。

**Comment by SeaHOH** [comment]
开了 EDNS？
但是解析出国外 IP 有用吗？干扰很严重吧。

**Comment by kalerice** [comment]
木有开EDNS呢，因为不了解这个。
主要是我在用户端结合chnroute食用，域名和IP分流的情况下，有时候浏览网页会莫名其妙显示“连接已重置”，尤其出现在Youtube的广告栏和某些有外链视频的网站。

**Comment by SeaHOH** [comment]
刚发现 `WhiteList.txt` 有一条 `Server=/doubleclick.net/`，你去掉试试。
另外，感觉 chnroute 不太好用吧。

**Comment by kalerice** [comment]
@SeaHOH 

> 刚发现 WhiteList.txt 有一条 Server=/doubleclick.net/，你去掉试试。`

白名单去掉注释的话就更会使用国内解析的结果了（如果开启了`Local Hosts`使白名单起作用的话）

再研读文档几遍后知道了，

` * 注意：关于 Local Force Request 和 Local Hosts 和 Local Routing 的组合说明`
`    * 所有参数均为关闭时：直接跳过使用境内服务器进行域名解析的过程`

由于解析到的`203.208.*`的地址匹配到`Routing.txt`里的`203.208.0.0/20`，所以无论如何，只要`Local Routing=1`都使得它只使用境内DNS服务器的解析。
把Local DNS区域的参数都关闭，就可以使用境外的解析。
不过这样就等于没有DNS分流。

我能研究到的比较容易维护的方法是将要使用境外解析的网站填在Hosts.conf，指定为香港的节点。一条CNAME规则就可以对应多个域名。
`[CNAME Hosts]`
`216.58.199.2|216.58.199.6 .*\.doubleclick.net`
`216.58.199.2|216.58.199.6 .*\.google.com`
`216.58.199.2|216.58.199.6 .*\.googlevideo.com`

但是这种网站如果多起来还是很麻烦。

接着，回到一开始的奇怪的现象，当`Local Routing = 1`且`SOCKS Proxy = 1`时，按照文档应该是先等待境内服务器返回的结果，再向境外服务器发起查询。
`  * Local Routing - 境内路由表识别功能：开启为 1 /关闭为 0`
`    * 本功能开启后所有请求都会先发送至境内服务器进行域名解析，再根据解析结果进行下一步的操作`
实际上并非如此，而是同时向境内境外发起查询。于是在VPS抓包见到有发往8.8.4.4的查询，而Pcap_DNSProxy却**只采纳了向境内服务器查询所返回的结果**。

现在发现一个问题：
成功匹配到`Routing.txt`的境内服务器结果，由于`Local Routing = 1`，最后肯定会**只采纳向境内服务器查询所返回的结果**；不过事实上Pcap_DNSProxy并没有在得到了境内服务器返回结果后就**立刻中断查询步骤并返回结果给用户**，而是**一直等待直到经SOCKS Proxy返回了境外服务器解析结果之后才结束整个查询工作**。

我猜测，同时发往境内和境外是为了节省时间（这个处理方式已经与文档有出入了，是吧？）。
而要等待境外服务器的结果到来了，才返回一个与之不相关的境内服务器结果给到用户，应该是一个BUG？

**Comment by SeaHOH** [comment]
>* 注意：关于 Local Force Request 和 Local Hosts 和 Local Routing 的组合说明
>    * 所有参数均为关闭时：直接跳过使用境内服务器进行域名解析的过程
>    * 默认情况下在境内服务器解析失败会进行下一步的操作
>    * 只开启 Local Hosts 时：将按照（黑）白名单（无）命中规则的域名，才（不）使用境内服务器进行解析
>      * 开启 Local Force Request 参数时，则强制已命中规则的域名只能使用境内服务器进行解析
>    * 只开启 Local Routing 时：所有请求都会先发送至境内服务器进行域名解析，然后根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者
>    * 同时开启 Local Hosts 和 Local Routing 时：所有（除了黑名单所指定的）请求都会先发送至境内服务器进行域名解析，然后根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者
>      * 开启 Local Force Request 参数时，则强制已命中规则的域名只能使用境内服务器进行解析

你的具体设置是？
你想要国外 IP 的话，我觉得应该是上面**只开启 Local Hosts 时**的情况，但是需要手动更新一次 `Update_WhiteList.sh` 排除谷歌域名。
另外，那个未及时返回结果要等 @chengr28 确认是否是 bug。

**Comment by LisonFan** [comment]
google dns 支持 edns 啊，等于你用 Google dns 来解析 googleads.g.doubleclick.net，Google dns 在发请求的时候回带上请求者的 IP，这样解释理解了吧？

**Comment by LisonFan** [comment]
中科大的 DNS 不支持 EDNS，用中科大的 DNS 来解析这个域名就不会是国内的 IP 了。
![image](https://user-images.githubusercontent.com/9424775/28818815-d99a557a-76de-11e7-9ff0-fff22621ca77.png)

**Comment by SeaHOH** [comment]
>google dns 支持 edns 啊

@LisonFan 好像不太对，通过 VPS 代理结果也是国内 IP。
难道 google dns 会检查代理来源 IP？ @kalerice 的 VPS 代理是非匿名的？

**Comment by LisonFan** [comment]
@SeaHOH 

![image](https://user-images.githubusercontent.com/9424775/28830514-80da59f0-7709-11e7-8129-acba6f45a8c5.png)


GCE TW

**Comment by SeaHOH** [comment]
我是说 kalerice 的情况不是因为 google dns 支持 edns，不是说 google dns 不支持 edns。
GCE 可以搞匿名啊。

**Comment by kalerice** [comment]
我用的是默认配置
`Local Hosts = 0`
`Local Routing = 1`
`EDNS Label = 0`

我在这次的问题中，使用的代理模式是在本地使用shadowsocksr-libev的ss-local来接收Pcap_DNSProxy的代理请求数据。
为什么拿到国内IP的原因我已经知道是由`Local Routing = 1`所致。
edns暂时对我应该没什么用。谢谢 @LisonFan  的解释。

> 另外，感觉 chnroute 不太好用吧。
@SeaHOH  那还有什么比chnroute要好的呢？我知道有bestroutetb，但它的路由压缩算法是有损压缩，我需要访问的不止日本美国香港新加坡这些地区，还有俄罗斯土耳其波兰这些但是bestroutetb不支持。

**Comment by SeaHOH** [comment]
我可能搞错了，你是用在 iptables 还是单独的程序里面？
我第一反应是前者，觉得这样不好用，后者就无所谓。
不过你这样用代理流量很大。

**Comment by kalerice** [comment]
@SeaHOH chnroute用在Windows里面呢。在本机就分流了，目的IP是国内和公司内网的TCP包就走网管DHCP分配的网关，目的IP是国外的TCP包就用VPN引到Linux主机，由Linux主机的iptables的redirect转发至ssr-libev的redir模式服务端。所以流量不大哦。

**Comment by SeaHOH** [comment]
那就还是默认的 VPN 分流方案，感觉要配置的东西太多了，出问题时不好排查。
我这种 Windows 老古董不太习惯 Linux 思维方式~

**Comment by kalerice** [comment]
的确要配置的东西非常非常多。。。不过挺适合企业内多人使用，尤其是网管不协助搭梯子的情形。

**Comment by chengr28** [comment]
上面一大段话，看起来好像尝试了不少的配置……大概是：
- 程序对于单个请求流程（例如 Local 或者 SOCKS 或者境外请求之类）的确是按顺序的逻辑，不存在并发的情况……实际上要改成并发还有不少难度，唯一的可能性是程序由于一定的配置或规则，没有接受某个流程所获得的解析结果，而不被接受的解析结果会被即时丢弃。
- `Local Routing` 和 `Local Host` 这 2 个选项正如字面意思，既然这个域名不论白名单还是路由表都有，那么只要开启就肯定会拿到境内服务器的解析结果。
- 在 SOCKS 的服务端抓包看到有请求，说明程序（在排除 Local 请求后）的确是有继续进行 SOCKS 协议的请求，然而从上面看出这个过程应该是失败了的，然后程序放弃 SOCKS 流程并继续下一步操作。下一步是直接请求 + 本地抓包，非常巧合的是这个域名在天朝境内直接请求境外的 DNS 服务器照样会获得境内的服务器地址，应该是 Google 做了特别的处理，支持 EDNS 的 DNS 服务器会向 NS DNS 呈递请求者的地址信息，发现来自天朝的请求就会解析成天朝的地址，之前提到的『与之不相关的境内服务器结果』应该指的就是这个。
- 个人觉得产生这种问题的关键可能是默认的 SOCKS 超时（就是 `Reliable Serial Socket Timeout` 参数）过短，在服务器返回结果前就已经超过超时时间，这边就会主动切断连接继续下一步操作。
- 如果不放心，可在本地进行抓包，观察 DNS 数据的收发情况。

**Comment by chengr28** [comment]
如果有任何更新可以直接回复，谢谢。
