### ISSUE TITLE
Ubuntu 16.04 LTS 编译完成后无法启动

### ISSUE THREAD

**Issue by huaxianyan** [chengr28/Pcap_DNSProxy#269]
0.4.9.0
Ubuntu 16.04.3 LTS

启动Linux_Install.Systemd.sh之后，终端会卡住，显示以下内容

> Created symlink from /etc/systemd/system/multi-user.target.wants/Pcap_DNSProxy.service to /etc/systemd/system/Pcap_DNSProxy.service.
> ● Pcap_DNSProxy.service - Pcap_DNSProxy, a local DNS server based on WinPcap and
>    Loaded: loaded (/etc/systemd/system/Pcap_DNSProxy.service; enabled; vendor pr
>    Active: active (running) since 三 2017-08-16 04:37:53 CST; 4ms ago
>   Process: 24545 ExecStart=/home/huaxianyan/Compile/Pcap_DNSProxy-0.4.9.0/Source
>  Main PID: 24546 (Pcap_DNSProxy)
>    CGroup: /system.slice/Pcap_DNSProxy.service
>            └─24546 /home/huaxianyan/Compile/Pcap_DNSProxy-0.4.9.0/Source/Release
> 
> 8月 16 04:37:53 7inaLaptop-Ubuntu systemd[1]: Starting Pcap_DNSProxy, a local DN
> 8月 16 04:37:53 7inaLaptop-Ubuntu systemd[1]: Started Pcap_DNSProxy, a local DNS

需要CTRL+C，错误log里显示

> [2017-08-16 04:22:22] -> [Notice] Pcap_DNSProxy started.
> [2017-08-16 04:22:22] -> [Network Error] Bind UDP Monitor socket error: Address already in use[98].
> [2017-08-16 04:22:22] -> [Network Error] Bind TCP Monitor socket error: Address already in use[98].
> [2017-08-16 04:32:49] -> [Notice] Pcap_DNSProxy started.
> [2017-08-16 04:32:49] -> [Network Error] Bind TCP Monitor socket error: Address already in use[98].
> [2017-08-16 04:32:49] -> [Network Error] Bind UDP Monitor socket error: Address already in use[98].

**Comment by chinaniupai** [comment]
艾特下老大好了，@chengr28

**Comment by jzp820927** [comment]
@huaxianyan  
 [Network Error] Bind UDP Monitor socket error: Address already in use[98].
53 端口占用，自己找找是什么进程占用了 53 端口，kill 掉就可以了

**Comment by huaxianyan** [comment]
@jzp820927 只有dnsmasq

> tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      5736/dnsmasq 
> udp        0      0 127.0.1.1:53            0.0.0.0:*                           5736/dnsmasq

**Comment by chengr28** [comment]
可以先使用如下的命令停止所有正在运行中的实例：
````
sudo systemctl stop Pcap_DNSProxy
sudo systemctl disable Pcap_DNSProxy
sudo killall Pcap_DNSProxy
````
需要先确认如果不是有其它程序在占用此端口，那基本上就是前一个正在运行的本程序占用了此端口导致后面启动的本程序（多开）无法使用此端口而报错。至于卡死的问题……可以进入二进制可执行文件所在的目录，使用：
````
./Pcap_DNSProxy --disable-daemon
````
普通模式启动程序，再观察是否在正常工作或者产生 `Error.log` 之类。

**Comment by chengr28** [comment]
@chinaniupai 全新提的 Issue 而不是讨论中的重要留言，不需要这样提醒我，项目这边每个人留言都是有通知的。

**Comment by huaxianyan** [comment]
@chengr28 

> root@7inaLaptop-Ubuntu:/home/huaxianyan/Compile/Pcap_DNSProxy-0.4.9.0/Source/Release# ./Pcap_DNSProxy --disable-daemon
> [2017-08-16 23:36:02] -> [Notice] Pcap_DNSProxy started.
> [2017-08-16 23:36:02] -> [Network Error] Bind UDP Monitor socket error: Address already in use[98].
> [2017-08-16 23:36:02] -> [Network Error] Bind TCP Monitor socket error: Address already in use[98].

用普通用户不加sudo去执行中间有2次会跳权限需求的框，看了下是对dnsmasq的操作，但是给了密码之后提示权限不够，用sudo执行或者切换root去执行则还是提示端口被占用

**Comment by jzp820927** [comment]
sudo killall dnsmasq

**Comment by huaxianyan** [comment]
折腾了好久这个事情，感觉上是这样

这个系统自带了一个dnsmasq，不受一般的方法的管控，杀掉就自启，Google的关闭的方法对他无效，但是可卸载，一卸载就把network manager那些东西全卸载了，网都无法上

我拿U盘装回来之后发现还是这个样子，然后apt又安装了一个以为可以覆盖，结果是另外一个dnsmasq，吃配置修改（包括改端口号，systemctl控制开关等），但是起进程和前面那个互不干扰，还是没有办法把那个端口释放出来

**Comment by chengr28** [comment]
那就没有办法了……因为如果需要架设和使用本地 DNS 代理类的工具，DNS 的 53 端口是必然需要占用的，不能两个程序都占用同一个端口，报错其实就是提醒这个情况。

**Comment by chengr28** [comment]
不过 dnsmasq 应该是有方法可以把 DNS 功能关掉的，可以寻找一下相关的文档，这边系统 53 端口默认情况不会有程序在使用。

**Comment by huaxianyan** [comment]
http://blog.csdn.net/gsls200808/article/details/39433149

参考了这篇文章，network manager自带的dnsmasq可以通过修改/etc/NetworkManager/NetworkManager.conf注释掉dns=dnsmasq的方法来关掉，需要重启才可以，直接kill不行。我之前也试过这个，但是发现kill之后会自启以为无效

然后把Pcap起起来可以正常nslookup，麻烦各位了

当时17.04没发现这个问题，换回LTS版本栽了个大跟头
