### ISSUE TITLE
最新版运行会提示不是有效的win32应用程序

### ISSUE THREAD

**Issue by c1024** [chengr28/Pcap_DNSProxy#27]
昨天下载最新版，点击ServiceControl.bat运行会提示不是有效的win32应用程序。点击pcap_dnsproxy,exe、pcap_dnsproxy_x86,exe运行也是这个问题。我是win7 64位系统，之前版本不会这样。

**Comment by chengr28** [comment]
感谢反馈，刚才重新上传的版本应该是没问题的了……
似乎是配置文件写错，导致上传的时候换行符识别有问题，GitHub 那边认不了的缘故 =_/=
