### ISSUE TITLE
解析慢

### ISSUE THREAD

**Issue by liuxyon** [chengr28/Pcap_DNSProxy#270]
﻿### Version/使用的版本/使用的版本

0.4.92

### Running Environment/运行环境/運行環境

windows 2016

### Actual/实际情况/實際情況

[Local DNS]
Local Protocol = IPv4 + UDP
Local Force Request = 0
Local Hosts = 0
Local Main = 1
Local Routing = 1
[DNS]
Outgoing Protocol = IPv6 + UDP + TCP 
Direct Request = IPv6
Cache Type = Timer + Queue
Cache Parameter = 512
Cache Single IPv4 Address Prefix = 0
Cache Single IPv6 Address Prefix = 0
Default TTL = 36000

目前调整为只使用ipv4本地域名解析.  我感觉路由好像不起作用.  另外缓存时间怎么调整更长点？

另外错误代码在哪里找结果？

[Network Error] Socket connecting error: An operation was attempted on something that is not a socket[10038].

**Comment by liuxyon** [comment]
另外能用个实际域名解释下怎么配置host文件. 帮助文档实在艰涩..
[Local Hosts]
.qq\.com\.com
.qq\.com

**Comment by chengr28** [comment]
关于这几个问题：
- 获取解析的时间长，应该是因为 `Outgoing Protocol` 开启了 TCP 协议的缘故。
- 默认开启的路由表识别，起不起作用是根据 Local DNS 返回的解析结果是否匹配决定的。
- 关于程序内置的 DNS 缓存，说明文档里 `[DNS]` 下应该有几个 `Cache..` 的参数，缓存的运作策略和时长都可以进行调整，算法也在那里有介绍。
- Windows 的错误代码 Microsoft 网站上应该有，不过这个应该只是普通的网络问题。
- Hosts 文件开头那段注释其实就是范例。

**Comment by liuxyon** [comment]
路由表不起作用，本地DNS解析国内所有域名仍然是通过国外DNS.
另外绑定ipv6监听不起作用，只有ipv4绑定工作.

**Comment by chengr28** [comment]
开启本地监听失败，请留意程序目录的 Error.log 任何和网络相关的报错都会有日志提示，错误日志里会有错误代码和简单的介绍，按照平时的情况来看多半是不拥有这个地址，或者地址+端口已经被其它程序占用掉了，占用情况可以用 netstat 看。

**Comment by liuxyon** [comment]
关键是没有错误日志内容，日志里现在是空的.

**Comment by liuxyon** [comment]
这个你看我配置对不？ 例如 baidu.com 不使用境外DNS. 
[Local Hosts]
.*\.baidu.com\.baidu.com
.*\.baidu.com

**Comment by chengr28** [comment]
关于错误日志，可以去系统盘的 system32 里看看有没有 Error.log 虽然几率很小但是以前有出现过错判目录的情况，可以检查一下。不过如果真的没有提示错误，那就说明绑定监听的操作是成功的，不明白『不起作用』是什么意思……可以使用 `nslookup 域名 地址` 直接发一个请求看看。

**Comment by chengr28** [comment]
要让 `baidu.com` 不使用境外 DNS 直接写：
```
baidu\.com
```
即可。如果想要所有 `baidu.com` 结尾的域名都匹配规则，请使用
```
.*baidu\.com
```
https://zh.wikipedia.org/wiki/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F

**Comment by chengr28** [comment]
如果还有需要报告的问题可以直接回复，Close 之后也可以发言的，谢谢。

**Comment by chengr28** [comment]
我觉得你需要重头再来并仔细检查一次，首先需要做的是先更新到最新版本，然后 **不要使用服务脚本而是直接双击程序** 以调试模式运行：
- 关于监听的问题，程序启动后会马上开启监听，如果可以 `ping` 通 IPv6 地址但是无法进行解析，请先观察目录内是否存在 Error.log 其次打开 `cmd` 使用 `netstat -a -p TCPv6` 和 `netstat -a -p UDPv6` 检查是否存在类似 `[::]:53` 或者 `[IPv6 地址]:端口` 的监听：存在则说明可能是 `Operation Mode` 或者 IPFilter 的阻止，不存在则说明监听没有成功。
- 关于 `Domain Test Protocol` 这个功能是给抓包模块做辅助的，启用 TCP 后会造成无法运行这个就无法处理了，因为找了不少人各个平台各种环境（包括 IPv6）都没有遇到问题……只能怀疑是不是系统的协议栈有问题了。

**Comment by liuxyon** [comment]
netstat -a -p UDPv6 这个检测设置的ip是监听了，但是就不能到达. 

Operation Mode 或者 IPFilter 的阻止  这个怎么检查？

**Comment by liuxyon** [comment]
Operation Mode 这个改成server 就可以用了.
 关于 Domain Test Protocol 这个还不知道怎么解决

**Comment by chengr28** [comment]
`Domain Test Protocol` 这个加上 `TCP` 后再运行程序，是直接一闪而过，还是有提示因为意外而终止或者收集错误信息之类的窗口？

**Comment by liuxyon** [comment]
是windows服务启动后几秒钟就自动停止，没任何提示。

**Comment by chengr28** [comment]
我的意思就是让你直接运行 exe 试试……
