### ISSUE TITLE
错误: 没有找到进程 "Pcap_DNSProxy.exe"。

### ISSUE THREAD

**Issue by bobcc4** [chengr28/Pcap_DNSProxy#271]
﻿### Version/使用的版本/使用的版本
Version = 0.45

### Running Environment/运行环境/運行環境
win7

###问题
错误: 没有找到进程 "Pcap_DNSProxy.exe"。

###问题截图
SERVICE_NAME: PcapDNSProxyService
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 3  STOP_PENDING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] DeleteService 成功
错误: 没有找到进程 "Pcap_DNSProxy.exe"。
[SC] CreateService 成功
操作成功完成。
操作成功完成。
[Notice] Windows Firewall test is successful.
[SC] ChangeServiceConfig2 成功
[SC] ChangeServiceConfig2 成功

SERVICE_NAME: PcapDNSProxyService
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x1
        WAIT_HINT          : 0xbb8
        PID                : 2300
        FLAGS              :

Windows IP 配置

已成功刷新 DNS 解析缓存。

请按任意键继续. . .

###问题补充
已经管理员运行Pcap_DNSProxy.exe，然后在进程里没找到该进程，开始以为是运行失败了，后来在所有用户的进程里找到了，但用户名为system，我以为是权限问题，但查看后本机的权限也为完全控制。

**Comment by chengr28** [comment]
- 关于服务控制脚本提示没有找到进程的问题，之前在 https://github.com/chengr28/Pcap_DNSProxy/issues/242 有提到过，这个其实是正常的操作，只要后续域名解析没有问题就行。
- 以服务运行的程序，都是以 `SYSTEM` 用户权限启动的，双击运行才会是当前的用户名。
