### ISSUE TITLE
为啥删除我的问题？

### ISSUE THREAD

**Issue by bobcc4** [chengr28/Pcap_DNSProxy#272]
﻿### Version/使用的版本/使用的版本

**Comment by SeaHOH** [comment]
并没有 #271

**Comment by chengr28** [comment]
那个是 close 不是删除，而且 close 之后是可以继续讨论的，如果有必要还可以 reopen 好吧……

**Comment by paperbag** [comment]
GitHub 木有删除 issue 的功能：
https://stackoverflow.com/questions/3081521/how-to-completely-remove-an-issue-from-github

（所以这个 issue 可以 close 了😂

**Comment by bobcc4** [comment]
抱歉，初次使用，已看到回复，感谢
