### ISSUE TITLE
更新windows10 1703后无法联网

### ISSUE THREAD

**Issue by lazureice** [chengr28/Pcap_DNSProxy#273]
###Version/使用的版本/使用的版本
0.4.9.2、0.4.5

###Running Environment/运行环境/運行環境
Windows10 1703 

###Expectation/期望情况/期望情況

###Actual/实际情况/實際情況
1. 之前使用win10 1607+pcap 0.4.5.一切正常.
2.更新win10 1703后：
1）chrome、IDM、QQ可用.
2）firefox、edge、app store、uwp app（我这里需要联网的是贴吧，IT之家，网易云音乐）不可用，无法连接网络.
3.强制使用代理，firefox可用.（uwp不知道怎么走代理）.
4.DNS空着不填，所有应用都能正常联网.但不能使用pcap.
5.服务的安装/卸载，停止/启动多试几次，也能正常联网，同时也能使用pcap.我还以为终于正常了！
但是，过一段时间又不能联网了，变成2的情况.（第5条是最迷的...简直不可思议.更多结果待测试）.

更新pcap至0.4.9.2，结果无变化.
以上是wifi测试结果，宽带测试结果晚上更新.（待编辑）

请问作者这是什么问题...？

（严格来说似乎是windows的问题，毕竟之前一直没出过错.
但是DNS不填127.0.0.1又能正常联网...
但是更新的人肯定不止一个，所以似乎是我自己的问题...我现在试试重装1703.（待编辑））

**Comment by wongsyrone** [comment]
如果是通过windows update更新的新版本，winpcap先卸载再安装试试

**Comment by lazureice** [comment]
@wongsyrone  谢谢~似乎可以了.
