### ISSUE TITLE
如何优先使用IPv6 Main DNS Address来解析AAAA记录？

### ISSUE THREAD

**Issue by ccaapton** [chengr28/Pcap_DNSProxy#274]
我正在使用HE的6in4隧道来访问google，但pcap_dns对AAAA记录的解析好像是优先请求IPv4 Main DNS Address，这样返回的地址都是针对IPV4优化的。比如google系列就返回了台湾的服务器，而HE的隧道是要绕美国的。能不能对AAAA记录优先使用IPV6 Main， 这样就会返回针对6in4优化后的地址呢？

下面是我的部分配置：
```
[Addresses]
IPv4 Listen Address =
IPv4 EDNS Client Subnet Address = 172.97.66.0/24
IPv4 Main DNS Address = 208.67.220.220:443
IPv4 Alternate DNS Address = 208.67.222.222:5353
IPv4 Local Main DNS Address = 114.114.115.115:53
IPv4 Local Alternate DNS Address = 223.6.6.6:53
IPv6 Listen Address =
IPv6 EDNS Client Subnet Address = 2001:470:66:96f::2/48
IPv6 Main DNS Address = [2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = [2001:4860:4860::8888]:53|[2620:0:CCD::2]:443|[2620:0:CCC::2]:5353
IPv6 Local Main DNS Address =
IPv6 Local Alternate DNS Address =
```

**Comment by chengr28** [comment]
嗯……这的确是个需要考虑的问题，现在的流程是无论通过什么协议发来的请求，都会统一灌到一个类似桶的一样的地方集中处理，不存在单独选路的情况。

**Comment by liuxyon** [comment]
我借用这个问题说下新版本0.9.4 仍然没有解决ipv6 聆听绑定本地ipv6问题，我绑定的ip本地测试能ping通，
但无论更换什么端口都不能解析。
另外 Domain Test Protocol = UDP 这个添加TCP就不能运行，也没有错误日志

**Comment by chengr28** [comment]
@liuxyon Please back to https://github.com/chengr28/Pcap_DNSProxy/issues/270, thanks.

**Comment by chengr28** [comment]
不好意思拖得时间好像有点太久了，一直有其它事情。

关于这个 issue 提到的功能，在刚才更新的版本里已经添加了，就是在 `xxx Protocol = ` 后面加 `Type` 详细使用方法参见 ReadMe 说明文档的介绍。在同时启用 IPv6 和 IPv4 后加上 `Type` 会让 AAAA 记录使用前者解析、A 记录使用后者解析，其它记录则按照原来的流程进行。

另外这次的更新也修正了默认的选路功能，在同时启用 IPv6 和 IPv4 时，程序这边会自动根据请求的来源（例如发到 ::1 就是 IPv6 发到 127.0.0.1 就是 IPv4）进行对应的选路，请求会被发送到对应协议的远程 DNS 服务器上。
