### ISSUE TITLE
请教下编译环境的问题

### ISSUE THREAD

**Issue by dNEryno** [chengr28/Pcap_DNSProxy#276]
编译潘多拉的IPK。。0.4.9.1

用的ubuntu14.04系统。

但是编译的时候提示
CMake Error at /home/s/PandoraBox-SDK/staging_dir/host/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)

但是我确实是装了的。这个问题在最新的ubuntu似乎没有出现。。不过会各种报so文件缺少。。

请问如何处理这个情况。

**Comment by chengr28** [comment]
就是单纯的 CMake 找不到 OpenSSL 库的问题，或许这个可以参考一下：https://stackoverflow.com/questions/16248775/cmake-not-able-to-find-openssl/16249265

**Comment by dNEryno** [comment]
好的，我试试。

**Comment by chengr28** [comment]
如果还有问题直接在这里回复就行，谢谢。

**Comment by dNEryno** [comment]
请问梅林的版本怎么编译呀。。

**Comment by chengr28** [comment]
Merlin 的编译和部署这边也不太清楚，可能得参考一下 [openwrt-Pcap_DNSProxy](https://github.com/wongsyrone/openwrt-Pcap_DNSProxy) 项目的情况，编译的方法应该是差不多的。记得好像有第三方的人有尝试过将本工具加入，或者也可以搜索一下相关的论坛。
