### ISSUE TITLE
Linux下很高的VSS占用

### ISSUE THREAD

**Issue by lunzima** [chengr28/Pcap_DNSProxy#277]
﻿### Version/使用的版本/使用的版本
master分支，版本>0.4.9.2

### Running Environment/运行环境/運行環境
类似于LEDE 17.01/Master，x86_64CPU，使用glibc库
尝试在编译时阉割openssl和libsodium，且配置文件里关闭了pcap的使用，但是没啥效果

### Expectation/期望情况/期望情況
看起来合理的虚拟内存（VSS）占用

### Actual/实际情况/實際情況
![lede-2017-09-18-18-57-04](https://user-images.githubusercontent.com/32062239/30539092-78a7910c-9ca3-11e7-8c8d-7c85a5cdd894.png)
VSS数值很高，刚启动时大约670M，在高并发时VSS数值高达10G，尽管实际占用内存没那么多。
这使得Pcap_DNSProxy没法在NOMMU的机器上使用。

**Comment by lunzima** [comment]
看了下running on Debian 8的，默认配置VSS占用要更高一些。

**Comment by chengr28** [comment]
抓包模块资源占用的问题在 https://github.com/chengr28/Pcap_DNSProxy/issues/178 有提到过，而本体虚拟内存占用的问题在 https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/issues/5 也有提到过的，无法解决。
