### ISSUE TITLE
建议：提供设置ulimit nofile的选项

### ISSUE THREAD

**Issue by lunzima** [chengr28/Pcap_DNSProxy#278]
高并发环境下Linux默认的1024个文件句柄软限制/4096个文件句柄硬限制的默认设置可能不够。
如果能增加自动调节ulimit nofile的选项会便于用户使用。

**Comment by chengr28** [comment]
以前 macOS 平台有过类似的问题 https://github.com/chengr28/Pcap_DNSProxy/pull/185 似乎也可以通过相似的方法修改 Linux 平台的默认打开文件上限数量，有时间会研究一下。

**Comment by lunzima** [comment]
OS X这默认值也太低了。。

**Comment by chengr28** [comment]
其实 1024 已经不算低了，这边发现网络模块有些部分也是有 1024 的硬性限制的，这个和一些系统的 API 有关，除了用脚本之类的调高系统的参数，这边也要研究怎么修改……

**Comment by chengr28** [comment]
已经把脚本里的软性文件描述符的资源限制调到和 macOS 一样，实际使用应该不用再担心这个问题了，感谢反馈。
