### ISSUE TITLE
恶劣校园网网络环境下的使用

### ISSUE THREAD

**Issue by CPCer** [chengr28/Pcap_DNSProxy#279]
小白一名，不奢望大佬无私相助。如可付费咨询，烦请附上支付宝、微信等等。paypal不太会弄，打算最近去办张信用卡，，所以可能要等一段时间……

﻿### Version/使用的版本/使用的版本
0.4.9.0

### Running Environment/运行环境/運行環境

win8，校园网，DNS对个别网站往往不解析。。。更换成其他任何非默认DNS全部超时。网络中心也不懂怎么解决。

### Expectation/期望情况/期望情況

正常解析？最好免翻上gg？

### Actual/实际情况/實際情況
nslookup不论是墙内还是墙外都超时

`C:\Usersxxxx>nslookup www.google.com
服务器:  pcap-dnsproxy.server
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
非权威应答:
DNS request timed out.
    timeout was 2 seconds.
名称:    wwW.GoOGLe.COm
Address:  172.217.24.132

C:\Usersxxxx>nslookup www.baidu.com
服务器:  pcap-dnsproxy.server
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
非权威应答:
DNS request timed out.
    timeout was 2 seconds.
名称:    www.a.shifen.cOM
Address:  103.235.46.39
Aliases:  wWW.BaiDu.cOM

C:\Usersxxxx>nslookup www.google.com 127.0.0.1
服务器:  pcap-dnsproxy.server
Address:  127.0.0.1

非权威应答:
名称:    wwW.google.CoM
Addresses: 172.217.27.132

C:\Usersxxxx>nslookup baidu.com 127.0.0.1
服务器:  pcap-dnsproxy.server
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
非权威应答:
DNS request timed out.
    timeout was 2 seconds.
名称:    BaIdu.coM
Addresses:    119.75.213.61
119.75.216.20
`
但是墙内网站基本**都能正常打开**。。墙外不行。增加了http代理或socks代理都无法打开google。

等于我这边的nslookup都废了嘛？

可能原因：WInpcap没有安装。
但是我事后运行Winpcap提示已有旧版，虽然按照帮助文档一些文件并没有找到。。停止程序，重新安装（使用软件附带的winpcap）不再提示有旧版了，装完之后好像也没有新增上述的文件。且问题依旧。

对了，Error.log记录的应该是winpcap安装之前的。

```
[2017-xxxx] -> [Network Error] Socket connecting error: A socket operation was attempted to an unreachable host[10065].
[2017-xxxx] -> [Network Error] Socket connecting error: A socket operation was attempted to an unreachable host[10065].
```

泣谢。

**Comment by CPCer** [comment]
已重置hosts，没有区别

**Comment by chengr28** [comment]
关于这几个问题：
- 本工具不提供任何直接翻墙的功能。
- WinPcap 没有装好的话程序是直接启动失败的，不可能启动后才报错。
- 至于不能正常解析的问题，建议是首先确认网络环境到底能不能正常使用 Config.ini 中的 DNS 服务器，如果有怀疑可以抓个包发到我的邮箱（Profile 里有）这边有时间会分析一下，然后给一个答复的。

**Comment by CPCer** [comment]
@chengr28 求问大佬。。配置里面的谷歌dns本来不就是访问不了嘛？还是说理论上只要解决投毒问题就能访问（我这里除外）？

**Comment by chengr28** [comment]
不明白你想表达什么……Google Public DNS 能不能用和所在的网络环境有关，就这边收到的反馈来看，有些地方可以有些地方不行。

**Comment by jzp820927** [comment]
@CPCer Google Public DNS 也就是 8.8.8.8 只是受到干扰，并没有被封死，使用还是能用的，只不过不是太稳定而已。

**Comment by CPCer** [comment]
查了一些资料，按照教程改了TCP方式，好像依然不行。。
[https://www.instapaper.com/read/961270369](url)

调低了Pcap Reading Timeout，无效
[https://blog.gazer.win/essay/pcap_dnsproxy_for_windows.html](url)
也换过内外的DNS，比如外走opendns内走dnspod，也没有卵用……
现在只好奇自己为啥能上网了。。

**Comment by lunzima** [comment]
楼主你得先排查问题在哪。
比如用现网环境中的DNS解析看看是不是能正常nslookup；或者上游是不是有劫持DNS访问的设备（如深信服、Panabit）等。

**Comment by chengr28** [comment]
关于你说的学校网络的情况，看起来是很恶劣，如果是这样的话你就算用本工具或者找网络中心那帮人都没用的，毕竟那边是黑箱操作，实际部署了什么规则你不知道也不会公开，缺乏透明度。

或者你可以先检测一下网络环境，首先使用类似 `nslookup www.baidu.com 114.114.114.114` 或者 `nslookup -vc www.taobao.com 114.114.115.115` 之类的命令，看看一些公共 DNS 服务器情况怎么样……

**Comment by chengr28** [comment]
如果还有需要报告的问题可以直接回复，Close 之后也可以发言的，谢谢。
