### ISSUE TITLE
能否设置让特定域名只返回IPV4/V6地址。

### ISSUE THREAD

**Issue by shuangzhijinghua** [chengr28/Pcap_DNSProxy#28]
用tunnelbroker，国内网站大多使用电信的IPV6，国外的V6网络无法连接到电信的V6网络，能不能增加设置只返回特定类型的地址？

**Comment by chengr28** [comment]
有一点需要注意……程序实际上只接收来自系统的请求并进行处理和转发，也就是说从系统发来的是什么类型的域名解析请求，程序只是代为处理而已，程序本身是不能控制系统那边发过来的是什么类型的请求
这方面可能需要找一下系统或者该程序有没有类似的选项控制这方面的行为……

**Comment by shuangzhijinghua** [comment]
这个就头疼了，用tunnel broker速度快，但是腾讯之类使用电信的IPV6地址国外是无法连接的。

或许应该这样说，屏蔽匹配域名的AAAA记录请求。或者对匹配域名的AAAA请求固定返回不存在的

**Comment by chengr28** [comment]
我看了下应该是可以做出来的……有时间做好了通知你到时候试试ww

**Comment by chengr28** [comment]
奇怪怎么 Close 掉了……

**Comment by shuangzhijinghua** [comment]
强迫症www

**Comment by chengr28** [comment]
邮件已经发过去了

**Comment by chengr28** [comment]
在刚才的更新中已经添加了这个功能，还增加了黑白名单的控制选项
详细情况参见 https://github.com/chengr28/Pcap_DNSProxy/tree/master/Documents 的说明
