### ISSUE TITLE
错误: 没有找到进程 "Pcap_DNSProxy.exe"。

### ISSUE THREAD

**Issue by simonfire007** [chengr28/Pcap_DNSProxy#280]
﻿### Version/使用的版本/使用的版本
Pcap_DNSProxy 0.4.9.1-0.4.9.2 

### Running Environment/运行环境/運行環境
win7 64

### Actual/实际情况/實際情況
输入 nslookup www.google.com 127.0.0.1
出现如下结果：

服务器:  pcap-dnsproxy.server
Address:  127.0.0.1

名称:    wwW.goOglE.coM
Addresses:  2404:6800:4008:801::2004
	  172.217.27.132

**现在我都不知道是否正常运行呢**

**Comment by chengr28** [comment]
关于这个问题，在 https://github.com/chengr28/Pcap_DNSProxy/issues/242 有相关的讨论。
