### ISSUE TITLE
Local Host的问题

### ISSUE THREAD

**Issue by zddewe** [chengr28/Pcap_DNSProxy#284]
﻿### Version/使用的版本/使用的版本

0.4.9

----------------------------------
[Local DNS]
Local Protocol = IPv4 + UDP
Local Force Request = 0
Local Hosts = 0
Local Main = 1
Local Routing = 1

----------------------------------
然后开启 LocalHost：

dig @127.0.0.1 www.facebook.com

; <<>> DiG 9.9.7-P3 <<>> @127.0.0.1 www.facebook.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
-----------------------------------

请教一下28小朋友，只要我开启了 LocalHost，DNS 解析就故障了呢

**Comment by zddewe** [comment]
我主要是想让国内常见域名走国内 DNS 服务器

**Comment by chengr28** [comment]
意思是，按照默认配置解析 Facebook 没有问题，开启了 `Local Hosts` 参数并重启服务后，就不正常了？

**Comment by zddewe** [comment]
@chengr28 Yes. brew services restart pcap...，只要我 localhost 改为1 就不能用了，

看28小朋友的文档是说让国内域名走国内 DNS server 是要开启 Local Host 的呢，

我应该没眼瞎吧...

**Comment by zddewe** [comment]
当然我还做了其它方面的一些修改：
[Base]
Version = 0.45
File Refresh Time = 15
Large Buffer Size = 4096
Additional Path =
Hosts File Name = Hosts.ini|Hosts.conf|Hosts|Hosts.txt|WhiteList.txt|White_List.txt
IPFilter File Name = IPFilter.ini|IPFilter.conf|IPFilter.dat|Routing.txt|chnrouting.txt|chnroute.txt

[Log]
Print Log Level = 3
Log Maximum Size = 8MB

[Listen]
Pcap Capture = 1
Pcap Devices Blacklist = AnyConnect|Host|Hyper|ISATAP|IKE|L2TP|Only|Oracle|PPTP|Pseudo|Teredo|Tunnel|Virtual|VMNet|VMware|VPN|any|gif|lo|stf|utun
Pcap Reading Timeout = 25
Listen Protocol = IPv6 + IPv4 + TCP + UDP
Listen Port = 53
Operation Mode = Private
IPFilter Type = Deny
IPFilter Level < 0
Accept Type =

[DNS]
Outgoing Protocol = IPv4 + TCP
Direct Request = 0
Cache Type = Timer + Queue
Cache Parameter = 1280
Cache Single IPv4 Address Prefix = 0
Cache Single IPv6 Address Prefix = 0
Default TTL = 9000

[Local DNS]
Local Protocol = IPv4 + UDP
Local Force Request = 0
Local Hosts = 0
Local Main = 1
Local Routing = 1

[Addresses]
IPv4 Listen Address =
IPv4 EDNS Client Subnet Address =
IPv4 Main DNS Address = 208.67.220.220:443
IPv4 Alternate DNS Address = 8.8.8.8:53|8.8.4.4:53|208.67.222.222:5353
IPv4 Local Main DNS Address = 114.114.114.114:53
IPv4 Local Alternate DNS Address = 223.6.6.6:53
IPv6 Listen Address =
IPv6 EDNS Client Subnet Address =
IPv6 Main DNS Address = [2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = [2001:4860:4860::8888]:53|[2620:0:CCD::2]:443|[2620:0:CCC::2]:5353
IPv6 Local Main DNS Address =
IPv6 Local Alternate DNS Address =

[Values]
Thread Pool Base Number = 0
Thread Pool Maximum Number = 512
Thread Pool Reset Time = 120
Queue Limits Reset Time = 0
EDNS Payload Size = 1220
IPv4 Packet TTL = 32 - 255
IPv4 Main DNS TTL = 0
IPv4 Alternate DNS TTL = 0
IPv6 Packet Hop Limits = 32 - 255
IPv6 Main DNS Hop Limits = 0
IPv6 Alternate DNS Hop Limits = 0
Hop Limits Fluctuation = 2
Reliable Once Socket Timeout = 3000
Reliable Serial Socket Timeout = 1500
Unreliable Once Socket Timeout = 2000
Unreliable Serial Socket Timeout = 1000
TCP Fast Open = 1
Receive Waiting = 0
ICMP Test = 900
Domain Test = 900
Alternate Times = 10
Alternate Time Range = 60
Alternate Reset Time = 300
Multiple Request Times = 2

[Switches]
Domain Case Conversion = 1
Compression Pointer Mutation = 0
EDNS Label = 1
EDNS Client Subnet Relay = 0
DNSSEC Request = 0
DNSSEC Validation = 0
DNSSEC Force Validation = 0
Alternate Multiple Request = 0
IPv4 Do Not Fragment = 0
IPv4 Data Filter = 0
TCP Data Filter = 1
DNS Data Filter = 1
Blacklist Filter = 1
Strict Resource Record TTL Filter = 0

[Data]
ICMP ID =
ICMP Sequence =
ICMP PaddingData =
Domain Test ID =
Domain Test Data =
Local Machine Server Name =

[Proxy]
SOCKS Proxy = 1
SOCKS Version = 5
SOCKS Protocol = IPv4 + TCP
SOCKS UDP No Handshake = 1
SOCKS Proxy Only = 0
SOCKS IPv4 Address = 127.0.0.1:8889
SOCKS IPv6 Address = [::1]:8889
SOCKS Target Server = 208.67.220.220:443
SOCKS Username =
SOCKS Password =
HTTP CONNECT Proxy = 0
HTTP CONNECT Protocol = IPv4
HTTP CONNECT Proxy Only = 0
HTTP CONNECT IPv4 Address = 127.0.0.1:1080
HTTP CONNECT IPv6 Address = [::1]:1080
HTTP CONNECT Target Server = 208.67.220.220:443
HTTP CONNECT TLS Handshake = 0
HTTP CONNECT TLS Version = 0
HTTP CONNECT TLS Validation = 1
HTTP CONNECT TLS Server Name Indication =
HTTP CONNECT TLS ALPN = 0
HTTP CONNECT Version = 1.1
HTTP CONNECT Header Field = User-Agent: Pcap_DNSProxy/0.4.5.0
HTTP CONNECT Header Field = Accept: */*
HTTP CONNECT Header Field = Cache-Control: no-cache
HTTP CONNECT Header Field = Pragma: no-cache
HTTP CONNECT Proxy Authorization =

[DNSCurve]
DNSCurve = 1
DNSCurve Protocol = IPv4 + TCP
DNSCurve Payload Size = 512
DNSCurve Reliable Socket Timeout = 3000
DNSCurve Unreliable Socket Timeout = 2000
DNSCurve Encryption = 1
DNSCurve Encryption Only = 0
DNSCurve Client Ephemeral Key = 0
DNSCurve Key Recheck Time = 1800

[DNSCurve Database]
DNSCurve Database Name = dnscrypt-resolvers.csv
DNSCurve Database IPv4 Main DNS = cisco
DNSCurve Database IPv4 Alternate DNS =
DNSCurve Database IPv6 Main DNS = cisco-ipv6
DNSCurve Database IPv6 Alternate DNS =

[DNSCurve Addresses]
DNSCurve IPv4 Main DNS Address = 208.67.220.220:443
DNSCurve IPv4 Alternate DNS Address =
DNSCurve IPv6 Main DNS Address = [2620:0:CCC::2]:443
DNSCurve IPv6 Alternate DNS Address =
DNSCurve IPv4 Main Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv4 Alternate Provider Name =
DNSCurve IPv6 Main Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv6 Alternate Provider Name =

[DNSCurve Keys]
DNSCurve Client Public Key =
DNSCurve Client Secret Key =
DNSCurve IPv4 Main DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
DNSCurve IPv4 Alternate DNS Public Key =
DNSCurve IPv6 Main DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
DNSCurve IPv6 Alternate DNS Public Key =
DNSCurve IPv4 Main DNS Fingerprint =
DNSCurve IPv4 Alternate DNS Fingerprint =
DNSCurve IPv6 Main DNS Fingerprint =
DNSCurve IPv6 Alternate DNS Fingerprint =

[DNSCurve Magic Number]
DNSCurve IPv4 Main Receive Magic Number =
DNSCurve IPv4 Alternate Receive Magic Number =
DNSCurve IPv6 Main Receive Magic Number =
DNSCurve IPv6 Alternate Receive Magic Number =
DNSCurve IPv4 Main DNS Magic Number =
DNSCurve IPv4 Alternate DNS Magic Number =
DNSCurve IPv6 Main DNS Magic Number =
DNSCurve IPv6 Alternate DNS Magic Number =

**Comment by chengr28** [comment]
`Local Main` 和 `Local Hosts` 两个参数在 0.4.9.2 之前不能同时开启的，去看看程序的目录里应该会有 Error.log 生成……其实默认配置文件就有请求境内 DNS 服务器，参见 `Local Main` 和 `Local Routing` 参数的介绍，在 0.4.9.2 之后 Local DNS 的请求策略改了才可以同时开。

**Comment by zddewe** [comment]
@chengr28 Thank u. 

[2017-10-06 21:14:40] -> [Notice] Pcap_DNSProxy started.
[2017-10-06 21:14:40] -> [Network Error] SOCKS request error.
[2017-10-06 21:15:40] -> [Network Error] SOCKS request error.
[2017-10-06 21:15:41] -> [Network Error] SOCKS request error.
Error.log (END)

看了一下 error.log 这就不明白为什么了。

**Comment by chengr28** [comment]
SOCKS 的错误就比较难查了，应该是和本地的代理工具有关系，得抓 `any` 的包才能知道为什么……
