### ISSUE TITLE
IPv4 Local Alternate DNS Address 支持多个地址？

### ISSUE THREAD

**Issue by AnyoeDove** [chengr28/Pcap_DNSProxy#286]
﻿### Version/使用的版本/使用的版本
0.4.9.3
### Running Environment/运行环境/運行環境
Windows 10 LTSB 2016 x64

我在 IPv4 Local Alternate DNS Address 中填入了多个 DNS 地址，发现日志中并没有出现报错，是否已放宽 Local DNS 的数量限制？如果不是，可否放宽 Local Alternate DNS Address 的数量限制？

另外 Alternate Multiple Request = 1 是是否同时对 Local Alternate DNS Address 中的 DNS 生效？我在测试时发现开启此参数时对国内域名的 DNS 请求时仅会使用 IPv4 Local Main DNS Address 中的 DNS （IPv4 Local Alternate DNS Address 中仅设置1个）。

**Comment by chengr28** [comment]
关于境内 DNS 服务器多线程的问题，在 https://github.com/chengr28/Pcap_DNSProxy/issues/43 是有提到过的，并没有并行请求的必要，一主一备这样的形式就是主流操作系统协议栈的运作方法，所以实际上就算开启 `Alternate Multiple Request` 也不能控制 Local DNS 的请求过程，因为根本就没有这个功能……
