### ISSUE TITLE
GFW 的 DNS 污染模式更新

### ISSUE THREAD

**Issue by ZeroClover** [chengr28/Pcap_DNSProxy#288]
在 `0.4.9.3` 版本后 built-in 的污染地址名单更新到 IPFilter，然而，今天测试新版本时意外发现 GFW 污染模式发生变化，不再是解析到无效地址，而是随机解析到 Facebook / Twitter / Softlayer 的某些 IP 段上。

经过数百次对某些已知被污染域名（非 Google  等特别知名的域名）进行全国 DNS 解析测试。测试方法是从 GFWList 随机选出被泛域名污染的域名，生成一个随机前缀以确保子域名本身不存在，然后进行 DNS 查询，与 IPFilter 文件内现有的 IP 地址列表去重后得到以下 IP 列表：

```
31.13.64.33
31.13.65.17
31.13.66.1
31.13.66.23
31.13.68.1
31.13.69.86
31.13.70.20
31.13.71.7
31.13.72.1
31.13.72.23
31.13.73.1
31.13.78.65
31.13.78.66
31.13.79.17
31.13.80.1
31.13.81.17
31.13.82.1
31.13.82.17
31.13.82.23
31.13.83.8
31.13.84.16
31.13.85.8
31.13.85.16
31.13.86.8
64.13.232.149
66.220.147.11
66.220.147.11
66.220.147.44
66.220.149.18
66.220.152.28
66.220.158.32
67.15.100.252
67.15.129.210
67.228.74.123
67.228.126.62
67.228.235.91
69.63.176.15
69.63.180.173
69.63.181.12
69.63.184.14
69.63.184.30
69.63.186.31
69.63.187.12
69.63.189.16
69.63.190.26
69.171.224.12
69.171.224.40
69.171.225.13
69.171.229.73
69.171.230.18
69.171.233.24
69.171.233.37
69.171.234.29
69.171.235.64
69.171.235.101
69.171.237.16
69.171.239.11
69.171.240.27
69.171.242.30
69.171.244.11
69.171.245.84
69.171.247.32
69.171.247.71
69.171.248.65
69.171.248.128
74.86.3.208
74.86.12.172
74.86.17.48
74.86.118.24
74.86.142.55
74.86.151.167
74.86.226.234
74.86.228.110
75.126.115.192
75.126.124.162
75.126.135.131
75.126.150.210
75.126.164.178
88.191.249.183
173.252.102.16
173.252.103.64
173.252.110.21
174.36.196.242
174.37.54.20
199.59.148.97
199.59.148.140
199.59.149.136
199.59.150.11
199.59.150.49
205.186.152.122
208.43.170.231
```

观察发现 GFW 目前偏向于将被污染域名解析到 Facebook / Twitter / Softlayer 的某些 IP 段而不是像以前解析为固定的几个无效地址和保留地址。这些 IP 所在的地址段内的任何一个地址都可能是解析结果（因为继续进行 DNS 查询仍然会得到不同的结果，但都在相同的网段内）

这种情况会导致 Pcap_DNSProxy 的 IP 地址过滤失效，通过 Pcap_DNSProxy 进行 DNS 查询时也仍然可能获得错误的解析结果。

![DNS 解析结果截图](https://user-images.githubusercontent.com/13190004/31693479-6d9566fa-b3d1-11e7-9e96-54dfd998c751.png)

**Comment by SeaHOH** [comment]
我这儿也中招了。

**Comment by chengr28** [comment]
GFW 用被墙网站服务器的 IP 地址做投毒污染其实不算新了，应该是属于中等级别。低一级的就是平时的，高一级的是 2016 年头那时直接用随机有效的。这次起码也还是在墙内无效的地址，只是 IP 地址的名单每次都不一样。

其实这些 IP 地址要不要加到 IPFilter 里，这边还在考虑中。之前的版本把 Built-in 的黑名单转移到 IPFilter 主要是为了解决工具国际化的问题，因为这些地址虽然在天朝不能用，但是在境外有可能是正常的解析地址，就像这次就肯定是可以用的，设想是让使用者能自行编辑列表。主要还是考虑到如果真的要加到默认的列表里，那境外的只能先编辑默认的 IPFilter 才能解决，有影响正常解析的可能性。

至于这次为什么会被成功投毒污染（看起来几率不高，但是的确有遇到这种情况）并不是因为黑名单没有更新，因为黑名单本身是作为一个绝对护壁的存在，但是也有相应的弱点（例如这次）所以程序主要不是依靠黑名单的，只是这次 GFW 对虚假数据包的伪装程度有提高，有一定几率能骗过程序……这边会研究相应的解决方法，做个更新。

**Comment by ZeroClover** [comment]
@chengr28 我之前测试时被污染成功的几率非常高，基本上请求 10 次只有1次能得到正确解析结果。

暂时让解析请求走了代理。

**Comment by chengr28** [comment]
成功率这么高也是奇怪，理论上不应该的……或者可以试试把 `EDNS Label` 参数开启，重启服务试试。

**Comment by ZeroClover** [comment]
@chengr28 因为用了 ECS，所以 EDNS Label 都是打开了的

**Comment by SeaHOH** [comment]
v0.4.9.1
我这儿频率不高，EDNS Label 和 DNSCurve 都开启了。

**Comment by chengr28** [comment]
@ZeroClover 或者有时间的话可以抓个包，在被投毒污染的情况下查询域名，这边看看怎么回事……不方便的话可以发到我的邮箱，Profile 里有，有什么分析也会直接发在这里的。

**Comment by chengr28** [comment]
@ZeroClover 把所有和 DNSSEC 有关的参数全部关闭，重启服务试试？

**Comment by ZeroClover** [comment]
@chengr28 确实在关闭强制 DNSSEC 请求后不会被污染成功了

**Comment by chengr28** [comment]
他们最近大概是升级了投毒污染方式，把 DNSSEC 也纳入到干扰的范围，所以如果开着 DNSSEC 就有问题了……其实原因是程序的 DNSSEC 有逻辑上的问题，才会导致这种情况，下次更新应该就能修复。

**Comment by chengr28** [comment]
最近比较忙，一直没有处理这边的事情。关于这里提到的问题一直都在改进中，最近的版本问题应该是不大的了，不过这边还需要一段时间才能彻底解决 DNSSEC 的问题。因为各地的网络状况不同，建议如果确实需要这个功能同时有时间，可以先试探性开启 DNSSEC 功能看看还会不会被投毒污染，谢谢。

**Comment by chengr28** [comment]
刚才的更新应该已经覆盖绝大部分启用 EDNS/DNSSEC 的请求，应该不会再被投毒污染了，建议如有需要开启后观察一段时间，感谢反馈。

**Comment by SeaHOH** [comment]
v0.4.9.9
又出现了，其它配置无论如何调整，都有大机率得到污染结果。
不得不把上面的 IP 都放入 [Blacklist]。
```ini
[Addresses]
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 
IPv4 Main DNS Address = 8.8.4.4:53
IPv4 Alternate DNS Address = 9.9.9.9:53|1.1.1.1:53|208.67.222.222:5353
IPv4 Local Main DNS Address = China Telecom:53
IPv4 Local Alternate DNS Address = 182.254.116.116:53
IPv6 Listen Address = 
IPv6 EDNS Client Subnet Address = 
IPv6 Main DNS Address = [2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = [2606:4700:4700::1001]:53|[2620:0:CCD::2]:443|[2620:0:CCC::2]:5353
IPv6 Local Main DNS Address = 
IPv6 Local Alternate DNS Address = 
```

**Comment by MikeLing** [comment]
补充3个IP：
199.59.148.209
69.63.176.15
75.126.33.156

**Comment by jiangjunfu19920216** [comment]
看了你们的解惑 我终于知道为啥 git 老是被封了 只要跟真相有关的 所有言论自由 都有仇
