### ISSUE TITLE
Compression Pointer Mutation 只有填入 1 有用, 填入 2 3 会导致无法解析.

### ISSUE THREAD

**Issue by LisonFan** [chengr28/Pcap_DNSProxy#289]
﻿### Version/使用的版本/使用的版本
0.4.9.4

### Running Environment/运行环境/運行環境
Windows Server 2012 x64 / macOS 10.13

**Comment by gjbg1989** [comment]
务必对 IPFilter 文件进行更新——怎么更新？

**Comment by chengr28** [comment]
@gjbg1989 如果没有修改过 IPFilter 文件，那么用新的直接覆盖旧的就行。

**Comment by chengr28** [comment]
关于这个压缩指针的问题……这边专门进行过测试，程序这边的数据包构造是没有问题的。不过毕竟不是标准的 DNS 请求，看起来只有 Google Public DNS 可以进行识别，有些地区不能使用造成不能解析，也是很正常的事情。

**Comment by laggardkernel** [comment]
@chengr28 至少Google DNS是能够解析所有级别的压缩指针的。

但问题在于不仅境外DNS可以返回请求，GFW也会抢答虚假结果。根据我的测试，利用Wireshark抓包，现存3种级别的带有压缩指针的UDP DNS请求均会被防火墙抢答。ChinaDNS的测试结果相同，压缩指针功能启用后也会被防火墙抢答。

基本确定GFW已经可以100%识别带有压缩指针的请求并抢答，其不再是一种可靠的过墙方案。建议移除此功能。
