### ISSUE TITLE
最近的修改似乎弄坏了 Hosts 功能

### ISSUE THREAD

**Issue by yfdyh000** [chengr28/Pcap_DNSProxy#29]
问题从 https://github.com/chengr28/Pcap_DNSProxy/commit/cf09cf063acb773877e690b7e19a74cc442668cc 版本开始出现，上一个版本的exe运行正常。

问题症状：ping Hosts中指定的域名会直接返回 `Ping 请求找不到主机 xxx。请检查该名称，然后重试。`，但nslookup查询的结果正常且正确。故障的域名也将无法被其他程序连接。

例如，在 Hosts.ini 中的 `[Hosts]` 中指定 `1.1.1.1 abc.abcd`，然后 `ping abc.abcd`。
`Remove Keccak.` 之前的版本会开始ping 1.1.1.1，而 `Remove Keccak.` 及之后的版本会直接报告找不到主机。

**Comment by chengr28** [comment]
测试过似乎是没有问题的……nslookup 查询正常说明程序这边没问题，但其它地方失败了可能是系统自身有缓存。不过刚才发现一个新的比较难触发的问题，就是如果把配置文件备份了一份，现在用的改坏了删掉换回原来的那份，可能会因为创建/修改时间比程序之前读取的那份早而被程序忽略，一会儿上传一个新的版本看看应该就没事了……

![Alt text](https://lh5.googleusercontent.com/-MU_NoVjaoWU/VVQtLshHNrI/AAAAAAACPS8/Z3Fw-TfjX8s/w0/2015-05-14-Hosts-Config.png)
如果你不放心，可以把配置文件发到我的邮箱，我帮你试试w

**Comment by yfdyh000** [comment]
Config.ini、Hosts.ini 等文件都是同一份，只是 Pcap_DNSProxy_x86.exe 的区别。用了 ServiceControl.bat 刷新缓存也是同样。`Flush DNS cache requesting` 那份（上一版本）的exe就没有问题。很奇怪……

**Comment by chengr28** [comment]
这个很难说的……建议还是发过来我看看是怎么回事

**Comment by chengr28** [comment]
已更新 0.4.0.1
