### ISSUE TITLE
EDNS Client Subnet Relay不支持专有网络

### ISSUE THREAD

**Issue by 1258159678** [chengr28/Pcap_DNSProxy#292]
﻿### Version/使用的版本/使用的版本
0.4.9.4

### Running Environment/运行环境/運行環境
Windows

### Actual/实际情况/實際情況
阿里服务器专有网络下无法使用EDNS Client Subnet Relay功能

**Comment by chengr28** [comment]
EDNS Client Subnet 是为解决请求经 DNS 服务器转发后来源地址丢失的问题，如果请求者使用私有网络地址则说明其和 DNS 服务器处于同一个网域内，此时不需要使用 EDNS Client Subnet 功能。
