### ISSUE TITLE
查询时DNS没有返回内容

### ISSUE THREAD

**Issue by wby238** [chengr28/Pcap_DNSProxy#293]
﻿### Version/使用的版本/使用的版本
0.4.9.4

### Running Environment/运行环境/運行環境
x64 win7

### Expectation/期望情况/期望情況
正常运行

### Actual/实际情况/實際情況
用的是`https://github.com/bazingaterry/SYSUv6-DNS`中的配置，在实际使用中必须删去`HTTP CONNECT Header Field = Content-Length: 0`这一行才能运行，不然报错`[Parameter Error] Data format error in \Pcap_DNSProxy-bin\Windows\Config.conf(Line 124).`
删去124行后，能够运行，但是使用`nslookup google.com ::1`来查询时返回`*** UnKnown 找不到 google.com: No response from server`

**Comment by chengr28** [comment]
这个问题其实老实说这边也不知道如何解决……因为如果用的是 SYSUv6-DNS 项目，说明是专有网络环境的，这边不清楚情况，具体可能需要去那个项目问一下。至于提到的两个问题：
* `Content-Length: 0` 是旧版的配置文件了，因为之前实现 HTTP CONNECT 的时候没留意，看过标准后发现是不能加这个 HTTP header 的，所以新版里已经删掉而且禁用了。
* `No response from server` 是因为程序在超时时间内没有回应任何的解析结果，至于为什么没有回应解析结果……这个就如上所说和网络环境有关了，可能性太多：DNS 服务器失效，网络状况有变化，返回的均为黑名单解析结果不被程序接受……等等。

**Comment by wby238** [comment]
SYSUv6-DNS 项目是我们学校的师兄创建的，现在在正常运行，那边是搭建在R6300v2和斐讯K2上的，见到能正常运行我就来这里问了一下，等等我去那边开个issue问一下。
