### ISSUE TITLE
无法优化DNS返回延迟值

### ISSUE THREAD

**Issue by sysconfon** [chengr28/Pcap_DNSProxy#294]
﻿### Version/使用的版本/使用的版本
0.4.9.4

### Running Environment/运行环境/運行環境
windows 2008 r2

### Expectation/期望情况/期望情況
期望：
优化配置后。能够使用dig IP地址，将延迟降低在10 - 15ms内。最差条件也期望能在60ms内。延迟太大导致页面响应时常过长。

### Actual/实际情况/實際情況

针对该程序优化。配置信息如下：
Pcap Reading Timeout = 16
Cache Type = Timer + Queue
Cache Parameter = 10800
Default TTL = 43200
以上信息均为提示配置后优化的结果。但是延迟还是居高不下，服务器为公网。提供公网下DNS解析服务。

还有疑问，该延迟会和以下几个项配置的dns延迟堆叠吗？
IPv4 Main DNS Address = 
IPv4 Alternate DNS Address = 
IPv4 Local Main DNS Address = 
IPv4 Local Alternate DNS Address = 

以下是dig请求后的信息：
; <<>> DiG 9.9.11 <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1515
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 14, AUTHORITY: 0, ADDITIONAL: 27

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;.                              IN      NS

;; ANSWER SECTION:
.                       345126  IN      NS      a.root-servers.net.
.                       345126  IN      NS      l.root-servers.net.
.                       345126  IN      NS      f.root-servers.net.
.                       345126  IN      NS      i.root-servers.net.
.                       345126  IN      NS      g.root-servers.net.
.                       345126  IN      NS      e.root-servers.net.
.                       345126  IN      NS      h.root-servers.net.
.                       345126  IN      NS      j.root-servers.net.
.                       345126  IN      NS      k.root-servers.net.
.                       345126  IN      NS      b.root-servers.net.
.                       345126  IN      NS      c.root-servers.net.
.                       345126  IN      NS      m.root-servers.net.
.                       345126  IN      NS      d.root-servers.net.
.                       357743  IN      RRSIG   NS 8 0 518400 20171114200000 20171101190000 46809 . IPnyN2hcO1ISxooHfr9WRXtxevYRyUgOw47TefDvbOGlWpLVCCtIVvV3 6WCq2V4tt4IA5u2d+t+z2okxmQNL8YKbrp32P2DwjCHcGYABhSsi35WJ V7by6KmwpVbEiz3q/S9cCtMApLqs9V+U2UBVGy1bxXIOl9+1bLw1Fr8Y NPNuzCc3dSo6doOiSFy8nYKB+prhjsHOdFTGWzcQv5nOH+s+o71NwPR2 cHwkly5S4wDEanQkAPb9QUx2SRRpHtSbMXqrNlWXAuiChwHIkK8KFcbn ajPyQBuKnjOTABPPOL0WQ+ZljXaEI8//PMnhj50COmHEMtwrlqQDDMN/ gcRlLw==

;; ADDITIONAL SECTION:
b.root-servers.net.     581388  IN      A       199.9.14.201
b.root-servers.net.     12144   IN      AAAA    2001:500:200::b
i.root-servers.net.     581390  IN      A       192.36.148.17
i.root-servers.net.     12144   IN      AAAA    2001:7fe::53
d.root-servers.net.     581388  IN      A       199.7.91.13
d.root-servers.net.     12144   IN      AAAA    2001:500:2d::d
h.root-servers.net.     581389  IN      A       198.97.190.53
h.root-servers.net.     12144   IN      AAAA    2001:500:1::53
j.root-servers.net.     581393  IN      A       192.58.128.30
j.root-servers.net.     12144   IN      AAAA    2001:503:c27::2:30
e.root-servers.net.     581396  IN      A       192.203.230.10
e.root-servers.net.     12144   IN      AAAA    2001:500:a8::e
l.root-servers.net.     581385  IN      A       199.7.83.42
l.root-servers.net.     12144   IN      AAAA    2001:500:9f::42
k.root-servers.net.     581387  IN      A       193.0.14.129
k.root-servers.net.     12144   IN      AAAA    2001:7fd::1
c.root-servers.net.     581394  IN      A       192.33.4.12
c.root-servers.net.     12144   IN      AAAA    2001:500:2::c
f.root-servers.net.     581392  IN      A       192.5.5.241
f.root-servers.net.     12144   IN      AAAA    2001:500:2f::f
a.root-servers.net.     444144  IN      A       198.41.0.4
a.root-servers.net.     12144   IN      AAAA    2001:503:ba3e::2:30
g.root-servers.net.     581391  IN      A       192.112.36.4
g.root-servers.net.     12144   IN      AAAA    2001:500:12::d0d
m.root-servers.net.     581385  IN      A       202.12.27.33
m.root-servers.net.     12144   IN      AAAA    2001:dc3::35

;; Query time: 239 msec
;; SERVER: 118.89.xx.xx#53(118.89.xx.xx)
;; WHEN: Sat Nov 04 17:48:06 China Standard Time 2017
;; MSG SIZE  rcvd: 1097

**Comment by chengr28** [comment]
响应速度的问题无法解决，基本取决于网络延迟。这边对延迟进行过测量，如果按照默认的配置：

* 首先向 Local DNS 发送请求并等待域名解析结果，这里是第一个产生延迟的地方，延迟取决于到 Local DNS 的延迟
* 再多线程向那一堆境外 DNS 服务器发送请求，然后取最快且正确的解析结果并返回

以上是解析产生延迟最主要的原因，尤其是境外的部分，你要求一个境外的服务器响应比从天朝南北传输还要短的时间是不可能的。说实话举出的例子，在 250ms 内获得结果已经是很不错的性能了，网络状况恶劣时超过半秒的情况比比皆是。还有一个比较客观的就是 `Pcap Reading Timeout` 参数 = 抓包模块的延迟，就是说抓包模块以每 16ms 的速度返回一次数据，理论上应该会造成小于 16ms 的延迟。不过其实不太建议调低，因为此操作会增加系统 I/O 方面的操作，增加资源占用。还有其它的诸如白名单路由表之类附加的处理，应该也是可以在 10ms 内完成，取决于 CPU 的速度。

增加缓存大小和时间是正确的解决方法，因为缓存解析结果后是没有延迟的。其实如果想提高服务器的性能，可以入手的就只有 Local DNS 的部分，选一个好的 Local DNS 和一个好的规则（路由表/白名单）应该可以提速不少。但正如上面所说，延迟基本是网络问题造成的，只能说这个是聊胜于无。
