### ISSUE TITLE
EDNS Label 和 EDNS Client Subnet Address 问题

### ISSUE THREAD

**Issue by debugzxcv** [chengr28/Pcap_DNSProxy#295]
﻿### Version/使用的版本/使用的版本
https://github.com/chengr28/Pcap_DNSProxy/commit/9a897ac63b34eae98d2d68d3a8ab4c797e992496

### Running Environment/运行环境/運行環境
Windows 7 x64 SP1

### Steps to reproduce/复现步骤
1. 在配置文件中做如下更改：
```
EDNS Label = 1
IPv4 EDNS Client Subnet Address = 
IPv4 Main DNS Address = 223.6.6.6:53
IPv4 Alternate DNS Address =  223.6.6.6:53
```
2. 查询 `www.baidu.com`

### Expectation/期望情况/期望情況
查询不超时

### Actual/实际情况/實際情況
查询超时

##
补充：如果填入了合法的 `IPv4 EDNS Client Subnet Address` 或者配置文件中更改 `EDNS Label = 0` 将获得期望结果。

**Comment by chengr28** [comment]
结论就是：此 DNS 服务器不支持 EDNS Label。
