### ISSUE TITLE
最新lede编译报错

### ISSUE THREAD

**Issue by zaion520** [chengr28/Pcap_DNSProxy#296]
﻿### Version/使用的版本/使用的版本

4.9.4

### Running Environment/运行环境/運行環境

最新lede编译报错

### Expectation/期望情况/期望情況

最新的lede

### Actual/实际情况/實際情況
[  4%] Building CXX object Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
In file included from /home/alx/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/lib/gcc/x86_64-openwrt-linux-musl/5.4.0/include/xmmintrin.h:34:0,
                 from /home/alx/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/lib/gcc/x86_64-openwrt-linux-musl/5.4.0/include/x86intrin.h:31,
                 from /home/alx/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/x86_64-openwrt-linux-musl/include/c++/5.4.0/x86_64-openwrt-linux-musl/bits/opt_random.h:33,
                 from /home/alx/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/x86_64-openwrt-linux-musl/include/c++/5.4.0/random:50,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Platform.h:361,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Structure.h:23,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Definition.h:23,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Template.h:23,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Base.h:23,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Base.cpp:20:
/home/alx/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/lib/gcc/x86_64-openwrt-linux-musl/5.4.0/include/mm_malloc.h:34:64: error: declaration of 'int posix_memalign(void**, size_t, size_t) throw ()' has a different exception specifier
 extern "C" int posix_memalign (void **, size_t, size_t) throw ();
                                                                ^
In file included from /home/alx/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/x86_64-openwrt-linux-musl/include/c++/5.4.0/cstdlib:72:0,
                 from /home/alx/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/x86_64-openwrt-linux-musl/include/c++/5.4.0/bits/stl_algo.h:59,
                 from /home/alx/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/x86_64-openwrt-linux-musl/include/c++/5.4.0/algorithm:62,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Platform.h:352,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Structure.h:23,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Definition.h:23,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Template.h:23,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Base.h:23,
                 from /home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/Source/Pcap_DNSProxy/Base.cpp:20:
/home/alx/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/include/stdlib.h:99:5: error: from previous declaration 'int posix_memalign(void**, size_t, size_t)'
 int posix_memalign (void**, size_t, size_t);
     ^
Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/build.make:62: recipe for target 'Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o' failed
make[5]: *** [Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o] Error 1
make[5]: Leaving directory '/home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4'
CMakeFiles/Makefile2:85: recipe for target 'Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[4]: *** [Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
make[4]: Leaving directory '/home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4'
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4'
Makefile:177: recipe for target '/home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/.built' failed
make[2]: *** [/home/alx/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.4/.built] Error 2
make[2]: Leaving directory '/home/alx/lede/package/lean/Pcap_DNSProxy'
package/Makefile:109: recipe for target 'package/lean/Pcap_DNSProxy/compile' failed
make[1]: *** [package/lean/Pcap_DNSProxy/compile] Error 2
make[1]: Leaving directory '/home/alx/lede'
/home/alx/lede/include/toplevel.mk:207: recipe for target 'package/lean/Pcap_DNSProxy/compile' failed
make: *** [package/lean/Pcap_DNSProxy/compile] Error 2

**Comment by chengr28** [comment]
看起来是工具链有问题，因为那个出错的函数似乎是在库里的，可能这个时候编译器根本就没来到主程序这边……建议检查一下各个工具的版本和系统环境之类。
