### ISSUE TITLE
Pcap_DNSProxy如何取消本地局域网解析时候使用远程服务器

### ISSUE THREAD

**Issue by sysconfon** [chengr28/Pcap_DNSProxy#297]
﻿### Version/使用的版本/使用的版本
4.9.4

### Running Environment/运行环境/運行環境

windows 7
windows 8
windows 10

### Expectation/期望情况/期望情況
在局域网区域内有搭建web环境。安装有对应网站。在本地访问的时候。加载资源请求被解析到远程服务器。
例如：http://172.18.19.33    类似这样的一个网址。网站的内容会被转换到远程请求。

### Actual/实际情况/實際情況
如何修改配置文件。实现172.16/10.0/192.168三个内网段IP地址。解析让其不访问远程DNS服务器。

**Comment by chengr28** [comment]
完全看不懂你的意思……如果是说直接访问 IP 地址，这样是完全不需要进行域名解析的。至于访问网站会请求什么域名，完全是由网站上的内容决定的。

**Comment by chengr28** [comment]
有什么新的疑问或者更新都可以在这里直接回复，Close 后也是可以回复的。

**Comment by ntm25576** [comment]
内网有DNS服务器，在接入内网的时候希望Pcap_DNSProxy使用内网的DNS服务器解析公司域名，以便更快速响应
