### ISSUE TITLE
有一个需求，不知道 Pcap_DNSProxy 能不能实现，咨询下作者？

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#298]
﻿需求可能有点奇葩，还请见谅。
大概说明一下需求是这样，在解析域名的时候，如果域名有 AAAA 的记录，就只返回 AAAA 的记录，而不要混合返回 AAAA 和 A 的记录，如果域名没有 AAAA 的记录，就返回 A 记录。

一句话总结一下，也就是想 IPv6 优先，但是也不影响 IPv4 的解析。
我目前是像下面这样配置的：
Accept Type = Permit:AAAA

但是这样就只能返回 v6 的 IP，没有 v6 IP 的域名就返回空了。
如果按默认配置对返回的记录不做任何限制，一般都是 v4 和 v6 混合的，而默认情况是 v4 优先的，也达不到我想要的 IPv6 优先的效果。

或者能不能增加自己手动在配置文件中指定特定的域名返回特定的记录的功能？
或者还有没有其他什么办法能实现这个需求，还请作者指教，谢谢！

**Comment by chengr28** [comment]
不不，你可能是因为看到 `nslookup` 默认显示 AAAA 记录和 A 记录所以以为是混合了，实际上并不是这样的。一个 DNS 请求只能请求一种类型的记录，也就是说如果请求的是 AAAA 记录，这边就会提供 AAAA 记录，如果请求的是 A 记录，则会提供 A 记录，决定权在上游或者系统协议栈手上。

如果你需要实现类似的功能，你应该去修改系统的网络设置，而不是本程序。

**Comment by SeaHOH** [comment]
请问，请求 ANY 的情况是怎么处理的呢？

**Comment by chengr28** [comment]
请求 ANY 类型，返回结果由 DNS 服务器决定，程序不单独处理这种类型的请求……很难说解析结果里放的是什么顺序，貌似（除了个别类型的记录外）也没强制是哪种记录要放在另外一种记录的前面还是后面。

**Comment by chengr28** [comment]
上面说的是『**请求 ANY 类型**，返回结果由 DNS 服务器决定』
系统的协议栈不会发送 ANY 类型的请求。

**Comment by jzp820927** [comment]
好吧，我暂时通过其他方式解决这个问题，谢谢！

**Comment by adamyi** [comment]
@jzp820927 我去年折腾ipv6的时候搞过这个 https://github.com/adamyi/v6dns 你可以用它再转发一次pcap的dns，不过如果你（和我一样）是somehow搞到了一个ipv6 ip所以不得不用NAT6的话 然后又给内网加了IPv6 ULA IP的话，你可以试一下内网不用ULA IP而随便找一个自己大概不会访问的IPv6段...这样按照prefix table会优先IPv6的

**Comment by chengr28** [comment]
@adamyi 这是收到 A 记录的请求后自己先用 AAAA 记录发一遍，如果有收到 AAAA 记录就直接返回，没有就再发 A 记录重新请求一次这样？
