### ISSUE TITLE
Pcap_DNSProxy 二进制编译版或python版

### ISSUE THREAD

**Issue by sysconfon** [chengr28/Pcap_DNSProxy#299]
﻿### Version/使用的版本/使用的版本
0.4.9.4

### Running Environment/运行环境/運行環境
Centos

### Actual/实际情况/實際情況
是否会推出Centos二进制版本或者python等其它版本。目前编译需要的东西太多。编译太复杂了。

**Comment by chengr28** [comment]
* 本项目是使用 C/C++ 语言编写，官方不会提供其它语言的支持。
* 二进制可执行文件与处理器架构和系统中第三方库的版本息息相关，依赖关系太繁杂，和其它两种专一化的平台不一样，最好的方法就是使用时自行编译。说实话虽然说明文档写得很长，但实际上依赖的库并不多，而且编译也是跑个脚本的事情，能做的这边都做了，没什么比较好的解决方法。

**Comment by xiaofami** [comment]
我在Centos 7上编译部署成功了。配置编译环境不难：

`sudo yum install centos-release-scl`
`sudo yum install devtoolset-7-gcc* clang cmake3 libpcap libpcap-devel libsodium libsodium-devel openssl openssl-devel`
`scl enable devtoolset-7 bash`

然后将`CMake_Build.sh`中第39行`CMakeShell="cmake "`修改为`CMakeShell="cmake3 "`，就可以开始编译了。安装服务用作者提供的`Linux_Install.Systemd.sh`就行。另外Centos 7 下53端口默认被dnsmasq占用，需要禁用或卸载，53端口占用情况用`sudo lsof -i:53`可以查看。

最后感谢作者提供这么好用的工具，配合HE TunnelBroker和ipv6 hosts效果很棒

**Comment by sysconfon** [comment]
@xiaofami 非常感谢大哥您提供的方案。我这边测试一下试试看。再次感激不尽。
