### ISSUE TITLE
新版默认配置查询www.v2ex.com无记录

### ISSUE THREAD

**Issue by shuangzhijinghua** [chengr28/Pcap_DNSProxy#30]
![image](https://cloud.githubusercontent.com/assets/7972337/7647087/0110a9c6-fb01-11e4-943c-751e5f9dec53.png)
这是个特例？配置文件使用默认。

**Comment by yfdyh000** [comment]
重现，4*8 查询高几率，4*114 没有问题。

**Comment by chengr28** [comment]
关于这个我在以前 Beta 测试的时候也遇到过，图里也抓到有问题的包了：第 370/376/377 这三个包没有回复 A 地址，而第 371 包则有回复地址，114 那边备用服务器查询时也经常会遇到这种没有地址的回复包，Nslookup 里显示出来就是这种效果。原因大概是 DNS 服务器的问题，可能是递归查询的时候遇到什么问题了，也可能是服务器什么的遇到差错 =_/=
因为这个包是真的，Pcap 并没有进行拦截的理由，然后就被缓存下来了……或者这样吧我下次升级的时候给程序的缓存加个条件避免这种情况，临时的解决方法只能清除程序的缓存重新请求了……

**Comment by chengr28** [comment]
刚才更新了 0.4.0.3 应该是不会缓存这类没有地址的结果了，不过 DNS 服务器返回这种错误的回复……无解的感觉
