### ISSUE TITLE
关于Pcap_DNSProxy在TCP模式下远程请求咨询

### ISSUE THREAD

**Issue by sysconfon** [chengr28/Pcap_DNSProxy#300]
﻿### Version/使用的版本/使用的版本

0.4.9.4

### Running Environment/运行环境/運行環境

Windows 2012 r2

### Actual/实际情况/實際情況

在使用dig检查DNS是否支持TCP请求：
dig +tcp www.google.com @168.95.1.1 -p 53
发起后显示如下：
;; communications error to 168.95.1.1#53: network unreachable

在使用nslookup查询dns是否支持tcp请求：
nslookup -vc www.google.com 168.95.1.1
发起后显示如下：
Server:  dns.hinet.net
Address:  168.95.1.1

Non-authoritative answer:
Name:    www.google.com
Addresses:  2404:6800:4008
          108.177.97.105
          108.177.97.104
          108.177.97.103
          108.177.97.99
          108.177.97.147
          108.177.97.106
疑问：是否在dig检查是否支持tcp请求提示network unreachable的情况下，pcap_dnsproxy是无法使用改dns的tcp模式请求解析？

配置信息如下：
[DNS]
Outgoing Protocol = IPv4 + Force TCP
Direct Request = 0
Cache Type = Timer + Queue
Cache Parameter = 10800
Cache Single IPv4 Address Prefix = 0
Cache Single IPv6 Address Prefix = 0
Default TTL = 43200

[Local DNS]
Local Protocol = IPv4 + Force TCP
Local Hosts = 0
Local Routing = 0
Local Force Request = 0

[Addresses]
IPv4 Main DNS Address = 208.67.222.222:5353
IPv4 Alternate DNS Address = 1.1.1.1:1
我不启用境内dns。所有的请求都是直接发到境外dns做解析。
为了方便测试。IPv4 Alternate DNS Address填写了个不存在的地址。使其只使用唯一dns尝试。

**Comment by chengr28** [comment]
不明白你想表达什么……是说在 `dig` 无法使用 TCP 请求但 `nslookup` 可以使用 TCP 请求的情况下，本程序就像 `dig` 一样在强制 TCP 模式下无法使用 TCP 协议进行解析？

**Comment by sysconfon** [comment]
是这样情况。就是我使用dig和nslookup两种方式来测试dns是否支持tcp模式的请求。测试后发现，使用dig测试tcp支持提示network unreachable，而使用nslookup检测dns支持tcp是能正常获取解析结果。而在这样的一个情况下。我把这个dns配置到pacp里面。发现我使用dig 或者 nslookup都无法正常获取到解析结果。配置信息如上面。IPv4 + Force TCP 我改成 IPv4 + TCP也无法正常获取到解析结果

**Comment by chengr28** [comment]
这个不好说呢……本程序的请求都是通过系统 API 完成的，网络环境之类的问题也不好判断。不过个人是建议可以多试几个域名，不要用 Google 那种黑名单里会被 RESET 的域名做测试。

**Comment by sysconfon** [comment]
嗯。你这个我试过。除了Google其他也是一样的情况。而且我开了Direct Request = IPv4 和 0 都尝试过。都是无法解析。是否为G。F。W墙了，还是路由问题无法连接。所以。。。。无法解析

**Comment by sysconfon** [comment]
还有，这句话是有问题吗。理解不通。
* Direct Request - 直连模式，启用后将使用系统的 API 直接请求远程服务器而启用只使用本工具的 Hosts 功能：可填入 IPv4 和 IPv6 和 0，关闭为 0

启用后将使用系统的 API 直接请求远程服务器
还是
启用只使用本工具的 Hosts 功能

纠结这里填写 IPv4 和 IPv6 的时候，将使用系统的 API 直接请求远程服务器，还是启用只使用本工具的 Hosts 功能。

**Comment by chengr28** [comment]
那还真是奇怪……这边测试 TCP 是正常工作的，可能是你那边的 TCP 连接有问题。如果你需要更加深入的分析，可以在测试时抓包，将抓到的数据包发到我的邮箱，结果我会在这里回复。

正常来说，填 `Force TCP` 会使程序在该请求过程中强制使用 TCP，而填 `TCP` 在 TCP 失败时还会使用 UDP 重试，所以现在的问题是两种协议都失效……只能看看实际的数据包收发了。

**Comment by chengr28** [comment]
`Direct Request` 这个介绍下次更新会修改一下……程序默认是使用抓包模式，也就是使用抓包模块接收远程服务器的解析结果，这个不是标准的网络传输流程，在使用诸如虚拟网络或者隧道之类时会导致失效，所以才增加这个功能。严格来说，启用这个等于『使用标准的网络传输流程』也就是几乎所有网络程序的标准方法，缺点是对 DNS 投毒污染的过滤能力较弱。

这个参数当初是叫 `Hosts Only` 所以才有了那句『启用只使用本工具的 Hosts 功能』，当初这个功能是设计用于增强系统 Hosts 的功能而不做其它非 Hosts 功能任何处理的目的，只是后来发现主要目的有所变化……说是这样说，其实所有请求都会首先经过程序 Hosts 功能的检查的，不存在不启用的情况，这里可能有点歧义。

**Comment by sysconfon** [comment]
问题1：
回复一下关于TCP的问题。目前大概判断出问题了。
TCP该问题。属于这类情况。
1、使用国内dns。TCP请求。例如：
dig + tcp www.google.com @1.2.4.8 -p 53
出现情况为：有返回结果，域名被污染。
dig +tcp www.baidu.com @1.2.4.8 -p 53
出现结果为：正常返回结果。域名解析正常。
2、使用国外dns。TCP请求。例如：
dig +tcp www.google.com @202.14.67.4 -p 53
出现情况为：;; communications error to 202.14.67.4#53: network unreachable
dig +tcp www.baidu.com @202.14.67.4 -p 53
出现结果为：正常返回结果。域名解析正常。
判断结果为：基于53端口TCP查询。使用国外dns。在G>F>W处，会直接做reset操作。使其路由不可达。

问题2：
基于Direct Request该问题。有疑问。我在此次是否该填写IPv4呢。我不是用抓包模式。直接使用非标准口从例如：HK等地获取到DNS解析后。返回到国内来。能实现免污染（目前非标准小众端口污染较少）。

问题3；
我在本地配置了Pcap_dnsproxy。然后在hk配置了一台服务器。开启了53和5353端口。然后在本地的Pcap_dnsproxy填写hk服务器的IP和端口。然后测试页面为51.ruyo.net。在hk配置的能正常解析该网站且页面显示正常。但是在本地的pcap_dnsproxy填写后。访问该网页。存在2种情况：
1、无法打开页面；
2、打开页面，显示内容不正常。
试问：该程序会影响到解析吗？ hk和本地都是使用pcap_dnsproxy搭建。

**Comment by chengr28** [comment]
1. 看起来是 Windows 平台上 `dig` 的错误输出有所误导，因为其它平台上如果是被切断连接，是可以显示 `connection reset` 的，不会提示说 `network unreachable`。
2. `Direct Request` 应该在使用非原生 IPv4/IPv6 协议时使用，例如隧道或者 VPN 之类。而上面提到的非标准端口，使用的也还是原生 IPv4 协议，在本地的部分不需要启用这个参数。因为这个参数代表的是直连，所以如果按照性能来看，反而 HK 机器上开启对响应速度会有改善。
3. 按照这种现象来看是有些解析成功有些解析失败，不排除是因为解析并非 100% 成功（因解析流程长需要的时间长，有可能超过了系统协议栈的默认超时时间）这个不好判断，有条件可以抓个包。

**Comment by sysconfon** [comment]
您需要什么方式抓包呢。能提供一下具体方式吗。我这边尝试一下。
还有一个问题
关于Linux版的pcap编译。说明里面提供的方式操作后编译还是经常失败。能否完善一下这块呢？

**Comment by chengr28** [comment]
1. 抓包用 Wireshark 就行。
2. Linux 主要是几个依赖的编译，这个建议查阅所依赖软件官方的帮助，程序本身的编译是一个简单的脚本，成功一次后系统环境不变应该是不会再失败的。

**Comment by sysconfon** [comment]
我发现。抓包的时候。WireShark无法抓取到51.ruyo.net该域名。不知道为何。您能尝试抓到DNS请求的包吗。

**Comment by chengr28** [comment]
特定网络环境有什么问题，要看到具体的抓包文件才能进行分析，这样直接说参考价值不大……顺便提供的网址这边测试，无论开不开 TCP 协议请求网页访问都是正常的，没有残缺的问题。

**Comment by chengr28** [comment]
如果有问题的话直接回复就行，谢谢。
