### ISSUE TITLE
将bat转成exe

### ISSUE THREAD

**Issue by onplus** [chengr28/Pcap_DNSProxy#301]
Bat To Exe Converter
http://www.f2ko.de/en/b2e.php

![b2e](https://ipfs.io/ipfs/Qmbei4FGZWHqSFnQ3WXNL5zbfenHM1Gj36J5nbWY6BVoGw)

**Comment by chengr28** [comment]
用 cmd 目的就是为了简化和透明化相关的工作流程，换成 exe 不是本末倒置了……
