### ISSUE TITLE
求大神出个config的模板！readme文件对我这种小白太难

### ISSUE THREAD

**Issue by jorismq** [chengr28/Pcap_DNSProxy#302]
感谢大神的工作！！
能不能出几个模板？针对个人修改哪里，有哪几种不同方案，优缺点是什么？
针对当服务器又怎样？
想用ipv6又有哪些注意的？
readme非常详细，但是我等小白一大半看不懂！不知道我个人使用的话，不同选项有啥意义

**Comment by sysconfon** [comment]
一般来说。整个Config模板修改不多。IPv6目前国内环境下使用并不多。具体修改需要根据网络环境。参考ReadMe来改会较好。不同网络修改也不相同。

**Comment by chengr28** [comment]
配置文件当前的目标是适配大多数网络环境，默认配置的 Config 就是模板和推荐配置，也就是类似开箱即用。如果你觉得需要修改配置文件，你需要自己搞清楚不同参数的含义，ReadMe 文档里都有说。个人是觉得 ReadMe 文档虽然长，但应该还没有到完全无法看懂的地步。
