### ISSUE TITLE
咨询特定域名能够设置特定DNS服务器解析？

### ISSUE THREAD

**Issue by Humanorino** [chengr28/Pcap_DNSProxy#305]
﻿### Version/使用的版本/使用的版本

v0.4.9.4

### Running Environment/运行环境/運行環境

windows server2016

### Expectation/期望情况/期望情況

对于某个特定的域名使用特定的DNS服务器来解析。

### Actual/实际情况/實際情況

目前存在一个域名同时在公网和内网存在DNS服务器记录，对应公网IP和内网IP。用DNSProxy默认的8.8.4.4只能解析到公网IP,而我想要能够解析到内网IP,请问怎么设置。内网IP的DNS服务器是一个内网的服务器，简单地在8.8.4.4后面添加该服务器并不能实现解析内网的功能。请问能否实现该功能，如果可以的话应该怎么设置。

**Comment by viewtheard** [comment]
貌似是谁先返回就用谁。

**Comment by AnyoeDove** [comment]
阅读 ReadMe [Dnsmasq 兼容地址格式](https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe.zh-Hans.txt#L927)

**Comment by chengr28** [comment]
理论上是可以用这个方法指定程序在境内部分请求时所使用的服务器，不过其实个人是建议写 Hosts 的……毕竟私有网络有什么域名有内网服务器，应该是已知的。
