### ISSUE TITLE
quad9 DNS设置失败

### ISSUE THREAD

**Issue by jorismq** [chengr28/Pcap_DNSProxy#306]
最新版
 
IPv4 Main DNS Address = 9.9.9.9:53

一直报错

[2017-11-18 11:14:41] -> [Notice] Pcap_DNSProxy started.
[2017-11-18 11:14:41] -> [Parameter Error] Data format error in F:\xx\Pcap_DNSProxy-bin\Windows\Config.ini(Line 62).

**Comment by viewtheard** [comment]
我这53正常。但其他端口不行

**Comment by chengr28** [comment]
```
  * IPv4 Main DNS TTL - IPv4 主要 DNS 服务器接受请求的远程 DNS 服务器数据包的 TTL 值：0 为自动获取，取值为 1-255 之间
    * 支持多个 TTL 值，与 IPv4 DNS Address 相对应
  * IPv4 Alternate DNS TTL - IPv4 备用 DNS 服务器接受请求的远程 DNS 服务器数据包的 TTL 值：0 为自动获取，取值为 1-255 之间
    * 支持多个 TTL 值，与 IPv4 Alternate DNS Address 相对应
```
如果上面 Main/Alternate Address 里没有填东西，请也把下面 TTL 参数里的东西删掉。

**Comment by viewtheard** [comment]
晕了，今天我用虚假dns也能返回地址
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 
IPv4 Main DNS Address = 1.9.9.9:5389
IPv4 Alternate DNS Address = 1.80.81.81:53
IPv4 Local Main DNS Address = 1.29.29.29:53
IPv4 Local Alternate DNS Address = 

IPv4 Main DNS TTL = 0
IPv4 Alternate DNS TTL = 0

DNSCurve = 1
DNSCurve IPv4 Main DNS Address = 1.67.220.220:443 
DNSCurve IPv4 Alternate DNS Address =

**Comment by chengr28** [comment]
我怎么知道你乱调了什么参数，或者系统是怎么回事……
