### ISSUE TITLE
EDNS Lebel 排除模式配置是不是还没更新过来啊

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#308]
﻿### Version/使用的版本/使用的版本

0.4.9.4

### Running Environment/运行环境/運行環境

win7x64

### Actual/实际情况/實際情況

`EDNS Lebel`的排除模式
文档里已经是由`1`改为`All`
但实际配置文件使用`All`时会报**Notice**错误
换回`1`便不报错

**Comment by chengr28** [comment]
ReadMe 文档里说得不太清楚……其实 `EDNS Label` 全部开启一直都是 `1` 举例那里引入 `All` 其实是为了更好地解释那个排除模式，那个 `All` 实际上没有任何作用……下次更新会修复这个问题，这样写 `All` 还是写 `1` 都是等价的了。

至于那个 `Notice: ..` 的问题，有可能是因为上面的问题导致程序有错误的判断，如果不放心可以把参数的内容以及报错的日志也都放上来，这边再看看。

**Comment by chengr28** [comment]
刚才更新的版本已经修复这个问题了，有时间可以试试，感谢反馈。
