### ISSUE TITLE
一小处文档不一致

### ISSUE THREAD

**Issue by yfdyh000** [chengr28/Pcap_DNSProxy#31]
https://github.com/chengr28/Pcap_DNSProxy/blob/Release/Windows/Config.ini#L22 `Default TTL = 900`
https://github.com/chengr28/Pcap_DNSProxy/blob/Release/Documents/ReadMe%28zh_Hans%29.txt#L199 及繁体文档。
> Default TTL - Hosts 条目默认生存时间：单位为秒，留空则为 900秒/15分钟，**默认为空**

**Comment by chengr28** [comment]
好吧改好了 =_/=
