### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by LisonFan** [chengr28/Pcap_DNSProxy#310]
﻿### Version/使用的版本/使用的版本
0.4.9.5

### Running Environment/运行环境/運行環境
macOS 10.13.1

### Expectation/期望情况/期望情況
正常返回

### Actual/实际情况/實際情況
超时

解析 ```gcore.lu ```
```IPv4 Main DNS``` 和 ```IPv4 Alternate DNS``` 配置如下：
![image](https://user-images.githubusercontent.com/9424775/33538413-33cb40e8-d8fc-11e7-8f99-bc485724ab56.png)

```Alternate Multiple Request = 1```

结果
![image](https://user-images.githubusercontent.com/9424775/33538451-609644b0-d8fc-11e7-9690-93c9fa2f3a82.png)

目前已知的是 ```OpenDNS``` 无法解析 ```gcore.lu ```
但是 `119.29.92.92` 可以解析
将 `119.29.92.92` 设置成 Main DNS 并关闭 ```Alternate Multiple Request``` 也是超时

通过抓包
![image](https://user-images.githubusercontent.com/9424775/33538586-1c13c10e-d8fd-11e7-9cde-a5247927a736.png)
有结果，但是终端还是显示超时
![image](https://user-images.githubusercontent.com/9424775/33538594-2d7ba39e-d8fd-11e7-8b49-7695e7adfd05.png)

**Comment by sysconfon** [comment]
我也有遇到类似问题。我是用的都是非标准53端口。

**Comment by sysconfon** [comment]
还有。楼主大大。能否加你个好友。讨论DNS相关问题呢？

**Comment by sysconfon** [comment]
IPv4 Alternate DNS

**Comment by SeaHOH** [comment]
Win7，版本也是 0.4.9.5，正常解析。
设置如下：
```ini
[Local DNS]
Local Hosts = 1
Local Routing = 0
[Addresses]
IPv4 Local Main DNS Address = ;ISP's DNS
[Switches]
EDNS Label = 1
DNSSEC Request = 1
[DNSCurve]
DNSCurve = 1
[DNSCurve Database]
DNSCurve Database IPv4 Alternate DNS = dnscrypt.eu-nl
DNSCurve Database IPv6 Alternate DNS = dnscrypt.eu-nl-ipv6
```
其余都是默认设置，结果如下
>C:\Users\x>nslookup gcore.lu
服务器:  pcap-dnsproxy.server
Address:  127.0.0.1
>
>非权威应答:
名称:    gcoRe.Lu
Addresses:  2a03:90c0:9997::9997
          92.223.97.97

**Comment by LisonFan** [comment]
@SeaHOH 你应该是走了 DNSCurve

**Comment by SeaHOH** [comment]
>你应该是走了 DNSCurve

应该是，关闭 DNSCurve 后超时。

**Comment by sysconfon** [comment]
@LisonFan 能咨询您一下，您dns：119.29.92.92是如何添加完整edns支持的呢？能否和您咨询一下呢？

**Comment by sysconfon** [comment]
@chengr28 edns完整支持。能否实现通过本地IPv4地址等实现将客户端IP带入后请求。实现客户端的IP地址完成edns支持呢？

**Comment by chengr28** [comment]
@sysconfon 有个 `EDNS Client Subnet Relay` 参数，开启后会将请求者的 IP 地址装入数据包的 EDNS Client Subnet 里，ReadMe 文档应该有相关的介绍。

**Comment by sysconfon** [comment]
@chengr28 EDNS Client Subnet Relay 参数我都已经打开。但是在测试的时候还是发现，edns信息并没有被带入进去。举例：baidu.com 或者 qq.com 在北京都存在节点。而我本地也是属于北京IP。都属于联通。但是请求总会将我带入到天津。甚至国外去。

**Comment by chengr28** [comment]
@LisonFan 有时间研究下……最近都比较忙

**Comment by chengr28** [comment]
这边看了一下这个 gcore.lu 看起来是因为 OpenDNS 方面无法解析域名造成的，但是这边无法重现问题，因为无论填入的 DNS 服务器是否有使用非标准端口，除了本身服务器没有反应外解析都是正常的……

**Comment by chengr28** [comment]
@sysconfon `EDNS Client Subnet Relay` 这个是只有其它地方放过来带有 EDNS 的请求才会带出去，至于为什么结果还是不对，咋整条 EDNS Client Subnet 链有很多环节都有可能出问题的……例如，有可能本身 NS 服务器不支持，域名所有者没有启用这样的功能，递归 DNS 服务器没有理会 EDNS 客户子网信息，或者可能压根发过来的请求就没有 EDNS 客户子网信息……等等。
