### ISSUE TITLE
Pcap_DNSProxy解析BUG

### ISSUE THREAD

**Issue by sysconfon** [chengr28/Pcap_DNSProxy#311]
﻿### Version/使用的版本/使用的版本

0.4.9.5

### Running Environment/运行环境/運行環境

windows 2008 r2

### Expectation/期望情况/期望情況

正常解析IP地址

### Actual/实际情况/實際情況
IPv4 Main DNS Address =此处填写非53端口。例如：5353
IPv4 Alternate DNS Address = 8.8.8.8:53|208.67.220.220:443|208.67.222.222:5353（此处默认）
以上情况。解析正常。nslookup  dig能正常获取信息

IPv4 Main DNS Address = 此处填写非53端口。例如：5353
IPv4 Alternate DNS Address = 此处填写非53端口。例如：5353
以上情况。解析正常。nslookup  dig不能正常获取信息

其它信息默认配置。然后替换回0.4.9.4正常。

**Comment by chengr28** [comment]
然而这边测试不能重现这个问题，就算所有目标地址端口都不为 53 也没出现类似不能解析的问题……或许可以在遇到问题的时候抓个包看看？

**Comment by sysconfon** [comment]
@chengr28 我的这个问题，和#310的问题基本上差不多。就是IPv4 Alternate DNS Address =208.67.222.222:5353（第一个DNS）然后就获取不到信息。

**Comment by chengr28** [comment]
看起来是无解？这边无法重现这个问题……也不知道和网络环境是不是也有关系。

**Comment by sysconfon** [comment]
@chengr28 目前我也未找到可行性解决方案。0.4.9.4测试没问题。0.4.9.5测试异常。0.4.9.6暂未测试。最近会考虑测试看看是否还存在问题。

**Comment by chengr28** [comment]
或者这样吧，有空可以测试一下看看，如果还有问题直接回复就行。
