### ISSUE TITLE
[Question] 技术支持是否同时包含 pre-release 与 release

### ISSUE THREAD

**Issue by Rictusempra** [chengr28/Pcap_DNSProxy#312]
见于 [README](https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe.zh-Hans.txt) 安装方法一节中第七条；
个人认为应该予以明确

**Comment by chengr28** [comment]
都会支持。现在的更新策略是 release 为正式版本 pre-release 为测试版本，一般来说是几个测试版本再更新一个正式版本，两者都只支持该分支最新的版本这样。当然因为 pre-release 的版本是实际上的最新，release 如果遇到问题这边也会建议先更新到 pre-release 测试看看。
