### ISSUE TITLE
windows hyper-v server 2016 x64 下无法正常运行。

### ISSUE THREAD

**Issue by wctliu** [chengr28/Pcap_DNSProxy#314]
﻿### Version/使用的版本/使用的版本
Pcap_DNSProxy 0.4.9.4、0.4.9.5
Windows
64位/x64版本：Windows Vista/2008 以及更新的版本

### Running Environment/运行环境/運行環境

安装环境为：windows hyper-v server 2016 x64  结果为：无法运行。

点击1安装后的提示
[SC] OpenService 失败 1060:
指定的服务未安装。
[SC] OpenService 失败 1060:
指定的服务未安装。
错误: 没有找到进程 "Pcap_DNSProxy.exe"。
[SC] CreateService 成功
操作成功完成。
操作成功完成。
[SC] ChangeServiceConfig2 成功
[SC] ChangeServiceConfig2 成功
[SC] StartService 失败 1053:
服务没有及时响应启动或控制请求。
Windows IP 配置
已成功刷新 DNS 解析缓存。
The program is not running, please check the configurations and error log.
请按任意键继续. . .

点击3 启动服务。出错提示“
[SC] ControlService 失败 1062:
服务尚未启动。
错误: 没有找到进程 "Pcap_DNSProxy.exe"。
[SC] StartService 失败 1053:
服务没有及时响应启动或控制请求。
Windows IP 配置
已成功刷新 DNS 解析缓存。
The program is not running, please check the configurations and error log.
请按任意键继续. . .

点击2 删除服务后。重新点1安装，出错提示：
[SC] ControlService 失败 1062:
服务尚未启动。
[SC] DeleteService 成功
错误: 没有找到进程 "Pcap_DNSProxy.exe"。
[SC] CreateService 失败 1072:
指定的服务已标记为删除。
操作成功完成。
值 AppDirectory 已存在，要覆盖吗(Yes/No)?
值 AppDirectory 已存在，要覆盖吗(Yes/No)? yes
操作成功完成。
[SC] ChangeServiceConfig2 失败 1072:
指定的服务已标记为删除。
[SC] ChangeServiceConfig2 失败 1072:
指定的服务已标记为删除。
[SC] StartService 失败 1058:
无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。
Windows IP 配置
已成功刷新 DNS 解析缓存。
The program is not running, please check the configurations and error log.
请按任意键继续. . .

**Comment by chengr28** [comment]
程序目录有生成 Error.log 之类的错误报告吗？

**Comment by chengr28** [comment]
如果还有什么问题可以直接在这里回复。
