### ISSUE TITLE
开启服务后对ftp支持的不好

### ISSUE THREAD

**Issue by jorismq** [chengr28/Pcap_DNSProxy#315]
我反复开启关闭多次，只要关了，打开ftp顺利
一打开，就不行。换DNS也不行

ftp://ftp.ncbi.nlm.nih.gov

**Comment by chengr28** [comment]
这是玄学吧，这边没发现有问题……个人唯一想到的一种可能性是监听端口和 FTP 所使用的端口重叠了，实际上两个是完全不一样的协议，端口理论上也不会相同。
