### ISSUE TITLE
更新检查安装

### ISSUE THREAD

**Issue by Rictusempra** [chengr28/Pcap_DNSProxy#316]
﻿### Version/使用的版本/使用的版本

0.4.9.5

### Running Environment/运行环境/運行環境

Windows 10.16299.98

### Expectation/期望情况/期望情況

至少应该能告知用户更新可用

### Actual/实际情况/實際情況

N/A

**Comment by chengr28** [comment]
关于这个问题之前也有人提过类似的建议，但是这边有几个理由：
* 更新依赖某个固定的地址，有失效和加重服务器负担的风险
* 本程序后台静默运行，没有图形界面
* 输出成错误报告不太可能有人会时常留意

**Comment by Rictusempra** [comment]
@chengr28 地址的话 GitHub本身就可以提供啊
返回一个提示信息让用户知道有没有更新就可以了

至于界面，加一个选项到bat里不就好了？

**Comment by chengr28** [comment]
做到 bat 里就没有意义了，还是要人点一下还不如直接访问网页……

**Comment by Rictusempra** [comment]
@chengr28 发布到 [chocolatey](https://chocolatey.org) 如何？

**Comment by chengr28** [comment]
暂时没有计划。
