### ISSUE TITLE
Pcap_DNSProxy内智能解析问题（严重）

### ISSUE THREAD

**Issue by sysconfon** [chengr28/Pcap_DNSProxy#318]
﻿### Version/使用的版本/使用的版本

0.4.9.4
0.4.9.5

### Running Environment/运行环境/運行環境

windows 2012 r2    windows  server 2016

### Actual/实际情况/實際情況

配置信息如下：
[Addresses]
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 
IPv4 Main DNS Address = 47.88.174.139:5353
IPv4 Alternate DNS Address = 65.49.219.123:5353
IPv4 Local Main DNS Address = 208.67.222.222:5353
IPv4 Local Alternate DNS Address = 208.67.220.220:5353
IPv6 Listen Address = 
IPv6 EDNS Client Subnet Address = 
IPv6 Main DNS Address = 
IPv6 Alternate DNS Address = 
IPv6 Local Main DNS Address = 
IPv6 Local Alternate DNS Address = 

问题说明：
[Addresses]区域配置文件不变。
[Local DNS]区域配置文件如下：
Local Hosts = 1
Local Routing = 1
Local Force Request = 1
出现问题：
dig www.boip.net 无法解析，提示如下：
; <<>> DiG 9.10.6 <<>> www.boip.net
;; global options: +cmd
;; connection timed out; no servers could be reached
nslookup www.boip.net无法解析，提示如下：
Server:  pcap-dnsproxy.server
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to pcap-dnsproxy.server timed-out

dig ip.dnspod.net正常解析，能智能解析，并且有双出口。显示如下：
; <<>> DiG 9.10.6 <<>> ip.dnspod.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53636
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ip.dnspod.net.                 IN      A

;; ANSWER SECTION:
ip.dnspod.net.          0       IN      A       67.215.80.71
ip.dnspod.net.          0       IN      A       39.106.155.0

;; Query time: 312 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Dec 20 20:36:30 China Standard Time 2017
;; MSG SIZE  rcvd: 74

[Addresses]区域配置文件不变。
[Local DNS]区域配置文件如下：
Local Hosts = 1
Local Routing = 1
Local Force Request = 0
出现问题：
dig www.boip.net 正常解析，提示如下：
; <<>> DiG 9.10.6 <<>> www.boip.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50219
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.boip.net.                  IN      A

;; ANSWER SECTION:
www.boip.net.           600     IN      CNAME   boip.net.cdnway.net.
boip.net.cdnway.net.    60      IN      CNAME   gslb.cdnway.net.
gslb.cdnway.net.        60      IN      A       47.88.158.242

dig ip.dnspod.net正常解析，但是不支持edns。出口变成IPv4 Main DNS Address里面的IP。本地出口IP未带入进去。
; <<>> DiG 9.10.6 <<>> ip.dnspod.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52083
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ip.dnspod.net.                 IN      A

;; ANSWER SECTION:
ip.dnspod.net.          0       IN      A       47.88.174.139

**Comment by chengr28** [comment]
不好意思最近比较忙没有时间顾及这边……是这样的，这个 `Local Hosts` + `Local Routing` + `Local Force Request` 的逻辑的确是有些问题的。

测试了一下，如果三个参数同时开启的话效果是：所有（除了黑名单所指定的）请求都会先发送至境内服务器进行域名解析，然后根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者。然而不幸的是 boip.net 这个域名虽然在白名单中，但解析出来却不是大陆的地址，导致 `Local Routing` 的配置生效而导致解析结果被剔除，又由于 `Local Force Request` 是启用状态，导致解析走不下去就没有结果了……

**Comment by chengr28** [comment]
下次更新境内请求的部分会使用新的逻辑判断：
* 默认情况下在境内服务器解析失败会进行下一步的操作
* 所有参数均为关闭时，直接跳过使用境内服务器进行域名解析的过程
* Local Hosts 可以单独开启：将按照（黑）白名单（无）命中规则的域名，才（不）使用境内服务器进行解析
* Local Routing 可以单独开启：所有请求都会先发送至境内服务器进行域名解析，然后根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者
* Local Force Request 不能单独启用：需要和 Local Hosts 配合使用
* Local Hosts + Local Routing 不能同时启用：功能冲突
* Local Hosts + Local Force Request 可以同时启用：强制已命中规则的域名只能使用境内服务器进行解析，解析结果有问题将直接丢弃并终止整个解析过程
* Local Routing + Local Force Request 不能同时启用：功能冲突
* Local Hosts + Local Routing + Local Force Request 可以同时启用：所有（除了黑名单所指定的）请求都会先发送至境内服务器进行域名解析，根据请求的性质：
  * 如果该请求的域名命中 Local Hosts 则强制已命中规则的域名只能使用境内服务器进行解析，解析结果有问题将直接丢弃并终止整个解析过程
  * 如果该请求的域名没有命中 Local Hosts 则根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者
  * 所有没有命中且没有成功匹配路由表的请求将会进行下一步的操作

**Comment by chengr28** [comment]
刚才推送的更新应该解决这个问题了，有时间可以测试一下看看，有问题直接在这里回复就行，谢谢。
