### ISSUE TITLE
安装了为何steam仍然被污染打不开讨论区

### ISSUE THREAD

**Issue by viewtheard** [chengr28/Pcap_DNSProxy#319]
﻿### Version/使用的版本/使用的版本
0.4.9.4

### Running Environment/运行环境/運行環境
win10

### Expectation/期望情况/期望情況
避免污染

### Actual/实际情况/實際情況
为何steam仍然被污染打不开讨论区，愿望单，市场，需要修改啥参数吗?

**Comment by Rictusempra** [comment]
@viewtheard HTTP 重置
客户端未使用 TLS 连接

**Comment by viewtheard** [comment]
@Rictusempra 这次事件不只是单纯的dns污染吗？还有其他干扰？

**Comment by chengr28** [comment]
```
非权威应答:
名称:    steamcommunity.com
Address:  69.171.228.74
```

DNS 投毒污染无误，至于忽略投毒后还是不能访问，大概是有其它方式干扰，屏蔽 IP 地址之类的。
