### ISSUE TITLE
hostname change

### ISSUE THREAD

**Issue by messiahluo** [chengr28/Pcap_DNSProxy#32]
OS X 上安装后hostname变成pcap-dnsproxy.localhost.server了，问下这个对程序有影响么？可以改掉么。

**Comment by yfdyh000** [comment]
没有影响。`Localhost Server Name` 可以改。
https://github.com/chengr28/Pcap_DNSProxy/blob/470ab1e4757c2b61c81ced4c626af349f0e29785/Documents/ReadMe%28zh_Hans%29.txt#L470

**Comment by messiahluo** [comment]
@yfdyh000 啊，多谢，看来得去仔细看看文档。。。

**Comment by chengr28** [comment]
这样吧分成两个部分来说：
* OS X 里变成 `pcap-dnsproxy.localhost.server` 的确是程序的问题……这个功能创立 GitHub 项目前就有，目的是实现 Windows 下 nslookup 反查地址时能看到程序的名称，Linux 也没有这方面的问题，但最后没想到 OS X 似乎是利用了类似的机制实现 Hostname 这样程序相当于覆盖了系统的设定……所以刚才更新的 0.4.1 里 OS X 版已经移除了这个功能，升级重启后应该就不会影响系统的设定了
* 至于那个名称的修改，参见 2L 的链接里文档的介绍
