### ISSUE TITLE
[Network Error] TCP socket connecting error: Connection refused[111]

### ISSUE THREAD

**Issue by WoChen5770** [chengr28/Pcap_DNSProxy#324]
﻿### Version/使用的版本/使用的版本

0.4.9.5

### Running Environment/运行环境/運行環境

ubuntu16.04

### Expectation/期望情况/期望情況
开启如下任何一个选项
Local Hosts = 0
Local Routing = 0
一切正常，不出现 [Network Error] TCP socket connecting error: Connection refused[111]。

### Actual/实际情况/實際情況
就会出现 [Network Error] TCP socket connecting error: Connection refused[111]。

还有个问题，fonts.gstatic.com不能解析

**Comment by chengr28** [comment]
填写在配置文件中的 Local DNS 的 TCP 协议请求是正常的吗？看起来像是这边请求 TCP 连接时被远程服务器拒绝了。

**Comment by WoChen5770** [comment]
> 
[Listen]
Process Unique = 1
Pcap Capture = 1
Pcap Devices Blacklist = AnyConnect|Host|Hyper|ISATAP|IKE|L2TP|Only|Oracle|PPTP|Pseudo|Teredo|Tunnel|Virtual|VMNet|VMware|VPN|any|gif|lo|stf|tunl|utun
Pcap Reading Timeout = 60
Listen Protocol = IPv4 + TCP + UDP
Listen Port = 53
Operation Mode = Server
IPFilter Type = Deny 
IPFilter Level < 0
Accept Type =  

[DNS]
Outgoing Protocol = IPv4 + UDP 
Direct Request = 0
Cache Type = Timer + Queue
Cache Parameter = 3600
Cache Single IPv4 Address Prefix = 24
Cache Single IPv6 Address Prefix = 0
Default TTL = 1800

[Local DNS]
Local Protocol = IPv4 + UDP
Local Hosts = 0
Local Routing = 0
Local Force Request = 0

[Addresses]
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 
IPv4 Main DNS Address =  8.8.8.8:53
IPv4 Alternate DNS Address = 8.8.4.4:53
IPv4 Local Main DNS Address = 119.29.29.29:53
IPv4 Local Alternate DNS Address = 119.28.28.28:53
IPv6 Listen Address = 
IPv6 EDNS Client Subnet Address = 
IPv6 Main DNS Address = 
IPv6 Alternate DNS Address = 
IPv6 Local Main DNS Address = 
IPv6 Local Alternate DNS Address = 
>

**Comment by WoChen5770** [comment]
TCP Fast Open = 0
TCP Data Filter = 0
有关tcp的基本都关闭了。只要
Local Hosts = 0
Local Routing = 0
 这两个个选项开启其中一个就会出现那个错误，而且查询时间有2s多，不开启只有不到100ms

**Comment by chengr28** [comment]
测试表明 `119.28.28.28` 和 `119.29.29.29` 不支持 TCP 协议进行请求，那么得到 `Connection refused` 也是正常的情况……

**Comment by WoChen5770** [comment]
关键是我上游dns没开tcp啊

**Comment by chengr28** [comment]
那还真是奇怪……因为拒绝连接这种事情基本只有 TCP 才有的错误，不开不会尝试用 TCP 的，最重要是这边测试过纯 UDP 的话那两台 Local DNS 似乎是正常的。修改配置后有重启过服务吗？

**Comment by chengr28** [comment]
关于 `fonts.gstatic.com` 不能解析的问题……这个问题实际上和 `Strict Resource Record TTL Filter` 这个参数有关。按照 RFC 标准的要求，这个严格检查对于所有 DNS 解析都必须遵守，节录如下：

> Each DNS Resource Record (RR) has a label, class, type, and data.  It is meaningless for two records to ever have label, class, type and data all equal - servers should suppress such duplicates if encountered.  It is however possible for most record types to exist with the same label, class and type, but with different data.  Such a group of records is hereby defined to be a Resource Record Set (RRSet).
> ..
> Consequently the use of differing TTLs in an RRSet is hereby deprecated, ***the TTLs of all RRs in an RRSet must be the same.***
> ..
> ***Should a client receive a response containing RRs from an RRSet with differing TTLs, it should treat this as an error.***  If the RRSet concerned is from a non-authoritative source for this data, the client should simply ignore the RRSet, and if the values were required, seek to acquire them from an authoritative source.  Clients that are configured to send all queries to one, or more, particular servers should treat those servers as authoritative for this purpose. Should an authoritative source send such a malformed RRSet, the client should treat the RRs for all purposes as if all TTLs in the RRSet had been set to the value of the lowest TTL in the RRSet.  ***In no case may a server send an RRSet with TTLs not all equal.***

Google 本意应该是通过设置自己的 NS 服务器为天朝用户提供定制的解析服务使得服务可以在境内正常使用，然而让人感到奇怪而且不幸的是他们在设置 `fonts.gstatic.com` 时 RRSet 的 TTLs 不统一，导致无法通过程序的内置检查……

或者这样吧，下次更新会把 `Strict Resource Record TTL Filter` 参数加回去，到时候把这个选项关掉应该就能解决问题了……感谢反馈。

**Comment by WoChen5770** [comment]
拒绝连接这种事情:
       我重启了，甚至还重启了服务器。你能在你的服务器上重现吗

**Comment by chengr28** [comment]
并不，默认配置就有开那个选项，并没有会变成使用 TCP 协议的问题。配置文件里默认会开 TCP 协议的除了监听端口 `Listen Protocol` 外就只有 `Domain Test Protocol` 了，这个是对填在 Main/Alternate 那些境外 DNS 进行测试的参数，你也可以调整一下。

除非改的配置文件和实际使用的不是同一个这种问题，再不行只能抓包了。

**Comment by WoChen5770** [comment]
我试了一下，把119改成8.8.8.8就没这个错误。119dns 直接dig是没有结果的，必须加+nocookie参数。报错跟这个有没有关系？

**Comment by WoChen5770** [comment]
最后换成alidns了。没这个错误了，而且响应也快。估计是dnspod的dns有问题

**Comment by chengr28** [comment]
DNS Cookies 好像是基于 EDNS 的新技术，新版 dig 默认启用，然而有些完全不支持 EDNS 的服务器估计直接就跪了……好吧，看起来是服务器的问题。

**Comment by WoChen5770** [comment]
119dns是支持ECS的啊，你的意思是我服务器的问题吗？我服务器的dig是9.10的，默认是不启用cookie的

**Comment by chengr28** [comment]
这个得慢慢做测试了看实验结果了，这边不对个别服务器的情况做特殊处理。

**Comment by chengr28** [comment]
从测试结果来看 119 的确是支持 EDNS 的，不过对于不支持的 EDNS 选项会造成直接丢弃请求，个人估计那个 2s 的超时就是这样来的，2000 ms 是程序 UDP 协议的默认超时时间。

**Comment by WoChen5770** [comment]
意思是请求的时候要加上nocookie是吗？是的话，你能不能做支持呢？毕竟国内支持ecs的就119和223.而223自己说还不完善。如果不能支持的话只能用google的了，google的延时也只有20多ms，还可以

**Comment by chengr28** [comment]
DNS Cookie 的问题这边会记下来，有时间会做一下处理。不过根据实际测试，程序本身对于 DNS Cookie 的 EDNS 标签是不做处理的，也就是说你发的请求有 DNS Cookie（dig 9.11 默认）这边出去就会有，没有 DNS Cookie（dig +nocookie 或者以前不支持的时候）发出去就不会带有这个。

顺便 Google Public DNS 写这个回复时测试，并不支持 DNS Cookie 功能，但是他们不会因为不支持这个特性就直接丢弃请求，所以看上去是正常的。

**Comment by WoChen5770** [comment]
你好，新版这个问题好像还是存在。
问题是，8.8.8.8或者223.5.5.5对于ecs支持不是很理想。
比如8.8.8.8解析qq.com错误而www.qq.com正确。223.5.5.5也有些网站不正常，很尴尬。
请问要怎样才能支持119dns呢？

**Comment by chengr28** [comment]
『测试表明 `119.28.28.28` 和 `119.29.29.29` 不支持 TCP 协议进行请求』
你把 TCP 协议关掉就会正常了

**Comment by chengr28** [comment]
对了还有一个情况就是，如果你给程序发送请求的时候用的是 TCP 协议（例如 `dig` 加上 `+vc` 之类）那么程序会忽略配置文件中指定协议的功能，也会使用 TCP 协议请求。

其实现在最重要的问题是不知道为什么 119 不支持 TCP

**Comment by WoChen5770** [comment]
我按照你说的 把Domain Test Protocol 关掉tcp。
dig 加上 +tcp 测试,是会报 Connection refused[111] 错误。查询时间是2000ms以上，
dig 不加 +tcp 测试,不报错误。但是查询时间还是2000ms以上。
换上8.8.8.8或者223.6.6.6，不管怎样都不报错，查询时间也为几十秒 。
确实 关掉tcp 并且不加 +tcp 不报错，查询时间是啥原因

**Comment by chengr28** [comment]
能提供一份出问题的配置文件吗？就是第二种情况，查询时间 2000ms 的

**Comment by WoChen5770** [comment]
@chengr28
http://cdn.ichenqiang.com/Config.conf

**Comment by chengr28** [comment]
不好意思，最近都没什么时间研究这边的事情。
关于这个第二种情况，直接使用提供的配置文件，用不同的命令似乎重现了这个问题。

* `dig 域名` 会出现 2000ms 以上的延迟
* `dig +nocookie 域名` 不会出现 2000ms 以上的延迟

这归根到底还是 119DNS 不支持（以他们的角度来看）未知 EDNS 格式的请求。首先是新版本 `dig` 不加参数默认是开启 DNS Cookies 功能的，然后把请求发送到 119DNS 然而他们收到这种格式的请求却直接没有任何响应，等到超时时间（2000ms）之后程序就继续请求，之后才有可能拿到结果。

**Comment by WoChen5770** [comment]
确实是这样。
能不能在Pcap_DNSProxy的配置文件加个Cookies 的开关呢？

**Comment by chengr28** [comment]
和开关没有关系啊，如果发过来的请求本身就带有 DNS Cookie 是不会去掉的，就算是以后再添加开关，也只是『是否帮忙加上』的意思，不是『加上或者去掉』的意思。
