### ISSUE TITLE
谁有只是域名污染的网站

### ISSUE THREAD

**Issue by viewtheard** [chengr28/Pcap_DNSProxy#325]
谁有只是域名污染的，没有其他干扰的网站样本，想好好测试下。

**Comment by Rictusempra** [comment]
zh.wikipedia.org

**Comment by chengr28** [comment]
这个不好说，使用什么手段屏蔽一个网站完全是不可预测的行为，现在是只有 DNS 投毒污染可能下一秒 IP 地址就被屏蔽了。
