### ISSUE TITLE
被 homebrew-core 移除了

### ISSUE THREAD

**Issue by sirius60111** [chengr28/Pcap_DNSProxy#326]
相关 [commit](https://github.com/Homebrew/homebrew-core/commit/4e49e65be8633ff1a3726a97fcc8053a0b93cb2b)

**Comment by chengr28** [comment]
被扫地出门也没有办法……他们那边移除 formula 一个有可能的原因是几乎没人在用，可能他们那边有安装的统计数据，低于某个阈值一定时间就会被自动移除。这边也不会强求，下次更新会把 Homebrew 相关的全部移除。

**Comment by sirius60111** [comment]
能不能保留并更新 pcap_dnsproxy.rb，这样的话可以比较方便的更新

**Comment by chengr28** [comment]
保留是没问题，不过 rb 里有个是 GitHub commit 的 Hash 需要这边更新后才能使用，也就是每次都必须在正式版之后一个版本才能更新……

**Comment by sirius60111** [comment]
明白
