### ISSUE TITLE
ReadParameter.cpp:3208:6: error: use of undeclared identifier 'sodium_base64_VARIANT_ORIGINAL'

### ISSUE THREAD

**Issue by WoChen5770** [chengr28/Pcap_DNSProxy#327]
﻿### Version/使用的版本/使用的版本
0.4.9.6

### Running Environment/运行环境/運行環境

ubuntu 16.04 编译出错

**Comment by chengr28** [comment]
无法编译是因为系统包管理的 libsodium-dev 库版本太旧，有两种解决方法：

* 卸载 libsodium-dev 并到 libsodium 下载编译和安装最新版本
* 编译运行脚本时添加 `--disable-libsodium` 禁用加密库

**Comment by WoChen5770** [comment]
可以了，升级了libsodium。感谢解答。
