### ISSUE TITLE
在ubuntu 16.04上最新的0.4.9.6编译失败，前版没问题

### ISSUE THREAD

**Issue by wangmice** [chengr28/Pcap_DNSProxy#329]
﻿### Version/使用的版本/使用的版本
0.4.9.6

### Running Environment/运行环境/運行環境
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Configuring done
-- Generating done

### Actual/实际情况/實際情況
Source/Pcap_DNSProxy/ReadParameter.cpp: In function ‘bool ReadParameterData(std::__cxx11::string, size_t, bool, size_t)’:
/home/wangmice/openwrt/src/Pcap_DNSProxy/Source/Pcap_DNSProxy/ReadParameter.cpp:3208:6: error: ‘sodium_base64_VARIANT_ORIGINAL’ was not declared in this scope
      sodium_base64_VARIANT_ORIGINAL) == nullptr)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wangmice/openwrt/src/Pcap_DNSProxy/Source/Pcap_DNSProxy/ReadParameter.cpp:3203:8: error: ‘sodium_bin2base64’ was not declared in this scope
    if (sodium_bin2base64(
        ^~~~~~~~~~~~~~~~~
/home/wangmice/openwrt/src/Pcap_DNSProxy/Source/Pcap_DNSProxy/ReadParameter.cpp:3203:8: note: suggested alternative: ‘sodium_bin2hex’
    if (sodium_bin2base64(
        ^~~~~~~~~~~~~~~~~
        sodium_bin2hex

**Comment by wangmice** [comment]
是libsodium的版本太低吗？

**Comment by chengr28** [comment]
之前的 https://github.com/chengr28/Pcap_DNSProxy/issues/327 说的就是这个事情。
