### ISSUE TITLE
Windows 10 每次大版本更新以后服务没了

### ISSUE THREAD

**Issue by l5h5t7** [chengr28/Pcap_DNSProxy#330]
﻿### Version/使用的版本/使用的版本

0.4.9.6

### Running Environment/运行环境/運行環境

Windows 10 Pro 1709 (64-bit)

### Expectation/期望情况/期望情況

大版本更新后服务依然正常工作，然后安然无事。

### Actual/实际情况/實際情況

Windows 大版本更新后 PcapDNSProxyService 没了（但是其他软件的服务基本都正常），然后七大姑八大姨开始联系我抱怨更新后就没网了。自家的电脑自己再装一遍服务就好了，但是别人家的电脑远程教一遍操作人家又不一定能听懂。

**Comment by chengr28** [comment]
那还真是奇怪，因为目前使用的方法是 MS 官方提供的……而且不好测试，有时间这边研究一下是怎么回事，或者可以先去 MS 那边问一下？

**Comment by whka** [comment]
同Windows 10 Pro 1709，我这边也出问题了![9otNX8.png](https://s1.ax1x.com/2018/03/18/9otNX8.png)

**Comment by chengr28** [comment]
然而根据 1803 实际的测试，升级完成后服务并没有出现丢失的问题……
