### ISSUE TITLE
可否更新下brew的版本，感谢了！

### ISSUE THREAD

**Issue by tudi1909** [chengr28/Pcap_DNSProxy#331]
﻿### Version/使用的版本/使用的版本
0.4.9.4

### Running Environment/运行环境/運行環境
macOS 10.13.3

### Expectation/期望情况/期望情況
查询brew上面是0.4.9.4的版本可否更新下？

**Comment by chengr28** [comment]
Homebrew 已经将本项目扫地出门，以后都不会再有 Homebrew 的支持。

**Comment by tudi1909** [comment]
好的 多谢了～
