### ISSUE TITLE
树莓派3 无法编译

### ISSUE THREAD

**Issue by asd2003asd** [chengr28/Pcap_DNSProxy#333]
root@raspberrypi:/home/pi/Pcap_DNSProxy/Source/Auxiliary/Scripts# ./CMake_Build.sh
mkdir: 无法创建目录"Release": 文件已存在
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/arm-linux-gnueabihf/libssl.so;/usr/lib/arm-linux-gnueabihf/libcrypto.so (found version "1.0.1t") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Pcap_DNSProxy/Source/Object
Scanning dependencies of target Pcap_DNSProxy
[ 13%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o
[ 13%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
[ 13%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o
[ 18%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurve.cpp.o
/home/pi/Pcap_DNSProxy/Source/Pcap_DNSProxy/DNSCurve.cpp: In function ‘void DNSCurveSocketPrecomputation(uint16_t, const uint8_t*, size_t, size_t, uint8_t**, uint8_t**, DNSCURVE_SERVER_DATA**, std::vector<_socket_data_>&, std::vector<DNSCurveSocketSelectingTable>&, std::unique_ptr<unsigned char []>&, size_t&, std::unique_ptr<unsigned char []>&, size_t&)’:
/home/pi/Pcap_DNSProxy/Source/Pcap_DNSProxy/DNSCurve.cpp:337:124: error: ‘sodium_is_zero’ was not declared in this scope
    ((!DNSCurveParameter.IsClientEphemeralKey && sodium_is_zero((*PacketTarget)->PrecomputationKey, crypto_box_BEFORENMBYTES) != 0) || 
                                                                                                                            ^
/home/pi/Pcap_DNSProxy/Source/Pcap_DNSProxy/DNSCurve.cpp:445:124: error: ‘sodium_is_zero’ was not declared in this scope
    ((!DNSCurveParameter.IsClientEphemeralKey && sodium_is_zero((*PacketTarget)->PrecomputationKey, crypto_box_BEFORENMBYTES) != 0) || 
                                                                                                                            ^
CMakeFiles/Pcap_DNSProxy.dir/build.make:134: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/DNSCurve.cpp.o' failed
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/DNSCurve.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
mv: 无法获取"Object/Pcap_DNSProxy" 的文件状态(stat): 没有那个文件或目录
mkdir: 无法创建目录"Release/Tools": 文件已存在

**Comment by chengr28** [comment]
请更新 LibSodium 的版本。

**Comment by asd2003asd** [comment]
好像没编译成功：/tmp/ccHILVzB.ltrans13.ltrans.o：在函数‘DNSCurveConfigurationTable::MonitorItemToUsing(DNSCurveConfigurationTable*)’中：
ccHILVzB.ltrans13.o:(.text+0x3608)：对‘sodium_is_zero’未定义的引用
ccHILVzB.ltrans13.o:(.text+0x3628)：对‘sodium_is_zero’未定义的引用
ccHILVzB.ltrans13.o:(.text+0x3648)：对‘sodium_is_zero’未定义的引用
ccHILVzB.ltrans13.o:(.text+0x3668)：对‘sodium_is_zero’未定义的引用
ccHILVzB.ltrans13.o:(.text+0x3688)：对‘sodium_is_zero’未定义的引用
/tmp/ccHILVzB.ltrans2.ltrans.o：在函数‘ReadParameterData(std::string, unsigned int, bool, unsigned int)’中：
ccHILVzB.ltrans2.o:(.text+0x37f0)：对‘sodium_bin2base64’未定义的引用
/tmp/ccHILVzB.ltrans8.ltrans.o：在函数‘DNSCurveInit()’中：
ccHILVzB.ltrans8.o:(.text+0x1b14)：对‘sodium_is_zero’未定义的引用
ccHILVzB.ltrans8.o:(.text+0x1b38)：对‘sodium_is_zero’未定义的引用
ccHILVzB.ltrans8.o:(.text+0x1ca0)：对‘sodium_is_zero’未定义的引用
ccHILVzB.ltrans8.o:(.text+0x1cd8)：对‘sodium_is_zero’未定义的引用
ccHILVzB.ltrans8.o:(.text+0x1d4c)：对‘sodium_is_zero’未定义的引用
/tmp/ccHILVzB.ltrans8.ltrans.o:ccHILVzB.ltrans8.o:(.text+0x1d70): 跟着更多未定义的参考到 sodium_is_zero
collect2: error: ld returned 1 exit status
CMakeFiles/Pcap_DNSProxy.dir/build.make:616: recipe for target 'Pcap_DNSProxy' failed
make[2]: *** [Pcap_DNSProxy] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
mv: 无法获取"Object/Pcap_DNSProxy" 的文件状态(stat): 没有那个文件或目录
