### ISSUE TITLE
有关于在双isp双拨的情况下使用Pcap_DNSProxy

### ISSUE THREAD

**Issue by kingofotaku** [chengr28/Pcap_DNSProxy#336]
﻿### Version/使用的版本/使用的版本
0.4.9.6

### Running Environment/运行环境/運行環境

win10 x64

### Expectation/期望情况/期望情況
对双isp混合网络的优化

### Actual/实际情况/實際情況
只是想问一下，我的路由器是没做策略路由的双isp并用。会完全随机地出现跳ip和随机叠加带宽又或不叠加。请问在这样的情况下有没有办法在pc端的Pcap_DNSProxy上调整某些设置以更好地应对这种情况（例如减少跳ip或者增加叠加几率，尽管这两者之间可能存在矛盾）

**Comment by chengr28** [comment]
并没有……Pcap_DNSProxy 使用系统的 API 发送和接收数据，也就是说路由策略是系统协议栈决定，数据包的转发对于上层来说是透明的。也就是说，系统协议栈使用时是什么效果，程序使用就会是什么效果。
