### ISSUE TITLE
请求 pcap-dnsproxy.server 超时

### ISSUE THREAD

**Issue by PoiHolic** [chengr28/Pcap_DNSProxy#337]
﻿### Version/使用的版本/使用的版本

Pcap_DNSProxy 0.4.9.6

### Running Environment/运行环境/運行環境

Win 10 专业版  1709
Pcap_DNSProxy conf 默认配置
仅修改Outgoing Protocol = IPv6 + IPv4 + TCP

### Expectation/期望情况/期望情況

系统首次启动，Pcap_DNSProxy就运行正常

### Actual/实际情况/實際情況
启动电脑后，发现DNS失效
运行
```
 nslookup www.google.com 127.0.0.1
    DNS request timed out.
        timeout was 2 seconds.
    DNS request timed out.
        timeout was 2 seconds.
    DNS request timed out.
        timeout was 2 seconds.
    DNS request timed out.
        timeout was 2 seconds.
```

**根据 FAQ**
1. nslookup www.google.com 8.8.4.4正常提供服务，
2. 重启服务，未解决
3. 重启系统，暂时解决
4. 第二天在开机，问题依旧，重启系统，暂时解决
5. FAQ提到因为长时间运行有错误累积造成

**Comment by SeaHOH** [comment]
看下 53 端口，是不是正常监听。

**Comment by PoiHolic** [comment]
```
netstat -an
UDP    0.0.0.0:53
TCP    0.0.0.0:53
UDP    [::]:53
TCP    [::]:53
```
@SeaHOH 
是不是没有正常监听？

**Comment by SeaHOH** [comment]
监听应该正常，只是谷歌无法解析吗？

**Comment by PoiHolic** [comment]
出现故障时候所有网站都无法解析（除了昨天缓存过），现在可能重启过暂时正常所以诊断看不出，明天开机故障的时候，我再查一下。

**Comment by SeaHOH** [comment]
都重启了，跟缓存扯不上关系。
如果你的 IPv6 不是原生的，或许把 Outgoing Protocol 改回去会好点，虽然会自动选择协议，但说不定这样响应时间过长（我没这样用过）。

**Comment by PoiHolic** [comment]
现在都改成原生的了，这几天试试效果，最后感谢建议Thanks♪(･ω･)ﾉ

**Comment by PoiHolic** [comment]
不好意思，表述错误了，应该是默认配置。因为我不用IPv6，按照你的建议都改回默认配置。今天开机正常！

**Comment by SeaHOH** [comment]
嗯，估计就是这样。先关掉吧，如果有问题再来问 28 小朋友~

**Comment by chengr28** [comment]
`IPv6 + IPv4` 的话，是 IPv6 优先，如果不行才会尝试 `IPv4` 不过这个『不行』指的是完全没有 IPv6 的支持，现代的操作系统默认都有开启 IPv6 协议栈的功能，所以『不行』的情况几乎没有。如果在不支持 IPv6 的情况下强开，那自然是无法正常工作了……

**Comment by PoiHolic** [comment]
我下次再也不订电脑报了2333，我下次一定认真读ReadMe
[http://www.icpcw.com/Information/rwgd/News/3309/330913.htm](url)
第二节中介绍了pcap-dnsproxy
