### ISSUE TITLE
关于指定域名服务器解析特定域名问题

### ISSUE THREAD

**Issue by Humanorino** [chengr28/Pcap_DNSProxy#338]
﻿### Version/使用的版本/使用的版本
0.4.9.4

### Running Environment/运行环境/運行環境
win10

### Expectation/期望情况/期望情況
关于某类域名,例如xyz.edu.cn这样的域名,想要指定例如114.114.114.114去解析.

### Actual/实际情况/實際情況
在Hosts.ini文件里的Local Hosts项里,添加了Server=/: . * \ xyz.edu.cn:/114.114.114.114,分析的时候,用nslookup www.xyz.edu.cn 时,发现还是没有使用114.114.114.114去解析, 而对于Server=/: . * \ abcde.edu.cn:/114.114.114.114,可以用114去解析www.abcde.edu.cn. 后来改为解析.xyz.edu.cn,即Server=/: . * \ . xyz.edu.cn:/114.114.114.114时,发现会使用114去解析了,请问什么原因

**Comment by chengr28** [comment]
正则表达式的问题。

    .*\xyz.edu.cn
    .*\abcde.edu.cn
    .*\.xyz.edu.cn

`\.` 是把有特殊含义的符号 `.` 转义成普通的 `.`
`\x` 和 `\b` 是什么鬼？
