### ISSUE TITLE
反向查询时会被重定向至tcp连接

### ISSUE THREAD

**Issue by mewsf** [chengr28/Pcap_DNSProxy#339]
﻿### Version/使用的版本/使用的版本

0.4.9.6

### Running Environment/运行环境/運行環境

Debian 9.4 x86_64

### Expectation/期望情况/期望情況

查询ptr记录时应当能直接返回结果 例如mtr会在路由追踪里标明ip反向解析的结果

### Actual/实际情况/實際情況

用dig -x x.x.x.x @127.0.0.1 时会出现;; Truncated, retrying in TCP mode.
使用mtr时会因此导致解析失败

**Comment by chengr28** [comment]
不知道具体是哪个地址会造成这种情况，还有是否开启了 EDNS 或者 DNSSEC 之类的参数？

`Truncated, retrying in TCP mode` 的意思是报文超长，需要使用 TCP 进行重试。
每个服务器都有一个 UDP 报文长度的硬性限制，程序的是接近 Ethernet 的最大可容纳长度，大约 1400 字节左右。如果请求的或者远程服务器回复的长度超过此值，会设置 Truncated 标志让请求者使用 TCP 协议重试。这个操作有可能是程序做的，也可能是远程 DNS 服务器做的，具体的情况最好抓一下包。

**Comment by mewsf** [comment]
我没有开启过dnssec功能，但是EDNS Label =  1,改为0之后就不会出现这样的问题。对于配置文件里的所有上游服务器（未使用dnscurve或者代理）进行查询,也不会出现truncated.

进一步的试验发现只要向cap_DNSProxy查询非A或AAAA的记录就会导致这个问题，更改Payload size为512也不能解决

**Comment by chengr28** [comment]
你是开启了 `EDNS Client Subnet` 功能吗？这边检查过，的确是程序的处理逻辑有问题。如果 `EDNS Client Subnet` 在启用状态，会导致 A 和 AAAA 类型记录以外的请求被意外当成 `Truncated` 处理，而请求者（可能是 `dig` 之类的）收到带有 `Truncated` 标志的回复，正常来说会使用 TCP 协议重试，有些可能就此作罢……

**Comment by mewsf** [comment]
的确 我设置了EDNS Client Subnet

**Comment by chengr28** [comment]
刚才的更新应该已经解决这个问题了，有空可以试试，感谢反馈。
