### ISSUE TITLE
请教DNS投毒启用CDN的网站(2层CNAME记录+1层A记录)

### ISSUE THREAD

**Issue by kang000feng** [chengr28/Pcap_DNSProxy#34]
已被DNS投毒的国外A站(随机抛向国外), 因为A站用了CDN, 这个隐藏较深,  A  CNAME记录到 B, B   CNAME记录到 C,  最后C  A记录到 IPX.X.X.X, 查不到A站的真实IP, 无法做本地HOST, HOST到C的IP无法打开(IP是在线的,估计是CDN商家做的设置不允许这样HOST), 请教@chengr28 和各位有什么方法? 谢谢

**Comment by chengr28** [comment]
是这样……DNS 服务器在进行递归解析的时候，实际上是先查 A 的记录拿到 CNAME（也就是 B 域名）再查 B 的记录拿到 CNAME（也就是 C 的记录）再查 C 的记录拿到地址后将整个过程回复给客户，所以事实上把 A 的域名 Hosts 去用 C 域名解析出来的地址是完全正确的……
而且最终请求的时候 HTTP 服务器也只有 A 域名，不会有 B 啊 C 之类的，不能用可能是解析 C 域名时或者 CDN 那边的问题

**Comment by kang000feng** [comment]
谢谢, 我测试了C解析得到的几个IP地址,80端口,http服务都是正常运行的,
