### ISSUE TITLE
Pcap_DNSProxy 0.4.9.7编译错误。请指救一下。谢谢

### ISSUE THREAD

**Issue by wctliu** [chengr28/Pcap_DNSProxy#341]
ubuntu 18.04 
cmake-3.11.1 
libsodium-1.0.16  
openssl-1.1.1-pre6 
libevent-2.1.8-stable 
libpcap-1.8.1

[ 63%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Proxy.cpp.o
[ 68%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadCommand.cpp.o
[ 72%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadHosts.cpp.o
[ 77%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadIPFilter.cpp.o
[ 81%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o
[ 86%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Request.cpp.o
[ 90%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Service.cpp.o
[ 95%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/TransportSecurity.cpp.o
[100%] Linking CXX executable Pcap_DNSProxy
/usr/local/lib/libcrypto.a(dso_dlfcn.o)：在函数‘dlfcn_globallookup’中：
dso_dlfcn.c:(.text+0x11): 警告： Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/x86_64-linux-gnu-ld: 找不到 -lz
collect2: error: ld returned 1 exit status
CMakeFiles/Pcap_DNSProxy.dir/build.make:385: recipe for target 'Pcap_DNSProxy' failed
make[2]: *** [Pcap_DNSProxy] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
mv: 无法获取'Object/Pcap_DNSProxy' 的文件状态(stat): 没有那个文件或目录
mv: 无法获取'DependencyTemp' 的文件状态(stat): 没有那个文件或目录
mkdir: 无法创建目录"Release/Tools": 文件已存在

**Comment by chengr28** [comment]
`/usr/bin/x86_64-linux-gnu-ld: 找不到 -lz`
要装一下 zlib

**Comment by wctliu** [comment]
谢谢、它是要求安装zlib1g-dev。

sudo apt-get install zlib1g-dev
现在已经成功编译了。。就是警告有点多。应该不会影响正常使用吧。

[ 68%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadCommand.cpp.o
[ 72%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadHosts.cpp.o
[ 77%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadIPFilter.cpp.o
[ 81%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o
[ 86%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Request.cpp.o
[ 90%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Service.cpp.o
[ 95%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/TransportSecurity.cpp.o
[100%] Linking CXX executable Pcap_DNSProxy
/usr/local/lib/libcrypto.a(dso_dlfcn.o)：在函数‘dlfcn_globallookup’中：
dso_dlfcn.c:(.text+0x11): 警告： Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/libevent.a(evutil.o)：在函数‘test_for_getaddrinfo_hacks’中：
/home/nextcloud/libevent-2.1.8-stable/evutil.c:1267: 警告： Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpcap.a(nametoaddr.o)：在函数‘pcap_nametoaddr’中：
(.text+0x5): 警告： Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpcap.a(nametoaddr.o)：在函数‘pcap_nametonetaddr’中：
(.text+0xc5): 警告： Using 'getnetbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/libevent.a(evutil.o)：在函数‘evutil_unparse_protoname’中：
/home/nextcloud/libevent-2.1.8-stable/evutil.c:911: 警告： Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpcap.a(nametoaddr.o)：在函数‘pcap_nametoproto’中：
(.text+0x305): 警告： Using 'getprotobyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/libevent.a(evutil.o)：在函数‘evutil_parse_servname’中：
/home/nextcloud/libevent-2.1.8-stable/evutil.c:883: 警告： Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
[100%] Built target Pcap_DNSProxy

**Comment by chengr28** [comment]
一般来说不会，这些警告意思是，你要求使用静态链接（把所有代码编译到同一个可执行文件里），但是提到的几个函数是 glibc 里用动态链接调用的，一旦你把这个编译出来的可执行文件拿到其它 glibc 版本不匹配的地方用，有可能会导致程序崩溃。
