### ISSUE TITLE
Raspbian stretch 无法完成编译 Pcap_DNSProxy 0.4.9.7

### ISSUE THREAD

**Issue by fems** [chengr28/Pcap_DNSProxy#342]
Raspbian GNU/Linux 9.4 (stretch)
build-essential 12.3
cmake 3.7.2-1
libpcap-dev 1.8.1-3
libsodium-dev 1.0.11-2
libssl-dev 1.1.0f-3+deb9u2

> 0.4.9.5正常编译
pi@raspberrypi ~/Pcap_DNSProxy-0.4.9.5/Source/Auxiliary/Scripts $ sudo ./CMake_Build.sh
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/arm-linux-gnueabihf/libssl.so;/usr/lib/arm-linux-gnueabihf/libcrypto.so (found version "1.1.0f")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Pcap_DNSProxy-0.4.9.5/Source/Object
Scanning dependencies of target Pcap_DNSProxy
[  9%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
[  9%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o
[ 18%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o
[ 18%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurve.cpp.o
[ 22%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurveRequest.cpp.o
[ 27%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Initialization.cpp.o
[ 31%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Main.cpp.o
[ 36%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Monitor.cpp.o
[ 40%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Network.cpp.o
[ 45%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PacketData.cpp.o
[ 50%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PrintLog.cpp.o
[ 54%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Process.cpp.o
[ 59%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Protocol.cpp.o
[ 63%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Proxy.cpp.o
[ 68%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadCommand.cpp.o
[ 72%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadHosts.cpp.o
[ 77%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadIPFilter.cpp.o
[ 81%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o
[ 86%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Request.cpp.o
[ 90%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Service.cpp.o
[ 95%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/TransportSecurity.cpp.o
[100%] Linking CXX executable Pcap_DNSProxy
[100%] Built target Pcap_DNSProxy
pi@raspberrypi ~/Pcap_DNSProxy-0.4.9.5/Source/Auxiliary/Scripts $

> 0.4.9.7无法完成编译
pi@raspberrypi ~/Pcap_DNSProxy-0.4.9.7/Source/Auxiliary/Scripts $ sudo ./CMake_Build.sh
mv: cannot stat 'Dependency': No such file or directory
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/arm-linux-gnueabihf/libssl.so;/usr/lib/arm-linux-gnueabihf/libcrypto.so (found version "1.1.0f")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Object
Scanning dependencies of target Pcap_DNSProxy
[ 13%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o
[ 13%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurveControl.cpp.o
[ 13%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o
[ 18%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
In file included from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Structure.h:23:0,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Definition.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Type.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Template.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Include.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Capture.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Capture.cpp:20:
/home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Platform.h:507:27: fatal error: event2/event.h: No such file or directory
  #include <event2/event.h>
                           ^
compilation terminated.
CMakeFiles/Pcap_DNSProxy.dir/build.make:86: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o' failed
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Structure.h:23:0,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Definition.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Type.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Template.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Include.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Base.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Base.cpp:20:
/home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Platform.h:507:27: fatal error: event2/event.h: No such file or directory
  #include <event2/event.h>
                           ^
compilation terminated.
In file included from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Structure.h:23:0,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Definition.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Type.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Template.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Include.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/DNSCurveControl.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/DNSCurveControl.cpp:20:
/home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Platform.h:507:27: fatal error: event2/event.h: No such file or directory
  #include <event2/event.h>
                           ^
compilation terminated.
In file included from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Structure.h:23:0,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Definition.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Type.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Template.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Include.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Configuration.h:23,
                 from /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Configuration.cpp:20:
/home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/Platform.h:507:27: fatal error: event2/event.h: No such file or directory
  #include <event2/event.h>
                           ^
compilation terminated.
CMakeFiles/Pcap_DNSProxy.dir/build.make:62: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o' failed
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o] Error 1
CMakeFiles/Pcap_DNSProxy.dir/build.make:134: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/DNSCurveControl.cpp.o' failed
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/DNSCurveControl.cpp.o] Error 1
CMakeFiles/Pcap_DNSProxy.dir/build.make:110: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o' failed
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
mv: cannot stat 'Object/Pcap_DNSProxy': No such file or directory
mv: cannot stat 'DependencyTemp': No such file or directory
pi@raspberrypi ~/Pcap_DNSProxy-0.4.9.7/Source/Auxiliary/Scripts $

**Comment by chengr28** [comment]
请先把 libevent 装上再编译。

**Comment by fems** [comment]
sudo apt-get install libevent-dev
装上后，尝试还是出错，我先尝试自己排除下问题

[ 86%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Request.cpp.o
/home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/ReadParameter.cpp: In function ‘bool ReadParameterData_Proxy(const string&, size_t, bool, size_t, CONFIGURATION_TABLE*, bool&)’:
/home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/ReadParameter.cpp:3851:6: error: ‘sodium_base64_VARIANT_ORIGINAL’ was not declared in this scope
      sodium_base64_VARIANT_ORIGINAL) == nullptr)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/Pcap_DNSProxy-0.4.9.7/Source/Pcap_DNSProxy/ReadParameter.cpp:3851:36: error: ‘sodium_bin2base64’ was not declared in this scope
      sodium_base64_VARIANT_ORIGINAL) == nullptr)
                                    ^
CMakeFiles/Pcap_DNSProxy.dir/build.make:470: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o' failed
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
mv: cannot stat 'Object/Pcap_DNSProxy': No such file or directory
mv: cannot stat 'DependencyTemp': No such file or directory

**Comment by chengr28** [comment]
第二次编译出错是因为 libsodium 的版本太低了，貌似包管理器里的 dev 版本都比较低，建议去官网下一个新的装上，官网的包全部都有带。

**Comment by fems** [comment]
升级到libsodium-1.0.16，后已经可以正常编译0.4.9.7，虽然还有些文件夹错误的提示，但是能用了

pi@raspberrypi ~/Pcap_DNSProxy-0.4.9.7/Source/Auxiliary/Scripts $ sudo ./CMake_Build.sh
mv: cannot stat 'Dependency': No such file or directory
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/arm-linux-gnueabihf/libssl.so;/usr/lib/arm-linux-gnueabihf/libcrypto.so (found version "1.1.0f")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Pcap_DNSProxy-0.4.9.7/Source/Object
Scanning dependencies of target Pcap_DNSProxy
[  9%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o
[  9%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
[ 18%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o
[ 18%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurveControl.cpp.o
[ 22%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurveRequest.cpp.o
[ 27%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Initialization.cpp.o
[ 31%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Main.cpp.o
[ 36%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Monitor.cpp.o
[ 40%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Network.cpp.o
[ 45%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PacketData.cpp.o
[ 50%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PrintLog.cpp.o
[ 54%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Process.cpp.o
[ 59%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Protocol.cpp.o
[ 63%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Proxy.cpp.o
[ 68%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadCommand.cpp.o
[ 72%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadHosts.cpp.o
[ 77%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadIPFilter.cpp.o
[ 86%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Request.cpp.o
[ 86%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o
[ 90%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Service.cpp.o
[ 95%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/TransportSecurity.cpp.o
[100%] Linking CXX executable Pcap_DNSProxy
[100%] Built target Pcap_DNSProxy
mv: cannot stat 'DependencyTemp': No such file or directory
pi@raspberrypi ~/Pcap_DNSProxy-0.4.9.7/Source/Auxiliary/Scripts $

**Comment by chengr28** [comment]
mv: cannot stat 'Dependency': No such file or directory
    mv: cannot stat 'DependencyTemp': No such file or directory

这两个错误是正常可忽略的，自带的 Dependency 文件夹在 Linux 平台不需要使用，但是 CMake 不太智能，源代码里如果含有会干扰依赖的搜索过程，所以脚本里暂时改了一下名字。执行失败看起来是因为没有找到这个文件夹，找不到才是最好的。

**Comment by chengr28** [comment]
昨天说那两个 `mv` 错误的问题，看了一下发现是新版本已经移除  Dependency 目录，但是脚本里没有导致的，下次更新会修改一下脚本，应该就不会有问题了，旧的脚本报错也不影响功能的。
