### ISSUE TITLE
请教下我想在境内和境外搭建DNS,境内负责国内解析,国外DNS负责其他解析,不知道可否实现?

### ISSUE THREAD

**Issue by tudi1909** [chengr28/Pcap_DNSProxy#346]
﻿### Version/使用的版本/使用的版本

### Running Environment/运行环境/運行環境
Debian

### Expectation/期望情况/期望情況
请教下我想在境内和境外搭建DNS,境内负责国内解析,国外DNS负责其他解析,不知道可否实现?
如果可以 境外的需要怎样配置呢?

### Actual/实际情况/實際情況
搭建完成后,在境内DNS上
IPv4 Main DNS Address = 境外DNS:53
IPv4 Alternate DNS Address = 境外DNS:53

似乎解析不正常

感谢!

**Comment by edidada** [comment]
服务进程已经开启 
dig @127.0.0.1 www.google.com

; <<>> DiG 9.9.5-9+deb8u15-Debian <<>> @127.0.0.1 www.google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by tudi1909** [comment]
换了5353端口 只能直接解析,如果设置在境内DNS配置中,就不能解析国外地址了

**Comment by chengr28** [comment]
不明白想实现什么效果。如果按照这种境内搭建 DNS 服务器负责境内解析，境外又搭建一台 DNS 服务器负责境外解析的情况，那么实际上做境内和境外分流的位置是在本地，境内 DNS 服务器随便搭一个可以响应的软件，境外 DNS 服务器把端口开在非标准端口上，然后本地的程序再把境内境外的服务器地址和端口填上，就能实现这种效果了。

**Comment by tudi1909** [comment]
已成功,感谢几位帮助! 多谢@chengr28 大佬
