### ISSUE TITLE
Win10 1803 专业版 ，开机就蓝屏

### ISSUE THREAD

**Issue by 5points** [chengr28/Pcap_DNSProxy#348]
﻿### Version/使用的版本/使用的版本

0.4.9.7 or 0.4.5

### Running Environment/运行环境/運行環境
Win10 1803 专业版
设备：Surface Pro4

### Expectation/期望情况/期望情況

希望不要总是出现蓝屏

### Actual/实际情况/實際情況

之前发现这个原因是，因为开机蓝屏，所以就恢复了系统。然后再安装Pcap_Dns之后重启，问题又出现了。

不过这开机蓝屏也是要看脸的，现在遇到蓝屏的解决办法就是，我会再安全模式里，把“Pcap_DNSProxy.exe”复制到别的地方，然后正常重启之后再把文件复制回去使用。

但，这问题对我依旧很困扰。。。

**Comment by chenjiajia9411** [comment]
如果你用的是WinPcap的话，试试用新的NDIS 6 API写的[Npcap](https://nmap.org/npcap/)？我这里也是SP4，从来没有因为这个蓝屏过。

**Comment by 5points** [comment]
@chengr28 啊，谢谢，我也推断是驱动级的问题，因为再我另一部win10笔记本上我就没有这个问题出现，后来我安装了Win10Pcap之后，目前就没有蓝屏的问题出现，还在观察中

**Comment by 5points** [comment]
@chenjiajia9411 谢谢哦，如果出现下载/安装windows更新的情况，请问你会蓝屏吗？还有再问一下，当你用winpcap的时候，有蓝屏过吗

**Comment by chenjiajia9411** [comment]
@5points 没有蓝屏过，只有某个早期版本的Npcap让我崩了一次，后来升级到现在就没有过了。
另外我是从来没用过WinPcap的，一上来就用Npcap了……一开始Win10Pcap我也考虑的，但是看它好久都没更新……

**Comment by chengr28** [comment]
看起来这需要跟上游的项目反馈。

**Comment by SeaHOH** [comment]
WinPcap 开发已经停止了，Npcap 有资金支持，感觉挺靠谱。
