### ISSUE TITLE
Local Protocol = IPv4 + UDP 改为 Local Protocol = Type 出现10038错误

### ISSUE THREAD

**Issue by yyy8888** [chengr28/Pcap_DNSProxy#350]
﻿### Version/使用的版本/使用的版本
windows7
Pcap_DNSProxy 0.4.9.8

尝试几次结果相同
[2018-06-05 09:15:18] -> [Notice] Pcap_DNSProxy started.
[2018-06-05 09:18:27] -> [Network Error] TCP socket connecting error: An operation was attempted on something that is not a socket[10038].
[2018-06-05 09:18:27] -> [Network Error] UDP socket connecting error: An operation was attempted on something that is not a socket[10038].

### Running Environment/运行环境/運行環境
[DNS]
Outgoing Protocol = IPv4 + UDP
Direct Request = 0
Cache Type = Timer + Queue
Cache Parameter = 4096
Cache Single IPv4 Address Prefix = 0
Cache Single IPv6 Address Prefix = 0
Default TTL = 900

[Local DNS]
# Local Protocol = IPv4 + UDP
Local Protocol = Type
Local Hosts = 1
Local Routing = 1
Local Force Request = 1

[Addresses]
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 
IPv4 Main DNS Address = 8.8.4.4:53
IPv4 Alternate DNS Address = 156.154.70.1:53|8.8.8.8:53|208.67.220.220:443|208.67.222.222:5353
IPv4 Local Main DNS Address = 119.29.29.29:53
IPv4 Local Alternate DNS Address = 114.114.114.114:53

**Comment by chengr28** [comment]
可能是 ReadMe 说明文档里解释得不是很清楚……这些参数的格式是这样：
```
= [网络层协议] + [传输层协议] + [Type]
```
也就是说 `Type` 是作为一个参数加进去的：
```
= IPv4 + IPv6 + UDP + Type
```
新版本里如果网络层协议不写默认是 `IPv6 + IPv4` 而传输层写默认是 `UDP` 或者 `TCP`（看当个 Protocol 参数的默认值）所以你这样只写 `Type` 就是相当于 `= IPv4 + IPv6 + UDP + Type`。

至于那个 10038 错误，应该是因为如上原因，开启了 IPv6 协议但是没有 IPv6 的网关（就是说 IPv6 没有出口）所以把 IPv6 关掉就不会出现了。

**Comment by yyy8888** [comment]
谢谢大家的回复，现在明白了。
