### ISSUE TITLE
 [Pcap Error] PacketGetAdapterNames: 传递给系统调用的数据区域太小。 (122)

### ISSUE THREAD

**Issue by wang93wei** [chengr28/Pcap_DNSProxy#351]
﻿### Version/使用的版本/使用的版本
0.4.9.8

### Running Environment/运行环境/運行環境
Win10 1803 
USB WIFI联网  无网线
把接口跃点数改为了 1
只将[Addresses] 下面两个参数改了一下
> IPv4 Local Main DNS Address = 114.114.114.114:53
> IPv4 Local Alternate DNS Address = 112.100.100.100:53

### Expectation/期望情况/期望情況
无错误报告

### Actual/实际情况/實際情況
不经常出现
 [Pcap Error] PacketGetAdapterNames: 传递给系统调用的数据区域太小。 (122)

经常出现
[Network Error] UDP connection initialization error: A socket operation was attempted to an unreachable network[10051].
出现此错误后，部分软件无法正常联网，但网页打开正常，例如：Microsoft Store

**Comment by chengr28** [comment]
关于这两个问题：
* `PacketGetAdapterNames` 这个应该是 WinPcap 内部的处理有问题，可能和那个 USB 网卡有关，但是因为这个 API 不是程序调用而是连锁调用的，所以没法解决。建议可以试试其它与 WinPcap 兼容的抓包工具，例如 Npcap 之类的试试。
* 10051 是网络不可达错误：
```
Network is unreachable.
A socket operation was attempted to an unreachable network. This usually means the local software knows no route to reach the remote host.
```
这个是系统 API 报告的错误，简单来说就是找不到目的地址的路由，与网络情况有关，这边也无法解决。至于你说调整过接口跃点数，也无法确定是否与此有关。如果确实不想看到类似的错误，可以调整配置文件将错误报告等级调低或者关闭。

**Comment by wang93wei** [comment]
昨天已经把WinPcap换成了Npcap，效果有待测试。
如果按照这样说法的话，应该是因为USB wifi的驱动还没加载上（在电脑启动时WIFI标志会出现反复 连接，断开，10秒以内能恢复正常），Pcap_DNSProxy已经开始尝试联网了。

我在网线直连的机器上做过测试，PacketGetAdapterNames  不会出现。10051 和10038 偶尔出现，应该和接口越点数没什么关系。

那我调整一下配置文件吧。

**Comment by chengr28** [comment]
这个问题其实有点迷……如果按照字面意思是缓冲区不够，实际上缓冲区已经相当大（默认是 4KB 根据那个配置文件里的参数决定）不太像是。查了一下还有说是因为用者装的版本和开发使用的库版本不一致造成的，然而 WinPcap 这个好多年都没更新过了……

这边还专门换成 Npcap 好像也没什么问题，估计还是跟系统里的某个网络适配器有关，可以试试用排除法。
