### ISSUE TITLE
开启域名大小写混淆，黑名单和分流失效

### ISSUE THREAD

**Issue by huaji0353** [chengr28/Pcap_DNSProxy#357]
﻿### Version/使用的版本/使用的版本
0.4.9.7

### Running Environment/运行环境/運行環境
win8.1

### Expectation/期望情况/期望情況

即使开启混淆也能过滤与分流

### Actual/实际情况/實際情況

ws抓包检查没有分流
dig查询黑名单能返回结果
关闭Domain Case Conversion后就能过滤

### 支持请求DNSSEC？
DNSCurve只有很少服务器支持，ipv4都被墙。

以下是部分配置
> [Base]
> Version = 0.45
> File Refresh Time = 15
> Large Buffer Size = 4096
> Additional Path = 
> Hosts File Name = Hosts.ini|WhiteList.txt
> IPFilter File Name = IPFilter.ini|Routing.txt
> 
> [Log]
> Print Log Level = 3
> Log Maximum Size = 8MB
> 
> [Listen]
> Process Unique = 1
> Pcap Capture = 1
> Pcap Devices Blacklist = AnyConnect|Host|Hyper|ISATAP|IKE|L2TP|Only|Oracle|PPTP|Pseudo|Teredo|Tunnel|Virtual|VMNet|VMware|VPN|any|gif|lo|stf|tunl|utun
> Pcap Reading Timeout = 250
> Listen Protocol = IPv4 + TCP + UDP
> Listen Port = 53
> Operation Mode = Private
> IPFilter Type = Deny
> IPFilter Level < 0
> Accept Type = Permit:A
> 
> [DNS]
> Outgoing Protocol = IPv4 + TCP
> Direct Request = 0
> Cache Type = Timer
> Cache Parameter = 86400
> Default TTL = 86400
> 
> [Local DNS]
> Local Protocol = IPv4 + UDP
> Local Hosts = 1
> Local Routing = 0
> Local Force Request = 0
> 
> [Addresses]
> IPv4 Listen Address = 
> IPv4 EDNS Client Subnet Address = 
> IPv4 Main DNS Address = 8.8.4.4:53
> IPv4 Alternate DNS Address = 8.8.8.8:53|208.67.220.220:443|208.67.222.222:5353
> IPv4 Local Main DNS Address = 114.114.115.115:53
> IPv4 Local Alternate DNS Address = 223.6.6.6:53
> 
> [Values]
> Thread Pool Base Number = 0
> Thread Pool Maximum Number = 128
> Thread Pool Reset Time = 120
> Queue Limits Reset Time = 0
> EDNS Payload Size = 1220
> IPv4 Packet TTL = 32 - 255
> IPv4 Main DNS TTL = 0
> IPv4 Alternate DNS TTL = 0
> Hop Limits Fluctuation = 2
> Reliable Once Socket Timeout = 3000
> Reliable Serial Socket Timeout = 1500
> Unreliable Once Socket Timeout = 2000
> Unreliable Serial Socket Timeout = 1000
> TCP Fast Open = 0
> Receive Waiting = 0
> ICMP Test = 900
> Domain Test = 900
> Alternate Times = 10
> Alternate Time Range = 60
> Alternate Reset Time = 300
> Multiple Request Times = 0
> 
> [Switches]
> Domain Case Conversion = 0
> Compression Pointer Mutation = 0
> EDNS Label = 0
> EDNS Client Subnet Relay = 0
> DNSSEC Request = 0
> DNSSEC Force Record = 0
> Alternate Multiple Request = 0
> IPv4 Do Not Fragment = 0
> TCP Data Filter = 1
> DNS Data Filter = 1
> Blacklist Filter = 1
> Resource Record Set TTL Filter = 1
> 
> [Data]
> ICMP ID = 
> ICMP Sequence = 
> ICMP PaddingData = 
> Domain Test Protocol = TCP + UDP
> Domain Test ID = 
> Domain Test Data = 
> Local Machine Server Name =

**Comment by chengr28** [comment]
关于这两个问题：
* 这边按照提供的配置文件，把 `Domain Case Conversion` 开启后，过滤和分流并没有发现有问题？你说不能分流，是什么模式下抓包抓到没有分流，不能过滤，是查询什么黑名单域名有错误的解析结果？
* 不清楚你说『支持请求DNSSEC』这个指的是什么？如果指的是『在请求里带上支持 DNSSEC』的标志，那么 `DNSSEC Request` 参数就可以，而 `DNSSEC Force Record` 还能提供对 DNSSEC 的强制支持。但如果你指的是『完整的 DNSSEC 信任链认证』这个只能使用递归 DNS 服务器进行，程序本质上只是个转发 DNS 服务器，并没有递归请求的功能。

**Comment by huaji0353** [comment]
好的，看了下ws设置是混杂mode，然而 win下嘛请无视

重启服务并flush后，开启混淆时：

- 使用dig，nslookup查询bilibili.com时，抓包显示国外和国内dns都请求过。
- 在`hosts.ini`输入`BANNED .*\.2345\.com`，dig，nslookup查询返回结果。

重启服务并flush后，关闭混淆时：
- 使用dig，nslookup查询bilibili.com时，只看到国内dns的请求。
- `BANNED .*\.2345\.com`，dig，nslookup查询超时。

`DNSSEC Request`开启经过抓包后，请求的域名经过加密后不管任何dns服务器，返回的结果都是无此域名，`DNSSEC Force` 开启就没法上网了 :(

**Comment by chengr28** [comment]
怎么说呢……其实这个和 https://github.com/chengr28/Pcap_DNSProxy/issues/366 的是同一个问题，就是那个 `BANNED` 关键词的问题，的确是程序处理流程有问题。昨天更新的版本应该已经修复这个问题了，有空可以更新测试一下看看。

**Comment by chengr28** [comment]
`DNSSEC Request` 不知道是不是因为上面提到的问题才会这样，这边测试过是正常工作的，其实就是带了个通知给远程 DNS 服务器说支持 DNSSEC 了。至于开启 Force 之后不能上网是正常的，这个参数虽然不是完整验证 DNSSEC 但是如果一个域名没有 DNSSEC 相关的记录会被直接拒绝，而现在只有极少数域名有 DNSSEC……那当然就不能用了。

**Comment by huaji0353** [comment]
请教一个问题，最近本地外网速度实在太慢，于是又抓了一次包
![img](https://i.loli.net/2018/07/21/5b531fd5e0dcf.png)

这些请求不仅毫无规律，而且dns服务器返回的结果都是no such name。消除这个是需要关选项什么的吗？

**Comment by chengr28** [comment]
这些请求是 `Domain Test` 参数控制的，不过需要注意的是如果关闭这些选项，抓包模块的过滤效果可能会大幅下降。

**Comment by chengr28** [comment]
默认是只会每隔一段时间测试几次，但是看起来程序是一直都在测试，这个是不正常的情况。建议是先更新到最新版本，然后检查填入的远程 DNS 服务器是否正常。

**Comment by huaji0353** [comment]
关了test选项的确没有了，刚试了下新版，开了大小写混淆能过滤分流了。
不过hosts可能有点问题，根域名正则无法匹配
比方在 hosts.ini 写入x.x.x.x github\.com
然后输入dig github.com 返回结果并非 x.x.x.x
不过想到个办法 使用etc/hosts+hosts.ini来匹配

**Comment by chengr28** [comment]
这边测试似乎没有问题……规则是写在 `[Hosts]` 里的吗，或者写入规则的前面是否有被其它规则先匹配了，或者修改后没有等待一段时间或者重启服务使规则生效？

**Comment by huaji0353** [comment]
是写在`[Hosts]`里面的，优先匹配考虑过，地址是放在最后面的。尝试过重启服务

**Comment by chengr28** [comment]
那还真是奇怪，不知道是不是和之前一样是和其它选项或者参数配合的问题……
或者这样吧，可以提供以下 3 个完整的配置文件吗？直接邮箱也行。

**Comment by huaji0353** [comment]
[config.zip](https://github.com/chengr28/Pcap_DNSProxy/files/2222077/config.zip)

**Comment by chengr28** [comment]
然而使用提供的配置文件测试并没有问题……可以正常工作。

**Comment by huaji0353** [comment]
行吧，又不是不能用，只不过 每天开电脑第一件事就是换dns和github hosts，万恶的长城，，，

**Comment by chengr28** [comment]
这不应该啊……正常流程在 `[Hosts]` 下面写了 `x.x.x.x github\.com` 保存然后重启服务，再 `dig @127.0.0.1 github.com` 这边换了好几个 IPv4 的地址都没问题，可能还是平台限定的问题？有时间这边用其它平台试试……
