### ISSUE TITLE
搭建好了，可是遇到的问题很奇怪

### ISSUE THREAD

**Issue by liankainan** [chengr28/Pcap_DNSProxy#359]
![1.png](https://i.loli.net/2018/07/02/5b3a472f2f36e.png)
![2.png](https://i.loli.net/2018/07/02/5b3a472f2ee77.png)
在尝试dig "www.google.com” 返回的结果是错误的ip，随后dig "google.com"返回的结果是正确的ip，有点迷

**Comment by liankainan** [comment]
dig 推特 带www和不带结果也是不一样

**Comment by chengr28** [comment]
好吧其实一开始那个 IP 地址是假的，可能是最近投毒污染的力度有所加大……可以试开启 `EDNS Label` 参数，应该有所帮助。
