### ISSUE TITLE
linuxmint 17.1 Cmake3.2.3安装不了

### ISSUE THREAD

**Issue by fzitou** [chengr28/Pcap_DNSProxy#36]
~/下载/cmake-3.2.3 $ sudo ./bootstrap
---------------------------------------------
CMake 3.2.3, Copyright 2000-2015 Kitware, Inc.
Found GNU toolchain
C compiler on this system is: gcc 
C++ compiler on this system is: g++ 
Makefile processor on this system is: make
g++ is GNU compiler
g++ has setenv
g++ has unsetenv
g++ does not have environ in stdlib.h
g++ has STL in std:: namespace
g++ has ANSI streams
g++ has streams in std:: namespace
g++ does not have sstream
g++ does not have strstream.h
g++ does not have strstrea.h
g++ does not have operator!=(string, char*)
g++ has stl iterator_traits
g++ has standard template allocator
g++ has allocator<>::rebind<>
g++ does not have non-standard allocator<>::max_size argument
g++ has stl containers supporting allocator objects
g++ has stl wstring
g++ has header cstddef
g++ requires template friends to use <>
g++ supports member templates
g++ has standard template specialization syntax
g++ has argument dependent lookup
g++ has struct stat with st_mtim member
g++ has ios::binary openmode
---------------------------------------------
g++  -I/home/fzitou/下载/cmake-3.2.3/Bootstrap.cmk -I/home/fzitou/下载/cmake-3.2.3/Source   -I/home/fzitou/下载/cmake-3.2.3/Bootstrap.cmk -DKWSYS_NAMESPACE=cmsys -DKWSYS_CXX_HAS_SETENV=1 -DKWSYS_CXX_HAS_UNSETENV=1 -DKWSYS_CXX_HAS_ENVIRON_IN_STDLIB_H=0 -DKWSYS_CXX_HAS_UTIMENSAT=0 -DKWSYS_CXX_HAS_UTIMES=0 -c /home/fzitou/下载/cmake-3.2.3/Source/kwsys/SystemTools.cxx -o SystemTools.o
In file included from /usr/local/include/c++/5.1.0/backward/strstream:51:0,
                 from /home/fzitou/下载/cmake-3.2.3/Bootstrap.cmk/cmsys/ios/sstream:38,
                 from /home/fzitou/下载/cmake-3.2.3/Source/kwsys/SystemTools.cxx:36:
/usr/local/include/c++/5.1.0/backward/backward_warning.h:32:2: 警告：#warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
In file included from /home/fzitou/下载/cmake-3.2.3/Source/kwsys/SystemTools.cxx:36:0:
/home/fzitou/下载/cmake-3.2.3/Bootstrap.cmk/cmsys/ios/sstream: 在成员函数‘void cmsys_ios::istringstream::clear(int)’中:
/home/fzitou/下载/cmake-3.2.3/Bootstrap.cmk/cmsys/ios/sstream:176:34: 错误：从类型‘int’到类型‘std::ios_base::iostate {aka std::_Ios_Iostate}’的转换无效 [-fpermissive]
     this->IStrStream::clear(flags);
                                  ^
In file included from /usr/local/include/c++/5.1.0/bits/basic_ios.h:516:0,
                 from /usr/local/include/c++/5.1.0/ios:44,
                 from /usr/local/include/c++/5.1.0/istream:38,
                 from /usr/local/include/c++/5.1.0/fstream:38,
                 from /home/fzitou/下载/cmake-3.2.3/Bootstrap.cmk/cmsys/ios/fstream:24,
                 from /home/fzitou/下载/cmake-3.2.3/Bootstrap.cmk/cmsys/FStream.hxx:15,
                 from /home/fzitou/下载/cmake-3.2.3/Source/kwsys/SystemTools.cxx:31:
/usr/local/include/c++/5.1.0/bits/basic_ios.tcc:41:5: 附注：  初始化‘void std::basic_ios<_CharT, _Traits>::clear(std::ios_base::iostate) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::iostate = std::_Ios_Iostate]’的实参 1
     basic_ios<_CharT, _Traits>::clear(iostate __state)
     ^
make: *** [SystemTools.o] 错误 1
---------------------------------------------
Error when bootstrapping CMake:
Problem while running make
---------------------------------------------
Log of errors: /home/fzitou/下载/cmake-3.2.3/Bootstrap.cmk/cmake_bootstrap.log
---------------------------------------------

请问这是什么原因,如何解决呢?

**Comment by chengr28** [comment]
这个其实是 CMake 编译的问题……我也不太清楚是怎么回事，查了似乎都是说因为 GCC 那边的库太旧了导致的，最终的原因可能是 Linux Mint 本身附带的软件包都太旧了……

有个简单的处理方法，就是修改项目的最低 CMake 版本要求：在 Pcap_DNSProxy 和 KeyPairGenerator 目录下都有一个 **CMakeLists.txt** 文件，里面的 **cmake_minimum_required(VERSION xxx)** 就是指定最低版本要求的参数，修改 xxx 为等于或低于安装的版本就行，注意不要删掉，CMake 要求一定要有这个参数
嘛项目本身也不是很复杂的结构，那个最低版本要求纯粹是我机器上的版本而已，低版本装应该也不会有大问题，当然没有实际测试过也不好说……你可以试试ww
