### ISSUE TITLE
境内解析服务器-主要的那个改成223.5.5.5以后无法解析了

### ISSUE THREAD

**Issue by wutongskype** [chengr28/Pcap_DNSProxy#361]
最新版，没改太多配置，就是照着网上的教程把默认工作模式改成了server,udp模式改成了tcp,然后就是想把默认的境内解析主要服务器地址114的那个改成223.5.5.5，可改完以后再用windows下面的nslookup测试无法返回解析的地址。

**Comment by wongsyrone** [comment]
请贴出修改之后的完整配置

**Comment by zanewayne78** [comment]
223.5.5.5估计是不支持tcp，既然你都知道没改多少，就不会逐一排查？而且国内dns没必要tcp

**Comment by chengr28** [comment]
有问题直接回复就行。
