### ISSUE TITLE
Debian9 编译时报错

### ISSUE THREAD

**Issue by kwl01skz** [chengr28/Pcap_DNSProxy#362]
### Version/使用的版本/使用的版本
Pcap_DNSProxy-master
### Running Environment/运行环境/運行環境
clang version 3.8.1-24 (tags/RELEASE_381/final)
LibEvent-2.0-5
libsodium 1.0.16
libcap2
libcap-dev
### Actual/实际情况/實際情況
报错
>    /bits/c++0x_warning.h:32:2: error: This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

如果我在CMakeFile.txt加上
`SET(CMAKE_CXX_FLAGS "-std=c++11")`
报错
>    no member named 'make_unique' in namespace 'std'

如果改成
`SET(CMAKE_CXX_FLAGS "-std=c++14")`

前面编译可以通过，但是到后面会报错：
 

> [ 86%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Request.cpp.o
> [ 90%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Service.cpp.o
> [ 95%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/TransportSecurity.cpp.o
> [100%] Linking CXX executable Pcap_DNSProxy
> CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o: file not recognized: 不可识别的文件格式
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> CMakeFiles/Pcap_DNSProxy.dir/build.make:616: recipe for target 'Pcap_DNSProxy' failed
> make[2]: *** [Pcap_DNSProxy] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
> make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> mv: 无法获取'Object/Pcap_DNSProxy' 的文件状态(stat): 没有那个文件或目录

卸载Clang和LLVM，使用gcc/g++编译成功

**Comment by kwl01skz** [comment]
也许是因为我在CMakeFile.txt里面增加了一行
SET(CMAKE_CXX_FLAGS "-std=c++14")

但如果不这样就会

> /bits/c++0x_warning.h:32:2: error: This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
或者
> no member named 'make_unique' in namespace 'std'

**Comment by chengr28** [comment]
新版本的 C++ 标准要求是 14 的，不能用 11 否则正常情况下都编译不了。

至于那个错误……是不是 Clang/LLVM 工具链有问题？据闻是和某个参数有关，可以试试编辑源代码目录下的 CMakeLists.txt 把 `add_definitions(-flto)` 和 `set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)` 删掉保存，然后清空所有中间文件再编译一次试试。
