### ISSUE TITLE
一个编译问题。想咨询一下解决方案

### ISSUE THREAD

**Issue by StarryVoid** [chengr28/Pcap_DNSProxy#364]
﻿### Version/使用的版本/使用的版本

git clone https://github.com/chengr28/Pcap_DNSProxy.git 
20180712
V0.4.9.8

### Running Environment/运行环境/運行環境

CentOS 7 + BBR
yum install epel-release
yum install -y git vim wget curl unzip net-tools
yum -y groupinstall "Development Tools"
yum install -y gcc gcc-c++ autoconf libmcrypt libmcrypt-devel libjpeg libjpeg-devel libpng libpng-devel libxml2 libxml2-devel curl curl-devel openssl openssl-devel freetype freetype-devel zlib zlib-devel glibc glibc-devel glib2 glib2-devel bzip2 bzip2-devel ncurses gdbm-devel db4-devel libXpm-devel libX11-devel gd-devel gmp-devel readline-devel libxslt-devel expat-devel xmlrpc-c xmlrpc-c-devel
yum install centos-release-scl
yum install devtoolset-7-gcc* clang cmake3 libpcap libpcap-devel libevent libevent-devel libsodium libsodium-devel openssl openssl-devel
scl enable devtoolset-7 bash 

内核
Package kernel-ml-4.17.6-1.el7.elrepo.x86_64 already installed and latest version
Package kernel-ml-devel-4.17.6-1.el7.elrepo.x86_64 already installed and latest version
Package kernel-ml-headers-4.17.6-1.el7.elrepo.x86_64 already installed and latest version
Package kernel-ml-tools-4.17.6-1.el7.elrepo.x86_64 already installed and latest version
Package kernel-ml-tools-libs-4.17.6-1.el7.elrepo.x86_64 already installed and latest version
Package kernel-ml-tools-libs-devel-4.17.6-1.el7.elrepo.x86_64 already installed and latest version

编译环境
Package devtoolset-7-gcc-c++-7.3.1-5.10.el7.x86_64 already installed and latest version
Package devtoolset-7-gcc-gdb-plugin-7.3.1-5.10.el7.x86_64 already installed and latest version
Package devtoolset-7-gcc-plugin-devel-7.3.1-5.10.el7.x86_64 already installed and latest version
Package devtoolset-7-gcc-gfortran-7.3.1-5.10.el7.x86_64 already installed and latest version
Package devtoolset-7-gcc-7.3.1-5.10.el7.x86_64 already installed and latest version
Package clang-3.4.2-8.el7.x86_64 already installed and latest version
Package cmake3-3.11.2-1.el7.x86_64 already installed and latest version
Package 14:libpcap-1.5.3-11.el7.x86_64 already installed and latest version
Package 14:libpcap-devel-1.5.3-11.el7.x86_64 already installed and latest version
Package libevent-2.0.21-4.el7.x86_64 already installed and latest version
Package libevent-devel-2.0.21-4.el7.x86_64 already installed and latest version
Package libsodium-1.0.16-1.el7.x86_64 already installed and latest version
Package libsodium-devel-1.0.16-1.el7.x86_64 already installed and latest version
Package 1:openssl-1.0.2k-12.el7.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.2k-12.el7.x86_64 already installed and latest version

### Expectation/期望情况/期望情況

编译通过

### Actual/实际情况/實際情況

[root@usa Scripts]# ./CMake_Build.sh
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/make/pcapdnsproxy/Source/Object
Scanning dependencies of target Pcap_DNSProxy
[  4%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
[  9%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o
[ 13%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o
[ 18%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurveControl.cpp.o
[ 22%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurveRequest.cpp.o
[ 27%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Initialization.cpp.o
[ 31%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Main.cpp.o
[ 36%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Monitor.cpp.o
[ 40%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Network.cpp.o
[ 45%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PacketData.cpp.o
[ 50%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PrintLog.cpp.o
[ 54%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Process.cpp.o
[ 59%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Protocol.cpp.o
[ 63%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Proxy.cpp.o
[ 68%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadCommand.cpp.o
[ 72%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadHosts.cpp.o
[ 77%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadIPFilter.cpp.o
[ 81%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o
/root/make/pcapdnsproxy/Source/Pcap_DNSProxy/ReadParameter.cpp: In function ‘bool ReadParameterData_Proxy(const string&, size_t, bool, size_t, CONFIGURATION_TABLE*, bool&)’:
/root/make/pcapdnsproxy/Source/Pcap_DNSProxy/ReadParameter.cpp:3876:6: error: ‘sodium_base64_VARIANT_ORIGINAL’ was not declared in this scope
      sodium_base64_VARIANT_ORIGINAL) == nullptr)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/make/pcapdnsproxy/Source/Pcap_DNSProxy/ReadParameter.cpp:3871:8: error: ‘sodium_bin2base64’ was not declared in this scope
    if (sodium_bin2base64(
        ^~~~~~~~~~~~~~~~~
/root/make/pcapdnsproxy/Source/Pcap_DNSProxy/ReadParameter.cpp:3871:8: note: suggested alternative: ‘sodium_bin2hex’
    if (sodium_bin2base64(
        ^~~~~~~~~~~~~~~~~
        sodium_bin2hex
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
make: *** [all] Error 2
mv: cannot stat ‘Object/Pcap_DNSProxy’: No such file or director

### 补充说明
重新搭建了一个什么都没有的CentOS虚拟机，相同命令，编译正常，运行正常。
网络中的VPS就不行。

**Comment by chengr28** [comment]
参见 https://github.com/chengr28/Pcap_DNSProxy/issues/327
