### ISSUE TITLE
无法启动服务，提示错误193

### ISSUE THREAD

**Issue by standritsu** [chengr28/Pcap_DNSProxy#365]
﻿### Version/使用的版本/使用的版本
Pcap_DNSProxy 0.4.9.8

### Running Environment/运行环境/運行環境
windows 10 17713.rs5

### Expectation/期望情况/期望情況
启动服务

### Actual/实际情况/實際情況

[SC] ControlService 失败 1062:

服务尚未启动。

错误: 没有找到进程 "Pcap_DNSProxy.exe"。
[SC] 由于发生错误 193， StartService 失败。

没有error日志

**Comment by chengr28** [comment]
可以试试直接双击 exe 运行？

**Comment by standritsu** [comment]
直接运行exe可以

**Comment by chengr28** [comment]
检查过，错误代码 193 是 `ERROR_BAD_EXE_FORMAT` 就是说识别不了 exe 的意思。然而双击却可以运行，那应该是有其它原因造成的问题，或者可以参考一下 https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc782541(v=ws.10)

一般来说：
* 修改过系统的一些不明的设置或者策略。
* 杀毒软件之类的阻止。
* 可能是批处理有问题，纯 exe 是 64 位的，但是系统是 32 位。
* exe 本身有问题，请核对一下 Hash 值或重新下载。

**Comment by standritsu** [comment]
https://github.com/chengr28/Pcap_DNSProxy/issues/368
我直接运行exe跟这个朋友的一样，不过我找到了解决方式，之前我把文件夹放在了D盘，现在移到C盘，问题解决

**Comment by chengr28** [comment]
这……好吧
