### ISSUE TITLE
添加BANNED:AAAA后只能使用境外DNS解析，无法走境内DNS解析？

### ISSUE THREAD

**Issue by gitlikang** [chengr28/Pcap_DNSProxy#366]
﻿### Version/使用的版本/使用的版本

PcapDNSProxy 0.4.9.8

### Running Environment/运行环境/運行環境

Windows 10 Professional edition x64
1709
16299.125
电信分配的Native IPv6，240e::开头的地址

### Expectation/期望情况/期望情況

在Hosts.ini文件中的[Hosts]使用BANNED:AAAA屏蔽记录后，希望能够走路由表Routing.txt，且匹配到CIDR地址段后使用境内DNS解析。

### Actual/实际情况/實際情況

没有使用BANNED:AAAA前，解析maps.google.cn会匹配到CIDR地址段，然后直接返回解析结果，走的是境内DNS解析。然而加了BANNED后就不同了，不管路由表有没有IPv4或IPv6的CIDR地址段都直接走的境外DNS解析。

Config.ini 不同之处，IPv4 Main DNS Address~一直到~IPv6 Alternate DNS Address

> [Base]
> Version = 0.45
> File Refresh Time = 15
> Large Buffer Size = 4096
> Additional Path = 
> Hosts File Name = Hosts.ini|Hosts.conf|Hosts|Hosts.txt|WhiteList.txt|White_List.txt
> IPFilter File Name = IPFilter.ini|IPFilter.conf|IPFilter.dat|Routing.txt|chnrouting.txt|chnroute.txt
> 
> [Log]
> Print Log Level = 3
> Log Maximum Size = 8MB
> 
> [Listen]
> Process Unique = 1
> Pcap Capture = 1
> Pcap Devices Blacklist = AnyConnect|Host|Hyper|ISATAP|IKE|L2TP|Only|Oracle|PPTP|Pseudo|Teredo|Tunnel|Virtual|VMNet|VMware|VPN|any|gif|lo|stf|tunl|utun
> Pcap Reading Timeout = 250
> Listen Protocol = IPv6 + IPv4 + TCP + UDP
> Listen Port = 53
> Operation Mode = Private
> IPFilter Type = Deny
> IPFilter Level < 0
> Accept Type = 
> 
> [DNS]
> Outgoing Protocol = IPv4 + UDP
> Direct Request = 0
> Cache Type = Timer + Queue
> Cache Parameter = 4096
> Cache Single IPv4 Address Prefix = 0
> Cache Single IPv6 Address Prefix = 0
> Default TTL = 900
> 
> [Local DNS]
> Local Protocol = IPv4 + UDP
> Local Hosts = 0
> Local Routing = 1
> Local Force Request = 0
> 
> [Addresses]
> IPv4 Listen Address = 
> IPv4 EDNS Client Subnet Address = 
> IPv4 Main DNS Address = 1.1.1.1:53
> IPv4 Alternate DNS Address = 1.0.0.1:53|208.67.220.220:443|208.67.222.222:5353
> IPv4 Local Main DNS Address = 119.29.29.29:53
> IPv4 Local Alternate DNS Address = 223.6.6.6:53
> IPv6 Listen Address = 
> IPv6 EDNS Client Subnet Address = 
> IPv6 Main DNS Address = [2606:4700:4700::1111]:53
> IPv6 Alternate DNS Address = [2606:4700:4700::1001]:53|[2620:0:CCD::2]:443|[2620:0:CCC::2]:5353
> IPv6 Local Main DNS Address = 
> IPv6 Local Alternate DNS Address = 
> ......

Hosts.ini

> [Source Hosts]
> 
> [Hosts]
> BANNED:AAAA .*\bgoogle\.cn
> ##203.208.50.79|203.208.50.95|203.208.50.88|203.208.50.87 .*\bgoogle\.cn
> 
> [Local Hosts]
> 
> [CNAME Hosts]
> 
> [Address Hosts]

Routing.txt

> Last update: 2018-07-13

**Comment by chengr28** [comment]
昨天更新的版本应该已经修复这个问题了，有时间可以测试一下看看，感谢反馈。
