### ISSUE TITLE
无法正常运行服务

### ISSUE THREAD

**Issue by sysconfon** [chengr28/Pcap_DNSProxy#368]
﻿### Version/使用的版本/使用的版本

0.4.9.9

### Running Environment/运行环境/運行環境

windows 10 1803 x64 企业版

### Actual/实际情况/實際情況

[System Error] Service start error: The service process could not connect to the service controller[1063].
[Notice] Program will continue to run in console mode.
[Notice] Please ignore these error messages if you want to run in console mode.

**Comment by sysconfon** [comment]
执行单文件。或者安装后执行，均报以上错误。

**Comment by chengr28** [comment]
> [注意] 程序将**继续**在控制台模式下运行。
> [注意] **如果要在控制台模式下运行，请忽略这些错误消息**。

**Comment by sysconfon** [comment]
错误信息在第一条。
[System Error] Service start error: The service process could not connect to the service controller[1063].

**Comment by sysconfon** [comment]
@chengr28 
还有个问题，能否在dns解析后返回阶段，能否以如下这样的方式进行展示呢

增加返回内容里面的如下内容段：
;; AUTHORITY SECTION:
;; ADDITIONAL SECTION:

; <<>> DiG 9.11.4 <<>> www.baidu.com @216.146.35.35
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45621
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 5, ADDITIONAL: 6

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1480
;; QUESTION SECTION:
;www.baidu.com.                 IN      A

;; ANSWER SECTION:
www.baidu.com.          649     IN      CNAME   www.a.shifen.com.
www.a.shifen.com.       300     IN      A       61.135.169.121
www.a.shifen.com.       300     IN      A       61.135.169.125

;; AUTHORITY SECTION:
a.shifen.com.           1200    IN      NS      ns5.a.shifen.com.
a.shifen.com.           1200    IN      NS      ns1.a.shifen.com.
a.shifen.com.           1200    IN      NS      ns2.a.shifen.com.
a.shifen.com.           1200    IN      NS      ns3.a.shifen.com.
a.shifen.com.           1200    IN      NS      ns4.a.shifen.com.

;; ADDITIONAL SECTION:
ns1.a.shifen.com.       600     IN      A       61.135.165.224
ns2.a.shifen.com.       600     IN      A       180.149.133.241
ns3.a.shifen.com.       600     IN      A       61.135.162.215
ns4.a.shifen.com.       600     IN      A       115.239.210.176
ns5.a.shifen.com.       600     IN      A       180.76.76.95

**Comment by chengr28** [comment]
这里的流程是这样的：
* 默认使用服务模式启动，如果遇到错误（1063 或者其它）就会输出到屏幕上
* 然后就会输出那两段提示，告诉你服务模式遇到错误
* 你可以不管这些错误，这样会继续使用控制台模式运行
* 继续运行

实际上功能没有区别。

**Comment by chengr28** [comment]
关于你说的第二个情况，首先需要明确一点是程序只负责转发远程 DNS 服务器的数据包，实际上数据包里附带了什么数据，除非是有规则需要修改外是不会干预的。

不清楚你说的如下展示具体是什么意思，如果你说的是 `AUTHORITY: 5, ADDITIONAL: 6` 这个是远程 DNS 服务器提供的数据，不是本程序提供的，一般来说大部分服务器也不会附带这个。这段数据是 DNS 服务器的递归过程，然后把请求域名的 NS 记录也附带返回了而已，实际上用处不大。如果真的需要这样的数据，你可以本地搭建递归服务器，或手动向 root servers 递归查询得到的。

**Comment by chengr28** [comment]
用 BIND 就行，EDNS 可能得配置一下，都有相关资料。

**Comment by sysconfon** [comment]
@chengr28 
好的，非常感谢呢。
还有个问题。就是。我的配置的dns都支持edns服务。但是在解析的时候，却没有把edns打进去。
例如：
dig ip.dnspod.net @193.112.15.186
解析出来之后，有2条解析记录。
但是。如果是dig ip.dnspod.net @127.0.01
解析出来就1条解析记录。

配置的dns都支持edns服务。正常解析ip.dnspod.net都是2条记录。

有开启以下配置
EDNS Label = 1
EDNS Client Subnet Relay = 1

**Comment by chengr28** [comment]
请求有没有带 EDNS 标签 dig 应该是可以看到的，某个域名有几条解析记录……这个不能拿来准确判断吧。
