### ISSUE TITLE
老问题：使用119dns并开启edns，国内域名使用国内dns查询失败

### ISSUE THREAD

**Issue by WoChen5770** [chengr28/Pcap_DNSProxy#369]
﻿### Version/使用的版本/使用的版本
0.4.9.9

### Running Environment/运行环境/運行環境
centos

### Actual/实际情况/實際情況
看到更新了新版本，马上编译测试，可是还是出现之前的问题：
    国内正常域名使用local dns查询失败，转为Main DNS。导致查询结果不准确而且查询时间很长很长，2000ms+
如果说是119dns不支持cookie查询，可是dig也加了nocookie参数。而且没有开启任何tcp。
Pcap_DNSProxy出现这个问题后，我使用的是overture，配置上游为119dns并开启edns，国内国外查询结果一切正常。
希望作者认为可以解决一下的话能帮忙解决一下这个问题。
感谢。

**Comment by chengr28** [comment]
查询的时候抓个包发我的邮箱吧，这样直接能看到是什么问题，配置文件做测试比较费时间。

**Comment by chengr28** [comment]
或者如果不介意也可以直接把配置文件发在这里？这边都可以的。

**Comment by WoChen5770** [comment]
@chengr28 http://file.ichenqiang.com/Config.conf
最近服务器放了个公司项目，没有拿来测试，麻烦你了

**Comment by WoChen5770** [comment]
@chengr28  
刚刚我把我这份测试文件用腾讯云的vps（centos 7）和windows版一起抓包看了一下。
1. [windows版返回没问题](http://ww1.sinaimg.cn/large/b8008f97gy1fv5gmurr2zj210a04odg0.jpg)
2. [centos 国内dns119没返回，返回的是国外dns](http://ww1.sinaimg.cn/large/b8008f97gy1fv5gqzgpwcj20n207lgmi.jpg)。
有没有可能是119把腾讯云ip屏蔽了？可惜我只有这一个vps能拿来测试这个问题
但是 我用了overture 上游指定119却没问题
Pcap_DNSProxy版本是最新版

**Comment by chengr28** [comment]
最近一直在测试这个情况，这个应该是有两个不同的问题。根据『国内正常域名使用 local dns 查询失败，转为 Main DNS 导致查询结果不准确而且查询时间很长很长 2000ms+』可以看到：
* Local DNS/119 过程没有结果，这个过程是失败的
* 超过 2000ms 后很长时间都没有结果，说明后续的请求也是失败的

如果按照最新的抓包截图来看：
* Local DNS 很明显没有响应，应该是由于多次超时没有响应，程序已经把 Local DNS 目标从 Main 的 .29.29.29 切换成 Alternate 的 .28.28.28 了，而且看起来依旧没有响应
* 至于 Main DNS 阶段，截图是看到有正常收到数据包的，除非数据包不符合过滤规则，那么正常来说在 2000ms 超时并请求 Main DNS 后就会返回解析结果，不会出现长时间没有反应的情况

建议是：
* 可以在 Ping/DNS/TCP DNS 请求 Local DNS 时抓包，看看是不是 VPS 上真的不通
* Main DNS 的问题，不清楚『查询时间很长很长』指的是 2000ms 之后直接没了响应，还是这个『很长很长』指的是 2000ms？因为如果开启了 EDNS Label 这边程序会有内部的逻辑判断，如果数据包不符合要求是不会接受的，不排除是这个情况

**Comment by chengr28** [comment]
至于 Overture 的工作正常不太清楚情况，不过抓包应该也可以看出来，有两种可能：
* Overture 实际上也是不行的，解析结果来自其它 DNS 服务器
* Overture 的数据包格式和本项目的有差别，VPS 服务商只接受他们的不接受本项目的

**Comment by WoChen5770** [comment]
刚刚抓了下overture的包 好像119是可行的，那估计就是数据表格式的问题了？[图](http://ww1.sinaimg.cn/large/b8008f97gy1fv5ypqzhddj20mq03xwex.jpg)

**Comment by chengr28** [comment]
`tcpdump -vvv` 可以输出最详细的数据包格式

**Comment by WoChen5770** [comment]
<img src="http://ww1.sinaimg.cn/large/b8008f97gy1fv5z1c5ks7j211c0a9ac0.jpg"/>

**Comment by WoChen5770** [comment]
这是Pcap_DNSProxy的
<img src="http://ww1.sinaimg.cn/large/b8008f97gy1fv5zilm77tj21970dktbv.jpg"/>

**Comment by chengr28** [comment]
貌似看不出有大差别，而且如果数据包格式有问题 Main DNS 也不会接受才对。
或者可以试试‘
* `Domain Case Conversion =1` 改成 0
* `EDNS Payload Size = 1220` 改成 4096

**Comment by WoChen5770** [comment]
如果把edns关了 
EDNS Label = 0
EDNS Client Subnet Relay = 0
<img src="http://ww1.sinaimg.cn/large/b8008f97gy1fv60mmwzrjj20zg04cdgf.jpg"/>

**Comment by chengr28** [comment]
看起来的确是 EDNS 标签的问题，不清楚是不是有特定格式的标签他们不支持，他们一旦收到不能识别格式的数据包就直接不会响应，看起来还是得把能拿到解析结果的数据包和拿不到解析的数据包做个详细的对比才能判断。

**Comment by WoChen5770** [comment]
有什么需要我帮忙的没？

**Comment by chengr28** [comment]
可以试试只把 `EDNS Client Subnet Relay` 调成 0 看看？

**Comment by WoChen5770** [comment]
关闭EDNS Client Subnet Relay能得到结果，但是edns不准确
<img src="http://ww1.sinaimg.cn/large/b8008f97gy1fvbdj3a2ovj2169067gmy.jpg"/>

**Comment by chengr28** [comment]
这边调查了一下，看起来还是 119 他们自己的问题。就像 https://github.com/chengr28/Pcap_DNSProxy/issues/240 他们虽然坚称自己的服务没有问题，但实际上对 EDNS Client Subnet 的支持一直都不是很好。先梳理一下造成这个问题的原因：

* 开启了 `EDNS Label` 参数，然后开启了 `EDNS Client Subnet Relay` 参数
* `EDNS Client Subnet Relay` 是请求者的 IP 地址转发给远程 DNS 服务器，以缓解 CDN 匹配问题
* 但是 119 对 EDNS Client Subnet 的前缀长度有限制，似乎只有小部分指定的前缀长度可以正常工作
* 程序按照 IETF RFC 的推荐默认使用 24 位/IPv4 和 56 位/IPv6 的前缀长度
* 119 看起来不或很长时间才回应以上列到的前缀长度的请求，造成超时

所以这也就解释了为什么关闭 `EDNS Client Subnet Relay` 功能后能正常解析。

**Comment by chengr28** [comment]
可以使用 `+client=x.x.x.x/**` 参数做测试，例如：

* `dig +nocookie +client=x.x.x.x/32 @119.29.29.29`
* `dig +nocookie +client=x.x.x.x/28 @119.29.29.29`
* `dig +nocookie +client=x.x.x.x/24 @119.29.29.29`
* `dig +nocookie +client=x.x.x.x/16 @119.29.29.29`
* `dig +nocookie +client=x.x.x.x/8 @119.29.29.29`

**Comment by WoChen5770** [comment]
经测试，关闭 EDNS Client Subnet Relay后：
dig @111.231.*.* www.baidu.com +nocookie +subnet=*.*.*.*/24 返回结果edns准确

**Comment by WoChen5770** [comment]
当我打开EDNS Client Subnet Relay，并将Cache Single IPv4 Address Prefix = 32：
dig @x.x.x.x www.v2ex.com +nocookie 119无返回
dig @x.x.x.x www.v2ex.com +nocookie +subnet=119.29.119.29/32   119成功返回

**Comment by WoChen5770** [comment]
当打开EDNS Client Subnet Relay，并IPv4 EDNS Client Subnet Address 为null，按照你在#240 所提到的：
`[DNS]
Outgoing Protocol = IPv4 + UDP
Direct Request = 0
Cache Type = 1
Cache Parameter = 4096
Cache Single IPv4 Address Prefix = 32
Cache Single IPv6 Address Prefix = 0
Default TTL = 900`
设置为32，好像没有用，119返回失败

**Comment by WoChen5770** [comment]
Cache Single IPv4 Address Prefix好像并不能控制前缀长度
1. dig @111.231.x.x www.v2ex.com +nocookie +subnet=121.33.215.x/32 
    结果：; CLIENT-SUBNET: 121.33.215.x/32/24        119成功响应
2. dig @111.231.x.x www.v2ex.com +nocookie +subnet=121.33.215.x 
    结果：; CLIENT-SUBNET: 121.33.215.x/32/24        119成功响应
3. dig @111.231.x.x www.v2ex.com +nocookie 
    结果：; CLIENT-SUBNET: 121.33.215.0/24/0          119响应失败

以上均在Cache Single IPv4 Address Prefix = 32 测试

**Comment by chengr28** [comment]
`Cache Single IPv* Address Prefix` 这个参数是控制缓存队列的，当然不能控制 EDNS Client Subnet 的前缀长度……这个参数 `IPv* EDNS Client Subnet Address` 就是把填入的地址带出去，但是如果开启了 `EDNS Client Subnet Relay` 就只会带请求者（就是发给本程序的来源）的地址，而且这个地址是内置了 24 位（IPv4）和 56 位（IPv6）前缀长度的，不能修改。

**Comment by WoChen5770** [comment]
这个前缀长度不能修改吗？如果能修改的话，可以在配置项加一个edns前缀长度

**Comment by chengr28** [comment]
现在是内置的要修改源代码，虽然是可以加一个选项。
不过总感觉这是 119 自己的问题……

**Comment by WoChen5770** [comment]
确实是119自己的问题，你看有时间方便的话加一个吧。119那边我也提过很多次了，感觉这公共dns他们不是很看重。可是国内支持edns的好像就这一家了，百度的刚出来说支持，阿里的也说会支持，但是这两家效果很不理想，百度的甚至在官网都去掉这个说明了。

**Comment by chengr28** [comment]
可以集中到 https://github.com/chengr28/Pcap_DNSProxy/issues/401 讨论，感谢反馈。
