### ISSUE TITLE
在Openwrt上的运行情况

### ISSUE THREAD

**Issue by wongsyrone** [chengr28/Pcap_DNSProxy#37]
下面说明在MIPS ar71xx 74kc上的运行情况，测试路由Qihoo C301，还有个WRT1900AC，可惜用gcc 4.9.3编译出来内核不启动，卡在Starting Kernel...所以暂时没法测试ARM上的运行情况。

路由CPU参数
root@OpenWrt:~# cat /proc/cpuinfo 
system type             : Atheros AR9344 rev 3
machine                 : Qihoo 360 C301
processor               : 0
cpu model               : MIPS 74Kc V4.12
BogoMIPS                : 278.93
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp dsp2
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

负载
root@OpenWrt:~# uptime
 10:16:18 up 2 days, 14 min,  load average: 1.54, 0.46, 0.19
 10:21:13 up 2 days, 19 min,  load average: 0.21, 0.63, 0.38
top命令看的负载
Mem: 77788K used, 48368K free, 980K shrd, 8536K buff, 23764K cached
CPU:   0% usr   1% sys   0% nic  96% idle   0% io   0% irq   1% sirq
Load average: 0.00 0.01 0.05 1/76 20354
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
20213 20008 root     S     226m 183%   1% /usr/sbin/Pcap_DNSProxy -c /etc/pcap-

很可能是因为下面运行出现的刷新系统DNS缓存问题
问题代码从https://github.com/chengr28/Pcap_DNSProxy/blob/master/Source/Pcap_DNSProxy/Service.cpp#L366
开始，应该为OP去掉清理系统DNS缓存的功能，在OP中缓存只有dnsmasq管理，一般是使用"/etc/init.d/dnsmasq restart"来刷新缓存。

这是指定配置文件路径的前台运行模式
root@OpenWrt:/etc/pcap-dnsproxy# /usr/sbin/Pcap_DNSProxy -c /etc/pcap-dnsproxy
/bin/sh: service: not found
/bin/sh: service: not found
/bin/sh: rndc: not found
/bin/sh: service: not found
/bin/sh: service: not found
/bin/sh: rndc: not found

这是端口监听情况
root@OpenWrt:~# netstat -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      1982/dnsmasq
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1370/dropbear
tcp        0      0 0.0.0.0:1053            0.0.0.0:*               LISTEN      20213/Pcap_DNSProxy
tcp        0      0 :::80                   :::*                    LISTEN      1409/uhttpd
tcp        0      0 :::53                   :::*                    LISTEN      1982/dnsmasq
tcp        0      0 :::22                   :::*                    LISTEN      1370/dropbear
tcp        0      0 :::1053                 :::*                    LISTEN      20213/Pcap_DNSProxy

具体应用可以像dnscrypt-proxy那样，做解析的前置代理，dnsmasq的上游服务器

**Comment by wongsyrone** [comment]
暂时解决办法
https://github.com/wongsyrone/openwrt-1/commit/ec33db258547472f9e87e7e25f4c87ef8aff6f10

**Comment by chengr28** [comment]
刚才推送了源代码的更新……因为要和源代码里的风格一致，所以把 COMPILE_OPENWRT 改成了 PLATFORM_OPENWRT 可能那边的 Makefile 也要改一下……

Patch 都改好了（后两个构建的时候要传入 PLATFORM_OPENWRT 定义才能实现）：
* 把 CMakeLists.txt 放到项目根目录
* 添加了 OpenWRT 平台的 CMake 最低版本要求
* 程序本体也添加了OpenWRT 平台的刷新 DNS 缓存

**Comment by chengr28** [comment]
关于性能和资源占用的问题，因为改架构比较麻烦……可能要一段时间仔细想想才能想出方案 =_/=

**Comment by wongsyrone** [comment]
@chengr28  GCC 4.9被标记为BROKEN，因为会miscompile，https://github.com/openwrt-mirror/openwrt/commit/53a77a939215c571f27c44c436cf5f715ffc6235 所以一时没法弄了

**Comment by chengr28** [comment]
那还真是压力大……这样新版本的 GCC 也不知道什么时候能用上了。嘛其实旧版除了正则表达式的支持，其它方面倒是没什么大问题，要用应该也是没大问题的。最近也是 Debian 升到 8.0+ 才开始用 4.9+ 的 GCC 以前一直都是旧版……

DNSPing 那边的 CMakeLists.txt 已经按照 OpenWRT 的平台最低版本要求改好了
也是改成了 PLATFORM_OPENWRT 那边应该就没有大问题了ww

**Comment by wongsyrone** [comment]
使用了新的开关，降低 gcc 要求到 4.8，去掉了所有的patch， https://github.com/wongsyrone/openwrt-1/commit/eaaf6bc99c9f188376a73e3103b92644fe73807b

**Comment by wongsyrone** [comment]
还是继续在Qihoo 360 C301上进行测试，这回使用的是官方GCC 4.8 + musl-libc编译的 https://github.com/wongsyrone/openwrt-1/commit/eaaf6bc99c9f188376a73e3103b92644fe73807b ，编译之后的大小是：
-rwxr-xr-x    1 root     root       14.4K Jun 28 18:43 KeyPairGenerator
-rwxr-xr-x    1 root     root      537.4K Jun 28 18:43 Pcap_DNSProxy
默认修改了监听端口为1053，因为会与默认dnsmasq的53端口冲突，导致dnsmasq起不来，然后修改模式为Server

占用情况
两次使用top和uptime命令得到的信息为
Mem: 61512K used, 64628K free, 872K shrd, 6704K buff, 21020K cached
CPU:   0% usr   0% sys   0% nic 100% idle   0% io   0% irq   0% sirq
Load average: 0.04 0.14 0.13 1/64 6498
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 6319     1 root     S    14284  11%   0% /usr/sbin/Pcap_DNSProxy -c /etc/pcap-

Mem: 61732K used, 64408K free, 872K shrd, 6704K buff, 21020K cached
CPU:   0% usr   0% sys   0% nic  99% idle   0% io   0% irq   0% sirq
Load average: 0.04 0.09 0.12 2/64 6751
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 6623     1 root     S    14244  11%   0% /usr/sbin/Pcap_DNSProxy -c /etc/pcap-

 21:03:09 up  1:03,  load average: 0.02, 0.12, 0.12
 21:08:48 up  1:08,  load average: 0.05, 0.09, 0.12
可以看到对内存（%VSZ）的占用下降很多，CPU的话基本是在0%～3%的范围波动。

配置文件除了上面的修改，主要还有：
Buffer Queue Limits = 512
这个不增加的话貌似会导致请求队列过长，然后请求就很慢
Log Maximum Size = 4KB
默认的4MB实在是太大了，这个路由单个FLASH才16MB，本来是双FLASH的配置，不过只能同时用一块，不用来调整设置的话应该降低到2KB感觉比较合适
Accept Type = Permit:1|5|28
只接受A、AAAA、CNAME记录的请求，不过用服务名会提示配置文件出错，暂且只能使用对应的ID号
EDNS Label = 1
这个是遵照Readme里面的推荐
DNSCurve = 1
DNSCurve Protocol = UDP
使用libsodium进行测试，开启DNSCurve，没测TCP的
sodium库可以正常加载，经过上面的配置已经基本可以比较流畅的进行DNS解析工作。

发现问题：
1. 频繁出现 2015-06-28 20:08:37 -> WinPcap Error: pppoe-wan is not a Ethernet device. 这样的信息，pppoe-wan是wan口的接口名，这个错误信息是不是可以在OP上消除？
2. 在ntp校时的前提下，使用KeyPairGenerator生成的keypair填入到DNSCurve Keys中依然会提示 2015-06-28 20:56:06 -> DNSCurve Error: Client keypair(public key and secret key) error. 反而留空让程序启动的时候去生成能正常工作
3. 在执行 /usr/sbin/Pcap_DNSProxy --flush-dns 之后会出现 Flush DNS cache message was sent successfully. 的提示，但是 用于刷新系统DNS的 "/etc/init.d/dnsmasq restart"命令貌似没被执行，因为并没出现预期的系统日志变化。

**Comment by chengr28** [comment]
* 监听端口的话没法动默认桌面端的配置文件……所以需要另外再设一份默认的配置文件？
* 其实个人不太建议开 Server 的，毕竟不安全……桌面端那边默认的 Private 是限制了只有私网地址才能进行请求，否则不会做回应
* Buffer Queue Limits 参数是控制队列长度的，然后队列长度统计的重置时间是 Queue Reset Time 不过事实上由于每个请求都会新开线程处理并拥有独立的缓冲区，理论上这个过程比网络 I/O 快一个数量级以上不会阻塞的，所以就算只开几个都没问题。或许 OpenWRT 平台本身的多线程处理速度跟不上吧……之前一直有这种感觉，OpenWRT 做多线程貌似会平白无故消耗非常多的资源，桌面端则完全没这方面的问题……
* Log Maximum Size 似乎是比较小，毕竟按照平时的错误输出可能十多句就没了。不过如果是严重错误，的确一两句就能知道，大概也没什么……
* Accept Type 类型名识别有 Bug 刚才上传的新版已经修复
* DNSCurve 其实不太建议开……毕竟如果资源寸进尺土，这协议加密解密一下各种消耗 =_/=
* pppoe-wan 已经添加到白名单里了
* KeyPairGenerator 也是有 Bug 生成的密钥不对所以这边才报错……刚才上传的新版已经修复
* Flush DNS 没有执行貌似是因为之前忘记把 PLATFORM_OPENWRT 的宏定义传到 CMake 那边了……刚才的新版已经更新了 CMakeLists.txt

Bug 何其多……看来还得多多测试唉 =3=

**Comment by wongsyrone** [comment]
配置文件你那里就不用动了，在编译包的时候我这直接用sed修改就好。
多线程那部分可以考虑新开一个分支去掉多线程然后再测试，不过由于不同平台的cpu性能也不同，我在做测试的时候选择的这个路由应该是中等或者中等偏下性能，应该还是有一定代表性。
pppoe-wan的问题我突然想到，有的人可能在op上面做多拨或者移植石像鬼qos，这样出现的接口名就不可预测了，数量也不太确定，能否通过传参数来设置白名单

**Comment by chengr28** [comment]
* 去掉多线程不太可能……要是真想去掉只能用 IOCP/Epoll/kqueue 之类的来做，不同平台不一样而且感觉自己没信心可以做好……
* pppoe-wan 那个问题……要不下次更新直接就把那个报错去掉算了，当初弄这个报错是为了避免所有接口都没法正确监听而做的，现在好像也有其它方法就不需要了

**Comment by wongsyrone** [comment]
去掉报错可以单独给op做，弄个patch应该就好了，多线程先放着也可以，也可能是因为设置不合理导致的

**Comment by wongsyrone** [comment]
OpenWrt官方最近新加了GCC 5.2.0,不过目前还没有完全开放，暂时标记为BROKEN，仅在mipsel32, arm32 and x86 上做了内核启动测试，有兴趣的话可以参考https://github.com/openwrt-mirror/openwrt/commit/596e461a6ca2bb94914227de3d82b0b0b688024f

**Comment by chengr28** [comment]
一堆错误修复和新功能预定压着……短期内看来是搞不了这边的呢 =_/=
主要是没搞清楚 OpenWRT 到底是怎么部署的……乃做的那个像是直接提供一个做好了（内置各种工具）的交叉编译用的固件？也不知道如果要单独装的话得注意些什么

**Comment by wongsyrone** [comment]
单独用来发布的项目仓库已经建好了，就是还没有推，效果和
aa65535给shadowsocks做的包很类似，简单来说，克隆那个仓库的文件放到openwrt的packages文件夹中，就可以选择软件包编译了，如果有必要，还可以提供预编译版本。
另外还想做一个路由器上的界面，Luci的，不过还没想好。

**Comment by AnyoeDove** [comment]
@wongsyrone 
呃C301不死UBOOT可刷双Flash固件：http://www.right.com.cn/forum/thread-136444-1-1.html
C301 32M版固件：http://www.right.com.cn/forum/thread-147319-1-1.html

**Comment by wongsyrone** [comment]
@AnyoeDove 
这个我知道啊，不过空间大其实没什么用，log刚开始是给不懂设置的人debug用的，一旦设置好之后，除非程序本身出什么问题会输出日志，之后就不用担心大量日志占据空间，导致flash不够用的问题，剩下的是SoC和RAM的处理性能的问题了。

**Comment by qiuzi** [comment]
@wongsyrone @chengr28  这个能判断域名是否被污染吗？

**Comment by wongsyrone** [comment]
@qiuzi 
一般来说GFW伪造的包会被丢弃

**Comment by qiuzi** [comment]
@wongsyrone  现在伪装包特征不是已经变随机了吗？ 貌似不支持socks5 吧？

**Comment by chengr28** [comment]
@wongsyrone 过滤的方法还是有很多的……不一定要靠特征，顺便的确不支持 Socks5

**Comment by shuangzhijinghua** [comment]
应该用ss-tunnel，转发DNS包，这样一样可以实现本地DNS查询，不过似乎并不知道能不能抓到localhost的包？

chengr28 <notifications@github.com>于2015年9月17日周四 上午10:15写道：

**Comment by chengr28** [comment]
@shuangzhijinghua SS-Tunnel 这种是在本地开了特别的端口的，就是说会把所有发往这个端口的数据都转发到远程服务器，所以为了实现查询，最关键的问题是把 DNS 请求发到 SS-Tunnel 的端口上

**Comment by qiuzi** [comment]
@chengr28  刚刚编译后居然有420打包，动大炮打蚊子啊

**Comment by wongsyrone** [comment]
软件包仓库push了：https://github.com/wongsyrone/openwrt-Pcap_DNSProxy

**Comment by chengr28** [comment]
OK 讨论的话都可以转到那边去了w

**Comment by Sense1988** [comment]
已经有人做了LuCI界面,但是model/cbi里的那个lua文件貌似不是很完善

**Comment by wongsyrone** [comment]
个人来讲是不倾向于使用luci的，毕竟主要配置都在Config.conf里面，使用SSH足够了。
