### ISSUE TITLE
[微小的问题] shell 脚本语句错误，echo 未加 -e 参数

### ISSUE THREAD

**Issue by YKilin** [chengr28/Pcap_DNSProxy#370]
https://github.com/chengr28/Pcap_DNSProxy/blob/17a851623a52612b8c39f70a3bc17bf734f0a7f4/Source/Auxiliary/Scripts/Update_Routing.sh#L34

**Comment by YKilin** [comment]
顺便还有这个地方也是（
https://github.com/chengr28/Pcap_DNSProxy/blob/17a851623a52612b8c39f70a3bc17bf734f0a7f4/Source/Auxiliary/ExampleConfig/PcapDNSProxyService#L59

**Comment by chengr28** [comment]
应该没问题了，感谢反馈。

**Comment by YKilin** [comment]
感谢修复
