### ISSUE TITLE
为什么正常使用后却打不开汤不热和维基百科？

### ISSUE THREAD

**Issue by chinaniupai** [chengr28/Pcap_DNSProxy#374]
版本是最新的测试版，DNS设置127.0.0.1，程序是正常开启的没有报错。但是打不开https://www.tumblr.com

**Comment by SeaHOH** [comment]
`www.tumblr.com`似乎 IP 被封
`zh.wikipedia.org`SNI 被封

**Comment by chengr28** [comment]
Tumblr 也是 TLS SNI RESET

**Comment by chinaniupai** [comment]
恕我直言，那本软件还有什么用？还有哪些网站是被DNS污染的？@SeaHOH @chengr28

**Comment by SeaHOH** [comment]
确实一日不如一日，但好歹还是有用的，毕竟这是互联网的基础，可配合其它工具使用。

**Comment by chinaniupai** [comment]
@SeaHOH 所以说，这是从可以越墙的清除DNS污染的软件变成了不可越墙类似于223.5.5.5的软件了？

**Comment by SeaHOH** [comment]
软件功能并未有改变，也不提供翻墙功能。

**Comment by chinaniupai** [comment]
上汤不热这种网站也算翻墙吧？虽然汤不热以前不是被IP封锁，但难道以前的汤不热不算被墙？

**Comment by SeaHOH** [comment]
Pcap_DNSProxy 从来不提供翻墙服务。
>Pcap_DNSProxy 是一个基于 WinPcap/LibPcap 用于过滤 DNS 投毒污染的工具，提供便捷和强大的包含正则表达式的修改 Hosts 的方法，以及对 DNSCurve/DNSCrypt 协议、并行和 TCP 协议请求的支持。多服务器并行请求功能，更可提高在恶劣网络环境下域名解析的可靠性：

**Comment by chinaniupai** [comment]
@SeaHOH 那上汤不热算不算翻墙？

**Comment by chinaniupai** [comment]
@SeaHOH 我的理解中，翻墙就是上国家封锁的网站，我个人认为汤不热和维基是国家封的，不是运营商ISP或者某些DNS自行投毒的。

**Comment by chinaniupai** [comment]
@SeaHOH 而我的理解中，既然本软件可以上汤不热这种国家封锁的网站，那就是翻墙软件。因为国家的墙封网站有很多种方式。“DNS投毒、IP封锁”等等。而本软件可以浏览国家墙掉的利用DNS投毒的网站。所以我的个人印象当中，本软件是一个过滤 DNS 投毒污染的工具，同时也能用来翻墙，所以本软件在我的印象里是一个翻墙软件。
除非本软件再也无法上那些被国家利用任何手段墙掉的网站，仅仅只是解除DNS投毒，而且这个解除DNS投毒还不包括国家进行的投毒【墙】。
比如114DNS，自称无劫持，但为什么上不去汤不热？因为如果他能上那些被国家利用DNS投毒劫持掉的网站。那他就算是一个翻墙工具了。

**Comment by chinaniupai** [comment]
我还是非常感谢所有对Pcap_DNSProxy 做出贡献的人。

**Comment by geekyouth** [comment]
所以，Pcap_DNSProxy到底还是无法用于翻墙？

**Comment by chinaniupai** [comment]
@geekyouth 是的，只能解除污染，至于解除污染之后你还是不能上那个网站就不归Pcap_DNSProxy管了。
