### ISSUE TITLE
pcap_DNSProxy 安装不成功 1062

### ISSUE THREAD

**Issue by aiyu20181** [chengr28/Pcap_DNSProxy#375]
﻿### Version/使用的版本/使用的版本
0.4.9.9

### Running Environment/运行环境/運行環境

windows10  X64

### Expectation/期望情况/期望情況

能安装，能使用

### Actual/实际情况/實際情況

**遇到了1062错误，不知道是什么原因？**
- 这是错误时的图片
![image](https://user-images.githubusercontent.com/35887199/46244955-41163100-c419-11e8-9620-f07dfcef2323.png)

- **这是Error.log(原版)**

[Error.log](https://github.com/chengr28/Pcap_DNSProxy/files/2430561/Error.log)

- **这是截图**

![image](https://user-images.githubusercontent.com/35887199/46244978-8dfa0780-c419-11e8-8873-c68d793e139a.png)

**Comment by aiyu20181** [comment]
- 应该不是**权限**问题，我已经用**管理员身份运行**了

**Comment by aiyu20181** [comment]
# 问题已经解决
- 解决方法
1. 安装时不能外挂SS及V2RAY
2. 个人感觉应该是其占用127.0.0.1端口，导致不能安装
3. 先停止SS及V2RAY服务，再安装，之后在启动SS及V2RAY就不耽误大家了！

**Comment by SeaHOH** [comment]
不好意思，没仔细看，看到警告还以为是权限不够。。。

**Comment by chengr28** [comment]
@SeaHOH 那段话是巨硬自己的详细介绍，或许通过错误代码去查更清晰：10048 WSAEADDRINUSE

**Comment by SeaHOH** [comment]
因为之前取消了自动请求权限，直接运行就是红的，然后看到这个完全没过脑。。。
坏习惯很难改掉，下次看到请无视我。捂脸~

**Comment by chengr28** [comment]
不过批处理显示是红色的确是因为检查到没有管理员权限，但奇怪的是最上面提供的截图『在没有管理员权限』的情况下却启动了服务，服务启动印象中是需要管理员权限的，所以出现这个情况的原因有可能是批处理的权限判断有问题……
