### ISSUE TITLE
关于黑名单及路由表更新问题

### ISSUE THREAD

**Issue by aiyu20181** [chengr28/Pcap_DNSProxy#376]
﻿### Version/使用的版本/使用的版本

0.4.9.9

### Running Environment/运行环境/運行環境

windows10 X64

### Expectation/期望情况/期望情況

- IPFilter.ini
- Routing.txt
- WhiteList.txt
会随时更新吗?还是要到什么地方更新?

**Comment by SeaHOH** [comment]
tools 文件夹附带路由表更新脚本，隔段时间运行一次即可。
黑名单随发布更新，一般不用在意。

**Comment by aiyu20181** [comment]
## 非常感谢
