### ISSUE TITLE
无法解析白名单外域名

### ISSUE THREAD

**Issue by qxwd1123** [chengr28/Pcap_DNSProxy#377]
﻿### Version/使用的版本/使用的版本

Pcap_DNSProxy 0.4.9.11
LibEvent version 2.1.8-stable
LibSodium version 1.0.16
libpcap version 1.9.0-PRE-GIT (with TPACKET_V3)
OpenSSL 1.1.1  11 Sep 2018

### Running Environment/运行环境/運行環境

Archlinux
默认配置未修改

### Actual/实际情况/實際情況

无法解析白名单外域名

dig google.com @127.0.0.1            

; <<>> DiG 9.13.3 <<>> google.com @127.0.0.1
;; global options: +cmd
;; connection timed out; no servers could be reached

附抓包
[a.zip](https://github.com/chengr28/Pcap_DNSProxy/files/2467181/a.zip)

**Comment by chengr28** [comment]
使用 `dig` 测试时请加上 `+nocookie` 参数，程序有相关的过滤，如果服务器不支持强开会有问题。

**Comment by qxwd1123** [comment]
+nocookie就好了
请问这个“服务器不支持”是指上有dns服务器吗？
另外有时候nslookup和dig返回的结果不同，请问是怎么回事？

**Comment by qxwd1123** [comment]
还有我这污染比较严重，可以用sstunnel转发dns做上游吗
谢谢

**Comment by chengr28** [comment]
ss-tunnel 本质上是个隧道，直接把请求发过去就行。
