### ISSUE TITLE
请问这个错误是什么意思？

### ISSUE THREAD

**Issue by chinaniupai** [chengr28/Pcap_DNSProxy#378]
[2018-10-12 13:54:52] -> [Network Error] UDP connection initialization error: A socket operation was attempted to an unreachable network[10051].
使用的是最新版本的

**Comment by chinaniupai** [comment]
我的比特彗星里面的tracker也会提示2018-10-12 14:10:30	UDP Tracker no response.

**Comment by chengr28** [comment]
找不到路由，就是上不了外网的意思。

**Comment by chinaniupai** [comment]
@chengr28 不知道为什么会弹出这个，该怎么解决呀？我是公网IP呀

**Comment by SeaHOH** [comment]
是不是设置成 IPv6 了。

**Comment by chinaniupai** [comment]
@chengr28 确实是一直刷屏，而且我的比特彗星里面的UDP的tracker也会提示UDP Tracker no response.，

请问Winsock怎么检查？

**Comment by chinaniupai** [comment]
@SeaHOH 我的Pcap是下载后直接使用的，没有修改过内容。您说的设置成 IPv6指的是软件里吗？还是？

**Comment by SeaHOH** [comment]
哦，默认配置没使用 IPv6 Out。

你可以尝试重置 Winsock 目录，如果问题没解决，你应该提供更多相关信息。
比如，网络环境和配置，防火墙设置等。

**Comment by chinaniupai** [comment]
@SeaHOH 请问如何重置Winsock 目录？

**Comment by chinaniupai** [comment]
@SeaHOH 暂时好像不弹出这个错误的日志了，但是比特彗星还是提示UDP Tracker no response.

**Comment by chengr28** [comment]
不持续输出错误就没问题，这个错误其实就像你把网线拔掉……可能是短暂连不通外网，域名解析正常就行。

**Comment by chinaniupai** [comment]
@SeaHOH 但似乎并不是没法使用，而是过一段时间这些原本显示【UDP Tracker no response】的tracker会恢复正常。.

**Comment by chinaniupai** [comment]
这些UDP的tracker都是一阵一阵的，刚开始打开软件的时候，就会集体提示UDP Tracker no response.
等过了一段时间之后，才会慢慢的正常

**Comment by SeaHOH** [comment]
估计是数量过多，bitcomet 可能同时发起太多请求。

**Comment by SeaHOH** [comment]
你的机器是否处于内网，没公网 IP 那种。

**Comment by chinaniupai** [comment]
@SeaHOH 看了一下，我是公网IP，联通

**Comment by chengr28** [comment]
可以留意下时间，一般来说有些机器在程序启动之后才初始化网络就有可能出现这种问题，如果解析正常就不用管，或者把错误输出关掉就行，这个 10065 也不是什么重大错误。
