### ISSUE TITLE
Hosts条目不生效

### ISSUE THREAD

**Issue by WeirdoShaw** [chengr28/Pcap_DNSProxy#379]
﻿### Version/使用的版本/使用的版本
0.4.9.11

### Running Environment/运行环境/運行環境
Windows 10 Pro Version 1809

### Expectation/期望情况/期望情況
以下Hosts条目工作
```
[Hosts]
192.168.100.100 Media-Server\.lan
192.168.100.1 VMWare-OpenWrt\.lan
```

### Actual/实际情况/實際情況
执行`nslookup` 返回`Non-existent domain`

### Appendix/附注/附注
对以下条目进行了测试
```
[Hosts]
192.168.100.100 Media-Server\.lan    //Non-existent domain
192.168.100.1 VMWare-OpenWrt\.lan    //Non-existent domain

192.168.100.201 test-domain    //Non-existent domain
192.168.100.202 ya-test-domain\.lan    //Works
192.168.100.105 another-test\.lan    //Works
192.168.100.100 plz-makeitwork.\lan    //Works
```
```
PS C:\Users\user> nslookup Media-Server 192.168.100.1
Server:  VMWare-OpenWrt.lan
Address:  192.168.100.1

Name:    Media-Server.lan
Address:  192.168.100.100
```

**Comment by chengr28** [comment]
这里的确有问题，因为之前添加大小写随机功能的时候似乎对 Hosts 的匹配有影响，所以内部处理是把所有请求小写化了，然后正则表达式大小写敏感，所以请求的时候就匹配不上了……

**Comment by WeirdoShaw** [comment]
我试了下，果然在`Hosts.ini`中把条目换成小写就可以了。
追问一下，为什么要在`Hosts.ini`中填入`media-server\.lan`而不是`media-server`呢？

**Comment by chengr28** [comment]
这个应该是因为设置了特定 DNS 后缀的缘故，在没有设置的情况下是直接请求的，设置后每个域名都会被自动加上后缀，参见 https://msdn.microsoft.com/en-us/library/ms813269.aspx

**Comment by chengr28** [comment]
刚才更新的版本应该没问题了，有空可以试试，感谢反馈。
