### ISSUE TITLE
Linux系统，添加 [Address Hosts] 条目之后，Pcap_DNSProxy 进程自动结束？

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#38]
Linux 系统信息：
root@ubuntu:~/Pcap_DNSProxy/Source/Release# cat /etc/os-release
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

root@ubuntu:~/Pcap_DNSProxy/Source/Release# uname -a
Linux ubuntu 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~/Pcap_DNSProxy/Source/Release#

--------------------------------------------------------------------
没有配置 [Address Hosts] 之前，Pcap_DNSProxy运行正常 ([Address Hosts] 条目已经用 # 注释掉了)：
root@ubuntu:~/Pcap_DNSProxy/Source/Release# cat Hosts.conf
[Hosts]
127.255.255.254 localhost.server

[Local Hosts]

[Address Hosts]
#127.0.0.1|127.0.0.2 127.0.0.0-127.255.255.255
root@ubuntu:~/Pcap_DNSProxy/Source/Release# netstat -tlnp|grep 53
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      62421/Pcap_DNSProxy
tcp6       0      0 :::53                   :::*                    LISTEN      62421/Pcap_DNSProxy

--------------------------------------------------------------------
添加 [Address Hosts] 条目之后，Pcap_DNSProxy 进程自动结束，而且也没有生成 error.log 错误日志文件 (删除 [Address Hosts] 条目的注释)：
root@ubuntu:~/Pcap_DNSProxy/Source/Release# cat Hosts.conf
[Hosts]
127.255.255.254 localhost.server

[Local Hosts]

[Address Hosts]
127.0.0.1|127.0.0.2 127.0.0.0-127.255.255.255
root@ubuntu:~/Pcap_DNSProxy/Source/Release# netstat -tlnp|grep 53
root@ubuntu:~/Pcap_DNSProxy/Source/Release#

而且没有生成 error.log 错误日志文件，下面是文件列表：
root@ubuntu:~/Pcap_DNSProxy/Source/Release# ll
total 936
drwxr-xr-x  2 root root   4096 Jun 28 12:20 ./
drwxr-xr-x 10 root root   4096 Jun 28 00:55 ../
-rw-r--r--  1 root root   4341 Jun 28 12:08 Config.conf
-rw-r--r--  1 root root    370 Jun 28 12:20 Hosts.conf
-rw-r--r--  1 root root   1271 Jun 28 00:55 IPFilter.conf
-rwxr-xr-x  1 root root   8576 Jun 28 00:54 KeyPairGenerator*
-rwxr-xr-x  1 root root 733232 Jun 28 00:55 Pcap_DNSProxy*
-rw-r--r--  1 root root   1153 Jun 28 01:04 Pcap_DNSProxy.service
-rw-r--r--  1 root root   1856 Jun 28 00:55 PcapDNSProxyService
-rw-r--r--  1 root root  91553 Jun 28 00:55 Routing.txt
-rw-r--r--  1 root root  80457 Jun 28 00:55 White_List.txt
root@ubuntu:~/Pcap_DNSProxy/Source/Release#

--------------------------------------------------------------------
说明：
比较奇怪的是，我在添加了[Address Hosts] 条目之后，也没有对 Pcap_DNSProxy 进程进行任何重启之类的操作，他就马上自动结束了，也没有生成 error.log 错误日志文件，不知道是什么原因造成的？

**Comment by chengr28** [comment]
抱歉拖了一段时间才有回复……刚才测试了的确是程序的问题，所有平台都有
下次更新的时候会修复……

**Comment by jzp820927** [comment]
感谢作者及时测试。等待更新！

**Comment by chengr28** [comment]
刚才已经更新了新的版本，应该是没有问题的了，感谢反馈w
