### ISSUE TITLE
编译错误：交叉编译 mips ar71xx，gcc 7.3  错误版本0.4.9.11

### ISSUE THREAD

**Issue by wangmice** [chengr28/Pcap_DNSProxy#380]
﻿### Version/使用的版本/使用的版本

0.4.9.11

### Running Environment/运行环境/運行環境
交叉编译 mips ar71xx，gcc 7.3
Source/Pcap_DNSProxy/Network.cpp:563:58: error: 'EVENT_BASE_COUNT_ACTIVE' was not declared in this scope

**Comment by xiaofami** [comment]
I'm compiling under Centos 7 and ecounted with the same issue .Below is the log:

> [demo@localhost Scripts]$ ./CMake_Build.sh
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/demo/Pcap_DNSProxy/Source/Object
Scanning dependencies of target Pcap_DNSProxy
[  4%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o
[ 13%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurveControl.cpp.o
[ 18%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
[ 18%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o
[ 22%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurveRequest.cpp.o
[ 27%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Initialization.cpp.o
[ 31%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Main.cpp.o
[ 36%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Monitor.cpp.o
[ 40%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Network.cpp.o
/home/demo/Pcap_DNSProxy/Source/Pcap_DNSProxy/Network.cpp: In function ‘void TimerCallback_SocketSend(int, short int, void*)’:
/home/demo/Pcap_DNSProxy/Source/Pcap_DNSProxy/Network.cpp:563:58: error: ‘EVENT_BASE_COUNT_ACTIVE’ was not declared in this scope
   event_base_get_num_events(CallbackArgument->EventBase, EVENT_BASE_COUNT_ACTIVE) > 0) //Waiting all callback finished.
                                                          ^~~~~~~~~~~~~~~~~~~~~~~
/home/demo/Pcap_DNSProxy/Source/Pcap_DNSProxy/Network.cpp:563:58: note: suggested alternative: ‘EVENT_BASE_FLAG_NO_CACHE_TIME’
   event_base_get_num_events(CallbackArgument->EventBase, EVENT_BASE_COUNT_ACTIVE) > 0) //Waiting all callback finished.
                                                          ^~~~~~~~~~~~~~~~~~~~~~~
                                                          EVENT_BASE_FLAG_NO_CACHE_TIME
/home/demo/Pcap_DNSProxy/Source/Pcap_DNSProxy/Network.cpp:563:3: error: ‘event_base_get_num_events’ was not declared in this scope
   event_base_get_num_events(CallbackArgument->EventBase, EVENT_BASE_COUNT_ACTIVE) > 0) //Waiting all callback finished.
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/demo/Pcap_DNSProxy/Source/Pcap_DNSProxy/Network.cpp:563:3: note: suggested alternative: ‘event_base_dump_events’
   event_base_get_num_events(CallbackArgument->EventBase, EVENT_BASE_COUNT_ACTIVE) > 0) //Waiting all callback finished.
   ^~~~~~~~~~~~~~~~~~~~~~~~~
   event_base_dump_events
/home/demo/Pcap_DNSProxy/Source/Pcap_DNSProxy/Network.cpp: In function ‘void TimerCallback_TransmissionOnce(int, short int, void*)’:
/home/demo/Pcap_DNSProxy/Source/Pcap_DNSProxy/Network.cpp:879:58: error: ‘EVENT_BASE_COUNT_ACTIVE’ was not declared in this scope
   event_base_get_num_events(CallbackArgument->EventBase, EVENT_BASE_COUNT_ACTIVE) > 0) //Waiting all callback finished.
                                                          ^~~~~~~~~~~~~~~~~~~~~~~
/home/demo/Pcap_DNSProxy/Source/Pcap_DNSProxy/Network.cpp:879:58: note: suggested alternative: ‘EVENT_BASE_FLAG_NO_CACHE_TIME’
   event_base_get_num_events(CallbackArgument->EventBase, EVENT_BASE_COUNT_ACTIVE) > 0) //Waiting all callback finished.
                                                          ^~~~~~~~~~~~~~~~~~~~~~~
                                                          EVENT_BASE_FLAG_NO_CACHE_TIME
/home/demo/Pcap_DNSProxy/Source/Pcap_DNSProxy/Network.cpp:879:3: error: ‘event_base_get_num_events’ was not declared in this scope
   event_base_get_num_events(CallbackArgument->EventBase, EVENT_BASE_COUNT_ACTIVE) > 0) //Waiting all callback finished.
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/demo/Pcap_DNSProxy/Source/Pcap_DNSProxy/Network.cpp:879:3: note: suggested alternative: ‘event_base_dump_events’
   event_base_get_num_events(CallbackArgument->EventBase, EVENT_BASE_COUNT_ACTIVE) > 0) //Waiting all callback finished.
   ^~~~~~~~~~~~~~~~~~~~~~~~~
   event_base_dump_events
[ 45%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PacketData.cpp.o
make[2]: *** [CMakeFiles/Pcap_DNSProxy.dir/Network.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
make: *** [all] Error 2
mv: cannot stat ‘Object/Pcap_DNSProxy’: No such file or directory
[demo@localhost Scripts]$

**Comment by chengr28** [comment]
Please uninstall all libevent or libevent-dev.. in package tools (like `apt-get`), then download and install latest libevent version manually from official website. Version in package tool is too old.

**Comment by xiaofami** [comment]
> Please uninstall all libevent or libevent-dev.. in package tools (like `apt-get`), then download and install latest libevent version manually from official website. Version in package tool is too old.

Thanks for instruction .The compiling went flawless after I compiled and installed the latest libevent.However ,the Pcap_DNSProxy run with the following error :

> [demo@localhost Pcap_DNSProxy]$ ./Pcap_DNSProxy
./Pcap_DNSProxy: error while loading shared libraries: libevent_core-2.1.so.6: cannot open shared object file: No such file or directory

The related libevent libraries is in **/usr/local/lib/** directory:

> /usr/lib64/samba/libevents-samba4.so
/usr/local/lib/libevent-2.1.so.6
/usr/local/lib/libevent-2.1.so.6.0.2
/usr/local/lib/libevent.a
/usr/local/lib/libevent.la
/usr/local/lib/libevent.so
/usr/local/lib/libevent_core-2.1.so.6
/usr/local/lib/libevent_core-2.1.so.6.0.2
/usr/local/lib/libevent_core.a
/usr/local/lib/libevent_core.la
/usr/local/lib/libevent_core.so
/usr/local/lib/libevent_extra-2.1.so.6
/usr/local/lib/libevent_extra-2.1.so.6.0.2
/usr/local/lib/libevent_extra.a
/usr/local/lib/libevent_extra.la
/usr/local/lib/libevent_extra.so
/usr/local/lib/libevent_openssl-2.1.so.6
/usr/local/lib/libevent_openssl-2.1.so.6.0.2
/usr/local/lib/libevent_openssl.a
/usr/local/lib/libevent_openssl.la
/usr/local/lib/libevent_openssl.so
/usr/local/lib/libevent_pthreads-2.1.so.6
/usr/local/lib/libevent_pthreads-2.1.so.6.0.2
/usr/local/lib/libevent_pthreads.a
/usr/local/lib/libevent_pthreads.la
/usr/local/lib/libevent_pthreads.so
/usr/local/lib/pkgconfig/libevent.pc
/usr/local/lib/pkgconfig/libevent_core.pc
/usr/local/lib/pkgconfig/libevent_extra.pc
/usr/local/lib/pkgconfig/libevent_openssl.pc
/usr/local/lib/pkgconfig/libevent_pthreads.pc

**Comment by xiaofami** [comment]
Issue solved:

> sudo vi /etc/ld.so.conf.d/libevent.conf

Add 

> /usr/local/lib

Then run

> sudo /sbin/ldconfig

Pcap_DNSProxy works now :smiley_cat:

**Comment by wangmice** [comment]
可以不可以加入对libevent 版本的判断？如果目标系统libevent版本过低的话提示一下。

**Comment by chengr28** [comment]
这个建议不错，有空这边测试一下。

**Comment by chengr28** [comment]
@wongsyrone 这种写在代码里的，如果是查看运行调用的版本 `--lib-version` 参数可以看到，计划是编译的时候检查一次，运行时检不检查得考虑一下，感觉有点重复了。

**Comment by wongsyrone** [comment]
那个是头文件里面的版本，并不是运行时版本，有可能用新版编译的，但是复制到旧库的机器上运行，可以不检查是否匹配，只用运行时版本就行

**Comment by chengr28** [comment]
已经加上了，感谢反馈。
