### ISSUE TITLE
Address Hosts 替换前缀长度 >= 64 的 IPv6 地址出错

### ISSUE THREAD

**Issue by LGA1150** [chengr28/Pcap_DNSProxy#381]
﻿### Version/使用的版本/使用的版本
0.4.9.11

### Running Environment/运行环境/運行環境
OpenWrt 18.06

### Expectation/期望情况/期望情況
Address Hosts
`2405:7000:8:3989::/64 2600:1409:a:780::-2600:1409:a:78f::ffff`
应该把 `2600:1409:a:780::6bb` 替换为 `2405:7000:8:3989::6bb`

### Actual/实际情况/實際情況
被替换为 `2405:7000:8:3989:2405:7000:8:3fbb`

**Comment by chengr28** [comment]
看起来是之前弄坏了，不太清楚是什么时候开始出问题的，下次更新应该会修复。
这个 Address Hosts 的实现比较精细，有被改坏的可能性……

**Comment by chengr28** [comment]
刚才更新的版本应该修复这个问题了，有空可以试试，感谢反馈。
