### ISSUE TITLE
安装成功后无法start服务

### ISSUE THREAD

**Issue by LiuZHolmes** [chengr28/Pcap_DNSProxy#383]
﻿### Version/使用的版本/使用的版本
Pcap_DNSProxy 0.4.9.9

### Running Environment/运行环境/運行環境
Ubuntu

### Expectation/期望情况/期望情況
安装完成后start服务成功

### Actual/实际情况/實際情況
服务PID为空，未启动

```
root@vultr:/home/Pcap_DNSProxy/Source/Release# ./Linux_Install.SysV.sh
./Linux_Install.SysV.sh: line 27: insserv: command not found
● PcapDNSProxyService.service - LSB: Pcap_DNSProxy service
   Loaded: loaded (/etc/init.d/PcapDNSProxyService; bad; vendor preset: enabled)
   Active: active (exited) since Tue 2018-10-16 22:31:15 CST; 7min ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0
   Memory: 0B
      CPU: 0

Oct 16 22:31:15 vultr.guest systemd[1]: Starting LSB: Pcap_DNSProxy service...
Oct 16 22:31:15 vultr.guest PcapDNSProxyService[15699]: Start Pcap_DNSProxy service.
Oct 16 22:31:15 vultr.guest PcapDNSProxyService[15699]: /sbin/start-stop-daemon: unable to stat /home/Pcap_DNSProxy/Source/Release/
Oct 16 22:31:15 vultr.guest systemd[1]: Started LSB: Pcap_DNSProxy service.
Oct 16 22:34:34 vultr.guest systemd[1]: Started LSB: Pcap_DNSProxy service.
Oct 16 22:37:07 vultr.guest systemd[1]: Started LSB: Pcap_DNSProxy service.
Oct 16 22:38:26 vultr.guest systemd[1]: Started LSB: Pcap_DNSProxy service.
root@vultr:/home/Pcap_DNSProxy/Source/Release# sh PcapDNSProxyService start
Start Pcap_DNSProxy service.
root@vultr:/home/Pcap_DNSProxy/Source/Release# sh PcapDNSProxyService status

  PID TTY          TIME CMD
-e
Pcap_DNSProxy is not running when PID is empty.

**Comment by chengr28** [comment]
请先升级到最新版本再试试，一般来说出问题在目录下会自动生成 `Error.log` 可以看看。
如果怀疑有问题可以绕过服务控制脚本，直接在终端运行的，都支持。

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/47277885-faba8900-d5f6-11e8-942c-fdb716ff6462.png)
错误: 没有找到进程 "Pcap_DNSProxy.exe"。
但32位Win10 运行 Pcap_DNSProxy.exe 报错，64位专用？
![image](https://user-images.githubusercontent.com/37962734/47277911-5a189900-d5f7-11e8-8e73-09af174152e3.png)
貌似目前正常，没必要：
1、卸载。。。
2、把 Pcap_DNSProxy_x86.exe 改名 Pcap_DNSProxy.exe 再安装？

**Comment by AnyWAT** [comment]
WinPcap_4.1.3.exe 安装报错？
![image](https://user-images.githubusercontent.com/37962734/47278091-b5975680-d5f8-11e8-952b-0f041ec4a0bb.png)

**Comment by chengr28** [comment]
```
错误: 没有找到进程 "Pcap_DNSProxy.exe"。
```
这个可以忽略的，因为截图脚本应该是选择了重启服务，也就是先停止再开启，中间会有个进程检查的功能检查是否还在运行，只要下面启动服务后不提示其它就没有问题。还有 Pcap_DNSProxy.exe 是 x64 专用的，用 32 位肯定运行不了……

**Comment by chengr28** [comment]
有更新的信息直接回复即可，谢谢。
