### ISSUE TITLE
socks代理中 Target Server 的问题

### ISSUE THREAD

**Issue by sayJYes** [chengr28/Pcap_DNSProxy#385]
疑问：
SOCKS Target Server配置项的做用是什么？
比如[Proxy]下面，我配置
SOCKS Target Server = 8.8.8.8:53
SOCKS Proxy = 1
SOCKS Proxy Only = 1
是不是意味着，[Addresses]下面的配置将失效，此时我的dns是走socks代理出去的，而且请求的目标dns为8.8.8.8:53

﻿### Version/使用的版本/使用的版本
Pcap_DNSProxy 0.4.9.11

### Running Environment/运行环境/運行環境
windows server 2008

### Expectation/期望情况/期望情況
配置proxy走本地ss的1080端口，出去后去SOCKS Target Server选项配置的8.8.8.8查询dns

### Actual/实际情况/實際情況
出去后去查询的dns服务器为114.114.115.115

使用的查询网站：
https://dnsleaktest.com/

配置如下：
[Base]
Version = 0.45
File Refresh Time = 15
Large Buffer Size = 4096
Additional Path = 
Hosts File Name = Hosts.ini|Hosts.conf|Hosts.txt|WhiteList.txt
IPFilter File Name = IPFilter.ini|IPFilter.conf|IPFilter.dat|Routing.txt|chnroute.txt

[Log]
Print Log Level = 3
Log Maximum Size = 8MB

[Listen]
Process Unique = 1
Pcap Capture = 1
Pcap Devices Blacklist = AnyConnect|Host|Hyper|ISATAP|IKE|L2TP|Only|Oracle|PPTP|Pseudo|Teredo|Tunnel|Virtual|VMNet|VMware|VPN|any|gif|lo|nflog|nfqueue|stf|tunl|utun
Pcap Reading Timeout = 250
Listen Protocol = IPv6 + IPv4 + TCP + UDP
Listen Port = 53
Operation Mode = Private
IPFilter Type = Deny
IPFilter Level < 0
Accept Type = 

[DNS]
Outgoing Protocol = IPv4 + UDP
Direct Request = 0
Cache Type = Timer + Queue
Cache Parameter = 4096
Cache Single IPv4 Address Prefix = 0
Cache Single IPv6 Address Prefix = 0
Default TTL = 900

[Local DNS]
Local Protocol = IPv4 + UDP
Local Hosts = 0
Local Routing = 1
Local Force Request = 0

[Addresses]
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 
IPv4 Main DNS Address = 114.114.115.115:53
IPv4 Alternate DNS Address = 114.114.114.114:53
IPv4 Local Main DNS Address = 114.114.115.115:53
IPv4 Local Alternate DNS Address = 114.114.114.114:53
IPv6 Listen Address = 
IPv6 EDNS Client Subnet Address = 
IPv6 Main DNS Address = [2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = [2606:4700:4700::1001]:53|[2620:FE::FE]:53|[2620:0:CCD::2]:5353
IPv6 Local Main DNS Address = [240C::6644]:53
IPv6 Local Alternate DNS Address = [240C::6666]:53

[Values]
Thread Pool Base Number = 0
Thread Pool Maximum Number = 128
Thread Pool Reset Time = 120
Queue Limits Reset Time = 0
EDNS Payload Size = 1220
IPv4 Packet TTL = 72 - 255
IPv4 Main DNS TTL = 0
IPv4 Alternate DNS TTL = 0
IPv6 Packet Hop Limits = 72 - 255	
IPv6 Main DNS Hop Limits = 0
IPv6 Alternate DNS Hop Limits = 0
Hop Limits Fluctuation = 1
Reliable Once Socket Timeout = 3000
Reliable Serial Socket Timeout = 1500
Unreliable Once Socket Timeout = 2000
Unreliable Serial Socket Timeout = 1000
TCP Fast Open = 0
Receive Waiting = 0
ICMP Test = 900
Domain Test = 900
Alternate Times = 10
Alternate Time Range = 60
Alternate Reset Time = 300
Multiple Request Times = 0

[Switches]
Domain Case Conversion = 1
Compression Pointer Mutation = 0
EDNS Label = 0
EDNS Client Subnet Relay = 0
DNSSEC Request = 0
DNSSEC Force Record = 0
Alternate Multiple Request = 0
IPv4 Do Not Fragment = 0
TCP Data Filter = 1
DNS Data Filter = 1
Blacklist Filter = 1
Resource Record Set TTL Filter = 0

[Data]
ICMP ID = 
ICMP Sequence = 
ICMP PaddingData = 
Domain Test Protocol = TCP + UDP
Domain Test ID = 
Domain Test Data = 
Local Machine Server Name = 

[Proxy]
SOCKS Proxy = 1
SOCKS Version = 5
SOCKS Protocol = IPv4 + UDP
SOCKS UDP No Handshake = 1
SOCKS Proxy Only = 1
SOCKS IPv4 Address = 127.0.0.1:1080
SOCKS IPv6 Address = [::1]:1080
SOCKS Target Server = 8.8.8.8:53
SOCKS Username = 
SOCKS Password = 
HTTP CONNECT Proxy = 0
HTTP CONNECT Protocol = IPv4
HTTP CONNECT Proxy Only = 0
HTTP CONNECT IPv4 Address = 127.0.0.1:1080
HTTP CONNECT IPv6 Address = 
HTTP CONNECT Target Server = 8.8.4.4:53
HTTP CONNECT TLS Handshake = 0
HTTP CONNECT TLS Version = 0
HTTP CONNECT TLS Validation = 1
HTTP CONNECT TLS Server Name Indication = 
HTTP CONNECT TLS ALPN = 0
HTTP CONNECT Version = 1.1
HTTP CONNECT Header Field = User-Agent: Pcap_DNSProxy/0.5.0.0
HTTP CONNECT Header Field = Accept: */*
HTTP CONNECT Header Field = Cache-Control: no-cache
HTTP CONNECT Header Field = Pragma: no-cache
HTTP CONNECT Proxy Authorization = 

[DNSCurve]
DNSCurve = 0
DNSCurve Protocol = IPv4 + UDP
DNSCurve Payload Size = 512
DNSCurve Reliable Socket Timeout = 3000
DNSCurve Unreliable Socket Timeout = 2000
DNSCurve Encryption = 1
DNSCurve Encryption Only = 0
DNSCurve Client Ephemeral Key = 0
DNSCurve Key Recheck Time = 1800

[DNSCurve Database]
DNSCurve Database Name = dnscrypt-resolvers.csv
DNSCurve Database IPv4 Main DNS = cisco
DNSCurve Database IPv4 Alternate DNS = 
DNSCurve Database IPv6 Main DNS = cisco-ipv6
DNSCurve Database IPv6 Alternate DNS = 

[DNSCurve Addresses]
DNSCurve IPv4 Main DNS Address = 208.67.220.220:443
DNSCurve IPv4 Alternate DNS Address = 
DNSCurve IPv6 Main DNS Address = [2620:0:CCC::2]:443
DNSCurve IPv6 Alternate DNS Address = 
DNSCurve IPv4 Main Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv4 Alternate Provider Name = 
DNSCurve IPv6 Main Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv6 Alternate Provider Name = 

[DNSCurve Keys]
DNSCurve Client Public Key = 
DNSCurve Client Secret Key = 
DNSCurve IPv4 Main DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
DNSCurve IPv4 Alternate DNS Public Key = 
DNSCurve IPv6 Main DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
DNSCurve IPv6 Alternate DNS Public Key = 
DNSCurve IPv4 Main DNS Fingerprint = 
DNSCurve IPv4 Alternate DNS Fingerprint = 
DNSCurve IPv6 Main DNS Fingerprint = 
DNSCurve IPv6 Alternate DNS Fingerprint = 

[DNSCurve Magic Number]
DNSCurve IPv4 Main Receive Magic Number = 
DNSCurve IPv4 Alternate Receive Magic Number = 
DNSCurve IPv6 Main Receive Magic Number = 
DNSCurve IPv6 Alternate Receive Magic Number = 
DNSCurve IPv4 Main DNS Magic Number = 
DNSCurve IPv4 Alternate DNS Magic Number = 
DNSCurve IPv6 Main DNS Magic Number = 
DNSCurve IPv6 Alternate DNS Magic Number =

**Comment by chengr28** [comment]
这个理解是正确的，SOCKS 协议的优先级比填入 `[Addresses]` 的高，同时 `SOCKS Proxy Only = 1` 所以会优先 SOCKS 而且不会走普通流程。
```
SOCKS IPv4 Address = 127.0.0.1:1080 <- SOCKS 服务器端地址，本地的也算是服务器端
SOCKS Target Server = 8.8.8.8:53 <- 经过 SOCKS 中转后真正的目标服务器
```
