### ISSUE TITLE
[feature]程序白名单/黑名单

### ISSUE THREAD

**Issue by Riajyuu** [chengr28/Pcap_DNSProxy#386]
即
仅接管指定程序的DNS查询或者仅绕开指定程序的查询

考虑 file picker 或者文件名正则表示

**Comment by SeaHOH** [comment]
DNS 查询属于系统功能，Pcap_DNSProxy 只是个服务器而已，无法修改系统，怕是没法搞。

**Comment by Riajyuu** [comment]
@SeaHOH 您似乎理解错了什么。。。
这个请求只是觉得是否恢复指定程序的默认行为而已

**Comment by SeaHOH** [comment]
建议你搜索下操作系统中域名的解析过程，普通程序的查询是提交给系统 API 的。
真不好搞，Windows 肯定没戏，其它 Linux 估计就要改内核了。

**Comment by chengr28** [comment]
这个 @SeaHOH 的理解是没有问题的，你的意思可能是想实现一些程序的 DNS 不经过本程序之类的功能，但实际上这个功能无法实现。首先正如上面说的本项目只是个（本地）服务器，无论是来自本机还是远程的请求，本项目都无法获取此 DNS 请求是由哪个程序发起的，即使在本机上也没有办法。

一般程序有 3 个方法获取域名解析：
1. 使用操作系统提供的域名解析 API
2. 读取网络适配器的 DNS 设置，然后用网络自己完成解析
3. 完全独立于操作系统之外，自己完成全套工作

绝大部分程序都是用第 1 个方法，这时操作系统的协议栈会完全控制域名解析，那就是把请求发到网络适配器所指定的 DNS 地址，那就是本项目了。所以这个 Issue 想咨询的应该是『如何接管指定程序的 DNS 查询或者仅绕开指定程序的查询，不让他们使用操作系统提供的域名解析 API』，这就不是本项目可以解决的问题了……
