### ISSUE TITLE
关于 HOSTS 规则优化的建议

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#39]
我遇到一个情况，具体情况如下：
root@ubuntu:~/Pcap_DNSProxy/Source/Release# cat Hosts.conf
[Hosts]
x.x.x.1|x.x.x.2|x.x.x.3|x.x.x.4 abc.com
x.x.x.1|x.x.x.2|x.x.x.3|x.x.x.4 def.com
x.x.x.1|x.x.x.2|x.x.x.3|x.x.x.4 sre.com
x.x.x.1|x.x.x.2|x.x.x.3|x.x.x.4 lsp.com
......
......
......
x.x.x.1|x.x.x.2|x.x.x.3|x.x.x.4 xxx.com

[Local Hosts]

[Address Hosts]

也就是说，有很多域名，要指向几台相同的服务器，域名没有什么规律，也用不了正则，所以要写很多相同 IP 的 HOSTS 条目，而且 IP 如果有改变的话，维护也比较麻烦，要一条一条修改。
我现在的想法是，HOSTS 配置规则中右边的域名部分，能不能参考左边的 IP 格式那样，支持多域名条目到相同 IP 的解析，类似下面这样：
root@ubuntu:~/Pcap_DNSProxy/Source/Release# cat Hosts.conf
[Hosts]
x.x.x.1|x.x.x.2|x.x.x.3|x.x.x.4 abc.com|def.com|sre.com|lsp.com|...|xxx.com

[Local Hosts]

[Address Hosts]

这样配置文件简洁，干净，维护也方便很多，只要修改一条记录的 IP，就可以让规则中的所有域名生效。

不知道我的建议是否合理，或者，作者是否有更好的方法解决这个问题。如果能优化这个问题，非常感谢。如果建议不合理，还请作者见谅！

**Comment by chengr28** [comment]
这完全是可以用正则表达式编写的……这里有基本的语法说明 https://zh.wikipedia.org/wiki/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F

你对正则可能了解得不深：
`x.x.x.1|x.x.x.2|x.x.x.3|x.x.x.4 (abc|def|sre|lsp|xxx)\.com`

**Comment by jzp820927** [comment]
感谢作者，确实可行！
