### ISSUE TITLE
新版 dig 带 cookie 字段，Pcap 就没返回了？

### ISSUE THREAD

**Issue by Justsoos** [chengr28/Pcap_DNSProxy#391]
Pcap 最新版本，下载了 Bind 的 windows 64bit 和 32bit ver 9.12.3，这个版本 dig 都遇到一个问题：
用 UDP 方式，查询缓存内没有域名时，大比例 timeout
```
$dig somessss.com @192.168.1.5

; <<>> DiG 9.12.3 <<>> somessss.com @192.168.1.5
;; global options: +cmd
;; connection timed out; no servers could be reached
```
用 +tcp 基本没问题，用其他几个低版本 linux 版本 dig 查，也没问题。
用 wireshark 抓包，发现 Pcap 有向上查询，没有任何返回给客户端的 UDP 包，直接导致 timeout

后来对比了发现只有这里不同，**新版 windows dig 每个查询都多出了 cookie字段，12字节**：
![image](https://user-images.githubusercontent.com/3480043/48883337-50828b00-ee5a-11e8-9d1c-620bb7cff256.png)

同时观察 Pcap 返回给正常能查询到的 dig 信息不包括这个cookie字段。多次试验，只要 Pcap 有查询缓存的，都能正常返回给无论新版还是旧版 dig 客户端。没缓存的，多数都会出这个问题，直到 timeout，Pcan 没有任何 UDP 发包。
同时，所有 +tcp 查询都没问题。

**Comment by Justsoos** [comment]
又反面印证了一下，高版本 `dig +nocookie `命令查询都没有问题了。
centos 和 ubuntu 的多数发行版默认还在 9.9 版本的 dig，还没有这个参数。

**Comment by chengr28** [comment]
新版本的 `dig` 在请求的时候会默认带上 DNS Cookies 这是一个新的特性，现在暂时还没有多少 DNS 服务器支持。导致这个问题的原因是因为程序会对数据包进行比较严格的过滤，如果发出去的请求带有 DNS Cookies 而返回的数据包没有，那么该回应就会被认为是伪造然后被丢弃。这个功能只会在使用抓包模块的时候启用，所以其它例如 Local 或者 TCP 协议的请求不会有问题。

**Comment by Justsoos** [comment]
还有几个逻辑解释不通，应该还是Pcap的问题：
首先，所有新版dig查询pcap无返回（默认三次，间隔五秒），都是pcap缓存内无查询记录的。比如随便敲的，根本没dns记录的 www.goaidhldsjlfljaskdjf.com 这样的域名，或者是缓存过期，pcap 按照反污染规则，去国外查询的被wall域名，比如 m.twitter.com 等等
其次，只要用非新版dig查询过这些域名，在pcap内有缓存了，再用新版dig，带cookie查，都能正确返回。
再次，只要是国内域名，新版dig带cookie查pcap，都能正确返回，跟踪了一下，pcap基本上对国内域名只查一次，对国外被wall和没注册域名，会查多个海外dns。
另外，特意组了局域网而不是127.0.0.1的本地，用wireshark抓了包，以上提到的无返回错误的情况，都不是新版dig丢弃了pcap回来的包，而是pcap根本没有的53端口 dns 包。

**Comment by Justsoos** [comment]
补充，用 opensuse 的高版本 DiG 9.11.2 测试，与 win10 dig 9.12.3 遇到情况完全相同。

**Comment by Justsoos** [comment]
补文件：openSUSE 新版带 cookie 的 DiG 9.11.2 查询无返回的 debug
[new_dig_udp.txt](https://github.com/chengr28/Pcap_DNSProxy/files/2650947/new_dig_udp.txt)

**Comment by chengr28** [comment]
你可能误解我的意思了，这边并没有说这个是正常的，之前只是说明了造成这个问题的原因。至于修复的事情还要考虑一下，因为如果彻底禁用这个检查会对过滤的能力有不小的影响。

**Comment by Justsoos** [comment]
没有误会，只是合并另外一贴 https://github.com/chengr28/Pcap_DNSProxy/issues/395，发现 Pcap 行为很怪异。
实际上，高版本+cookie 引发这个bug，只要收到域名查询请求，进入 Pcap 反污染处理前，直接cut off 掉这个 cookie 字段就可以了，不会影响任何处理流程。
为何会引发 Pcap 对 dig 客户端超时无返回？这应该不是很严重问题啊？

**Comment by chengr28** [comment]
这个抓包模块会丢掉部分带 EDNS 标签解析结果的问题应该已经修复好了，可以拿最新的源代码到 Linux 平台上测试一下，感谢反馈。

**Comment by Justsoos** [comment]
> 这个抓包模块会丢掉部分带 EDNS 标签解析结果的问题应该已经修复好了，可以拿最新的源代码到 Linux 平台上测试一下，感谢反馈。

看来，我传递信息和你反馈，逻辑上还是没对上。哈
用wireshark抓包，发现dig带+cookie的访问到达 Pcap 之后，Pcap 正常向上几个公共DNS发出查询，回包并没有带 cookie 和EDNS的信息。
下面截图是 8.8.4.4 返回左侧是新版默认 +cookie ，右侧是 +nocookie 。

![image](https://user-images.githubusercontent.com/3480043/50056215-293a8780-0194-11e9-9a2f-a12e5554eee6.png)

看你的意思是返回抓包问题。
但我怎么觉得是 Pcap 拒绝服务了呢？

另外，怎么测试？我没有编译环境。也没见你发新的release出来哦

**Comment by chengr28** [comment]
我不是说你的抓包有问题，我是说程序内置的抓包模块的算法有问题，所以才需要升级才能解决。另外关于测试，可以用 Linux 平台编译出来的测也一样，或者等下次版本更新 releases 也行，还有一些问题需要确认，这次没有发。

**Comment by Justsoos** [comment]
嗯，我其实对于这个产品设计的逻辑原理感兴趣，可能还得看源码。
你说的 pcap （从公共 DNS 回包）抓包模块抓到错误返回包，会影响 pcap 对 dig client 的返回，实际上有逻辑不对等：

pcap对+tcp 和 udp 对待dig client查询态度完全不同，前者正常返回，后者完全超时。我给出 wireshark 抓包是为了证明两个事，第一，上游公共DNS回包也是没有+cookie字段的。第二，pcap 对 udp 查询完全不理不睬然后超时，这是一种 “拒绝服务” 逻辑姿态，很怪异。

还有个奇怪的逻辑是，只要pcap有非 +cookie 的客户端查询**国外域名，和不存在域名**缓存后（默认缓存大概不超过60秒），再用 +cookie 的 dig 以udp方式就能获取正常返回。
然后，这个逻辑下，还有延续奇怪逻辑，**只要是国内域名**，比如qq.com，+cookie 的dig udp 方式查询，无论是否有缓存，都能正常返回。

这些应该都在同一群bug体系下。

**Comment by Justsoos** [comment]
如果能加一个开关，可以记录每次pcap 的 dns 查询以及结果，状态到 log ，就方便多了。 最新版 chrome 取消了 dns cache 查看，firefox 没法看

**Comment by chengr28** [comment]
刚才更新了 releases 可以试试。

关于那个详细 log 大概有余力的时候再考虑。

**Comment by Justsoos** [comment]
新版本 +cookie 没问题了。但前两次测，又出现了两个污染返回，等我开了 wireshark ，返回又正常了。真是怪异啊。
![image](https://user-images.githubusercontent.com/3480043/50550335-b78d2e00-0ca9-11e9-901e-7bbc1aa02bac.png)

**Comment by Justsoos** [comment]
正确结果在污染结果后4-6秒钟到达，因此，看起来是超时判断导致pcap选择了污染结果？ 
进一步wireshark发现，就在刚才，我这里 github.com 完全没有正确（无污染）结果返回了。
只有这么多：
![image](https://user-images.githubusercontent.com/3480043/50558786-f82d8b80-0d2b-11e9-927c-414266f2672b.png)
