### ISSUE TITLE
如何用一条命令手动更新 ipv4 ipv6 的大陆IP地址表？

### ISSUE THREAD

**Issue by AxIauk** [chengr28/Pcap_DNSProxy#393]
我使用 路由器里 entware 编译好的Pcap_DNSProxy，因为版本比较老，我想更新更新一下ip表。
网上查到 如下命令，如何修改支持本软件格式，及IPV6？
curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > chnroute.txt

**Comment by SeaHOH** [comment]
https://raw.githubusercontent.com/chengr28/Pcap_DNSProxy/master/Source/Auxiliary/ExampleConfig/Routing.txt

**Comment by chengr28** [comment]
`/Source/Auxiliary/Scripts/Update_Routing.sh` 这个脚本可以更新自带的路由表。
