### ISSUE TITLE
原理、功能：可以用这个方式判断污染域名--又发现一个无解析返回的bug

### ISSUE THREAD

**Issue by Justsoos** [chengr28/Pcap_DNSProxy#395]
https://dnsparanoia.com/
`dig 任意域名 @dnsp.co`
由于这个网站在wall外，必然通过污染网关。
只要返回不是 123.45.67.89 就说明是被污染的。
在本地维护一个确定被污染域名缓存库，是很有意思的一个方向

**Comment by Justsoos** [comment]
哈，不过又因此发现 pcap 一个 bug：
`dig fail.dnsp.co`
使用 pcap 本地查询，无论 +tcp 还是 +nocookie 都是能看到上行dns服务器查询，但客户端无返回的。

![image](https://user-images.githubusercontent.com/3480043/49542669-2d9fae80-f911-11e8-97f4-46939d2041e8.png)


![image](https://user-images.githubusercontent.com/3480043/49542368-61c69f80-f910-11e8-8124-eebd31de9094.png)

**Comment by Justsoos** [comment]
啊，更奇特的 bug，出现了
![image](https://user-images.githubusercontent.com/3480043/49542912-c1717a80-f911-11e8-80de-0e70d3cd9c01.png)

而且，error.log 也出现了时间戳错乱。？
![image](https://user-images.githubusercontent.com/3480043/49543042-19a87c80-f912-11e8-8edf-1f466d3a2bc6.png)

**Comment by Justsoos** [comment]
补充测试截图：
![image](https://user-images.githubusercontent.com/3480043/49543399-1792ed80-f913-11e8-8e1c-83824cfbabed.png)

**Comment by Justsoos** [comment]
附上旧版 DiG 9.10.3-P4-Ubuntu（无 cookie）的debug输出。包括 +tcp 和 udp
[pcap_dig_fail.dnsp.co.txt](https://github.com/chengr28/Pcap_DNSProxy/files/2650838/pcap_dig_fail.dnsp.co.txt)

**Comment by SeaHOH** [comment]
> 哈，不过又因此发现 pcap 一个 bug：
> `dig fail.dnsp.co`
> 使用 pcap 本地查询，无论 +tcp 还是 +nocookie 都是能看到上行dns服务器查询，但客户端无返回的。

```ini
#IPFilter.ini
[Blacklist]
192.0.0.0-192.0.0.255 ALL
```

大概是这个原因。

**Comment by Justsoos** [comment]
@SeaHOH 的确如此，全部中招。UDP 查询无返回，TCP查询出错。
```
# dig rfc5735.freeddns.org +tcp
;; Connection to fec0:0:0:ffff::1#53(fec0:0:0:ffff::1) for rfc5735.freeddns.org failed: connection refused.
;; Connection to fec0:0:0:ffff::2#53(fec0:0:0:ffff::2) for rfc5735.freeddns.org failed: connection refused.
root@iPad:~# dig RFC3068.freeddns.org
# dig RFC3068.freeddns.org +tcp
;; Connection to fec0:0:0:ffff::1#53(fec0:0:0:ffff::1) for RFC3068.freeddns.org failed: connection refused.
;; Connection to fec0:0:0:ffff::2#53(fec0:0:0:ffff::2) for RFC3068.freeddns.org failed: connection refused.
# dig RFC3068.freeddns.org +short @223.5.5.5
192.88.99.1
# dig RFC5735.freeddns.org +short @223.5.5.5
192.0.0.1
```

**Comment by Justsoos** [comment]
建议 Pcap 如果没有特殊需要，还是把上面出错的查询，都改成标准 DNS 返回吧。类似这个，目前返回就是正常的：
```
# dig LOCAL.freeddns.org +short
127.0.0.1
```
毕竟有些人不知道这个问题，开了 pcap，在本地作各种网络测试时候，会掉坑里。
不知道 dynu 能支持静态IP多久，上面都是我刚刚设置的，符合公网域名DNS要求。

**Comment by SeaHOH** [comment]
可能需要按标准做一个特殊的白名单。

**Comment by Justsoos** [comment]
@SeaHOH 这些域名其实都来自你提到的 `IPFilter.ini` 的 `[Blacklist]`，估计是 Pcap 的代码逻辑处理问题，这些保留 IP 只要被处理流程发现就会引发 黑名单 出错，实际上，应该按标准 DNS 服务器返回给客户端来处理。保留 IP 都是用来作本地和特殊应用的，不应该如此处置。

**Comment by SeaHOH** [comment]
问题是保留地址有可能被拿来作为污染地址，实际上也这么做了。
所以需要根据标准做个特殊的白名单。

**Comment by Justsoos** [comment]
污染地址，无论是否是保留地址，应该由Pcap内部处理逻辑解决，而不应该表现为查询的UDP超时，TCP连接出错，DNS 对保留地址，以及未知的处理方式，这些错误返回，会影响很多软件。包括，在这里还发现了带 +cookie 查询，就会无返回的bug
https://github.com/chengr28/Pcap_DNSProxy/issues/391

**Comment by SeaHOH** [comment]
好吧，我记得 28小盆友说过，现在的处理不是很依赖黑名单，你可以试试去掉默认黑名单来测试。

**Comment by Justsoos** [comment]
IPFilter.ini 文件改名或删除后，问题解决了。

```
# dig local.freeddns.org +short
127.0.0.1

# dig rfc5735.freeddns.org +short
192.0.0.1

# dig rfc3068.freeddns.org +short
192.88.99.1
```

**Comment by Justsoos** [comment]
另外，这个列表里，可能带来规则问题。
https://zh.wikipedia.org/wiki/%E5%9F%9F%E5%90%8D%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%BC%93%E5%AD%98%E6%B1%A1%E6%9F%93

譬如，google 域名经常会被污染到 `31.13.65.18`
但，这个 IP 并不是随便一个无效 IP，它是 facebook 使用的：
```
31.13.65.18
{
  "code": 0,
  "data": {
    "ip": "31.13.65.18",
    "country": "美国",
    "area": "",
    "region": "佐治亚",
    "city": "亚特兰大",
    "county": "XX",
    "isp": "脸书",
    "country_id": "US",
    "area_id": "",
    "region_id": "US_110",
    "city_id": "US_1053",
    "county_id": "xx",
    "isp_id": "2000262"
  }
}
```

**Comment by SeaHOH** [comment]
本来大多数污染结果就不是无效 IP。
我说的测试还包括测试反污染，在不使用黑名单的情况下能否正常工作。

**Comment by chengr28** [comment]
看起来这里一下子提到了不少疑问：

1. 本工具应该不会依靠任何固定的服务实现基础功能，例如之前有人说提到加上在线更新的功能，以及这次说依靠某个 DNS 服务器做鉴定，或许以后有机会可以尝试一下。而且这个污染域名缓存库实际上并没有很大的用处，本工具是尽力提供正确的解析结果，就算得知某个域名被投毒污染，没有方法获得真正的结果也没什么作用，实际上以现在的条件不依靠这个特殊的 DNS 服务器也能做到。

**Comment by chengr28** [comment]
2. 不太清楚你所说的『代码逻辑处理问题』指的是什么，这个地址是在 IP 地址黑名单里，现在的处理方法就是只要发现解析结果里有就会被标记上伪造数据包直接丢弃，对外的表现当然就是超时响应了，因为压根就不可能会有响应。你总是说这个流程有问题，对于一些域名的解析可能的确会造成问题，但就像 @SeaHOH 所说，首先这些地址都是特殊用途，不太应该放到域名解析里，其次就是你没法判断一个域名的解析结果真的是这些地址还是伪造的，事实上他们的确这样做过。这是一个取舍的问题，如果按标准 DNS 服务器那样返回给请求者，那么使用本工具的意义何在？

**Comment by chengr28** [comment]
3. 关于使用 Facebook 真实 IP 地址投毒污染的问题和上面说的一样，是一个过滤取舍的问题。这边现在也把整个黑名单放到文本文件里了，可以用正则表达式直接把一些域名排除掉，或者干脆直接把整个黑名单删掉。虽然现在因为策略升级黑名单的作用是下降了，不过是对过滤有正面帮助的，所以也会一直保留到适当的时机再决定处理方法。

**Comment by Justsoos** [comment]
由于以下一些考虑：
第一，对Pcap的核心标准要求，是本地 DNS 代理，或者说，就是本地 DNS。像本贴讨论的 保留地址，其实对很多网络程序是相当重要的。越能模仿一个正常 DNS 公网服务器给出返回越合格。
这是基本出发点。DNS 实际是网络访问最重要的一个部分。

第二，目前Pcap给出的以第一基本要求来看显得 “怪异” 行为看，本贴内提到，多数和这个 IPFilter.ini 的 [Blacklist] 有关，而【代码逻辑处理问题】即，facebook 的 这个 IP 31.13.65.18 本身是无错的，如果确定某 facebook 域名解析出这个 IP，Pcap 的逻辑将导致这个正确查询是否出错呢？

其实这个IP当时举例不太好，因为它虽然目前在 wikipedia 的列表里，但并不在 Pcap 的黑名单里，这里就看出这个网站 https://dnsparanoia.com/ 对基本逻辑严格化启发非常有帮助，找到另一个 IP：

` dig 37.61.54.158.spec.dnsp.co` 这个域名，返回就是前缀的 IP  `37.61.54.158 ` 这个 IP 就在 Pcap 黑名单里。上面这个 dig 命令会导致 Pcap UDP查询超时无返回出错，+TCP 会出现如下拒绝连接的错误。
```
# dig 37.61.54.158.spec.dnsp.co +tcp
;; Connection to fec0:0:0:ffff::1#53(fec0:0:0:ffff::1) for 37.61.54.158.spec.dnsp.co failed: connection refused.
;; Connection to fec0:0:0:ffff::2#53(fec0:0:0:ffff::2) for 37.61.54.158.spec.dnsp.co failed: connection refused.
```
而这个出错，和 https://github.com/chengr28/Pcap_DNSProxy/issues/391 提到的出错**行为**是极其类似的，相当于 Pcap 强硬的拒绝了客户端查询的返回，而不是标准DNS应该有的返回行为，在 Pcap 错误日志里也没有任何表示，这说明 Pcap 没有将此认定为程序错误。

这个行为首先来说，这不是正常 DNS 应该有的行为，尤其是 污染常用 wikipedia 列表（小数量）和保留地址（大数量）都被放在 `IPFilter.ini ` 文件内情况下，对符合诸多 RFC 标准的查询，Pcap 目前都没有正确返回，而实际上，很多用来作程序开发的程序员对此并不知情，这容易导致相当多严重逻辑误判问题。

其次，表明 Pcap 对这些 IP 处理并没有考虑**如果确实是一个正确 域名 指向情况下**的代码对 IP 背后 domain name 误杀问题。这不是对投毒过的 domain name 查询的反污染处理，反而是对查询之后 IP 独立进行黑名单，这是 Pcap 对自身功能定位逻辑过于简单化的出错了。

说句题外话，我本想去 dynu 去注册个主机名，指向任何 `IPFilter.ini` 里黑名单的 IP 地址任何一个，都会引发 Pcap 出错。但这个网站 https://dnsparanoia.com/ 的确很有意思，把大量 dns 上经常出现的问题都考虑到了。这个`.spec.dnsp.co ` 就非常方便，可以返回任何 IP 地址指向，用来测试。

第三，通过对 Pcap 的研究，发现工作原理，本贴最早一贴其实是个抛砖引玉，鉴于目前 Pcap 的原理，使用的是类似西厢计划的先返回 DNS 包A是污染的，后返回B，C是正确的。 -- 这是个 `与时俱进` 的原理，一旦未来某 wall 确定 drop 掉A，只返回污染的C 呢？我觉得，这个只返回 123.45.67.89 ，建立在海外的伪 DNS，是个非常有意义的用来查询、建立污染域名库的手段。可以内置在 Pcap 里，甚至可以独立成产品。

**Comment by Justsoos** [comment]
另外，还发现一个现象，可以作为升级策略，或者定制新产品。
wall 对 非标准 53 和 5353 端口的 DNS 查询，其实并不会搞污染。
比如，你可以试试：
`dig www.google.com @dnsp.co -p 10053`

**Comment by Justsoos** [comment]
附带说这个逻辑问题，可能是现在 Pcap 两难地方，为什么抛弃这些 IP 的dns查询，因为这些 “未污染域名” 查询回来的 IP，从
```
114.114.114.114
9.9.9.9
1.0.0.1
8.8.8.8
```
的（西厢计划原理下）“多个” 返回值是一致的？或者， Pcap 在得到第一个返回包（被默认为污染包）后，等待后续（未污染查询包）导致了超时和内置逻辑判断错误，这策略导致 Pcap 无法确定首先受到的包是否是污染，发生了宁可错杀1000，不可放过1个的策略，也就是本贴说的 Pcap 的逻辑判断流程问题吧。

**Comment by Justsoos** [comment]
又发现一个可能是 Pcap 处理逻辑问题：
```
# dig www.google.com.qq.com +short
31.13.80.1
```
这个查询直接返回了污染后的著名的那个 FaceBook 的 IP
但实际上，正确公网dns应该给出的是无返回记录。

**Comment by Justsoos** [comment]
进一步测试，本来应该可以返回 0.0.0.0 的正确结果（黄色部分），但没有被 Pcap 采信。
命令为： `dig www.google.com.spec.dnsp.co`
实测 Pcap 无返回超时。

![image](https://user-images.githubusercontent.com/3480043/49611111-889dd800-f9db-11e8-8b8b-42c1fc44e5c6.png)

**Comment by SeaHOH** [comment]
污染域名库已经说得很明白了，就是个取舍问题，添加一句说明告知应该就没问题了，不需要就自己拿掉，专门弄个特殊白名单确实比较蛋疼。
至于推荐的这个特殊 DNS 获取污染域名，实在是没必要，手段不要太多，墙又不防这个。
 
> 又发现一个可能是 Pcap 处理逻辑问题：
> 
> ```
> # dig www.google.com.qq.com +short
> 31.13.80.1
> ```
> 
> 这个查询直接返回了污染后的著名的那个 FaceBook 的 IP
> 但实际上，正确公网dns应该给出的是无返回记录。

我猜你大概是这么配置的：
```ini
Local Hosts = 1
Local Routing = 1
Local Force Request = 1
EDNS Label = 0
```
同时命中了 Local 和墙单，这不是一个正常的域名，`EDNS Label = 1`时会判断被污染（但这个增强特性似乎处理有误，见 https://github.com/chengr28/Pcap_DNSProxy/issues/387#issuecomment-445059939 ）。

> 进一步测试，本来应该可以返回 0.0.0.0 的正确结果（黄色部分），但没有被 Pcap 采信。

同上，去掉黑名单就行。

另外，那个不污染非标准端口的现状倒是可以利用，建成转发服务器看起来比较简单实用。

**Comment by Justsoos** [comment]
下载后运行，并没有改配置：
```
Local Protocol = IPv4 + UDP
Local Hosts = 0
Local Routing = 1
Local Force Request = 0
EDNS Label = 0
```
实际上，本贴讨论明白一个逻辑问题：IP 有罪（在黑名单），并不意味着域名有罪（应该给出正确解析），尤其是对于保留地址，这个判断逻辑搞反了，而且查询无返回，太粗暴了。

**Comment by SeaHOH** [comment]
保留地址的问题上面已经重复了好几遍：不要使用黑名单。

上面这个问题又测了几个不同配置，好像是有点问题。
![es](https://user-images.githubusercontent.com/8470820/49637826-7060a400-fa41-11e8-96a6-fe34e929fc34.png)

**Comment by SeaHOH** [comment]
保留地址的问题上面已经重复了好几遍：不要使用黑名单。

上面这个问题又测了几个不同配置，好像是有点问题。
![es](https://user-images.githubusercontent.com/8470820/49638292-b79b6480-fa42-11e8-94ef-7ff462393f80.png)

**Comment by Justsoos** [comment]
哈，你也中招了。 @SeaHOH  Pcap 还有个bug，是已经缓存的域名与非缓存域名，dig 出来行为也不同。我在另外 issues https://github.com/chengr28/Pcap_DNSProxy/issues/391 里面反复测，非常令人诧异，非 +cookie 版本dig才能产生 “有效缓存”，而且国内域名与国外域名，包括无注册，无IP指向的域名，策略都有不同。DNS 真是个非常复杂的大杂烩系统。
另外，不要再用 nslookup 了，有设计 bug，最好还是用 dig。

**Comment by SeaHOH** [comment]
> Pcap 还有个bug，是已经缓存的域名与非缓存域名，dig 出来行为也不同。

我觉得这主要是因为上游 DNS 有多个，同时网络状况是一直在变化的。
你隔段时间（即非短时间内） dig 同一个非缓存域名，其行为也应该有变化。
为了处理污染，不得不把一个简单的过程搞得很复杂，毕竟这不是个单纯的 DNS 服务器。

>另外，不要再用 nslookup 了，有设计 bug，最好还是用 dig。

懒得安装 BIND，一大包东西，我平常又用不着。
抓包我都少有用，过滤规则写得真是难受。。。

**Comment by Justsoos** [comment]
开 wireshark 非常简单，过滤里敲三个字母 dns 回车就行了。
不开抓包，你看不到真实过程。 +cookie 的 dig 查询，实际上 Pcap 也是上行公共 DNS 查询了的，这是判定 Pcap 存在 bug 的关键。

win10 里实际不需要装bind dig，装 wsl  bind-dnsutils 以及增强版 knot-dnsutils 非常方便。
ubuntu 18.04 里普遍升级 DiG 9.11，普遍带+cookie 查询了。Pcap 会遇到越来越多 bug 报告的，只不过很多小白用户不晓得怎么回事吧。

实际上，这里讨论的，其实是 gfw 的规则。比如 www.google.com.qq.com 这种三级域名被 dns 层面封，显然是有很多人用来作方便的google转发代理。 www.twitter.com.baidu.com 就没被封。这些都是复杂规则，pcap 这么多小 bug 来历，就在于对这些复杂规则考虑不到那么细致。

**Comment by chengr28** [comment]
这个这边记录一下吧，感觉很多奇奇怪怪的问题……

**Comment by tec1987** [comment]
抱歉挖个坟，@Justsoos  pcapdns的最初设计原理就是用各种办法过滤掉被GFW污染的DNS包，这种过滤或多或少会因为一些域名规则及DNS的复杂性产生各种问题。。。

www.google.com.qq.com，这个域名，我认为是：8.8.8.8向qq.com查询子域名www.google.com时，qq.com将缓存中被污染的数据应答给了4个8，从往返时间来判断，第三个包确定是从4个8传回来的。。。
我把qq换成taobao再次查询，同样是3个错误应答，经过几次查询后，taobao这面可能刷新了缓存，返回了其它结果。

鉴于传统DNS的工作机制，在不使用加密和代理的情况下，很难做到十分有效的过滤和防止污染。

**Comment by tec1987** [comment]
天朝的DNS污染已经通过腾讯泛滥到全世界，这个锅谁来背？
![mmexport1566479314044](https://user-images.githubusercontent.com/23297763/63517651-efd7ca00-c521-11e9-8ca0-9149cf19980e.png)
