### ISSUE TITLE
NOERROR但是解析为空

### ISSUE THREAD

**Issue by iamsurfing** [chengr28/Pcap_DNSProxy#396]
win10 
4.9.11 pcap

之前有这么一段时间，能上网但是上不了百度，我以为百度抽风了，后来dig一下pcap发现状态显示NOERROR，但是ip地址的位置是空的。就上不了网了。
后来发现是百度的dns出问题了。
我不知道怎么复现。但是记忆中大概就是这样。
就是希望pcap如果以后咨询dns的时候，只要结果是空的而且NOERROR就直接过滤。

类似这样
$ dig dropbox.com MX @127.0.0.1

; <<>> DiG 9.11.2-P1 <<>> dropbox.com MX @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49482
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dropbox.com.                   IN      MX

;; Query time: 217 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: 周六 12月 15 00:11:10 CST 2018
;; MSG SIZE  rcvd: 40

**Comment by chengr28** [comment]
这个其实不是很好……因为这个属于上游的 DNS 服务器配置问题，并不是这个解析结果有问题，也有可能域名的管理员就真的配置成这样，所以不能当成虚假的结果直接丢弃掉的……

**Comment by iamsurfing** [comment]
@chengr28 
不可能的，没有dns会配置成这样的。
NOERROR就意味着一定有对应结果，出错的话status会写对应错误的。
“域名的管理员配置成这样”，能不能举例？

117.50.22.22和117.50.11.11就是这样。早先联通的116dns咨询AAAA时也是这样。
正常的dns的status会显示SERVFAIL，只有不负责任的才会显示NOERROR。
所以希望把SERVFAIL结果和NOERROR但是无结果的回应过滤。
过滤是说用其他的国内dns，而不是说国内dns被污染换国外dns。
（但实际上就是污染的。）

$ dig dropbox.com MX @117.50.22.22
;; BADCOOKIE, retrying.

; <<>> DiG 9.11.2-P1 <<>> dropbox.com MX @117.50.22.22
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42581
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 5c468aae1c0f940d7cbaeee75c1672e4e14e69dddbfda5d8 (good)
;; QUESTION SECTION:
;dropbox.com.                   IN      MX

;; Query time: 103 msec
;; SERVER: 117.50.22.22#53(117.50.22.22)
;; WHEN: 周日 12月 16 23:44:38 CST 2018
;; MSG SIZE  rcvd: 68

$ dig dropbox.com MX @223.5.5.5

; <<>> DiG 9.11.2-P1 <<>> dropbox.com MX @223.5.5.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 45528
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dropbox.com.                   IN      MX

;; Query time: 1988 msec
;; SERVER: 223.5.5.5#53(223.5.5.5)
;; WHEN: 周日 12月 16 23:44:15 CST 2018
;; MSG SIZE  rcvd: 29

**Comment by SeaHOH** [comment]
不知道这样算不算
```
<DNS Header: id=0xd802 type=RESPONSE opcode=QUERY flags=RD,RA rcode='NOERROR' q=1 a=2 ns=0 ar=0>
<DNS Question: 'www.cnbeta.com.' qtype=AAAA qclass=IN>
<DNS RR: 'www.cnbeta.com.' rtype=CNAME rclass=IN ttl=4 rdata='f9feedcf.cnbeta.com.cdn.dnsv1.com.'>
<DNS RR: 'f9feedcf.cnbeta.com.cdn.dnsv1.com.' rtype=CNAME rclass=IN ttl=4 rdata='706.dispatch.spcdntip.com.'>
```

**Comment by iamsurfing** [comment]
而且我再问一下，如果NOERROR而且结果是空的，那么是如何判断ip是国内的还是国外的，还是直接内存泄漏？

**Comment by chengr28** [comment]
NOERROR 但是无结果这个可以作为特殊环境下产生的问题进行过滤，不过 SERVFAIL 能不能也作为过滤选项有保留。刚才说有些域名配置错误有可能会造成问题，这个 SERVFAIL 就是其中之一，当然没有做过实际的部署不清楚怎么样才能达成条件，但是如果 SERVFAIL 造成的问题这边做了过滤，就相当于把本身不属于程序的问题硬扛下来，这样其实不是一个很好的解决方法。

**Comment by chengr28** [comment]
> 如果NOERROR而且结果是空的，那么是如何判断ip是国内的还是国外的

按照现在 Local 请求的流程，在启用路由表的情况下，只要解析结果里的 IP 地址不在路由表中就会直接丢弃并进入下一步的操作，结果为空相当于没有命中。至于前面说没有命中再请求其它 Local DNS 服务器的问题，以现在的架构来看是无法实现的，以后如果有类似现在并行 Local DNS 请求的功能，这样的流程应该就可以实现。
