### ISSUE TITLE
Pcap_DNSProxy 启动服务失败

### ISSUE THREAD

**Issue by krollMJ** [chengr28/Pcap_DNSProxy#398]
﻿### Version/使用的版本/使用的版本

Pcap_DNSProxy-0.4.9.12-bin\Pcap_DNSProxy-bin\Windows

Windows 10 64bit

Pcap_DNSProxy 手动启动服务失败

Error.log
[2018-12-21 12:27:12] -> [Notice] Pcap_DNSProxy started.
[2018-12-21 12:27:13] -> [Network Error] Bind UDP Monitor socket error: Only one usage of each socket address (protocol/network address/port) is normally permitted[10048].
[2018-12-21 12:35:55] -> [Notice] Pcap_DNSProxy started.
[2018-12-21 12:35:56] -> [Network Error] Bind UDP Monitor socket error: Only one usage of each socket address (protocol/network address/port) is normally permitted[10048].

![pcap_dnsproxy -001](https://user-images.githubusercontent.com/28785430/50325290-ee7f7900-051e-11e9-9b10-b38ce02ba1ec.JPG)

**Comment by krollMJ** [comment]
![pcap_dnsproxy -002](https://user-images.githubusercontent.com/28785430/50325331-2686bc00-051f-11e9-8c8f-c514b19b4ad0.JPG)

**Comment by Stzx** [comment]
#320

**Comment by Allentong61** [comment]
据我所知是windows系统服务引起的，ShardAccess这个服务自动重启并绑定UDP53号端口。可是我试过在组策略禁用，似乎还是会自动启动。

**Comment by krollMJ** [comment]
都已经到Win10了，瘟到死的系统管理还是如此蛋痛。
几千个可用端口，干嘛都去抢53端口？
端口被占用，为啥不直接提示被占用？被谁占用？映射到一个新端口有多难？

**Comment by AnyWAT** [comment]
😂貌似LS无理要求　https://github.com/chengr28/Pcap_DNSProxy/issues/384#issuecomment-433696909

**Comment by krollMJ** [comment]
> 😂LS貌似无理要求 [#384 (comment)](https://github.com/chengr28/Pcap_DNSProxy/issues/384#issuecomment-433696909)

什么叫无理要求啊？啥叫【人工智能】？不就是，自动发现问题，自动解决问题。
即使无法自动解决问题，好歹给个靠谱的提示吧。
一句“服务未经使用，启动后停止”，我咋知道说的啥？

即使53端口作为DNS专用端口，在一对一需求的单机上，也不存在自动映射到一个新端口，发生解析错误的问题。
就好比自己家的东西，即使没有放在固定的地方，也不可能找不到一样。

**Comment by AnyWAT** [comment]
😭代码老白不懂 @chengr28

**Comment by chengr28** [comment]
> The program is not running, please check the configurations and error log.

> [Network Error] Bind UDP Monitor socket error: Only one usage of each socket address (protocol/network address/port) is normally permitted[10048].

DNS 服务只能用 53 端口，其它端口监听了没用。
要想 DNS 使用其它端口需要修改系统配置，系统环境千差万别，这种行为不应由本程序完成。
上面冒号之后由系统提供，程序只是代为报告，系统没有提供的信息查不到。
对错误的描述有疑问的请联系软件提供商。
