### ISSUE TITLE
Linux 版本的守護進程無法啓動。

### ISSUE THREAD

**Issue by otakuchiyan** [chengr28/Pcap_DNSProxy#4]
https://github.com/otakuchiyan/pcap_dnsproxy 這是我修改過 Makefile 的版本。原版是沒法編譯通過的。
服務已註冊，也可以啓動服務腳本，但是二進制文件卻無法啓動。
沒有 Error.log 輸出。當前目錄放置有從 Example 複製出來的 Config.conf 。

**Comment by chengr28** [comment]
刚才同步更新了 0.4 的 Linux 版，迟到了一年多真是不好意思……
