### ISSUE TITLE
关于ServiceControl.bat

### ISSUE THREAD

**Issue by 5sq** [chengr28/Pcap_DNSProxy#40]
ServiceControl.bat中的“ Get Administrator Privileges”在一些机器会出现死循环。

主要是这
>nul 2>&1 "%SystemRoot%\system32\cacls.exe" "%SystemRoot%\system32\config\system"

**Comment by wongsyrone** [comment]
对于win7及以上，检测管理员可以使用
```batch
setlocal ENABLEDELAYEDEXPANSION
bcdedit >nul 2>&1
echo !errorlevel!
endlocal
pause & break
```
对于xp，bcdedit换成fsutil。

在我这win 8.1 x64测试

> nul 2>&1 "%SystemRoot%\system32\cacls.exe" "%SystemRoot%\system32\config\system" 

的返回值全是0

**Comment by 5sq** [comment]
建议删除Get Administrator Privileges部分

**Comment by chengr28** [comment]
获取管理员权限这部分不能删除……之前没有强制获取管理员权限的时候，因为普通权限是不能进行服务的安装以及程序的运行，造成控制台窗口生成了比较多的错误消息，同时一部分用户没有认真查看文档的说明，然后一直由早到晚……所以这步就帮他们做了

**Comment by 5sq** [comment]
可能需要用“ver”命令判断win的版本，再用相关命令来判断是否是管理员权限。不然会出现errorlevel值全是0的情况（死循环）。

**Comment by chengr28** [comment]
这几天认真想了下……这个果然还是有点太危险了。之前有碰到过无限弹窗的情况 =_/=
还是加个提示写到说明文档然后去掉这部分的代码让用户自己来算了……

**Comment by chengr28** [comment]
刚才更新的版本去掉了管理员权限检测的部分……感谢反馈w

**Comment by 5sq** [comment]
应该谢谢你给大家带来的福利。

2015-07-09 0:21 GMT+08:00 chengr28 <notifications@github.com>:

> 刚才更新的版本去掉了管理员权限检测的部分……感谢反馈w
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chengr28/Pcap_DNSProxy/issues/40#issuecomment-119647293>
> .
>



-- 
⊙蜀国人⊙伍零厚⊙老宅男⊙好奇种⊙有老婆⊙尚微勃⊙老房子⊙旧车子⊙歪文凭
