### ISSUE TITLE
请问能否将上游DNS服务器动态配置成与主机DNS服务器一致呢

### ISSUE THREAD

**Issue by Jackie-Yang** [chengr28/Pcap_DNSProxy#402]
﻿### Version/使用的版本/使用的版本

### Running Environment/运行环境/運行環境

Win10

### Expectation/期望情况/期望情況

在一些内网应用场景下，DNS服务器需要配置成内网的DNS服务器

### Actual/实际情况/實際情況

上游DNS服务器只能固定配置，请问能否动态配置成与主机DNS服务器一致呢

**Comment by chengr28** [comment]
为什么上游 DNS 服务器的地址会经常发生变化？

**Comment by chengr28** [comment]
这个其实不应该由程序完成，而是可以编写类似脚本的东西，根据系统拿到的配置生成程序的配置文件。

**Comment by Jackie-Yang** [comment]
@chengr28 是的，目前也打算通过这个思路去解决，只是想先请教下目前有没有可实现的方法，谢啦

**Comment by Jackie-Yang** [comment]
@chengr28 顺便想请教下，Windows是用VS编译吗？编译发现缺少libevent这些依赖，这个需要配置些什么吗？

**Comment by chengr28** [comment]
libevent 这个是依赖库，编译出来的静态链接库按照 VS 中的结构放到对应的位置就行。
