### ISSUE TITLE
服务等一起工作安装成功，还是无法科学上网

### ISSUE THREAD

**Issue by anlexN** [chengr28/Pcap_DNSProxy#404]
﻿### Version/使用的版本/使用的版本

0.4.9.13

### Running Environment/运行环境/運行環境

windows 10 pro

### Expectation/期望情况/期望情況

ping google.com **成功""
网页能够浏览google

### Actual/实际情况/實際情況

ping google.com "失败“

网页无法浏览google

**Comment by zanewayne78** [comment]
？？？
这只是个DNS，不是代理

**Comment by chengr28** [comment]
> Pcap_DNSProxy 是一个基于 WinPcap/LibPcap 用于过滤 DNS 投毒污染的工具

本功能没有你想象中的那种功能。

**Comment by anlexN** [comment]
@chinaniupai , 您怎么翻墙？

**Comment by chinaniupai** [comment]
@anlexN 当然是代理服务器
