### ISSUE TITLE
请教怎么配置cloudflare的dnscrypt?

### ISSUE THREAD

**Issue by blog2i2j** [chengr28/Pcap_DNSProxy#407]
﻿### Version/使用的版本/使用的版本
0.4.9.13

### Expectation/期望情况/期望情況

我使用dnscurve=1,Encryption=1, DNSCurve IPv4 Main DNS Address = 1.1.1.1:853, 就出现无法解析.
能否请教一下这个怎么设置? 谢谢了

**Comment by chengr28** [comment]
853 端口那个是 DNS over TLS 不是 DNSCrypt 暂时还在计划中 https://github.com/chengr28/Pcap_DNSProxy/issues/207

**Comment by blog2i2j** [comment]
明白了, 谢谢
