### ISSUE TITLE
日志不停出现[Pcap Error] vlan3: That device is not up

### ISSUE THREAD

**Issue by wangmice** [chengr28/Pcap_DNSProxy#409]
﻿### Version/使用的版本/使用的版本
0.4.9.13

### Running Environment/运行环境/運行環境
tomato arm7 gcc7.3 glibc 2.23

### Expectation/期望情况/期望情況
消除错误

### Actual/实际情况/實際情況
日志里一直不停地出现：
[2019-02-07 05:01:11] -> [Pcap Error] vlan3: That device is not up
……………………
大概1分钟左右一次增加一条，日志文件不停增长。
vlan3 确实是不存在的 （ifconfig 时不显示，但ifconfig -a 时确实是存在的接口）

**Comment by chengr28** [comment]
这个应该是抓包模块传回来的错误，配置文件里有个参数 `Pcap Devices Blacklist` 可以把 `vlan` 加进去，重启服务之后应该就不会再报告了。

**Comment by wangmice** [comment]
谢谢了。
