### ISSUE TITLE
添加学校局域网DNS地址后不能启动

### ISSUE THREAD

**Issue by matthew728960** [chengr28/Pcap_DNSProxy#41]
无论哪个均不能启动
IPv4 Local  DNS Address = 8.8.4.4:53|192.168.0.11:53
IPv4 Local Alternate DNS Address = 223.6.6.6:53|192.168.0.11:53

**Comment by wongsyrone** [comment]
试试仅指定一个ip，看参数说明的时候这两项没说可以多个服务器啊

**Comment by chengr28** [comment]
正如楼上所说，只有 IPv4/IPv6 Listen Address 和 IPv4/IPv6 (Alternate) DNS Address 支持多线程请求，其它服务器都是主要备份服务器这样单线程的

**Comment by matthew728960** [comment]
我只在IPv4 Local Alternate DNS Address 加了 192.168.0.11:53 就不能启动了，而且帖子是在表达两种情况均不能启动。
但已经直接添加到系统设置里了
需要学校的DNS是因为，每天早上需要登录天翼校园网。

**Comment by chengr28** [comment]
希望能提供修改过的整个配置文件内容
或者看看有没有 Error.log

**Comment by matthew728960** [comment]
[Base]
Version = 0.4
File Refresh Time = 10
Buffer Queue Limits = 64
Queue Limits Reset Time = 0
Additional Path = 
Hosts File Name = Hosts.ini|Hosts.conf|Hosts|Hosts.txt|Hosts.csv|WhiteList.txt|White_List.txt
IPFilter File Name = IPFilter.ini|IPFilter.conf|IPFilter.dat|IPFilter.csv|IPFilter|Guarding.p2p|Guarding|Routing.txt|chnrouting.txt|chnroute.txt

[Log]
Print Error = 1
Log Maximum Size = 8MB

[DNS]
Protocol = IPv4 + UDP
Hosts Only = 0
Local Main = 0
Local Hosts = 0
Local Routing = 0
Cache Type = Queue
Cache Parameter = 128
Default TTL = 900

[Listen]
Pcap Capture = 1
Pcap Reading Timeout = 200
Listen Protocol = IPv6 + IPv4 + TCP + UDP
Listen Port = 53
Operation Mode = Private
IPFilter Type = Deny
IPFilter Level < 
Accept Type = 

[Addresses]
IPv4 Listen Address = 
IPv4 EDNS Client Subnet Address = 
IPv4 DNS Address = 8.8.4.4:53
IPv4 Alternate DNS Address = 8.8.8.8:53|208.67.220.220:443|208.67.222.222:5353
IPv4 Local DNS Address = 114.114.115.115:53
IPv4 Local Alternate DNS Address = 223.6.6.6:53|192.168.0.11:443
IPv6 Listen Address = 
IPv6 EDNS Client Subnet Address = 
IPv6 DNS Address = [2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = [2001:4860:4860::8888]:53|[2620:0:CCD::2]:443|[2620:0:CCC::2]:5353
IPv6 Local DNS Address = 
IPv6 Local Alternate DNS Address = 

[Values]
EDNS Payload Size = 
IPv4 TTL = 0
IPv6 Hop Limits = 0
IPv4 Alternate TTL = 0
IPv6 Alternate Hop Limits = 0
Hop Limits Fluctuation = 2
Reliable Socket Timeout = 5000
Unreliable Socket Timeout = 3000
Receive Waiting = 0
ICMP Test = 900
Domain Test = 900
Alternate Times = 10
Alternate Time Range = 60
Alternate Reset Time = 300
Multi Request Times = 0

[Switches]
TCP Fast Open = 0
Domain Case Conversion = 1
Compression Pointer Mutation = 0
EDNS Label = 0
EDNS Client Subnet = 0
DNSSEC Request = 0
DNSSEC Validation = 0
DNSSEC Force Validation = 0
Alternate Multi Request = 0
IPv4 Data Filter = 0
TCP Data Filter = 1
DNS Data Filter = 1
Blacklist Filter = 1

[Data]
ICMP ID = 
ICMP Sequence = 
ICMP PaddingData = 
Domain Test ID = 
Domain Test Data = 
Localhost Server Name = 

[DNSCurve]
DNSCurve = 0
DNSCurve Protocol = UDP
DNSCurve Payload Size = 
Encryption = 1
Encryption Only = 0
Key Recheck Time = 3600

[DNSCurve Addresses]
DNSCurve IPv4 DNS Address = 208.67.220.220:443
DNSCurve IPv4 Alternate DNS Address = 208.67.222.222:443
DNSCurve IPv6 DNS Address = [2620:0:CCD::2]:443
DNSCurve IPv6 Alternate DNS Address = [2620:0:CCC::2]:443
DNSCurve IPv4 Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv4 Alternate Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv6 Provider Name = 2.dnscrypt-cert.opendns.com
DNSCurve IPv6 Alternate Provider Name = 2.dnscrypt-cert.opendns.com

[DNSCurve Keys]
Client Public Key = 
Client Secret Key = 
IPv4 DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
IPv4 Alternate DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
IPv6 DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
IPv6 Alternate DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
IPv4 DNS Fingerprint = 
## IPv4 DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007
IPv4 Alternate DNS Fingerprint = 
## IPv4 Alternate DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007
IPv6 DNS Fingerprint = 
## IPv6 DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007
IPv6 Alternate DNS Fingerprint = 
## IPv6 Alternate DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007

[DNSCurve Magic Number]
IPv4 Receive Magic Number = 
IPv4 Alternate Receive Magic Number = 
IPv6 Receive Magic Number = 
IPv6 Alternate Receive Magic Number = 
IPv4 DNS Magic Number = 
## IPv4 DNS Magic Number = qe47QHHw
IPv4 Alternate DNS Magic Number = 
## IPv4 Alternate DNS Magic Number = qe47QHHw
IPv6 DNS Magic Number = 
## IPv6 DNS Magic Number = qe47QHHw
IPv6 Alternate DNS Magic Number = 
## IPv6 Alternate DNS Magic Number = qe47QHHw

**Comment by matthew728960** [comment]
2015-07-01 14:11:07 -> Log opened at this moment.
2015-07-01 14:11:07 -> Parameter Error: Data length error in line 40 of D:\Online\PCAP_D~1\Windows\Config.ini.

**Comment by matthew728960** [comment]
[SC] startservice

**Comment by chengr28** [comment]
刚开始两层楼就说了 `只有 IPv4/IPv6 Listen Address 和 IPv4/IPv6 (Alternate) DNS Address 可以支持指定多个服务器` 其它参数都是不支持的

提供的配置文件里：
`IPv4 Local Alternate DNS Address = 223.6.6.6:53|192.168.0.11:53`
这样写意思就是多个服务器……
然而 Local 系列的参数都不支持，那自然就报错了。直接把自带的换掉就没事了：
`IPv4 Local Alternate DNS Address = 192.168.0.11:53` 或者 `IPv4 Local DNS Address = 192.168.0.11:53`

**Comment by wongsyrone** [comment]
建议在参数说明中把`只有 IPv4/IPv6 Listen Address 和 IPv4/IPv6 (Alternate) DNS Address 可以支持指定多个服务器`用Markdown标记粗体

**Comment by 5sq** [comment]
（Addresses - 普通模式地址区域）第三行：
IPv4 DNS Address - IPv4 主要 DNS 服务器地址：需要输入一个带端口格式的地址，留空为不启用，默认为 8.8.4.4:53。也支持同时请求多服务器的功能？

**Comment by chengr28** [comment]
@5sq 你可以这样理解……在多服务器模式下（也就是说主要和备用地址参数一共填入的地址大于2个时）这两个参数是同一个系统。举个例子吧：
`IPv4 DNS Address = 8.8.4.4:53`
`IPv4 Alternate DNS Address = 8.8.8.8:53|208.67.222.222:5353`
和
`IPv4 DNS Address = 8.8.4.4:53|8.8.8.8:53`
`IPv4 Alternate DNS Address = 208.67.222.222:5353`
在程序载入的时候读取到的地址列表是一样的：
`8.8.4.4:53` 和 `8.8.8.8:53` 和 `208.67.222.222:5353`

**Comment by matthew728960** [comment]
Sorry,没看清楚。已经改了，谢谢！
