### ISSUE TITLE
失败1062，由于发生错误193

### ISSUE THREAD

**Issue by tudouniurou** [chengr28/Pcap_DNSProxy#410]
1，4.13版本，安装exe正常，win10
2，右键管理员ServiceControl.bat，输入 1 并回车，即选择 "1: Install service" 安装服务正常
3，然后失败1062，由于发生错误193。
4，根据别人帖子，我又直接双击那个exe，这样再去更改dns就可以了吧？

![image](https://user-images.githubusercontent.com/47689916/53717443-21d17300-3e93-11e9-9092-7e83110badbb.png)

![image](https://user-images.githubusercontent.com/47689916/53717580-8bea1800-3e93-11e9-8a9f-a6b78fa410bc.png)

**Comment by chengr28** [comment]
直接运行 exe 是没有问题的，只是每次开机都比较麻烦，而且会有窗口。
红色这个可以检查一下程序的目录有没有 Error.log 生成，一般都可以找到原因。
