### ISSUE TITLE
设置hosts后nslookup能找到A记录但ping无法解析IP

### ISSUE THREAD

**Issue by zhangyz1997** [chengr28/Pcap_DNSProxy#412]
﻿### Version/使用的版本/使用的版本
Pcap_DNSProxy 0.4.9.13
### Running Environment/运行环境/運行環境
Windows 10 Pro 18845 + Npcap 0.99-r7
### Expectation/期望情况/期望情況
![quic1](https://user-images.githubusercontent.com/22343073/53745716-85cb5a00-3eda-11e9-9ad0-170314cc8221.png)
如上所示, 在quic.conf中就设定了youtube的IP, 且config.ini里面的Hosts File Name也追加了quic.conf
期望在我使用 ping -4 www.youtube.com 走我指定的IP
### Actual/实际情况/實際情況
![quic2](https://user-images.githubusercontent.com/22343073/53745984-320d4080-3edb-11e9-95b4-8ab19a91cb2b.png)
Error.log中在测试的时间节点周围唯一出现的错误是: [Pcap Error] Insufficient privileges or not any available network devices.
Chrome访问报错DNS_PROBE_FINISHED_NXDOMAIN找不到IP
![quic3](https://user-images.githubusercontent.com/22343073/53747648-b1504380-3ede-11e9-8c0c-04ae6d2f7776.png)
但是同一hosts中部分规则又能正常生效

**Comment by chengr28** [comment]
那还真是奇怪，一般出现这种情况有一种可能是处理出来的数据包格式错了，系统的协议栈不接受，不过一下子也没找到具体是什么地方的问题，可以提供出问题的配置文件这边看看。

**Comment by zhangyz1997** [comment]
> 那还真是奇怪，一般出现这种情况有一种可能是处理出来的数据包格式错了，系统的协议栈不接受，不过一下子也没找到具体是什么地方的问题，可以提供出问题的配置文件这边看看。

[Config.ini](https://github.com/chengr28/Pcap_DNSProxy/files/2937020/Config.ini.txt)
完整的配置文件在这儿(GitHub只接受TXT所以改了下后缀), 还需要所有的hosts配置文件嘛

**Comment by chengr28** [comment]
呃，这边用这个配置文件和图中一样的 `quic.conf` 重现不了这个问题……或者这样吧，如果你用的是 Npcap 那么应该是可以抓 loopback 接口的数据包，可以抓一下 UDP 53 的看看是不是格式真的错了……

**Comment by zhangyz1997** [comment]
> 呃，这边用这个配置文件和图中一样的 quic.conf 重现不了这个问题……或者这样吧，如果你用的是 Npcap 那么应该是可以抓 loopback 接口的数据包，可以抓一下 UDP 53 的看看是不是格式真的错了……

更奇怪的现象出现了, nslookup能抓到query和response, 但是ping的时候什么也抓不到, 但换个域名抓就能抓到
