### ISSUE TITLE
更新0.4.9.13版本后无法启动

### ISSUE THREAD

**Issue by zvg** [chengr28/Pcap_DNSProxy#414]
﻿### Version/使用的版本/使用的版本
0.4.9.13

### Running Environment/运行环境/運行環境
OS X 10.14.3 (18D109)

### Expectation/期望情况/期望情況

程序正常运行

### Actual/实际情况/實際情況

使用的是全新安装的升级模式,就是删除所有文件,重新配置.

启动后出现,:

> [2019-03-14 20:40:12] -> [System Error] Create FIFO error: File exists[17].
> [2019-03-14 20:40:12] -> [Pcap Error] en0: You don't have permission to capture on that device ((cannot open BPF device) /dev/bpf0: Permission denied)
> 
> [2019-03-14 20:40:14] -> [Network Error] Bind UDP Monitor socket error: Permission denied[13].
> [2019-03-14 20:40:23] -> [Notice] Pcap_DNSProxy started.
> [2019-03-14 20:40:23] -> [System Error] Create FIFO error: File exists[17].
> [2019-03-14 20:40:23] -> [Pcap Error] en0: You don't have permission to capture on that device ((cannot open BPF device) /dev/bpf0: Permission denied)

配置, Pcap Devices Blacklist ,再启动,就一直 en1 en2 en3 en4 变化.

重启电脑后,再次启动. 提示
再次重启也是这个提示.

> [2019-03-14 21:31:25] -> [Notice] Pcap_DNSProxy started.
> [2019-03-14 21:31:25] -> [Network Error] TCP connection initialization error: Network is unreachable[51].
> [2019-03-14 21:31:25] -> [Network Error] TCP connection initialization error: Network is unreachable[51].
> [2019-03-14 21:31:25] -> [Network Error] TCP connection initialization error: Network is unreachable[51].

**Comment by Stzx** [comment]
你好!

你可以执行 `sudo chmod o+r /dev/bpf*` 来打开对网络设备的访问权限.

然后再试试启动程序 (๑•̀ㅂ•́)و✧

**Comment by zvg** [comment]
启动还是失败了了.提示:

> [2019-03-15 09:21:48] -> [Notice] Pcap_DNSProxy started.
> [2019-03-15 09:21:48] -> [System Error] Process already exists error: Resource temporarily unavailable[35].
> [2019-03-15 09:21:58] -> [Notice] Pcap_DNSProxy started.
> [2019-03-15 09:21:58] -> [System Error] Process already exists error: Resource temporarily unavailable[35].
> [2019-03-15 09:22:08] -> [Notice] Pcap_DNSProxy started.
> [2019-03-15 09:22:08] -> [System Error] Process already exists error: Resource temporarily unavailable[35].
> [2019-03-15 09:22:18] -> [Notice] Pcap_DNSProxy started.
> [2019-03-15 09:22:18] -> [System Error] Process already exists error: Resource temporarily unavailable[35].
> [2019-03-15 09:22:28] -> [Notice] Pcap_DNSProxy started.
> [2019-03-15 09:22:28] -> [System Error] Process already exists error: Resource temporarily unavailable[35].
> [2019-03-15 09:22:38] -> [Notice] Pcap_DNSProxy started.
> [2019-03-15 09:22:38] -> [System Error] Process already exists error: Resource temporarily unavailable[35].
> [2019-03-15 09:22:48] -> [Notice] Pcap_DNSProxy started.
> [2019-03-15 09:22:48] -> [System Error] Process already exists error: Resource temporarily unavailable[35].
> [2019-03-15 09:22:52] -> [Notice] Pcap_DNSProxy started.
> [2019-03-15 09:22:52] -> [System Error] Process already exists error: Resource temporarily unavailable[35].

**Comment by zvg** [comment]
我用一个全新安装的系统macbook pro 测试,也是如上的提示.系统版本也是OS X 10.14.3 (18D109)

**Comment by Stzx** [comment]
> 启动还是失败了了.提示:
> 
> > [2019-03-15 09:21:48] -> [Notice] Pcap_DNSProxy started.
> > [2019-03-15 09:21:48] -> [System Error] Process already exists error: Resource temporarily unavailable[35].

关于这个错误，请确认同时只有一个 `pcap_dnsproxy` 在运行. 

#307 （。＾▽＾）

**Comment by zvg** [comment]
请问如何确定是否有一个进程运行呢。

我通过 **活动监视器.app** 和 **ps aux | grep dnsproxy** 没有发现进程存在。

我使用 $ nslookup www.google.com 127.0.0.1 可以成功解析，这似乎说明 Pcap_DNSProxy 已经运行了。

> $ nslookup www.google.com 127.0.0.1
> Server:		127.0.0.1
> Address:	127.0.0.1#53
> 
> Non-authoritative answer:
> Name:	www.google.com
> Address: 172.217.14.100

但是，**Config.conf** 里 **Domain Case Conversion = 1** 是开启大小写转换的。 nslookup的结果并没有转换。都是小写的。

我糊涂了。不知道如何确定 Pcap_DNSProxy 已经运行了。

**Comment by chengr28** [comment]
是否有在运行只能靠其它程序去确认，Windows 下任务管理器或者其它平台 root 权限的应该可以查看。

至于 `Domain Case Conversion` 这个，返回解析结果混合大小写其实是不符合标准要求的，所以之前的更新有添加还原功能，就是说背后是转换了大小写的，但是在返回给请求者之前会转换回来……

**Comment by chengr28** [comment]
`Network is unreachable[51]`  这个只是单纯报告说上不了网，应该是因为程序在启动的时候系统的网络服务还未启动，或者用着的途中网络断了也是这个错误，如果确认配置没问题可以修改 `Print Log Level` 参数关掉错误报告。
