### ISSUE TITLE
debian 9.8 按照教程操作无法使用systemdctl启动

### ISSUE THREAD

**Issue by blizzardster** [chengr28/Pcap_DNSProxy#416]
﻿### Version/使用的版本/使用的版本

0.4.9.9

### Running Environment/运行环境/運行環境

Debian 9.8

### Expectation/期望情况/期望情況

正常启动程序

### Actual/实际情况/實際情況

编译安装
tar -zxvf libevent-2.1.8-stable.tar.gz
cd libevent-2.1.8-stable
./autogen.sh
./configure
make && make install

tar -zxvf libsodium-1.0.17-stable.tar.gz
cd libsodium-stable
./autogen.sh
./configure
make && make install

tar -zxvf libpcap-1.9.0.tar.gz
cd libpcap-1.9.0
./configure
make && make install

tar -zxvf Pcap_DNSProxy-0.4.9.9.tar.gz
cd Pcap_DNSProxy-0.4.9.9/Source/Auxiliary/Scripts
chmod 755 CMake_Build.sh
./CMake_Build.sh

设备启动配置
cp -r /root/Pcap_DNSProxy-0.4.9.9/Source/Release /usr/local/Pcap_DNSProxy
nano /usr/local/Pcap_DNSProxy/Pcap_DNSProxy.service

[Unit]
After=network.target
Description=Pcap_DNSProxy, a local DNS server based on WinPcap and LibPcap
Wants=network-online.target

[Service]
ExecStart=/usr/local/Pcap_DNSProxy/Pcap_DNSProxy
GuessMainPID=yes
LimitNOFILE=10240
Restart=on-failure
RestartSec=15s
Type=forking
WorkingDirectory=/usr/local/Pcap_DNSProxy

[Install]
WantedBy=multi-user.target

错误提示
● Pcap_DNSProxy.service - Pcap_DNSProxy, a local DNS server based on WinPcap and LibPcap
   Loaded: loaded (/etc/systemd/system/Pcap_DNSProxy.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-04-25 07:04:08 CST; 5ms ago
  Process: 4274 ExecStart=/usr/local/Pcap_DNSProxy/Pcap_DNSProxy (code=exited, status=127)

**Comment by chengr28** [comment]
可以去程序所在目录看看有没有 `Error.log` 生成。

**Comment by blizzardster** [comment]
> 可以去程序所在目录看看有没有 `Error.log` 生成。

不好意思，我是菜鸟很多还不会，我用命令find / -name Error.log 没有找到这个错误文件，程序所在目录也没找到，我不知道还有什么启动办法

**Comment by Stzx** [comment]
启动的错误日志显示，没有找到 `/usr/local/Pcap_DNSProxy/Pcap_DNSProxy` 这个执行程序。

使用 `type Pcap_DNSProxy` 看看程序安装成功了吗。

**Comment by blizzardster** [comment]
> 启动的错误日志显示，没有找到 `/usr/local/Pcap_DNSProxy/Pcap_DNSProxy` 这个执行程序。
> 
> 使用 `type Pcap_DNSProxy` 看看程序安装成功了吗。

提示Pcap_DNSProxy: not found，这怎么搞？

**Comment by blizzardster** [comment]
> > 启动的错误日志显示，没有找到 `/usr/local/Pcap_DNSProxy/Pcap_DNSProxy` 这个执行程序。
> > 使用 `type Pcap_DNSProxy` 看看程序安装成功了吗。
> 
> 提示Pcap_DNSProxy: not found，这怎么搞？

按照教程，做到./CMake_Build.sh结束，步骤都没有提示错误，

**Comment by blizzardster** [comment]
不知道那个文件没复制，我把ExampleConfig 目录和 Scripts所有文件拷贝到 Release 目录且替换就好了，
