### ISSUE TITLE
请教配置文件中一个配置项解释的疑惑？

### ISSUE THREAD

**Issue by jzp820927** [chengr28/Pcap_DNSProxy#42]
* Addresses - 普通模式地址区域
  * IPv4 DNS Address - IPv4 主要 DNS 服务器地址：需要输入一个带端口格式的地址，留空为不启用，默认为 8.8.4.4:53
    * 本参数支持同时请求多服务器的功能，开启后将同时向列表中的服务器请求解析域名，并采用最快回应的服务器的结果

在配置文件中，上面这一段关于 IPv4 DNS Address 的配置说明中，“本参数支持同时请求多服务器的功能，开启后将同时向列表中的服务器请求解析域名”，但是我把整个 readme 都看完了，也没看到有控制“同时请求多服务器”的开启配置项。
是不是只要配置了"地址A:端口|地址B:端口|地址C:端口"这样格式的多个DNS以后，同时请求多服务器的功能就自动开启了，不需要人为手动控制？还是在其他地方有控制项，我没看到？
感谢作者对本项目的付出，辛苦了！

**Comment by chengr28** [comment]
* `Alternate Multi Request` 这个参数就是多线程请求的开关……在 Main 和 Alternate 的地址参数里如果都只填了一个地址，那么开启这个参数时就是多线程请求这两个服务器
* 还有就是你提到的，在 Main 和 Alternate 里如果一共填入超过2个地址，那么 `Alternate Multi Request` 则会自动进入开启状态，就是说 `只要配置了"地址A:端口|地址B:端口|地址C:端口"这样格式的多个DNS以后，同时请求多服务器的功能就自动开启了，不需要人为手动控制` 的确没错

**Comment by jzp820927** [comment]
明白了，非常感谢作者的解答。
