### ISSUE TITLE
ServiceControl.bat

### ISSUE THREAD

**Issue by senolyusan** [chengr28/Pcap_DNSProxy#420]
﻿### Version/使用的版本/使用的版本
0.4.9.9
### Running Environment/运行环境/運行環境
Microsoft Windows [版本 10.0.18895.1000]
### Expectation/期望情况/期望情況
ServiceControl.bat 第28~32行理想输出为
%Prog%=Pcap_DNSProxy.exe
### Actual/实际情况/實際情況
实际输出为
%Prog%=Pcap_DNSProxy_XP.exe

可能原因：
` findstr /L /I " 5."`
运行时会忽略掉5前面的空格。
修改为
` findstr /L /I /C:" 5."`
可以正常识别空格。

**Comment by chengr28** [comment]
感谢反馈，不过因为后续的版本已经将 XP/2003 的支持移除了，所以这部分以后应该会整个去掉了。
