### ISSUE TITLE
whitelist及Routing无法更新

### ISSUE THREAD

**Issue by PS0123456** [chengr28/Pcap_DNSProxy#421]
﻿### Version/使用的版本/使用的版本

0.4.9.13

### Running Environment/运行环境/運行環境

win7 64

### Expectation/期望情况/期望情況
自动更新

### Actual/实际情况/實際情況

whitelist
![2019-5-19 18-3-12](https://user-images.githubusercontent.com/13433663/57980789-29e88a00-7a62-11e9-9877-44b1c85c07f3.png)

Routing 则闪现系统不存在该文件，然后自动关闭

证书问题？

**Comment by chengr28** [comment]
curl 这个错误应该是网络问题吧？看样子并没有成功连接到服务器。

**Comment by PS0123456** [comment]
> curl 这个错误应该是网络问题吧？看样子并没有成功连接到服务器。

啥原因呢。。。我挂梯子也不行啊

**Comment by SeaHOH** [comment]
添加环境变量 `http_proxy` 和 `https_proxy`，大多数工具都使用这两个变量名称，而不会读取 Win 系统设置。

**Comment by PS0123456** [comment]
> 梯子也有很多种类型的，这个 curl 不清楚是否会自动跟随使用系统的代理设置。

我是设置的全局代理。

**Comment by PS0123456** [comment]
> 添加环境变量 `http_proxy` 和 `https_proxy`，大多数工具都使用这两个变量名称，而不会读取 Win 系统设置。

我理解为是否即使我挂的梯子设置全局，也要单独在curl中设置环境变量？如果我理解没错，能否大致告知设置方式？

**Comment by SeaHOH** [comment]
变量格式： `http://ip:port`
设置方法，搜索关键字：
- 如何设置 系统 环境变量
- 如何设置 命令行 环境变量

**Comment by huaxianyan** [comment]
@PS0123456 可以考虑试试 proxychains 之类的工具

**Comment by chengr28** [comment]
可以试试先用其它方法把文件拖下来，然后修改脚本里 curl 的地址为本地的地址，这样 curl 就不会运行的时候才去下载了。

**Comment by PS0123456** [comment]
> 可以试试先用其它方法把文件拖下来，然后修改脚本里 curl 的地址为本地的地址，这样 curl 就不会运行的时候才去下载了。

我whitelist就是这么操作的，https://github.com/felixonmars/dnsmasq-china-list，去这边下载文件，然后地址也不用改，会自动读取本地文件。
但IP Routing规则我尝试了下，不知道下载什么文件，也拉不动，能否帮助我下？

**Comment by chengr28** [comment]
`curl "https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest" -o "delegated-apnic-latest"`

如果需要读取本地的文件， 直接改这句就行了。
