### ISSUE TITLE
Armbian安装出错

### ISSUE THREAD

**Issue by shushiwei** [chengr28/Pcap_DNSProxy#422]
﻿### Version/使用的版本/使用的版本

0.4.9.13

### Running Environment/运行环境/運行環境

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

### Actual/实际情况/實際情況
czh438@aml:~/Pcap_DNSProxy/Source/Auxiliary/Scripts$ ./CMake_Build.sh --enable-static                      
mkdir: cannot create directory 'Release': File exists
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.a (found version "1.1.0g") 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBEVENT_LIBRARIES
    linked by target "Pcap_DNSProxy" in directory /home/czh438/Pcap_DNSProxy/Source/Pcap_DNSProxy
LIBZ_LIBRARIES
    linked by target "Pcap_DNSProxy" in directory /home/czh438/Pcap_DNSProxy/Source/Pcap_DNSProxy

-- Configuring incomplete, errors occurred!
See also "/home/czh438/Pcap_DNSProxy/Source/Object/CMakeFiles/CMakeOutput.log".
See also "/home/czh438/Pcap_DNSProxy/Source/Object/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
mv: cannot stat 'Object/Pcap_DNSProxy': No such file or directory
cp: cannot create regular file 'Release/Linux_Install.Systemd.sh': Permission denied
cp: cannot create regular file 'Release/Linux_Install.SysV.sh': Permission denied
cp: cannot create regular file 'Release/Linux_Uninstall.Systemd.sh': Permission denied
cp: cannot create regular file 'Release/Linux_Uninstall.SysV.sh': Permission denied
cp: cannot create regular file 'Release/PcapDNSProxyService': Permission denied
cp: cannot create regular file 'Release/Pcap_DNSProxy.service': Permission denied
cp: cannot create regular file 'Release/Config.conf': Permission denied
cp: cannot create regular file 'Release/Hosts.conf': Permission denied
cp: cannot create regular file 'Release/IPFilter.conf': Permission denied
cp: cannot create regular file 'Release/Routing.txt': Permission denied
cp: cannot create regular file 'Release/WhiteList.txt': Permission denied
mkdir: cannot create directory 'Release/Tools': File exists
cp: cannot create regular file 'Release/Tools/Update_Routing.sh': Permission denied
cp: cannot create regular file 'Release/Tools/Update_WhiteList.sh': Permission denied
chmod: changing permissions of 'Release': Operation not permitted
chmod: changing permissions of 'Release/IPFilter.conf': Operation not permitted
chmod: changing permissions of 'Release/Linux_Install.SysV.sh': Operation not permitted
chmod: changing permissions of 'Release/Linux_Install.Systemd.sh': Operation not permitted
chmod: changing permissions of 'Release/Routing.txt': Operation not permitted
chmod: changing permissions of 'Release/PcapDNSProxyService': Operation not permitted
chmod: changing permissions of 'Release/Hosts.conf': Operation not permitted
chmod: changing permissions of 'Release/Pcap_DNSProxy.service': Operation not permitted
chmod: changing permissions of 'Release/Tools': Operation not permitted
chmod: changing permissions of 'Release/Tools/Update_WhiteList.sh': Operation not permitted
chmod: changing permissions of 'Release/Tools/Update_Routing.sh': Operation not permitted
chmod: changing permissions of 'Release/Config.conf': Operation not permitted
chmod: changing permissions of 'Release/Linux_Uninstall.Systemd.sh': Operation not permitted
chmod: changing permissions of 'Release/WhiteList.txt': Operation not permitted
chmod: changing permissions of 'Release/Linux_Uninstall.SysV.sh': Operation not permitted

**Comment by chengr28** [comment]
```
LIBEVENT_LIBRARIES
linked by target "Pcap_DNSProxy" in directory /home/czh438/Pcap_DNSProxy/Source/Pcap_DNSProxy
LIBZ_LIBRARIES
linked by target "Pcap_DNSProxy" in directory /home/czh438/Pcap_DNSProxy/Source/Pcap_DNSProxy
```

这个依赖（zlib 和 libevent）都设置好了吗？

**Comment by shushiwei** [comment]
> ```
> LIBEVENT_LIBRARIES
> linked by target "Pcap_DNSProxy" in directory /home/czh438/Pcap_DNSProxy/Source/Pcap_DNSProxy
> LIBZ_LIBRARIES
> linked by target "Pcap_DNSProxy" in directory /home/czh438/Pcap_DNSProxy/Source/Pcap_DNSProxy
> ```
> 
> 这个依赖（zlib和libevent）都设置好了吗？

装了依赖以后编译安装好了，但是用不了
错误日志
[2019-05-23 20:13:12] -> [Notice] Pcap_DNSProxy started.
[2019-05-23 20:13:12] -> [Parameter Error] Local request options error in /etc/Pcap_DNSProxy/Config.conf.
[2019-05-23 20:13:29] -> [Notice] Pcap_DNSProxy started.
[2019-05-23 20:13:29] -> [Parameter Error] Local request options error in /etc/Pcap_DNSProxy/Config.conf.
[2019-05-23 20:13:46] -> [Notice] Pcap_DNSProxy started.
[2019-05-23 20:13:46] -> [Parameter Error] Local request options error in /etc/Pcap_DNSProxy/Config.conf.
[2019-05-23 20:14:03] -> [Notice] Pcap_DNSProxy started.
[2019-05-23 20:14:03] -> [Parameter Error] Local request options error in /etc/Pcap_DNSProxy/Config.conf.
[2019-05-23 20:14:21] -> [Notice] Pcap_DNSProxy started.
[2019-05-23 20:14:21] -> [Parameter Error] Local request options error in /etc/Pcap_DNSProxy/Config.conf.
[2019-05-23 20:14:38] -> [Notice] Pcap_DNSProxy started.
[2019-05-23 20:14:38] -> [Parameter Error] Local request options error in /etc/Pcap_DNSProxy/Config.conf.
[2019-05-23 20:14:55] -> [Notice] Pcap_DNSProxy started.
[2019-05-23 20:14:55] -> [Parameter Error] Local request options error in /etc/Pcap_DNSProxy/Config.conf.
[2019-05-23 20:15:12] -> [Notice] Pcap_DNSProxy started.
[2019-05-23 20:15:12] -> [Parameter Error] Local request options error in /etc/Pcap_DNSProxy/Config.conf.
                                                                                                          
配置文件
就修改了这前面这几段
再弱弱的问句 需要配合dnsmasq使用吗？dnsmasq已经被我禁用了
[Base]
Version = 0.45
File Refresh Time = 15
Large Buffer Size = 4096
Additional Path =
Hosts File Name = Hosts.ini|Hosts.conf|Hosts.txt|WhiteList.txt
IPFilter File Name = IPFilter.ini|IPFilter.conf|IPFilter.dat|Routing.txt|chnroute.txt

[Log]
Print Log Level = 3
Log Maximum Size = 8MB

[Listen]
Process Unique = 1
Pcap Capture = 1
Pcap Devices Blacklist = AnyConnect|Host|Hyper|ISATAP|IKE|L2TP|Only|Oracle|PPTP|Pseudo|Teredo|Tunnel|Virtual|VMNet|VMware|VPN|any|gif|ifb|lo|nflog|nfqueue|stf|tunl|utun
Pcap Reading Timeout = 250
Listen Protocol = IPv6 + IPv4 + TCP + UDP
Listen Port = 53
Operation Mode = Private
IPFilter Type = Deny
IPFilter Level < 0
Accept Type =

[DNS]
Outgoing Protocol = IPv4 + TCP
Direct Request = 0
Cache Type = Timer + Queue
Cache Parameter = 256
Cache Single IPv4 Address Prefix = 0
Cache Single IPv6 Address Prefix = 0
Default TTL = 1800

[Local DNS]
Local Protocol = IPv4 + UDP
Local Hosts = 1
Local Routing = 1
Local Force Request = 0

[Addresses]
IPv4 Listen Address =
IPv4 EDNS Client Subnet Address =
IPv4 Main DNS Address = 202.141.162.123:5353
IPv4 Alternate DNS Address = 8.8.4.4:53|149.112.112.112:53|208.67.220.220:5353
IPv4 Local Main DNS Address = 202.101.226.69:53
IPv4 Local Alternate DNS Address = 202.101.224.69:53
IPv6 Listen Address =
IPv6 EDNS Client Subnet Address =
IPv6 Main DNS Address = [2001:4860:4860::8844]:53
IPv6 Alternate DNS Address = [2606:4700:4700::1001]:53|[2620:FE::9]:53|[2620:0:CCD::2]:5353
IPv6 Local Main DNS Address = [240C::6644]:53
IPv6 Local Alternate DNS Address = [240C::6666]:53

**Comment by chengr28** [comment]
```
  * 注意：关于 Local Hosts 和 Local Routing 和 Local Force Request 的组合说明
    * 默认情况下在境内服务器解析失败会进行下一步的操作
    * 所有参数均为关闭时，直接跳过使用境内服务器进行域名解析的过程
    * Local Hosts 可以单独开启：将按照（黑）白名单（无）命中规则的域名，才（不）使用境内服务器进行解析
    * Local Routing 可以单独开启：所有请求都会先发送至境内服务器进行域名解析，然后根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者
    * Local Force Request 不能单独启用：需要和 Local Hosts 配合使用
    * Local Hosts + Local Routing 不能同时启用：功能冲突
    * Local Hosts + Local Force Request 可以同时启用：强制已命中规则的域名只能使用境内服务器进行解析，解析结果有问题将直接丢弃并终止整个解析过程
    * Local Routing + Local Force Request 不能同时启用：功能冲突
    * Local Hosts + Local Routing + Local Force Request 可以同时启用：所有（除了黑名单所指定的）请求都会先发送至境内服务器进行域名解析，根据请求的性质：
      * 如果该请求的域名命中 Local Hosts 则强制已命中规则的域名只能使用境内服务器进行解析，解析结果有问题将直接丢弃并终止整个解析过程
      * 如果该请求的域名没有命中 Local Hosts 则根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者
      * 所有没有命中且没有成功匹配路由表的请求将会进行下一步的操作
```

**Comment by shushiwei** [comment]
> ```
>   * 注意：关于 Local Hosts 和 Local Routing 和 Local Force Request 的组合说明
>     * 默认情况下在境内服务器解析失败会进行下一步的操作
>     * 所有参数均为关闭时，直接跳过使用境内服务器进行域名解析的过程
>     * Local Hosts 可以单独开启：将按照（黑）白名单（无）命中规则的域名，才（不）使用境内服务器进行解析
>     * Local Routing 可以单独开启：所有请求都会先发送至境内服务器进行域名解析，然后根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者
>     * Local Force Request 不能单独启用：需要和 Local Hosts 配合使用
>     * Local Hosts + Local Routing 不能同时启用：功能冲突
>     * Local Hosts + Local Force Request 可以同时启用：强制已命中规则的域名只能使用境内服务器进行解析，解析结果有问题将直接丢弃并终止整个解析过程
>     * Local Routing + Local Force Request 不能同时启用：功能冲突
>     * Local Hosts + Local Routing + Local Force Request 可以同时启用：所有（除了黑名单所指定的）请求都会先发送至境内服务器进行域名解析，根据请求的性质：
>       * 如果该请求的域名命中 Local Hosts 则强制已命中规则的域名只能使用境内服务器进行解析，解析结果有问题将直接丢弃并终止整个解析过程
>       * 如果该请求的域名没有命中 Local Hosts 则根据路由表进行匹配，命中路由表的解析结果将直接返回给请求者
>       * 所有没有命中且没有成功匹配路由表的请求将会进行下一步的操作
> ```

谢谢大佬指点
已经用上了

修改 Direct Request = IPv4 就OK了
[DNS]
Outgoing Protocol = IPv4 + TCP
Direct Request = IPv4
Cache Type = Timer + Queue
Cache Parameter = 256
Cache Single IPv4 Address Prefix = 0
Cache Single IPv6 Address Prefix = 0
Default TTL = 1800
