### ISSUE TITLE
brew install pcap_dnsproxy ，但是提示没有这个包，怎么回事？

### ISSUE THREAD

**Issue by luckypoem** [chengr28/Pcap_DNSProxy#426]
### Running Environment/运行环境/運行環境: mac sierra,10.10.26,
我看了此文https://www.jianshu.com/p/fc67d4542189 ，运行了
brew install pcap_dnsproxy ，但是提示没有这个包，怎么回事？
谢谢回复。

**Comment by chengr28** [comment]
不怎么回事……homebrew 很久以前就移除了，原因不明，可能是使用量太少？

**Comment by luckypoem** [comment]
这个包是由你（作者）提交的吗？就像clowwindy提交ss那样？（可用pip install shadowsocks来安装ss).
如果是被homebrew删除了，你可以重新提交申请吗

**Comment by chengr28** [comment]
应该不是本人提交的，不过之前有为了版本的更新而提过 PR 的。至于 Homebrew 应该是以后都不会再进行支持了，如果需要可以直接下载 macOS 平台的可执行文件，手动进行部署。

**Comment by luckypoem** [comment]
我下载 macOS 平台的可执行文件，手动进行部署，失败。为什么Homebrew 应该是以后都不会再进行支持了？怎么以前就可以成功运行brew install pcap_dnsproxy呢？
