### ISSUE TITLE
ubuntu 18.04 编译出错

### ISSUE THREAD

**Issue by wctliu** [chengr28/Pcap_DNSProxy#428]
ubuntu@ubuntu:~/Pcap_DNSProxy/Source/Auxiliary/Scripts$ ./CMake_Build.sh --enable-static
mkdir: cannot create directory ‘Release’: File exists
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.a (found version "1.1.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Pcap_DNSProxy/Source/Object
Scanning dependencies of target Pcap_DNSProxy
[  9%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
[  9%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Configuration.cpp.o
[ 13%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurveControl.cpp.o
[ 18%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Capture.cpp.o
[ 22%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/DNSCurveRequest.cpp.o
[ 27%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Initialization.cpp.o
[ 31%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Main.cpp.o
[ 36%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Monitor.cpp.o
[ 40%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Network.cpp.o
[ 45%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PacketData.cpp.o
[ 50%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/PrintLog.cpp.o
[ 54%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Process.cpp.o
[ 59%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Protocol.cpp.o
[ 63%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Proxy.cpp.o
[ 68%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadCommand.cpp.o
[ 72%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadHosts.cpp.o
[ 77%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadIPFilter.cpp.o
[ 81%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/ReadParameter.cpp.o
[ 86%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Request.cpp.o
[ 90%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/Service.cpp.o
[ 95%] Building CXX object CMakeFiles/Pcap_DNSProxy.dir/TransportSecurity.cpp.o
[100%] Linking CXX executable Pcap_DNSProxy
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(nptl-init.o): In function `__pthread_initialize_minimal_internal':
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:294: undefined reference to `_dl_cpuclock_offset'
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:429: undefined reference to `_dl_pagesize'
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:438: undefined reference to `_dl_pagesize'
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:454: undefined reference to `_dl_init_static_tls'
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:456: undefined reference to `_dl_wait_lookup_done'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(nptl-init.o): In function `__pthread_get_minstack':
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:475: undefined reference to `_dl_pagesize'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(pthread_create.o): In function `allocate_stack':
/build/glibc-OTsEL5/glibc-2.27/nptl/allocatestack.c:526: undefined reference to `_dl_stack_flags'
/build/glibc-OTsEL5/glibc-2.27/nptl/allocatestack.c:652: undefined reference to `_dl_stack_flags'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(pthread_getattr_np.o): In function `pthread_getattr_np':
/build/glibc-OTsEL5/glibc-2.27/nptl/pthread_getattr_np.c:99: undefined reference to `_dl_pagesize'
/build/glibc-OTsEL5/glibc-2.27/nptl/pthread_getattr_np.c:137: undefined reference to `_dl_pagesize'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(elision-lock.o): In function `do_set_elision_enable':
/build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/x86/elision-conf.c:67: undefined reference to `_dl_x86_cpu_features'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.a(dlopen.o): In function `dlopen':
(.text+0x5): undefined reference to `__dlopen'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.a(dlclose.o): In function `dlclose':
(.text+0x1): undefined reference to `__dlclose'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.a(dlsym.o): In function `dlsym':
(.text+0x5): undefined reference to `__dlsym'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.a(dlerror.o): In function `dlerror':
(.text+0x1): undefined reference to `__dlerror'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.a(dladdr.o): In function `dladdr':
(.text+0x1): undefined reference to `__dladdr'
collect2: error: ld returned 1 exit status
CMakeFiles/Pcap_DNSProxy.dir/build.make:621: recipe for target 'Pcap_DNSProxy' failed
make[2]: *** [Pcap_DNSProxy] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[1]: *** [CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
mv: cannot stat 'Object/Pcap_DNSProxy': No such file or directory
mkdir: cannot create directory ‘Release/Tools’: File exists

**Comment by chengr28** [comment]
试试把 `--enable-static` 去掉。

**Comment by wctliu** [comment]
谢谢。搞定了。果然去掉就好了。

**Comment by chengr28** [comment]
那个静态链接一般是交叉编译的时候才会用，平时都是默认参数就好。
