### ISSUE TITLE
希望下版本能够增加如下功能~

### ISSUE THREAD

**Issue by yuyangzxw** [chengr28/Pcap_DNSProxy#43]
首先非常感谢作者开发出如此好使的软件,谢谢了~

1.境内DNS服务器地址:IPv4 Local DNS Address和IPv4 Local Alternate DNS Address能够使用类似境外服务器的格式(地址A:端口|地址B:端口|地址C:端口)指定多个DNS服务器.

2.HOST能够支持TAB键的读取,貌似个人强迫症喜欢用TAB来整齐排列HOST格式,然后发现直接复制到Hosts.ini里面会报错,需要手动替换成空格才可以,希望能够自动识别TAB间隔呢

3.希望增加类似Hosts.ini里面[Local Hosts]格式文件,但是是黑名单模式.本人设置方法之一就是Local Main = 1 同时 Local Routing = 1.同时本人一个域名是使用智能DNS:国内DNS解析自动走日本线路,国外DNS解析走美国线路,同时美国线路是无法直接访问的,但是必须设置CNAME到美国线路来进行欺骗设置.软件当前功能下就会发现没有办法设置强制走境内DNS,因为Local Hosts 和 Local Routing不能同时启用...然后就没
有然后了...

尝试过IPv4 DNS Address设置为境内DNS服务器,IPv4 Local DNS Address为境外DNS服务器,然后Local Hosts输入域名来实现"黑名单"模式,发现IPv4 Local DNS Address境外DNS服务器解析的域名跟默认设置下IPv4 DNS Address境外DNS服务器解析的域名返回的IP貌似不一样的...不知道是不是IPv4 DNS Address和IPv4 Local DNS Address实现原理不一样造成的...

希望作者能够完善这类功能,同时再次感谢作者~

**Comment by yuyangzxw** [comment]
貌似再重新配置了下,IPv4 DNS Address和IPv4 Local DNS Address对换来实现类似[Local Hosts]的"黑名单"模式发现没问题,可能是以前设置了好几种方案,混淆了...
不过这样的话,还是希望IPv4 Local DNS Address能够像IPv4 DNS Address格式(地址A:端口|地址B:端口|地址C:端口)来指定多个DNS服务器,谢谢~

**Comment by yuyangzxw** [comment]
找了一大圈,貌似作者20楼应该给出方案,暂时调试试试,谢谢了~

https://www.v2ex.com/t/119128

**Comment by chengr28** [comment]
* 指定多个服务器，也就是多线程功能本身目的并不是为了提高解析的速度，而是为了在丢包严重的环境下提高解析的可靠性，Local 服务器实际上并没有解析可靠性方面的问题，所以不会为 Local 的部分加入多线程的支持
* 关于这个之前在 SNS 上有提过 https://plus.google.com/104603245338932141930/posts/WMEUc4NM9aW 实际上是支持那堆空格格式的包括 Tab 不过刚才测试发现是因为识别的部分有问题才导致了报错……下次更新会顺便修复这个错误
* 这种情况还不如改个 Hosts……本身 Local 请求只是为了解决境内 CDN 的问题，并不是拿来故意指向某个服务器解析的，而且刚才也说了与其选定某个 DNS 服务器，还不如改一下 Hosts 直接指定解析的结果更好

**Comment by yuyangzxw** [comment]
1.这个问题我主要发现公共DNS都有一个问题,就是很多网站有CDN的,假如我用114DNS,可能返回的不是离我最近的CDN的IP,而阿里dns返回的是正确的CDN的IP;然后其他域名114DNS却比较准确,或者114DNS和阿里DNS都不准确,是其他DNS比如OneDNS返回的才是离我最近准确的CDN的IP,所以我想利用这个多个DNS返回IP的ping速度(姑且这么说,我也不知道怎么描述,就是离我最近的IP地址)来使用最近的IP地址加快访问速度.刚开始我看到IPv4 DNS Address有类似描述,以为是返回上述原因的IP,所以才希望加入多DNS解析加速的,如果不是我上述说的原理,估计确实没怎么必要
2.没问题了...
3.用说明文档的那个 NULL 解决了

**Comment by chengr28** [comment]
不不不……这样的需求就算使用多线程也是满足不了的。并不是某个 DNS 服务器返回解析结果的速度快，那么这个结果就是实际距离最接近的地址。举个例子，服务器查询并缓存了某个域名的解析结果，那么你去查询相同域名的时候自然能非常快地返回解析结果，然而这和解析出来的地址是不是距离最近的没有任何关系……

**Comment by yfdyh000** [comment]
其实此前我也有这个想法。并不是根据结果响应速度，而是根据返回的结果的ping IP速度。
但这样的话势必增加处理耗时，不知道能否做到可接受的程度，处理策略很需要考虑。

比如查询一个域名，从3个DNS得到了6份结果（每个各返回2个IP），先考虑去重，然后多线程ping（资源占用和互相及其他干扰要考虑）。ping超时最好不要超过100ms（不然影响较大；但这样就不能处理国外IP了；可考虑路由表辅助，如果处理速度更快）。然后选优。以及加权方面，最好能永久加权，对于某个域或某个DNS的最优性统计。总体来说，困难重重，可能不值得去做……

**Comment by yuyangzxw** [comment]
其实返回正确的运营商也就算了,像我是浙江电信的,有些DNS返回的却是是山东联通CDN的,然后我打开很慢,甚至打不开的情况,不过现在很多视频站什么的都有个读取客户端的IP自动判断客户机地址返回最近的视频源,问题倒也不是很大,主要是一个不大不小的站,很麻烦,最近发现这个问题还蛮多的,各个公共DNS都或多或少有这个问题.

**Comment by chengr28** [comment]
@yfdyh000 这已经超出了一个 DNS 代理工具的范畴了……貌似这些行为让递归服务器来做比较好。不过说实话 Ping 这种方式实际上不能完全反映网络的真实情况，况且有些 ISP 还直接把 ICMP 丢了，甚至 ICMP 的优先级可能还比较低。特别是后面涉及了数据统计，这个资源消耗……感觉就算是 Google 可能也不会这样做，而且想想 Google 那边搞出来的 EDNS Client Subnet 到头来还更实用 =_/=

**Comment by chengr28** [comment]
@yuyangzxw 这的确是个问题，不过这个其实一直都是 CDN 要完成的目标，或许逐渐就会完善起来……至于后面那个查地址库，最大的问题是网络的地址和地理位置之间并没有很强的关联，就是说除非大家都在同一个网段里，否则传输的远近还是得实际路由过去才会知道，而且还是动态变化的……这也不是一个工具能解决的事情了 =_/=

**Comment by shuangzhijinghua** [comment]
不过话说回来，CDN的问题是网站使用者以及CDN运营商要解决的，而这个DNS工具是保证解析结果不受干扰，要明确制作目的才是啊。

**Comment by yfdyh000** [comment]
@chengr28 确实很难。然而楼主的问题就是DNS判断和返回的CDN区域不正确，导致结果很慢。
ping方面，大致反映还是可以的，比如区分50ms与200ms的IP，或者直接优选第一个ICMP响应包的IP。
特殊网络环境，功能开关或者智能判断都可以。不过有些网站的IP是禁ICMP的，那就更麻烦了。
可以像tcping工具那样，大概就能避免ICMP问题？支持测试端口开放性和-f强制发送测试字节。
数据统计只是期望，几个指标感觉不会很费资源。总之还是成本、难度、复杂性等问题……
嗯，好像必要性的确不高，那就忽略以上吧 >_< ……

@shuangzhijinghua 也不算跑题吧，因为干扰不得不使用不准确的DNS，间接导致的结果不准确，用工具来避免。不过楼主这种复杂的DNS不准确情况的确没遇到（我都有点没看懂……），目前工具提供的过滤+本地DNS的方案一般也足够了……
