### ISSUE TITLE
如何添加SRV记录？

### ISSUE THREAD

**Issue by ic0xgkk** [chengr28/Pcap_DNSProxy#432]
﻿### Version/使用的版本/使用的版本

Pcap_DNSProxy 0.4.9.13

### Running Environment/运行环境/運行環境

CentOS 7 x86_64

### Expectation/期望情况/期望情況

回答我的问题

### Actual/实际情况/實際情況

请问下Pcap_DNSProxy支持SRV记录吗？如果支持的话怎么添加SRV记录做服务发现？谢谢

**Comment by chengr28** [comment]
一般来说如果是上游的 DNS 记录解析基本都没问题，但是如果需要额外在本地添加 SRV 记录就属于 Hosts 的范畴了。
