### ISSUE TITLE
Bind UDP Monitor socket error: Cannot assign requested address[99].

### ISSUE THREAD

**Issue by wubx** [chengr28/Pcap_DNSProxy#436]
﻿### Version/使用的版本/使用的版本

Pcap_DNSProxy 0.4.9.13

### Running Environment/运行环境/運行環境
ubuntu

### Expectation/期望情况/期望情況

sudo /usr/local/Pcap_DNSProxy/Pcap_DNSProxy 

启动Pcap_DNSProxy

配置系统默认的Config.conf

### Actual/实际情况/實際情況

[2019-09-14 23:51:59] -> [Notice] Pcap_DNSProxy started.
[2019-09-14 23:52:01] -> [Network Error] Bind UDP Monitor socket error: Cannot assign requested address[99].

**Comment by wubx** [comment]
系统systemctl启动了一个本地的DNS 服务造成的。

**Comment by chengr28** [comment]
这个错误代码是比较少见，正常来说端口被占了不应该是这个错误的……
