### ISSUE TITLE
typo for "CFosSpeed"

### ISSUE THREAD

**Issue by yfdyh000** [chengr28/Pcap_DNSProxy#44]
更新日志中。开头的c要小写……

现在文档有点乱，两个分支四份文档，所以没发补丁了。Github wiki不维护了吗。

**Comment by chengr28** [comment]
说明文档主要是考虑到以前份数太多，维护起来晕头转向……所以 GitHub Wiki 的文档已经去掉了，两个分支 Documents 里的内容是完全一样的，所以其实只有简繁两份

还有这是强迫症末期啊 /w\

**Comment by yfdyh000** [comment]
知道是一样的，然而若要提交补丁就要弄两个pull，或者等手动维护合并，总之形式上还是挺麻烦……
哦，好的。

**Comment by chengr28** [comment]
改好了 =_/=
