### ISSUE TITLE
无法在win10上运行ServiceControl

### ISSUE THREAD

**Issue by renyouguo** [chengr28/Pcap_DNSProxy#45]
开启后，1，回车，没有反应。

**Comment by chengr28** [comment]
回车后屏幕上有没显示什么文字信息或者出现什么反应？因为服务控制脚本里有一步是等待3次 Ping 本地回环地址达到延时检测的效果，有可能是这部分卡住了
试试在 cmd 里直接 Ping 127.0.0.1 看看是不是卡住很久才有回应？

**Comment by renyouguo** [comment]
发现是当时直接release分支打包下载的错误。
找了个之前的存档的版本就没有问题。

**Comment by chengr28** [comment]
现在 GitHub 上最新的服务控制批处理还会有这个问题吗？之前因为检测管理员权限的部分在有些系统里会造成严重问题，所以最近的版本去掉了

**Comment by chengr28** [comment]
WIndows 10 正式版本下最新版本的服务控制批处理似乎可以正常工作……
