### ISSUE TITLE
设置Local Host不生效

### ISSUE THREAD

**Issue by shuangzhijinghua** [chengr28/Pcap_DNSProxy#46]
![image](https://cloud.githubusercontent.com/assets/7972337/8599912/90947982-2695-11e5-9fbe-7eea6a69e489.png)
`.*\.alicdn\.com`应该能命中`g.alicdn.com`才是啊，但是为何还是使用了8.8.8.8而不是Local DNS？

**Comment by chengr28** [comment]
测试过程序工作是没问题的。想了下几个可能，确认参数配置文件里 Local Hosts = 1 了吗？0.4 正式版之后由于自带了 Local Hosts 列表，所以使用需要先在参数配置文件里开启 Local Hosts 功能

**Comment by xinhugo** [comment]
@shuangzhijinghua 试试用程序自带的白名单列表。
