### ISSUE TITLE
 本地dns 可以加入多服务器请求的功能吗

### ISSUE THREAD

**Issue by gaoyan1234** [chengr28/Pcap_DNSProxy#47]
当只开启local main 模式的时候，其他被污染的域名都可以得到正确的ip 唯独*googlevideo.com有问题。因为对114dns 请求*googlevideo.com 对应的ip时，114不是返回被污染的ip 而是返回空的，而且这种模式下好像备用的本地dns服务器 也没有工作。如果在电脑还填入除::1之外的dns时，最后电脑得到的就是被污染的ip 。如果 本地dns 可以加入多服务器请求的功能，就不会出现这个问题了。
tips：目前gfw的dns污染随机返回境外ip的方式 貌似已经关闭  ，是否可以加入 ip黑名单这种最简单的防污染的方法

> r8---sn-4g57knlz.googlevideo.com
服务器:  pcap-dnsproxy.localhost.server
Address:  ::1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
非权威应答:
DNS request timed out.
    timeout was 2 seconds.
名称:    r8.sn-4g57knlz.GoOgLeViDeO.CoM
Address:  74.125.99.45
Aliases:  r8---Sn-4G57kNlZ.GoOgLeViDeO.CoM

> r8---sn-4g57knlz.googlevideo.com  114.114.115.115
服务器:  [114.114.115.115]
Address:  114.114.115.115

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 114.114.115.115 超时
C:\Users\Administrator>ping r7---sn-4g57knlz.googlevideo.com

正在 Ping r7---sn-4g57knlz.googlevideo.com [203.98.7.65] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

203.98.7.65 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)

**Comment by chengr28** [comment]
* 关于 114DNS 请求 Googlevideo 的问题，后来发现是程序内置过滤的问题，更新到最新的 0.4.2.5 应该会不会有这方面的问题了，实际上 114DNS 也是有返回解析的，只是被投毒污染了而已。至于空包的问题，程序只能做到不缓存，但是这个问题其实普遍存在的……只是几率比较低，参见 https://github.com/chengr28/Pcap_DNSProxy/issues/30
* 如果填入除回环地址之外的 DNS 时，首选 DNS 请求超时就会去请求备用 DNS（注意这是系统的策略）如果备用 DNS 有投毒污染的话，最终的结果也是会有污染的，就像最后提供的结果 203.98.7.65 这个就是污染的地址
* 关于 Tips 的问题，程序的黑名单是通过配置文件中的 Blacklist 参数控制的，从程序开始写的第一天到现在就一直没关闭过，所以不用担心这方面的问题w
* 至于 Local 服务器多线程的问题在 https://github.com/chengr28/Pcap_DNSProxy/issues/43 也讨论过，这边就针对你的疑问：程序的主要和备份策略，纯粹就是当主要服务器在一定条件下掉线后才会使用（参见说明文档）而不是第一次解析失败就马上使用，因为针对的仅仅是短暂下线的问题；程序的多线程策略是『一次发出多个请求，接收最先或最后的正确的解析』刚才也说过不能解析 Googlevideo 是程序的问题，而且如果 114DNS 解析不出来那就基本说明使用境内服务器能成功解析的几率比较低，这种情况下就需要使用境外服务器进行解析了

抱歉拖的时间有点长了才回复……

**Comment by gaoyan1234** [comment]
谢谢作者解答，发现0.4.2.5 版本有个bug ： Local Hosts =  选项没有作用   即单独开启  Local Hosts = 1 时，所有的域名都还是通过境外服务器进行解析  上一个版本没有这个问题 。

**Comment by chengr28** [comment]
看了下，貌似是因为 0.4.2.5 这版为了降低资源占用把检查 Hosts 的部分从请求远程服务器的一边前移到接收数据包时忘记把 Local Hosts 的功能加回去了……感谢反馈，刚才上传的 0.4.2.5（版本号没变）应该已经修复这个问题了，可以试试ww

**Comment by gaoyan1234** [comment]
试了更新后 0.4.2.5   似乎还有点bug。通过抓包工具发现：当只开启 Local Hosts = 1 时，对于非白名单内的域名 0.4.2.1版向境外ip发送多线程请求，白名单内的域名向本地dns请求（完美）；而0.4.2.5 版，对于非白名单内的域名（*.googlevideo.com)，也会向本地dns发送请求，在得到污染的ip之后才会再向国外dns 请求，容易请求超时（114dns 不是啥好东西 天知道它有没有统计某个ip 请求敏感域名的次数，再通过电信后台 可以直接确定用户）

  最后再问一句  Direct Request 选项到底有啥作用  看了配置介绍 还是云里雾里的 ，开启关闭   通过抓包看不到区别  可否通俗易懂的说一下   谢谢
![20150721144106](https://cloud.githubusercontent.com/assets/10344954/8794642/f66ce962-2fb7-11e5-8bfe-bfc66f9fc52a.jpg)

**Comment by chengr28** [comment]
* 好吧刚才又更新了 0.4.2.5（还是没变）刚才去看了发现是因为昨晚补上面 Local Hosts 的时候漏写了重置状态的部分，所以只要有一次 Local Hosts 命中了的话后续的也一直都会是 Local Hosts……现在应该是没问题的了。总感觉最近这几天的更新手忙脚乱的感觉 =_/=
* Direct Request 其实就是直接把相应协议（不是指 A 记录或者 AAAA 记录而是根据配置文件选定的网关的协议）请求交给系统处理并等待系统的回复，而程序本身不做任何过滤之类的处理（实际上还是有做，视乎配置文件而定）这个功能以前是考虑有些用户可能只需要 Hosts 而不需要本程序的过滤（所以以前叫 Hosts Only）后来发现有些用户可能会在本地挂了 IPv6 隧道之类的代理工具，这样如果直接往系统那边发系统就会自动通过这类隧道进行解析，这样就不需要程序进行过滤之类的处理了
