### ISSUE TITLE
查询lovevpn.wicp.net失败

### ISSUE THREAD

**Issue by shuangzhijinghua** [chengr28/Pcap_DNSProxy#48]
![image](https://cloud.githubusercontent.com/assets/7972337/8756286/be2325e6-2d03-11e5-9b26-6a0d6db91f09.png)

**Comment by chengr28** [comment]
刚才去看了下，是因为这个域名带的 A 记录太多导致 UDP 协议传输数据的时候截断……按照 RFC 的标准流程的话应该是需要使用 TCP 协议重试的，程序可能这方面不太协调……下次更新的时候会留意这方面的问题w

**Comment by chengr28** [comment]
不过其实这种小问题的话比较好是直接通过邮件找我，或者看看例如都是无法解析，可以 Reopen https://github.com/chengr28/Pcap_DNSProxy/issues/46 然后改个标题之类，一时开很多 Issue 感觉会很乱……

**Comment by shuangzhijinghua** [comment]
好吧..因为觉得这个东西应该不算是小问题可能是和程序设计考虑的问题有关，就开了一个issue。

chengr28 <notifications@github.com>于2015年7月18日周六 上午11:08写道：

**Comment by chengr28** [comment]
其实个人觉得这样给自己域名放上一堆地址不太好……虽然是没问题，不过既防不了投毒污染，也会因为现在这种 UDP 截断问题而必须使用 TCP 然而现在网络环境各种不好的情况下……解析成功率会下降

**Comment by wongsyrone** [comment]
个人感觉这些ip早晚都会封干净的，这样做解析没有什么意义，而且维护起来很繁杂

**Comment by chengr28** [comment]
刚才更新的 0.4.2.5 已经修复好了 =_/=
