### ISSUE TITLE
更新到0.4.2.5以后,境内服务器解析不生效,内详

### ISSUE THREAD

**Issue by yuyangzxw** [chengr28/Pcap_DNSProxy#49]
换了0.4.2.5以后,刚开始没注意,就是感觉上网突然好卡,很多网站都打不开或者图片也显示不了,一直以为是自己电脑问题,然后无意间排查中发现,是0.4.2.5的境内解析出了问题.

图一:使用0.4.2.4版本,**[防火墙](http://www.dayanzai.me/glasswire.html "防火墙我用的是这个网站的破解版")**截取的DNS解析,可以看到最上面是境内服务器也就是中国的DNS,我这里是AliDNS和OneDNS,根据 host.ini 设置,境内服务器流量占大多数
![0.4.2.4](http://ww3.sinaimg.cn/large/3f7b9425gw1eu9pblbqjhj211y0ke0v9.jpg)

图二:使用0.4.2.5版本,防火墙截取的DNS解析,发现没有任何境内服务器的DNS解析(其实也没显示中国国旗,网站都是随机点的大多数也是境内服务器解析的网站)
![0.4.2.5](http://ww4.sinaimg.cn/large/3f7b9425gw1eu9pcozd2bj211y0kmtb8.jpg)

以下是两个配置文件,其他一样的,0.4.2.4和0.4.2.5关于config.ini里面[DNS]内参数 Hosts Only  和 Direct Request 已经根据更新日志各自修改了的,下面是按0.4.2.5的参数来的,就一个字段的差别就没重复贴

Config.ini配置:

    [Base]
    Version = 0.4
    File Refresh Time = 10
    Buffer Queue Limits = 64
    Queue Limits Reset Time = 0
    Additional Path = 
    Hosts File Name = Hosts.ini|Hosts.conf|Hosts|Hosts.txt|Hosts.csv|WhiteList.txt|White_List.txt
    IPFilter File Name = IPFilter.ini|IPFilter.conf|IPFilter.dat|IPFilter.csv|IPFilter|Guarding.p2p|Guarding|Routing.txt|chnrouting.txt|chnroute.txt
    
    [Log]
    Print Error = 1
    Log Maximum Size = 1MB
    
    [DNS]
    Protocol = IPv4 + TCP
    Direct Request = IPv6 + IPv4
    Local Main = 0
    Local Hosts = 1
    Local Routing = 0
    Cache Type = Queue
    Cache Parameter = 128
    Default TTL = 900
    
    [Listen]
    Pcap Capture = 1
    Pcap Reading Timeout = 200
    Listen Protocol = IPv6 + IPv4 + TCP + UDP
    Listen Port = 53
    Operation Mode = Private
    IPFilter Type = Deny
    IPFilter Level < 
    Accept Type = 
    
    [Addresses]
    IPv4 Listen Address = 
    IPv4 EDNS Client Subnet Address = 
    ## 依次是: OpenDNS   |OpenDNS|GoogleDNS |YandexDNS   |DynDNS  |CloudNS   |DNSCrypt
    IPv4 DNS Address = 208.67.222.222:443|208.67.220.220:5353|8.8.8.8:53|77.88.8.1:53|216.146.36.36:53|113.20.6.2:443|176.56.237.171:443
    IPv4 Alternate DNS Address = 208.67.222.220:443|208.67.220.222:5353|8.8.4.4:53|77.88.8.8:53|216.146.35.35:53|113.20.8.17:443|77.66.84.233:443
    ## 上下依次是:   aliDNS 和 oneDNS
    IPv4 Local DNS Address = 223.6.6.6:53
    IPv4 Local Alternate DNS Address = 112.124.47.27:53
    IPv6 Listen Address = 
    IPv6 EDNS Client Subnet Address = 
    IPv6 DNS Address = [2001:4860:4860::8844]:53
    IPv6 Alternate DNS Address = [2001:4860:4860::8888]:53|[2620:0:CCD::2]:443|[2620:0:CCC::2]:5353
    IPv6 Local DNS Address = 
    IPv6 Local Alternate DNS Address = 
    
    [Values]
    EDNS Payload Size = 
    IPv4 TTL = 0
    IPv6 Hop Limits = 0
    IPv4 Alternate TTL = 0
    IPv6 Alternate Hop Limits = 0
    Hop Limits Fluctuation = 2
    Reliable Socket Timeout = 5000
    Unreliable Socket Timeout = 3000
    Receive Waiting = 0
    ICMP Test = 900
    Domain Test = 900
    Alternate Times = 10
    Alternate Time Range = 60
    Alternate Reset Time = 300
    Multi Request Times = 0
    
    [Switches]
    TCP Fast Open = 0
    Domain Case Conversion = 0
    Compression Pointer Mutation = 0
    EDNS Label = 0
    EDNS Client Subnet = 0
    DNSSEC Request = 0
    DNSSEC Validation = 0
    DNSSEC Force Validation = 0
    Alternate Multi Request = 1
    IPv4 Data Filter = 0
    TCP Data Filter = 1
    DNS Data Filter = 1
    Blacklist Filter = 1
    
    [Data]
    ICMP ID = 
    ICMP Sequence = 
    ICMP PaddingData = 
    Domain Test ID = 
    Domain Test Data = 
    Localhost Server Name = 
    
    [DNSCurve]
    DNSCurve = 0
    DNSCurve Protocol = TCP
    DNSCurve Payload Size = 
    Encryption = 1
    Encryption Only = 0
    Key Recheck Time = 3600
    
    [DNSCurve Addresses]
    DNSCurve IPv4 DNS Address = 208.67.220.220:443
    DNSCurve IPv4 Alternate DNS Address = 208.67.222.222:443
    DNSCurve IPv6 DNS Address = [2620:0:CCD::2]:443
    DNSCurve IPv6 Alternate DNS Address = [2620:0:CCC::2]:443
    DNSCurve IPv4 Provider Name = 2.dnscrypt-cert.opendns.com
    DNSCurve IPv4 Alternate Provider Name = 2.dnscrypt-cert.opendns.com
    DNSCurve IPv6 Provider Name = 2.dnscrypt-cert.opendns.com
    DNSCurve IPv6 Alternate Provider Name = 2.dnscrypt-cert.opendns.com
    
    [DNSCurve Keys]
    Client Public Key = 
    Client Secret Key = 
    IPv4 DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
    IPv4 Alternate DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
    IPv6 DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
    IPv6 Alternate DNS Public Key = B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79
    IPv4 DNS Fingerprint = 
    ## IPv4 DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007
    IPv4 Alternate DNS Fingerprint = 
    ## IPv4 Alternate DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007
    IPv6 DNS Fingerprint = 
    ## IPv6 DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007
    IPv6 Alternate DNS Fingerprint = 
    ## IPv6 Alternate DNS Fingerprint = 227C:86C7:7574:81AB:6AE2:402B:4627:6E18:CFBB:60FA:DF92:652F:D694:01E8:EBF2:B007
    
    [DNSCurve Magic Number]
    IPv4 Receive Magic Number = 
    IPv4 Alternate Receive Magic Number = 
    IPv6 Receive Magic Number = 
    IPv6 Alternate Receive Magic Number = 
    IPv4 DNS Magic Number = 
    ## IPv4 DNS Magic Number = qe47QHHw
    IPv4 Alternate DNS Magic Number = 
    ## IPv4 Alternate DNS Magic Number = qe47QHHw
    IPv6 DNS Magic Number = 
    ## IPv6 DNS Magic Number = qe47QHHw
    IPv6 Alternate DNS Magic Number = 
    ## IPv6 Alternate DNS Magic Number = qe47QHHw

Hosts.ini配置:
    
    ## Example:
    #
    # (Anywhere)
    # NULL localhost
    # BANNED localhost
    #
    # [Hosts]
    # 127.0.0.1 localhost
    # ::1 localhost
    # 
    # [Local Hosts]
    # localhost
    #
    # [Address Hosts]
    # 127.0.0.0-127.255.255.255 127.0.0.1
    # ::-::FFFF ::1
    #
    
    [Hosts]
    已经了解,和谐了
    
    [Address Hosts]

**Comment by chengr28** [comment]
看了下，貌似是因为 0.4.2.5 这版为了降低资源占用把检查 Hosts 的部分从请求远程服务器的一边前移到接收数据包时忘记把 Local Hosts 的功能加回去了……感谢反馈，刚才上传的 0.4.2.5（版本号没变）应该已经修复这个问题了，可以试试

PS：随便把 Hosts 晒出来好像不是很好……如果下次有需要的话可以直接发到我的邮箱里w

**Comment by yuyangzxw** [comment]
嗯,那我把host部分修改了哈

**Comment by yuyangzxw** [comment]
测试了下,应该没问题了,感谢作者~
