### ISSUE TITLE
开启Local Hosts导致无法在windows应用商店下载

### ISSUE THREAD

**Issue by renyouguo** [chengr28/Pcap_DNSProxy#50]
win10
whitelist ## Last update: 2015-05-01

关闭后就没问题了。

不知道究竟是哪一条白名单导致出错。

**Comment by chengr28** [comment]
刚才在 Windows 10 正式版本上下载了那个默认自带的游戏集锦，似乎是没问题的……
而且 Microsoft 的服务一般也不会被干扰，大概只是临时出现的网络问题？

如果情况持续，可以考虑安装一个 Wireshark 软件，并打开数据包抓取
然后打开应用商店并下载应用，出现失败信息后把抓到的数据包发到我的邮箱，看看是不是这方面的问题

**Comment by renyouguo** [comment]
最近这个问题自己好了。
