### ISSUE TITLE
brew 怎么安装？提示找不到

### ISSUE THREAD

**Issue by ferocknew** [chengr28/Pcap_DNSProxy#51]
如题

**Comment by blackgear** [comment]
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

参考http://brew.sh

**Comment by chengr28** [comment]
如果是以前有安装过 Homebrew 的话建议安装前先更新下 brew update 自带的软件库信息……
安装完后根据提示或者 brew info pcap_dnsproxy 可以查询到程序的部署方法
