### ISSUE TITLE
不支持 VPN

### ISSUE THREAD

**Issue by otakuchiyan** [chengr28/Pcap_DNSProxy#52]
-  DNS 已經設定爲 127.0.0.1 和 ::1 ，包括 NetworkManager 的有線、VPN 中的 IPv4/v6 字段和 /etc/resolv.conf .  
- 情況就是連 VPN 的時候有時找不到 IP 地址從而連不上。  
Error.log 中，絕大多數錯誤都是這一個：  
2015-08-03 17:32:51 -> WinPcap Error: vpn0 is not supported.  
這似乎是庫的問題。

**Comment by chengr28** [comment]
* 建议先更新到最新的 0.4.3 版本
* `not supported` 这个好像是旧版的错误日志，新版里有网络适配器黑名单所以不会报了
* 如果使用的是 VPN 等路由级别的代理，需要把 Direct Request 参数改为 IPv4 或者 IPv6（视乎 Protocol 参数和 VPN 类型的情况）并重启服务才能生效，否则如果数据包通过 VPN 发出去了，服务器回复的时候程序是抓不回来的，参见 Direct Request 参数的介绍：https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe(zh_Hans).txt#L192

**Comment by otakuchiyan** [comment]
已經解決了，謝謝。
