### ISSUE TITLE
Readme文档的一个细节问题

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#54]
`ReadMe(zh_Hans).txt`
   * 542行  * DNSCurve IPv6 Provider Name少个 Alternate

`ReadMe(zh_Hant).txt`
   * 同

以上 :)

**Comment by chengr28** [comment]
好吧……下次更新的时候会改掉
大概是有时更新内容的时候漏掉了……

**Comment by chengr28** [comment]
刚才更新的 0.4.3.2 应该已经改好了w
