### ISSUE TITLE
切换配置文件

### ISSUE THREAD

**Issue by icylogic** [chengr28/Pcap_DNSProxy#55]
请问如何切换配置文件?
在 Readme 里找到 `.\Pcap_DNSProxy.exe -c .\anotherconfig.ini`, 但是
如果服务本身没有运行, 没有任何效果, 执行之后再启动服务也没有效果.
如果服务已经在运行, 就会报错
```
System Error: Service start error, error code is 1063.                
System Error: Program will continue to run in console mode.           
Please ignore these error messages if you want to run in console mode.
```
如果删掉默认的 Config.ini 就无法启动服务
在 ServiceControl.bat 里也没有找到相关的.

**Comment by icylogic** [comment]
这个需求主要是想通过脚本启动 VPN 的时候启用 Direct Request 等配置, 没有 VPN 的时候启用 DNSCurve 等配置. 目前我只能这么解决
``
copy /y novpn.ini Config.ini
echo 5 | ServiceControl.bat
``

**Comment by chengr28** [comment]
关于这个在解决 https://github.com/chengr28/Pcap_DNSProxy/issues/53 的时候想了一个办法……不是切换配置文件，而是和 IPFilter 以及 Hosts 文件一样，大概在下次更新之后配置文件也会即时更新。就是说如果配置文件有修改的话，程序会在不需要重启的情况下立即重新读取大部分的参数，因为有几个是必须只能砸启动的时候读取……

不知道这个功能是不是比切换配置文件要好？

**Comment by icylogic** [comment]
这样也好，希望在配置文件或者 Readme 里注释一下哪些参数修改可以立即生效。

**Comment by chengr28** [comment]
刚才更新的 0.4.3.3 已经添加配置文件部分参数自动刷新功能……主要需要注意 DNSCrypt 那边的参数虽然可以支持自动刷新，不过由于牵扯到握手信息之类的东西，要改的话要三思……其它貌似都没什么问题了w

**Comment by icylogic** [comment]
看到了，谢谢
