### ISSUE TITLE
关于淘宝“www.taobao.com”总被解释为国外IP，应该怎样配置才能解决

### ISSUE THREAD

**Issue by 5sq** [chengr28/Pcap_DNSProxy#58]
如题：
我的config设置为
[Listen]
Listen Protocol = IPv4 + TCP + UDP
[Addresses]
IPv4 DNS Address = 8.8.4.4:53
IPv4 Alternate DNS Address = 8.8.8.8:53|208.67.220.220:443|208.67.222.222:5353
IPv4 Local DNS Address = 223.6.6.6:53
IPv4 Local Alternate DNS Address = 114.114.115.115:53

其它配置没有改变

淘宝（“www.taobao.com”）经常被解释我国外ip （如美国的）导致淘宝数据读取慢。

怎么解决？望指点。

**Comment by chengr28** [comment]
* 把 Local Main = 1 同时 Local Routing = 1 然后重启服务
* 把 Local Hosts = 1 然后重启服务

默认是没有开启境内 DNS 请求功能的，那些地址只是写在配置文件里而已
还是要使用者自己去开……上面2种随便选一个都行

**Comment by 5sq** [comment]
修改前：
dig www.taobao.com

; <<>> DiG 9.10.2 <<>> www.taobao.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25062
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;wWw.tAoBaO.CoM.                        IN      A

;; ANSWER SECTION:
wWw.tAoBaO.CoM.         376     IN      CNAME   www.taobao.com.danuoyi.tbcache.C
oM.
www.taobao.com.danuoyi.tbcache.CoM. 28 IN A     66.198.24.131

;; Query time: 395 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Aug 13 21:12:50 中国标准时间 2015
;; MSG SIZE  rcvd: 104

按你的方：把 Local Main = 1 同时 Local Routing = 1 然后重启服务后

dig www.taobao.com

; <<>> DiG 9.10.2 <<>> www.taobao.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55918
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;wWw.tAoBaO.CoM.                        IN      A

;; ANSWER SECTION:
wWw.tAoBaO.CoM.         550     IN      CNAME   www.taobao.com.danuoyi.tbcache.C
oM.
www.taobao.com.danuoyi.tbcache.CoM. 59 IN A     182.140.238.87

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Aug 13 21:17:22 中国标准时间 2015

问题已经解决谢谢！

**Comment by 5sq** [comment]
怎样设置后任然还是有问题（如淘宝图片）：
; <<>> DiG 9.10.2 <<>> img.alicdn.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4292
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;iMg.aLiCdN.CoM.                        IN      A

;; ANSWER SECTION:
iMg.aLiCdN.CoM.         18659   IN      CNAME   img.alicdn.com.danuoyi.aLiCdN.Co
M.
img.alicdn.com.danuoyi.aLiCdN.CoM. 28 IN A      66.198.24.240
img.alicdn.com.danuoyi.aLiCdN.CoM. 28 IN A      66.198.24.250

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Aug 13 21:25:31 中国标准时间 2015
;; MSG SIZE  rcvd: 112

**Comment by shuangzhijinghua** [comment]
你要把所有alicdn和tbimg都要添加进去

5sq <notifications@github.com>于2015年8月13日周四 下午9:28写道：

**Comment by 5sq** [comment]
请教：把 Local Hosts = 1 
添加需要Hosts.ini中的 Local Hosts - 境内 DNS 解析域名列表？

如果这就有点麻烦了……

**Comment by chengr28** [comment]
* Local Main = 1 + Local Routing = 1
这个主要是对境内 DNS 服务器返回的地址进行过滤，如果全部都是境内的地址才会接受，否则还是会去请求境外的 DNS 服务器……最好是看看是不是那些境内 DNS 服务器返回境外的地址了

* Local Hosts = 1
这个程序自带有白名单域名的列表了，就是 WhiteList.txt 直接开启就能用
注意不要混用两个方法

**Comment by 5sq** [comment]
将Local Main = 0 + Local Routing = 0
设置Local Hosts = 1
阿里图片任然会出现如下地址……
; <<>> DiG 9.10.2 <<>> img.alicdn.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37248
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ImG.AlIcDn.cOm.                        IN      A

;; ANSWER SECTION:
ImG.AlIcDn.cOm.         16673   IN      CNAME   img.alicdn.com.danuoyi.AlIcDn.cO
m.
img.alicdn.com.danuoyi.AlIcDn.cOm. 313 IN A     66.198.178.120
img.alicdn.com.danuoyi.AlIcDn.cOm. 313 IN A     66.102.255.50
img.alicdn.com.danuoyi.AlIcDn.cOm. 313 IN A     66.198.178.110
img.alicdn.com.danuoyi.AlIcDn.cOm. 313 IN A     66.102.255.40

;; Query time: 250 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Aug 13 21:57:53 中国标准时间 2015
;; MSG SIZE  rcvd: 144

**Comment by chengr28** [comment]
那可能是因为境内 DNS 服务器返回的就是这个地址……建议 `dig @223.6.6.6 img.alicdn.com` 和 `dig @114.114.115.115 img.alicdn.com` 看看结果

**Comment by 5sq** [comment]
墙内DNS是正确的
; <<>> DiG 9.10.2 <<>> @223.6.6.6 img.alicdn.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27091
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;img.alicdn.com.                        IN      A

;; ANSWER SECTION:
img.alicdn.com.         25      IN      CNAME   img.alicdn.com.danuoyi.alicdn.co
m.
img.alicdn.com.danuoyi.alicdn.com. 25 IN A      118.123.202.240
img.alicdn.com.danuoyi.alicdn.com. 25 IN A      118.123.202.250

;; Query time: 42 msec
;; SERVER: 223.6.6.6#53(223.6.6.6)
;; WHEN: Thu Aug 13 22:06:50 中国标准时间 2015
;; MSG SIZE  rcvd: 101
----------------------------------------------------
 <<>> DiG 9.10.2 <<>> @114.114.115.115 img.alicdn.com
 (1 server found)
; global options: +cmd
; Got answer:
; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8093
; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

; OPT PSEUDOSECTION:
 EDNS: version: 0, flags:; udp: 4096
; QUESTION SECTION:
img.alicdn.com.                        IN      A

; ANSWER SECTION:
mg.alicdn.com.         43462   IN      CNAME   img.alicdn.com.danuoyi.alicdn.co
.
mg.alicdn.com.danuoyi.alicdn.com. 30 IN A      118.123.202.240
mg.alicdn.com.danuoyi.alicdn.com. 30 IN A      118.123.202.250

; Query time: 38 msec
; SERVER: 114.114.115.115#53(114.114.115.115)
; WHEN: Thu Aug 13 22:07:41 中国标准时间 2015
; MSG SIZE  rcvd: 112

**Comment by 5sq** [comment]
是不是WhiteList.txt没有被调用？

**Comment by chengr28** [comment]
`dig +vc @223.6.6.6 img.alicdn.com` 和 `dig +vc @114.114.115.115 img.alicdn.com` 也是正确的？因为饿之前有人开 Issue 反馈过有些服务器 TCP 和 UDP 的结果不一样……

**Comment by 5sq** [comment]
; <<>> DiG 9.10.2 <<>> +vc @223.6.6.6 img.alicdn.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6123
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;img.alicdn.com.                        IN      A

;; ANSWER SECTION:
img.alicdn.com.         7313    IN      CNAME   img.alicdn.com.danuoyi.alicdn.co
m.
img.alicdn.com.danuoyi.alicdn.com. 60 IN A      115.238.23.240
img.alicdn.com.danuoyi.alicdn.com. 60 IN A      115.238.23.250

;; Query time: 201 msec
;; SERVER: 223.6.6.6#53(223.6.6.6)
;; WHEN: Thu Aug 13 22:16:45 中国标准时间 2015
;; MSG SIZE  rcvd: 112

; <<>> DiG 9.10.2 <<>> +vc @114.114.115.115 img.alicdn.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59423
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;img.alicdn.com.                        IN      A

;; ANSWER SECTION:
img.alicdn.com.         42851   IN      CNAME   img.alicdn.com.danuoyi.alicdn.co
m.
img.alicdn.com.danuoyi.alicdn.com. 50 IN A      118.123.202.250
img.alicdn.com.danuoyi.alicdn.com. 50 IN A      118.123.202.240

;; Query time: 38 msec
;; SERVER: 114.114.115.115#53(114.114.115.115)
;; WHEN: Thu Aug 13 22:17:14 中国标准时间 2015
;; MSG SIZE  rcvd: 112

**Comment by chengr28** [comment]
貌似那个 66 开头的地址是 OpenDNS 的……那的确是奇怪，可能是程序的问题也不确定
得花点时间看看……

**Comment by 5sq** [comment]
在G+上看了你的贴，现在这样配置就正常了。

Direct Request = IPv4
Local Main = 0
Local Hosts = 1
Local Routing = 0
--------------------------------------------
不知道是不是没有把Direct Request =0改为Direct Request = IPv4的原因。

谢谢你的无私贡献。

**Comment by exitwin98** [comment]
不错，按2楼的修改，任选其一就行了

**Comment by uuudbx** [comment]
按照说明配置依然会出现解析alicdn到国外的情况，但并不是总是解析错。有点奇怪

**Comment by uuudbx** [comment]
把Direct Request =0改为Direct Request = IPv4似乎有效果

**Comment by uuudbx** [comment]
依然没有效果，还是出现解析到国外地址。好无奈，先用国内dns

**Comment by chengr28** [comment]
是这样……Linux 平台详细测试过，均没有发现这类问题，就是 Local Hosts = 1
数据包都是直接发往境内 DNS 服务器的……不过看了下流程，的确有可能会导致这类情况

就是境内 DNS 服务器的回复没有被程序接收而是被丢弃然后去请求境外 DNS 服务器
那个 66 开头的地址是 OpenDNS 的，就是说程序把境内 DNS 服务器的回复丢弃掉了
丢弃的原因……有可能是境内 DNS 服务器压根没回复，或者实际上是被劫持了
程序如果发现境内的服务器发过来的是假包也是会直接丢弃的……所以建议检查下自己的网络

Direct Request 是设计给有系统路由级别代理才启用的……一般启用会导致程序过滤失效
当然不能排除就是因为程序的过滤失效了导致境内 DNS 服务器的回复被程序接受
不过如果用着没事也可以一直用下去，但这个个人觉得只是权宜之计
