### ISSUE TITLE
关于白名单WhiteList.txt的建议

### ISSUE THREAD

**Issue by 5sq** [chengr28/Pcap_DNSProxy#59]
关于白名单WhiteList.txt的建议
最好是直观，便于普通用户添加与删除。对于编程的人来说正则表达式强大方便，但对与一般使用者却比较艰涩。
建议：判断域名的方式，只匹配句号分隔的后两部分。

匹配域名按 . 分隔的后两部分或者整个域名，例子：
baidu.com => *.baidu.com
com.cn => *.com.cn
edu.cn => *.edu.cn
music.163.com => music.163.com

**Comment by chengr28** [comment]
关于这个……正则表达式的功能是非常强大的，然而如果按照你所说只匹配句号分隔的后两部分，这就相当于把一个强大的功能阉割掉了，因为正则表达式和这个是不能互相兼容的。据我所知很多使用者对于 Hosts 规则的灵活性有很高的要求，而正则表达式正好满足了他们这方面的需求

个人建议如有需要使用还是先去看看相关的资料比较好
例如你举的例子 WhiteList.txt 里就有样板 -> `.*\.cn` 匹配所有 `*.cn` 的域名

**Comment by xinhugo** [comment]
@5sq 你所举的例子，白名单已经做了匹配。

「.*\.cn」对应所有 CN 域名。
「.*\bbaidu\.com」对应「baidu.com」和「*.baidu.com」。
「.*\b163\.com」对应「music.163.com」。

在使用这个程序前，我对正则表达式的理解仅仅是听过名字。
至今对它的理解，是通过 *多写、多测试* 得来的。在维护白名单这里，设计到的正则表达式规则并不多，很容易上手的。

如果有什么特别需求，可以提 Issue。
