### ISSUE TITLE
El Capitan Beta 6 无法正常工作

### ISSUE THREAD

**Issue by messiahluo** [chengr28/Pcap_DNSProxy#60]
dig的时候提示找不到服务器，服务正常启动，ChinaDNS可以正常使用。没有找到错误日志。
由于是Beta系统，所以仅供参考。

**Comment by chengr28** [comment]
程序的确是在后台正常运行中吗？使用 `dig @::1 www.google.com` 之类的能不能拿到结果
安装方式是 Homebrew 还是直接下的可执行文件？Homebrew 的配置文件藏得比较深

造成这种情况的可能性，其实还是挺多的……
OS X 的话现在部署用的是 Yosemite 看样子没什么问题 =_/=

**Comment by messiahluo** [comment]
刚又测试了一下，确认是在运行的，Homebrew安装，--HEAD也试过
dig douban.com 正常 dig google.com 出错，电脑网络是连了PPTP的VPN，ping 8.8.8.8 是正常的。

<img width="503" alt="screen shot 2015-08-18 at 12 33 17 am" src="https://cloud.githubusercontent.com/assets/1495875/9310224/17b61596-4541-11e5-92ba-5869b8f4a267.png">

**Comment by chengr28** [comment]
使用 VPN 等路由级别的代理时，请把 Direct Request 改为 IPv4 并重启服务

**Comment by messiahluo** [comment]
原来如此。。多谢，虽然直接 dig 还是拿不到，但是指定域名都能得到结果了。

**Comment by chengr28** [comment]
因为程序一般都是工作在直接与服务器连接的环境里，回复是靠抓包模块抓取的而不是系统的 API
如果挂了路由级别的代理的话，抓包那边就抓不到了，所以就没有结果返回……
Direct Request 就是拿来控制是否使用系统 API 的参数w

**Comment by messiahluo** [comment]
了解，再请教一个问题，Windows上连接VPN之后怎么修改DNS？我连上之后cmd里面nslookup看到是走了本地，但是浏览器好像并没有用这个。

**Comment by chengr28** [comment]
VPN 的话需要修改 VPN 网络适配器的 DNS 参数才能更改
一般 VPN 服务器端会推送过来的……自己改不知道行不行

**Comment by messiahluo** [comment]
OSX是可以的~貌似Win10这个选项按不动OTZ

**Comment by chengr28** [comment]
那可能是被 VPN 软件或者系统默认强制远程服务器决定了……这个貌似没有解决的办法
