### ISSUE TITLE
能否指定某个域名只用境外dns解析

### ISSUE THREAD

**Issue by c1024** [chengr28/Pcap_DNSProxy#61]
目前用Pcap_DNSProxy作为本地dns,但是dl.google.com老是解析到北京去，目前这个谷歌中国ip访问有问题，能否指定dl.google.com用境外dns解析?

**Comment by chengr28** [comment]
先说程序的问题……看到这个问题后去检查了逻辑，发现的确不太完善，所以刚才更新了 0.4.3.2 建议先更新，再配置 Hosts 文件即可强制绕过境内 DNS 服务器解析：
* 如果使用的是 `Local Hosts = 1` 域名白名单列表这种，直接将和 `dl.google.com` 有关的条目删去即可（印象里自带的 WhiteList.txt 里是没有的）
* 如果使用的是 `Local Main = 1` 同时 `Local Routing = 1` 境内地址路由表识别这种，直接在 `[Local Hosts]` 标签下添加 `NULL dl\.google\.com`

再说实际情况……看过 `dl.google.com` 这个貌似 Google Public DNS 和 OpenDNS 如果是用境内的地址去请求解析的话貌似都是拿到北京服务器的……
个人建议如果不想用那些地址，还是写个 Hosts 比较好w

**Comment by xinhugo** [comment]
@c1024 @chengr28 检查发现，白名单有「.*\bdl\.google\.com」这条对应「dl.google.com」的规则。

保留这条规则，似乎并没有坏处。（Google 的程序有数字签名，境内流量速度更快）

**Comment by chengr28** [comment]
@xinhugo 这域名其实不适合加到白名单里的……就算是到处的解析结果都是北京的服务器，但事实上 Google 非 cn 的域名并不属于境内的域名……

**Comment by xinhugo** [comment]
@chengr28 也对，就删除好了。
