### ISSUE TITLE
使用pcap导致上传无速度

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#62]
### 问题描述: 
- 使用pcap以后国内上传速度变的极慢,整体带宽1Mbps都不到
- 然后国外上传速度几乎为0,目前是100%的机率无法成功上传

### 前后情况:
- 一开始使是在imgur上传图片,一直失败,一开始是以为是GFw的关系,没太在意
- 今天在b站上传视频,发现速度很慢,慢的简直离谱,以为运营商偷偷搞限速
- 遂用speedtest测速,一看吓一跳,上传速度俨然回到了电话线时代
![pcap速度测速](http://www.speedtest.net/result/4597125672.png "使用pcap情况下速度测速")
- 然后局端的另一台机子听了也测了一下速,表示毫无问题
![无pcap速度测试](http://www.speedtest.net/result/4597120356.png "未使用pcap情况下速度测速")

### 目前我解决方法:
- 对于国内只用切换无线网卡进行上传
- 对于国外由于墙的存在先通过pcap解析可用的代理服务器地址,连接上后换回自动dns再上传

**Comment by chengr28** [comment]
程序并没有任何代理和干涉网络其它流量的能力……只是一个 DNS 代理。看情况似乎是 CDN 的缘故……使用境外 DNS 解析出来的地址可能并不是最优地址，导致实际与服务器之间的传输的速率比较低。建议打开境内服务器请求功能试试……下次更新可能会默认打开：

**使用境内 DNS 服务器解析境内域名加速访问 CDN 速度功能，选择其中一种方案，配置完成后重启服务：**
* Local Main = 1 同时 Local Routing = 1 开启境内地址路由表识别功能
* Local Hosts = 1 开启境内域名白名单功能

**Comment by muink** [comment]
本地host功能我是开着的
而且edns子网地址也填写了上级网关的网络地址
国内dns是用的路由器和阿里做的解析
按理说只要命中白名单不应该出问题......搞不清
我晚上再做一些测试看看

**Comment by muink** [comment]
@chengr28 不是程序的问题,是局端路由器的原因
测试的时候突然想起来了,去年也遇到同样的情况
使用网线连接路由器的lan端就会导致上传变渣

结合最近下电影,遂停用wifi改用网线连接,时间也对得上

**Comment by chengr28** [comment]
还有这么奇葩的路由器 =_/=
