### ISSUE TITLE
如何更新windows文件夹中的Routing.txt

### ISSUE THREAD

**Issue by uu236** [chengr28/Pcap_DNSProxy#63]
小白一枚，使用Windows 32位操作系统，开启了Local Main=1,Local Routing=1, 求教如何自己去更新routing.txt文件夹的内容，看到最新的更新是7月28日，“https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest”  上最新的是8月30日。

**Comment by yfdyh000** [comment]
得用 Linux 环境（或工具链）运行那串命令，下载和处理数据。
一般不用频繁更新吧，变化没那么快。

**Comment by chengr28** [comment]
`Routing.txt` 里有附带获取的方法，不过需要 Linux 平台的机器，在终端中运行即可：
`curl 'https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{printf("%s/%d\n", $4, 32-log($5)/log(2))}' > Routing_IPv4.txt` IPv4 和 `curl 'https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv6 | grep CN | awk -F\| '{printf("%s/%d\n", $4, $5)}' > Routing_IPv6.txt` IPv6 的中国大陆地址

正如 LS 所说这个列表其实不用经常更新的，新拿到的地址也不是第一时间就会用
项目的话一般是更新程序的时候附带更新一下，上次更新是接近8月的样子
