### ISSUE TITLE
Local Hosts 没有工作

### ISSUE THREAD

**Issue by gaoyan1234** [chengr28/Pcap_DNSProxy#65]
通过抓包软件发现 无论是否开启Local Hosts， 所有的地址都是通过境外的dns 进行解析的

**Comment by 5sq** [comment]
新版我也发现有这个问题。现在只能用

**Comment by gaoyan1234** [comment]
我一般都不这么用，这样做 所有地址都会首先通过国内的解析，天知道如114dns这样的国内公司有没有后台统计你上过哪些敏感网站。

**Comment by chengr28** [comment]
刚才更新的 0.4.3.3 应该已经没问题了……
Local Hosts 主要是牵扯到的地方太多，有时改着改着可能会改坏掉了……貌似是第二次了的样子 =_/=
