### ISSUE TITLE
能否指定DNS查询走代理

### ISSUE THREAD

**Issue by AnyoeDove** [chengr28/Pcap_DNSProxy#67]
Windows7x64 因为在昨晚开始 墙外DNS查询全部time out，导致墙内网站正常、墙外网址全部打不开。
已经测试了https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv 的所有DNS。。

**Comment by chengr28** [comment]
参见 [说明文档](https://github.com/chengr28/Pcap_DNSProxy/blob/Release/Documents/ReadMe(zh_Hans).txt) 对 Direct Request 参数的介绍：

`如需让程序的流量通过系统路由级别的代理（例如 VPN 等）进行域名解析，请选择其中一种方案，配置完成后重启服务：`
`* Direct Request = IPv4`
`* Direct Request = IPv6`
`* Direct Request = IPv4 + IPv6`

`Direct Request - 直连模式，启用后将使用系统的 API 直接请求远程服务器而启用只使用本工具的 Hosts 功能：可填入 IPv4 和 IPv6 和 0，关闭为 0，默认为 0`
`* 建议当系统使用全局代理功能时启用，程序将除境内服务器外的所有请求直接交给系统而不作任何过滤等处理，系统会将请求自动发往远程服务器进行解析`
`* 填入 IPv4 或 IPv6 时将会启用对应协议的 Direct Request 功能，填入 IPv4 + IPv6 将会启用所有协议的功能`

**Comment by 5sq** [comment]
辛苦了，谢谢更新

当前配置
Config.ini

[Local DNS]
Local Protocol = IPv4 + UDP
Local Hosts = 1
Local Main = 0
Local Routing = 0

成功

服务器:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

非权威应答:
名称:    img.alicdn.com.danuoyi.aLiCdN.CoM
Addresses:  118.123.202.250
          125.65.81.150
          118.123.202.240
          125.65.81.140
Aliases:  iMg.aLiCdN.CoM

**Comment by AnyoeDove** [comment]
如果我是用sock5代理呢？例如ss

**Comment by chengr28** [comment]
Socks5 的话现在是没有原生的支持……有考虑是不是可以添加这个功能

**Comment by AnyoeDove** [comment]
好的 明白了
顺带问一句config.ini是否支持#注释 = =因为边看ReadMe边配置是有点不方便 想把一些设置注释写进config.ini里面

**Comment by yfdyh000** [comment]
@AnyoeDove 本质是INI，支持`;`（半角分号）标注注释。

**Comment by AnyoeDove** [comment]
@yfdyh000 OK 谢谢

**Comment by chengr28** [comment]
所有文件都可以 # 开头随便做注释的

**Comment by chengr28** [comment]
刚才的更新已经添加 SOCKS v4/4a/5 的支持了w
