### ISSUE TITLE
有没有使用Lantern的？

### ISSUE THREAD

**Issue by exitwin98** [chengr28/Pcap_DNSProxy#68]
这几天发现家里的Lantern都不能用了，但是办公室的又可以用，

下载了各个版本都无效，包括防止DDos的版本，

猛然想起会不会是自定义DNS的关系，

赶紧改回默认的试了一下（清楚DNS缓存或重启），果然可以了，不知道是什么原因造成的。

6.特别注意：
  * 如需使用境内 DNS 服务器解析境内域名加速访问 CDN 速度功能，请选择其中一种方案，配置完成后重启服务：
    * Local Main = 1 同时 Local Routing = 1 开启境内地址路由表识别功能
    * Local Hosts = 1 开启境内域名白名单功能

两种方法都试过，都不行

附上防DDOS版

https://groups.google.com/forum/?hl=zh-CN#!topic/fqlt/Ca3xJm3_1JU
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
试下蓝灯的防DDoS版（0.0.25），看是否有改善

https://copy.com/4vvvi2jFlddt9jXx/lantern0.0.25_windows.bz2?download=1

Server side of fix for Cf's DDoS protection's false positive
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

**Comment by chengr28** [comment]
这怎么想都是 Lantern 那边的锅……可能他们自己有一套避免 DNS 投毒污染的方法
大概也是本地服务器之类的东西……和程序撞在一起就用不了

**Comment by wongsyrone** [comment]
还不如直接汇报bug到lantern那
