### ISSUE TITLE
关于Pcap Devices Blacklist选项

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#69]
`Pcap Devices Blacklist`选项是匹配符合上面的连接名称还是匹配符合下面的硬件名称的网卡?
![giy](https://cloud.githubusercontent.com/assets/7929014/9714307/b2e979ce-5589-11e5-80ae-238cd4776325.PNG)

**Comment by chengr28** [comment]
说明文档有说明『以抓包模块从系统中获取的名称或简介为准，与其它网络配置程序所显示的不一定相同』就是说以抓包模块而非系统的网络适配器信息为准……建议安装一个 Wireshark

程序主界面上的 Interface List 里的 Description 就是

**Comment by muink** [comment]
Wireshark显示的是连接名称

**Comment by chengr28** [comment]
Wireshark 用的也是 WinPcap 所以 Interface List 里的 Description 显示什么就是什么
