### ISSUE TITLE
新版0.4.3.5 for Windows 使用白名单后

### ISSUE THREAD

**Issue by 5sq** [chengr28/Pcap_DNSProxy#70]
系统windows 10
Config.ini 配置：（原配置没有动，仅修改”Local Hosts = 1“）

[Local DNS]
============================
Local Protocol = IPv4 + UDP
Local Hosts = 1
Local Main = 0
Local Routing = 0

测试
==================================
C:\>nslookup www.google.com
服务器:  pcap-dnsproxy.localhost.server
Address:  127.0.0.1

非权威应答:
名称:    wWw.gOoGlE.CoM
Addresses:  2404:6800:4005:80a::2004
          216.58.221.228

C:\>nslookup www.google.com 114.114.114.114
服务器:  public1.114dns.com
Address:  114.114.114.114

非权威应答:
名称:    www.google.com
Addresses:  2404:6800:4005:808::2004
          216.58.221.68

怎么设置能让使用白名单后，白名单以外的都用国外DNS。
=========================

**Comment by chengr28** [comment]
程序的逻辑并没有问题……白名单启用之后非白名单的域名都是使用境外 DNS 解析的，完全不会联系境内的 DNS 服务器。原因似乎是你的测试并不全面，先看看：

`114.114.115.115 的结果是 -> 216.58.221.132`
`114.114.114.114 的结果是 -> 216.58.221.132`
`8.8.4.4 的结果是 -> 216.58.221.36`
`8.8.8.8 的结果是 -> 216.58.221.100`
`208.67.222.222 的结果是 -> 216.58.221.36`
`208.67.220.220 的结果是 -> 216.58.221.228`

就是说所有列表中的 DNS 解析出来都是这个地址段的地址，并非是只有境内的 DNS 才是
如果你不放心，可以抓个包看看就能搞清楚了

**Comment by 5sq** [comment]
重新测试了几个dns如你如你所言。
