### ISSUE TITLE
FIFO write messages error, error code is 2.

### ISSUE THREAD

**Issue by hongyi-zhao** [chengr28/Pcap_DNSProxy#71]
Pcap_DNSProxy 本来好好的，一次开机后，就不能用了。

启动命令后没有任何反应。

尝试下面的命令，也返回错误：
$ ./Pcap_DNSProxy --flush-dns
FIFO write messages error, error code is 2.

好奇怪的事情，这是怎么回事阿？

**Comment by chengr28** [comment]
errno = 2 应该是 ENOENT 大概是因为主程序并没有在运行中的意思

建议检查是否有 Error.log 生成，或者 SysV/Systemd 或者其它启动的方法有没配置好
最好是配置好重启看看进程是否会自动运行

**Comment by hongyi-zhao** [comment]
没有 Error.log 生成。

另外，我没有用SysV/Systemd 启动，因为没有配置成功。

而是直接启动的原程序的方法使用的。

效果上应该时一样的吧？


另外的问题：


你在service.cpp 中有如下命令：


	#if defined(PLATFORM_OPENWRT)
		system("/etc/init.d/dnsmasq restart"); //Dnsmasq manage DNS cache on OpenWrt, restart it to flush cache.
	#else
		system("service nscd restart"); //Name Service Cache Daemon service
		system("service dnsmasq restart"); //Dnsmasq service
		system("rndc restart"); //Name server control utility or BIND DNS service
	#endif


但是有如下问题：

 1- 如果系统没有安装相应的工具，这些命令会失败。
 2-  rndc restart 这个命令是没有的。目前还没有实现这个 restart 参数。参考我下面的运行结果：


    $ sudo rndc restart
     rndc: 'restart' is not implemented

**Comment by hongyi-zhao** [comment]
进一步测试，遇到的错误各种各样：

$ sudo ./Pcap_DNSProxy --disable-daemon
Failed to restart nscd.service: Unit nscd.service failed to load: No such file or directory.

$ sudo ./Pcap_DNSProxy --flush-dns
FIFO write messages error, error code is 6.

**Comment by wongsyrone** [comment]
写死命令确实不是好做法

**Comment by chengr28** [comment]
效果是一样的……如果运行有问题的确是建议先直接以 ROOT 权限启动程序看看是不是有问题
errno = 6 那个 ENXIO 也是由于程序并没有在前台或后台运行导致的

关于以上你提到终端输出的错误，都是在程序试图清除系统 DNS 缓存的时候碰到的
因为 Linux 不同发行版 DNS 缓存的程序不一样，所以清除的时候只能一网打尽
不过出现此类错误不需要在意，因为程序本身是多线程设计，DNS 缓存清除失败程序也是不会结束运行的，如果是结束运行了那肯定是其它的问题

`rndc` 那个一会儿去查一下，如果的确没有，下次更新会撤掉

**Comment by chengr28** [comment]
@wongsyrone 然而并没有很好清除系统 DNS 缓存的方法……Windows 和 OS X 还好说，Linux 不同发行版之间差异太大，甚至可能连 DNS 缓存都没有，并没有很好的解决方法……

**Comment by wongsyrone** [comment]
有一个比较dirty的办法，将常见几个dns解析器的刷新dns命令写入，同时改成stderr重定向到null，不知道能否检测进程然后发信号给解析器，SIGHUP好像一般都定义为刷新了吧

**Comment by chengr28** [comment]
@wongsyrone 越来越复杂了……其实个人觉得现在这种终端调用 DNS 缓存程序自身参数清除也挺好的，平时以守护进程方式运行的话，输出什么到屏幕都不会看到……

**Comment by hongyi-zhao** [comment]
@chengr28 
尝试了root启动，遇到下面的错误：

  # ./Pcap_DNSProxy --disable-daemon -c /home/werner/software/anti-gfw/anti-DNS-cache-poisoning/dnscrypt-relative/Pcap_DNSProxy/Pcap_DNSProxy.git/Source/Release
Segmentation fault

  # ./Pcap_DNSProxy --disable-daemon -c /home/werner/software/anti-gfw/anti-DNS-cache-poisoning/dnscrypt-relative/Pcap_DNSProxy/Pcap_DNSProxy.git/Source/Release --flush-dns
FIFO write messages error, error code is 2.

**Comment by wongsyrone** [comment]
如果指定的配置文件路径没问题的话，尝试自行编译一下看看

**Comment by hongyi-zhao** [comment]
在 2015年9月22日 下午12:38，chengr28 <notifications@github.com>写道：

> 效果是一样的……如果运行有问题的确是建议先直接以 ROOT 权限启动程序看看是不是有问题
> errno = 6 那个 ENXIO 也是由于程序并没有在前台或后台运行导致的
>
> 关于以上你提到终端输出的错误，都是在程序试图清除系统 DNS 缓存的时候碰到的
> 因为 Linux 不同发行版 DNS 缓存的程序不一样，所以清除的时候只能一网打尽
> 不过出现此类错误不需要在意，因为程序本身是多线程设计，DNS 缓存清除失败程序也是不会结束运行的，如果是结束运行了那肯定是其它的问题
>
> rndc 那个一会儿去查一下，如果的确没有，下次更新会撤掉
>

参考我的系统中给出的帮助信息：

$ sudo rndc --help

给出的部分相关信息：

--------------------
   *restart    Restart the server.

* == not yet implemented
Version: 9.9.5-9-Debian
------------------------------

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chengr28/Pcap_DNSProxy/issues/71#issuecomment-142180150>
> .
>



-- 
Hongyi Zhao <hongyi.zhao@gmail.com>
Xinjiang Technical Institute of Physics and Chemistry
Chinese Academy of Sciences
GnuPG DSA: 0xD108493

**Comment by hongyi-zhao** [comment]
附加说明：
对于rndc来说，应该用下面的命令：
rndc flush

**Comment by hongyi-zhao** [comment]
附加说明：
对于rndc来说，应该用下面的命令：
rndc flush

**Comment by hongyi-zhao** [comment]
@wongsyrone 
我一直都是使用的自己编译的版本。

因为系统时Debian，只能自己编译。

**Comment by chengr28** [comment]
@hongyi-zhao 关于那个 BIND 清空 DNS 缓存的命令，查了 9.2.0 之后的确都换成 rndc flush 了，不过之前的要清除都需要 restart 所以那条旧的命令大概也不会去掉……

**Comment by chengr28** [comment]
git 回来的 `Segmentation fault` 问题也不知道是不是因为那个错误日志输出有问题导致的
最新的版本 git clone 回来貌似没再出现了……
