### ISSUE TITLE
Debian jessie, 使用systemd方法启动Pcap_DNSProxy失败。

### ISSUE THREAD

**Issue by hongyi-zhao** [chengr28/Pcap_DNSProxy#72]
见下面的命令结果：

1- 运行安装脚本的瞬间时可以成功起动的：

     $ sudo bash Linux_Install.Systemd.sh 
      ● Pcap_DNSProxy.service - A local DNS server based on WinPcap and LibPcap
      Loaded: loaded (/etc/systemd/system/Pcap_DNSProxy.service; enabled)
       Active: active (running) since Tue 2015-09-22 08:51:13 CST; 6ms ago
        Process: 1530 ExecStart=/home/werner/software/anti-gfw/anti-DNS-cache-poisoning/dnscrypt-relative/Pcap_DNSProxy/Pcap_DNSProxy.git/Source/Release/Pcap_DNSProxy (code=exited, status=0/SUCCESS)
      Main PID: 1531 (Pcap_DNSProxy)
         CGroup: /system.slice/Pcap_DNSProxy.service
           ‣ 1531 [Pcap_DNSProxy]

2- 但是，随后，程序立刻就自动退出了：

       $ sudo systemctl status Pcap_DNSProxy.service 
      ● Pcap_DNSProxy.service - A local DNS server based on WinPcap and LibPcap
     Loaded: loaded (/etc/systemd/system/Pcap_DNSProxy.service; enabled)
     Active: inactive (dead) since Tue 2015-09-22 08:51:13 CST; 11s ago
      Process: 1530 ExecStart=/home/werner/software/anti-gfw/anti-DNS-cache-poisoning/dnscrypt-relative/Pcap_DNSProxy/Pcap_DNSProxy.git/Source/Release/Pcap_DNSProxy (code=exited, status=0/SUCCESS)
       Main PID: 1531 (code=exited, status=0/SUCCESS)

不知道什么原因。

**Comment by hongyi-zhao** [comment]
已经明白，是config.conf中的下面设定造成的冲突：


Local Hosts = 1
Local Main = 1
Local Routing = 1

使用上面的两种方法之一就可以了，如下：

Local Hosts = 0
Local Main = 1
Local Routing = 1

或者：

Local Hosts = 1
Local Main = 0
Local Routing = 0

**Comment by chengr28** [comment]
配置文件不符合要求或者配置错误是会有 Error.log 生成的

**Comment by hongyi-zhao** [comment]
2015-09-23 12:41 GMT+08:00 chengr28 <notifications@github.com>:

> 配置文件不符合要求或者配置错误是会有 Error.log 生成的
>
>
 1- Error.log 默认保存在什么位置？

我从来没有看到过Error.log 阿。

2- 正常情况下，可否通过参数控制输出详细的运行日志到特定文件，一便于观察运行过程？



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chengr28/Pcap_DNSProxy/issues/72#issuecomment-142489820>
> .
>



-- 
Hongyi Zhao <hongyi.zhao@gmail.com>
Xinjiang Technical Institute of Physics and Chemistry
Chinese Academy of Sciences
GnuPG DSA: 0xD108493

**Comment by chengr28** [comment]
* 刚才花了点时间去看了下……Linux/OS X 版的 Error.log 的确没有输出，似乎是几个月前某个版本开始改了读取文件列表生成方式后就有问题，下次更新的时候会修复……

* 如果能正常输出 Error.log 是保存在与配置文件相同的目录内的，修复之后可以试试故意往配置文件里写几个错误的参数然后运行程序，应该就能看到有输出

* 运行流水日志很久以前有人提议过，后来觉得并没有必要……毕竟只是个中介工具，而且遇到重大出错才会输出错误日志，平常的例如解析哪些域名成功和失败之类的流水时时刻刻都会有，对调试也没什么大的帮助，所以没有添加这个功能

**Comment by chengr28** [comment]
刚才已经更新了新的版本……错误日志输出应该没有问题了w

**Comment by hongyi-zhao** [comment]
2015-09-23 21:20 GMT+08:00 chengr28 <notifications@github.com>:

> 刚才已经更新了新的版本……错误日志输出应该没有问题了w
>
> 好的。我测试一下。


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chengr28/Pcap_DNSProxy/issues/72#issuecomment-142596980>
> .
>



-- 
Hongyi Zhao <hongyi.zhao@gmail.com>
Xinjiang Technical Institute of Physics and Chemistry
Chinese Academy of Sciences
GnuPG DSA: 0xD108493
