### ISSUE TITLE
关于程序的详细参数说明及manpage。

### ISSUE THREAD

**Issue by hongyi-zhao** [chengr28/Pcap_DNSProxy#74]
很奇怪一个事情，在下面的这个网站有Pcap_DNSProxy的非常详细的使用说明：

http://www.lichanglin.cn/防DNS污染工具Pcap_DNSProxy/

而且很多参数的解释，在源码中都找不到。

怎么回事阿？

**Comment by wongsyrone** [comment]
可能那篇文章已经过期

**Comment by hongyi-zhao** [comment]
确实已经过期，它的描述并不是针对最新版本的。

不过确实很详细。


另外，一个需要说明的问题是： 所有的linux/unix 程序最全面的说明都是在manpage/infopage里随软件的发行实时给出。

但是，这个软件并没有这些。各种参数的解释也不详细。

配置文件中也看不到详细的说明，解释。

另一方面，如果想实时的debug，发现那些参数设定有问题，似乎也没有办法。

这会对于用户的使用带来困难。

**Comment by chengr28** [comment]
`本分支 master 为 Pcap_DNSProxy 项目用于存放源代码的分支，可执行编译版本请移步 Release 分支，说明文档参见项目 Documents 文件夹 的内容` -> https://github.com/chengr28/Pcap_DNSProxy/tree/master/Documents

说明文档一直都有。以前是写在 GitHub Wiki 里的，那篇 Blog 应该也是直接抄了 Wiki 的，后来为了统一和方便才只做了 TXT 的一份。顺便 Manpage 之类的应该也不会做了，因为上面有详细的说明，也不是那种比较大型需要安装才能用的软件，或许你一开始可能没注意到……

程序本身是有报错的功能，但是不是那种解析错误之类的运行流水
而是类似无法建立端口或者没有可用网络之类的大错误，会直接输出到 Error.log 文件
当然以终端运行的话也是会直接输出到终端窗口的
在终端中以非守护进程模式运行如果出错应该是有提醒的，没有 Error.log 同时程序没有任何反应地终止只有两个可能性：找不到配置文件，或者有未知的 Bug
