### ISSUE TITLE
Warning: ID mismatch 及相关问题。

### ISSUE THREAD

**Issue by hongyi-zhao** [chengr28/Pcap_DNSProxy#75]
有时候，查询会返回如下的类似结果：

$ dig youtube.com -p6666;; Warning: ID mismatch: expected ID 28000, got 0
;; Warning: query response not set
;; Warning: ID mismatch: expected ID 28000, got 0
;; Warning: query response not set

; <<>> DiG 9.9.5-9+deb8u2-Debian <<>> youtube.com -p6666
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28000
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;YoUtUbE.CoM.			IN	A

;; ANSWER SECTION:
YoUtUbE.CoM.		299	IN	A	216.58.221.142

;; Query time: 201 msec
;; SERVER: 127.0.0.1#6666(127.0.0.1)
;; WHEN: Wed Sep 23 12:35:21 CST 2015
;; MSG SIZE  rcvd: 56

为什么会出现那些警告，是什么原因阿？

**Comment by chengr28** [comment]
关于这个问题，之前测试的时候的确也有出现过，而且都是 dig 在等待程序回复的时候
有时因为网络环境比较恶劣或者断网了，程序这边是不会返回任何解析结果的

不过正常来说都是 Timeout 这个 ID mismatch 也是奇怪，看信息似乎是返回了一个空的数据包
不知道是不是系统里什么机制起了作用……再出现的时候会看看

**Comment by chengr28** [comment]
等了好久没能重现，也检查了很多遍流程也没发现有问题……
不过根据 dig 报错的结果，推测 dig 似乎是收到了内容为空的数据包，而实际上程序是不可能会发送此类没有长度和没有内容的数据包的，所以具体是什么原因不得而知，但是推测可能是和系统会优化同一系统内套接字的传输有关

**Comment by chengr28** [comment]
刚才发了一个新的版本，可以试试……修改了一些可疑的地方
