### ISSUE TITLE
不开启Direct request时，解析总是超时

### ISSUE THREAD

**Issue by LGA1150** [chengr28/Pcap_DNSProxy#79]
使用的 Google Public DNS 8.8.4.4
必须打开Direct request 才能正常

**Comment by chengr28** [comment]
Direct Request 使用的是系统的 API 基本能上网就能用
默认是抓包模块在工作，如果要开启 Direct Request 才能用，那说明抓包模块没有在工作
建议检查一下是不是用的是比较偏门的网络适配器（外置 USB 网卡之类）或者安装一个 Wireshark 看看正在使用的网络适配器名称是不是在 Pcap Devices Blacklist 里面
