### ISSUE TITLE
用此工具在公网建立DNS时，IPv4 EDNS Client Subnet Address怎么填？

### ISSUE THREAD

**Issue by XIAOSpider97** [chengr28/Pcap_DNSProxy#80]
您好！我想用此工具在公网建立一个DNS供几十人使用。
我想开启eDNS，求解IPv4 EDNS Client Subnet Address这栏怎么填...
是填我DNS所在VPS的IP/32，还是填0.0.0.0/0？
谢谢！

**Comment by chengr28** [comment]
其实程序设计是比较贴近客户端而不是服务器端的，并没有测试过能不能作为服务端为复数的人使用……

关于 EDNS Client Subnet Address 这个功能基本也是设计给客户端用的：客户端将自己的公网地址（建议用 /24 或者干脆 /32 因为实际上这里只是确定一个区域，不需要太准确的地址或地址范围）发给服务器
所以理论上如果是在服务器端使用，这个功能是不应该开启的，因为怎么请求域名解析拿到的都只是适合 VPS 的结果而不是客户端的，除非客户端和 VPS 是在差不多的网段内

**Comment by XIAOSpider97** [comment]
感谢回答，看来我理解了，这个程序主要为家庭单独用户设计，他只需要在EDNS加上自己的IP就行了...
关于DNS我提个建议：168.95.192.1或168.95.1.1？使用8888或opendns极易导致akamai被解析到美西，速度极慢...

**Comment by chengr28** [comment]
`IPv4/IPv6 (Alternate) DNS Address` 这几个参数是最主要境外请求用服务器，默认配置的话需要考虑到服务器的承载能力和可靠性之类的情况，选定这几个服务器是稳定性的考虑。如果个人有需要的话，可以修改配置文件里的地址并重启服务即可生效

**Comment by chengr28** [comment]
顺便刚才更新的 0.4.4.2 修改了 EDNS Client Subnet 的转发策略
之前是只要开了就会发送带指定地址的 EDNS Client Subnet 但后来想了下如果真要作为服务器使用，给远程 DNS 回报服务器的地址其实是不对的……所以这版开始就分离了两个部分：
* 如果开启了 `EDNS Client Subnet Relay` 参数，无论地址那边怎么填，只要接收到的请求来自公网地址则以公网地址为 EDNS Client Subnet 信息进行请求，如果是内网地址的请求则回报所填的地址，如果没开这个参数同时没有填地址（默认配置）则等于关闭 EDNS Client Subnet
* 如果没开 `EDNS Client Subnet Relay` 参数但填了地址，则所有信息都会带上填入地址的 EDNS Client Subnet 信息
