### ISSUE TITLE
SOCKS Proxy = 0时报Network Error: Socket connecting error, error code is 10065.

### ISSUE THREAD

**Issue by AnyoeDove** [chengr28/Pcap_DNSProxy#82]
Network Error: Socket connecting error, error code is 10065.
日志只有这一条

配置：
>[Proxy]
>SOCKS Proxy = 0
>SOCKS Version = 5
>SOCKS Protocol = IPv4 + TCP +UDP
>SOCKS Reliable Socket Timeout = 6000
>SOCKS Unreliable Socket Timeout = 3000
>SOCKS UDP No Handshake = 1
>SOCKS Proxy Only = 0
>SOCKS IPv4 Address = 127.0.0.1:1106
>SOCKS IPv6 Address = [::1]:1106
>SOCKS Target Server = 208.67.220.220:443
>SOCKS Username = 
>SOCKS Password =

**Comment by chengr28** [comment]
10065 错误是 No route to host 的意思
请检查你的网络连接是否正常
