### ISSUE TITLE
用Local Main的话,本国DNS被污染解析出的IP如何识别...

### ISSUE THREAD

**Issue by dNEryno** [chengr28/Pcap_DNSProxy#84]
如果用阿里DNS访问ins的话,解析的地址是错的...访问很慢..
本地DNS换为谷歌或者其他的为正常..
所以建议
IPv4 Local DNS Address = 8.8.4.4:53
换为这个...这样子 解析出来的国外地址都是正确的.否则有几率解析出本国地址导致不会再用外国DNS解析一遍了...什么114,阿里基本上国内都试了个遍都不好使...其实谷歌DNS也很少解析国内网站出国了.还不错的..

**Comment by chengr28** [comment]
参见说明文档 https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe(zh_Hans).txt 中对 Local Main 和 Local Routing 以及 IPv4/IPv6 Local DNS Address 参数的介绍，前面那两个参数是互相配合使用的
