### ISSUE TITLE
可否根据解析结果 CNAME 替换地址

### ISSUE THREAD

**Issue by debugzxcv** [chengr28/Pcap_DNSProxy#85]
格式和 Address Hosts 类似:
[CNAME Hosts]
127.0.0.1|127.0.0.2 a.domain
::1 a.domain

  * 解析结果的 CNAME 为 a.domain 时将被替换为 127.0.0.1 或 127.0.0.2
  * 解析结果的 CNAME 为 a.domain 时将被替换为 ::1

**Comment by shuangzhijinghua** [comment]
updated？
2015年10月14日 上午9:36，"debugzxcv" <notifications@github.com>写道：

**Comment by chengr28** [comment]
CNAME Hosts 其实是有计划添加的，不过优先级比较低
毕竟要先解决 Bug 之类的问题，保证程序能正常运行……有空就试试

**Comment by LGA1150** [comment]
同问

**Comment by chengr28** [comment]
刚才更新的 0.4.4.5 已经添加了对 CNAME Hosts 的支持，可以试试w
