### ISSUE TITLE
Local Protocol下UDP和TCP差很多嘛?

### ISSUE THREAD

**Issue by dNEryno** [chengr28/Pcap_DNSProxy#86]
TCP解析有点慢..UDP是不是就可以过滤掉DNS污染了?
我只测试了几个地址,比如ins,twitter.
作者大人说下吧..
用TCP模式,微软支持网站打不开 ..换UDP就很快了.

**Comment by wongsyrone** [comment]
目前tcp查询也开始被干扰了，感觉udp足够了

**Comment by dNEryno** [comment]
TCP 至少我目前测试都还好..没有解析到不正常地址.就是太慢

**Comment by debugzxcv** [comment]
我这里 tcp 查询干扰
```
dig www.baidu.com @8.8.8.8 +vc
;; ANSWER SECTION:
www.baidu.com.          232     IN      CNAME   www.a.shifen.com.
www.a.shifen.com.       299     IN      A       103.235.46.39
```
```
dig admin.youtube.com @8.8.8.8 +vc
;; communications error to 8.8.8.8#53: network unreachable
```

**Comment by angle1895** [comment]
win7是这样查吗？
C:\Users\Administrator>nslookup -vc www.baidu.com 8.8.8.8
服务器:  google-public-dns-a.google.com
Address:  8.8.8.8

非权威应答:
名称:    www.a.shifen.com
Addresses:  180.97.33.107
          180.97.33.108
Aliases:  www.baidu.com

**Comment by chengr28** [comment]
**注意……这个 `Local Protocol` 控制的是请求境内服务器时所使用的协议，而不是请求远程境外服务器时所使用的协议，想要控制后者所使用的协议，请修改 `[DNS]` Tag 下的 `Protocol` 参数**

之前一段时间主要是由于境外的 DNS 服务器丢包比较严重，TCP 由于需要进行握手所以经常拿不到解析结果，用起来效果不是很好。而从上个月开始有部分服务器被完全切断所有 TCP 协议的传输……更不用想可以好好用了
所以默认配置就只启用了 UDP 协议，顺便工具一开始就是可以过滤 UDP 的w

**Comment by dNEryno** [comment]
还好填进列表的时候先用DNSBench测了一遍..
本地协议那里如果填写国内DNS解析出来的国外网站IP五花八门,鹿唇不对马嘴.无奈只能用谷歌DNS先用下了.我这里并没有干扰TCP目前.UDP干扰了.
另外单开EDNS Label = 1 这项有什么用嘛?

**Comment by dNEryno** [comment]
还有dnscrypt 是不是目前DNS方案里面最安全的了?

**Comment by AnyoeDove** [comment]
![question](https://cloud.githubusercontent.com/assets/10519576/10505230/c8c4f81e-733d-11e5-9de3-92bbc4ff8069.png)

nslookup出来是移动的ip....可是阿里的DNS我是填在Local DNS那里的。OpenDNS解析结果正常。OneDNS解析结果居然也正常。。。

**Comment by chengr28** [comment]
* EDNS 的介绍参见 [Extension mechanisms for DNS](https://en.wikipedia.org/wiki/Extension_mechanisms_for_DNS)
* DNSCrypt 协议本身是有强加密的，想要破解现阶段非常困难，所以说是最安全的公共 DNS 方案的确不为过，不过在天朝首要面对的并非安全而是 DPI 深度包检测的问题，而 DNSCrypt 协议本身是非常容易被定点识别和屏蔽的……
* 本工具不能解决路由级别的 DNS 劫持问题。关于移不动的 DNS 劫持之前在 SNS 上我有提到过，由于完全没有收到真正服务器的数据包，所以所有避免投毒污染的方法都是没有用的……
