### ISSUE TITLE
境内备用服务器一直没有工作

### ISSUE THREAD

**Issue by gaoyan1234** [chengr28/Pcap_DNSProxy#87]
更新了最近的版本  发现一个问题，在境内主dns错误的时候，备用dns 一直都是不工作的，nslookup  直接不返回 。从这张统计图中也可以发现  在主192.168.7.1 错误时 备用的114dns 一直就没有工作
![20151015150351](https://cloud.githubusercontent.com/assets/10344954/10506930/5ba2d0c8-734f-11e5-9ff4-3d19265c71b3.jpg)

**Comment by chengr28** [comment]
嗯貌似是之前大修并行请求的时候弄坏掉了……刚才更新的版本已经修复好了
感谢你的反馈w
