### ISSUE TITLE
设置的 Additional Path 失效

### ISSUE THREAD

**Issue by debugzxcv** [chengr28/Pcap_DNSProxy#89]
#### 重现步骤
* 设置文件 `[Base]` 一节 `Additional Path = test`
* 在主程序目录下新建文件夹名为 `test`
* 在 `test` 目录下新建文件 `Hosts.ini`
* `Hosts.ini` 内容如下:
```
[Hosts]
127.0.0.1 www\.baidu\.com
```
* 启动主程序, 查询 `www.baidu.com`

**预期:** 查询结果 A 记录为 127.0.0.1

**实际:** 查询结果 A 记录不为 127.0.0.1

Pcap_DNSProxy_x86 v0.4.4.2
Windows 7

**Comment by chengr28** [comment]
`Additional Path` 参数只支持绝对路径，此处请输入目录的绝对路径
这样做的目的是可以让程序读取其它目录下的配置文件，不一定需要放在程序目录内
