### ISSUE TITLE
关于SOCKS Proxy Only选项

### ISSUE THREAD

**Issue by muink** [chengr28/Pcap_DNSProxy#90]
`SOCKS Proxy Only - 只使用 SOCKS 协议代理模式：开启为 1 /关闭为 0`选项是不是开启全局dns代理?
感觉对选项的解释还是比较少啊

**Comment by chengr28** [comment]
这个和 `DNSCurve Encryption Only` 是一样的意义……就是只使用 SOCKS 协议进行请求，不进行其它协议（包括普通的 DNS 请求）的请求，出来的效果就是全局 SOCKS 协议代理 DNS 的流量
