### ISSUE TITLE
Xubuntu 14.04下跟dnsmasq-base端口冲突的疑问

### ISSUE THREAD

**Issue by yangwe1** [chengr28/Pcap_DNSProxy#91]
启动的时候发现是端口跟dnsmasq的53端口冲突的问题，因为印象中没用过`dnsmasq`，可能是之前用`DNSCrypt`一并装上去的就想卸载，但是卸载里只有`dnsmasq-base`，卸载之后倒是可以启动`PcapDNSProxyService`，然而发现`network-manager`也一并被卸载了，但这样就只能手动配置`interfaces`。想问一下这种情况下有没有更好的做法呢，最好是不用卸载`network-manager`的？

**Comment by chengr28** [comment]
参见 [说明文档](https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe(zh_Hans).txt) 对 `Listen Port` 参数的介绍。比较好的方法是配置程序监听一个不常用的端口做 dnsmasq 的上游服务器，然后在 dnsmasq 中配置目标服务器为程序的监听端口

**Comment by yangwe1** [comment]
噢原来可以这样设置，谢谢
