### ISSUE TITLE
设置Local Main = 1 后所有域名不能解析。

### ISSUE THREAD

**Issue by cielpy** [chengr28/Pcap_DNSProxy#92]
系统：OpenWrt
系统版本：15.05
软件版本：0.4.4.2
现象：默认Config.conf文件，启动后，将所有DNS请求转发到1053端口，所有域名解析正常，然后修改Local Main = 1，保存重启pcap_dnsproxy服务后，所有域名不能解析，Chrome左下角显示正在解析域名...在系统log中看不到有DNS query，而在默认的配置情况下，域名正常解析，系统log中是看得到DNS query的。

**Comment by cielpy** [comment]
在Mac上安装了试了一下 开启Local Main = 1是可以解析的，可能还是OpenWrt版本的问题吧。@wongsyrone

另，在Mac上开启Local Main = 1后试了下解析速度似乎没有快，正常的话114DNS的解析应该在30ms左右，在Mac上试了下130ms左右。

**Comment by wongsyrone** [comment]
libpcap版本是多少，/etc/config/pcap-dnsproxy是否开启，dnsmasq和本程序的全部配置文件

**Comment by cielpy** [comment]
..上午稳定复现的，现在设置一下竟然好了！都能解析了！。。

**Comment by cielpy** [comment]
还有一台昨天折腾的也有这个问题，等会回家了看看，现在这台是没有改什么东西的，怎么就突然好了。

**Comment by cielpy** [comment]
- -刚才电脑DNS设置成了本地的Mac版pcap-dnsproxy，所以可以了，改回路由器还是不行的。
libpcap版本1.5.3-1
/etc/config/pcap-dnsproxy enabled为1
配置文件

https://cloud.githubusercontent.com/assets/3138493/10727297/8f53f1b4-7c13-11e5-8f3a-cd1f2ce26093.png
文件改成zip解压

**Comment by chengr28** [comment]
Error.log 里报了两个错误，建议先试着解决一下：
* 错误代码 125 是 Operation Canceled 估计是多开了程序，程序同一时间只能开启一个
* 第42行的地址格式错误，Local Address 不支持一个参数内写入多个服务器，请将多余的服务器去掉

**Comment by wongsyrone** [comment]
异常多开的程序可以使用 `killall -SIGTERM Pcap_DNSProxy` 发送TERM信号，如果不行换成KILL

**Comment by chengr28** [comment]
关于延迟的问题，建议使用 [DNSPing](https://github.com/chengr28/DNSPing) 工具进行测试。普通的 Ping 只是 ICMP 包基本在 NIC 就能直接处理，只能反映链路的响应速度，不能反映出应用层的响应速度，因为服务器还要花时间找其它服务器进行递归查询或者准备回复客户端的数据

**Comment by cielpy** [comment]
Error.og里的错误是之前的，已经解决了，现在没有Error.log
dig 出现这个错误
![image](https://cloud.githubusercontent.com/assets/3138493/10730511/59e5f726-7c2b-11e5-928d-2af72a23bb0c.png)

**Comment by cielpy** [comment]
同时dig tudou.com是正常的
![image](https://cloud.githubusercontent.com/assets/3138493/10730628/190090d0-7c2c-11e5-8ae0-e20064f76a82.png)
这个是问题所在吗？

**Comment by wongsyrone** [comment]
@cielpy  更了新版，试试吧

**Comment by cielpy** [comment]
刚装了新版，在路由器上用dig命令，试了都可以解析，还没有不可以解析的，然后电脑上很多不可以解析，有的特别慢，Chrome左下角正在解析域名停留几秒中，在路由器上dig一下，电脑上就可以了。。 - -

**Comment by cielpy** [comment]
把路由器搞砖了。。不说了。。哭去了。。

**Comment by cielpy** [comment]
在公司的路由器上试了一下，没有问题了，可能昨天家里的网络的问题吧，晚上回去再试一下。

**Comment by cielpy** [comment]
真是奇怪，公司的极路由(rampis)没问题了，家里这个(ar71xx)始终是有问题的，在路由器上用dig始终返回正确结果，DHCP/DNS设置中DNS转发设置为127.0.0.1#1053，然后连接路由器的设备上，几乎所有域名都不能解析。

**Comment by cielpy** [comment]
系统日志里经常有类似的这条
Thu Oct 29 00:42:43 2015 daemon.info dnsmasq[6701]: reply aPi.tWiTtEr.cOm is NODATA-IPv6

**Comment by wongsyrone** [comment]
去掉IPv6的监听设置和抓包设置等

**Comment by wongsyrone** [comment]
因为每个版本的预编译包都是同一套makefile批量编译的，所以不太可能出现你现在的情况，除非官方SDK有问题，还有其实可以用dnsmasq区分国内外解析的，参考其他网络资料进行配置

**Comment by cielpy** [comment]
我也觉得很奇怪，dig没问题的话应该是解析正常吧？从dnsmasq转发到pcap_dnsproxy并响应这个过程出问题了。

2015年10月29日星期四，Syrone Wong <notifications@github.com> 写道：

**Comment by wongsyrone** [comment]
dig如果没问题说明程序本身是没有问题的，至于和其他程序比如dnsmasq的解析配合问题，需要你查找其他资料进行修复，并不在本 Issue 的讨论范围之内。

**Comment by chengr28** [comment]
`Thu Oct 29 00:42:43 2015 daemon.info dnsmasq[6701]: reply aPi.tWiTtEr.cOm is NODATA-IPv6`
这条是因为 dnsmasq 识别到 api.twitter.com 的域名解析回复里没有 IPv6 的地址，这是正常的，因为这个域名本身就没有 IPv6 地址。当然最终客户端那边能不能获得回复，应该是和 dnsmasq 的配置有关

**Comment by cielpy** [comment]
在系统log里查看，只看到设备发起的query然后forward到127.0.0.1，并没有reply，想问下pcap_dnsproxy的log在哪里？或者dug模式什么的？

**Comment by wongsyrone** [comment]
@chengr28  运行日志貌似没有吧，只有错误日志
@cielpy  你在dnsmasq.conf 中加入 `no-resolv` 并且加入`server=127.0.0.1#1053`看看dnsmasq的运行日志是否有反应。

**Comment by chengr28** [comment]
流水日志之前有人提到过，但是考虑了觉得并没有什么必要……

**Comment by cielpy** [comment]
我现在用这个是正常的，query forward然后reply，正常流程，家里那台就只有前两个了，想看看为什么没有reply。。无从查起啊。。。
no-resolv 并且加入server=127.0.0.1#1053 这个和在Luci里勾选忽略配置文件然后在DNS转发填上127.0.0.1#1053的作用是相当的吧？

**Comment by wongsyrone** [comment]
别用luci了，直接用配置文件吧，把luci的设置还原。

**Comment by cielpy** [comment]
Luci有bug?我昨天到是想试一下改dnsmasq.conf，想了下不一定支持非标准端口那种写法，这个想法就闪了一下就过去了没尝试，晚上回去试一下吧。

**Comment by cielpy** [comment]
理论上来说，如果dnsmasq转发请求到pcap_dnsproxy，而pcap_dnsproxy正常运行，这样肯定会有reply的吧？如果没有reply的话，从dnsmasq转发到pcap_dnsproxy这个过程就出问题了。可能还是设置问题。都是从OpenWrt默认的配置改的，发动的地方也不多，想不到哪里会出问题。

**Comment by wongsyrone** [comment]
如果dnsmasq配置文件如果没有带 `all-servers`参数会按照配置文件中的上游服务器列表顺序进行请求，接收最先的回应，后面的回应会被忽略，如果没有 `no-resolv` 参数，就会从系统的resolv.conf中读取server值，一般是ISP提供的。其余的去看dnsmasq的manpage

**Comment by cielpy** [comment]
用ChinaDNS的时候就是这样用的，同样的配置只把1053改成ChinaDNS的端口就能用，换成pcap_dnsproxy的1053端口就不能用。。见鬼。

**Comment by cielpy** [comment]
还是折腾不好。大量这种日志。
![image](https://cloud.githubusercontent.com/assets/3138493/10820715/b06d22e4-7e89-11e5-8f39-1bceacebace3.png)

开了ChinaDNS，把dnsmasq.conf里server=127.0.0.1#1053改成server=127.0.0.1#5353好了。期间把ChinaDNS的上游改成pcap_proxydns的1053端口也是不行，改成8.8.8.8可以了。不知道为什么。先用ChinaDNS吧。

**Comment by cielpy** [comment]
总觉得，是pcap_proxydns接收DNS转发的时候有问题.，直接用作53端口是没问题的。
因为不知道从哪下手找问题，只能靠猜。试验了一下，仅供参考。
我把dnsmasq的端口改成53以外的任意端口，并次pcap_dnsproxy端口改为53，然后下发192.168.1.1为DNS到各个客户端，dnsmasq.conf里加上no-resolv和
server=127.0.0.1#53，阻止路由器获取ISP的DNS，强制只使用127.0.0.1的53端口也就是pcap_proxydns，这样是可以的，都能解析了。
但是这样又解释不了为什么在另外一台路由器上转发到pcap_dnsproxy是可以的。

**Comment by cielpy** [comment]
@chengr28 关于解析速度问题，dig的Query time结果应该能反应出来解析速度吧？
