### ISSUE TITLE
干嘛用114做默认dns,经常解析4399出错.

### ISSUE THREAD

**Issue by viewtheard** [chengr28/Pcap_DNSProxy#93]
干嘛用114做默认dns,经常解析4399出错.换了个无污染的dns就好了,花了我半年时间才查出来问题.建议作者修改默认的dns,让别人少走弯路.

**Comment by chengr28** [comment]
首先需要说明的是，默认配置 114DNS 只是 **境内的默认服务器** 而不是全局默认服务器，全局默认服务器是没有 Local Address 那几个，而且境内域名请求 **默认还是没有开启的**

至于首选服务器使用 114DNS 是稳定性和可靠性的选择，或者换句话，境内的 DNS 服务器除了 114DNS 还有哪个稳定性、准确性、可靠性和性能是能赶上 114DNS 的？境内服务器的作用纯粹是为境内域名提供 CDN 服务而已，本身并不是主要在使用的 DNS 服务器，这点需要搞清楚

**Comment by viewtheard** [comment]
登录后换小号会跳转网页到首页,比如http://s3.ddt.qq933.com/Default.aspx?user=张三 .....
会经常跳转到www.4399.com,一旦出现该情况短期内再也登录不进去了反复跳转.

**Comment by viewtheard** [comment]
Local Main = 1 同时 Local Routing = 1,既然能加速境内访问,不考虑默认开启是何原因阿

**Comment by chengr28** [comment]
4399 那个应该不是 DNS 的问题……当然每个网站有每个网站自己的策略，这个不好说
至于为什么不默认启用境内域名查询，因为这个方法现阶段虽然还是比较可靠的，但是有时还是会被投毒污染成功的例子，事实上之前就有收到过反馈说是用境内的地址进行投毒污染的，所以才没有默认启用
