### ISSUE TITLE
设置Local Main = 1 Local Routing = 1 时遇到的问题求解

### ISSUE THREAD

**Issue by hocoo** [chengr28/Pcap_DNSProxy#94]
本机系统WIN10。下载的最新版Pcap_DNSProxy
config.ini配置如下：
[Base]
Additional Path = C:\Pcap_DNSProxy-Release\Pcap_DNSProxy-Release\Windows
[Local DNS]
Local Main = 1
Local Routing = 1
[Addresses]
IPv4 DNS Address = 118.69.72.1:53(这个DNS是错误的，以便测试)
IPv4 Alternate DNS Address = 
IPv4 Local DNS Address = 114.114.115.115:53
IPv4 Local Alternate DNS Address = 223.6.6.6:53
.
其它配置项、条目默认。
![default](https://cloud.githubusercontent.com/assets/15389153/10836878/e7eb44f8-7eed-11e5-909a-8fbc7bc661ef.JPG)
运行NSLOOKUP命令如图。尝试在Routing.txt文件中加入：
216.58.221.0/23
这个IP段，运行结果一样。
我的理解是所有请求应该经由IPv4 Local DNS Address，命中路由表后直接返回结果，为何在Routing.txt文件中加入了IP段依然time out?
如果在IPv4 DNS Address中写入正确的DNS，则可以返回结果，但是被污染的。结论是IPv4 Local DNS Address 没有起作用。为何会这样？

**Comment by chengr28** [comment]
其实这个并不是因为 Local DNS 没有起作用，而是因为程序在读取 IPv4 的 CIDR 路由表时有错误，导致读取到的是错误的路由表，所以实际识别的时候没有命中
刚才的更新已经修复这个问题，可以试试新的版本w
