### ISSUE TITLE
安装在OpenWrt上，解析时间很长，大概要2-4秒，很少有感觉不到有解析过程就解析完的域名。

### ISSUE THREAD

**Issue by cielpy** [chengr28/Pcap_DNSProxy#95]
比如，先flush，然后打开QQ空间的时候，就将近3秒钟。这个时间太长了吧。。
打开了
Local Main = 1
Local Routing = 1

本地部署的不会这么长时间。
![image](https://cloud.githubusercontent.com/assets/3138493/10851566/c6db95e6-7f66-11e5-8700-ee5b57904dbe.png)

**Comment by wongsyrone** [comment]
在我这并没有问题，直接dig的是走dnsmasq，设置它的上游DNS只有127.0.0.1#1053

```
root@OpenWrt:~# dig ptlogin2.qq.com

; <<>> DiG 9.9.7-P3 <<>> ptlogin2.qq.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27877
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ptlogin2.qq.com.               IN      A

;; ANSWER SECTION:
ptlogin2.qq.com.        30      IN      A       123.151.152.48
ptlogin2.qq.com.        30      IN      A       123.151.10.167

;; Query time: 36 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Oct 31 07:51:52 CST 2015
;; MSG SIZE  rcvd: 76

root@OpenWrt:~# dig ptlogin2.qq.com @127.0.0.1 -p 1053

; <<>> DiG 9.9.7-P3 <<>> ptlogin2.qq.com @127.0.0.1 -p 1053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53430
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;PtLoGiN2.qQ.CoM.               IN      A

;; ANSWER SECTION:
PtLoGiN2.qQ.CoM.        258     IN      A       123.151.152.48
PtLoGiN2.qQ.CoM.        258     IN      A       123.151.10.167

;; Query time: 130 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Sat Oct 31 07:52:33 CST 2015
;; MSG SIZE  rcvd: 76
```

**Comment by cielpy** [comment]
我是在电脑上dig的，上游已经设置为1053端口。

**Comment by cielpy** [comment]
算了，放弃了，继续用pdnsd了。

**Comment by wongsyrone** [comment]
今晚发一个新版，到时候再试一下吧www

**Comment by cielpy** [comment]
好。

**Comment by wongsyrone** [comment]
刚上传完，估计待一会就可以下载了

**Comment by cielpy** [comment]
一会儿就到家了。

2015年11月3日星期二，Syrone Wong <notifications@github.com> 写道：

**Comment by cielpy** [comment]
![image](https://cloud.githubusercontent.com/assets/3138493/10908168/a861a0d6-826a-11e5-86c3-c262d3075963.png)
NAND版本没更新，我自己编译了一个先安装了。

**Comment by wongsyrone** [comment]
多谢反馈，已经加上了

**Comment by cielpy** [comment]
还是不行- -端口改成pdnsd的就行了。

**Comment by wongsyrone** [comment]
`opkg install tcpdump`安装之后抓一下包然后发上来，这样好分析问题出在哪里

**Comment by chengr28** [comment]
或者这样吧……可以先试试在 Linux 桌面端装个 Wireshark 并以 ROOT 权限开启抓包，然后 dig 一下 OpenWrt 上 Pcap_DNSProxy 开的端口，这样绕过了 dnsmasq 就可以测试 OpenWrt 上的程序是否在正常工作

**Comment by cielpy** [comment]
现在是，启动不起来了。。
start没反应，没Error.log，系统日志也没有反应。这两天用的dnscrypt-proxy启动提示
root@OpenWrt:~# /etc/init.d/dnscrypt-proxy start
/usr/sbin/dnscrypt-proxy: can't load library 'libsodium.so.13'
是不是pcap_dnsproxy也不能加载这个library？刚才没升级1.0.6的时候还没有这个，现在提示找不到library。降到1.0.5也不行。

**Comment by cielpy** [comment]
恢复出厂重新安装可以运行了。
现象还是部分域名不能解析，能解析的域名很慢，在路由器上dig @127.0.0.1 -p 1053 domain.com正常，速度正常，在电脑上dig @192.168.1.1 -p 1053 domain.com 不能正常解析
dnsmaqs.conf就只有这些。
![image](https://cloud.githubusercontent.com/assets/3138493/10909923/31ebfad4-8277-11e5-974b-99fbcf200158.png)

**Comment by cielpy** [comment]
Wireshark我玩不太转，要不你远程看一下？

**Comment by wongsyrone** [comment]
如果在dnsmasq中指定了上游服务器的话，在电脑上就不能再dig 1053端口了
在上面的conf文件中加上 `all-servers`
贴出 /etc/resolv.conf; /etc/config/network的内容，个人信息抹掉

**Comment by cielpy** [comment]
all-servers已加
![image](https://cloud.githubusercontent.com/assets/3138493/10910303/a1287826-8279-11e5-9016-2eda1f87ec8e.png)
![image](https://cloud.githubusercontent.com/assets/3138493/10910308/a66954c2-8279-11e5-915b-da67c3453123.png)

**Comment by cielpy** [comment]
![image](https://cloud.githubusercontent.com/assets/3138493/10910323/c22b10f6-8279-11e5-9844-4a423a320af2.png)

**Comment by chengr28** [comment]
Wireshark 其实很简单的……OS X 的话去官方网站下个 dmg 装上就行，一般是选 eth0 按一下绿色的按钮直接开始抓，然后 dig 去路由器并等待 dig 返回结果或者超时，再按红色的停止抓包按钮并保存结果就行
[OpenWrt 上的 tcpdump 更简单](http://demon.tw/hardware/openwrt-tcpdump.html)……直接输一条命令就能开始抓，然后这边 dig 一下，停止抓包保存结果就行……

**Comment by wongsyrone** [comment]
在/etc/config/network的wan配置项下面加上
        option peerdns '0'
        option demand '0'
        option mtu '1500'  <<<<----这个如果不确定就不要加了
        option dns '127.0.0.1'

**Comment by cielpy** [comment]
OK，软件有装，保存直接上传结果就行了是吧。

**Comment by cielpy** [comment]
![dns](https://cloud.githubusercontent.com/assets/3138493/10910565/fdc92070-827a-11e5-8954-96ba9b07e84c.png)
扩展名改成pcapng

**Comment by chengr28** [comment]
OK 收到了……从 OS X 上抓包的结果来看路由器那边完全没有回复呢
不知道是程序没有收到还是说发送的过程有问题

试试 `dig +vc @192.168.1.1 -p 1053 domain.com` 看看 TCP 的端口有没有反应

**Comment by cielpy** [comment]
![all](https://cloud.githubusercontent.com/assets/3138493/10911246/e46d8c3e-827e-11e5-9294-e964653314a5.png)
上面是在路由器上用tcpdump -i any -w all.cap命令得到的结果
第一用dig @192.168.1.1 -p 1053 music.163.com 超时无结果
第二次用dig +vc @192.168.1.1 -p 1053 music.163.com 正常返回结果
而且。。dig +vc所有域名正常返回。。我试了加vc参数还没有一个失败的。

**Comment by cielpy** [comment]
也就是TCP模式正常，UDP不行？。。

**Comment by cielpy** [comment]
试了下，dnsmasq转发到pcap_dnsproxy端口，直接在电脑上dig domain.com不指定到路由器的1053端口，不行，加上+tcp选项，都可以。

**Comment by cielpy** [comment]
。。。。把pdnsd的上游设置成了pcap_dnsproxy，然后dnsmasq上游设置为pdnsd，pdnsd用tcponly方式请求pcap_dnsproxy，能用- -先用着。

**Comment by wongsyrone** [comment]
@cielpy 我记得你之前说过你有两个路由吧，一个是ar71xx nand，另一个是ramips对么，在ramips上运行没问题，而另一个就有问题是么

**Comment by cielpy** [comment]
@wongsyrone 之前反馈的时候，在ramips上离奇的是好的，后来观察其实也有相同症状，那一会儿不知道为什么是好的。

**Comment by cielpy** [comment]
TCP模式正常，UDP不行，问题在这吧？我现在是用pdnsd，上游是Pcap_dnsproxy，两个都是这样用的。

**Comment by wongsyrone** [comment]
诶，我以为找到问题症结了，因为ramips是mipsel是little endian，而ar71xx nand是mips是big endian，因为之前 @chengr28  和我提到过貌似对大小端考虑不周全，听你这样说可能不是这里的问题

**Comment by cielpy** [comment]
我明天再测试一下，然后再反馈一下吧。ar71xx上是不行，rampis我明天再确认下。

**Comment by wongsyrone** [comment]
如果确认的话编译主项目最新commit吧，OP的因为目前这个问题没有进行更新

**Comment by cielpy** [comment]
好。
问题不应该是在接收UDP类型的请求这里吗？也就是客户端用UDP方式请求dnsmasq，dnsmasq转发到Pcap_dnsproxy，然后接收到，再就没有响了。

现象就是在电脑上直接dig @192.168.1.1 -p 1053 domain.com不会响应
加上tcp选项，也就是dig @192.168.1.1 -p 1053 +tcp domain.com就完全正常。

**Comment by wongsyrone** [comment]
这个可能是dnsmasq的几个设置引起的，比如：
1. 重绑定保护（丢弃RFC1918上行响应数据）
2. 过滤本地包（不转发反向查询本地网络的Lookups命令）
取消这两个在LuCI中的选项试试

**Comment by cielpy** [comment]
![image](https://cloud.githubusercontent.com/assets/3138493/11062934/109c0208-87ee-11e5-9102-687dd50072ce.png)
这两个吗？关了不行。还是那个现象。

**Comment by wongsyrone** [comment]
另一个在高级设置里面，关了之后也不行么

**Comment by cielpy** [comment]
![image](https://cloud.githubusercontent.com/assets/3138493/11063082/18443434-87ef-11e5-8431-ea74a10f5d7c.png)
也关了，不行。

**Comment by cielpy** [comment]
编译了最新的包，启动不起来- -  
先提示 Pcap_DNSProxy started successfully
紧接着就提示Pcap_DNSProxy is already running

restart的时候只提示Pcap_DNSProxy started successfully 没有提示 Pcap_DNSProxy terminated successfully

**Comment by wongsyrone** [comment]
之前0.4.4.3正常么，因为并没有改init脚本

**Comment by cielpy** [comment]
重新安装了 pcap-dnsproxy_0.4.4.4-1_ramips_24kec.ipk 重启路由后正常了。额，本来用的就是这个版本，用了好几天了。

**Comment by wongsyrone** [comment]
编译最新的需要你改 https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/blob/master/Makefile#L16 这行为 `9e73c3460f4a711318205619ef7c8fe72dab1ef9`

**Comment by cielpy** [comment]
我刚才改成了最新的commit

**Comment by cielpy** [comment]
用9e73c3460f4a711318205619ef7c8fe72dab1ef9编译也不行，一样的情况。

**Comment by wongsyrone** [comment]
@cielpy 
尝试一下把服务器IP换成网关IP，比如`server=192.168.1.1#1053`而不是`server=127.0.0.1#1053`

**Comment by cielpy** [comment]
还是不行。

**Comment by hero18688** [comment]
这个对比老久没更新的pdnsd怎么样

**Comment by chengr28** [comment]
在别的 Issue 讨论忽然想起……不知道题主在程序运行时是否有在 OpenWrt 上运行其它代理工具，例如 VPN 等导致程序的抓包模块没有正常在工作？

**Comment by chengr28** [comment]
@hero18688 和本 Issue 不相关的文件建议开新的 Issue 讨论
不过关于这个问题似乎并没有意义……就像是在问 Windows 和 OS X 两个操作系统有什么不一样一样，各有各的优点和缺点而已……或许我这个只是个人的工具，水平不高吧笑

**Comment by cielpy** [comment]
没有跑过 VPN，只跑了 ss和 DNS相关的服务，当时可能还有 pdnsd 什么的。记不太清楚了。
