### ISSUE TITLE
如果收到reset包打开空白页,应该调整哪个参数?

### ISSUE THREAD

**Issue by viewtheard** [chengr28/Pcap_DNSProxy#96]
如题

**Comment by chengr28** [comment]
不太清楚你说的 RESET 包指的是哪里的 RESET 包。如果是用 TCP DNS 查询模式收到的 RESET 包，那么程序会自动切换到其它查询方式，但如果是打开的网页被 RESET 那么这个就不是 DNS 的范畴了，你应该使用代理工具打开网页
