### ISSUE TITLE
Tomatoware ARM 下静态编译以及一些疑问

### ISSUE THREAD

**Issue by rampageX** [chengr28/Pcap_DNSProxy#97]
使用 Tomato 固件，先下载 tomatoware ( https://github.com/lancethepants/tomatoware ) ，然后自己编译下 CMake 和 libsodium，这里一般没什么问题，带上 tomatoware 的安装目录就行：

CMake：
./bootstrap --prefix=/mmc && make && make install

libsodium：
./configure --prefix=/mmc && make && make install

然后静态编译 Pcap_DNSProxy，需要修改下源码的 /Pcap_DNSProxy/Source/Pcap_DNSProxy/CMakeLists.txt 文件：

#Executable file name
#static
SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
SET(BUILD_SHARED_LIBRARIES OFF)
SET(CMAKE_EXE_LINKER_FLAGS "-static -pthread -Wl,--whole-archive -lpthread -Wl,--no-whole-archive")
#static
add_executable(Pcap_DNSProxy ${MAIN_SRC_FILES})
IF(PLATFORM_OPENWRT)
	INSTALL(TARGETS Pcap_DNSProxy RUNTIME DESTINATION sbin)
ENDIF(PLATFORM_OPENWRT)

当然还是希望作者加一个静态编译的开关选项。

我仔细看过项目的 readme 文件，还是没搞懂 Pcap_DNSProxy 的解析流程，想请问下 @chengr28 ：
1. 如果已经支持并启用国内路由表，那么压缩指针和抓包的意义是？一个补充？抓漏网之鱼？
2. 非标端口服务器，Socks/HTTP 代理远程解析，DNSCurve（我没看错就是一个 dnscrypt-proxy 的客户端）都可以用来避规 DNS 污染，而且本软件都支持，那它们在软件中的解析优先级/顺序是？还是不在国内路由表中的，或者抓包判断受污染的域名，会并发向这几种方式发请求，谁先应答取谁的结果？
3.国内域名CDN加速保证是完全依赖路由表还是EDNS或者其他？

谢谢！

**Comment by houzi-** [comment]
@rampageX 不知道LZ编译的是否运行正常？

**Comment by wongsyrone** [comment]
我建议参照 http://stackoverflow.com/questions/7101862/want-to-make-standalone-program-with-cmake 使用：
我不太清楚tomato的编译环境会不会给cmake传入CMAKE_EXE_LINKER_FLAGS参数，所以最好不要直接覆盖传入参数，而是附加在后面，这样应该比较好。

set(CMAKE_EXE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS} "-static")

因为这个项目并不涉及自己的库，所以下面这个可以去掉
BUILD_SHARED_LIBS: Global flag to cause **add_library** to create shared libraries if on.

**Comment by chengr28** [comment]
Tomatoware ARM 的静态编译问题可能还需要再看看。关于下面的几个问题：
* 本身程序一开始是只有抓包过滤模块的，境内路由表和压缩指针是后来才加进去。至于为什么要加这么多功能，原因是项目本身的意义就是想给用户多一个选择。不过境内路由表和压缩指针貌似是两个不互相冲突的功能？主要是看用户是怎么配置自己的解析方案
* 解析的顺序：DNS 缓存 - 境内服务器 - （压缩指针修改） - SOCKS/HTTP - 代理直连 - DNSCrypt - TCP - UDP 抓包。这里是按顺序而不是并发的，任意过程都可以随便开关以决定是否启用，有过程解析成功就终止请求返回结果不会进行下一步解析，也是看用户是怎么配置自己的解析方案
* 境内域名 CDN 依靠的是境内服务器+境内路由表，和 EDNS 并没有关系，当然如果境外的服务器对天朝的网络有很好的 CDN 支持也就不需要这个功能了。境内路由表主要是用于过滤境内 DNS 的投毒污染，CDN 实际上是 DNS 服务器而不是程序在做，其它域名解析过程并不会使用

**Comment by rampageX** [comment]
@chengr28 感谢您的解答！

**Comment by rampageX** [comment]
@houzi- 运行没什么问题

@wongsyrone @chengr28 单独只加 -static 参数，程序 -v 这些自检运行没问题，但是一旦正式解析会提示出错：

`terminate called after throwing an instance of 'std::system_error'
what(): Enable multithreading to use std::thread: Operation not permitted`

我也是 google 了一下才解决的。

Tomato ARM 如果用 Shibby 的 AIO 版本，libsodium 库是有的（因为它集成了 dnscrypt-proxy），libcap 则需要自己装 Entware 后用 opkg 手动安装。所以编译一个静态版本方便一些。

**Comment by wongsyrone** [comment]
那条参数只是个示例，如果需要什么就补充什么

**Comment by houzi-** [comment]
@rampageX不知道lz能否提供一下你编译的版本出来，我自己交叉编译运行不到几分钟就会闪退！是在tomato_arm shibby 上的运行的

**Comment by rampageX** [comment]
@houzi- 链接: http://pan.baidu.com/s/1hqtZZ9M 密码: 9fem

**Comment by wongsyrone** [comment]
根据上面的信息拟添加

```diff
--- a/Source/Pcap_DNSProxy/CMakeLists.txt
+++ b/Source/Pcap_DNSProxy/CMakeLists.txt
@@ -80,6 +80,12 @@ IF(ENABLE_LIBSODIUM)
        add_definitions(-DENABLE_LIBSODIUM)
 ENDIF(ENABLE_LIBSODIUM)
 
+# Link to static libraries if needed
+IF(STATIC_LIB)
+       SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
+       SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static -pthread -Wl,--whole-archive -lpthread -Wl,--no-whole-archive")
+ENDIF(STATIC_LIB)
+
 # Executable file name
 add_executable(Pcap_DNSProxy ${MAIN_SRC_FILES})
 IF(PLATFORM_OPENWRT)
```

根据 https://cmake.org/pipermail/cmake/2001-June/059137.html 的信息，BUILD_SHARED_LIBRARIES已经被废弃，BUILD_SHARED_LIBS根据上面的解释应该也不需要。

给CMake传入 `-DSTATIC_LIB=ON`应该就可以了，如果没有异议并且编译测试正常的话就可以commit了。

**Comment by houzi-** [comment]
@rampageX thanks! 应该是交叉编译器的问题，我使用的是bcm53xx的toolchain,无奈tomato-arm 提供的toolchian gcc版本太低！不知道tomato-arm在路由器上编译要多久？重来没试过tomato-arm

**Comment by houzi-** [comment]
@rampageX
tomatoware-mipsel 的gcc version升级到5.2.0，跟entware-ng，lz可以编译个mipsel试试！
