### ISSUE TITLE
更新路由表时下载未完成就开始更新路由表了

### ISSUE THREAD

**Issue by AnyoeDove** [chengr28/Pcap_DNSProxy#98]
![bug](https://cloud.githubusercontent.com/assets/10519576/10966871/7707e530-83f1-11e5-9dda-de2069fd10d7.png)

**Comment by chengr28** [comment]
这个并非下载未完成就开始更新路由表，而是因为 cURL 下载的时候遇到错误导致下载未完成便中断掉了，而批处理的话是一步一步向下执行的，下载完开始处理数据是正常的流程
建议检查一下是否为网络问题
